### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#1]
Probably use Tipue.

If `include_search` is set needs to generate the compiled index javascript file.

Also *if* the theme includes a search.html page that should be rendered and included.

**Comment by kyub** [comment]
Awesome! Merge please guys. :)

**Comment by d0ugal** [comment]
See #457. This is done!

**Comment by tobegit3hub** [comment]
Great job @d0ugal :+1:

**Comment by zx2c4** [comment]
What about making this optional?
