### ISSUE TITLE
Invoke external ->html or ->md tools

### ISSUE THREAD

**Issue by memeplex** [mkdocs/mkdocs#1000]
Maybe this will be better covered by the new plugin api, but it would be very useful to have a simple hook to call external tools like pandoc or nbconvert (currently I'm calling nbconvert using my own watchdog to convert python notebooks to markdown). If the plugin api will take too long to be stabilized, could you add a trivial extension->external tool map to the configuration. I think Pareto principle applies here.

**Comment by waylan** [comment]
As stated [here][1]:

> ...  we have a planned way for people to alter the behavior of MkDocs: the Plugin API. We have no interest in adding a similar feature separate from the Plugin API. When the Plugin API is added, then we would need to maintain two ways to accomplish the same thing, which is not reasonable. In other words, if you want to do the work to provide a way to alter MkDocs behavior, your time would best be spent on the Plugin API. ... until we have a clearly defined Plugin API, the assumption will be that all customization not already implemented will be deferred to the Plugin API.

[1]: https://github.com/mkdocs/mkdocs/pull/970#issuecomment-227870921

**Comment by memeplex** [comment]
Seems fair enough to me, I will just keep a patched fork for the time being and wait for the plugin api to find its way into master.
