### ISSUE TITLE
Linking without giving a title

### ISSUE THREAD

**Issue by Xemiru** [mkdocs/mkdocs#1001]
Not sure how else to best explain it in a way that'd fit in the title, but basically, I'm looking to not have to write something like this:

```
* [http://lua-users.org/](http://lua-users.org/)
```
just to resolve to [http://lua-users.org/](http://lua-users.org/). A nice solution would be being able to simply not provide a title at all, defaulting to the link itself.

```
* [](http://lua-users.org/)
```

Pretty small change.

**Comment by waylan** [comment]
Sounds like you are looking for Markdown's [automatic links][1]. Like this:

    <http://lua-users.org/>

[1]: http://daringfireball.net/projects/markdown/syntax#autolink

**Comment by Xemiru** [comment]
oh ok thanks
