### ISSUE TITLE
Page Order get Shuffled when no `pages configuration` is found

### ISSUE THREAD

**Issue by SusanthCom** [mkdocs/mkdocs#1005]
`pages configuration` :  If not provided, the pages configuration will be automatically created by discovering all the Markdown files in the documentation directory.

This is really hand feature 👍  especially when having more documents.

* **The Page order get shuffled, when the files are renamed**. It is not alphabetically listed 👎 . It will be good, if the pages are always listed in alphabetically sorted on their file names. 

* In current implementation, Directories are listed after files. Even if we rename directory, it is consistently listed in alphabetic order ! 👍  Thats good. 

* It will be nice, if we have an `option` in config file to **list directory first** instead of default order ( after files).

* If `pages configuration` is provided, it skips auto listing. If there is an  `option` in config file to **force auto listing**, it brings good of both worlds (manual + auto). That is, do as per instructed in `pages configuration` for the files mentioned in it and continue with auto listing for files not mentioned in `pages configuration`. This is handy when there are large number of documents and prefer manual listing control for few files and auto listing for remaining.

Thank you

**Comment by waylan** [comment]
> * The Page order get shuffled, when the files are renamed. It is not alphabetically listed :-1: . It will be good, if the pages are always listed in alphabetically sorted on their file names.

They should be. Can you provide an example where this fails?

> * It will be nice, if we have an `option` in config file to list directory first instead of default order ( after files).

> * If `pages configuration` is provided, it skips auto listing. If there is an `option` in config file to force auto listing, it brings good of both worlds (manual + auto). 

Those both sound like they may be candidates for a plugin (see #206).

**Comment by SusanthCom** [comment]
@waylan  Thanks.

Let me try to recreate....

There are some live update issue. That means, when file system is updated while server is running, new changes not reflected immediately. some times refreshing browser too shows same old contents.

But once Once the server is restarted, it appears to be ok now. Let me try to recreate the issue ... will update soon.

**Comment by SusanthCom** [comment]
Browser Output
![_browser-out](https://cloud.githubusercontent.com/assets/11663470/17225218/a160aa22-5521-11e6-8deb-72e5b0cb19f4.png)

Docs Folder Contents
![_docs-contents](https://cloud.githubusercontent.com/assets/11663470/17225219/a1cbf2d2-5521-11e6-839c-7d37bb6ff3f9.png)

This is current state. I restarted server several times. still it shows like this. ( If sorted, `Sopen` should come before `Test` )

**Comment by rickpeters** [comment]
there is a difference between lower and uppercase? I'm not sure is mkdocs sort is case-insensitive...

**Comment by SusanthCom** [comment]
@rickpeters accidently i found this mismatch. Let me close monitor and figure out to re create.

**Comment by waylan** [comment]
@rickpeters is correct:

```python
>>> lst = ['a', 'b', 'A', 'B']
>>> lst.sort()
>>> lst
['A', 'B', 'a', 'b']
>>> sorted(lst)
['A', 'B', 'a', 'b']
```

We [use][1] those default sorting functions/methods without modification.

I haven't considered it before, but as the page title is taken from the file name and capitalized, that could make it appear in the nav that things are not sorted properly as the case used when sorting has been changed. So, should we require users to account for case sensitivity in their file names or should we just do a case-insensitive sort by default?

```python
>>> sorted(lst, cmp=lambda x,y: cmp(x.lower(), y.lower()))
['A', 'a', 'B', 'b']
```

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/config_options.py#L358-L359

**Comment by rickpeters** [comment]
I would propose a case insensitive search, I often don't think about the case on my pages. However I would also like some way to be able to manually order some pages and after that the rest be ordered automatically. I have a large site (300 pages).
I have been dabbling in using prefixes for page names (1_title of page, 2_other title). This works for ordering bit as you can understand I don't like the page names.
An option (for a plugin?) would be to order based on the full name but to remove the 'prefix' on rendering in menu's. Looks like a fairly simple implementation to me?

regards,
Rick

p.s. sorry if I use the wrong issue to mention this, it's just a quick thought before I'm off on holiday :-)

**Comment by waylan** [comment]
So I was curious about the historical behavior here (case sensitive sorting has been used since support for auto-populated pages has been added. See 9dcd881), and I found commit 9a667c5 (which added sorting to directories, not just filenames). That commit message reminded me that even if we make sorting case-insensitive, the results could still be "wrong" for various non-English languages (specifically if non-ASCII characters are used).

The reason we even sort at all is so that the pages are listed in the same order every time (some systems will provide a list of files in a different random order each time requested). The sorting is **not** to ensure the pages are sorted in a "correct" alphanumeric order, but rather a consistent order. That being the case, I'm inclined to leave it as-is.

If you really want a specific ordering, then keep all of your file and directory names in the same case (and use ASCII characters only). As noted above (and in the commit message on 9a667c5), any additional options can be addressed via a plugin when that becomes available.

**Comment by SusanthCom** [comment]
Hi

What about adding an user configurable option `case_ insensitive_sort_filenames: true` in `mkdocs.yml`

If so, let default state be as it is now; and new option for those who prefer case insensitive, 

Thank you

**Comment by SusanthCom** [comment]
Yes. Confirmed !

Case itself is the cause. It is found in directory names too !

see ... `MMM` listed before `Aa`

![screen shot 2016-07-29 at 12 42 01 pm](https://cloud.githubusercontent.com/assets/11663470/17240587/e76e5db2-5589-11e6-920f-ef964284b7cb.png)

**Comment by SusanthCom** [comment]
Hi,

Can any one, please provide me a `fix code` and instruction to apply (for case insensitive sort for both files and directory names ). 
So that : i can apply in my local installation.

Thanks in advance 😄

**Comment by waylan** [comment]
Our goal to keep the number of config settings as low as possible.  In fact, we are in the process of removing some. We have no interest in adding more, with the exception of the setting for plugins, which will make this and many other things possible.

If you want to patch the code yourself, then this should do the trick:

```diff
--- a/mkdocs/config/config_options.py
+++ b/mkdocs/config/config_options.py
@@ -356,8 +356,8 @@ class Extras(OptionallyRequired):
             raise StopIteration

         for (dirpath, dirs, filenames) in os.walk(docs_dir):
-            dirs.sort()
-            for filename in sorted(filenames):
+            dirs.sort(cmp=lambda x,y: cmp(x.lower(), y.lower()))
+            for filename in sorted(filenames, cmp=lambda x,y: cmp(x.lower(), y.lower()))
                 fullpath = os.path.join(dirpath, filename)

                 # Some editors (namely Emacs) will create temporary symlinks
```

**Comment by SusanthCom** [comment]
@waylan  Thank you very much for the code and time.

Yes you are right.
More options makes things complicated. I was using Harp previously. MkDocs Simplicity is what attracted me. 

Thanking you all Contributors 👍

**Comment by waylan** [comment]
> Where (path) can i find the file to patch; with above code ?

That depends on how your system is configured, how you installed Python, and possibly even how you installed MkDocs.

The simplest solution would be to download the package, modify it, then install your modified package. If you previously installed via a package manager, then use that tool to uninstall the previously installed version first.

1. Download the package here: <https://pypi.python.org/packages/b9/ca/eae66b7db8d651d41e148dba1d2a329e285eb9b979d6eef33cd508d9302a/mkdocs-0.15.3.tar.gz>

2. After unpacking it (`tar xzf mkdocs-0.15.3.tar.gz`), enter the `mkdocs-0.15.3` directory (`cd mkdocs-0.15.3`) and make the changes to the `mkdocs/config/config_options.py` file.

3. Finally, from within the  `mkdocs-0.15.3` directory, run the following command to install: `python setup.py install`.

**Comment by SusanthCom** [comment]
@waylan Wow ! Much detailed Help !!

I installed using `pip install mkdocs`

Will follow your guide lines. Thank you Very much. ❤️

**Comment by MaderHatt3r** [comment]
Why is the solution to modify the code? Can we submit a bugfix for the improper sort order? I just came across this issue in my own deploy where I had a document sorted wrong due to case sensitivity.
