### ISSUE TITLE
documentation on easier publishing with github pages

### ISSUE THREAD

**Issue by stephenturner** [mkdocs/mkdocs#1031]
Github just announced a simplification to publishing pages that allows you to serve pages directly from the master branch, or better yet, from a `docs/` directory on master. 

https://github.com/blog/2228-simpler-github-pages-publishing

For now, it seems that the configuration is inflexible - looks like it _must_ be served from `docs/` and no other directory. It would be nice to see documentation on the deployment page describing this as an alternative to the `ghp-import` route.

**Comment by waylan** [comment]
Yeah, I saw that announcement last night. At first I was a little excited, then I realized ...

> ... that the configuration is inflexible - looks like it *must* be served from `docs/` and no other directory.

Of course, if you are using Jekyll, that works fine as your raw Markdown can be contained in the `docs/` dir, and Jekyll will render them to HTML. However, if you are rendering the docs to HTML yourself (as when using MkDocs), that doesn't work so well. To me, it feels that GitHub only intended this new feature for those using the built-in Jekyll system. For the rest of us, the docs need to continue to be pushed to the `gh-pages` branch.

Of course, that is not to say it wouldn't work. One could set up their `docs_dir` setting to a different dir than `docs/` and then set `site_dir` to `docs/`. But then how do you commit changes? That depends on whether you want to update the live docs with every commit, or only on each release (tag?). To me, the best way to accomplish that would be with a git hook. If a commit includes any changes to the `docs_dir`, then run MkDocs and amend the commit to include any changes in the `site_dir`. The hook could be triggered for every commit, or only for tags. Of course, there is not anything MkDocs need to do. This is all in the git hook realm. If someone wanted to write such a script, I suppose we could point to it.

**Comment by ppKrauss** [comment]
I using at Github the `index.html` (at the git root), and the index points to the documentation at `/site`, generated by `mkdocs build`. Working fine, even the *search* navigation.

**Comment by waylan** [comment]
There is not any actionable item here and I don't see nay value in adding to our documentation so I'm closing this.
