### ISSUE TITLE
HTML output structure for local view

### ISSUE THREAD

**Issue by rainman20** [mkdocs/mkdocs#1032]
Is it possible to change the structure of the  `site` directory files so we can we it locally? right now, if I have multiple pages, and I click on `index.html` and then choose another page I dont see page directly. I see the folder in the browser which I have to choose the index.html inside the folder to see the page.

**Comment by waylan** [comment]
You want the [`use_directory_urls`][1] config setting. However, be aware that not everything works properly when the pages are not served from a server (see #871 for example).

[1]: http://www.mkdocs.org/user-guide/configuration/#use_directory_urls
