### ISSUE TITLE
base_url incorrect for 404 subdirectories

### ISSUE THREAD

**Issue by murrant** [mkdocs/mkdocs#1035]
When visiting a sub directory such as `http://docs.org/first/second` and getting a 404, all the links and resource urls are incorrect because base_url is `.` instead of `../..`

Is there a way force absolute urls, or perhaps fix the relative base_url?

**Comment by waylan** [comment]
This appears to be a duplicate of #77 and is closely related to #192 (where a reasonable solution has been described).
