### ISSUE TITLE
mkdocs build doesn't work in crontab?

### ISSUE THREAD

**Issue by mark-rodgers** [mkdocs/mkdocs#1036]
I have a crontab that runs a script I put inside my mkdocs directory. The cron is correctly triggering the script to run, cd into the mkdocs directory, make sure I am on the correct branch, and run the mkdocs build command. For some reason I can't seem to get the command **mkdocs build --clean** to work inside the cron. No errors, no output, build command does not run.

Not sure if it matters, but I have Python 2.7.12 installed AND Python 2.6.6. Python 2.6 came packaged with CentOS so I do not want to remove/update it in fear or breaking the OS. I installed pip for python2.7 and installed mkdocs via pip so that mkdocs will use python 2.7.12

Running the script works perfectly, but when the script gets called from the cron it seems to skip over the **mkdocs build**.
## update.sh

```
( cd /root/docs && pwd && git branch && mkdocs build --clean )
```
## crontab

```
* * * * * . /root/docs/update.sh > /root/docs/log
```
## crontab output to log

```
/root/docs
  cabb
  master
* mrodgers
```
## environment

CentOS release 6.8 (Final)
Python 2.7.12 (alias = python2.7)
Python 2.6.6 (alias = python)
pip 8.1.2 (python 2.7)
mkdocs, version 0.15.3

**Comment by waylan** [comment]
I don't see that you mentioned this, but does the build run without the `--clean` flag from within the cron? If not, then `--clean` is a red hearing and you have a different problem.

If this is related only to the `--clean` flag, then you may be interested to know that `--clean` will become the default on the next release (even if the flag is not specified; you will need to use the new `--dirty` flag to avoid a clean build). In any event, the `--clean` flag causes the [`mkdocs.utils.clean_directory`][1] function to run. Perhaps something in there does not have proper permissions from within a cron job?

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/utils/__init__.py#L123

**Comment by mark-rodgers** [comment]
Just tested without the clean flag, same problem using **mkdocs build**

**Comment by waylan** [comment]
Okay, so clean is not relevant to the problem. And using Python's `-m` flag was a good step to try.

How is Python (and mkdocs) added to your path. If that happens in a user specific config file (like `.profile` and friends), then that may not be applied from crontab. This seems especially likely as you are using a non-default Python install. Perhaps try running `python2.7 --version` from a cron job and see if that outputs anything. Then maybe do the same with MkDocs: `python -m mkdocs --version`. If those print a version to the log, then we have a MkDocs related issue, if not, you likely have a local configuration issue.

If it is a MkDocs issue, then try running `build` with the `--verbose` flag and see if that outputs any helpful info?

**Comment by waylan** [comment]
This appears to be a Python config issue, not a Mkdocs specific issue so I am closing it. If the problem still persists, please feel free to leave and comment and we will reconsider.

**Comment by RuffaloLavoisier** [comment]
> Okay, so clean is not relevant to the problem. And using Python's `-m` flag was a good step to try.
> 
> How is Python (and mkdocs) added to your path. If that happens in a user specific config file (like `~/.profile` and friends), then that may not be applied from crontab. This seems especially likely as you are using a non-default Python install. Perhaps try running `python2.7 --version` from a cron job and see if that outputs anything. Then maybe do the same with MkDocs: `python -m mkdocs --version`. If those print a version to the log, then we have a MkDocs related issue, if not, you likely have a local configuration issue.
> 
> If it is a MkDocs issue, then try running `build` with the `--verbose` flag and see if that outputs any helpful info?

It is working . `python3 -m` !!
