### ISSUE TITLE
Build option for local documentation

### ISSUE THREAD

**Issue by pierreporte** [mkdocs/mkdocs#1045]
I work on a documentation that will be distributed alongside the programme. I chose MkDocs for its ease of use, the flat markdown files, the client-side search engine, and of course because it only builds static files. The users will have access to it with a menu in the GUI that will open the default browser to the index file, or by going to the application website (the files would be the same, an other advantage of MkDocs).

The problem I encounter for my specific use of the tool is that each markdown file is converted into a directory containing a single index.html file. When a browser encounter a link to a directory, it doesn’t redirect to the index file when one is present, but displays the list of the files contained in the directory.

I propose to make an option to translate the markdown files into simple HTML files. To build a local documentation, one would execute `mkdocs --local` for example.

**Comment by zlalanne** [comment]
Try setting the use_directory_urls=false in your configuration file.

http://www.mkdocs.org/user-guide/configuration/#use_directory_urls

**Comment by pierreporte** [comment]
It works! Thanks.
