### ISSUE TITLE
mkdocs serve doesn't serve anything

### ISSUE THREAD

**Issue by sathibault** [mkdocs/mkdocs#1046]
There are no errors but the visiting the http://localhost:8000/ yields a 404.  Any suggestions?

**Comment by waylan** [comment]
Do you have an `index.md` at the root of your `docs_dir`? When you use the build command, does that `index.md` file get rendered as an `index.html` file at the root of the `site_dir`.

**Comment by sathibault** [comment]
My top-level file was not named index.md.  Might be good to put that in the docs if not already.
