### ISSUE TITLE
Suggestion: Add Scroll Animation to readthedocs theme

### ISSUE THREAD

**Issue by ronakdev** [mkdocs/mkdocs#1049]

**Comment by waylan** [comment]
The readthedocs theme is intended to mimic the theme used by the Read the Docs service. Does their theme offer this feature? If not, then I doubt we want to offer it. If so, then this would be a duplicate of #588.

**Comment by ronakdev** [comment]
Oh, didn't realize that this wasn't the base source. I'll submit this issue there

**Comment by waylan** [comment]
This is the base source of MkDocs. However, the readthedocs theme contained in MkDocs is a clone of the default Sphinx theme used by the [readthedocs][1] service.

[1]: https://readthedocs.org/
