### ISSUE TITLE
Collapsing sidebar when zooming out

### ISSUE THREAD

**Issue by lebigot** [mkdocs/mkdocs#1050]
**Zooming out** with Safari 10.0 on macOS Sierra **collapses the side bar** of the MkDocs, Cinder, Yeti, etc. styles into the main text.

![cinder](https://cloud.githubusercontent.com/assets/5793/18836205/38336f28-83ff-11e6-91f0-4f4b742360a7.jpg)

**Comment by waylan** [comment]
The Cinder theme is a third party theme outside our control. Please report any problems directly to the developers of that theme: https://github.com/chrissimpkins/cinder

I'm not familiar with Yeti, but the same situation applies.

**Comment by waylan** [comment]
I don't have access to Safari 10.0 on macOS Sierra so someone else will need to confirm this, but, yes, if this is occurring on the MkDocs or Readthedocs themes, then it should be reopened.

**Comment by lebigot** [comment]
Let me confirm:
<img width="767" alt="mkdocs" src="https://cloud.githubusercontent.com/assets/5793/18841912/99f179d0-8413-11e6-99b6-8258df4e59db.png">

**Comment by ikirker** [comment]
I can reproduce this with Safari 10.0 on OS X El Capitan. Changing window size doesn't trigger or fix it, only zooming to <100%. Toggling `position: fixed;` pops it in and out. 🙁

**Comment by waylan** [comment]
So this only occurs when zoom is <100% with Safari 10.0 on OS X El Capitan. That seems like a very specific edge case. I have to wonder if a bug was introduced in the browser or if this was an intentional behavior change. If its the former, then a report should be filed upstream. If its the latter, seems like there should be some info about it somewhere.

> Toggling `position: fixed;` pops it in and out.

So you are saying this fixes the problem? On which element? Or more specifically, which line in the CSS files?

**Comment by waylan** [comment]
Oh and our themes are built on top of bootstrap/bootswatch. Does this problem occur with those projects default themes? If so, what are they doing to fix the problem (we should do the same)?

**Comment by ikirker** [comment]
With the inspector set on the sidebar element:

100% Zoom: 
![screen shot 2016-10-17 at 17 39 40](https://cloud.githubusercontent.com/assets/479061/19451102/ea0a7d5e-94a3-11e6-9d05-5771e10b4f11.png)

Zoom out one step: 
![screen shot 2016-10-17 at 17 40 00](https://cloud.githubusercontent.com/assets/479061/19451145/10dc0c9a-94a4-11e6-8e06-da4f36078660.png)

Unchecked the box in the Inspector to "comment out" `position: fixed;`: 
![screen shot 2016-10-17 at 17 40 18](https://cloud.githubusercontent.com/assets/479061/19451176/32d909c4-94a4-11e6-90e1-149f55df939e.png)

(Re-checking the checkbox produces identical output to the first zoomed-out shot.)

It does also occur in the basic MkDocs Bootstrap theme, but I can't find the corresponding sidebar component in the Bootstrap docs. (I'm not very experienced in this area or layout design in general, I was just investigating MkDocs for use and saw something I could help verify, sorry.) Given the relatively weird conditions it triggers under, I agree that this *could* be a rendering bug in the browser.

I don't know enough about Bootstrap's grid system at the moment to make a minimal test case, but I might be able to give it some more thought tomorrow.

**Comment by waylan** [comment]
Ah, this is directly connected to media queries and mind-width. The default is to set `position: static;` (at [base.css#L150][1]). However, if (via a media query)  `min-width: 992px` ([base.css#L198][2]), then we set `position: fixed;` (at [base.css#L208][3]). When you zoom in, the min-width calculation changes such that we get a different behavior.

[This article][4] is presumably directly on point, albeit an older article. I assume that Webkit's behavior was changed again in the latest release, and its hard to say if the proposed solution in that article would work here.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/css/base.css#L150
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/css/base.css#L198
[3]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/css/base.css#L208
[4]: http://blog.55minutes.com/2012/04/media-queries-and-browser-zoom/
