### ISSUE TITLE
Assets urls are broken on subpages

### ISSUE THREAD

**Issue by Oza94** [mkdocs/mkdocs#1055]
I'm having troubles with the multiple pages feature, I searched through issues and I didn't find one with similar problem. Sorry if I missed something.

I just created my project using `mkdocs new project` and I added a subpage. Here is my file structure : 

```
mkdocs.yml
docs/
  index.md
  scripting-api.md
```

And my `mkdocs.yml` : 

``` yaml
site_name: My Docs
pages:
  - 'index.md'
  - 'scripting-api.md'
```

When trying to access a subpage, no style or javascript is loaded. I took a look at the logs and it seems that a double `//` at the beginning of the relative URL cause this issue. Here are the logs of `mkdocs serve` : 

![mkdocs serve error logs](http://i.imgur.com/Kpk9Rkx.png)

And indeed if I look at the served sources (or files produced by `mkdocs build`, here is what I get.

`index.html`

```
        <link href="./css/bootstrap-custom.min.css" rel="stylesheet">
        <link href="./css/font-awesome-4.5.0.css" rel="stylesheet">
        <link href="./css/base.css" rel="stylesheet">
        <link rel="stylesheet" href="./css/highlight.css">
```

`scripting-api/index.html`

```
        <link href="..//css/bootstrap-custom.min.css" rel="stylesheet">
        <link href="..//css/font-awesome-4.5.0.css" rel="stylesheet">
        <link href="..//css/base.css" rel="stylesheet">
        <link rel="stylesheet" href="..//css/highlight.css">
```

I use Windows 7 64 bit with python 2.7.

Any solution to this issue ?

**Comment by waylan** [comment]
Which version of MkDocs are you using?

**Comment by Oza94** [comment]
Sorry forgot the essential ! Mkdocs version 0.15.3.

I did a regular installation through pip (6.0.8) without errors.

**Comment by waylan** [comment]
Hmm, I can't seem to replicate this.  I just checked both 0.15.3 and the latest dev version and I'm getting:

```html
<link href="../css/bootstrap-custom.min.css" rel="stylesheet">
<link href="../css/font-awesome-4.5.0.css" rel="stylesheet">
<link href="../css/base.css" rel="stylesheet">
<link rel="stylesheet" href="../css/highlight.css">
```

Which is the correct output. And I am also on Windows 7 64 bit with Python 2.7.

**Comment by Oza94** [comment]
Strange ! I don't understand how this can happen since I have really basic configuration and usage of mkdocs. I've also quickly checked dependencies versions and it seems fine if I compare to mkdocs requirements.

I'll try on a fresh environment if possible, otherwise I'll just dockerize the build process.

**Comment by waylan** [comment]
You wouldn't happen to be using cygwin would you?

**Comment by Oza94** [comment]
Nope, no cygwin. This is a work machine that comes with some pre-installed python stack that suits our environment,. This is not ideal but I have to deal with it.

That's why I consider using docker for the mkdocs build so its isolated from my normal environment. I think I can also do it with virtualenv but I do not have a lot experience with this tool, I feel more confident with docker.

I would like to investigate more, but I do not have the time for it at the moment :/
