### ISSUE TITLE
Support for Image Lightboxes

### ISSUE THREAD

**Issue by martnst** [mkdocs/mkdocs#1065]
Hi there, 
we are currently using [MDwiki](http://dynalon.github.io/mdwiki/#!index.md) which looks very very similar to MKDocs, but would like to change to MKDocs as it seems to be a more active project and seems to have more features. 

Unfortunately it seems that MKDocs does not have a lightboxes built in as MDwiki does, see [here](http://dynalon.github.io/mdwiki/#!quickstart.md#Images). As we have screenshots in our docs it is crucial to us that the reader can bringt them fullscreen to see all details while still having the images aligned nicely in the text per default. 

**Is there any theme that supports lightboxes or plan to include it in a future version?**

**Comment by waylan** [comment]
I haven;t checked, but perhaps a third party theme offers such support. Check the [wiki][4] for a list.

I see no reason why we would include that specifically in the default theme. However, themes can certainly be modified. In fact, in the next release (0.16) there will be much more support for theme customization (see a [preview][0]). Until then, there is always the [exta_css][1] and [extra_javascript][2] config settings for you to provide your own styling and JavaScript for your lightboxes. You just need to write your HTML then. Of course, Markdown accepts and passes through raw HTML, or you could create (or find an existing) [Markdown Extension][3] to generate the HTML from some simple Markdown markup. And later, when the Plugin API becomes available (see #206), then this could possibly be all wrapped up in a plugin.

[0]: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/styling-your-docs.md#customizing-a-theme
[1]: http://www.mkdocs.org/user-guide/configuration/#extra_css
[2]: http://www.mkdocs.org/user-guide/configuration/#extra_javascript
[3]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
[4]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes

**Comment by waylan** [comment]
I just occurred to me that there are a collection of bootstrap themes in  [mkdocs/bootstrap][1]. And with a quick search, a [Bootsrap Lightbox plugin][2] exists. You might be able to get that working with less effort.

[1]: https://github.com/mkdocs/mkdocs-bootstrap
[2]: https://ashleydw.github.io/lightbox/

**Comment by waylan** [comment]
Also, the default theme (`mkdocs`) and all the themes in [mkdocs/mkdocs-bootswatch] are built with bootswatch, which is a bootstrap wrapper.

[1] https://github.com/mkdocs/mkdocs-bootswatch

**Comment by waylan** [comment]
@martnst I thought that adding a lightbox would make for an excellent simple example of how to use the new `theme_dir` features in the upcoming version 0.16 of MkDocs. I just through together a simple project which implements a lightbox at [waylan/mkdocs-theme_dir-example][1].

@d0ugal if you are interested, we can move that example repo to the mkdocs organization if you want. I just don't have the permissions to create repos (which is fine, just pointing out that you will need to do it). Not sure if we want to wait for 0.16 to be released first though. When it is, we can add links in the README to the updated docs.

[1]: https://github.com/waylan/mkdocs-theme_dir-example

**Comment by waylan** [comment]
And if that repo gets moved to the `mkdocs` account, we can add a link to it from the docs. I think it really helps complete the [theme customization][1] docs.

[1]: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/styling-your-docs.md#customizing-a-theme

**Comment by marcelstoer** [comment]
> I just threw together a simple project which implements a lightbox at waylan/mkdocs-theme_dir-example.

What a fantastic tutorial, thanks!

**Comment by m-kuhn** [comment]
For those without a compatible theme, I just published a fancybox based extension https://github.com/opengisch/fancyboxmd
