### ISSUE TITLE
How Can I Remove the Footer "Documentation built with MkDocs"

### ISSUE THREAD

**Issue by ahmadawais** [mkdocs/mkdocs#1070]
I read all the documentation but am unable to find How Can I Remove the Footer "Documentation built with MkDocs"? Can anyone help?

What am I missing?

**Comment by waylan** [comment]
The simple answer would be to use some custom CSS to "hide" that bit of HTML. However, to actually "remove" it, you would need to do some theme customization. In the current release (0.15), that is not so easy. However, in the next release (0.16), that should be much easier to do. See [here][1] for a preview of the documentation.

[1]: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/styling-your-docs.md#customizing-a-theme

**Comment by waylan** [comment]
I'm closing this as there appears to be no actionable item.

Also I should note that version 0.16 is now released and theme customization is available and documented [here](http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme).
