### ISSUE TITLE
can mkdocs support Chinese md files?

### ISSUE THREAD

**Issue by jeffsui** [mkdocs/mkdocs#1072]
can mkdocs support Chinese md files?

**Comment by waylan** [comment]
As long as the files are encoded in UTF-8, there shouldn't be any reason why that won't work. The underlying Markdown parser is known to work, so any MkDocs specific issues would be considered a bug. Please try it and report any bugs you may encounter. 

The one known exception would be the search feature. It only works with English right now. See #826.

As there is no actionable item here, I'm closing this.
