### ISSUE TITLE
ReadTheDocs theme - List paragraph spacing

### ISSUE THREAD

**Issue by tpluscode** [mkdocs/mkdocs#1073]
The read the docs theme includes a style

```
.rst-content .section ul li p:last-child {
   margin-bottom: 0;
}
```

It causes the last paragraph to be very close to the next bullet point. I see though how the entire list takes quite a lot of space. Maybe the `.rst-content .section ul p` style selector could be extended with something like `margin-top: -5px;` to make lists more condensed?

**Comment by waylan** [comment]
As a reminder, the `readthedocs` theme is a clone of the default (Sphinx) theme for the Read the Docs service (as used [here][1]). I haven't checked, but if the MkDocs clone matches that theme, we are not likely to make a change. If, however, there is a difference, then the MkDocs theme should be updated to match. There is a general issue already open for this: #588. Any specific fixes related to that issue can be addressed via pull requests. However, we don't need a whole bunch of separate open issues for each individual variation, so I'm closing this. Feel free to document any issues variations you find as comments on #588.

[1]: https://docs.readthedocs.io/en/latest/index.html
