### ISSUE TITLE
Can't get option --dirtyreload to work?

### ISSUE THREAD

**Issue by rickpeters** [mkdocs/mkdocs#1074]
In reference to issue #990 I am trying to get a dirty reload to work. Since I have a site with almost 300 pages a full rebuild takes about 4 minutes.
Testscenario:
Use mkdocs 1.16
1. test with `mkdocs serve`, on change of a page the full site gets rebuilt
2. test with `mkdocs serve --dirtyreload`, on change of page nothing happens?
3. test with `mkdocs serve --dirtyreload --livereload`:
the output correctly states that mkdocs is `watching changes`. However on a change the full site is rebuilt and not only the changed file.

What I find strange is that when I only use `--dirtyreload` that I don't see a message taht mkdocs is `watching changes`

Is this an issue with how mkdocs watches for changes when doing `--dirtyreload` or am I doing something wrong. I have to add that I'm running using my own docker container, that's why I explicitly tried whether reload does indeed work without `--dirtyreload`

regards,
Rick

**Comment by rickpeters** [comment]
I think I am not sure that I use the right mkdocs version. When I run `mkdocs --version` it states *0.15.3*. I use

`https://github.com/mkdocs/mkdocs/archive/master.tar.gz` in my requirements.txt on building the environment?

Didn't notice this earlier because the flag `--dirtyreload` is accepted on running `mkdocs serve`

regards,
Rick

**Comment by waylan** [comment]
The options `--dirtyreload`, `--livereload`, and `--no-livereload` are mutually exclusive. You can only use one at a time. The fact that you are not getting an error when trying to use two of them is concerning. Perhaps we need to improve the docs for that.

Unfortunately, this project doesn't update/alter its version number to indicate a dev version. If you installed directly from the Git repo, then you should be using the latest code.

Finally, I agree, there is something weird going on with `--dirtyreload`. Haven't worked out what yet. Thanks for the report.

**Comment by rickpeters** [comment]
Hi Waylan,

thanks for the quick update. I'll await the great work your always doing :-)
And if I can test something for this then just let me know!

I just did a test using the -verbose option and I noticed that it didn't state the usage of the `--dirtyreload` option? And as stated earlier it doesn't say that it's looking for changes.

regards,
Rick

**Comment by waylan** [comment]
For the record, I raised an issue at pallets/click#673 regarding the fact that an error isn't raised when using mutually exclusive feature switches.
