### ISSUE TITLE
skip certain files from building

### ISSUE THREAD

**Issue by sander76** [mkdocs/mkdocs#1076]
I use mkdocs for simple building and deploying to a website.
Sometimes I am creating a file which is not ready for deployment yet. I want this file to show up when doing a `mkdocs serve` but want it skipped when doing a `mkdocs build`

Is there a way to "tag" a file, using metadata or file naming scheme which will help doing the above ?
Or is there any other scenario I could use ?

**Comment by rickpeters** [comment]
A trick I use for this is that I have my sources in a git repository. The mkdocs build is based on the master branch (and automated). Now you can use several tricks to keep your 'drafts' on your local workstation only and show them while using mkdocs serve.

**Comment by waylan** [comment]
You may want to read through the discussion in #699. While not directly related, there is a lot of similarities. Regardless, I don't think this is a feature we want to include by default. I expect that this would be a good candidate for a Plugin (see #206).

**Comment by sander76** [comment]
I saw that discussion #699. I thought this would be a plugin candidate, but hoping someone already did this...

**Comment by waylan** [comment]
The plugin API is not finished yet (expected with the release of version 1.0). Therefore, there are no plugins at this point.
