### ISSUE TITLE
Autodoc and plugin architecture idea

### ISSUE THREAD

**Issue by guyskk** [mkdocs/mkdocs#1078]
I am working on a autodoc plugin for mkdocs, just like autodoc for sphinx.
I had read https://github.com/mkdocs/mkdocs/issues/206 and https://github.com/erichulser/mkdocs_autodoc ,and sadlly found that there are no plugin API in mkdocs.

But it doesn't matter, I read the code of mkdocs and hack it. Now my autodoc plugin works and I want to share my idea about plugin architecture.

The plugin: https://github.com/restaction/mkdocs-autodoc
Usage: https://github.com/restaction/docs-zh_CN/blob/master/docs/api.autodoc
Demo: http://restaction.readthedocs.io/zh_CN/master/api/

It would be great to use loaders to load files, then I can implement a
autodoc loader which parse `*.autodoc` files and convert them into html.

This plugin architecture is similar to [webpack](https://webpack.github.io/)
which use lots of loaders to load css, images, etc and convert them into js.

Meanwhile, loader is much easier to implement then events callback.

@erichulser @d0ugal

**Comment by waylan** [comment]
The Plugin API is a work in progress and very different from that proposed and used in https://github.com/erichulser/mkdocs_autodoc. The end of the discussion in #206 indicates where we are going.

In any event, this appears to be an announcement rather than an actionable issue. Therefore, I'm closing it. In the future, please make announcements on the [mailing list](https://groups.google.com/forum/#!forum/mkdocs).

**Comment by guyskk** [comment]
@waylan https://groups.google.com/forum/#!topic/mkdocs/7x2u9iN7gdk

**Comment by waylan** [comment]
If you have a proposal for an API, then it would be more helpful to provide a diff of the changes you made to MkDocs code, or even better, write up a full proposal similar to the one on the [wiki](https://github.com/mkdocs/mkdocs/wiki/Event-Based-Plugin-API). You can create your own wiki page for your proposal and link to it from #206.

The point is, if you want us to consider your proposal, you have to do the work. Make it easy for us to understand what you are proposing. Don't make us go digging through your code to figure it out. I certainly don't have the time for that.
