### ISSUE TITLE
readthedocs theme looks bad in large screen

### ISSUE THREAD

**Issue by guyskk** [mkdocs/mkdocs#1080]
It would be better to increase white space width on the both side of content, like [Paypal API](https://developer.paypal.com/docs/api/).

![selection_004](https://cloud.githubusercontent.com/assets/6367792/19600092/f69153b2-9792-11e6-8fc1-d8dc5a3fb6d6.png)
![selection_003](https://cloud.githubusercontent.com/assets/6367792/19600101/feddade0-9792-11e6-8489-36fcc0ce34d6.png)

**Comment by waylan** [comment]
The readthedocs theme is a clone of the default Sphinx theme used by the Read the Docs service. Any changes to our clone would need to reflect updates made to that theme. This is already addressed in #588. Therefore, I am closing this as a duplicate.
