### ISSUE TITLE
Not able to add code sample as part of bulleted list

### ISSUE THREAD

**Issue by viktorasm** [mkdocs/mkdocs#1081]
If I add code sample as part of list item, it does not get highlighted properly. Sample documentation excerpt:

```
* Add `ngskintools\Contents\plug-ins\windows-maya2017-64bit` to `MAYA_PLUG_IN_PATH` (use particular plugin path for your OS/Maya version);
* Add `ngskintools\Contents\scripts` to `PYTHONPATH`; you should be able to execute "import ngSkinTools" from python script editor;
* Add ngSkinTools shelf button with python code:
	
	(This get recognized as proper second paragraph if indented with a tab.)
	
	```python
	# this is improperly formatted
	from ngSkinTools.ui.mainwindow import MainWindow
	MainWindow.open()
	`﻿``
```

As for second paragraph in list item, I indent code sample with a tab, but instead it gets formatted rather weird: code block not recognized, comment formatted as header; if I remove the comment, the whole block is still formated as simple indented block.

**Comment by waylan** [comment]
First of all, this is an issue with the Markdown parser that MkDocs uses, not MkDocs itself. However, this is a known limitation (see waylan/Python-Markdown#53) with Fenced Code Blocks; they **must** be at the document root only. In all other situations, you must use indented code blocks. Of course, to use indented code blocks in a list, they require an extra level of indentation, once to make them a child of the list item, and a second time to make them code blocks for a total of 8 spaces (or two tabs) of indentation:

```
* Add `ngskintools\Contents\plug-ins\windows-maya2017-64bit` to `MAYA_PLUG_IN_PATH` (use particular plugin path for your OS/Maya version);
* Add `ngskintools\Contents\scripts` to `PYTHONPATH`; you should be able to execute "import ngSkinTools" from python script editor;
* Add ngSkinTools shelf button with python code:

    (This get recognized as proper second paragraph if indented with a tab.)

        # this is indented twice as a nested code block
        from ngSkinTools.ui.mainwindow import MainWindow
        MainWindow.open()
```

As there is no actionable item for MkDocs, I'm closing this.

**Comment by keviny22** [comment]
this seems to be a work around

1.  Item 1
<pre>```
git clone https://github.com/foo/bar
cd bar
```</pre>
2. Item 2
