### ISSUE TITLE
Duplicate headings on same page - linking to specific heading

### ISSUE THREAD

**Issue by nathanaherne** [mkdocs/mkdocs#1083]
I have spent a heap of time googling for this but have not found the answer.

In the documentation we write, we often have multiple "Example" headings. We would like to be able to link to the specific example. Is there a way to have an alternate name for a heading (which doesn't show) but which allows us to link to the heading?

**Comment by waylan** [comment]
First of all, it is invalid HTML to assign two elements the same `id`. And it is generally poor form to have two identical headings in a document. That said, the code which generates the ids for the headings ensures that no two headings within the same document have the same `id` by appending `_n` (where `n` is a number) counting up for each occurrence (see [the docs][0]). For example, three headings containing the text "`Foo`" would result in the following ids: `foo`, `foo_1`, and `foo_2`.

If however, you would like to define your own custom `id`s, then you may want to [enable][1] the [Attribute Extension][2].

[0]: http://pythonhosted.org/Markdown/extensions/toc.html
[1]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
[2]: http://pythonhosted.org/Markdown/extensions/attr_list.html

**Comment by waylan** [comment]
As this is not a MkDocs specific issue, I'm closing it.

**Comment by nathanaherne** [comment]
Thank you for this, the extension works well.
