### ISSUE TITLE
Feature request - validation of internal links, including headings.

### ISSUE THREAD

**Issue by nathanaherne** [mkdocs/mkdocs#1084]
It is fantastic that Mkdocs validates links to internal pages but it would be fantastic if it could validate links to internal pages and headings, this would save a huge amount of time having to check each link individually, especially when heading names change for whatever reason.

**Comment by waylan** [comment]
This would be extremely difficult to implement. The current validation runs by injecting into the Markdown parser (via a custom Extension) and comparing each internal link with the global list of pages. However, to compare the URL hash with a pages TOC, would require that that page already be rendered to HTML. There is no way to guarantee that a given page would be rendered when rendering another page. Or put another way, we could only validate URL hashes for pages previously rendered, but not for pages yet to be rendered.

In the end, I view the current validation as a nice-to-have feature and probably not something that should be relied on. If you want to completely validate your internal links, then I would recommend adding something to your own testing mechanisms to check those sorts of things. In fact, MkDocs does this in our [own tests][1]. We use the [LinkChecker][2] tool and run it against a completed build of the docs.

[1]: https://github.com/mkdocs/mkdocs/blob/master/tox.ini#L26-L34
[2]: http://wummel.github.io/linkchecker/

**Comment by nathanaherne** [comment]
I can see your points, thank you for clarifying.

**Comment by hfagerlund** [comment]
Here is an example using Jinja filters to generate hyphenated anchor links from multi-word heading tags on the same page:
https://github.com/hfagerlund/mkdocs-docskimmer/blob/d26adf98eafc2f955873ce0019e5644a010f6827/mkdocs_docskimmer/page-toc.html#L5-L7

Hope this helps.

**Comment by waylan** [comment]
@hfagerlund that would not be helpful. This request is referring to the headings in the Markdown text, which are given IDs my a Markdown extension.
