### ISSUE TITLE
Option to set upper limit heading level for toc

### ISSUE THREAD

**Issue by mehulkar** [mkdocs/mkdocs#1086]
It looks like markdown_toc supports a `baselevel` attribute, but doesn't have a config to set an upper limit on header tags that should be included in the TOC. 

Is this a feature option for mkdocs TOC?

I have h3 level markdown in my content, and considering #588 since they collapsibility isn't a thing, I wonder if we can at least limit the number of levels that show up in the TOC? (I'm using the `readthedocs` theme, but I think this would apply to other themes as well.

**Comment by waylan** [comment]
Hmm, if we include less levels, some people request more, but if we include more, some people want less. Seems like this should be configurable as everyone has a different opinion about which level is ideal. That said, we are generally trying to have less config options, not more so its not clear how we should proceed with this. I wonder if a plugin could address this? [Theme customization][1] would work today, but that seems like a lot of work for something that could be addresses with a very simple setting.

[1]: http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

**Comment by pabl0rg** [comment]
+1 for config option

**Comment by waylan** [comment]
> on some pages, 3 levels might make sense but on others only 2

Well, then it couldn't be a config option, it would need to be a meta data value. That might actually make more sense. If a theme checks for the value in the page's meta data, it can adjust, if not, then it does some sensible default. There is no need to modify any code, only the template.

**Comment by pabl0rg** [comment]
thanks for the lead.  i didn't know that existed.

**Comment by EpicEric** [comment]
Today, you can use the [`toc_depth` option](https://python-markdown.github.io/extensions/toc/#usage), which was added to Python-Markdown [in version 3.0](https://github.com/Python-Markdown/markdown/pull/686).

**Comment by squidfunk** [comment]
Closing, since this is now supported as mentioned in the comment above.
