### ISSUE TITLE
Long menu or sidebar is hidden outside bottom of browser

### ISSUE THREAD

**Issue by gurnard123** [mkdocs/mkdocs#1097]
If there is a long page with 20 + headings then the sidebar does not scroll into view when page scrolls so the bottom items are permanently hidden.
You can see in the attached image I am on the bottom section but there is still loads more content that I can scroll (see scrollbar) but the menu does not scroll with the content.
![sidemenu](https://cloud.githubusercontent.com/assets/8625592/20567723/1d1c5bf0-b19a-11e6-95c1-45b6093b2fe1.PNG)

The same applies to the drop down menu from the top bar. If it is too long then it is hidden outside of the browser.

**Comment by waylan** [comment]
Which theme are you using? From your screenshot, it does not appear that you are using either of the built-in theme (`mkdocs` or `readthedocs`). If you are using one of the [bootswatch themes][1] or the [bootstrap theme][2] (which are installed by Mkdocs by default), then you should still report the issue to the proper project. If you are using a third party theme, then you need to report the issue to the theme authors as MkDocs has no control over third party themes.

[1]: https://github.com/mkdocs/mkdocs-bootswatch
[2]: https://github.com/mkdocs/mkdocs-bootstrap

**Comment by gurnard123** [comment]
Thanks for the repy waylan. Yes you are right it is cinder I will post on there, thanks.

**Comment by yannick-dupont** [comment]
i have the same issue with united theme

**Comment by waylan** [comment]
@yannick-dupont please report this to the united theme.
