### ISSUE TITLE
How does one edit the content layout?

### ISSUE THREAD

**Issue by JimBobUKII** [mkdocs/mkdocs#1103]
Hi

Lets say i have index.md, within that file I have
```
# Company overview
Founded in 1996, The Company is one of Europe's leading managed IT services providers. We offer businesses hosting, networks and communications services. We have over 5,700 customers and an outstanding record for delivering high quality solutions, across a wide range of industries. With over 1,200 employees, we are based in 18 offices across Europe.
```

When building the site, the content is rendered/built as follows
```
<h1 id="company-overview">Company overview</h1>
<p>Founded in 1996, The Company is one of Europe's leading managed IT services providers. We offer businesses hosting, networks and communications services. We have over 5,700 customers and an outstanding record for delivering high quality solutions, across a wide range of industries. With over 1,200 employees, we are based in 18 offices across Europe.</p>
```

Could someone advise what template I need to edit to change the built output please?
I would like to add something along the line of:
`<h1 id="company-overview">Company overview</h1><a href="url#company-overview">share</a>`

I have tried looking through the theme etc. but maybe I am missing something?

Thanks in advance

**Comment by waylan** [comment]
Have you read through the [Customizing a Theme][1] section of the documentation? I expect that will answer most of your questions.

As there is no actionable issue here (bug report, feature request, etc), I am closing this. Please direct future support questions to the [list][2].

[1]: http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme
[2]: https://groups.google.com/forum/#!forum/mkdocs

**Comment by waylan** [comment]
I just reread your post and it appears that you are asking for custom rendering of the Markdown text. The Body of a page is generated by the Markdown parser and is inserted into the document at once. If you are looking to modify the behavior of the Markdown parser, then you need to do that through extensions to the Markdown parser, which are [supported and configurable][1] via the MkDocs config file. However, if no existing extension does what you desire, you will need to create your own and that is beyond the scope of the MkDocs project to help you with.

[1]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
