### ISSUE TITLE
only open current directories on the left and fold the rest

### ISSUE THREAD

**Issue by laoshaw** [mkdocs/mkdocs#1108]
I have a long list of items on the left sidebar, when I click on the end of the list, the page opens on the right(expected), but the left list reset so I can only see the top of the list.

the real read-the-docs handles this correct, i.e. all folders stay folded, only the one I am viewing stays expanded, how can mkdocs' readthedocs theme achieve the same effect? otherwise it becomes unusable when the left sidebar is longer than a page's height.

**Comment by waylan** [comment]
If this is a difference with the upstream theme then this is a duplicate of #588.

**Comment by laoshaw** [comment]
it is indeed a duplicate of #588 thus I close this one. Please get the collapse menu working. thanks.
