### ISSUE TITLE
Show directory tree instead of home page

### ISSUE THREAD

**Issue by Sergey-Terekhin** [mkdocs/mkdocs#1111]
It's seems to be a bug:
I've created empty project and built it. It works well, but then I click on "My Docs" header it shows me my site's file system.
I think, index.html should be shown instead

My operating system is Windows 10 Professional x64
MkDocs version is 0.16.0 (latest installed by pip)

![image](https://cloud.githubusercontent.com/assets/5369802/21350733/ed26e722-c6c9-11e6-9699-f94d87d6bf5f.png)

![image](https://cloud.githubusercontent.com/assets/5369802/21350723/deecbb64-c6c9-11e6-9266-39b014146e51.png)

**Comment by d0ugal** [comment]
This is because you are viewing the static files, rather than via a web server. `mkdocs serve` will give you the results you expect.

If you can it to work with static files, you can set `use_direcotory_urls = False` http://www.mkdocs.org/user-guide/configuration/#use_directory_urls
