### ISSUE TITLE
image shows using mkdocs serve but not when hosted on github

### ISSUE THREAD

**Issue by hotemetoot** [mkdocs/mkdocs#1116]
mkdocs version 0.16.0

When linking to an image, using the filename am-pm-1.png the image is visible only when using mkdocs serve but not after building and hosting on github.

However, after renaming the file to ampm1.png it shows both locally and online.

**Comment by waylan** [comment]
Is the image in the same directory as the Markdown file that links to it? If not, then where?

What Markdown are you using to link to the image (both with the working filename and the broken one)?

**Comment by hotemetoot** [comment]
the image is in an "img" folder which is in the same directory as the markdown file that links to it.

The link I am using is:
`![am-pm-1](img/am-pm-1.png)` (not working)
`![am-pm-1](img/ampm1.png)` (working)

**Comment by waylan** [comment]
Hmm, the generated HTML that I'm getting is:

```html
<p><img alt="am-pm-1" src="./img/am-pm-1.png" /> (not working)
<img alt="am-pm-1" src="./img/ampm1.png" /> (working)</p>
```

Which looks correct to me. Not sure why one would work but not the other.

Are you sure your browser cache was cleared?

**Comment by hotemetoot** [comment]
Ah, I guess you are right. I cleared the cache and now it is working with the am-pm-1.png filename as well.

Sorry for bothering you, I thought I was being helpful.
Thank you for helping me out.

**Comment by waylan** [comment]
Glad I could be of help.
