### ISSUE TITLE
allow mkdocs.yml outside current directory

### ISSUE THREAD

**Issue by petri** [mkdocs/mkdocs#1117]
As far as I can tell, mkdocs.yml has to be in the current directory when any of the commands are run. It would be very useful to be able to refer to mkdocs.yml that's elsewhere in the file system.

For example just add a -c | --config option.

**Comment by waylan** [comment]
I believe you want the `-f | --config-file` option.

**Comment by petri** [comment]
Aww damn was bitten by click only showing the option in subcommand help :( Sorry and thanks!

**Comment by twardoch** [comment]
Apologies for duplication, I also was not aware that I could do `mkdocs build -h` and would get extra help info.

**Comment by Naramsim** [comment]
For the folks out there, `-f` is a flag for `build`, `serve`, ...

So you should type:

```sh
mkdocs serve -f mkdocs.1.yml
```
