### ISSUE TITLE
Add ability to supply `--config=custommkdocs.yml` 

### ISSUE THREAD

**Issue by twardoch** [mkdocs/mkdocs#1118]
It would be very useful if MkDocs allowed to supply a custom path (folder and filename) for a `mkdocs.yml` config file, possibly through an optional parameter a la 

`mkdocs --config=/path/to/custommkdocs.yml build`

**Comment by waylan** [comment]
This is a duplicate of #1117. Curious we got this request twice in one day when we already offer the feature.
