### ISSUE TITLE
Setting page title per MD file for Better SEO

### ISSUE THREAD

**Issue by collizo4sky** [mkdocs/mkdocs#1120]
Apparently, mkdocs uses the breadcomb esque title such as "Theme Installation - Documentation - ProfilePress"

Setting the page tire in mkdocs.yml file will mean the navigation menu label becomes too long.

Is there a way to set title of each page for better SEO?

cc @d0ugal @waylan

**Comment by waylan** [comment]
The page "title" is exactly what you set it in the config file.

However, if you mean the contents of the `<title>` tag in the HTML, then that is a function of the theme you are using. Each theme could be different (although I believe the included themes all behave the same). 

For example, the `mkdocs` theme using this in the [template][1]

```django
{%- block htmltitle %}
    <title>{% if page and page.title and not page.is_homepage %}{{ page.title }} - {% endif %}{{ config.site_name }}</title>
{%- endblock %}
```

So, (with a few exceptions) you get `[page title] - [site name]`. However, if you would like to override that, we have conveniently wrapped that in a template block so you can [override it][2] using the [theme_dir][3].

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/base.html#L15-L17
[2]: http://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks
[3]: http://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme_dir

**Comment by waylan** [comment]
I'm closing this as there appears to be no actionable item.
