### ISSUE TITLE
RTL language

### ISSUE THREAD

**Issue by torisoft** [mkdocs/mkdocs#1125]
Hi
Is it support RTL language ?

**Comment by waylan** [comment]
Yes, the underlying Markdown parser, Python-Markdown, does support RTL languages. I'm not aware of any reason why the addons that MkDocs provides (templates, etc) wouldn't work as well, but if there is any problems, please let us know and we will do our best to address them.

**Comment by waylan** [comment]
I'm closing this as there appears to be no actionable item.

**Comment by ZamanOof** [comment]
Hello,
Are there docs for active RTL?

**Comment by waylan** [comment]
No, not at this time. However for Markdown, just use whatever language you want. The files are just plain text files.

We are currently working on providing theme translation in #2299. However it is not yet complete. Therefore, at this time you would likely need to [create your own theme][1] if you don't want English next/previous links, etc.

By the way, any feedback and/or help in translation in #2299 would be appreciated and help us move closer to getting it completed.

[1]: https://www.mkdocs.org/user-guide/custom-themes/

**Comment by squidfunk** [comment]
Material for MkDocs has [full RTL support](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#directionality).
