### ISSUE TITLE
GitHub repo link appears, but no "Edit on GitHub" link appears

### ISSUE THREAD

**Issue by chrisdeeming** [mkdocs/mkdocs#1129]
Hello,

Although a number of these options appear to have suitable defaults, I have the following in my `mkdocs.yml` file:

```
repo_name: GitHub
repo_url: https://github.com/chrisdeeming/reponame/
edit_uri: edit/master/docs/
```

I have only just recently updated to `mkdocs, version 0.16.1` and unfortunately no edit link appears (using the default, unmodified theme).

Assuming it should appear in the breadcrumb area, all I see is this:

![image](https://cloud.githubusercontent.com/assets/2158514/22223203/e6eafcec-e1b1-11e6-8f9f-bc403d7cc771.png)

The "GitHub" link just links to `https://github.com/chrisdeeming/reponame/` as per the `repo_url`. Does displaying the edit link require some sort of manual action on each page?

Many thanks,

Chris

**Comment by waylan** [comment]
See [this comment][1] for an explanation of the current situation. It appears that the plan was to leave the current link as-is and add a new second ("edit this page") link to the mkdocs theme (the readthedocs theme already had two separate links). But the issue got closed when the edit feature was added and then it was forgotten about. Thanks for the reminder. We can use this issue to track this much narrower feature now.

[1]: https://github.com/mkdocs/mkdocs/issues/269#issuecomment-229165658

**Comment by chrisdeeming** [comment]
Also, just an aesthetic thing, there should probably be a space after the icon and GitHub.
