### ISSUE TITLE
Documentation about setting page_description

### ISSUE THREAD

**Issue by ThomasArdal** [mkdocs/mkdocs#1135]
I'm looking to set the a meta description on all of my pages. In my template, the tag is added, if a `page_description` variable is present. I cannot seem to find any documentation on this variable. I can set the site description in the yaml file, but I want an unique description per document.

**Comment by ThomasArdal** [comment]
Sam goes for variables like `canonical_url`.

**Comment by waylan** [comment]
The available template variables are documented [here][1]. In the latest release, the `page_description` variable was [deprecated][2] (along with a number of other variable names). The name is misleading as it only ever was a copy of `config.site_description` and was not page specific. Additionally, it was only set for the "homepage" and left blank on all other pages with no way to set it.

If you would like to reference page specific meta-data, then you can access that from the [`page.meta`][3] variable. If you set a `description` in your page as meta-data, then you can reference it as `{{ page.meta.description }}` in your template.

There is no way to override the [`config.site_description`][4] or [`page.canonical_url`][5] variables. Those are set from the config and we have no intention of changing that.

[1]: http://www.mkdocs.org/user-guide/custom-themes/#template-variables
[2]: http://www.mkdocs.org/about/release-notes/#template-variables-refactored-874
[3]: http://www.mkdocs.org/user-guide/custom-themes/#pagemeta
[4]: http://www.mkdocs.org/user-guide/custom-themes/#config
[5]: http://www.mkdocs.org/user-guide/custom-themes/#pagecanonical_url

**Comment by ThomasArdal** [comment]
@waylan That works! I have a problem using it though. If I add the following to the top of a document:

    description: This is the description

it comes out like this in the document:

    <meta name="description" content="[u'This is the description']">

I thought it could be something with the encoding of the markdown file. I'm currently using ANSI. If switching to UTF-8, the line is shown in the top of the generated page and no meta description is added. 

After reading about it I found out, that it's the default serialization of a list in Python (don't know much about Python). So using `page.meta.description[0]` in the template works. But I'm thinking there may be another way of telling MkDocs, that this isn't a list?

**Comment by waylan** [comment]
There was a failed attempt to address this in #713. I know there was a discussion about it somewhere, but I can't find it with a quick search. In any event, being able to address this was part of a much bigger refactor of the Markdown handling code. Its on the roadmap, but we haven't gotten to it yet.

**Comment by ThomasArdal** [comment]
Thanks
