### ISSUE TITLE
Unable to access fonts.googleapis.com in China.

### ISSUE THREAD

**Issue by hifall** [mkdocs/mkdocs#1138]
Not sure if this is a concern of yours, but I am reporting it anyways.

I notice that mkdocs-generated docs refer to fonts.googleapis.com for font files. As you know, Google sites are blocked in China, including fonts.googleapis.com. Therefore, when a user in China tries to access a mkdocs-generated document, it will take him like 10-20 seconds for the browser to time out accessing fonts.googleapis.com, then the rest of the content shows up. This gives an impression that the docs are slow in China.

Thanks.

**Comment by d0ugal** [comment]
It is possible to solve this with a custom theme.

Is there a way we can make it fail faster?

**Comment by waylan** [comment]
So I did some searching and it seems that China has blocked, then unblocked, then blocked, then unblocked ... various googleapis.com sites. The common solution is to simply not use googleapis.com. At least three resources ([here][1], [here][2], and [here][3]) suggest a mirror of fonts.googleapis.com (`fonts.useso.com`) which is actually hosted in China, the second suggesting to use a script to only use the mirror if the user is actually in China. 

As far as I can tell, we have three options:

1. Add the files to the theme for self-hosting
2. Use the Chinese hosted mirror as a fallback
3. Do nothing and leave those in China behind

[1]: https://chineseseoshifu.com/blog/google-fonts-instable-in-china.html
[2]: http://www.hongkiat.com/blog/google-fonts-china/
[3]: https://www.reddit.com/r/China/comments/2jo9yn/mirror_for_google_fonts/

**Comment by waylan** [comment]
Just found [this][1] which suggests a way to use a local copy of a font if the user has it installed locally. Not sure if that is a sensible alternative for this sort of problem or not.

[1]: http://stackoverflow.com/a/13264619/866026

**Comment by patatetom** [comment]
hi,
the same problem appears on a mkdoc provided a lan without internet access... :-(
regards, lascaP.

**Comment by waylan** [comment]
It occurs to me that we could provide a Plugin (support for which will be available in the next release) which provided the font files. If the plugin is activated, then a build would include the font files locally. That way we make it a user decision. This would work for those who are doing development on a local system without internet access. 

My one hesitation is that the default behavior doesn't solve the China problem. Why would the default not work everywhere? Unfortunately, including the font files by default and having a Plugin exclude them as an option is a little more difficult to do.

Unless we can make this work with theme inheritance though the new theme customization support coming in the next release... Hmmm......

**Comment by tomchristie** [comment]
I guess ideally our built-in themes ought to just self-serve any resources they use.

**Comment by coliff** [comment]
> I guess ideally our built-in themes ought to just self-serve any resources they use.

An alternative approach is what Medium, Bootstrap and others do and use a native font stack so no external or bundled fonts are needed.

REF: https://getbootstrap.com/docs/4.1/content/reboot/#native-font-stack

**Comment by tomchristie** [comment]
Yup totally up for that. PRs very welcome.

**Comment by evitalis** [comment]
Stumbled upon this coming from mdbook, the latest reference issue, and would also like to see less embedded Google if possible in the mkdocs output. Since this issue was last updated awhile ago I was curious if work has happened since I am not familiar with the mkdocs code.

**Comment by waylan** [comment]
As stated int he last comment, PRs are welcome.

**Comment by enricobasso** [comment]
[W3C validator](https://validator.w3.org/) also says this:
![image](https://user-images.githubusercontent.com/9715230/61785974-14e6f900-ae0d-11e9-99f5-1c9ae1418b03.png)

I know that this is the correct syntax given by Google but still it's a error.

**Comment by Gunni** [comment]
I would like to add that courts have rules that linking stuff like fonts or js to content hosts in the US violates GDPR.

For example: https://thehackernews.com/2022/01/german-court-rules-websites-embedding.html

We have a Content Security Policy that blocks these requests, thankfully, but we would appreciate it if you just embedded the font files with the application.

**Comment by ultrabug** [comment]
AFAIK there's no mention or hardcoded URL downloading of fonts from Google in the mkdocs project (at least not anymore?)

@Gunni would you care to share more details about what you think should be done here? or provide an example of what you would expect to be "fixed"?

Then I'll allow myself to close this issue.

**Comment by Gunni** [comment]
> what you think should be done here?
Use default fonts, don't use special fonts. The defaults/fallback fonts look fine.

**Comment by ultrabug** [comment]
Closing then, mkdocs shipped themes do not use fonts downloaded from google
