### ISSUE TITLE
Nesting multiple navigation levels.

### ISSUE THREAD

**Issue by Carbowix** [mkdocs/mkdocs#1139]
is it Possible to put a extension inside another extension.

For example there is a Extension called "Guide"

Which you click and opens like 4 more things. is it possible to make another extension inside the "Guide"

**Comment by waylan** [comment]
I'm not sure what you mean. We support [Markdown Extensions][1], but I'm not familiar with an extension named "Guide". You certainly wouldn't put Markdown Extensions inside one another, although I suppose the syntax from one could be nested in the syntax for another. That is a Markdown question, not a McDocs specific question and the answer would depend on how the extension was implemented and whether the developers of the extension support it. I would suggest asking your question to the developers of the specific extension you are referring to.

If, on the other hand, you mean something other than a Markdown Extension, then you will need to provide more specific information. Could you provide an example of what you want to do, what you have tried and how that does not meet your needs?

[1]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by Carbowix** [comment]
For Example in this Picture in the link.
[image](http://imgur.com/a/Yf54P)

There is in the tab section called "User Guide" when you press it. it opens 4 more options to be opened. that is the extension. My Question is that if its possible to create another extension inside that extension.
For example I want to put more option for the section called "Configuration".

That is all i can explain to you.

thanks in advance

**Comment by waylan** [comment]
Ah, that is not called an "extension" which is what confused me. You want [multilevel navigation][1]. Have you tried adding more levels? Can you provide an example of what you have in your config? How it that not working for you?

[1]: http://www.mkdocs.org/user-guide/writing-your-docs/#multilevel-documentation

**Comment by Carbowix** [comment]
Well i didn't try it yet, because i didn't know about it.

at first i tried to do this

 - Extensions:
    - Admonition: extensions/admonition.md
                          - CodeHilite: extensions/codehilite.md

Thought it would do another extension, but it failed. That is why i came here to ask.

**Comment by waylan** [comment]
A parent nav item (one which contains children) cannot have a page attached to it. It either has a single page, or a nested list of pages, not both. Like this:

```yaml
- Home: index.md
- Parent:
    - 'Nested Page': 'somepage.md'
    - 'Nested Parent':
        - 'Nested nested page': `someotherpage.md`
```

Note that after a colon (`:`) you either have a path to a page (on the same line)  or a nested list (on the next line), but not both.

**Comment by Carbowix** [comment]
Okay Thank you so much for the Help. I appreciate it. You saved me now from thinking for days lol.

You can close the case now.

**Comment by erinallard-infoscout** [comment]
@waylan Thank you for your response last year about how a Parent nav item can either have a page attached to it or a nested list of pages below it, but not both. I kept trying to do both and was getting an error I didn't understand. I wish your comment was included in the official mkdocs documentation! Thanks again.

**Comment by parthi2929** [comment]
> A parent nav item (one which contains children) cannot have a page attached to it. It either has a single page, or a nested list of pages, not both. Like this:
> 
> ```yaml
> - Home: index.md
> - Parent:
>     - 'Nested Page': 'somepage.md'
>     - 'Nested Parent':
>         - 'Nested nested page': `someotherpage.md`
> ```
> 
> Note that after a colon (`:`) you either have a path to a page (on the same line) or a nested list (on the next line), but not both.

Hi
Can you please share why it is so? I sometimes very much need a page for the folder level to give an introduction about the sections under that.

**Comment by waylan** [comment]
@parthi2929 For starters, the suggested example provided by @Carbowix is invalid YAML. In other words, YAML itself forces the rule. Of course, there could be other solutions, which have been discussed extensively in #73. A solution was attempted in #1042, but was abandoned due to numerous problems.

In the end, we settled on sorting pages so that an auto-generated nav would list an index file (`index.md`) as the first item within a parent with the expectation that themes could detect that and do something special with it (use it as the "folder level page").  In other words, MkDocs provides the mechanism for it to be possible as long as themes provide support to display it correctly. However, I'm not aware of any themes which have implemented support for it yet.

**Comment by parthi2929** [comment]
Thanks for detailed explanation. I tried having index.md in folder (apart from main one), with hope that it would be picked up as page for folder, but it did not, instead shown as another section under folder. I used RTD theme.

**Comment by waylan** [comment]
> I used RTD theme.

Note that the `readthedocs` theme is a direct clone of the upstream Sphinx theme by the same name and will only ever support features included in the upstream theme. As the upstream theme does not support this feature, then our clone never will either.

**Comment by mehrad-meraji** [comment]
How does one access the file structure built by mkdocs? Is there a variable to access through the template to try and detect the index.md file in every folder? Specifically trying to accomplish what @waylan mentioned:

> MkDocs provides the mechanism for it to be possible as long as themes provide support to display it correctly. However, I'm not aware of any themes which have implemented support for it yet.

I've been trying using the ``nav`` variable but it doesn't look like it includes all the routes that mkdocs has access to.

could someone point me in the right direction?

**Comment by mehrad-meraji** [comment]
How does one access the file structure built by mkdocs? Is there a variable to access through the template to try and detect the index.md file in every folder? Specifically trying to accomplish what @waylan mentioned:

> MkDocs provides the mechanism for it to be possible as long as themes provide support to display it correctly. However, I'm not aware of any themes which have implemented support for it yet.

I've been trying using the nav variable but it doesn't look like it includes all the routes that mkdocs has access to.

could someone point me in the right direction?

**Comment by waylan** [comment]
@mehrad-meraji the idea is that the `nav` structure would look something like this:

```yml
nav:
    - Home: index.md
    - Parent:
        - foo/index.md
        - Other child: foo/otherchild.md
```

You would then need to create a theme template which built the desired HTML from that `nav` structure. In other words, the template should detect that the first child of `Parent` is an index file and use that as the URL for the `Parent` item. However, that same template would need to not include that same index file in the list of child pages. Again, this all needs to happen in the template itself.

**Comment by waylan** [comment]
For anyone who is interested in working on a solution for this, I provided some more details about how I envision this working [here](https://stackoverflow.com/a/54598748/866026).
