### ISSUE TITLE
Relative or absolute links assigned to a variable?

### ISSUE THREAD

**Issue by happicamper** [mkdocs/mkdocs#1143]
Hello pips!
Is there a way that I can declare links something like this in a markdown file:
```
mydocs.md
[URL1]: mydocs/index.md
[URL2]: mydocs/index2.md
[URL3]: mydocs/index3.md
```
then another **markdown file** recycles or use these already declared links something like this:
```
mynewdocs.md
Hello my [index][URL1] and also [index2][URL2]
```
Thank you in advance!

**Comment by waylan** [comment]
There is no Markdown standard for this. However, you should be able to accomplish something like that with the [Markdown Include Extension][1]. See the documentation for how to use [Markdown extensions][2] with MkDocs.

[1]: https://github.com/cmacmackin/markdown-include/#markdown-include
[2]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by happicamper** [comment]
Can you please guide me more with this installation, I really don't have an idea where to put those codes in order to run the extension. Sorry for the request! Hope you can help me further, thanks!

**Comment by happicamper** [comment]
Nevermind hehe I just need to clear my mind before asking these things. Thanks for the answer @waylan once again you helped.
