### ISSUE TITLE
What is the default theme for MkDocs? And where I can find the codes?

### ISSUE THREAD

**Issue by notalentgeek** [mkdocs/mkdocs#1145]
I want to make my own navigation bar, but there is no documentation on `{{nav}}` and its properties. Since, all what I need is in the default theme (http://www.mkdocs.org/), I would like to see the sources for the default theme.

**Comment by d0ugal** [comment]
https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/mkdocs

This is specifically what you need: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/nav.html

Also see a simple example here: https://github.com/mkdocs/mkdocs-basic-theme/blob/master/basic_theme/nav.html

We should do a better job of documenting this.
