### ISSUE TITLE
How can I manipulate string in `{{ nav_child.title }}`?

### ISSUE THREAD

**Issue by notalentgeek** [mkdocs/mkdocs#1147]
This is what I have.

![http://i.imgur.com/YUj97Pl.png](http://i.imgur.com/YUj97Pl.png)

Let say I want,

* "Pc ut linear algebra".
* "Example exam".
* ....

to be all in lower case. How can I achieve that?

**Comment by d0ugal** [comment]
You can do it either in the Jinja2 template `{{ nav_child.title.lower() }}` or with CSS `text-transform: lowercase;`.

The Jinja2 template designer documentation may be useful for you. http://jinja.pocoo.org/docs/2.9/templates/
