### ISSUE TITLE
First line bullet of `<ul>` is always not rendered when using custom theme I made.

### ISSUE THREAD

**Issue by notalentgeek** [mkdocs/mkdocs#1148]
Here is an example of my MarkDown codes.

![http://i.imgur.com/LBi9UoN.png](http://i.imgur.com/LBi9UoN.png)

Here is what it is rendered in the web page using my custom theme.

![http://i.imgur.com/8E9ZodX.png](http://i.imgur.com/8E9ZodX.png)

There is no problem with the default theme.

![http://i.imgur.com/1fcmGqX.png](http://i.imgur.com/1fcmGqX.png)

Here is my codes for the custom theme.

    <!DOCTYPE html>
    <html>
      <head>
        <link
          href="{{ base_url }}/css/bootstrap.min.css"
          rel="stylesheet"
        >
        <link
          href="{{ base_url }}/css/metis.css"
          rel="stylesheet"
        >
        <link
          href="{{ base_url }}/css/metisMenu.min.css"
          rel="stylesheet"
        >
        <title>{% if page_title %}{{page_title}} - {% endif %}{{site_name}}</title>
      </head>
      <body>
        <aside class="sidebar">
          <nav class="sidebar-nav">
            <ul
              class="metismenu"
              id="ntg-metismenu"
            >
              {% for nav_child in nav %}
                {% if nav_child.children %}
                  <li>
                    <a
                      aria-expanded="false"
                    >{{ nav_child.title }}</a>
                    {% include "nav_sub.html" %}
                  </li>
                {% else %}
                  <li>
                    <a
                      class="ntg-link"
                      href="{{ nav_child.url }}"
                    >{{ nav_child.title }}</a>
                  </li>
                {% endif %}
              {% endfor %}
            </ul>
          </nav>
        </aside>
        {{ content }}
        <script src="{{ base_url }}/js/jquery.min.js"></script>
        <script src="{{ base_url }}/js/bootstrap.min.js"></script>
        <script src="{{ base_url }}/js/metisMenu.min.js"></script>
        <script>
          $("#ntg-metismenu").metisMenu();
        </script>
      </body>
    </html>

What is wrong with my custom theme?

**Comment by notalentgeek** [comment]
Nevermind I solved this. This was caused by `float: left;` in `<aside class="sidebar">` for whatever the reason was XD.

**Comment by waylan** [comment]
I'm guessing this is related to your CSS and not related directly to MkDocs. Therefore it is beyond our ability to help you debug. You might want to find an appropriate site to ask CSS related questions and post the HTML fragment (generated by your Markdown) and your CSS and see if someone who is more experienced can assist you.

Finally, GitHub Issues is for reporting bugs (and making feature requests ) in MkDocs itself. For support questions, we would prefer you use the [mailing list][1].

[1]: https://groups.google.com/forum/#!forum/mkdocs

**Comment by notalentgeek** [comment]
True it was actually. Sorry.

**Comment by notalentgeek** [comment]
@waylan, it is listed in the MkDocs homepage. So I thought I asked here because I hate Google Group.

    Getting help
    To get help with MkDocs, please use the discussion group, GitHub issues or the MkDocs IRC channel #mkdocs on freenode.

**Comment by waylan** [comment]
Yes, that's the one. It's also listed in the [README][1]:

> * Discussions and support: https://groups.google.com/forum/#!forum/mkdocs

[1]: https://github.com/mkdocs/mkdocs/blob/master/README.md
