### ISSUE TITLE
toc extension permalink id do not support utf8 first character

### ISSUE THREAD

**Issue by ngtrian** [mkdocs/mkdocs#1158]
I using toc extension with mkdocs.

toc can not convert character  bellow to id:

> đ

**Comment by waylan** [comment]
This needs to be handled upstream by the Python-Markdown project. As the same report has been made there waylan/Python-Markdown#555, I'm closing this.

**Comment by waylan** [comment]
Oh and this is technically a duplicate of #212 which contains a workaround to get a working solution for MkDocs.

**Comment by ngtrian** [comment]
Thanks for support!
