### ISSUE TITLE
mkdocs gh-deploy --skip-build

### ISSUE THREAD

**Issue by fredrikaverpil** [mkdocs/mkdocs#1165]
I'm trying to figure out a way to `mkdocs gh-deploy` into a specific folder inside of my `gh-pages` branch.

I think this could be solved by:
1. Building the docs with `mkdocs build` and making sure my "site" folder has the desired structure.
2. Perform a `mkdocs gh-deploy` without re-building the docs automatically (meaning, skipping the build prior to the deploy).

This would mean another option is needed to `mkdocs gh-deploy` such as `--skip-build`.

What do you think?

**Comment by fredrikaverpil** [comment]
Could something like this work?

```python
skip_build_help = "Skip building prior to deploying (not default)."
```

```python
@cli.command(name="gh-deploy")
@click.option('-c', '--clean/--dirty', is_flag=True, default=True, help=clean_help)
@click.option('-f', '--config-file', type=click.File('rb'), help=config_help)
@click.option('-m', '--message', help=commit_message_help)
@click.option('-b', '--remote-branch', help=remote_branch_help)
@click.option('-r', '--remote-name', help=remote_name_help)
@click.option('--skip-build', is_flag=True, help=skip_build_help)
@click.option('--force', is_flag=True, help=force_help)
@common_options
def gh_deploy_command(config_file, clean, message, remote_branch, remote_name,
                      skip_build, force):
    """Deploy your documentation to GitHub Pages"""
    try:
        cfg = config.load_config(
            config_file=config_file,
            remote_branch=remote_branch,
            remote_name=remote_name
        )
        if skip_build:
            build.build(cfg, dirty=not clean)
        gh_deploy.gh_deploy(cfg, message=message, force=force)
    except exceptions.ConfigurationError as e:  # pragma: no cover
        # Avoid ugly, unhelpful traceback
        raise SystemExit('\n' + str(e))
```

**Comment by waylan** [comment]
Sounds like this would be out-of-scope to me. As I see it, our tool is for MkDocs only. If you want to wrap it in something else, then that is not something we want to maintain. As it is, the `gh-deploy` command is just a thin wrapper around [ghp-import][1] with some sensible defaults which are specific to MkDocs (plus a call to build). For your use case, you can call `mkdocs build`, then call `ghp-import` directly which gives total control to tune the setup just the way you want it. While you have two commands to run, your proposal required that anyway. You could always wrap it all up on a little shell script with your options coded in.

As an aside, as part of our effort to add a Plugin API (see #206), one of the things we have discussed is the possibility of providing a mechanism for people to include their own deploy scripts. If that happens, then the current command would go away in favor of the new system. At that time, you could make your deploy script do as you want. Until then, I don't see the point in expanding the current solution.

[1]: https://github.com/davisp/ghp-import

**Comment by fredrikaverpil** [comment]
@waylan Many thanks for taking the time for the write up! 👍 This all makes total sense to me!
Closing this issue.

**Comment by fareszr** [comment]
for future vistors use this for github actions:

    - name: mkdocs build
      run: mkdocs build --clean --verbose 

    - name: ghp-import
      run: |
        git config user.name "{botname}"
        git config user.email "{botmail}"
        ghp-import -m "{botname} deploy (${GITHUB_SHA:0:7})" -p site
