### ISSUE TITLE
Version 1.0 Roadmap

### ISSUE THREAD

**Issue by waylan** [mkdocs/mkdocs#1166]
The following is my proposal for moving forward with version 1.0:

As previously discussed, we intend to release 1.0 as the next (major and minor) release after 0.16. However, there are still a few bug fix (micro) releases in the 0.16 release cycle. Therefore, I have created the [1.0.dev] branch which tracks all 1.0 specific changes. Pull requests for 1.0 features should be applied to the 1.0.dev branch. Any bug fixes in the master branch should be ported to the 1.0.dev branch as well.

The actual work to be included in version 1.0 is the collection of issues and pull requests with the [1.0.0 milestone]. The actual issues included in that milestone may change over time (items added or subtracted as per discussions int he individual issues), but the release will be ready when no open issues remain in the milestone. As GitHub allows the issues to be reordered, I may occasionally reorder them to reflect the order in which specific issues are being worked on (i.e., the plugin API gets completed before search specific issues get started as search is being moved to a plugin), but that doesn't mean the order is a hard and fast rule.

The first unique commit (8c9773d) on the 1.0.dev branch bumps the version to `1.0.dev` (this way we avoid confusion. For example, pip won't download dev versions from PyPI if we accidentally upload from the wrong branch). The final commit should bump the version to `1.0.0`. There could be alpha, beta, or release candidate versions, but I'm not sure if we need/want them. It is also unclear when the 1.0.dev branch will be merged with master. At the latest it would be when the version is bumped to `1.0.0`, but it could be earlier. Those discussions can happen in the comments below as we move forward in development.

One final question: **Should the bug fixes in master be *merged* to the 1.0.dev branch, or should we *rebase* them?** If we merge, then they will be interspersed within the 1.0 specific commits. If we rebase, then all of the 1.0 commits will be on top of the 0.16 bugfix commits (a more logical order), but that rewrites the commit history each time and be rather inconvenient for anyone who is tracking changes locally (I think they can use `git fetch --force` etc, buts its more steps). I like the idea of a cleaner commit history, but understand if we decide against it.

[1.0.dev]: https://github.com/mkdocs/mkdocs/tree/1.0.dev
[1.0.0 milestone]: https://github.com/mkdocs/mkdocs/milestone/4

**Comment by trel** [comment]
Hooray for imminent 1.0.

Please don't rebase across branches.  `--force` (in perhaps all cases) should be reserved for having to fix up something that is broken, in my opinion.  I hope the 'normal process' will not require `--force`.

Cherry-pick any specific commits across branches and use the helpful GitHub comment linking to talk about any confusing work that might be happening.  Most users won't care later, but it's nice for archeologists who may stumble in here.

**Comment by waylan** [comment]
@trel good points. I rebase across branches all the time. But that is always for a feature specific branch (perhaps attached to a single PR), which is very different than this. Its reasonable to believe that multiple people will be tracking the 1.0.dev branch, so it makes sense to avoid that. I asked to get just that sort of feedback. Thanks.

**Comment by waylan** [comment]
FIY, I just merged the 1.0.dev branch into master (#1296).

The 1.0.dev branch should now be inactive. **All future development should happen on the *master* branch.**

In the event that any additional 0.16.x bug-fix releases need to be made, a [0.16][1] branch has been created (at the last commit before the merge), which bug-fixes can be back-ported to from master.

[1]: https://github.com/mkdocs/mkdocs/tree/0.16

**Comment by d0ugal** [comment]
Nice! :+1:

**Comment by d0ugal** [comment]
This plan seems okay to me. I do find it a bit strange to have so many braking changes in a minor release (so number 4 is the only one that bothers me). 

How many other 1.0 plans are backwards incompatible? We could just release 1.0 and then continue adding new features in 1.1 etc.

**Comment by waylan** [comment]
> How many other 1.0 plans are backwards incompatible? We could just release 1.0 and then continue adding new features in 1.1 etc.

I considered that. However, for features like those proposed in #989 and/or #699 I believe there is the possibility for some major behavioral changes that need to happen before 1.0. I have some preliminary work done on that, but there is a lot more to do.

> I do find it a bit strange to have so many braking changes in a minor release. 

I understand, which is why I suggested we make the transition a little smother. I expect I'll add a few warnings back in (without changing the behavior).

**Comment by waylan** [comment]
Today I went through all the open issues in the 1.0 Milestone and moved a bunch to the Post-1.0 Milestone. The 1.0 milestone is just too big and taking way longer than we initially anticipated. Anything that I saw as non-essential got bumped off. What remains are mostly deep behavioral changes which would require a major version bump to release. All the bumped issues are enhancements which can be included in future minor releases.

The biggest items are now included in the two projects [Pages Refactor] and [Refactor search]. The majority of open issues in the 1.0 Milestone are in one of those two projects. What remains after that is mostly minor bug fixes, documentation and cleanup stuff.

[Pages Refactor]: https://github.com/mkdocs/mkdocs/projects/2
[Refactor search]: https://github.com/mkdocs/mkdocs/projects/1

**Comment by waylan** [comment]
We are down to two issues in the 1.0 Milestone (including this issue). #1502 is simply waiting on a design decision which we haven't gotten to yet. I just triaged all open issues not in the 1.0 Milestone and did not find any which should be moved to the 1.0 Milestone except possibly #1543 (we are waiting on info to determine if it is a bug).

Therefore, it appears that we are one or two commits away from releasing version 1.0!

**Comment by d0ugal** [comment]
Amazing. Fantastic job.

**Comment by waylan** [comment]
Just pushed 1.0 Alpha 1 in #1550. Approximately once a week I'll move to the next step (beta, RC, final). Everyone, please test and provide feedback.

**Comment by itviewer** [comment]
thank you!

**Comment by waylan** [comment]
Version [1.0 Beta 1][1] has just been released.

[1]: https://pypi.org/project/mkdocs/1.0b1/

**Comment by waylan** [comment]
Version [1.0 Release Candidate 1][1] has just been released. 

If there are no changes over the next week, this will become 1.0 Final in a week (aprox. August 3rd). If we have any changes within the next week, then 1.0rc2 will be released next week. This could be your last change to provide feedback.

[1]: https://pypi.org/project/mkdocs/1.0rc1/

**Comment by waylan** [comment]
[Version 1.0 Final][1] is released:exclamation:  :tada: :tada: :exclamation: 

Thanks to everyone who contributed. :+1:  :1st_place_medal:

[1]: https://pypi.org/project/mkdocs/1.0/

**Comment by d0ugal** [comment]
Well done! A great achievement!

**Comment by timani** [comment]
Waited for today, like a kid on Christmas. Excellent work everyone 👏
