### ISSUE TITLE
AttributeError: iter after mkdocs serve

### ISSUE THREAD

**Issue by abayob** [mkdocs/mkdocs#1191]
Heya,

I am trying to get Mkdocs to work on a Centos version 6.8 machine.
I have Python version 2.6.6 installed.

I have done the following:

1. First I created a new project:
`sudo mkdocs new abayodocs`
This worked like a charm.

2. Then I tried to start the preview mode:
`sudo mkdocs serve`

But this is not working:

> WARNING: Support for Python 2.6 will be dropped in the 1.0.0 release of MkDocs
> INFO    -  Building documentation...
> INFO    -  Cleaning site directory
> /usr/lib/python2.6/site-packages/markdown/__init__.py:259: DeprecationWarning: Using short names for Markdown's builtin extensions is deprecated. Use the full path to the extension with Python's dot notation (eg: "markdown.extensions.meta" instead of "meta"). The current behavior will raise an error in version 2.7. See the Release Notes for Python-Markdown version 2.6 for more info.
>   DeprecationWarning)
> /usr/lib/python2.6/site-packages/markdown/__init__.py:259: DeprecationWarning: Using short names for Markdown's builtin extensions is deprecated. Use the full path to the extension with Python's dot notation (eg: "markdown.extensions.toc" instead of "toc"). The current behavior will raise an error in version 2.7. See the Release Notes for Python-Markdown version 2.6 for more info.
>   DeprecationWarning)
> /usr/lib/python2.6/site-packages/markdown/__init__.py:259: DeprecationWarning: Using short names for Markdown's builtin extensions is deprecated. Use the full path to the extension with Python's dot notation (eg: "markdown.extensions.tables" instead of "tables"). The current behavior will raise an error in version 2.7. See the Release Notes for Python-Markdown version 2.6 for more info.
>   DeprecationWarning)
> /usr/lib/python2.6/site-packages/markdown/__init__.py:259: DeprecationWarning: Using short names for Markdown's builtin extensions is deprecated. Use the full path to the extension with Python's dot notation (eg: "markdown.extensions.fenced_code" instead of "fenced_code"). The current behavior will raise an error in version 2.7. See the Release Notes for Python-Markdown version 2.6 for more info.
>   DeprecationWarning)
> ERROR   -  Error building page index.md
> Traceback (most recent call last):
>   File "/usr/bin/mkdocs", line 11, in <module>
>     sys.exit(cli())
>   File "/usr/lib/python2.6/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python2.6/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python2.6/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.6/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python2.6/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python2.6/site-packages/mkdocs/__main__.py", line 127, in serve_command
>     livereload=livereload
>   File "/usr/lib/python2.6/site-packages/mkdocs/commands/serve.py", line 110, in serve
>     config = builder()
>   File "/usr/lib/python2.6/site-packages/mkdocs/commands/serve.py", line 106, in builder
>     build(config, live_server=live_server, dirty=dirty)
>   File "/usr/lib/python2.6/site-packages/mkdocs/commands/build.py", line 380, in build
>     build_pages(config, dirty=dirty)
>   File "/usr/lib/python2.6/site-packages/mkdocs/commands/build.py", line 333, in build_pages
>     dump_json)
>   File "/usr/lib/python2.6/site-packages/mkdocs/commands/build.py", line 189, in _build_page
>     site_navigation=site_navigation
>   File "/usr/lib/python2.6/site-packages/mkdocs/commands/build.py", line 59, in convert_markdown
>     extension_configs=config['mdx_configs']
>   File "/usr/lib/python2.6/site-packages/mkdocs/utils/__init__.py", line 366, in convert_markdown
>     html_content = md.convert(markdown_source)
>   File "/usr/lib/python2.6/site-packages/markdown/__init__.py", line 375, in convert
>     newRoot = treeprocessor.run(root)
>   File "/usr/lib/python2.6/site-packages/markdown/treeprocessors.py", line 361, in run
>     brs = root.iter('br')
> AttributeError: iter

Is it the Python version, or am I doing something wrong?

**Comment by waylan** [comment]
Yes that error is definitely related to Python 2.6. It is being raised by the Python-Markdown library, which MkDocs uses under the hood. Recent versions of Python-Markdown do not support Python 2.6. You don't specify how you installed MkDocs, but if you used our install script we set a maximum version of Python-Markdown which works (2.5). If you have a more recent version then this error would be expected.

**Comment by abayob** [comment]
Ah, I forgot to mention that. I followed your guide by the point.
I first had to install pip. I did that with the provided get-pip.py (linked from your page).
After that I installed mkdocs with the pip install command.

I will check the version of Python-Markdown tomorrow. So hopefully that is the issue.
Upgrading the Python version requires more work and can raise issues on a Centos server, so I would like to do that as a final resolution.

**Comment by abayob** [comment]
@waylan I checked the Markdown version with the following:
`pip freeze | grep Markdown
Markdown==2.6.8`

So the Markdown version is too high for Mkdocs if I understand what u mean.
This should've been mentioned during the installation? 
Is it a fatal condition, or just a notice?
I could've missed the notice?

**Comment by waylan** [comment]
My guess is you already had Markdown installed prior to installing MkDocs. However, any version of Markdown after 2.5 will not work on Python 2.6. You either need to find an older version of Markdown which works (MkDocs supports Markdown all the way back to version 2.3.1) or update to a newer version of Python.

**Comment by abayob** [comment]
Thank you, that did the trick.
I installed a version before 2.5 and everything seems to work great.

Thank you for the support!
