### ISSUE TITLE
Using ENV variables in mkdocs.yml

### ISSUE THREAD

**Issue by squidfunk** [mkdocs/mkdocs#1195]
This is more of a question - is there some way to use ENV variables in `mkdocs.yml`? The thing is that I want to automatically deploy to gh-pages when the build is successful, but I don't want to expose my Google Analytics tokens. Would be awesome!

**Comment by squidfunk** [comment]
Digging into PyYAML, I can answer my own question:

``` yaml
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_TOKEN"]
  - auto
```

**Comment by majkinetor** [comment]
@squidfunk , do you know if it is possible to add non strings this way ?

This doesn't work:

```
plugins:
    - search
    - pdf-export:
        combined: !!python/object/apply:os.getenv ["PDF_EXPORT_COMBINED"]
```

The build complains that string is not boole value - `combined` value must be true/false, not string 'true'/'false'.

I looked into PyYAML section _YAML tags and Python types_[^1] to no avail. I guess form:

>  !!python/object/apply:module.f | value of f(...)

could be used as I need pythons `distutils.util.strtobool( os.getenv("PDF_EXPORT_COMBINED") )` but not sure if that is possible using that syntax.




[^1]: https://pyyaml.org/wiki/PyYAMLDocumentation

**Comment by squidfunk** [comment]
@majkinetor don't know, sorry. I'm not proficient in Python.

**Comment by mendax1234** [comment]
> Environment variables can be loaded as explained here in the Mkdocs documentation:
https://www.mkdocs.org/user-guide/configuration/#environment-variables

Hi, after reading the mkdocs site, l still have some problems with ENV variables in mkdocs. If l use this line `site_name: !ENV SITE_NAME`, where can l define the value of `SITE_NAME`? @evolve2k Thank you very much!

**Comment by squidfunk** [comment]
For example when invoking `mkdocs build`:

```
SITE_NAME="https://example.com" mkdocs build
```

**Comment by evolve2k** [comment]
The idea is that you define it in your system enviroment variables.

For example:
$ export SITE_NAME="My personal blog"

then you should be able to run your build.

$ mkdocs build

Depending where you are deploying to for production, most production environments support you being able to add environment variables, both programtically and manually if its just for a few.

Here's two examples:
https://render.com/docs/configure-environment-variables

https://docs.netlify.com/environment-variables/overview

**Comment by mendax1234** [comment]
> For example when invoking `mkdocs build`:
> 
> ```
> SITE_NAME="My personal blog" mkdocs build"
> ```

Hi, thanks for your reply! @evolve2k @squidfunk  My initial purpose is not to expose my Google Analytics Token when deploying my mkdocs to gh-pages. And l notice that this line `property: !ENV GOOGLE_ANALYTICS_KEY ` is recommended. l have already set up an environment variable in my Github repo, but it seems that it doesn't work. Would you please provide me some instructions on how to set up it correctly. Thanks!

**Comment by evolve2k** [comment]
Where are you hosting your site?

**Comment by evolve2k** [comment]
On a server where you have shell access.. you'd be adding the environment varibles there just like you would on your local computer.

But for most modern deployment options where you dont have shell access.. you need to see how the place you're deploying to handles this.

In your case deploying to gh-pages, do a websearch for "Gh Pages Environment Variables".. my quick search found this on SO: https://stackoverflow.com/questions/53648652/how-to-use-environment-variables-in-github-page

**Comment by mendax1234** [comment]
> On a server where you have shell access.. you'd be adding the environment varibles there just like you would on your local computer.
> 
> But for most modern deployment options where you dont have shell access.. you need to see how the place you're deploying to handles this.
> 
> In your case deploying to gh-pages, do a websearch for "Gh Pages Environment Variables".. my quick search found this on SO: https://stackoverflow.com/questions/53648652/how-to-use-environment-variables-in-github-page

@evolve2k Thanks for your reply. l find that the secrets that l have created in GitHub are only used in Github Action, which only supports the `.yml` files in the workflow. However, if l want to use the secrets in `mkdocs.yml`, will that be the same? Thank you very much!
