### ISSUE TITLE
Pushing to gh-pages from Travis

### ISSUE THREAD

**Issue by squidfunk** [mkdocs/mkdocs#1196]
I'm trying to push my docs automatically to gh-pages with `mkdocs gh-deploy`, but I cannot find a guide which explains how to do this from inside Travis/CI. I already created an OAuth token for Travis - are there any environment variables to set or is there any standard way to follow in order to do this?

**Comment by waylan** [comment]
See #814 and #1082.

**Comment by squidfunk** [comment]
Thanks! Will investigate.
