### ISSUE TITLE
use of colspan and rowspan in mkdocs table

### ISSUE THREAD

**Issue by mehrotra-prateek** [mkdocs/mkdocs#1198]
Hello,

Can i make use of colspan and rowspan in mkdocs table?

**Comment by waylan** [comment]
MkDocs uses the [Python-Markdown Tables Extension][1]. That extension mirrors the syntax used by  [PHP Markdown Extra][2] (where the syntax is more fully documented). If that doesn't give you the features you want/need, then you may install and [configure][3] a [third party extension][4] which does (if one exists).

[1]: https://pythonhosted.org/Markdown/extensions/tables.html
[2]: http://www.michelf.com/projects/php-markdown/extra/#table
[3]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
[4]: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions

**Comment by waylan** [comment]
Closing this is this appears to be a support question which has been answered.

**Comment by rehevkor5** [comment]
Fixed link: https://python-markdown.github.io/extensions/tables/

It appears possible to use eg. `{ rowspan=2 }`, but you end up with an extra cell in the other row, even if it's not present in your Markdown.

**Comment by sennewood** [comment]
@rehevkor5 May you post an example where to put `{ rowspan=2 }` in a table?

**Comment by ScottNotFound** [comment]
@sennewood You put it immediately after any text that will become part of the element you want to modify. You just need the `attr_list` extension.

You can also make the extra cell disappear with some style modifications.

with extra cell
```
| fruit | definition |
|-------|------------|
| Apple | Pomaceous fruit of plants of the genus Malus in the family Rosaceae. {: rowspan=2} |
| Also Apple | 
```

make the extra cell go away
```
| fruit | definition |
|-------|------------|
| Apple | Pomaceous fruit of plants of the genus Malus in the family Rosaceae. {: rowspan=2} |
| Also Apple | &#8288 {: style="padding:0"} |
```

These are the results with the material theme.

![image](https://user-images.githubusercontent.com/25657066/191550360-574f5b3a-fdcc-47b2-b4c6-278d511f5173.png)
