### ISSUE TITLE
disable markdown rendering on a section

### ISSUE THREAD

**Issue by anantshri** [mkdocs/mkdocs#1200]
is there an option where we do not render markdown on a file and directly print it as in on the page. something like {{ content.raw }} 

Experimenting on something and i need 1-2 pages where the markdown should not be rendered as html but available as markdown itself. in some cases for client side rendering.

**Comment by facelessuser** [comment]
1. You can put it under HTML (but there can be some pre-processors, such as fenced code, where this won't work quite right).
2. You can escape the Markdown.
3. You can put in some placeholders and use a post processing script to inject it after rendering.
4. You can write your own Python Markdown extension to create some syntax that will preserve Markdown content between some delimiters.
5. Maybe something else.

So there are ways, you may just need to be creative and find/create something that works well for you.

**Comment by anantshri** [comment]
thanks i think i got some ideas. closing the issue.

**Comment by waylan** [comment]
Are you looking to have raw Markdown for a *section* of a page or for an entire page? If the former, then @facelessuser's answer is the only thing that would make any sense. If however, you mean the latter, this is actually possible in the 1.0.dev branch (which is under heavy development and not at all stable right now). In a template you can do `{{ page.markdown }}` which would give you the raw Markdown for the page (the relevant changes are in #1180). However, I can not make any guarantee that this will remain for the 1.0 release. Nor can I estimate when 1.0 will be ready for release.

**Comment by anantshri** [comment]
page.markdown seems more apt for my usecase. Thanks for the suggestion @waylan . I sincerily hope this makes it to the final release.

**Comment by waylan** [comment]
@anantshri was there a reason you reopened this? The change has already been committed so there is no more work to do and no reason to leave this open (we close an issue when the change is committed, not when a release is made).

**Comment by anantshri** [comment]
@waylan that makes sense. i thought keeping it open will act like a reminder that atleast someone needs page.markdown feature for 1.0. Feel free to close it if you think the work is done.
