### ISSUE TITLE
html table gets class names from mkdocs

### ISSUE THREAD

**Issue by sander76** [mkdocs/mkdocs#1203]
I have a "raw" html table inserted in my markdown file. On output it automatically gets classes added to it (table table-striped table-hover). Is there any way to avoid that ?

**Comment by waylan** [comment]
Could you provide a simple example (input and output)? Are you sure those classes are in the HTML output, not being added by some JavaScript? If its the later, then some theme alterations or using a different theme would solve your problem.

**Comment by waylan** [comment]
I just checked and the MkDocs theme does in fact have some JavaScript which assigns classes to tables. As this can be addressed by using a different theme (or modifying a existing theme) and we do not intend to alter the current default behavior, I'm closing this.
