### ISSUE TITLE
Moving to 'encode'?

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#1204]
Hi folks. I think we could consider MkDocs under the wing of [the 'encode' organisation](https://github.com/encode).
Granted I've not been contributing lately, but there's a few things that I think would make it a reasonable course of action...

* Having a bit of money coming in to pay for development time as needed is pretty valuable (eg. contracting out the theme redesign)
* We rely on MkDocs being well maintained for REST framework, and having both projects under the same governance would be helpful to us there.
* We're having to do plenty of work w/ Encode in order to ensure that REST framework is logistically and legally transferrable if it needs to be, and reducing the bus-factor there (eg. if I'm unable to work then we've still got money coming in, and can pass over the paid maintainership position) MkDocs might also benefit from being in the same situation here.
* Perhaps there's scope to extend the sponsorship model to include MkDocs?
* Both projects would benefit in terms of audience by being under the same banner. Branding-wise I'd be really happy to have them both under the Encode OSS umbrella, esp. given that MkDocs was created specifically *for* Django REST framework.

Along these lines it'd also be interesting to know if either @waylan or @d0ugal would be available for contracted time on the project if that's something we wanted to pursue at a later date?

Mainly asking this to @waylan and @d0ugal. Would either of you object if we went down this route? (And if so what would be needed to overcome those objections?)

**Comment by d0ugal** [comment]
I think I am fine with this idea. In reality I am not all that involved with MkDocs at the moment - I've been very inactive, @waylan has really been driving things and doing a great job.

Initially it sounds like there would be no immediate change, other than the location of the repo. Longer term I would be curious to hear what this means for the project - will encode become a place for a large number of projects or just a few?

I can't think of anything similar, my only point of comparison is with large open source foundations - like Apache or OpenStack. They have defines rules around governance etc. Are there plans to do something similar with encode?

@jazzband is possibly the closest comparison I can think of but I think the goals are quire different.

**Comment by tomchristie** [comment]
Just a few projects. Yup it'd mean shared governance.

**Comment by waylan** [comment]
I'm indifferent. Although, given the lack of help on the front-end development anything which helps that would be welcome.

**Comment by waylan** [comment]
@tomchristie what ever happened with this? If this is not happening, then we should probably close the issue.

**Comment by tomchristie** [comment]
I don’t know. Given that I’ve not been involved in development for ages it might be a bit odd moving under encode. On the other hand, I quite like the idea of having it under the same banner. 🤷‍♂️

**Comment by tomchristie** [comment]
@waylan I'm starting to consider getting back into `mkdocs` and taking on maintenance time under Encode. Obviously we're using it everywhere for Encode, but I bumped into the issue of finding it awkward for generating blogs or other non-documentation static sites, and have been diving into thinking about what changes we'd need to make in order to do a better job there. How interested would you be in considering a MkDocs 2 if it looked compelling?

**Comment by waylan** [comment]
> I bumped into the issue of finding it awkward for generating blogs or other non-documentation static sites, and have been diving into thinking about what changes we'd need to make in order to do a better job there. 

Personally, I like that MkDocs does one thing and, IMO, does it well. I prefer using a separate tool for a blog. 

In the 1.0 release we added support for including external URLs in the nav. And with a custom plugin, it wouldn't be difficult to combine an existing static blog generator and MkDocs for a complete site. In fact I currently have no vision for 2.0 as I feel like we offer pretty much everything we need to offer. Any major feature additions can be implemented as plugins.

That said, this is your project and you can take it wherever you want.

**Comment by tomchristie** [comment]
Fair enough! I’m going to plug away at what I’ve got for a bit and then sling an update here to give a bit more context.

**Comment by tomchristie** [comment]
@waylan I've been doing a bit of bumping along with https://github.com/tomchristie/mkdocs2 

What I like about the work that's there is how simple the build system is looking. I'm going to keep ticking over with it for a bit. 

There's a bunch of things I figure I'd want to try to address...

* Including API documentation.
* Simple Interlinking eg. `Link to [this topic](ref:Topic)` which automatically links to a `Topic` heading elsewhere in the site.
* Multi-version support.
* Multi-language.
* Some easy way of keep compatibility.

I'm also idling with the thought that if it seems to be progressing nicely then it might be worth also getting @squidfunk involved and figuring out if we could work towards a mkdocs 2.0 with the material theme as one of the defaults.

Anyways, really this is all just thinking aloud at the moment, but just wanted to nudge some ideas out there.

**Comment by squidfunk** [comment]
@tomchristie happy to help on the theme side. As already discussed via Twitter, I would regard downward compatibility and an easy upgrade path as one of the critical success factors. Some potential headaches:

- **Localization**: Material currently provides its own template-based I18N/L10N. What would themes need to provide to support multi-language builds? Would it be necessary to integrate I18N into MkDocs, so themes could then provide L10N?

- **Plugin architecture**: Material was first released before the new 1.x plugin architecture. One thing that is currently not possible is to pre-build the search index, because Material does heavy post-processing on the index to group search results in a user friendly way. How could we handle those kind of transformations? Should they be part of a plugin? There are some sites which have huge search indexes that would benefit from custom pre-building.

**Comment by squidfunk** [comment]
@tomchristie I'm not proficient in Python, but I understand `autodoc` as a docstring to Markdown converter, correct? The GIF which is included in the README already looks pretty good to me. I guess you're talking about including the styles that are specified in the README by default into Material? We can do that. Basically the same as with `pymdown-extensions`.

**Comment by tomchristie** [comment]
> I understand autodoc as a docstring to Markdown converter, correct?

Yeah, it adds a block type that you can use to automatically pull in Python docstrings & function signatures.

> I guess you're talking about including the styles that are specified in the README by default into Material?

Yeah, that.

Together with perhaps adding a section that's equivelent to `pymdown`, but specifically for mkautodoc. (Or wait until it's gotten some more usage, and then consider it)

**Comment by squidfunk** [comment]
> Together with perhaps adding a section that's equivelent to pymdown, but specifically for mkautodoc. (Or wait until it's gotten some more usage, and then consider it)

Sure. I like Material being used for more API-like documentation. If you would like to PR, you could add the styles in a new file called `_mkautodoc.scss` here:
https://github.com/squidfunk/mkdocs-material/tree/master/src/assets/stylesheets/extensions

... and of course some documentation on how to set it up, similar to `pymdown`. Regarding usage: `pymdown` was also pretty small when I started integrating it. However, it solves some more Markdown-y problems that `mkautodoc`, so I don't know, maybe wait a little? If it's stable and the CSS / HTML structure is not expected to change, I don't mind though.
