### ISSUE TITLE
Can not automatically reload the page 

### ISSUE THREAD

**Issue by zibuyule** [mkdocs/mkdocs#1208]
Hello,

I found that this version (0.16.3) can not automatically reload the page when the file is modified.
So I have to use the old version.

**Comment by waylan** [comment]
Are you sure you are on version 0.16.3? We had a bug in 0.16.2 related to this which was fixed in 0.16.3. Could you provide some more information so that we can replicate the problem?

**Comment by waylan** [comment]
As I can't reproduce the reported problem in the latest release and no additional information has been provided, this is being closed.
