### ISSUE TITLE
Integrity of edit_uri parameter whenever there is changes

### ISSUE THREAD

**Issue by happicamper** [mkdocs/mkdocs#1212]
Okay, I want to utilize the helpful button in MkDocs to edit files then redirect it to the repository whenever someone wants to fix something like typos. But my problem is that whenever there are changes that merged to master, the path of the repository changes e.g `src/00awe1231/docs/?at=master` to `src/00newmerge111/docs/?at=master` so with this changes my `edit_uri` with a value of `src/00awe1231/docs/?at=master` won't work and will display error 404 because the path changed. Btw, I'm using Bitbucket repository. Thank you so much for the help!

**Comment by waylan** [comment]
Yes, Bitbucket's URL scheme makes it difficult to have a working solution. There was some discussion about that when we implemented the feature in #269 and #978. As none of the maintainers actually use Bitbucket in our day-to-day work, it is not clear to us what the best approach is.

**Comment by waylan** [comment]
Based on [this comment](https://github.com/mkdocs/mkdocs/pull/978#issuecomment-229069266) it appears that there is no public URL to "edit" a specific page on Bitbucket. If or when that changes, this matter can be revisited.
