### ISSUE TITLE
TypeError: object of type '…' has no len()

### ISSUE THREAD

**Issue by ppKrauss** [mkdocs/mkdocs#1213]
Seems a Python error...
The folowing steps are working fine at my laptop ( UBUNTU 16 LTS) with full installations of Python... 

```sh
git clone https://github.com/okfn-brasil/miniguias.git
cd  miniguias/DiscussOKBr
mkdocs build
```
The [`mkdocs.yml`](https://github.com/okfn-brasil/miniguias/blob/master/DiscussOKBr/mkdocs.yml) use  [this commom theme](https://github.com/okfn-brasil/miniguias/tree/master/okbr_theme).
  
When do the same in a "fresh UNBUNTU 16 LTS" (a sever) it not works fine.

```
INFO    -  Building documentation to directory: /tmp/miniguias/DiscussOKBr/site 
INFO    -  The directory contains stale files. Use --clean to remove them. 
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.14.0', 'console_scripts', 'mkdocs')()
....
TypeError: object of type 'SiteNavigation' has no len()
```

**Comment by waylan** [comment]
The error message suggests you have MkDocs version 0.14.0 installed. The SiteNavigation object had the length attribute added in 0.15 (IIRC, but it definitely wasn't in 0.14). If the theme is checking for the length, then it expects at least MkDocs version 0.15. You need to update MkDocs to a more recent version (current release is 0.16).

**Comment by waylan** [comment]
Sorry, the change was made in version 0.16 not 0.15. Note that the [release notes][1] list the `include_nav` variable as being deprecated and that the nav length should be checked instead (`nav|length>1`). See #1026 for the relevant changes and #679 for the discussion regarding the change.

[1]: http://www.mkdocs.org/about/release-notes/#major-additions-to-version-0160

**Comment by ppKrauss** [comment]
@waylan  Thanks. Yes, my v0.16 is running, the mkdocs at server, making error, was v0.14. 

-----

Problem with `apt`, `sudo apt install mkdocs`:  "mkdocs is already the newest version (0.14.0-1ubuntu2)".

Not solved after long `sudo apt install python-pip` and `pip install mkdocs`:

```
...
Successfully installed Jinja2 Markdown MarkupSafe PyYAML backports-abc 
certifi click livereload mkdocs singledispatch six-1.10.0 tornado
   You are using pip version 8.1.1, however version 9.0.1 is available.
   You should consider upgrading via the 'pip install --upgrade pip' command.
```
Then `pip install --upgrade pip` "Successfully installed pip-9.0.1"... redo `pip install mkdocs`... no changes, v0.14.

**Comment by waylan** [comment]
Did you tell pip to upgrade MkDocs:

    pip install --upgrade mkdocs

Or you can specify a specific version:

    pip install 'mkdocs>=0.16'

**Comment by ppKrauss** [comment]
As try above, not works, and same messages:

```
$ pip install --upgrade mkdocs
Requirement already up-to-date: mkdocs in /home/user/.local/lib/python2.7/site-packages
Requirement already up-to-date: tornado>=4.1 in /home/user/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: livereload>=2.5.1 in /home/user/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: PyYAML>=3.10 in /home/user/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: Jinja2>=2.7.1 in /home/user/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: Markdown>=2.3.1 in /home/user/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: click>=3.3 in /home/user/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: singledispatch in /home/user/.local/lib/python2.7/site-packages (from tornado>=4.1->mkdocs)
Requirement already up-to-date: certifi in /home/user/.local/lib/python2.7/site-packages (from tornado>=4.1->mkdocs)
Requirement already up-to-date: backports-abc>=0.4 in /home/user/.local/lib/python2.7/site-packages (from tornado>=4.1->mkdocs)
Requirement already up-to-date: six in /home/user/.local/lib/python2.7/site-packages (from livereload>=2.5.1->mkdocs)
Requirement already up-to-date: MarkupSafe>=0.23 in /home/user/.local/lib/python2.7/site-packages (from Jinja2>=2.7.1->mkdocs)

$ mkdocs --version
mkdocs, version 0.14.0

$ pip install 'mkdocs>=0.16'
Requirement already satisfied: mkdocs>=0.16 in /home/user/.local/lib/python2.7/site-packages
Requirement already satisfied: tornado>=4.1 in /home/user/.local/lib/python2.7/site-packages (from mkdocs>=0.16)
Requirement already satisfied: livereload>=2.5.1 in /home/user/.local/lib/python2.7/site-packages (from mkdocs>=0.16)
Requirement already satisfied: PyYAML>=3.10 in /home/user/.local/lib/python2.7/site-packages (from mkdocs>=0.16)
Requirement already satisfied: Jinja2>=2.7.1 in /home/user/.local/lib/python2.7/site-packages (from mkdocs>=0.16)
Requirement already satisfied: Markdown>=2.3.1 in /home/user/.local/lib/python2.7/site-packages (from mkdocs>=0.16)
Requirement already satisfied: click>=3.3 in /home/user/.local/lib/python2.7/site-packages (from mkdocs>=0.16)
Requirement already satisfied: singledispatch in /home/user/.local/lib/python2.7/site-packages (from tornado>=4.1->mkdocs>=0.16)
Requirement already satisfied: certifi in /home/user/.local/lib/python2.7/site-packages (from tornado>=4.1->mkdocs>=0.16)
Requirement already satisfied: backports-abc>=0.4 in /home/user/.local/lib/python2.7/site-packages (from tornado>=4.1->mkdocs>=0.16)
Requirement already satisfied: six in /home/user/.local/lib/python2.7/site-packages (from livereload>=2.5.1->mkdocs>=0.16)
Requirement already satisfied: MarkupSafe>=0.23 in /home/user/.local/lib/python2.7/site-packages (from Jinja2>=2.7.1->mkdocs>=0.16)

$ mkdocs --version
mkdocs, version 0.14.0
```

**Comment by waylan** [comment]
You could try uninstalling first, then reinstalling:

```
pip uninstall mkdocs
pip install mkdocs
```

If that doesn't work, then my assumption is that your system is configured to use a nonstandard package index which is out-of-date.

However, you can have pip download a specific file and install it:

```
pip install https://pypi.python.org/packages/65/b7/b1ccc6e91a44d0356657cd8e6bc642d4e2f6e64360b8d8073ad8ba284c4e/mkdocs-0.16.3-py2.py3-none-any.whl
```

**Comment by waylan** [comment]
It occurs to me that you could have two copies of MkDocs installed in different locations. In your last comment your output indicates that the package is being installed in a directory for a specific user. However, it may be that a copy of version 0.14 is installed in a global directory. To check that, open a python console and try the following:

```
>>> import mkdocs
>>> import os
>>> os.path.abspath(mkdocs.__file__)
```

The last line should return the absolute path to `mkdocs/__init__.pyc`. If it is different than `/home/user/.local/lib/python2.7/site-packages/mkdocs/__init__.pyc` (the location pip install it above) then that confirms the problem. Presumably the 0.14 package was installed without using pip. Try uninstalling with `apt-get` or whatever other method may have been used.

**Comment by ppKrauss** [comment]
Thanks @waylan ,  the command `sudo apt remove mkdocs; pip install mkdocs` fixed the problem (!). We can close this issue.

Opening a new issue for "the root of the problem", see #1214.
