### ISSUE TITLE
Maintain (or kill) apt install mkdocs

### ISSUE THREAD

**Issue by ppKrauss** [mkdocs/mkdocs#1214]
The command `sudo apt install mkdocs` is valid, and it is  even a recommendation in terminal messages  at UBUNTU when you say `mkdocs` without installed it.

As `apt`  is the most reliable and popular to install something, it is good to preserve it (in addition to the `pip` command), to promote the *mkdocs* project.

So, if  `apt install mkdocs` will be not killed by the project, the project must maintain it:

* to ensure that `apt` is patched with updated *mkdocs* (most stable *mkdocs* version for UBUNTU LTS);

* to offer "official instructions" on how to obtain the "most modern version" via PPA, when it is not possible to upgrade via `apt`.

* to avoid lost of users, "angry users", with [running and installation problems as reported at #1213](https://github.com/mkdocs/mkdocs/issues/1213#issuecomment-295073299).

**Comment by waylan** [comment]
I don't know who has been responsible for maintaining the package in the Ubuntu repo. @d0ugal do you know?

**Comment by d0ugal** [comment]
No idea, sorry. Somebody in the community handles that, I know very little about Ubuntu packaging.

**Comment by waylan** [comment]
According to the package index, Ubuntu [16.04LTS][1] is at MkDocs 0.14.0 and Ubuntu [16.10][2] and [17.04][3] are at MkDocs 0.15.3. In the first case (16.04LTS), the maintainer is listed as "Ubuntu Developers" with the link pointing to the [Ubuntu-devel-discuss][4] mailing list and in the later two (16.10 & 17.04) the maintainer is listed as "Ubuntu MOTU Developers" with a link pointing to the the [Ubuntu-motu][5] mailing list. It would seem that Ubuntu is maintaining the packages themselves.

Personally, I'm not interested in maintaining the packages as I don't use them (I run everything in virtual environments so system installed packages don't affect me). And if we as a project start officially maintaining the official package for one system, then we should for the others, which is more work than I'm interesting in taking on. Which leaves this to be handled by community members who care about it. That approach has worked fine for me for many years with the Python-Markdown project. As the various package maintainers seem to follow the project closely, I've never even needed to make any extra effort to notify them of new releases.

Of course, things may be a little bumpy as MkDocs approaches 1.0 and various backward incompatible changes are introduced. In fact, it may be that Ubuntu LTS hasn't updated for that specific reason. We started changing things more dramatically in 0.15 so I'm not surprised the LTS release has stayed at 0.14.

@ppKrauss if you (or anyone else) would really like to see the Ubuntu packages updated (or you would like to help with maintenance) I would suggest reaching out to the linked maintainers.

[1]: http://packages.ubuntu.com/xenial/mkdocs
[2]: http://packages.ubuntu.com/yakkety/mkdocs
[3]: http://packages.ubuntu.com/zesty/mkdocs
[4]: http://lists.ubuntu.com/archives/ubuntu-devel-discuss/
[5]: http://lists.ubuntu.com/archives/ubuntu-motu/

**Comment by ppKrauss** [comment]
Hi @waylan and @d0ugal, see [bugs/ubuntu/python-mkdocs/1685174](https://bugs.launchpad.net/ubuntu/+source/python-mkdocs/+bug/1685174)  and [bugs.debian.org/852078](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852078)
... what I must to do as next-step ?

**Comment by waylan** [comment]
As there is no actionable item for us, I'm closing this.

**Comment by ppKrauss** [comment]
Informative comments: 

* ~1,5 years ago was *UBUNTU 16 LTS*, now is *18 LTS* (!).  
* installing in "only Python3 env"  *UBUNTU 18 LTS*: `mkdocs --version` results in<br/>  *"mkdocs, **version 0.17.5**"*, so very better than v0.15... Seems someone now is updating Debian.

**Comment by SRAPSpencer** [comment]
I recommend removing the recommendation to use apt to install from the "Getting Started" guide or at least advise on what distros have up to date MkDocs versions. I followed this guidance only to discover I was terribly out of date weeks later.

**Comment by waylan** [comment]
@SRAPSpencer The second paragraph of that section states:

> If your package manager does not have a recent "MkDocs" package, you can still use your package manager to install "Python" and "pip". Then you can use pip to install MkDocs.

Seems pretty clear to me that it is your responsibility to check that. That said, we probably should remove that section as any such packages are not officially supported and all maintained by third parties. Feel free to open a new issue.
