### ISSUE TITLE
WebApp support

### ISSUE THREAD

**Issue by markusressel** [mkdocs/mkdocs#1215]
Hi,

I really this project and use it in conjunction with  the mkdocs-material theme.
I have manually added some javascript and html body tags to allow the website to be added to an android device as a WebApp essentially removing the URL bar on the device.

It would be great if this functionallity could be implemented by mkdocs itself with minimal mkdocs.yaml configuration additions and support for iOS and Android.

**Comment by funkyfuture** [comment]
i'm confused, do you mean the term 'WebApp' means a webbrowser without an address bar?

**Comment by markusressel** [comment]
Well it obviously means more than just that. A full implementation would have some kind of ServiceWorker that could potentially download (cache) the whole documentation site to allow full offline usage of the website (at least text). I wanted to keep this request small though and adding the required headers to allow the website to be run like an app (with a custom icon, title and removing the URL bar) is not complicated.
It would be great if those items could be configured right from the yaml file without the need to add them manually using a custom theme template.

**Comment by waylan** [comment]
It seems to me that a custom theme would be the best way to implement this. I'm not sure what value would be gained by including that in the default theme.
