### ISSUE TITLE
Trailing slash on document pages

### ISSUE THREAD

**Issue by evitalis** [mkdocs/mkdocs#1216]
I know about #344 but I am unsure if it was intended for document pages or just directories. I have a couple subdirectories and then my documents for organization purposes, and this ends up looking awkward. Should documentation pages itself use the trailing slash in the URL for non-directories?

**Comment by waylan** [comment]
As long as the [use_directory_urls][1] setting is on (the default), yes, all pages should end in a slash. As per the documentation, the url `/about/` actually points to the page `about/index.html`. As you can see, `/about/` is a directory which happens to only contain one file, 'index.html`. As HTML servers typically return the `index.html` contained within a directory if no file is specified, this works fine and we get "pretty URLs" with no special configuration. #344 fixed an inconsistency where some URLs were missing the slash.

[1]: http://www.mkdocs.org/user-guide/configuration/#use_directory_urls

**Comment by evitalis** [comment]
Thanks @waylan . That explains it well and I reviewed the documentation on the setting as well. I think I will keep it as is for my site.
