### ISSUE TITLE
Proposal: add a facility to run a pre-build hook

### ISSUE THREAD

**Issue by funkyfuture** [mkdocs/mkdocs#1217]
i'd like to contribute a way to run code before a site is build. in my case, i'm assembling markdown from yaml files.

i can think of two ways how this would work:

1) a configuration value in 'dot-notation' points to a function (`package.module.function`) that will be imported and called.
2) there would be a `hooks` directory in a project's root that can contain an executable `pre-build` that would be invoked as subprocess. hooks for other events would fit here as well.

in any case, an option to define further directories that are watched upon `serve` would be needed as well.

**Comment by waylan** [comment]
This should all be possible with the upcoming Plugin API. See #206. Any discussion should happen there.

**Comment by funkyfuture** [comment]
ai'ght, thanks for the hint.
