### ISSUE TITLE
require.js Error: Mismatched anonymous define() module 

### ISSUE THREAD

**Issue by lierisme** [mkdocs/mkdocs#1218]
# use MkDocs

## mydocs.yml:
site_name: My Docs

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
markdown_extensions:
    - pymdownx.superfences

## test.md
\```flow
st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com
op1=>operation: My Operation
sub1=>subroutine: My Subroutine
cond=>condition: Yes
or No?:>http://www.google.com
io=>inputoutput: catch something...

st->op1->cond
cond(yes)->io->e
cond(no)->sub1(right)->op1
\```

## run: mkdocs serve
http://127.0.0.1:8000

## result:
**Uncaught Error: Mismatched anonymous define() module: function ()** ......

why???
help!
thanks!

**Comment by facelessuser** [comment]
This is better suited for the repo containing SuperFences. https://github.com/facelessuser/pymdown-extensions

**Comment by waylan** [comment]
> This is better suited for the repo containing SuperFences. 

I agree. Please follow up there.

**Comment by lierisme** [comment]
Thank you for your.

**Comment by facelessuser** [comment]
@waylan I do think this might need some kind of fix in the default `mkdocs` theme.  It appears some scripts don't play nice with being loaded after `require.js` and the `mkdocs` theme loads all extra scripts after `require.js`.  I'm not sure if and how you'd guys would approach this, but the current setup limits what can be loaded in extra javascript.  So feel free to reopen this if needed, but this seems to be an issue that can only be worked around by overriding the `mkdocs` theme `base.html`.  See comment https://github.com/facelessuser/pymdown-extensions/issues/67#issuecomment-298495186.

**Comment by facelessuser** [comment]
Official statement from require.js on this error: http://requirejs.org/docs/errors.html#mismatch.

**Comment by waylan** [comment]
IIRC, we only use `require.js` for search, which is getting a refactor. I had every intention of trying to remove the dependency on `require.js` in the refactor. This is another reason to add to the list. See [Search Refactor](https://github.com/mkdocs/mkdocs/projects/1) for more info.

**Comment by facelessuser** [comment]
Removing `require.js` is exactly what I would suggest.  Seems like it would just be a pain to expect everyone to workaround.  Sounds like a great module if you plan to build everything around it, but not so much for a generalized template where you don't know what the user is going to try to pair with it.

Thanks!
