### ISSUE TITLE
Rendering issue for lines starting with hyperlink

### ISSUE THREAD

**Issue by gokceneraslan** [mkdocs/mkdocs#1221]
Two hyperlinks in the following docstring in Keras documentation (`[here]` and `[details]` see https://keras.io/callbacks/#tensorboard):

![image](https://cloud.githubusercontent.com/assets/1140359/25843803/d2c4618c-34a8-11e7-9d58-98eed89e141b.png)

are rendered incorrectly as follows:

![image](https://cloud.githubusercontent.com/assets/1140359/25843769/af9cd6f8-34a8-11e7-9930-038db06d9f32.png)

That is I guess because the lines 581 and 603 start with hyperlinks. Is this a mkdocs bug or should one use `\` in the end of the line?

**Comment by waylan** [comment]
MkDocs does not generate documentation from doc strings in code. Additionally, that doc string is not formatted as Markdown (Markdown would never see that as a list). I suspect you have some other tool generating that document which does not understand Markdown links.

**Comment by gokceneraslan** [comment]
OK, sorry. I think I found the script https://github.com/fchollet/keras/blob/master/docs/autogen.py#L390.

**Comment by waylan** [comment]
I took a look at your git repo and found that myself. You need to look at the output of that script. I suspect that will reveal the problem.
