### ISSUE TITLE
Integrated text editor

### ISSUE THREAD

**Issue by itaied246** [mkdocs/mkdocs#1222]
Is there an integrated text editor tool to edit the pages in an easier process?
We are keeping our docs sources with in the project repository, 
and what we do currently is modifying the docs locally and pushing the whole project.
We could separate the docs from the project, but then it still not comfortable enough to edit and merge the `md` files from the local machines.
How do you add docs to an online site without generating the whole site from scratch?

**Comment by waylan** [comment]
MkDocs is a static site generator. By definition, you make changes by regenerating the site as static files and re-uploading them. If you want the ability to edit individual pages in place, then you do not want a static site generator. An integrated text editor is out-of-scope for MkDocs. You might want to look at a CMS or Wiki to meet those needs.
