### ISSUE TITLE
Running mkdocs on OSX fails when click aborts, even though locale settings seem correct

### ISSUE THREAD

**Issue by tombaker** [mkdocs/mkdocs#1230]
I installed `mkdocs` OSX 10.11.6.  When I try to run it:

```
$ mkdocs new test-repo
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.5/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.
```

After Googling pretty extensively, the best I could do was check that my terminal app (iTerm2) was configured for UTF-8.  To the settings already configured in my `.bash_profile`:
```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
I added:
```
export LC_CTYPE=en_US.UTF-8
export PYTHONIOENCODING=utf-8:surrogateescape
```

When I try `$ locale`, I get:
```
LANG="en_US.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL="C"
```
but after three hours, I cannot get to the bottom of this.  I figure that if I am having issues with a regular OSX installation, others might too.

**Comment by tombaker** [comment]
Some additional diagnostics:
```
$ python3
Python 3.5.2 (default, Oct 11 2016, 05:05:28)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getdefaultlocale()
(None, None)
>>> locale.getpreferredencoding()
'US-ASCII'
```

**Comment by tombaker** [comment]
Problem solved.  I discovered a setting downstream that overrode LC_ALL, in a subsequent config file.  When I commented this out, problem solved.

**Comment by waylan** [comment]
@tombaker I'm glad you worked it out. I'm curious which setting you had to change to fix this in case others encounter the problem. And was it broken with the default of the other way around?

**Comment by tombaker** [comment]
@waylan Thank you! I use the same base `.bash_profile`, via Github, for a Linux machine and a Mac.  On my Mac, where `uname -s` returns 'Darwin', a `bash_profile_osx` also runs, with a few Mac-specific settings.  On of these was `export LC_ALL='C'` which, according to an inline comment dated 2011, "fixes problem with sort order involving non-ASCII characters".  I commented this line out and everything worked fine.
