### ISSUE TITLE
How can I add meta keywords to my mkdocs site?

### ISSUE THREAD

**Issue by rhiever** [mkdocs/mkdocs#1241]
I'd like to add meta keywords to my mkdocs site. For example, in HTML the meta keywords would look like:

```html
<meta name="keywords" content="example keyword 1, example keyword 2">
```

 I've looked through all the documentation and can't quite figure out how to do it. Is this possible to do in mkdocs? It'd be ideal if I could set the meta keywords on a per-page basis.

**Comment by waylan** [comment]
We currently do not have any specific feature which explicitly allows you to do this. However, you may be able to use [template customization][1] to accomplish this. Specifically, you could use the `extrahead` or `site_meta` [blocks][2] to insert additional tags into the document head.

As for having per-page keywords, I would suggest using Markdown [meta-data][3] (which is included in MkDocs by default, albeit, undocumented). Define the keywords as meta-data within the page and then in the template you could access the keywords via `page.meta.keywords`. For example, this Page:

```md
keywords: example keyword 1, example keyword 2

Page content here...
```

with this template:

```django
{% extends "base.html" %}

{% block site_meta %}
    {{ super() }}
    {% if page and page.meta.keywords %}<meta name=""keywords" content="{{ page.meta.keywords[0] }}"> {% endif %}
{% endblock %}
```

... will give you everything on the `keywords` line in the page included in the `content` tribute of your `meta` tag. Of course, if you want something more complex, you are welcome to work that out. But this should get you started.

[1]: http://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme_dir
[2]: http://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks
[3]: https://pythonhosted.org/Markdown/extensions/meta_data.html

**Comment by coliff** [comment]
@rhiever why are you adding keywords? Search engines don't use meta keywords as a ranking factor at all, so it is not recommended to use them. Bing still takes them into account as a signal for spammers not ranking.
REF: http://gethead.info/#meta-not-recommended

**Comment by rhiever** [comment]
Thanks for the info, everyone!

**Comment by waylan** [comment]
Sorry, I should have mentioned this when I closed it, but this is closed as a (rejected) feature request. If there is some reason why a user would still want to do this as a custom behavior, you can ask for help on the [mailing list](https://groups.google.com/forum/#!forum/mkdocs).
