### ISSUE TITLE
Preprocessor and Live Reload

### ISSUE THREAD

**Issue by mottosso** [mkdocs/mkdocs#1242]
Hi everyone,

This is a question and not a problem. I'm using a markdown pre-processor script that needs to run before mkdocs gets a chance to serve things.

```bash
$ python preprocess.py
# home.template -> home.md
# about.template -> about.md
$ mkdocs serve
```

What would be swell, is if I didn't have to run this manually, but could somehow hook into the live reloading mechanism such that it could run this command whenever a change is made to any of my templates.

I noticed that it already reloads when they change, so I figure it might be relatively straightforward to accomplish, if it isn't already possible.

Is there any way of achieving this at the moment?

**Comment by waylan** [comment]
This should all be possible when the Plugin API is released. You can find a working copy in the 1.0.dev branch. See #1223 for details.

**Comment by mottosso** [comment]
Thanks @waylan, having a look at this today!

**Comment by mottosso** [comment]
I gave this a quick go, but being on a deadline hindered me from working around the first issue I encountered, even though it is likely easily overcome if I knew why it happens, which was installing mkdocs from source.

```bash
$ git clone https://github.com/mkdocs/mkdocs.git -b 1.0.dev
$ cd mkdocs
$ python -m pip install .
Processing c:\users\marcus\git\mkdocs
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\Python27\lib\site-packages\pip\download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "C:\Python27\lib\site-packages\pip\download.py", line 686, in unpack_file_url
    shutil.copytree(link_path, location, symlinks=True)
  File "C:\Python27\lib\shutil.py", line 208, in copytree
    raise Error, errors
Error: [('C:\\Users\\marcus\\git\\mkdocs\\mkdocs\\tests\\integration\\unicode\\docs\\?.md', 'c:\\users\\marcus\\appdata\\local\\temp\\pip-okqzvl-build\\mkdocs\\tests\\integration\\unicode\\docs\\?.md', "[Errno 22] invalid mode ('rb') or filename: 'C:\\\\Users\\\\marcus\\\\git\\\\mkdocs\\\\mkdocs\\\\tests\\\\integration\\\\unicode\\\\docs\\\\?.md'")]
$
```

So did what I already knew, which was throwing together a `watchdog` script that runs alongside `mkdocs serve` and runs the Python pre-processor on any files being changed.

```python
import os
import sys
import time
import logging
import subprocess

from watchdog import observers, events

class TemplateHandler(events.FileSystemEventHandler):
    def on_modified(self, event):
        super(TemplateHandler, self).on_modified(event)

        path = os.path.normpath(event.src_path)
        subprocess.call([sys.executable, "build.py", path])


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')
    path = os.path.join(os.path.dirname(__file__), "pages")

    event_handler = TemplateHandler()
    observer = observers.Observer()
    observer.schedule(event_handler, path, recursive=True)
    observer.start()

    print("Watching %s.." % path)

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()

    observer.join()

    print("Good bye")
```

I also quickly discovered some of my requirements.

1. Builds sometime take a long time, multiple seconds per page (due to initiating a Docker environment with dependencies installed for the execution of code in the docs, e.g. Autodesk Maya)
2. Most changes aren't changes to the code, so there needs to be a way to do a "lite" build, and leave the "full" build for deployment on Travis.

On the next iteration, the plug-in API looks just like what I want, with the [`on_pre_build()`](https://github.com/mkdocs/mkdocs/blob/1.0.dev/docs/user-guide/plugins.md#on_pre_build) callback.

Any idea what I could have done differently to install the 1.0.dev branch?

**Comment by waylan** [comment]
Hmm, interesting error. It appears that when copying the files to the installed location it is tripping up on one of our Unicode test files. Weird that I've never encountered that before.

**Comment by waylan** [comment]
Now that version 0.17 is released, this can be addressed with the Plugin API.
