### ISSUE TITLE
Search in YAML headers

### ISSUE THREAD

**Issue by ghost** [mkdocs/mkdocs#1243]
Is it possible to search in YAML headers, like this:
```
---
author: Me
---
Foo
```

I want to find "Me" if I search it

**Comment by waylan** [comment]
No, not at this time. However, that may be something that might be added when the search feature gets refactored. I've added this to the (already long) list of issues in that [project](https://github.com/mkdocs/mkdocs/projects/1).

**Comment by waylan** [comment]
Oh and that is not YAML, but multimarkdown style meta-data.

**Comment by waylan** [comment]
Not really sure how this would work. Should the entire meta-data section be indexed as a block of text or should each individual key be indexed? I doubt we should index all keys (`template` for example makes no sense). I suppose a set of keys could be defined in the config. Maybe something like:

```yml
plugins:
    - search:
        index_meta_data: [author, summary]
```

Then for any page which has those meta-data keys assigned, they get indexed. 

Any thoughts from someone who wants/needs this feature?

**Comment by noraj** [comment]
@waylan related to #1828, yead letting the user the possibility to configure the YAML key to be indexed is better than indexing all by default as you said. But some default key like `tags`, `title`, or `description`/`summary` should be indexed by default.

**Comment by pawamoy** [comment]
Nowadays (2024) lunr.js is unmaintained (last commit 2020). While we welcome enhancements to existing themes, we're also discussing creating a new, better default theme, which would probably use something else than lunr.js. @squidfunk also stated that he and his team are working on a standalone search plugin that is theme-agnostic and will bring such functionality, see the discussion starting here https://github.com/mkdocs/mkdocs/pull/3560#issuecomment-2051748530.

For these reasons, we'll close this as not planned! If someone wants to work on this anyway, we can re-open the issue.
