### ISSUE TITLE
Multi-Label Classification

### ISSUE THREAD

**Issue by arman817** [mkdocs/mkdocs#1244]
Is it possible to calculate the joint probabilities in Multi-Label Classification, also taking into account the dependency of the labels?

Thanks.

**Comment by waylan** [comment]
Not sure I understand what this is about. MkDocs doesn't have "labels". Can you please clarify?

**Comment by arman817** [comment]
Oh sorry but actually I meant about the Multi-label classification Problem
for Machine Learning in the mlr package which the MkDocs mentioned. So the
question is about getting the joint probability in multi label
classification problems.

**Comment by waylan** [comment]
What "mlr package which the MkDocs mentioned"? Can you provide a link?

MkDocs is documentation building tool. It has nothing to do with Machine Learning. Unless some machine learning project uses MkDocs to generate their documentation, in which case you should be during your question to that project, not the developers of the documentation tool.

**Comment by arman817** [comment]
I am really sorry because in this case I need to then contact the people in
the project. Since I am new to this I didn't have any idea whom to contact.

Thanks a lot and I really appreciate for your time.

Regards,
Arman
