### ISSUE TITLE
Per-page JavaScript

### ISSUE THREAD

**Issue by garry-jeromson** [mkdocs/mkdocs#1245]
I couldn't find any other issues along these lines apart from https://github.com/mkdocs/mkdocs/issues/986, which is closed - please merge if I've overlooked something.

So, my goal is to have certain javascript files that are included only on a per-page basis; this is useful for configuring individual DataTables, without having to lump all the code in a site-wide script. This is easily achieved using metadata: at the top of the relevant page I declare `local_scripts: some-file.js`, and my tweaked theme does the heavy lifting of including the script in the page headers.

The problem is that `some-file.js` is naturally in the local folder tree, which means that it's automatically picked up and added to `extra_javascript`. Is there any way to explicitly prohibit this behaviour?

**Comment by waylan** [comment]
This sounds like a good candidate for a Plugin.  The Plugin API (see #1223) is currently available in the 1.0.dev branch and should be included in the next major release..

**Comment by garry-jeromson** [comment]
Will take a look. Thanks!
