### ISSUE TITLE
Is there anyway so I can load `{{ content }}` in `<iframe>`?

### ISSUE THREAD

**Issue by notalentgeek** [mkdocs/mkdocs#1246]
* I have this in my main .html file, `<iframe src="{{ base_url }}/content.html"></iframe>`.
* I have this in content.html, `{% block content %}{{ content }}{% endblock %}`.

When I clicked a link it loads the whole website in the `<iframe>`. I want so that when I change pages everything is persistent but the content (not the whole page) itself. Is there anyway to do this? Or a workaround?

The problem is I have ~4000 .md files in the navigation bar. Reloading the pages re - do the rendering for those ~4000 .md files with each its style again. I think would be good for my website to only load the content compared to reloading the whole website.

**Comment by waylan** [comment]
We don't explicitly support this, but it may be possible to get it to work with a custom theme. It may be easier when we release 1.0 as some additional theme customization options will be added then (currently available in the 1.0.dev branch). See #1201 for more details.

You may also find #1137 interesting as it discusses a slightly different solution to the same type of problem. At least one third party theme is exploring building in that solution.

**Comment by notalentgeek** [comment]
I am looking through https://stackoverflow.com/questions/3272071/iframe-to-only-show-a-certain-part-of-the-page at this point. I will post here again later.
