### ISSUE TITLE
I have an error when accesing 404.html.

### ISSUE THREAD

**Issue by notalentgeek** [mkdocs/mkdocs#1247]
This is the error, `tornado.template.ParseError: unknown operator: 'do' at 404.html:127` I am not sure why, nor I know Tornado. Every web pages is fine but when user try to access unavailable page it return this error in my terminal (I run this via `mkdocs serve`).

**Comment by ovasquez** [comment]
Which template are you using? I just tested accessing a non existing page with the themes: _default_, _readthedocs_ and _material_, and the three of them worked as expected.

**Comment by waylan** [comment]
Could you post the content of your `404.html` file. Based on the error message, it appears that there is an error on line 127 of that file.

**Comment by notalentgeek** [comment]
Hi there, I tried to make my own theme based on structure I saw in https://github.com/mkdocs/mkdocs-basic-theme. This is my self - made temp, https://github.com/notalentgeek/mkdocs-basic-flex-theme. Where is 404.html located (where should I put it)?

**Comment by waylan** [comment]
You need to review how [template inheritance][1] works. And then look at how we have implemented that in the built-in themes. That should clear up your problems. If you need help with that, I would suggest asking on the mailing list (this is for bug reports and the mailing list is for support).

In any event, it appears that the original error was related to a missing template. That may be a bug in that we should be reporting a more clear error. I'm marking this as a bug for that reason, although we need to confirm that my assumption is correct.

[1]: http://jinja.pocoo.org/docs/2.9/templates/#template-inheritance
