### ISSUE TITLE
[Question]: What is the easiest way to get syntax highlighting for a custom language?

### ISSUE THREAD

**Issue by NOhs** [mkdocs/mkdocs#1248]
I read that by default mkdocs uses highlight.js to highlight code fence blocks. If I want to add a custom language to highlight.js for one mkdocs project, how would I do this? I know how to write a language file for highlight.js, but I would like to keep the default installation for highlight.js, so how can I tell mkdocs to use something else for a specific project? Or is there an easier way of getting custom language syntax highlighting?

**Comment by waylan** [comment]
I don't recall off-hand how you tell highlight.js about a custom language, but if you need to simply add an extra JS file, you might want to start with the [extra_javascript][1] config setting as explained in the [docs_dir section][2] of the [Theme Customization][3] docs. For something more complex, it would likely be necessary to override/replace the default files via the [theme_dir][4].

[1]: http://www.mkdocs.org/user-guide/configuration/#extra_javascript
[2]: http://www.mkdocs.org/user-guide/styling-your-docs/#using-the-docs_dir
[3]: http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme
[4]: http://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme_dir

**Comment by NOhs** [comment]
I tried the `extra_javascript`, it didn't have an effect, so I guess I will try the `theme_dir` option next.

**Comment by NOhs** [comment]
This works. Thank you.
