### ISSUE TITLE
Add support for git's textual symlinks on Windows.

### ISSUE THREAD

**Issue by mikolysz** [mkdocs/mkdocs#1250]
When symbolic links are used to include documentation from outside the "docs" folder, i.e. the readme or the contributing guidelines and the repo is cloned with msysgit for windows on a file system that doesn't support symlinks, the pages render incorrectly. Sometimes that approach is needed, because files like README.md or CONTRIBUTING.md need to both be in the root directory of the repo to be rendered by github and in the docs directory to be rendered by mkdocs.
This solution was proposed [here](https://groups.google.com/forum/#!topic/mkdocs/_X9l1znCRxw). A good example of a project that uses this is [Ranvier MUD](https://github.com/shawncplus/ranviermud).

**Comment by waylan** [comment]
How would MkDocs add support? Why can't you set up git to convert the symlics to native links (perhaps [like this][1]). That way there no need for each individual tool to build in support. Besides, as none of the maintainers use such a feature we're not in a good position to maintain it or debug problems. However you can implement something that works for your specific use case.

[1]: https://stackoverflow.com/a/16754068

**Comment by waylan** [comment]
This is related to #1134. I didn't remember that that PR was never merged. We don;t even follow symlinks on Linux at this point.

**Comment by warmfusion** [comment]
'Dont even follow symlinks' - That's not entierly true - https://github.com/mkdocs/mkdocs/pull/948

Without the patch described in #1134 a symlinked dir under docs/ was being generated without the content, but all the asset images loaded in...

**Comment by roipoussiere** [comment]
What is the status of this?

I'm using mkdocs 1.1.2 on linux and syminks does not work for me (I tried with `ln -s ./README.md ./doc/getting_started.md` and got a FileNotFound error.

**Comment by oprypin** [comment]
Seeing as Windows is starting to more commonly support actual symlinks, I think special support for it is no longer necessary.

Consider also that plugins or extensions may let you solve the same use case without symlinks. 
E.g. make a file that entirely consists of a "snippets" inclusion: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/

**Comment by ilyagr** [comment]
I think the [`include-markdown` plugin](https://github.com/mondeja/mkdocs-include-markdown-plugin) is a decent workaround. 

I did trip on a bug (https://github.com/squidfunk/mkdocs-material/issues/6749), but triggering it requires also using the `offline` plugin from mkdocs-material.
