### ISSUE TITLE
Include runnable javascript code snippets

### ISSUE THREAD

**Issue by Viatorus** [mkdocs/mkdocs#1251]
Hello there,

I am writing a javascript library and I would like to add runnable javascript-code snippets into the docs (similar to jsfiddle but without html).
Is there any such possibility? I wonder, if any other js project have done this yet.

**Comment by waylan** [comment]
I'm not aware of anything that has been done specific to MkDocs. For a one-off, I'd just use jsfiddle, but I can see the value of using a built-in solution. Of course, you should only need to add a JS library (and possibly some CSS), which is fairly easy. See [Customizing a theme][1] in the docs for a summary of the various ways you could accomplish that.

[1]: http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

**Comment by waylan** [comment]
I should note that my response above assumes that a third-party "snippet" library exists that you would need to include in your site (I'm not aware of any and haven't searched for any). Without that, you would need to build everything from scratch, in which case using jsfiddle would likely be a much more attractive option.

**Comment by Viatorus** [comment]
@waylan Thank you for your answer.

I did it by myself - with the help of CodeMirror: https://lokijs-forge.github.io/LokiJS2/

**Comment by waylan** [comment]
Hmm, looks like CodeMirror is sung RequireJS. I'm assuming that's causing a conflict with the search lib, which also uses RequireJS. If CodeMirror can be called without requireJS, I'd suggest that. If not... a future planned refactor of search will likely remove the RequireJS dependency, but that doesn't help you today. However, as the RTD theme (which you are using) only shows search results in the `search.html` page (which is its own template), you may be able to use some custom template code to not include CodeMirror on the search page. At least, that's where I would start.
