### ISSUE TITLE
gh-deploy removes "Custom domain" configuration

### ISSUE THREAD

**Issue by aleixmorgadas** [mkdocs/mkdocs#1257]
When the GitHub Pages has a *Custom domain* configured, and you run
`mkdocs gh-deploy`,
the "Custom domain" is removed

**Comment by waylan** [comment]
As a reminder, the documentation states regarding [gh-deploy][2]:

> You should never edit files in your gh-pages branch by hand if you're using the `gh-deploy` command because you will lose your work.

That behavior is determined by the underlying third-party tool we use (and how it interacts with Git), so there's not any reasonable way to change that behavior.

However, if you include the `CNAME` file (required by GitHub for custom domains) in your `docs_dir`, then MkDocs will copy it to the `site_dir`. In fact, this is what MkDocs [does][1] for its own documentation.

[1]: https://github.com/mkdocs/mkdocs/blob/master/docs/CNAME
[2]: http://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages

**Comment by aleixmorgadas** [comment]
Thanks @waylan!

**Comment by itsthejoker** [comment]
GitHub no longer requires a CNAME file when setting this value through the UI -- this behavior is very counter-intuitive for those of us who didn't use Pages in the beginning since it does wipe the value set through the UI. Is it possible to get a warning through the tool when this is happening so we know to create and include the CNAME file?

**Comment by gllrmzndm** [comment]
This also works for mkdocs-material (https://squidfunk.github.io/mkdocs-material/)

Create a file in the docs_dir called "CNAME" without quotes.
Add your apex domain into the file example: andereguillermozaandam.be

`mkdocs gh-deploy` to deploy your site.

And it should work.

![image](https://user-images.githubusercontent.com/43880437/221455140-f069264b-2a8b-4ee4-ae5e-8e572fd7f90f.png)

**Comment by rajaduraicloud** [comment]
Thanks @waylan it's working..!!!
