### ISSUE TITLE
Search on site deployed to Azure Web App

### ISSUE THREAD

**Issue by bierkopf** [mkdocs/mkdocs#1258]
Hello, 

I'm running Mkdocs 0.16.3 for some time with excellent results. When I run on my local machine via the 'serve' feature, or via IIS, the search function works great. For both themes available. However when I deploy the site to Azure Web Apps, the search stops working.

What have I overlooked? 

Thanks

**Comment by waylan** [comment]
How does search "stop working"? If you mean it returns no results, then continue reading. If you mean something else, you'll need to report more info.

I'm not familiar with the specifics of Azure. And I don't see any reported issues with Azure in the [lunr.js][1] project (which we use). So we'll need to figure this out by trial and error.

When you build the site, MkDocs creates a single JSON file which contains the text of all pages. When a page is loaded in the browser, that JSON file is downloaded in the background and used to build a local search index. If there's no index, then there is no search results to return. 

I would start by checking the developer tools of my browser for any JavaScript errors on the page. If search is failing to return results, then I would guess that the JSON file used to build the index is not accessible. Maybe Azure is doing something weird with it?

[1]: https://github.com/olivernn/lunr.js/issues?utf8=✓&q=azure

**Comment by bierkopf** [comment]
Thanks for the quick reply. Indeed, you have pointed me in the right direction. You were right - I meant 'it returns no result'.

So far, I have verified that the search json file is uploaded with the rest of the site. Also, developer tools in browser indicate the json file was not found.

So now I am going to see why and find maybe a configuration bug. Will share it here once found.

Thank you

**Comment by bierkopf** [comment]
Awesome. You pointed me to the right direction. So: for static sites on Azure Web Apps, you need to enable Mime-types by adding a web.config file to the root. Here is a description which [solves the json search file retrieval](http://sabbour.me/how-to-serve-static-json-files-from-a-windows-azure-website/). 

It turns out that more types are disabled. So I modified the web.config to the following:

```
<?xml version="1.0"?> 
<configuration> 
    <system.webServer> 
        <staticContent> 
            <mimeMap fileExtension=".json" mimeType="application/json" /> 
            <mimeMap fileExtension=".woff" mimeType="application/x-woff" />
            <mimeMap fileExtension=".mustache" mimeType="text/html" />
     </staticContent> 
    </system.webServer> 
</configuration>
```

Notice the .mustache file was causing some extra issues. Now all works.

Thank you
