### ISSUE TITLE
[WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by sachinanshu** [mkdocs/mkdocs#1260]

**Comment by waylan** [comment]
We are going to need more information so that we can reproduce the error. What system are you on? What version of MkDocs are you using? Do you have any custom config settings? Which specific command did you run?

**Comment by waylan** [comment]
Due to a lack of info, this is being closed.

**Comment by yc-zc** [comment]
> We are going to need more information so that we can reproduce the error. What system are you on? What version of MkDocs are you using? Do you have any custom config settings? Which specific command did you run?

Windows 10 
MkDocs 1.0.4
https://github.com/yc-zc/web/blob/master/mkdocs.yml
mkdocs serve

**Comment by waylan** [comment]
@yc-zc thanks for the information. Could you please copy and paste the entire console session?

**Comment by yc-zc** [comment]
> @yc-zc thanks for the information. Could you please copy and paste the entire console session?

Sorry but I have restarted my computer, so all the logs have lost. 
But the entire console session would be the same as:

 zc@ZHIYUANS-20HKCT  D\..\..\..\int.xyz   master ≣ +6 ~5 -0 !  mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - algorithm\divide&conquer.md
  - algorithm\polynomial.md
  - algorithm\transform&conquer.md
  - cv\convolution_neural_network.md
  - cv\correlation_and_convolution.md
  - cv\siamfc.md
  - cv\siamrpn++.md
  - cv\variant.md
  - kubernetes\command_line_interface.md
  - machine_learning\distribution.md
  - master\about.md
  - master\curriculum_vitae.md
  - master\resume.md
  - mathematics\introduction.md
  - mathematics\linear_algebra.md
  - mathematics\probability.md
  - nlp\introduction.md
  - nlp\tf-idf.md
  - nlp\word_processing.md
[WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by waylan** [comment]
According to this [Stackoverflow question][1], it could be either a port you don't have permission to access or that the port is being used by something else. The problem is that the livereload server opens two ports, one for the http server which serves the pages and a second for the socket which tells the browser to reload the page. I suspect, but need to confirm that it is the socket which is causing the error. So I need the following two pieces of info:

1. Could you try again and this time provide any errors raised in your browser's console?

2. Also, could you try using the `--no-livereload` option? Do you still get the error?

You might also want to read through the answers to the Stackoverflow question I linked above. One of those could resolve it for you. For example, do you have any antivirus software or firewall running which is blocking the port? Could you run `netstat -ban` to confirm what ports are already in use?...

[1]: https://stackoverflow.com/q/2778840/866026

**Comment by yc-zc** [comment]
> According to this [Stackoverflow question](https://stackoverflow.com/q/2778840/866026), it could be either a port you don't have permission to access or that the port is being used by something else. The problem is that the livereload server opens two ports, one for the http server which serves the pages and a second for the socket which tells the browser to reload the page. I suspect, but need to confirm that it is the socket which is causing the error. So I need the following two pieces of info:
> 
> 1. Could you try again and this time provide any errors raised in your browser's console?
> 2. Also, could you try using the `--no-livereload` option? Do you still get the error?
> 
> You might also want to read through the answers to the Stackoverflow question I linked above. One of those could resolve it for you. For example, do you have any antivirus software or firewall running which is blocking the port? Could you run `netstat -ban` to confirm what ports are already in use?...

As I mentioned in another issue, I do have access and I tried some different ports like 8001.

The error is:

127.0.0.1 refused to connect.

The process was killed, and there is nothing more you can expect.

I tried dirty load but it doesn't work, I'll try --no-livereload next time I encounter this bug.

**Comment by oprypin** [comment]
This is possibly not reproducible anymore, as the server implementation has changed. Feel free to reopen if you get a fresh case of this error on the latest MkDocs version.

**Comment by oprypin** [comment]
OK, so this wasn't about multiple ports or livereload. Still though, I have no idea what one would need to do to observe this error, so it remains not actionable. Anyway I suspect that this is not specific to MkDocs, any other server trying to listen on the port would also fail. Maybe even just run `py -m http.server`. If someone could confirm or deny that that one fails (or doesn't) in the same situation as MkDocs, that would be great.

**Comment by mwpowellhtx** [comment]
> Anyway I suspect that this is not specific to `MkDocs`.

I agree with that much; the same issue appears to happen for other services as well.

As a community aligned over the issue, though, if anyone had any insights, workarounds, resolutions, that would be fantastic. My digging into the matter came back with the usual troubleshooting, verification, etc, to no avail.

**Comment by drojf** [comment]
I got this issue today - it turned out I forgot I was running another python script which also used  http://127.0.0.1:8000/. Strangely it gave this "[WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions" error, rather than a "port in use" error.

I also tried just running multiple instances of mkdocs, to see if it would give the same error, but it didn't give any error and just let me open it multiple times. Perhaps the way I bound the port in the other python script gave the error? I'm not super well versed in this so I don't know.

One other thing I'll note is that my error occurs before the IP/port is printed out (as in, the port that mkdocs opens is not shown in the logs). The IP/port should already be known by the user, since it is the default one, but it would be useful to see for debugging if it was printed before the port was opened. I also tried verbose mode and I think it is not shown there either.

```python
python -m mkdocs serve -f mkdocs.yml
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
             - support-checklist.md
             - Higurashi\Higurashi-Part-1.1---Voices-only-Patch.md
             - Higurashi\steam-add-console-arcs\steam-add-console-arcs.md
             - Snippets\Cross-Platform-Installer.md
             - Snippets\gnome-crash-warning.md
             - Snippets\higurashi-saves-warning.md
             - Snippets\higurashi-voice-matching-level.md
             - Snippets\installer-linux-wine.md
             - Snippets\installer-proton-instructions.md
             - Snippets\installer-usage.md
             - Snippets\support-checklist.md
             - Snippets\third-party-features.md
             - Snippets\umineko-project-recommendation.md
             - Snippets\umineko-saves-warning.md
             - Snippets\uninstall-steamgrid.md
             - Umineko\Tsubasa-Hane.md
INFO    -  Doc file 'Umineko/Umineko-Getting-started.md' contains a link
           'Umineko-Part-0-TroubleShooting-and-FAQ.md#the-game-has-poor-performance-even-on-high-end-systems', but the
           doc 'Umineko/Umineko-Part-0-TroubleShooting-and-FAQ.md' does not contain an anchor
           '#the-game-has-poor-performance-even-on-high-end-systems'.
INFO    -  Documentation built in 0.88 seconds
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\drojf\AppData\Roaming\Python\Python312\site-packages\mkdocs\__main__.py", line 370, in <module>
    cli()
  File "C:\Users\drojf\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drojf\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\drojf\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drojf\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drojf\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drojf\AppData\Roaming\Python\Python312\site-packages\mkdocs\__main__.py", line 272, in serve_command
    serve.serve(**kwargs)
  File "C:\Users\drojf\AppData\Roaming\Python\Python312\site-packages\mkdocs\commands\serve.py", line 104, in serve
    server.serve(open_in_browser=open_in_browser)
  File "C:\Users\drojf\AppData\Roaming\Python\Python312\site-packages\mkdocs\livereload\__init__.py", line 173, in serve
    self.server_bind()
  File "C:\Program Files\Python312\Lib\wsgiref\simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "C:\Program Files\Python312\Lib\http\server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "C:\Program Files\Python312\Lib\socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```
