### ISSUE TITLE
Config value: 'theme'. Error: The theme 'flatly' is no longer included in MkDocs by default

### ISSUE THREAD

**Issue by armadsen** [mkdocs/mkdocs#1265]
I'm running mkdocs 0.16.3 on macOS 10.13 beta 5. When I run `mkdocs serve` or `mkdocs build`, I see:

```
INFO    -  Building documentation... 
ERROR   -  Config value: 'theme'. Error: The theme 'flatly' is no longer included in MkDocs by default and must be installed with pip. See http://www.mkdocs.org/about/release-notes/#add-support-for-installable-themesfor more details 

Aborted with 1 Configuration Errors!
```

However, running `pip install mkdocs-bootstrap` or `pip install mkdocs-bootswatch` results in:

```
Requirement already satisfied: mkdocs-bootstrap in /Library/Python/2.7/site-packages
```

implying that they're already installed (as expected).

Perhaps this is a problem specific to the macOS High Sierra beta? In any case, any thoughts on a workaround? This was working last time I ran mkdocs on macOS 10.12, but that was quite a while ago, and I believe mkdocs has been updated (via Homebrew) since then.

**Comment by waylan** [comment]
From the terminal run `mkdocs build --help` and all of the installed themes should be listed as options for the `--theme` flag ( I get `[cosmo|united|nature|journal|readthedocs|readable|spacelab|cerulean|
bootstrap|simplex|flatly|yeti|amelia|cyborg|slate|mkdocs]`). If a theme is missing from that list, then it is not installed properly.

Also note that pip does not "upgrade" a package unless you expressly tell it to. Try this: `pip install --upgrade mkdocs-bootstrap mkdocs-bootswatch`.

**Comment by waylan** [comment]
Another possibility is that you have multiple Pythons installed on your system. I note that you installed MkDocs via Homebrew, but you installed the themes via pip. If pip is installing to a different Python install than Homebrew, then the two will never find each other. I recommend sticking to a single tool for installing all python libs. In other words choose either pip or Homebrew and only use that for installing everything (both MkDocs and the themes). You may need to uninstall the existing install first.

**Comment by armadsen** [comment]
Reinstalling mkdocs and the themes with pip instead of homebrew fixed the issue. homebrew doesn't seem to have formulas for `mkdocs-bootstrap` or `mkdocs-bootswatch`. It seems that if homebrew has a formula for `mkdocs`, it should have a formula for the themes as well. Perhaps I'll see about submitting a PR to homebrew for that.

Anyway, thanks so much for the super quick help, and the great software!
