### ISSUE TITLE
"News" section

### ISSUE THREAD

**Issue by lucasdemarchi** [mkdocs/mkdocs#1266]
I'm building the documentation for a project (https://intel-aero.github.io/).  I'd like to have on the first page or somewhere else a "News" section so I can communicate when new releases happen, or something else.  I haven't found any info if mkdocs support this (I think it would need to have an option to keep this section out of mkdocs.yml). Is that possible?

Otherwise, would integrating another tool like pelican to generate this part of the site a way out?

**Comment by waylan** [comment]
MkDocs does not support something like this. I suppose you could do it manually but it sounds like you would rather not. Using something like Pelican could work, except that there is currently no way to link to external pages in the navigation outside of customizing the theme templates. I expect this will be easier in the next major release, but there is no timetable on when that will happen.

**Comment by lucasdemarchi** [comment]
Doing it manually would involve a huge mkdocs.yml and changing it on each "news".  However it seems to be the most straightforward while we don't have lots of news to share :). We may revisit it later.

Thanks  for the prompt reply.
