### ISSUE TITLE
Images in headers don't create TOC items

### ISSUE THREAD

**Issue by YerayAlonso** [mkdocs/mkdocs#1268]
The Table Of Contents is constructed respecting the headers hierarchy. Ie:

```
## Google
### Subtitle
```

Shows this:

![imagen](https://user-images.githubusercontent.com/1788228/29816638-1d52e250-8cb5-11e7-8c79-2004263bdae5.png)

Now imagine you have an image you want to put instead of "Google" title. Ie:

```
## ![Google](img/google.png "Google")
### Subtitle
```

Shows this:

![imagen](https://user-images.githubusercontent.com/1788228/29816914-560385c2-8cb6-11e7-979b-a55c56e2e706.png)

The "Google" string is used for the `alt` and `title` properties of the `<img>` tag, but the item disappears from the Table Of Contents and the Subtitle loses the hierarchy.

Note I'm using material theme to show the table of contents but I believe the job of identifying `toc_items` is done by mkdocs.

**Comment by waylan** [comment]
IIRC this is an upstream issue. The TOC extension to [Python-Markdown][1] generates the TOC and strips out any markup from each header, leaving text only. Of course, the contents of the `alt` and `title` attributes are not HTML "text" so they are excluded as well.

I would say you should report this upstream, but I don't see any reasonable fix. Suppose another user has both an image *and* text side-by-side in their header (where the image is ancillary). In that case, `alt` or `title` text would be inappropriate in the TOC item. How can it tell the difference between that use case and yours?

[1]: https://github.com/Python-Markdown/markdown

**Comment by facelessuser** [comment]
Do other implementations of Markdown include images in TOC like functionality?

**Comment by YerayAlonso** [comment]
Thanks for the comments!!  
I don't see a clear way to go either :(  
I hoped there could be a way to use an image as a title and have a permalink and an item in the TOC.

At the moment, the dirty solution is to add the text in the TOC before the image, in the title:

```
## Google ![Google](img/google.png "Google")
### Subtitle
```

And remove that text manually later from the generated index.html. From this:

`<h2 id="google">Google <img alt="Google" src="./img/google.png" title="Google" /><a class="headerlink" href="#google" title="Permanent link">&para;</a></h2>`

To this:

`<h2 id="google"><img alt="Google" src="./img/google.png" title="Google" /><a class="headerlink" href="#google" title="Permanent link">&para;</a></h2>`

That's a pain, but it works...

**Comment by waylan** [comment]
@facelessuser you raise a good question. I did some checking with this input:

```
# ![Google](img/google.png "Google")
# Foo **Bar**
```

## Multimarkdown's output

```html
<div class="TOC">
    <ul>
        <li><a href="#google"></a></li>
        <li><a href="#foobar">Foo <strong>Bar</strong></a></li>
    </ul>
</div>
<h1 id="google"><img src="img/google.png" alt="Google" title="Google" /></h1>
<h1 id="foobar">Foo <strong>Bar</strong></h1>
```
1. The image was completely striped out.
2. The image `alt` text was used for the `id` of the header (but not the title; I checked).
3. The `strong` tag in the second header was not striped.

## Pandoc's output:

```html
<div id="TOC">
  <ul>
    <li><a href="#google"><img src="img/google.png" title="Google" alt="Google" /></a></li>
    <li><a href="#foo-bar">Foo <strong>bar</strong></a></li>
  </ul>
</div>
<h1 id="google"><img src="img/google.png" title="Google" alt="Google" /></h1>
<h1 id="foo-bar">Foo <strong>bar</strong></h1>
```

1. Pandoc does not strip any markup out of their TOC.
2. The image `alt` text was used for the `id` of the header (but not the title; I checked).

## Kramdown's Output:

```html
<ul id="markdown-toc">
    <li><a href="#googleimggooglepng-google"><img src="img/google.png" alt="Google" title="Google" /></a>
    </li>
    <li><a href="#foo-bar">Foo <strong>Bar</strong></a>
    </li>
</ul>

<h1 id="googleimggooglepng-google"><img src="img/google.png" alt="Google" title="Google" /></h1>
<h1 id="foo-bar">Foo <strong>Bar</strong></h1>
```

1. Kramdown does not strip any markup out of their TOC.
2. The `id` of the header is comprised of `{{ alt }}{{ path }}{{ title }}` where `path` has all punctuation striped, which I find very strange.

## Maruku's Output:

```html
<div class="maruku_toc">
    <ul>
        <li><a href="#google"><img src="img/google.png" alt="Google" title="Google" /></a>
        </li>
        <li><a href="#foo_bar">Foo <strong>Bar</strong></a>
        </li>
    </ul>
</div>

<h1 id="google"><img src="img/google.png" alt="Google" title="Google" /></h1>
<h1 id="foo_bar">Foo <strong>Bar</strong></h1>
```

1. Maruku does not strip any markup out of their TOC.
2. The image `alt` text was used for the `id` of the header (but not the title; I checked).

## Python-Markdown's Output

```html
<div class="toc">
  <ul>
    <li><a href="#_1"></a></li>
    <li><a href="#foo-bar">Foo Bar</a></li>
  </ul>
</div>
<h1 id="_1"><img alt="Google" src="img/google.png" title="Google" /></h1>
<h1 id="foo-bar">Foo <strong>Bar</strong></h1>
```

1. Python-Markdown strips all markup out of their TOC.
2. The image `alt` text is **not** used for the `id` of the header.

## Conclusion

One thing I find interesting is that all of the implementations I checked used the `alt` text for the `id` of the header except Python-Markdown (and Kramdown, which is so weird int his respect that we can ignore it). Also of note is that Python-Markdown is the only implementation which strips all markup out of the TOC. However, at least one other implementation (MultiMarkdown) does strip out images. Notably, none use the `alt` text of an image in the TOC.

In the end, there is no clear path here. Every implementation is different in various ways. with no clear pattern except that `alt` text is not used in the TOC, but is used for the header `id`. While it might make sense for Python-Markdown to make that adjustment, that doesn't solve the OP's problem.

Regarding Python-Markdown stripping out all markup, see Python-Markdown/markdown#232.  In retrospect, stripping tags was any easy-out to avoid various weird edge cases, but perhaps it's not the best approach.

**Comment by waylan** [comment]
Closing this as an upstream issue. If you want to pursue this, open an issue with Python-Markdown.
