### ISSUE TITLE
Add furigana support (ruby tag)

### ISSUE THREAD

**Issue by Nerothos** [mkdocs/mkdocs#1271]
First, a big thanks for putting together that solution, I love it and use it for my documentations  👍 

I'm not sure if you can have a hand directly on that with mkdocs or if it's on the markdown end (i've saw implementation so I think it's possible) anyway, is it possible to add support for the html ruby tag directly in markdown?

The syntax is the following one 
`<ruby><rb>base_text</rb><rp>(</rp><rt>ruby_text</rt><rp>)</rp></ruby>`
With base text generally kanji and ruby text kanas (for japanese for example)

I know I can use the html tag directly but it's unreadable when we start to use some of it.

Would you see it as an interesting improvement?

I've founds theses topics that speak of those implementations if that could help 
https://talk.commonmark.org/t/proper-ruby-text-rb-syntax-support-in-markdown/2279/24
https://japanese.meta.stackexchange.com/questions/199/jlu-hacks-ruby-rendering

N.

**Comment by waylan** [comment]
Something like that would need to be implemented as a [Markdown Extension][1], which MkDocs [supports][2]. We will not be including such an extension by default, but you are free to [develop your own extension][3] and use it on your projects.

[1]: https://pythonhosted.org/Markdown/extensions/index.html
[3]: https://github.com/Python-Markdown/markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown
[2]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
