### ISSUE TITLE
Bug in Safari on how menu is only sized to main content

### ISSUE THREAD

**Issue by alkemann** [mkdocs/mkdocs#1278]
See comparison screenshots between Safari and Firefox bellow. Desired outcome is that the sidebar get maximum height.

Safari 10.1.2 ( "buggy behaviour" ):
![safari](https://user-images.githubusercontent.com/48854/30209255-7b7f1b84-9497-11e7-9cd4-94bad37181c7.png)

Firefox 55.0.3 ("good behaviour"):
![firefox](https://user-images.githubusercontent.com/48854/30209280-8bcf16c4-9497-11e7-9c6f-359b0c120f31.png)

**Comment by alkemann** [comment]
A possible solution:
```diff
diff --git a/docs/custom.css b/docs/custom.css
index f2385f0..1adc69f 100644
--- a/docs/custom.css
+++ b/docs/custom.css
@@ -14,3 +14,8 @@
     font-size: 1.15rem;
 }

+.md-container>.md-main>.md-main__inner {
+    height: inherit;
+    position: relative;
+}
+
```

**Comment by waylan** [comment]
Which theme is this? It doesn't look like any of the included themes and the proposed patch suggests making changes to a file in the `docs` dir, which would appear to be a custom file specific to the project.

**Comment by alkemann** [comment]
Sorry. Yes the theme is material. I had both projects up and seem to have put issue on the wrong one. Sorry about that
