### ISSUE TITLE
[Question] Site wide links reference

### ISSUE THREAD

**Issue by Maxiride** [mkdocs/mkdocs#1282]
Is there a way, while using markdown to use site wide url references with mkdocs?

Like I define in the index.md:
```
[link1]: my.link
[link2]: my.link2
```

and then into another file I call the reference:
`[You can check this site][link1]`

**Comment by facelessuser** [comment]
Let me preface this with the following: I believe there are other Python Markdown extensions that can do similar things, but for the purpose of answering your question, I will use my own extension as an example as that is what I know :slightly_smiling_face:.

Extension: http://facelessuser.github.io/pymdown-extensions/extensions/snippets/
Setup Example: https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml#L87
Examples: https://github.com/facelessuser/pymdown-extensions/tree/master/docs/src/markdown/_snippets

You'll notice I usually add the reference to the snippets at the bottom of documents: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/markdown/extensions/arithmatex.md

If this doesn't suite your needs, feel free to shop around or create one that is to your liking.  It is also possible that in the future, the Mkdocs plugin API (in 1.0) might be leveraged for something similar, but really, it isn't really needed for something like this as this can basically be achieved now without it.

**Comment by Maxiride** [comment]
@facelessuser woah, your extensions are basically everything I need! Awesome, I need to read better your whole gh-page since I only stumbled upon the emoji one :see_no_evil:  :clap:

**Comment by facelessuser** [comment]
I'm glad it seems useful.  They are essentially extensions I wrote to help me write documents easier.   They are biased to how I work or what I find useful, but hopefully you may find many extensions that are useful to you as well :slightly_smiling_face:.
