### ISSUE TITLE
Feature request for latest highlight.js

### ISSUE THREAD

**Issue by JenningsWu** [mkdocs/mkdocs#1284]
Hi,

YAML syntax highlighting are supported by highlight.js but not the current version used by mkdocs. It would be great if mkdocs could update to use the latest version of highlight.js

**Comment by jemc** [comment]
We'd like to see this as well.

**Comment by waylan** [comment]
Pull requests are always welcome. Either way, this has been added to the 1.0.0 milestone so it should be available in that release.

**Comment by waylan** [comment]
I just went to update this and remembered that highlight.js has a [default bundle][1] which supports 23 languages, or you can build a custom bundle with whatever languages you want to support. Users can use MkDocs to document anything, so we shouldn't limit language support (MkDocs' own documentation uses some languages not in the default bundle: YAML and Django). At the same time, for users who only need a few languages, supporting all languages adds unnecessary bandwidth requirements.

Perhaps we should add a theme specific setting to control code highlighting. For example the user could set the option to be enabled or disabled. When enabled, the highlight.js' default set of supported languages would be used (just link to the CDN). When disabled, a user could use extra-css and extra-javascript to add their own custom bundle or use some other highlighter. A few possibilities would include using a competing JS library or providing CSS for Pygments and enabling the `codehilite` Markdown extension.

[1]: https://highlightjs.org/download/

**Comment by waylan** [comment]
Closed in #1533.
