### ISSUE TITLE
Proposal: Drop support of Python 2 and 3.3 with the 1.0 release

### ISSUE THREAD

**Issue by funkyfuture** [mkdocs/mkdocs#1288]
i will not elaborate too much on my proposal initially as this *may* get religious. here are some points why i think it's not worth to support Python 2 and 3.3 with the 1.0 release:

- i expect the 1.0 release in 2018
- Python 3.3 will be [eol](https://www.python.org/dev/peps/pep-0398/#x-end-of-life) by the end of this month
- i'm not aware of any maintained distribution that still delivers it as default Python 3 interpreter
- Python 2.7 will be [eol](https://www.python.org/dev/peps/pep-0373/#update) in 2020
- any Desktop system (which `mkdocs` aims at) is able to run Python 3 by now or even uses it as standard Python interpreter
- dropping Python 2 reduces compatibility code
- also opens opportunities to use Python 3 exlusive features and cleaner syntax

**Comment by waylan** [comment]
> Python 2.7 will be eol in 2020

I think we should maintain 2.7 support for at least that long. Despite many systems defaulting to Python 3, there are still a surprising number of users who report using 2.7.

> Python 3.3 will be eol by the end of this month

I'm okay with dropping 3.3 support, but what does this actually give us? I don't believe we actually would change anything except to eliminate that set of tests, especially if we keep 2.7 support. That being the case, we might as well keep support for as long as 2,7.

**Comment by funkyfuture** [comment]
> I think we should maintain 2.7 support for at least that long.

i'm really interested in the rationale for this. not because i'm very keen regarding `mkdocs`, but i never understand why old technologies are nurtured without the need to do so. imo, it's irresponsible to maintain a software that relies on an unmaintained one.

> Despite many systems defaulting to Python 3, there are still a surprising number of users who report using 2.7.

but they also able to use Python 3.

a breaking release is a good opportunity for such a step.

**Comment by facelessuser** [comment]
Maintain <2.6 is more of a pain than maintain 2.7. 2.6 should get dropped. I personally think it reasonable to support 2.7 to end of life. It's only a couple years away. People will be using 2 to the bitter end even if there is no reason to.

I'm meh about 3.3, and yeah, I don't think there is 3.3 specific code in the project, so no gain there unless one of the dependencies drop 3.3 support. But if one the dependencies do drop it...

**Comment by funkyfuture** [comment]
> Over the years I've come to appreciate that many users are running production systems on what their organization deems to be "stable" software.

i'm aware of this with regards to servers. does this also apply to desktop systems? at least not in the institutions i've been working so far.

> Probably not a dig deal for MkDocs

that's my point.

> but I have made it my personal practice to try to always support systems until at least their eol.

for server software and libraries this is reasonable. for user applications i'd consider it an unnecessary dogma. as a side-effect this (user applications supporting old interpreters) prolongs the need for libraries to support outdated interpreters.

> 3.3 specific code

i don't remember specifics, but iirc there are some idionsyncrasies involved when one wants to use Python 3 specific features that haven't been ironed out before 3.4. well, this assumes Python 2 has been dropped.

**Comment by waylan** [comment]
> this assumes Python 2 has been dropped.

That's my point. We're not dropping 2.7 support yet, so why bother with 3.3?

Finally, I see Python 2.7 as a special case. Many people are very resistant to adopting Python 3 at all. I don't want to get into that (personally I'm "meh" on the whole thing), but I do like giving people the choice. When 2.7 is eol, then the decision is made for everyone. Until then, the option still exists.

**Comment by funkyfuture** [comment]
> Finally, I see Python 2.7 as a special case. Many people are very resistant to adopting Python 3 at all.

so, it finally became religious. :smiling_imp:

**Comment by waylan** [comment]
I apologize, I was a little ornery this morning. Personally, I don't care one way or the other regarding Python2 vs. Python3. However, I do believe that we should not force one or the other on our users. By continuing to support both, we are refusing to take sides in the debate.

I had originally left the issue open and given it the Post 1.0 Milestone thinking that we don't want to forget about it later. But, in retrospect, 2020 is long time to leave an issue open. Therefore, I'm closing this. The matter can be revisited in 2020. If someone really cares, feel free to create a PR removing support for 3.3 and I'll merge it, but I'm not interested in spending any more time on this.

**Comment by funkyfuture** [comment]
i know there's that stupid tension within developers, but i didn't know users also care about it. well…

> By continuing to support both, we are refusing to take sides in the debate.

in a way, this perfectly describes the misery.

**Comment by twardoch** [comment]
I would personally love to forget 2.7. Unfortunately, there are many dependencies that still aren't Python 3.6-compatible. Not of MkDocs directly but things like Markdown extensions and packages used by those extensions. It all pours downstream. I think there is only a tiny portion of people who want to stay on Python 2.7 on purpose. Most are stuck with 2.7 because of dependency hell, and don't have the resources to fix or rewrite all those dependencies. So I’d be happy to see 2.7 supported for a few more years!
