### ISSUE TITLE
Render equations (latex)

### ISSUE THREAD

**Issue by nodesocket** [mkdocs/mkdocs#1301]
I'm looking for a way to render equations in mkdocs? Is there a latex plugin or way to render math based equations? Thanks.

**Comment by facelessuser** [comment]
You can try out http://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/ or check out Python Markdown's wiki and check out other math extensions. The first one relies on the JavaScript Mathjax library to render the equations after they are preserved by the extension.

**Comment by waylan** [comment]
This question was asked on StackOverflow some time ago, A pretty [comprehensive answer][1] exists (disclaimer, I provided the answer, so I may be bias) there which uses the extension at https://github.com/mitya57/python-markdown-math. That extension and the one by @facelessuser are two good (competing) methods which each take a slightly different approach. I can comfortably recommend both of them. I suggest looking at them and choosing the one which best fits your needs. The process of incorporating them into MkDocs should be very similar for each.

[1]: https://stackoverflow.com/a/31926644/866026

**Comment by facelessuser** [comment]
Yeah, I probably should be more clear that I am affiliated with Arithmatex (which is part of pymdown-extensions).

With that said, if you have no intentions of using anything else from pymdown-extensions (which is a collection of extensions which you can pick and choose extensions from), then https://github.com/mitya57/python-markdown-math probably makes more sense as it is a targeted solution to your question.  I use the former because I am already using pymdown-extensions for all my documents.

**Comment by waylan** [comment]
The two extensions each use different notation for delimiting the equations and different methods for escaping. Depending on how you work and how you intend to use it, that may also be a significant factor in which extension you choose. Personally, I like that the two options exist as each serves a different need better than a single configurable extension probably could.

**Comment by nodesocket** [comment]
Thanks for all the info and help. Decided on using the [material](http://squidfunk.github.io/mkdocs-material theme) with markdown_extension `pymdownx.arithmatex`.

I'm also looking for people who are passionate about baseball ⚾️  and MLB to help out with a project I am launching [baseball-stats.net](https://baseball-stats.net). The concept is a beautiful reference with examples of common baseball statistics.

If you are interested in helping out, check out the public repository on GitHub [baseball-stats.net](https://github.com/nodesocket/baseball-stats.net). Send in issues and PR's.

Here is a very early screenshot:

![screenshot 2017-10-05 17 35 15](https://user-images.githubusercontent.com/523312/31258373-9909a1bc-a9f3-11e7-8c7d-b4d16f4b9130.png)

**Comment by facelessuser** [comment]
@nodesocket Glad you got it working.  And yeah, since Material has adopted pymdown-extensions, it makes since to just take advantage of it since it is already installed 😉.
