### ISSUE TITLE
Comment in Markdown that is not rendered in the build

### ISSUE THREAD

**Issue by nodesocket** [mkdocs/mkdocs#1303]
Is it possible to add a comment in the Markdown that is **not** rendered in the build output? Using `<!--` and `-->` renders the comment in the build.

**Comment by facelessuser** [comment]
There is this extension (I haven't tried it): https://github.com/ryneeverett/python-markdown-comments.

And there is the one included in pymdown-extensions (which I maintain): http://facelessuser.github.io/pymdown-extensions/extensions/plainhtml/.  It was mainly created to strip out unwanted attributes and comments in cases where you wanted the HTML tags or had specific attributes you wanted to strip out, but you can disable the other attribute stripping if you just want comments, which in reality is the main thing I use it for, so I set it to strip no attributes (see below).

```py
  - pymdownx.plainhtml:
      strip_attributes: ''
```

**Comment by twardoch** [comment]
https://github.com/ryneeverett/python-markdown-comments works nicely.
