### ISSUE TITLE
external font 

### ISSUE THREAD

**Issue by patatetom** [mkdocs/mkdocs#1305]
hi,

using external font in theme (readthedoc) can take long time to display page in "offline" browser.

regards.

`<link href='https://fonts.googleapis.com/css?family=Lato:400,700|Roboto+Slab:400,700|Inconsolata:400,700' rel='stylesheet' type='text/css'>`

**Comment by waylan** [comment]
While not a direct duplicate, this is very similar to #1138 and, in fact, is mentioned in a comment there. Whatever solution we use will likely address this as well. Therefore, I'm closing this as a duplicate.

**Comment by patatetom** [comment]
sorry for the noise, I didin't remember my previous issue :-(
