### ISSUE TITLE
Code highlighting not deployed with gh-deploy

### ISSUE THREAD

**Issue by maurelian** [mkdocs/mkdocs#1311]
I have configured code highlight using a customer pygments lexer, in [pymarkdown.highlight](https://facelessuser.github.io/pymdown-extensions/extensions/highlight/).

When I run either `mkdocs build` or `mkdocs server` the highlighting works.

When I run `mkdocs gh-deploy` the highlighting is lost.

`mkdocs`, `pygments`, and the [customer lexer](https://gitlab.com/veox/pygments-lexer-solidity) are all installed using pip. 

The site is here: https://maurelian.github.io/best-practices-docs/known_attacks/

**Comment by facelessuser** [comment]
Please create an issue over at the pymdown-extensions repo and ask questions there.  This isn't the place to track 3rd party extension questions.  Most likely this is a user configuration issue.  When you create the issue there, please provide your mkdocs.yml config so I can see how you've configured things.

**Comment by waylan** [comment]
I just checked your site and code highlighting is working fine. Perhaps you need to delete your browser's cache?

Also, I couldn't help buy notice that you are using the [Material][1] theme. Any problems related to that theme should be reported to that project. 

As code highlighting is theme dependent and you are using a third party Markdown extension for highlighting, it seems unlikely that MkDocs can help. This matter should be reported downstream. I'm closing this for now. If, in fact, this is a problem with MkDocs, leave a comment explaining why (and link to the relevant downstream issue) and we'll reconsider.

[1]: https://github.com/squidfunk/mkdocs-material

**Comment by maurelian** [comment]
>I just checked your site and code highlighting is working fine. Perhaps you need to delete your browser's cache?

Oh, yes, it's working! 

Thank you both, for monitoring this repo as well as your own projects. :)
