### ISSUE TITLE
rotten left menu in readthedocs theme

### ISSUE THREAD

**Issue by epogrebnyak** [mkdocs/mkdocs#1312]
I'm building the following documentation at <https://mini-kep.github.io/documentation>, the source is at <https://github.com/mini-kep/documentation>.

A local server shows documentation well, but on github pages, the left menu in rotten:  links below 
Data Pipeline menu item are in pale grey, they are offset and not clickable. Used several browsers to view it. 

I tryied erasing the ```site``` folder and ```gh-pages``` branch but the problem persists. Any ideas?

**Comment by waylan** [comment]
I just checked your site and it looks fine to me. Sounds like you need to clear your cache.  I would suggest browser cache, but you said you tried multiple browsers. Are you behind a caching proxy or something?

**Comment by waylan** [comment]
Opps, sorry, didn't mean to close this yet.

**Comment by epogrebnyak** [comment]
Indeed, on a different network the site looks fine. Could be the firewall issue as you describe. Many thanks for checking.
