### ISSUE TITLE
anchor link

### ISSUE THREAD

**Issue by homerzhou** [mkdocs/mkdocs#1320]
anchor link in mkdocs is not case sensitive?

```
## License
[example](index.md#license)      ---- Success
[example](index.md#License)     ----- Fail
```

**Comment by waylan** [comment]
Yes, MkDocs uses the [TOC} extension to Python-Markdown. That extension converts all text to lowercase and replaces spaces with underscores when generating slugs.

You are not the only one who likes the default behavior, which is the subject of #212. You will find a few alternatives there. I'm closing this as a duplicate.

[TOC]: https://pythonhosted.org/Markdown/extensions/toc.html
