### ISSUE TITLE
Error: Unrecognised theme name: 'material'

### ISSUE THREAD

**Issue by nodesocket** [mkdocs/mkdocs#1323]
Brew decided to upgrade `mkdocs` which in turn broke:

```
iMac ➜  baseball-stats.net git:(master) mkdocs serve
INFO    -  Building documentation...
WARNING -  Config value: 'site_favicon'. Warning: Unrecognised configuration name: site_favicon
ERROR   -  Config value: 'theme'. Error: Unrecognised theme name: 'material'. The available installed themes are: readthedocs, mkdocs

Aborted with 1 Configuration Errors!
```

The most concerning is `material` is not a valid theme? What am I missing?

**Comment by waylan** [comment]
The material theme is a third-party theme which ships separately from MkDocs and needs to be installed separately. However, I believe the theme has not yet been updated to work with 0.17 of MkDocs. I would suggest you check downstream with the developers of the theme.

The `site_favicon` config setting has been deprecated for a few versions now. Simply remove the setting from your config file and ensure your favicon file is located at `img/favicon.ico` in your `docs_dir`.

**Comment by waylan** [comment]
Favicons are documented [here](http://www.mkdocs.org/#changing-the-favicon-icon).
