### ISSUE TITLE
Error 500 when accent in query

### ISSUE THREAD

**Issue by sebw** [mkdocs/mkdocs#1332]
For example `/randonnée`

```
# curl -I http://127.0.0.1:8000/randonn%C3%A9e
HTTP/1.1 500 Internal Server Error
Date: Sun, 29 Oct 2017 14:38:13 GMT
Content-Length: 93
Content-Type: text/html; charset=UTF-8
Server: TornadoServer/4.5.2
```

Stacktrace:

```
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2358, in get
        self.root, absolute_path)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2539, in validate_absolute_path
        if (os.path.isdir(absolute_path) and
      File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
        st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 22: ordinal not in range(128)
```

**Comment by waylan** [comment]
For the record, the requested URL appears to be encoded correctly:

```python
>>> path = u'/randonnée'
>>> path.encode('utf-8')
'/randonn\xc3\xa9e'
>>> urllib.quote(path.encode('utf-8'))
'/randonn%C3%A9e'
```

I can't help but notice that the error appears to be raised from within tornado (when determining if the requested path is a dir that exists), which makes me suspect this is an upstream problem.

Also, I wonder if the problem persists with Python 3.

Finally, if you link to a page with that name from within another page, how does the URL get rendered? Does that request work properly?

**Comment by waylan** [comment]
Are you sure that all files are saved as `utf-8` files?

I'm not seeing this behavior. Without the file existing I receive these headers:

```
HTTP/1.1 404 Not Found
Date: Mon, 30 Oct 2017 15:20:15 GMT
Content-Length: 5714
Content-Type: text/html; charset=UTF-8
Server: TornadoServer/4.3
```

And after creating the file: 

```
HTTP/1.1 200 OK
Content-Length: 8763
Accept-Ranges: bytes
Server: TornadoServer/4.3
Last-Modified: Mon, 30 Oct 2017 15:30:25 GMT
Etag: "be14239da67282c49753781aac4e7468"
Date: Mon, 30 Oct 2017 15:30:25 GMT
Content-Type: text/html
```

A Markdown link to the page: `[randonnée](randonnée.md)` generated the following HTML: `<a href="randonnée/">randonnée</a>`, which worked just fine.

Note that I did receive an error or two when setting up the test as I had failed to notice that the text editor I used had defaulted to an encoding other than `utf-8`. Once I switched the encoding of all files to `utf-8` and saved, all errors disappeared.

**Comment by sebw** [comment]
I'm investigating now, I can't reproduce the problem at work. My report is actually on a mkdocs instance behind an Apache reverse proxy.

**Comment by waylan** [comment]
Are you pointing a proxy server at the `mkdocs serve` server? Don't do that. We do not support such a use-case and provide no guarantee that it will work.

MkDocs is a **Static Site Generator**. The intention is to build static files which are copied to a *static* directory of a third-party production level *static* file server. If you are serving the site through Apache, then the content of the `site_dir` after a build should be copied to a *static* file directory of the Apache server.  

We only provide the "dev server" as a convenience for local development only. Not everyone has a static file server handy on their local machine for testing, so we provide one. But that is the only use-case we support.

**Comment by sebw** [comment]
I found the problem, it lied in the encoding of the system (Debian). It was supposedly set to `en_US.UTF-8` but something was apparently missing.

After following this procedure, I don't get the error anymore, I get a proper 404 error:

https://unix.stackexchange.com/questions/303712/how-can-i-enable-utf-8-support-in-the-linux-console

I'm closing this report.

Thanks!
