### ISSUE TITLE
Empty or non-defined extra_css generates warning

### ISSUE THREAD

**Issue by kcgthb** [mkdocs/mkdocs#1335]
I have a bit of css files in my project that I *don't* want  to include in `extra_css`.

With 0.17, even if I define empty lists in `mkdocs.yml`, I get a warning that makes `--strict` building fail.

For instance, with this in `mkdocs.yml`
```yaml
extra_css:
  - ' '
```
I get:
```
$ mkdocs build --strict
WARNING -  Config value: 'extra_css'. Warning: Some files in your 'docs_dir' are not listed in the 'extra_css' config setting and will be ignored by the theme. Add the following files to the 'extra_css' config setting if you want them to have an effect on the theme: ['file.css']

Aborted with 1 Configuration Warning in 'strict' mode!
```
The exact same thing happens if I remove the `extra_css` part from `mkdocs.yml`.

Is there a way to build in `strict` mode while making sure that extra CSS files are not added to the project?

**Comment by waylan** [comment]
No, not at this time, although, that should be temporary. Prior to this release, all CSS files in your `docs_dir` were automatically added to `extra_css` if the setting was empty. During the transition, we are issuing a warning for those users who now need to add a list of files to the setting. I expect the warning will be downgraded to an "info" message in the future.

**Comment by kcgthb** [comment]
All right, thanks for the clarification. I guess I'll build without `--strict` for now.
