### ISSUE TITLE
Adopt Semantic Versioning

### ISSUE THREAD

**Issue by robodude666** [mkdocs/mkdocs#1340]
`mkdocs` should consider adopting [Semantic Versioning](http://semver.org) to make it easier for its users to known when to expect backwards compatibility and when to expect breaking changes.

**Comment by waylan** [comment]
We do. Note that we have not yet reached version 1.0.0. As [rule 4][1] states:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

In practice, we make breaking changes on 0.y releases and only bugfixes on 0.y.z releases. Of course, that practice will change upon the release of version 1.0.0.

[1]: http://semver.org/#spec-item-4

**Comment by robodude666** [comment]
Fair point. Forgot about the `0.y.z` exception.
