### ISSUE TITLE
Easy change of markdown engine?

### ISSUE THREAD

**Issue by HaoZeke** [mkdocs/mkdocs#1344]
Is it non-trivial to switch to pandoc or pypandoc?

**Comment by waylan** [comment]
At this time we do not support switching the Markdown parser. And we do not currently have any plans to include such support in a future release.

I suppose it might be possible with a [Plugin][1]. However, there is no way to override the builtin Markdown parsing. One could conceivably build a plugin which discards the rendered Markdown and then call a separate parser and return its output as a replacement. Such a plugin would need to be developed and maintained as a third party plugin. There would be no official support for it.

[1]: http://www.mkdocs.org/user-guide/plugins/
