### ISSUE TITLE
navigation is different on each page

### ISSUE THREAD

**Issue by zoubin** [mkdocs/mkdocs#1352]
version: 0.17.2

If `pages` is not specified in the configuration file (mkdocs.yml), the navigation built by the built-in theme (mkdocs) varies on each page.  
Is this the meant behavior? 
How to make the navigation on all pages show the same title when `config.pages` is None?

**Comment by waylan** [comment]
Are your page titles being determined by the first H1 in the body of your documents? If so, then this is a duplicate of issue #1347.

**Comment by zoubin** [comment]
Yes, I think so.  I'll watch that issue. Thanks!
