### ISSUE TITLE
site_url don't apply with all url

### ISSUE THREAD

**Issue by thomas-illiet** [mkdocs/mkdocs#1362]
Hello :)

I recently encountered an error in my mkdocs, site_url do not apply with all url :/

`<link rel="canonical" href="http://0.0.0.0:8000/powershell/office365/get-msoluserlicences/">`

`<script type="text/javascript">document.write("<script src=http://" + window.location.hostname + ":8000/livereload.js> </"+"script>");</script></head>`

` <a href="http://0.0.0.0:8000/" title="My Mkdocs" class="md-header-nav__button md-logo">`

I think I configured it well :

> site_name: 'My Mkdocs'
site_description: 'NNNNNNNN'
site_author: 'Thomas ILLIET'
site_url: 'https://XXXXX.YYYYY.fr'
edit_uri: '/master/book/'

my site is exposed from the web on different url = 'https://XXXXX.YYYYY.fr'

do you have idea  for my issue ?

**Comment by waylan** [comment]
I'm not sure I understand your problem. Can you tell us what Markdown are you using in your document? What HTML does it output? How does that differ from the expected output?

**Comment by thomas-illiet** [comment]
Hello Waylan,

you can found directly this problem on my website  : https://cookbook.netboot.fr

**Comment by waylan** [comment]
Could you still provide the answers to my three questions above? Thank you.

**Comment by thomas-illiet** [comment]
I wylan,

This error is present on all mkdocs sites.

I would like the livereload to work too!

**Comment by waylan** [comment]
I'm sorry but I'm not sure I understand the problem. Are you taking about URLs in templates or URL's in Markdown?

Do you mean that the `site_url` is not prepended to every URL or something else?

And what does this have to do with livereload?

As stated previously, please provide a complete, reproducible  example with the input, expected output and actual output.
