### ISSUE TITLE
hyperlink not working in static pages

### ISSUE THREAD

**Issue by jkobti** [mkdocs/mkdocs#1367]
I'm trying to build a documentation with mkdocs. The problem is that the links in the static created pages are not working. Instead of going to [folder]/index.html I'm presented with the following page like in the following imag e![image](https://user-images.githubusercontent.com/5858677/34488915-90a8055e-efda-11e7-8962-8abeb3f0e76e.PNG)

The problem however doesn't exist when i try mkdocs serve

I'm writing the yml file like this: 
`pages:
    - Home: 'index.md'
    - Customer: 'customer.md'
    - Admin: 
        - 'Main page' : 'admin-functions/main-page.md'
        - 'login page' : 'admin-functions/login-page.md'`

and the resulting hyperlinks are like this:
`<a class="" href="admin-functions/main-page/">Main page</a>`

so I don't think that the browser can figure out that index.html should be used.

**Comment by waylan** [comment]
Yes, the static pages expect to be served by a server. Browsing them with the `file://` scheme is not expected to work. As a reminder, the actual filename is not included in the URL. Of course, web servers know to return the contents of `index.html` for the requested directory if no file is specified. However, the filesystem on your computer knows nothing about that.

You could set the [use_directory_urls][1] setting to `False`, which would include the filename in each URL. But be warned that search will still not work without a server.

[1]: http://www.mkdocs.org/user-guide/configuration/#use_directory_urls

**Comment by jkobti** [comment]
thanks :)
