### ISSUE TITLE
创建工程后启动，打开lcalhost:8000预览效果不一样

### ISSUE THREAD

**Issue by EmperorZzl** [mkdocs/mkdocs#1372]
预览的效果是这样
http://www.cnperfect.top/upload/2018/01/3i11mtq3gehairuntorafe0rjn.png

**Comment by waylan** [comment]
For the record, google translate gives this translation of this report:

> # After creating a project to start, open lcalhost: 8000 preview is not the same effect 
>
> The effect of the preview is this 
http://www.cnperfect.top/upload/2018/01/3i11mtq3gehairuntorafe0rjn.png

Which theme are you using? Perhaps providing a copy of your `mkdocs.yml` configuration file would be most helpful.

Also, if you do a `build`, do the theme related files get copied to the `site_dir`?

**Comment by waylan** [comment]
Closing this as we do not have enough information to duplicate the reported problem.
