### ISSUE TITLE
link a file at the root of the project

### ISSUE THREAD

**Issue by jodumont** [mkdocs/mkdocs#1373]
Hi everyone;

I tried to make a file which is at the root of my project into mkdocs
let's me try to explain

mkdocs render everything inside ./docs/*
my file is at the root level which like ./norendering.md instead of ./docs/rendering.md

an example I found is https://github.com/mkdocs/mkdocs/blob/master/CONTRIBUTING.md what if I want this file appear inside the website like this one https://github.com/mkdocs/mkdocs/blob/master/docs/index.md

regards!

Jonathan

ps: if rendering is not the appropriate words tell me how to speak python/jinga/mkdocs :)

**Comment by waylan** [comment]
This appears to be related to #1134. As there is currently no open issue for this, I'll leave this open so we don't forget about it.

**Comment by jodumont** [comment]
wow I just saw (https://github.com/mkdocs/mkdocs/commit/34ef3ca6d0390959080ce93a695361eea1649272#diff-55f7e7bab4ecafd524c20778d6920fdaR43)

I can't wait to test it :)

Thanks!

**Comment by waylan** [comment]
@jodumont a beta has been released. Please do test it out. To install do:

    pip install --upgrade mkdocs=1.0b1

**Comment by deltahedge1** [comment]
after sometime I found some extensions which did the trick, using `pymdown-extensions` and specifically the `snippets` ext you can now include files like README.md and changelog.md from your root directory. 

https://facelessuser.github.io/pymdown-extensions/extensions/snippets/

**Comment by ssbarnea** [comment]
@deltahedge1 Sadly this approach does not work with mkdocs monorepos and probably neither with simple inclusion.
