### ISSUE TITLE
Title doubles

### ISSUE THREAD

**Issue by Serhioromano** [mkdocs/mkdocs#1374]
I have a file in subdirectory. Let's say I call it ACL.md. In config it is used like this

```
pages:
- Developer:
    - ACL: ACL.md
```

The file starts with H1 tag and then other titles like a structure. The H1 title is the same meaning as the title in config file. So in navigation title doubles and create unnecessary level. I have only one H1 per file.

Is it possible to tell mkdocs not to use first H1 in menu navigation? I have a screenshot, not sure if it is helpfull because it is on russian.

![2018-01-08_13-24-05](https://user-images.githubusercontent.com/650741/34661992-989b69e4-f477-11e7-963b-9f418c7775d3.png)

1 - is a title in configuration

    - Метод API: 'developer/apiendpoint.md'

2 and 3 is H1 title in the document. how to avoid this?

**Comment by algo99** [comment]
++
Looks like feature request for me as well.

We solve this though not using H1 headers in our index.md files.

**Comment by waylan** [comment]
At this time there is no builtin way to account for this. However, you might be able to address this through [theme customization][1]. I haven't looked at the template, not sure if it would be a simple fix or not.

[1]: http://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme-custom_dir

**Comment by squidfunk** [comment]
Material uses a hack to determine if a `h1` is included in the Markdown source, see:

https://github.com/squidfunk/mkdocs-material/blob/5bc0875e7e3bb5edfb984a516b22cc74acb5d257/src/partials/toc.html#L29-L37

**Comment by waylan** [comment]
@squidfunk interesting approach. Not sure how that it supposed to work in the layout for the readthedocs theme though. We would then have children with no parent. I suspect the right approach would be to skip/exclude the child link to the `h1`. The parent link to the "page" would get you there anyway.

**Comment by squidfunk** [comment]
This hack has been in Material for a long, long time and it works reasonably well. It just kills the first layer of TOC if it is an `h1`, but it also assumes that there is only one `h1` per document, which is semantically correct.

However, just wanted to let you know how I solved the problem.

**Comment by Serhioromano** [comment]
@squidfunk Of course it is solvable with hack. i can override navigation file and exclude that. But that way I rather solve my own problem but not the problem itself.

On the other hand Python is not my strongest side. If it would be PHP or JS, I would create PR instead of issue.

**Comment by cjsheets** [comment]
Unfortunately, the [rtd-dropdown](https://github.com/cjsheets/mkdocs-rtd-dropdown) theme doesn't gracefully support all doc structures at the moment. Thanks for referencing the issue @Serhioromano. 

I'm almost done cleaning up the initial implementation and adding configuration options to extend support to additional doc structures.

Because MkDocs is pretty flexible, users will probably still need to pick a convention and stick to it. I'll improve the Readme to clarify what configurations are supported to create the nested effect.

Thanks for referencing the technique used in Material @squidfunk. After some testing I think I'll need to do something similar. I'll have to make it a configurable option though because the ReadTheDocs convention is to have multiple H1 tags per page and make the TOC collapse at each one.

**Comment by squidfunk** [comment]
> because the ReadTheDocs convention is to have multiple H1 tags per page

Correct me, but from my knowledge that's semantically incorrect HTML, except when those headlines are enclosed in separate `article` tags.

**Comment by Serhioromano** [comment]
If there are few H! tags per document it is logical to use those as collapsable in menu. it mean that user user H1 tags to create sections of the document.

I use H1 tag to create a single title of the document. I think it is logical that user see the same title as menu link used to be, on which he clicked. Also the point of MkDocs to use markdown as text, in my opinion is to have readable base. So even if website is not generated, documents are automatically readable for example though github document preview.  So the H1 title in the document become very important.
