### ISSUE TITLE
HTML codes of navigation tree takes up too much space

### ISSUE THREAD

**Issue by mohanson** [mkdocs/mkdocs#1381]
I've been using Mkdocs to post blogs, until I've posted hundreds of articles, and I've found that every `index.html` will have the HTML codes of the navigation bar, the navigation bar occupies far more space than my article.

Is there a way to just let the code of the navigation bar not be copied to every `index.html` ?

**Comment by froschdesign** [comment]
@mohanson 
Can be done in a theme / template. Example:

```html
{% if page.is_homepage %} navigation bar here {% endif %}
```

But CSS would be a better choice. Hide the navigation by default and add a button the show them.

**Comment by waylan** [comment]
This sort of thing can be accomplished by theme customization. You could [create your own theme][1] or [override the behavior of an existing theme][2].

It's not documented, but you can even assign a specific document to use a different template that the default with the `template` meta-data value.

As there is no actionable item for us, I'm closing this.

[1]: http://www.mkdocs.org/user-guide/custom-themes/
[2]: http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme
