### ISSUE TITLE
Git author and committer environment variables are not respected during gh-deploy

### ISSUE THREAD

**Issue by danielhoherd** [mkdocs/mkdocs#1383]
The following [git environment variables](https://git-scm.com/book/gr/v2/Git-Internals-Environment-Variables) do not appear to be respected by mkdocs when running `mkdocs gh-deploy`:

- GIT_AUTHOR_NAME
- GIT_AUTHOR_EMAIL
- GIT_COMMITTER_NAME
- GIT_COMMITTER_EMAIL

Probably more are not respected, but these are the ones I observed in my own environment after switching from ~/.gitconfig to environment variables. When I re-enabled these configurations in ~/.gitconfig and ran a test `mkdocs gh-deploy` the commit information was available in the new commit.

**Comment by waylan** [comment]
Our gh-deploy script is a light wrapper around [ghp-import][1]. Does that script exhibit the same behavior?

I would say this is an upstream issue, but we use a locally vendored fork, so we need to update our own copy to match upstream. Please report this upstream, and leave a comment here pointing to the upstream issue. If/when this is addressed upstream, we'll merge the fix here.

As an aside, there are some corner cases were our wrapper doesn't work (see #1291). In those situations using ghp-import directly is the only workable solution at this time. The down side is that you don't get to store the config values for the script in the `mkdocs.yml` config file. They need to be passed in on the command line instead.

[1]: https://github.com/davisp/ghp-import

**Comment by danielhoherd** [comment]
I've checked the behavior of `ghp-import` and found that the bug is there. I'll file this bug with them. Thanks for the guidance @waylan.

**Comment by danielhoherd** [comment]
Filed https://github.com/davisp/ghp-import/issues/67

**Comment by waylan** [comment]
As a side note, we would likely need to support ghp-import's `-s` flag (use shell). But according to davisp/ghp-import#63, that appears to be buggy. We'll review this if/when ghp-import is updated.

**Comment by waylan** [comment]
Just noted that this was fixed upstream in version 0.6.0. We will likely get the change when we follow through with #2170.
