### ISSUE TITLE
Multiple lines in a table cell - impossible?

### ISSUE THREAD

**Issue by VanKurt** [mkdocs/mkdocs#1384]
Hi,
I would like to create a table where cells can have multiple lines of text or code in them. Can this be achieved with mkdocs?

PS: This is my current table. Here all lines are merged into a single line of code, which does not look nice.

Language | Example
--------- | -----------
**C#** | ```CodeLine1(); CodeLine2(); CodeLine3();```

**Comment by waylan** [comment]
That is correct. Table cells cannot contain block level elements, therefore you cannot have multiple lines within a cell. That is a limitation of the upstream table extension provided by Python-Markdown. That is also the behavior of most Markdown table implementations.

However, Python-Markdown does have an [extension API][1] and various [third-party extensions][2] exist. Perhaps one of them supports multi-line tables (I haven't checked). Or you can always [build your own][3]. MkDocs fully [supports][4] Python-Markdown extensions.

As there is no actionable item for MkDocs, I'm closing this.

[1]: https://python-markdown.github.io/extensions/api/
[2]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
[3]: https://github.com/Python-Markdown/markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown
[4]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by yonixw** [comment]
If some one still searching, see https://stackoverflow.com/a/71132936/1997873
