### ISSUE TITLE
Plugin API option name does not work

### ISSUE THREAD

**Issue by raimon49** [mkdocs/mkdocs#1391]
I am trying to implement my Plugin by referring to the [document of Plugin API](http://www.mkdocs.org/user-guide/plugins/).

When `mkdocs.yml` is set as follows, Events has no problem.

```yml
plugins:
  - mkdocs_my_plugin
```

However, when trying to set `option_name`, a warning will be generated.

```yml
plugins:
  - mkdocs_my_plugin:
      lang: en
```

And 'plugins' in `config.user_configs` passed in Events will also be empty.

```console
$ mkdocs build
WARNING -  Config value: 'plugins'. Warning: (u'lang', u'Unrecognised configuration name: lang')
```
Is something missing to get own configuration option value?

My environment:

* Python 2.7.14
* mkdocs, version 0.17.2

**Comment by waylan** [comment]
You need to define a [config_scheme][1] in your Plugin class. It looks like this needs to be more fully documented. As a start, the [tests][2] show how to define a simple scheme.

We'll leave this open to remind us to update the documentation.

[1]: http://www.mkdocs.org/user-guide/plugins/#config_scheme
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/tests/plugin_tests.py#L14

**Comment by raimon49** [comment]
@waylan Oh, thanks for your advice.

I was able to define my `config_scheme` tuple, and get my Plugin configuration option value.
