### ISSUE TITLE
Low frame rate when scrolling on large screens

### ISSUE THREAD

**Issue by rpkilby** [mkdocs/mkdocs#1394]
Scrolling the docs on a large screen (2560x1440) has a very noticeable impact on frame rate (drops to between 10 and 20 fps). This is due to using `background-attachment: fixed` for the body's background image. Disabling that property fixes the issue. Of course, that also disables the fixed background. 

There is a solution presented in [this article](https://www.fourkitchens.com/blog/article/fix-scrolling-performance-css-will-change-property/), but it's not clear to me how to adapt this to a background for the entire body.

**Comment by yeraydiazdiaz** [comment]
Hi @rpkilby, thanks for reporting this, I made a quick stab at implementing your suggested solution but I can't test it myself on big screen, any chance you could test it?
