### ISSUE TITLE
Please allow overriding use_directory_urls option via a command line flag

### ISSUE THREAD

**Issue by mitya57** [mkdocs/mkdocs#1401]
Dear mkdocs developers,

Some projects have `use_directory_urls: true` in their `mkdocs.yml` files, which creates some problems when browsing the documentation locally.

I am Debian packager, and we often package documentation to make it easier for developers to browse it locally. So it would be nice to have a `--use-directory-urls=false` flag (or similar) to override that setting, so that I don’t have to patch `mkdocs.yml`.

**Comment by waylan** [comment]
That seems like a reasonable reason for adding that option. However, it's not going to be high on my priority list, so a PR is more likely to get the change made sooner than later.

**Comment by waylan** [comment]
> use-directory-urls: false does not work in mkdocs.yml while using 1.0.4

Please report this as a separate issue.
