### ISSUE TITLE
Documentation Links to Python Markdown library broken

### ISSUE THREAD

**Issue by FireSBurnsmuP** [mkdocs/mkdocs#1402]
On the page http://www.mkdocs.org/user-guide/configuration/#markdown_extensions the links to the Python Markdown library are broken.

You'll notice that www.PythonHosted.org/Markdown yields a 404 error, so they must have either closed down shop, or (much more likely) they've moved to a new location.

I tried to clone the repo and make the changes, so I could submit a pull request instead, but the latest version already has the new location - https://python-markdown.github.io/.

Does the online documentation just need to be rebuilt?

Thanks!

**Comment by waylan** [comment]
As you note, this was fixed in b9b3749. The docs will be updated with the next release.
