### ISSUE TITLE
doc: enhance search experience

### ISSUE THREAD

**Issue by s-pace** [mkdocs/mkdocs#1404]
👋 team,

I like your website and I couldn't help providing you [a nice search experience for your nice documentation](https://community.algolia.com/docsearch/):
![Demo DocSearch](https://cl.ly/pN8m/Screen%20Recording%202018-02-07%20at%2006.27%20PM.gif)

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:
- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />
<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '948e42f1fa7275355f1458e1a749d0fa',
  indexName: 'mkdocs',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

- Add a search input if you don't have any yet, and update the inputSelector value in the code snippet to a CSS selector that targets your input field.
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/mkdocs.json). Feel free to open pull requests!

Feel free to get back to us if you have any issues or questions regarding the integration.
We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

**Comment by s-pace** [comment]
Hi @KuroNoDev @waylan ,

Let us know if you need any help or if you have any feedback?

I have updates your config, changes are already live.

Cheers

**Comment by waylan** [comment]
We already have a search feature that works great. And I don't use products which use spam-like advertising. so No thanks!

**Comment by s-pace** [comment]
@waylan Thanks for your feedback, I will remove tou index then.

I was just asking feedback since it takes us some ressources and we had none.

Nothing related with spam :)

Thanks again.

**Comment by igitur** [comment]
@s-pace Kudos to you for keeping it professional, despite the other comments.

**Comment by s-pace** [comment]
Thank you for this kind and super feedback @igitur 

Would you be interested in integrated DocSearch into the website? It will be great value from a UX POV

**Comment by oprypin** [comment]
https://github.com/mkdocs/mkdocs/issues/1404#issuecomment-375306327 still stands. Please let's not bump this thread for no good reason.
