### ISSUE TITLE
theme custom parameters parsed as a name

### ISSUE THREAD

**Issue by akovachev** [mkdocs/mkdocs#1405]
Trying to customize a theme based on [the documentation here](http://www.mkdocs.org/user-guide/configuration/#theme).

`theme: 'material'` works as intended. When I try to setup other theme parameters it fails as it is parsing the list of parameters as a theme name itself - see output below. Even trying to set the just the name as a sub-item under theme fails.

**mkdocs.yaml**
```
site_name: My Docs

theme:
  name: 'material'
```

**Error Output**
```
$ mkdocs serve
INFO    -  Building documentation... 
ERROR   -  Config value: 'theme'. Error: Unrecognised theme '{u'name': u'material'}'.
The available installed themes are: material, readthedocs, mkdocs
```

**Additional information**
```
$ python --version
Python 2.7.10
$ mkdocs --version
mkdocs, version 0.16.3
```

**Comment by waylan** [comment]
As pointed out in the [release notes][1], theme parameters (or nested options) were a new feature added in MkDocs version 0.17. However, you appear to be using version 0.16. Either update to a newer version of MkDocs or use the older method without parameters to set your theme:

```yml
theme: material
```

[1]: http://www.mkdocs.org/about/release-notes/#theme-customization-1164

**Comment by akovachev** [comment]
Thank you, @waylan !

I'm closing this as it is a user error, but I'm sure others in the same situation will find your answer very useful.
