### ISSUE TITLE
Not able to build with circleci with github

### ISSUE THREAD

**Issue by Tslimshady99** [mkdocs/mkdocs#1413]
I keep getting this everytime i try to use circleci to deploy.
```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/ubuntu/Docs/site 
INFO    -  Copying '/home/ubuntu/Docs/site' to 'gh-pages' branch and pushing to GitHub. 
ERROR   -  Failed to deploy to GitHub with error: 
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.

ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 

mkdocs gh-deploy returned exit code 1

Action failed: mkdocs gh-deploy
```

**Comment by waylan** [comment]
The `mkdocs gh-deploy` command is a light wrapper around [ghp-import][1], which is a light wrapper around git. Are you sure that either git or ghp-import does not return this error when pushing to GitHub? If they both work, then we can look at why MkDocs is not working. However, I suspect this is an upstream issue.

Try doing this in your script:

```sh
mkdocs build
ghp-import site
git push origin gh-pages
```

Note that in this scenario, we are using git directly to push. When you get authentication working there, then it should work with ghp-import's `--push` flag and with `mkdocs gh-deploy`.

[1]: https://github.com/davisp/ghp-import

**Comment by sinkcup** [comment]
> ERROR: The key you are authenticating with has been marked as read only.

I have this problem on travis-ci.org too, there are 2 ways to resolve:

1. create a deploy key "Allow write access" at github.com/{username}/{repository}/settings/keys, then follow https://github.com/openwrtio/openwrtio.github.io/blob/mkdocs/.travis.yml
2. add a "Personal access tokens" at https://github.com/settings/tokens , then paste to ci config.

**Comment by Tslimshady99** [comment]
Thanks i was able to fix the error

**Comment by casperdcl** [comment]
Still have this issue here: https://circleci.com/gh/openworm/openworm_docs/574 despite having a github ssh user key with read/write access (https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys) and no default (read only) deploy key

```
WARNING -  Version check skipped: No version specificed in previous deployment. 
INFO    -  Copying '/home/circleci/repo/site' to 'gh-pages' branch and pushing to GitHub. 
ERROR   -  Failed to deploy to GitHub with error: 
ERROR: Permission to openworm/openworm_docs.git denied to openworm-bot.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 
Exited with code 1
```
