### ISSUE TITLE
mkdocs inter-cite reference issue

### ISSUE THREAD

**Issue by kongdeju** [mkdocs/mkdocs#1420]
cite like this 
书写一个质能守恒公式[^LaTeX]
will turn into:
书写一个质能守恒公式[1]

is this possible in mkdocs ?

**Comment by waylan** [comment]
I'm not sure I understand. The carrot (`^`) is used for footnotes. Are you trying to use footnotes or are you trying to create a link? Please provide the Markdown, the actual HTML output and the expected output.

**Comment by kongdeju** [comment]
thanks for you answer@walan.
      i mean if (^) ifootnotes is supported by mkdocs markdown ?  i am trying to use markdown to write scientific reference

**Comment by facelessuser** [comment]
There is a footnotes extension that enables footnotes which you don't have to use, but scientific notation is not part of the Markdown specifications. Scientific notation is a convention that was created outside of Markdown, though some implementations might pair it with Markdown. I'd look to see if there is a 3rd party extension that will give you the ability you are looking for.

**Comment by waylan** [comment]
You can add to Markdown's standard features using the [markdown_extensions][1] config setting. If you want to have support for footnotes or any other non-standard feature, review that documentation for how to enable such features. You will also find links there to lists of available extensions.

[1]: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by kongdeju** [comment]
thank you so much . i will hava a try !
