### ISSUE TITLE
Autogen nav for pages in a sub-directory

### ISSUE THREAD

**Issue by pylang** [mkdocs/mkdocs#1430]
Is there an option to generate pages for all files in a directory.  For example, in the `mkdocs.yml`, rather than pointing to  every page in a directory:

```
pages:
    - foos: 
        - foos/foo1.md
        - foos/foo2.md
        - foos/foo3.md
        - ...
```

I'd prefer to point to the directory:

```
pages:
    - foos: foos/ 
```

This would save from hardcoding addresses for every file that is added to a directory.

I've seen [this issue](https://github.com/mkdocs/mkdocs/issues/46), but the link to the closing response no longer works.

**Comment by waylan** [comment]
CUrrently you have two options:

1. Do not define any `pages` and MkDocs will walk the `docs_dir` and autopopulate your nav with all files found.
2. Define every individual file in the `pages` config. Only listed files will be included in the output.

There are various requests for alternate behaviors. Many of these requests will be made possible by the [Pages Refactor][1]. I thought this request has been made before, but I can't find it so I've added it to the project. However, I'm not sure if this will actually get implemented (this the `Needs design decision` label.

Note that the structure of the pages config is not tied to the directory structure. You can have a multi-level directory structure with a flat nav or a flat directory structure with a flat nav. Therefore, there is no obvious solution that works across all projects.

[1]: https://github.com/mkdocs/mkdocs/projects/2

**Comment by pylang** [comment]
Thank you.  I was unaware of the first option (automatically walking the directory by omitting `pages`).  This works well enough.  The remaining value this request has is the ability to customize the order and naming of tabs/pages.

**Comment by waylan** [comment]
I've just punted this to the Post 1.0 milestone. It would be an add-on so it could be done at any time in the future without changing the existing behavior. We have more than enough for 1.0 as it is and we're just not going to get to this.
