### ISSUE TITLE
uninstallation of project

### ISSUE THREAD

**Issue by chris4real** [mkdocs/mkdocs#1436]
An mkdocs project i created refused to delete, how do i go about that

**Comment by waylan** [comment]
What do you mean by "refused to delete.”  What method did you use? Did you get an error message? If so, what was the message? What system are you on?

And just to be clear, am I understanding you correctly that you are attempting to delete some documentation, not the MkDocs Library?

**Comment by chris4real** [comment]
yeah an mkdocs project i created

**Comment by waylan** [comment]
Thanks for the clarification, but you should be able to simply delete the files in any manor which your OS provides. Therefore, my questions:

> What do you mean by "refused to delete.” What method did you use? Did you get an error message? If so, what was the message? What system are you on?

Please provide an answer to **all** of those questions.

**Comment by waylan** [comment]
Lacking enough information to determine the problem, this issue is being closed.
