### ISSUE TITLE
Update FontAwesome in themes

### ISSUE THREAD

**Issue by waylan** [mkdocs/mkdocs#1438]
FontAwesome should be updated to latest for the 1.0 release. 

See #1435 for at least one icon (GitLab) missing from the currently included version.

**Comment by coliff** [comment]
I could take care of this with a PR... should we update to v4.7.0 (webfont) which includes GitLab (https://fontawesome.com/v4.7.0/icon/gitlab/).

Alternatively we could update to Font Awesome v5, but this means changing many of the icons code (for example `fa fa-gitlab` becomes `fab fa-gitlab`). v5 is a heavier download as it's a 665 KB (281 KB gzipped) JS file. (https://use.fontawesome.com/releases/v5.0.8/js/all.js).

**Comment by waylan** [comment]
PRs are always welcome. And if we are going to update with breaking changes, the 1.0 release is the time to do it, not after.
