### ISSUE TITLE
Global template variables?

### ISSUE THREAD

**Issue by heathermiller** [mkdocs/mkdocs#144]
This is more of a question (and potentially a feature request if this isn't supported) than an issue – is there some way to declare global variables?

For example, in my config.yml, I'd like to define some global variable, `version-num` that, of course, represents the current version of the library that I'm documenting. I'd naturally like to use this all over in my documentation and have only one place to update the version number when releasing a new version – in config.yml.

Though I've tried to do this and beyond the pre-defined variables in the mkdocs documentation, nothing that I declare seems to be picked up.

Is there some way to do this that I don't see?

PS, Jekyll allows for this, so I'm basically assuming the same semantics as Jekyll, i.e., that user-defined variables in config.yml are globally accessible

**Comment by waylan** [comment]
Reading through this PR, it occurs to me that the original feature request assumes that the user can define any custom settings (including settings that mkdocs knows nothing about) and that those should then be available in the template. However, the work in #496 makes that impossible as only "known" settings will validate. Creating an "unknown" setting would result in an error. In that case, a custom setting which contains a dict of user defined keys and values makes sense. Something like `custom`, `extra`, or `user_defined` seems logical (I like `extra`). Then, that setting can be passed to the template regardless of whether all of the config is.

I suppose the real question is: Is this issue about the custom user-defined settings or all settings being available in the template. If it is the former, then that should be an easy addition to #496 and the rest can be punted for later consideration. However, if it is the later, a final decision needs to be made first.

For the record,  I don't understand the aversion to having all of the config available to the templates. For Markdown files, I agree that not everything should be available (if #304 ever gets implemented), but whats the big deal for templates?

**Comment by d0ugal** [comment]
@waylan 

> For the record,  I don't understand the aversion to having all of the config available to the templates. For Markdown files, I agree that not everything should be available (if #304 ever gets implemented), but whats the big deal for templates?

I'm not sure anyone is against it really, just trying to make the most sensible choice. I think it would make sense to pass the full config.

I'd like to look at this after I finish the work in #496. I think my plan will be to make the full config available as `{{ config.setting_name }}` to templates. Then use `extra` to have a dictionary of whatever the user wants. Then it could be accessed with `{{ config.extra.my_custom_thing }}`.

Over time I'd like to remove the [duplication with settings](https://github.com/mkdocs/mkdocs/pull/503/files#diff-cbfacbafa3042a0b35cee6270e6ca67aR130) in the template context, and have them all accessible via `{{ config }}` - that would probably be a switch for a `1.0` release.

**Comment by tomchristie** [comment]
**Wrote this before I saw @d0ugal's fix, but posting it for clarity all the same. The fix in #510 handles all this properly, similar to the second of the options presented below.**

> For the record, I don't understand the aversion to having all of the config available to the templates. 

There's two acceptable options here...

* Have the entire config available, and namespaced under `{{ config.<setting> }}`.
* Have a config key for user defined / theme specific settings `{{ config.context.<setting> }}`.

The first is nice and simple.
The second has the advantage that it's explicit which of the config variables are built in MkDocs settings, and which are just extra template context, but don't have any behavior affect in the code.

**Comment by d0ugal** [comment]
@tomchristie Just for clarity, [the change](https://github.com/mkdocs/mkdocs/blob/5b03b54f91f0330f7bf2f26eab47201252736ad7/mkdocs/build.py#L95) I made means that `{{ context.<setting> }} ` is the current way to access user defined globals. Although, I went for `extra` in the end. So it is `{{ extra.<setting> }}`.

I have been thinking about this further and I think this actually makes more sense: `{{ config.extra.<setting> }}` as it is still part of the config after all. Then users can access anything in the config and I we can remove a [bunch of code duplication](https://github.com/mkdocs/mkdocs/blob/5b03b54f91f0330f7bf2f26eab47201252736ad7/mkdocs/build.py#L66-L77) and [documentation duplication](https://github.com/mkdocs/mkdocs/blob/5b03b54f91f0330f7bf2f26eab47201252736ad7/docs/user-guide/styling-your-docs.md#global-context).

**Comment by tomchristie** [comment]
@d0ugal Yes, perfect. We may even want to move some non-behavioral stuff such as `copyright` and `google_analytics` into the `extra` block. It'll help the maintainance of the project if we can reduce the number of valid settings keys - less moving parts then, and the context stuff all nicely separated out.

**Comment by d0ugal** [comment]
@tomchristie Yup, I would like to move those too.

I'm not sure how to do the transition, it might be that we can duplicate `google_analytics` etc. to the old names with some sort of lazy-property-function that logs a warning if it is accessed. Just removing them wouldn't be great, as Jinja2 wont even complain, unless you try to access a property on that object (which you typically wouldn't for `google_analytics` or `copyright`).

**Comment by tomchristie** [comment]
Could we have a transition period where the config loading checks explicitly for them, raises a warning if they exist, and duplicates them into extra if so?

**Comment by d0ugal** [comment]
Oh, of course, that makes sense. None of these have useful defaults so they will always be in the config if they are used. Much easier.

**Comment by d0ugal** [comment]
This is done, moving the discussion about deprecating/moving other config options to #551
