### ISSUE TITLE
update packaging dependencies?

### ISSUE THREAD

**Issue by brainwane** [mkdocs/mkdocs#1440]
Hi! I'm a [Twine](https://twine.readthedocs.io) maintainer; thanks for using Twine. I noticed you've pinned some old versions of Twine and other packaging dependencies in `requirements/packaging.txt`. Twine [has changes in 1.11.0](https://twine.readthedocs.io/en/latest/changelog.html) that you might find useful, and I hope you'll upgrade. If you have any trouble upgrading, please do [let us know](https://github.com/pypa/twine/issues).

**Comment by waylan** [comment]
Nice update. Thanks for the heads up.

I noticed we have a very specific version of twine listed recently and thought that was strange. Not sure if there was a specific reason for that or not.

**Comment by pawamoy** [comment]
We don't use Twine anymore, as new releases are build and published to PyPI from GitHub Actions, using the official `pypa/gh-action-pypi-publish` action, see https://github.com/mkdocs/mkdocs/blob/master/.github/workflows/deploy-release.yml :slightly_smiling_face:
