### ISSUE TITLE
Recently changed plugin

### ISSUE THREAD

**Issue by cpoetter** [mkdocs/mkdocs#1444]
Hi everyone, 

I am completely new to *mkdocs* and I love it! I was playing around with it over the weekend, and I could achieve basically everything I wanted besides one thing:

Is there a plugin that creates a "recently changed" page or section? The docs are very likely located in a git repository, so it could be possible to find out which pages changed, am I right?

I tried to search for something like this for quite a while, but I could not find anything.  Does anybody know such a plugin?

Best, 
Chris

**Comment by waylan** [comment]
The Plugin API was only introduced in version 0.17 (October 2017). Currently, I am not aware of any plugins except the included `search` plugin.

**Comment by waylan** [comment]
As this is a candidate for a third party plugin, I am closing this. See also #1474.
