### ISSUE TITLE
Editorconfig

### ISSUE THREAD

**Issue by coliff** [mkdocs/mkdocs#1449]
It'd be good to add a `.editorconfig` file so that anyone contributing to MkDocs can follow the same rules for tabs/spaces, newlines, charsets etc.
Editorconfig (http://editorconfig.org/) is very popular and it's become standard for open-source projects to include one.
I would imagine it should be something like this:
```
# editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 4
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
```
Shall I open a PR?

**Comment by waylan** [comment]
Personally, I'm indifferent. But if it helps contributors and your willing to do the work, I'd be willing to accept it.
