### ISSUE TITLE
Keyboard shortcut to start search

### ISSUE THREAD

**Issue by ptbrowne** [mkdocs/mkdocs#1456]
In my project I added a tiny bit of JS to allow "/" to be used to focus the search bar. 

https://github.com/cozy/cozy-docs-v3/pull/53/files

If OK I could try to make a PR for this feature ?

**Comment by waylan** [comment]
We already have [multiple][1] keyboard shortcuts, including one for search`. Use `?` for help to get a list of supported shortcuts.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/js/base.js#L30-L57
