### ISSUE TITLE
Internal linking not working

### ISSUE THREAD

**Issue by Bootta11** [mkdocs/mkdocs#1457]
Hi,

I trying to link my document in docs folder(named my_document_nema.md) by:

`[custom_link_name](my_document_nema.md)`

markdown syntax but it now work. I got only 404 error.

**Comment by waylan** [comment]
Are the two documents (source and target) in the same directory? If not, you need to provide a relative link to the target from the source document. Perhaps you could provide your file structure.

**Comment by waylan** [comment]
> Can i add page to pages in config so it is not displayed in nav?

No, not at this time. In fact, that is the subject of #699.
