### ISSUE TITLE
Please support tornado-5

### ISSUE THREAD

**Issue by yurivict** [mkdocs/mkdocs#1458]
```tornado-5.0.1``` is the latest version: https://pypi.python.org/pypi/tornado
You require ```tornado>=4.1,<5.0```.
Your dependency ```livereload``` depends on the default ```tornado-5```.
```tornado-4``` and ```tornado-5``` are incompatible and conflict with each other.

**Comment by froschdesign** [comment]
Already in master:
https://github.com/mkdocs/mkdocs/blob/d4c5832876accc7e59293852d86810585b97674c/setup.py#L64

See also #1453

**Comment by yurivict** [comment]
Thanks!

**Comment by waylan** [comment]
> Your dependency `livereload` depends on the default `tornado-5`.

Hmm, that is new. Last I checked `livereload` hadn't been updated yet. Thanks for the heads-up.

As stated in #1427:

> Currently the only version of MkDocs which contains the `<5.0` dependency requirement is `0.17.3` and the only difference between `0.17.3` and `0.17.2` is that dependency requirement (no code changes were made). In your situation I would suggest using MkDocs `0.17.2`.
