### ISSUE TITLE
`theme_dir` or `custom_dir`?

### ISSUE THREAD

**Issue by charlesreid1** [mkdocs/mkdocs#1464]
On the [Custom Themes](http://www.mkdocs.org/user-guide/custom-themes/) page, it states:

> The bare minimum required for a custom theme is a main.html Jinja2 template file. 
> This should be placed in a directory which will be the theme_dir and it should be 
> created next to the mkdocs.yml configuration file. 

So, `theme_dir` should contain the `main.html` file.

> Within mkdocs.yml, specify the theme custom_dir option and set it to the name 
> of the directory containing main.html.

So, `custom_dir` should contain the `main.html` file? This information is unclear. (Edit: after interpreting the note below, I think this means you should be using _either_ `theme_dir` _or_ `custom_dir`.)

> Generally, when building your own custom theme, the theme name 
> configuration setting would be set to null.

<s>Okay, but where is the theme name set? Probably in the theme configuration file, but theme configuration files are not linked to or mentioned on that page. But then, the [mkdocs theme YAML file](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/mkdocs_theme.yml) does not specify a name either. So perhaps the name comes from the directory name? Unclear.</s> (this is more clear after some discussion in #1452)

> However, if used in combination with the custom_dir configuration value a
> custom theme can be used to replace only specific parts of a built-in theme. 
> For example, with the above layout and if you set name: "mkdocs" then the 
> main.html file in the custom_dir would replace that in the theme but otherwise 
> the mkdocs theme would remain the same. 

This block of text is difficult to comprehend, but it describes _key_ behavior. Why is it in a _note_?

**Comment by waylan** [comment]
`theme_dir` is an old, deprecated setting which was replaced by the nested `custom_dir`. If you find any mention of `theme_dir` in the existing docs, then is should be updated to `theme.custom_dir`. The theme related code went through a pretty significant refactor over the last few releases. Apparently a few remnants still exist from old theme stuff.

> This block of text is difficult to comprehend, but it describes key behavior. Why is it in a note?

That content is in a note because it is in a section about building custom themes, not in a section about customizing existing themes. The section about customizing existing themes describes the same behavior in more detail. A link to that section can be found at the end of the note.

**Comment by charlesreid1** [comment]
Sure. The language could definitely be more clear - building a customized theme vs customizing an existing theme. Since the pages all focus on the word "customize" this is further adding to confusion.

Maybe just say "Build a Theme" instead of "Custom Theme", or refer to "Modified Themes" instead of "Customized Existing Themes".

**Comment by waylan** [comment]
Those are valid points. Unfortunately, the existing pages have existed for some time and have a lot of external links pointing to them. As the theme stuff has gradually morphed over time, we have been trying to keep the links intact. But if its confusing new users, then perhaps we need to do a docs refactor for the upcoming 1.0.
