### ISSUE TITLE
Source tags rendering incorrectly.

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#1471]
Refs: https://github.com/encode/django-rest-framework/issues/5945

Building against 0.17.3

![image](https://user-images.githubusercontent.com/647359/39004342-0271c10c-43f5-11e8-88dd-6ada66c17e76.png)

Building against 0.16.3

![image](https://user-images.githubusercontent.com/647359/39004374-1245a120-43f5-11e8-8137-9cbac7236504.png)

Presumably they're incorrectly being treated as a list even in the single-tag case.

**Comment by waylan** [comment]
This appears to be related to your [custom theme][1] and a change in how MkDocs handles Markdown meta-data. Markdown's default is to return raw meta-data such that each value is a list of lines (most of which contain one item). As this doesn't really make sense for MkDocs, in 0.17 MkDocs now joins those items into a string.

However, in your template, you are still treating the value of `page.meta.source` as a list, iterating over it, and creating a link for each item. Of course, this is creating a separate link for each character in the string. Instead, your template should just create a single link without iteration.

I'm assuming a page would only ever have a single "source" to link to, so the loss of ability to define a list shouldn't be a problem here. The change was made with the understanding that the feature was completely undocumented and mostly unused. @tomchristie I suspect you are the only one who has ever made use of it. The only officially supported meta-data key is `template`, which MkDocs was already joining into a single string. But even that was completely undocumented until after the change.

[1]: https://github.com/encode/django-rest-framework/blob/master/docs_theme/main.html#L116

**Comment by tomchristie** [comment]
> I suspect you are the only one who has ever made use of it.

This is very possibly true. 😝

**Comment by tomchristie** [comment]
> I'm assuming a page would only ever have a single "source" to link to, so the loss of ability to define a list shouldn't be a problem here.

That’s not quite the case for us, no. Occasionally a single docs page will refer to more than one module.

**Comment by waylan** [comment]
> Occasionally a single docs page will refer to more than one module.

I'm not quite sure of the best way to support this. The [underlying library][1] offers a way to define a "type" for a given key which would convert the raw data to that "type". However, that is not exposed to the MkDocs user.

Truth be told, I would like to switch to using YAML for the meta-data. Of course, YAML has type-support builtin and users already are using YAML for the config file. The problem is that Markdown systems which use YAML traditionally require a YAML deliminator (line of `---`) to separate the data from the Markdown text. Therefore, it's not a straightforward switch. Users would need to edit their docs to conform to the new format. And a list would be defined differently as well, requiring an additional edit by users.

[1]: https://github.com/waylan/docdata

**Comment by mitya57** [comment]
> However, in your template, you are still treating the value of page.meta.source as a list, iterating over it, and creating a link for each item. Of course, this is creating a separate link for each character in the string. Instead, your template should just create a single link without iteration.

I have just stumbled upon this. But the mkdocs’ documentation suggests that `page.meta.source` is a list, while it actually isn’t. Quoting the example from [the documentation](https://www.mkdocs.org/user-guide/custom-themes/#pagemeta):

```django
{% for filename in page.meta.source %}
  <a class="github" href="https://github.com/.../{{ filename }}">
    <span class="label label-info">{{ filename }}</span>
  </a>
{% endfor %}
```

Maybe that example should be fixed to replace the `{% for %}` loop with `{% if page.meta.source %}`?

Ah, and also the default theme is [doing the same](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/content.html). I tried adding a `source:` line to a file in mkdocs’ own documentation, and it is rendered as a set of single letters.

**Comment by waylan** [comment]
Good catch. I wasn't aware we were expecting lists anywhere internally.

Probably the correct change to the documentation is to update the meta-data in the sample document to use YAML style meta-data. Then the existing template would be correct. Note that the existing behavior of Meta-Data is correctly documented under [writing your docs][1] (YAML style retains types, including lists, while MultiMarkdown style returns a single string for each key).

It might also make sense to have the templates check the type of `page.meta.source` and act accordingly.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data

**Comment by pawamoy** [comment]
So it seems like it's a limitation of MultiMarkdown which doesn't support list of strings? Do we know how widely used MultiMarkdown is? Should we deprecate it in favor of the probably more robust and common YAML front-matter metadata? @tomchristie I'd suggest we close this as out of scope. Are you still interested in this?

**Comment by tomchristie** [comment]
> Are you still interested in this?

Let's close this as stale.
