### ISSUE TITLE
edit_uri misbehaving when using Read the Docs with mkdocs as rendering engine

### ISSUE THREAD

**Issue by mauroservienti** [mkdocs/mkdocs#1472]
I'm trying to setup documentation for our OSS project using Read The Docs, that is much much faster compared to what we're using now. We need to have the `Edit on GitHub` button on every page linking directly to the markdown file in our documentation repo.

I've configured our [`mkdocs.yml`](https://github.com/RadicalFx/documentation/blob/read-the-docs/mkdocs.yml) following the documentation. However regardless of whatever configuration I use it seems that the `edit_uri` setting is always ignored, and the [rendered documentation](http://radical-documentation.readthedocs.io/en/read-the-docs/) `Edit on GitHub` button links to the repo and not to the markdown document.

I'm not sure if this is the right place to raise such an issue, or the Read the Docs repo or even the [Sphinx Read the Docs repo](https://github.com/rtfd/sphinx_rtd_theme).

It seems to me that the problem lies here: https://github.com/rtfd/sphinx_rtd_theme/blob/7cd846b4fdd0e971f2c409ad9a2af24070b7b111/sphinx_rtd_theme/breadcrumbs.html#L40-L46

In which case it's a template issue. Unfortunately I have no idea how the engine works. Looking at the linked code above it seems that the logic is:

* if there is a `github_url` defined directly use that
* otherwise build one (this is what I expect to happen)

The problem with the above code lies in the `display_github` variable that is true only if `github_url` is defined, in with case it means that the if/else will always evaluate to true rendering only the `github_url`, without the full path to the document.

**Comment by waylan** [comment]
Is this problem occurring on local builds or on the site hosted on the RTD service?

Last I knew, the RTD service still used MkDocs version 0.14 and any changes we make are not percolating downstream. If this issue is related to the service, then I suggest you open an issue there. Of course, it is possible that the service has recently updated (I haven't checked in the last few months), in which case that's not a factor.

If you are building locally and having the issue, then that is something we need to fix. However, IIRC, the readthedocs theme includes two links to GitHub on each page. One is the edit link and the other is simply a link to the GitHub project. Are you sure you are looking at the correct link?

**Comment by mauroservienti** [comment]
@waylan thanks for the response. We’re using the hosted version, I’ll reach out to them.
If you take a look at the rendered version there is only one link http://radical-documentation.readthedocs.io/en/read-the-docs/

Here is the configuration we’re using https://github.com/RadicalFx/documentation/blob/read-the-docs/mkdocs.yml

Once I opened an issue in the RtD repo, I’ll link this one. Thanks again.

**Comment by waylan** [comment]
I just checked the latest in master and everything is working fine. Note that there are two GitHub links: (1) A link to the GitHub project page located at the bottom of the sidebar and (2) an "edit on GitHub" link at the top right of the page. The first link is not an "edit" link and is not intended to be whereas the second is an "edit" link and works correctly. 

![screen shot 2018-04-20 at 8 19 09 pm](https://user-images.githubusercontent.com/78846/39078709-476e61b6-44db-11e8-8130-74fa17f6e0fe.png)

This mimics the same behavior from Read The Docs default Sphinx theme as seen in their [own documentation][1].

![screen shot 2018-04-20 at 8 18 56 pm](https://user-images.githubusercontent.com/78846/39078716-5c0bab38-44db-11e8-9ace-fe6b4eca7d78.png)

[1]: https://docs.readthedocs.io/en/latest/getting_started.html

**Comment by mauroservienti** [comment]
Thanks, I’ll raise an issue with them. BTW read the docs doesn’t use MkDocs engine.

**Comment by waylan** [comment]
> BTW read the docs doesn’t use MkDocs engine.

Yes, I know. They use Sphinx. Our `readthedocs` theme is a clone of the Sphinx theme of the same name. I was simply demonstrating that our behavior matches the upstream theme. So there is nothing we need to change in regard to this issue.
