### ISSUE TITLE
[Feature request] Add automatic history to markdown based on git commits

### ISSUE THREAD

**Issue by oliviernguyenquoc** [mkdocs/mkdocs#1474]
It would be nice to track the history of each markdown/doc page (who have done a modification, when and what kind of update).

It could be based on commits (author, commit date and commit message)

Exemple:
-------------------------------------------------------
|     Author     |      When     |  Message|
| ------------- |:-------------:| -----:|
|    woman_1  | 12/03/2018 | Add features section |
|      man_1     | 10/03/2017 | Document creation   |
-------------------------------------------------------

Very linked with issue:
#1408 [Feature request] Add Created and Updated datetime on all page

**Comment by waylan** [comment]
As with #1406, this would be a great candidate for a third party Plugin.

**Comment by oliviernguyenquoc** [comment]
Ok I will see if I have some time to do it. 

If anyone see an existing third party plugin, please let me know.

May I close the issue ?

**Comment by waylan** [comment]
As this is a candidate for a third party plugin, I am closing this.

**Comment by Ir1d** [comment]
@oliviernguyenquoc hi i'm also interested in this, have you implemented this?

**Comment by oliviernguyenquoc** [comment]
@Ir1d No didn't have time for it

**Comment by pawelsikora** [comment]
@oliviernguyenquoc @Ir1d did you found the solution? I was also looking for such functionality but without success, so I wrote something that satisfies me at least:

![Screenshot from 2020-10-18 09-05-54](https://user-images.githubusercontent.com/6966193/96361211-2ad48e00-1124-11eb-9d5d-db74db881c20.png)

it will change the ' {{ git_blame_history }}' wherever you put it in your markdown file and check the git history for this file up to N number of commits.

Still thinking about the proper name and to improving it a bit. But if it will make sense, then I will publish it as a third-party plugin.
