### ISSUE TITLE
Is there a way to recover my local files from my published docs?

### ISSUE THREAD

**Issue by JoabMendes** [mkdocs/mkdocs#1475]
I did a `git hard reset` in my docs repository and lost some big changes I wrote. Luckily all those changes where already published/uploaded. I would like to know if there's a way to download the published content so I could recover everything I did.

**Comment by waylan** [comment]
MkDocs is a Markdown to HTML tool and that's it. We don't do HTML to Markdown. Sorry.

Are you sure you can't recover the work? Perhaps from a remote? I'd make sure I exhausted all options here first. Of course, you should get help on that elsewhere.

If you really need to recover the text from the rendered HTML, then I would suggest an HTML to Markdown tool such as Pandoc. You should be able to get something that works with a quick search online. Note that while Pandoc does a pretty good job with Markdown, if you have been using any unique Markdown extensions, it may stumble over those. Pandoc will give you the text, but some of the formatting may need to be fixed.

**Comment by JoabMendes** [comment]
The person who has been writing the documentation didn't commit her work for a while and she was only publishing it. For this reason there's no remote to recover from 😢. As she did a git hard reset to fix some stuff, all staged work was lost. The only way I thought I could recover it was getting the content from the published pages. My plan now is to check if there's a way to revert a git reset hahah. Thanks for answering, @waylan!
