### ISSUE TITLE
How to Build html of internal pages separately with style files and all related linked files

### ISSUE THREAD

**Issue by UsmanMaqbool** [mkdocs/mkdocs#1477]
I want to build pages separately with all javascript and CSS files.

**Comment by waylan** [comment]
I'm not sure what you mean. Can you provide more information?

**Comment by UsmanMaqbool** [comment]
Thanks for your kind reply, actually i have couples of markdown files in my mkdocs workspace, (sections), i want to build each section separatly

**Comment by waylan** [comment]
Then you should create separate MkDocs projects with separate config files and build each as a separate project. MkDocs is designed specifically to support the built docs being served from any arbitrary location. The MkDocs root does not need to be the server root.

**Comment by waylan** [comment]
As there appears to be no actionable item here, I'm closing this.
