### ISSUE TITLE
Potential security vulnerability in hapijs / hoek

### ISSUE THREAD

**Issue by jtalati** [mkdocs/mkdocs#1480]
We are receiving the following vulnerability message:

![image](https://user-images.githubusercontent.com/24463592/39596168-8f03d160-4edf-11e8-969c-8d41de46b572.png)

Our mkdocs version is the latest(Version 0.17.3) 

if anyone can guide us or have been through this issue before it would be good help. 

This would be a good way for future users who face this issue to interact and find a possible solution for any security vulnerabilities.

**Comment by jtalati** [comment]
@waylan we are using custom javascript in our project.

**Comment by waylan** [comment]
I asked three questions, but you only answered the first. I need more information to act on this. Is your custom JavaScript making use of the offending library? Are you using a third party theme which is using the offending library? If so, then the matter is out of my hands. But until I can reproduce the problem, I have no way of knowing.

**Comment by waylan** [comment]
What tool is reporting the problem? If I knew that, at the very least I could check if the tool reports the same issue in a default MkDocs build with the included themes.

**Comment by waylan** [comment]
Closing this due to a lack of useful information. I'm assuming this is related to a third party theme as neither of the included themes make use of the named library.
