### ISSUE TITLE
Server not refreshing for symlink

### ISSUE THREAD

**Issue by chaonan99** [mkdocs/mkdocs#1483]
Hi,

Great thanks for your work!

I'm using mkdocs as a document server to share documents all around the computer with co-workers. Basically I would create a symlink to some markdown files inside `docs`. I found that saving the linked file won't trigger the refresh. Is there a way to get it auto-refreshed when the linked file is updated?

**Comment by waylan** [comment]
Presumably, as the actual file is updated, but not the link, the file watcher won't detect any changes. I'm not aware, but do file watchers even support such a feature (watching the file a link points to)?

The [on_serve][1] event of the Plugin API would allow you to add additional locations to watch for changes, but writing a custom plugin does seem a little extreme just to watch linked files. Unfortunately at this time that is the only option. However, I suspect the next release (1.0) will offer some more flexibility that a general purpose plugin would be able to address.

[1]: http://www.mkdocs.org/user-guide/plugins/#on_serve

**Comment by waylan** [comment]
As this appears to be a limitation of the watcher (failing to detect changes to the target of a symlink), this is an upstream issue. Therefore, I am closing this.
