### ISSUE TITLE
Add option for disabling auto linking of urls and e-mail addressses globally

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [mkdocs/mkdocs#1485]
I am writing a documentation for a mail server and therefore mention a lot of e-mail addresses. It does not make sense that they get automatically linked with `<a>` and `mailto:` because I am not talking about real e-mail addresses.

I found some hacks like adding a `<span>` but this is just ugly.

It would be nice to have a global setting to disable auto linking of e-mail addresses and/or urls. This would be the preferred solution for me, because I mention e-mail addresses several hundred times but would use an actual link to an e-mail address maybe once or twice.  So 99,9% of e-mail address uses would not require any modification like adding a `<do-no-highlight>` tag.

**Comment by waylan** [comment]
Standard Markdown does not auto-link email addresses and links unless they are [wrapped in angle brackets][1] (like this: `<address@example.com>`). [Python-Markdown][5] (the library MkDocs uses) follows the same pattern. Therefore, you should be able to simply include your email addresses as plain text and they will be ignored. Some would argue that all email addresses and links (which are not to link to anything) should be wrapped in code spans, which also causes them to not be converted to links.

If neither of those solutions meet your needs, then you can always [create a Python-Markdown extension][2] which modifies the Markdown parser in whatever way you desire. In any event, as MkDocs [fully supports][3] Python-Markdown extensions, there is no need to make any changes to MkDocs.

Finally, note that if there is any errors with how Python-Markdown parses/converts your markdown documents, then that should be [reported][4] upstream to the Python-Markdown project.

[1]: https://daringfireball.net/projects/markdown/syntax#autolink
[2]: https://github.com/Python-Markdown/markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown
[3]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
[4]:  https://github.com/Python-Markdown/markdown/issues
[5]: https://python-markdown.github.io/

**Comment by PanCakeConnaisseur** [comment]
My mistake. I completely overlooked that I had `- pymdownx.magiclink` in my mkdocs.yml.

**Comment by facelessuser** [comment]
@PanCakeConnaisseur, if it is a problem (that email addresses are specifically linked) an option can be added to turn it off. You can create an issue.

I personally use [EscapeAll](https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/) and just escape the `@` like this when I want it to not auto-link: `mail\@mail.com`.
