### ISSUE TITLE
Specify additional files to include when publishing to gh-pages

### ISSUE THREAD

**Issue by robfletcher** [mkdocs/mkdocs#1488]
In the root of my repository I have `.circleci/config.yml` which configures the way CircleCI builds my project. The configuration in that file tells CircleCI to ignore the `gh-pages` branch.

Unfortunately in order for that to work the `.circleci` directory has to _exist_ on the `gh-pages` branch (CircleCI reads the config from whatever branch it clones) and MkDocs deletes it when I run `mkdocs gh-deploy`.

I tried symlinking and copying the `.circleci` directory into the `docs` directory, but MkDocs ignores anything in there starting with `.`. I've tried including the file in `extra_templates` but that blows up as MkDocs tries to process the file. I've also tried `extra_css` and `extra_javascript` but when running `mkdocs build` there was no sign of a `.circleci` directory in the site that was built.

Is there any way I can configure MkDocs to include this sub-directory? If not, consider this a feature request!

**Comment by waylan** [comment]
MkDocs will copy any unknown file in the docs_dir to the site_dir with the one exception that it ignores all dot files (and directories). For any other file you would have had to do nothing (for example a CNAME file gets copied correctly although MkDocs knows nothing about it). Obviously we don't want to completely remove our block of dot files, so the question is: how do you tell MkDocs to not ignore your specific dot file? 

This seems a little too special edge case to include a global config setting for. However, a [Plugin][1] would be an easy way to get around this. It would not be difficult to set up a plugin to copy a list of given files/dirs to the site_dir during a build. In the Plugin config the user would just define the list of files not to ignore. It would make for a useful general purpose plugin, I expect.

[1]: http://www.mkdocs.org/user-guide/plugins/

**Comment by robfletcher** [comment]
@waylan ok, that sounds like something I could try to contribute.

Yep, my `CNAME` file works fine.

**Comment by waylan** [comment]
As this would be addressable via a plugin, I am closing this. See also the refactor in #1504 which should make this even easier.

**Comment by sebastian-garn** [comment]
I ran into the same issue. An easy fix for this is to add a commit message to the mkdocs gh-deploy containing the string "[ci skip]" as CircleCi will skip any of these builds. For example: `mkdocs gh-deploy -m "[ci skip]"`

**Comment by caljess599** [comment]
I have used an existing plugin to solve this: https://github.com/oprypin/mkdocs-gen-files

This plugin allows you to edit/add files during the build process, which means any modifications will persist into the content that is pushed to the `gh-pages` branch, thus allowing circleci to see it. (As the circleci config it is not a markdown file, it will not render to the site contents.)

Simply using this plugin to copy your existing circleci config — assuming that no workflow it contains will be triggered on the `gh-pages` branch — is sufficient for circleci to report 'no worfklow', which is the state we desire. 

Here's the steps to implement:

1. in `requirements.txt` (assuming this is how you're satisfying the python install), add the plugin, e.g., 
`mkdocs-gen-files==0.3.3`
2.  in `mkdocs.yml` add the plugin
```
plugins:
- gen-files:
    scripts:
      - add_circle_config.py
```
3. to the root of the repo, create the file `add_circle_config.py` with these contents:
```
import mkdocs_gen_files

with open(".circleci/config.yml", "r") as f:
  data = f.readlines()

with mkdocs_gen_files.open(".circleci/config.yml", "w") as f:
  f.writelines(data)
```

For extra reference, here is our workflow (simplified; I removed the notifications steps) that only runs when the pipeline branch is main (master):
```
---
version: 2.1

workflows:
  deploy-main:
    when:
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
    - update-mkdocs-site:

jobs:
  update-mkdocs-site:
    docker:
    - image: 'cimg/python:3.10'
    steps:
    - checkout
    - run:
        name: Install requirements
        command: pip install -r requirements.txt
    - run:
        name: Build mkdocs site
        command: |
          mkdir _site && mkdocs gh-deploy
