### ISSUE TITLE
How to implement a plugin without defining an entry point?

### ISSUE THREAD

**Issue by akhmerov** [mkdocs/mkdocs#1489]
I would like to implement a plugin that executes some of the code in the site source and substitutes the results. Because I do not expect this plugin to be reusable, I would like to just include it within my mkdocs site.

However, if I understand everything correctly, right now mkdocs will only recognize plugins that registered an entrypoint using setuptools. On the other hand it feels wrong to install something specific to a single project and to make it visible to the global namespace.

Is it possible to define a plugin without registering an entrypoint, or is it the only option?

**Comment by waylan** [comment]
Yes, plugins must use entry points. Their is no workaround and no plans to support any alternatives. If you are concerned about your plugin being in the global namespace then I would suggest a virtual environment.
