### ISSUE TITLE
test_doc_dir_in_site_dir fails when the checkout directory name is not ‘mkdocs’

### ISSUE THREAD

**Issue by mitya57** [mkdocs/mkdocs#1490]
If you clone this repository as `mkdocs`, then all the tests pass. However if you clone it with a different name, e.g. `mkdocs-0.17.3`, then one of the tests fails:
```
======================================================================
FAIL: test_doc_dir_in_site_dir (mkdocs.tests.config.config_tests.ConfigTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/mkdocs-0.17.3/mkdocs/tests/config/config_tests.py", line 264, in test_doc_dir_in_site_dir
    self.assertEqual(len(errors), 1)
AssertionError: 0 != 1
```

This happens because the test expects this error:
https://github.com/mkdocs/mkdocs/blob/7e06ca68d100d27c0323a59a13a9a692c2ee537f/mkdocs/config/config_options.py#L369-L373

for this line:
https://github.com/mkdocs/mkdocs/blob/7e06ca68d100d27c0323a59a13a9a692c2ee537f/mkdocs/tests/config/config_tests.py#L242

But this happens only when `../mkdocs` points back to the current directory.

Note: I run the tests using `python3 setup.py build; PYTHONPATH=. python3 -m nose`. This also affects the Debian package build.

**Comment by waylan** [comment]
PRs are welcome. Python already has a packaging systems that works fine. If anyone wants to distribute MkDocs through some other package system, then they can provide patches to make it work. Personally, I have more important things to spend my time on.

**Comment by mitya57** [comment]
OK, submitted a pull request.

Note that I did **not** say that the bug happens only with Debian’s build system. You can reproduce it with normal Python tools, you just need to name your current directory in a different way. This is what you get if you e.g. get the tarball from PyPI and unpack it.

**Comment by waylan** [comment]
Sorry if my tone was off above. And thanks for the PR. Much appreciated.
