### ISSUE TITLE
mkdocs gh-deploy: add flag to disable .nojekyll

### ISSUE THREAD

**Issue by lramage94** [mkdocs/mkdocs#1491]
-n, --no-jekyll       Include a .nojekyll file in the branch.

https://github.com/davisp/ghp-import#usage

**Comment by waylan** [comment]
I suppose we could add such a flag, but what useful purpose would it serve? the `gh-deploy` command only ever will be used with GitHub Pages. Therefore, it will never be used on a non-Jekyll host. In what scenario would you want to run Jekyll on an already rendered site? Perhaps if you were combining the MkDocs output with other output; but then the gh-deploy script wouldn't be used anyway. In other words, we don't foresee any use case were the option would be useful. Any edge case in which it might make sense it probably enough of an edge case that the user will need to provide their own script anyway. Or do you have a reasonable use-case in mind where it makes sense?
