### ISSUE TITLE
Feature idea: Allow to override docs_dir with commandline option

### ISSUE THREAD

**Issue by pixelbrackets** [mkdocs/mkdocs#1499]
The build command offers several options. One of them is `--site-dir` to override the setting `site_dir` in a `mkdocs.yml`.

Is it possible to add an option `--docs-dir` to override the setting `docs_dir` as well?

Use case: Use the same mkdocs.yml configuration file to repeatedly execute the `build` command on various different source directories.

    mkdocs build --config-file mkdocs.yml  --docs-dir /path/to/1/docs/ --site-dir /path/build/1/
    mkdocs build --config-file mkdocs.yml  --docs-dir /path/to/2/docs/ --site-dir /path/build/2/
    mkdocs build --config-file mkdocs.yml  --docs-dir /path/to/3/docs/ --site-dir /path/special/3
    …

**Comment by waylan** [comment]
This might have made (some) sense in the past, however, in #1376 , which will be available in the next release, we are changing the behavior so that all paths in the config file are relative to the config file. Therefore, the config file will be more specific to a given set of files and not likely to work with multiple different `docs_dir`s.

**Comment by waylan** [comment]
It occurs to me that a way to approach this might be to merge multiple partial config files. Over the years I have seen a few different use cases that could benefit from that sort of feature. For example, other projects which use Python config files can easily `import` one into another allowing all sorts of variations with the correct set of imports with no duplicity.  However, that is not something supported by YAML. While YAML does support a `merge`, that only applies to separate "sections" (separated by deliminators) in a single file. YAML provides no support for merging multiple files.

That said, we could potentially take the Python `dict` object from each YAML file and `merge` them. But how would the user specify which files to merge with which? And what if the user wants to merge a subsection of a setting, not the root setting object (for example, should two lists be merged or should one replace the other)? In the end if feels like we would be inventing a whole new mechanism on top of YAML, which I'd rather avoid.

**Comment by pixelbrackets** [comment]
> This might have made (some) sense in the past, however, in #1376 , which will be available in the next release, we are changing the behavior so that all paths in the config file are relative to the config file.

Oh. But should still be possible to use this feature on the command line

    mkdocs build --config-file /path/to/general/mkdocs.yml --docs-dir ../1/docs/ --site-dir ../../build/1/

> It occurs to me that a way to approach this might be to merge multiple partial config files. … But how would the user specify which files to merge with which?

Merging values and configure which values should prefered is hard. And way to much overhead for this feature here.

In my case a have one very simple `mkdocs.yml` file and a large number of documentation folders. All these documentation folders dont have a `mkdocs` file. Instead of copying the single file into all projects I could just use the very same file for all builds, if I have the opportunity to set *docs* and *site* dir (only site dir possible atm).

**Comment by flynneva** [comment]
Any updates on this feature request? I could also use this feature as well.

**Comment by oprypin** [comment]
FWIW this is always possible:

```bash
echo '{INHERIT: mkdocs.yml, docs_dir: docs2}' >mkdocs2.yml; mkdocs build -f mkdocs2.yml
```

And the following is *almost* possible (these two examples are equivalent in Bash):

```bash
echo '{INHERIT: mkdocs.yml, docs_dir: docs2}' | mkdocs build -f -
```
```bash
mkdocs build -f - <<<"{INHERIT: mkdocs.yml, docs_dir: docs2}" 
```

But currently it fails, it works only if this line is removed:
https://github.com/mkdocs/mkdocs/blob/afb66c1bea3eb07a917803a25d5e536edd2b8084/mkdocs/config/base.py#L313

**Comment by oprypin** [comment]
Conceptually, a site is a config file along with its dedicated docs dir, and they are tightly connected. So again just conceptually, I think it doesn't make sense to provide a special option to rip them apart for special setups where another docs dir somehow happens to match up.

Note that overriding the docs dir is *not* similar to overriding the config file, because overriding the config file overrides everything, so, well, it isn't even an override.
