### ISSUE TITLE
blank line in .md file doesn't show in the .html file

### ISSUE THREAD

**Issue by yalunren** [mkdocs/mkdocs#1501]
Hi, MK team. First of all, great work! I tried many static site generator, Mkdocs is the best.

Here's my question. In the .md file, for formatting purpose, I leave a lot of blank lines. However, they are not show in the html file. Could you add </br> tag when it md gets translate into html?

Thanks!

**Comment by waylan** [comment]
If you are reporting a bug in the Markdown parser then you should report that upstream to [Python-Markdown/markdown][1]. And be sure to provide some sample input, the actual output and the output you expect. However, while I can't be certain from the info provide thus far, it appears that you are misunderstanding some basic concepts about how Markdown works. For example see [Create two blank lines in markdown][2].

[1]: https://github.com/Python-Markdown/markdown
[2]: https://stackoverflow.com/q/20543454/866026

**Comment by yalunren** [comment]
Got it. Thanks!
