### ISSUE TITLE
Latest published files display incorrectly on readthedocs

### ISSUE THREAD

**Issue by shyjaprabhu** [mkdocs/mkdocs#1507]
The output for the latest/last (published) build looks different. It may be because MKDocs version 0.17 is used when published to readthedocs. 

The previous build link is: https://snappydata-docs.readthedocs.io/en/docv1.0.1/
The latest build is: https://snappydata-docs.readthedocs.io/en/latest/

Can you please let me know how can this be corrected?

**Comment by waylan** [comment]
Without more information, I can only assume this is an issue with the readthedocs service. Therefore, I am closing this. I'll happily reconsider if more information is provided.

**Comment by shyjaprabhu** [comment]
Thank you for your suggestion. 
I had to make various changes to the configuration to make the templates work. Thank you for pointing me in the right direction. I do have it working now.
