### ISSUE TITLE
Double escaping of ampersand in URLs

### ISSUE THREAD

**Issue by letmaik** [mkdocs/mkdocs#1512]
```
[title](http://example.com/?a=1&amp;b=2)
```
results in:
```
http://example.com/?a=1&amp;amp;b=2
```
The expected behaviour is that `&amp;` is left as-is. A work-around is to use `[title](http://example.com/?a=1&b=2)`.

**Comment by waylan** [comment]
Markdown parsing is handled by the [Python-Markdown/markdown] project. Please report any issues with the parser upstream. 

[1]: https://github.com/Python-Markdown/markdown

**Comment by letmaik** [comment]
Thanks for the pointer, reported at https://github.com/Python-Markdown/markdown/issues/669.
