### ISSUE TITLE
[Question] RPM info with Mkdocs

### ISSUE THREAD

**Issue by fmunteanu** [mkdocs/mkdocs#1513]
I would like to generate HTML pages from local RPM files, similar to:
https://centos.pkgs.org/7/centos-extras-x86_64/cadvisor-0.4.1-0.3.git6906a8ce.el7.x86_64.rpm.html

Do you recommend a program/plugin which I could combine with Mkdocs? I would like to process each RPM in a directory and generate HTML pages for each file. Local command example to obtain the list of RPM provides:
```
rpm -qp --provides cadvisor-0.4.1-0.3.git6906a8ce.el7.x86_64.rpm | sort -u
```

**Comment by waylan** [comment]
MkDocs only processes Markdown files which use common Markdown file extensions. We have no interest in or intention to support anything else. If you would like to do anything else, you would need to create your own plugin. The plugin API is new and only a couple basic plugins exist. I would be surprised if you found any existing plugin which met your needs. While I suppose one could use the Plugin API to process non-Markdown markup, it was not designed for that and I expect the results to be less than satisfactory. It would be even more difficult to get a plugin to recognize, let alone process, files with alternate file extensions.
