### ISSUE TITLE
`docs_dir` not resolved relative to the config file directory.

### ISSUE THREAD

**Issue by arhoyling** [mkdocs/mkdocs#1515]
The mkdocs documentation says:

> docs_dir
>
> Lets you set the directory containing the documentation source markdown files. This can either be a relative directory, in which case **it is resolved relative to the directory containing your configuration file**, [...].

However, in practice, the `docs_dir` is resolved relative to the **working directory**. This means that when the directory of the configuration file is not the working directory, the option validation in `load_config()` fails with a `ConfigurationError`: 'Error: The path docs isn't an existing directory.'

We can fix this either by:

* modifying the documentation to be truthful.
* or by modifying `load_config()` to honour the documentation.

Although more involved, I think the second option is the more useful approach.
I can submit a PR if you think it is worth fixing.

**Comment by waylan** [comment]
This has been fixed in #1376 and will be available in the next release.
