### ISSUE TITLE
Release notes missing section for v0.17.4

### ISSUE THREAD

**Issue by edmorley** [mkdocs/mkdocs#1521]
Hi!

The newly release v0.17.4 isn't listed on:
https://www.mkdocs.org/about/release-notes/

**Comment by waylan** [comment]
The [release notes][1] in the 0.17 branch had been updated. It would appear that I didn't deploy the updated docs when I issued the release. I just did a deploy and the update should be available immediately (pending any caching issues). Thanks for the heads-up.

[1]: https://github.com/mkdocs/mkdocs/blob/0.17/docs/about/release-notes.md

**Comment by edmorley** [comment]
Many thanks :-)
