### ISSUE TITLE
Testing plugin.py without mkdocs

### ISSUE THREAD

**Issue by fralau** [mkdocs/mkdocs#1528]
I am trying to test a plugin directly (`python3 plugin.py`), before trying it with mkdocs, but the following error appears:

```
$ python3 plugin.py
Traceback (most recent call last):
  File "plugin.py", line 9, in <module>
    from mkdocs.plugins import BasePlugin
  File "/usr/local/lib/python3.6/site-packages/mkdocs/plugins.py", line 14, in <module>
    from mkdocs.config.base import Config
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/__init__.py", line 2, in <module>
    from mkdocs.config.defaults import DEFAULT_SCHEMA
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/defaults.py", line 119, in <module>
    ('plugins', config_options.Plugins(default=['search'])),
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/config_options.py", line 621, in __init__
    self.installed_plugins = plugins.get_plugins()
AttributeError: module 'mkdocs.plugins' has no attribute 'get_plugins'
```
This error does not occur when the plugin is executed in its normal context.

This is can be a hindrance, because a developer might want to do units tests before trying the plugin in the normal context. My solution was to externalise the "difficult" parts of the code in an external module that I tested separately, but that's not necessarily practical or the best solution. Is there some declaration or hack that would allow us to emulate normal context?

**Comment by waylan** [comment]
All of the `mkdocs` module (and all of its various internal parts) are one package. We never anticipated that one or more files would be removed from the package and used independently. Nor are we interested in supporting that use case. You get the entire `mkdocs` package or nothing. 

For example, the config for a plugin uses a separate instance of the same [`Config`][2] class that MkDocs uses.  In fact, most of the code that makes up the `BasePlugin` class deals with the config. Therefore, at a minimum, you need the `mkdocs.config` module to be able to create an instance of a plugin class. I suppose you could [mock][0] the `Config` class for your tests, but why not just use the `Config` class itself. After all, you will want to have tests which ensure that your custom config scheme properly validates your plugin's config settings. And for that you'll need to use the real `Config` class.

In Mkdocs' own tests, we [mock an entry point][1] to fake having our "dummy" test plugin installed. Notice that our `test_plugins.py` module only makes reference to the `mkdocs.config` module in addition to `mkdocs.plugins` (also `mkdocs.utils` for PY2-PY3 compatibility) . I expect that that is the minimum anyone would need. Although, I have to wonder how you would test the functionality of the events for your plugin. Events are intended to manipulate the various parts of MkDocs internals. Without the various objects defined within  MkDocs, how will you be testing that you are properly manipulating those objects?

[0]: https://docs.python.org/3/library/unittest.mock.html
[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/tests/plugin_tests.py#L128-L132
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/base.py#L17

**Comment by fralau** [comment]
Thanks a lot. To answer your question, what I want to test is not the "inside" part (the interface with MkDocs), but the "outside" code (whatever the plugin is supposed to do). My concern is to make sure that the plugin "outside" code I am writing is working (unit testing), before I am trying to call it from mkdocs. 

If this seems unusual or overly complex, perhaps I am not looking at the problem from the right angle. 

How would you do that? Or perhaps, my putting the "outside" code in an outside piece of code was indeed the right approach after all?

**Comment by waylan** [comment]
As search is implemented as a plugin, may I suggest you look at [search_tests.py][1] and see how we test the `search` plugin. Note that we are not testing the MkDocs API, but rather that the Plugin itself does what it is supposed to do. However, as I mentioned above, as what it is supposed to do is manipulate Mkdocs objects, we import various parts of MkDocs as well. We also make use of quite a few mock objects so that we don't actually write files to disc, etc but can still varify that the appropriate methods were called.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/tests/search_tests.py

**Comment by fralau** [comment]
Thanks a lot. If I understand well, [mock](https://docs.python.org/3/library/unittest.mock.html) is a standard library that allows to "mock" (i.e. emulate) objects and attributes that aren't there because they don't exist yet, or are not available.

This may not be self-evident, but I guess by trial and error (*litterally*) and looking at [search_tests.py](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/tests/search_tests.py), we could work out how to mock up the components that are missing? My intuition is that there should be a pattern that could perhaps be documented?

**Comment by waylan** [comment]
As this appears to be a support question rather than a bug report, I'm closing this.
