### ISSUE TITLE
Something I can't solve

### ISSUE THREAD

**Issue by Steaunk** [mkdocs/mkdocs#1551]
Hello, sir!
When I use `mkdocs build`, there's some mistakes I can't solve.
Could you help me?

> Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.14.0', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mkdocs/cli.py", line 133, in build_command
    site_dir=site_dir
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 147, in load_config
    errors, warnings = cfg.validate()
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 80, in validate
    self._post_validate()
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 72, in _post_validate
    config_option.post_validation(self, key_name=key)
  File "/usr/lib/python3/dist-packages/mkdocs/config/config_options.py", line 263, in post_validation
    theme_dir = [os.path.join(package_dir, 'themes', config['theme']), 
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'dict'

That's it. So what should I do to fix it?
Thank you.

**Comment by waylan** [comment]
It appears that you have an error in your config file. Could you provide the contents of that file?

**Comment by Steaunk** [comment]
Like this?
-----
# Project Information
site_name: OI Wiki
site_description: OI Wiki
site_author: OI Wiki Team
site_url: https://oi-wiki.cf

# Repository
repo_name: 'Ir1d/OI-wiki'
repo_url: 'https://github.com/Ir1d/OI-wiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 OI Wiki Team'

# Contents
pages:
  - Introduction:
  - Basic:
# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'cn'
  disqus: 'OI-Wiki'

extra_javascript:
  - '_static/js/extra.js'
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde`

**Comment by waylan** [comment]
You appear to be using MkDocs version 0.14 (see third line of traceback), however, MkDocs did not support a nested `theme` configuration until version 0.17. You need to upgrade to a newer version of MkDocs.

**Comment by Steaunk** [comment]
`Successfully installed Jinja2-2.10 Markdown-2.6.11 MarkupSafe-1.0 PyYAML-3.13 backports-abc-0.5 certifi-2018.4.16 click-6.7 livereload-2.5.2 mkdocs-0.17.5 singledispatch-3.4.0.3 six-1.10.0 tornado-4.5.3`

I've already use `pip install --upgrade mkdocs`, ans it shown what you see above.

But when I use `mkdocs -V`, it said `mkdocs, version 0.14.0`. So how can I upgrade to a newer version ?

**Comment by facelessuser** [comment]
What version of pip are you on?

**Comment by Steaunk** [comment]
8.0.0

Should I upgrade to the newest one?

**Comment by waylan** [comment]
What is the entire string returned by `pip -V`? Also, what about `pip3 -V`?

I suspect you have multiple version of Python installed and the `mkdocs` command is related to a different version than `pip` is. If I'm right, and `pip3 -V` reports being associated with Python 3.5, then try upgrading using that: `pip3 install --upgrade mkdocs`.

**Comment by facelessuser** [comment]
I've found if your pip is too old, it doesn't play nice with changes made in PyPI recently. I'd check what waylan is asking, and if you're on an old one, upgrade it. I think the latest is 10.x.

**Comment by waylan** [comment]
Closing this due to the lack of any actionable information.

**Comment by jasekiw** [comment]
I got this error immediately. I installed with  `sudo apt-get install mkdocs` on ubuntu 16.04. Why is ubuntu 16.04 not receiving the latest build?

**Comment by waylan** [comment]
@jasekiw, we (the developers of MkDocs) do not maintain the Ubuntu package. Some third party took it upon them-self to create that package. You will need to contact the maintainer of that package regarding having it updated.

We recommend using `pip` rather than your OS's package manager to install Python packages.
