### ISSUE TITLE
Search function doesn't work

### ISSUE THREAD

**Issue by wukefe** [mkdocs/mkdocs#1552]
Hi,

I found the search function didn't work properly.  Tested on the [https://www.mkdocs.org/](https://www.mkdocs.org/).  See the screenshot below

![image](https://user-images.githubusercontent.com/8315666/42777503-48b6b200-8908-11e8-96e8-b9482173c83f.png)

Environment:

- Mac OS X EI Capitan
- Chrome 67.0.3396.99

My current project has the same problem with the search function when I `mkdocs build` a static website.  However, it **works** when I test webpages locally with `mkdocs serve`.

The version of my mkdocs  is

    mkdocs, version 0.16.2

**Comment by waylan** [comment]
The most recent stable release of MkDocs is version 0.17.5, which a complete rewrite of search included in the alpha release 1.0a1. Yet, you state you are using 0.16.2. Please update to a newer release and confirm whether the problem still exists.

**Comment by wukefe** [comment]
> The most recent stable release of MkDocs is version 0.17.5, with a complete rewrite of search included in the alpha release 1.0a1. Yet, you state you are using 0.16.2. Please update to a newer release and confirm whether the problem still exists.

Thank you!  It works.  But I need to modify my existing theme (which is pretty old) to work with the new mkdocs version (0.17.5) that takes time to learn how to handle the new structure of a theme.

**Comment by waylan** [comment]
As there is no actionable item here, I'm closing this.
