### ISSUE TITLE
Cite pip3 from now, in de documentation

### ISSUE THREAD

**Issue by ppKrauss** [mkdocs/mkdocs#1553]
Python2 is past, in nowadays Python3 is the real standard... Modern systems like UBUNTU 18 LTS use only  "pip3", and "pip"  not exists as default.

**Comment by waylan** [comment]
Python does not install `pip` as `pip3` on any system unless their is already a default `pip` for Python 2. In other words, if you install Python 3 directly from python.org, you will get `pip`.  In fact, on most systems, `pip`, `pip2` and `pip3` are all symbolic links on the path which point to the actual program located within the Python distribution. `pip` could point to one of any number of different Python versions (2 or 3), usually the default. In other words, in all systems the correct command name has always been `pip` (use the default version). If the Ubuntu package is no longer creating the `pip` link, then I would suggest filing a bug with the appropriate package maintainer.

I'll reconsider if you can point me to some documentation from the Python/pip developers suggesting that `pip` is deprecated and should no longer be used.

**Comment by ppKrauss** [comment]
Hi, @waylan , thanks explanations (!).

... Sorry, was about https://www.mkdocs.org/#installation  and other minor citations of `pip` that cause confusion: need remember "dummy usr" of UBUNTU that is not `pip`  but `pip3`.
