### ISSUE TITLE
Feature Idea: Ability to use nofollow links

### ISSUE THREAD

**Issue by markallasread** [mkdocs/mkdocs#1557]
One issue we've ran into in generating docs is that mkdocs doesn't support nofollow links.
It's typically added to rel like such on links that you don't want google to follow.

```
 <a href="signin.php" rel="nofollow">sign in</a>
```

I saw that Jekyll implemented it like such, though not certain of the syntax:
```
[Google](https://www.google.com/){:rel="nofollow"}
```
I've seen one other instance where it's in the format ```https://www.example.com rel="nofollow"```
If someone wants to think about how it should be implemented syntactically, I'm happy to dig in & attempt to handle it. 

Edit:
I now realize that one can dump html directly into md files and the markdown parser will just process it straight, that's a good enough workaround for my use-case — while I won't close this, it's at least solved for me! :)

**Comment by waylan** [comment]
Markdown parsing is handled by [Python-Markdown][1] and MkDocs fully supports Python-Markdown [extensions][2]. Check the list of [third-party extensions][3] to see if one meets your needs, or you are free to [create your own][5].

For that matter, the Attribute Extension which ships with Python-Markdown should be able to give you the same behavior that Jekyll is using. Just [enable the extension][4] in your config file.

As there is nothing that we need to do, I'm closing this.

[1]: https://python-markdown.github.io/
[2]: https://python-markdown.github.io/extensions/
[3]: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions
[4]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
[5]: https://github.com/Python-Markdown/markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown
