### ISSUE TITLE
Feature Idea: Ability to seperate site source code & config from build 'site' folder into different repos

### ISSUE THREAD

**Issue by ajhstn** [mkdocs/mkdocs#1562]
For those publishing to github pages, please allow deployment to push source code and configuration to repo A and the built `site` folder to repo B.

Currently, i can only use `mkdocs gh-deploy` to publish to gh-pages.

**Comment by waylan** [comment]
Thanks to the work in #1376, this will be possible in version 1.0, which is currently available as a beta release ([1.0b1][1]). You can preview the docs [here][2].

I encourage others to please download the beta, test it, and report back with any issues you may find.

[1]: https://pypi.org/project/mkdocs/1.0b1/
[2]: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/deploying-your-docs.md#organization-and-user-pages

I'm closing this as a duplicate to #1525, which describes the workaround if you are using an earlier version of MkDocs.
