### ISSUE TITLE
"Files not present in docs directory" message shown for external links

### ISSUE THREAD

**Issue by edmorley** [mkdocs/mkdocs#1564]
Hi!

### STR
1. `mkvirtualenv mkdocs -p python 3.6`
2. `pip install mkdocs==1.0b1`
3. Update [an existing project's mkdocs.yml](https://github.com/mozilla-neutrino/neutrino-dev/blob/cab8e9e0f50c83fbb5ae0f6fb0e98b286beef049/mkdocs.yml) to use `nav` and take advantage of external link support. eg:

```yaml
docs_dir: 'docs'
site_dir: 'build'
strict: true
theme:
  name: 'material'
# ...

nav:
  - Introduction: './index.md'
  # <snip>
  - v8 Documentation: 'https://neutrinojs.org/'
  - v7 Documentation: 'https://release-v7.neutrinojs.org/'
  - v6 Documentation: 'https://github.com/mozilla-neutrino/neutrino-dev/tree/release/v6/docs'
  - v5 Documentation: 'https://github.com/mozilla-neutrino/neutrino-dev/tree/release/v5/docs'
  - v4 Documentation: 'https://github.com/mozilla-neutrino/neutrino-dev/tree/release/v4/docs'
```

4. `mkdocs serve`

### Expected

Console output doesn't output warnings that give the impression something is broken.

### Actual

```
(mkdocs) neutrino-dev $ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following paths are included in the "nav" configuration, but do not exist in the docs directory:
  - https://neutrinojs.org/
  - https://release-v7.neutrinojs.org/
  - https://github.com/mozilla-neutrino/neutrino-dev/tree/release/v6/docs
  - https://github.com/mozilla-neutrino/neutrino-dev/tree/release/v5/docs
  - https://github.com/mozilla-neutrino/neutrino-dev/tree/release/v4/docs
[I 180723 17:15:03 server:292] Serving on http://127.0.0.1:8000
...
```

For links that are clearly external links (ie contain a full URL), it would be good to not output this message (even at log level INFO), since it's likely to be confusing for end users working on our documentation. (Perhaps log level DEBUG is the most appropriate?)

Many thanks :-)

**Comment by waylan** [comment]
You make a good point. DEBUG probably makes more sense. Thanks for the feedback.

**Comment by edmorley** [comment]
Many thanks :-)
