### ISSUE TITLE
More expressive markdown for lists?

### ISSUE THREAD

**Issue by ppKrauss** [mkdocs/mkdocs#1568]
I not see options to other "flavors of markdown", supposing that the only one is https://daringfireball.net/projects/markdown/syntax

It is a problem: we can't preserve `type="A"` or `type="i"` ordered lists...  See here at Github-markdown

1.  One
2.  Two
3.  Three

I.  One
II. Two
III. Three

i.  One
ii. Two
iii. Three

A.  One
B.  Two
C.  Three

a.  One
b.  Two
c.  Three

the source is
```md
1.  One
2.  Two
3.  Three

I.  One
II. Two
III. Three

i.  One
ii. Two
iii. Three

A.  One
B.  Two
C.  Three

a.  One
b.  Two
c.  Three
```

## reversible pandoc
HTML and "good Markdown" most be resersible about "minimal structured HTML content".

```sh
pandoc -f html -t markdown << EOT
<ol type="1">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="I">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="i">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="A">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="a">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
EOT
```
Or the same above with `-o test.md` and  `pandoc -f markdown -t html test.md`   givin back the good lists, with correct `type` attributes.

**Comment by waylan** [comment]
Markdown parsing is handled by the [Python-Markdown][1] parser, and fully supports various extensions which alter the behavior. You may find an [extension][3] ([more here][4]) which meets your needs (or create one if it doesn't exist) and then include it in the [markdown_extensions][2] config setting. As there is no action for MkDocs to take, I'm closing this.

[1]: https://python-markdown.github.io/
[2]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
[3]: https://python-markdown.github.io/extensions/
[4]: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions
