### ISSUE TITLE
Possible addition to deploying documentation

### ISSUE THREAD

**Issue by c0gent** [mkdocs/mkdocs#1577]
I put together a short guide for a work mate:

https://c0gent.github.io/mkdocs-info/

Would any of the information listed there be useful within the user guide? Perhaps a 'GitHub Pages & Travis - Quick Start' section? If so I can submit a PR.

**Comment by waylan** [comment]
Possibly, but I couldn't say without seeing what you had in mind.

**Comment by c0gent** [comment]
Whoops, pasted the wrong link :)

https://c0gent.github.io/mkdocs-info/

**Comment by waylan** [comment]
Wow that very handy to have.  However, while interesting, the first section doesn't really fit with deployment. And the Travis section is just normal Travis stuff. Only the last line of `.travis.yml` file is MkDocs specific. 

It occurs to me that the existing docs mostly assume the user is already familiar with git/GitHub and MkDocs is the only new piece of the user's workflow. However your guide is written for a complete newbie, which has a certain value. Just not sure where or how it fits into the docs.

I wonder if it might make more sense on the [wiki](https://github.com/mkdocs/mkdocs/wiki). Not really sure though.

**Comment by c0gent** [comment]
Sure, I was thinking more just the Travis section might be of use just copy pasted somewhere. I don't need any attribution or anything.

**Comment by c0gent** [comment]
Or just a link to the existing gh-pages site from somewhere. It will exist there until GitHub shuts down :P
