### ISSUE TITLE
Support automatic edit_uri on readthedocs

### ISSUE THREAD

**Issue by danepowell** [mkdocs/mkdocs#1578]
We are using Readthedocs to host our documentation, and we are using mkdocs' built-in readthedocs theme. Note that our project does not have a 'master' branch.

Out of the box, our "edit on github" link was broken because the edit_uri assumes a master branch. We figured out how to override this, but it would be a much better OOTB experience if this "just worked".

I'm not very familiar with mkdocs, but it seems like this should be technically feasible. For instance, the original readthedocs theme (not the mkdocs clone) [automatically detects](https://github.com/rtfd/sphinx_rtd_theme/blob/f20bfa5882979da724241f06bcab075ec3411486/sphinx_rtd_theme/breadcrumbs.html#L45) the current Github branch.

**Comment by waylan** [comment]
The default value for `edit_uri` is the most common default that most people will use. Seems to me that anyone who would have a nonstandard setup, should expect to need to define a custom `edit_uri`. And I would say that not having a 'master' branch would be a non-standard setup. After all, when you create a new repo on GitHub, they create a 'master' branch by default for you. To not get a 'master' branch, you need to explicitly alter the default setting. Therefore, it would not be much of a stretch to also need to alter the default setting for MkDocs.

In any event, I expect any solution to this would be part of a larger solution to #1378. therefore, I am closing this as a duplicate.
