### ISSUE TITLE
Make deferring JS script loading optional?

### ISSUE THREAD

**Issue by elichad** [mkdocs/mkdocs#1581]
I have a custom JS script in one of my documentation pages to allow the page to update with data from another page on the site (not in the docs). It uses jQuery, so I've had to customise the mkdocs theme so that the loading of jQuery isn't deferred. It'd be useful if there was a config option to turn off the automatic deferring. (In my case, it's not really bothersome if the site loads slightly slower.)

**Comment by waylan** [comment]
As this would be a theme specific item, it would make a good candidate for a theme setting (`config.theme.<setting_name>`) which would be added to a specific theme only. As this isn't a high priority item for me a PR is welcome.

**Comment by schneidersoft** [comment]
Ok. So I would like to use jquery in my documents but:
1. extra js is loaded after the document content meaning $ is not available when the script tag loads.
2. the jquery that mkdocs carries is defered. again $ is not available when the script tag loads.

I can add a script tag to each document and load jquery manually. But why load it twice?

If defer was removed I could use the jquery already loaded by mkdocs.

**Comment by oprypin** [comment]
I am interested in totally dropping `defer` from the standard themes.
We'd have to make sure to also remove it from jQuery *and* move it out of the HEAD tag.

mkdocs-material theme never uses `defer`. Also the upstream readthedocs theme never uses it.

I'm wondering, would there be any downsides at all to this?

So, what we have:

#### mkdocs/mkdocs
* `head`
  https://github.com/mkdocs/mkdocs/blob/5af8bd30538ff8f0cfb698c8b90c3020da319f92/mkdocs/themes/mkdocs/base.html#L33-L34
* End of `body`
  https://github.com/mkdocs/mkdocs/blob/5af8bd30538ff8f0cfb698c8b90c3020da319f92/mkdocs/themes/mkdocs/base.html#L199-L201

  Aiming to move these all to end of `body` without `defer`

#### mkdocs/readthedocs
* `head`
  https://github.com/mkdocs/mkdocs/blob/5af8bd30538ff8f0cfb698c8b90c3020da319f92/mkdocs/themes/readthedocs/base.html#L42-L44
* End of `body`
  https://github.com/mkdocs/mkdocs/blob/5af8bd30538ff8f0cfb698c8b90c3020da319f92/mkdocs/themes/readthedocs/base.html#L172-L181

  Aiming to move these all to end of `body` without `defer`

#### mkdocs-material/material
* End of `body`
  https://github.com/squidfunk/mkdocs-material/blob/e8c4528b41abf443e316b21ff5387a7ebdb7b810/src/base.html#L412-L425

#### sphinx_rtd_theme
* `head`, without `defer` (how are they getting away with this??) -  [example site using this, so you can see for yourself](https://python-path-specification.readthedocs.io/)
  https://github.com/readthedocs/sphinx_rtd_theme/blob/2442ab9ffdb8910f8484362cc8dfd165ca3ffb15/sphinx_rtd_theme/layout.html#L64-L92


CC @Sparticuz @squidfunk

**Comment by squidfunk** [comment]
IMHO, there's no need for `defer` if your scripts load at the bottom of `body`, only if you load them in `head`. We never used `defer` in Material for MkDocs, and only use `async` to initiate loading of [analytics scripts](https://github.com/squidfunk/mkdocs-material/blob/530f84416e50e517991b6f1cd44ce8192421bce0/src/partials/integrations/analytics/google.html#L89-L92) as soon as possible.

**Comment by oprypin** [comment]
Opened a pull request accordingly, part of it is dropping `defer`. Would be glad if someone checked that I didn't mess up anything in the frontend part.
