### ISSUE TITLE
mkdocs 1.0.1 bug,Click on the link and the docs prefix will be added automatically.

### ISSUE THREAD

**Issue by lijiawen** [mkdocs/mkdocs#1591]
Click on the link and the docs prefix will be added automatically. the docs is nginx path，the same as directory name。

[I 180814 20:33:29 handlers:132] Browser Connected: 
 http://localhost:8000/docs/docs/docs/socket.md
http://localhost:8000/docs/docs/docs/docs/socket.md
http://localhost:8000/docs/docs/docs/docs/docs/socket.md

**Comment by waylan** [comment]
I can't replicate this behavior. What links are clicking and how are those links being created? Also, which theme are you using?

**Comment by lijiawen** [comment]
my mykdocs.yml config:

site_name: xxx
pages:
    - 'index': 'docs/index.md'
    - 'contract': 'docs/intro/contract.md'

theme:
  name: material

when i click ‘contract’ link in the website，the correct url should be: http://myblog.com/docs/contract
，but when i click again(if is 'index') ,the url is:http://myblog.com/docs/contract/docs/index ,

nginx config：
location /docs { 
  proxy_pass http://ip:8000;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade"; 
}
location /assets {
  proxy_pass http://ip:8000;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade"; 
} 
mkdocs version:1.0.1

my mkdocs directory:
parent:
 -mkdocs.yml
 -api/docs/index.md
 -api/docs/contract.md
 -api/docs/socket.md

  

if i downgrade to 0.17.4 , it it ok

**Comment by squidfunk** [comment]
I've only seen this happen when using MkDocs 1.x with Material < 3. Have you upgraded Material to 3.x?

**Comment by lijiawen** [comment]
@squidfunk , Your answer is a perfect solution to my problem.thanks a lot.
But there is still a problem, when i click the logo,unable to jump to a custom domain url.
my config is:
site_url: https://mydomian.com/docs

**Comment by waylan** [comment]
Please take any discussions regarding the Material theme to the [squidfunk/mkdocs-material](https://github.com/squidfunk/mkdocs-material) project.
