### ISSUE TITLE
Support absolute URLs to internal pages

### ISSUE THREAD

**Issue by ghost** [mkdocs/mkdocs#1592]
# Background

Version 1.0 no longer calculates filepaths back to the root. Where previously a Markdown link `[exec](/ref/exec.md)` might produce HTML with a computed path `<a href="../../../ref/exec/">exec</a>` it now simply replicates the path: `<a href="/ref/exec/">exec</a>`. While the documentation says this is unsupported (no link path should begin with a slash) this actually works fine with `mkdocs serve`. And it also works fine when the site is exported to a server root. But it fails if the site is exported to a child folder of the server root, e.g. `docs.example.com/preview/`.

# Use case

MkDocs instance code.kx.com has about 250 pages. Because from time to time major sections are re-arranged, the internal links contain no paths that include `../`. Paths are either to siblings, to descendants, or specified from the root. This allows major sections to be moved without rewriting the link filepaths. 

Currently we have 775 internal links beginning with slash, in 111 files. Upgrading to 1.0 would require us to convert all of them to relative paths. 

We would prefer to retain the paths from the site root, for the following benefits:

* Retain the mobility of large sections of our site. 
* Uncouple article copy from the site structure. For example, an article should refer to, say, a Reference article, `see [exec](/ref/exec.md)` regardless of where in the site the article is posted. 
* Avoid the work of converting the existing filepaths.
* Support our practice of previewing in development multiple branches of the main site.

# Feature request

Restore the computation of relative file paths to the root.

**Comment by StephenTaylor-Kx** [comment]
> that the URL remains intact as an absolute URL was a feature request

My FR would have appeared some time ago had I realised previous behaviour was to be dropped! Perhaps others are in a similar position. 

If I’m following you we have three use cases in play:

1. Link to a URL on the same server but not in the site
2. Follow links in the source as hosted on GitHub
3. Specify internal links from the site root rather than the link start 

Version 1.0 supports (1) and (2). All three cases have merit, but for my work the utility of (3) well outweighs the other two combined. 

You might wish to leave the issue open for a while to see if others are similarly placed.

**Comment by waylan** [comment]
> ...previous behaviour was to be dropped!

We did not "drop" anything. We fixed a bug. I realize that's a nitpick, but an important distinction in deciding how we should proceed.

> Version 1.0 supports (1) and (2). All three cases have merit, but for my work the utility of (3) well outweighs the other two combined.

Great, then you have the motivation to do the work. I don't (for me (1) and (2) far outweigh (3)), so don't expect anything from me regardless of how "popular" the request is. Or you can wait for someone else who wants the feature to come along and do the work. Either way, I'm not opposed to the feature being added so long as we don't break (1) and (2). Therefore, I'll leave the issue open.

**Comment by zhangzq** [comment]
The point 3 of @StephenTaylor-Kx could be accomplished by relative path. But Point 1 won't be accomplished if change the behavior of the `[link](/path/file)`。

**Comment by waylan** [comment]
Following the discussion in #1619 and the report/fix in #1621 / #1623, I'm closing this as wont-fix. If you want to use absolute paths to internal pages, then you can, but there will be no validation of them and they will not be altered in any way. You *must* use a URL which points to the rendered page, not the source page. Of course, without any validation, this is risky. And the same source files won't work if the site is hosted in a subdir of a domain.

**Comment by foosel** [comment]
Just as an FYI, I solved this issue for my own workflow with a [custom plugin](https://github.com/OctoPrint/mkdocs-site-urls). No link validation, but at least a solution that takes `site_url` into account and generates *site relative* URLs from something like `site:images/foo.png`. Also works for site relative URLs in links (`[foo][site:path/to/foo]`).
