### ISSUE TITLE
"pip install -U mkdocs" => 1.0 not found? 

### ISSUE THREAD

**Issue by pantorian** [mkdocs/mkdocs#1605]
Hi,
I am trying to upgrade to version 1 but pip doesn't find any release later than 0.17.5
The environment is Centos 7.
Any pointers / suggestions would be greatly appreciated.

Thanks
Rolf

**Comment by waylan** [comment]
I'm assuming you resolved this as it has been closed.

**Comment by pantorian** [comment]
Hi Waylan,

No, I haven’t been able to resolve it.
I asked the same question on the google forum and decided to close it here.
https://groups.google.com/forum/#!topic/mkdocs/7Y1uYRWZ6Ew <https://groups.google.com/forum/#!topic/mkdocs/7Y1uYRWZ6Ew>

Thanks
Rolf

**Comment by waylan** [comment]
Well, the files are available for download from [PyPI][1]. If pip isn't finding them, then that suggests it may not be connecting to the correct index. In other words, my assumption is that you have a system configuration problem on your end. Not much I can do to help with that. The documentation can be found [here][2].

As a workaround you might try installing a specific version:

```
pip install -U mkdocs=1.0.2
```

Or you could manually download the file and install it:

```
wget https://files.pythonhosted.org/packages/5d/9c/c5f22a137c19ef4c02361b61dfa84df2e733e1f920def3644f9b7eac0374/mkdocs-1.0.2-py2.py3-none-any.whl
pip install -U mkdocs-1.0.2-py2.py3-none-any.whl
```

[1]: https://pypi.org/project/mkdocs/#history
[2]: https://packaging.python.org/tutorials/installing-packages/

**Comment by algo99** [comment]
Hi,
which Python version do you have? 
Some CentOS-7 distros still have 2.7.5 as standard version. 

From https://pypi.org/project/mkdocs/1.0/:
> Requires: 
> Python >=2.7.9,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*

**Comment by pantorian** [comment]
Hi, your intuition was correct; ‘python -V’ shows 2.7.5
I tried to install rh-python36 and then mkdocs 1.0.2 but did not get this to work.
I will try to find some other way to install python 3.

Thanks for your assistance.
