### ISSUE TITLE
Minimal template in custom themes documentation doesn't work

### ISSUE THREAD

**Issue by mivade** [mkdocs/mkdocs#1608]
It looks like the documentation for custom themes [here](https://www.mkdocs.org/user-guide/custom-themes/) is out of date. For example, it says that the following is a minimal template:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>{% if page_title %}{{ page_title }} - {% endif %}{{ site_name }}</title>
  </head>
  <body>
    {{ content }}
  </body>
</html>
```

yet this results in a completely blank page. By inspecting [mkdocs-basic-theme](https://github.com/mkdocs/mkdocs-basic-theme) I found that `content` should now evidently be `page.content`, `page_title` should now be `page.title`, and `site_name` should be `config.site_name`.

**Comment by waylan** [comment]
Looks like we missed that section. Thanks for the report. Those variable names were first deprecated in [0.16][1] and and completely removed in [0.17][2].

[1]: https://www.mkdocs.org/about/release-notes/#template-variables-refactored-874
[2]: https://www.mkdocs.org/about/release-notes/#previously-deprecated-template-variables-removed-1168
