### ISSUE TITLE
Sidebar is not showing in Github pages

### ISSUE THREAD

**Issue by wongjiahau** [mkdocs/mkdocs#1612]
Here's how my page look like in my local development server (my laptop):
![image](https://user-images.githubusercontent.com/23183656/44718310-41599e80-aaf2-11e8-99ea-458762596fe1.png)

But, when I upload the pages using `mkdocs gh-deploy`, the pages does not have sidebar, as shown below:
![image](https://user-images.githubusercontent.com/23183656/44718342-5afae600-aaf2-11e8-88fc-ec11d4dccd2e.png)

Is this normal or had I miss out some steps?

**Comment by waylan** [comment]
Do your browser’s developer tools reflect any errors when loading the page? Could you point me at the project?

**Comment by wongjiahau** [comment]
@waylan [This link](https://github.com/wongjiahau/Pineapple) is my Github project link, [this link](https://wongjiahau.github.io/Pineapple/) is the Github pages link.

**Comment by froschdesign** [comment]
@wongjiahau 
Something went wrong, because you do not use MkDocs to generate the HTML. You are using Jekyll:

```html
<meta name="generator" content="Jekyll v3.7.3.1">
```

**Comment by wongjiahau** [comment]
@froschdesign What should I do to fix that?

**Comment by wongjiahau** [comment]
Sorry guys, I found out what is the problem, because I set to use `master/docs` as Github pages instead of `gh-pages` branch.  

![image](https://user-images.githubusercontent.com/23183656/44774901-e930a400-aba6-11e8-9a39-4a1ff1d98729.png)
