### ISSUE TITLE
How to specify the push credentials

### ISSUE THREAD

**Issue by nitinsurana** [mkdocs/mkdocs#1614]
Pushing to gh-pages branch requires basic credentials. How can I specify the credentials in the `mkdocs gh-deploy --clean` command ?

PS : I'm using jenkinsfile, I have the user-passwd/basic credentials in the ENV variables.

**Comment by waylan** [comment]
The `gh-deploy` command is a light wrapper around [ghp-import][1], which does not have any `--clean` option. Therefore we don't either. If you would like to have such an option added, you need to take that up with the ghp-import project.

[1]: http://github.com/davisp/ghp-import

**Comment by waylan** [comment]
As it is unclear what the issue is and no followup has been received, I'm closing this issue.
