### ISSUE TITLE
Security Issue on Module PyYAML

### ISSUE THREAD

**Issue by barreeeiroo** [mkdocs/mkdocs#1620]
I've integrated Snyk into the repository github.com/Makeroid/Documentation, and I found there was a **High Severity Vulnerability**

![screenshot_2018-09-04-23-21-56-318_com android chrome](https://user-images.githubusercontent.com/19251112/45058678-a9cbf100-b099-11e8-8f07-f95e53c5d30e.png)

Should I by worried about that?

**Comment by waylan** [comment]
This is a duplicate of #1529. The tradeoffs are discussed there, but in short, we do not consider it a concern for how we are using it.
