### ISSUE TITLE
How to set base url ?

### ISSUE THREAD

**Issue by seeb0h** [mkdocs/mkdocs#1622]
Hi!

I need to deploy a mkdocs generated website at this url: `https://my-website/doc/` 
For routing needs, I need each links to be prefixed with `./doc/`. E.g. `./doc/assets/images/favicon.png` instead of `./assets/images/favicon.png`

I can't find a way to set it this base url in the .yml.

**Comment by waylan** [comment]
Have you set the `site_url` setting to the full URL: `https://my-website/doc/`?

Regardless, internal links between the documents don't need to include `doc/` as they are relative to each other within that directory and there is no reason for the relative links to step out of the directory, The few rare occasions were it does matter, we make use of the `site_url` setting to derive the appropriate base url.

**Comment by seeb0h** [comment]
Well, it works now.

It was a combination of routing issues with AppEngine and misconfiguration of mkdocs.yml.

For the sake of futur people who may encounter this, here is something working.

app.yaml
``````

**Comment by root-ansh** [comment]
@seeb0h  what is app.yaml? where it has to be created?

**Comment by waylan** [comment]
I believe `app.yml` is the configuration file for AppEngine, the server @seeb0h is using for serving his site.
