### ISSUE TITLE
Any way to configure live reload ports?

### ISSUE THREAD

**Issue by dodekeract** [mkdocs/mkdocs#1627]
I’m running the local development version inside docker. The port outside of docker does not match the port inside of docker.

Is there any way to either:

1. specify a port that live reload will use?
2. tell live reload to automatically use the port that the browser uses?

**Comment by waylan** [comment]
Did you check `--help` for the `serve` command?

```
$ mkdocs serve --help
Usage: mkdocs serve [OPTIONS]

  Run the builtin development server

Options:
  -f, --config-file FILENAME      Provide a specific MkDocs config
  -a, --dev-addr <IP:PORT>        IP address and port to serve documentation
                                  locally (default: localhost:8000)
  -s, --strict                    Enable strict mode. This will cause MkDocs
                                  to abort the build on any warnings.
  -t, --theme [readthedocs|mkdocs]
                                  The theme to use when building your
                                  documentation.
  -e, --theme-dir PATH            The theme directory to use when building
                                  your documentation.
  --livereload                    Enable the live reloading in the development
                                  server (this is the default)
  --no-livereload                 Disable the live reloading in the
                                  development server.
  --dirtyreload                   Enable the live reloading in the development
                                  server, but only re-build files that have
                                  changed
  -q, --quiet                     Silence warnings
  -v, --verbose                   Enable verbose output
  -h, --help                      Show this message and exit.
```

Specifcally, the `--dev-addr` option accepts an IP address and port.

**Comment by dodekeract** [comment]
@waylan Yes, I’m already using that argument to specify where the server will listen internally. However, the frontend is not smart enough to pick up the correct port from the URL. The port used by the frontend is the same port that’s specified in this argument, which is wrong since the frontend isn’t exposed on that port.

**Comment by waylan** [comment]
I'm sorry, I'm not following.

In any event, our server is a light wrapper around [python-livereload][1]. I would suggest exploring whether using that server directly addresses your needs.

[1]: https://github.com/lepture/python-livereload

**Comment by dodekeract** [comment]
@waylan here’s a minimal config to reproduce what I’m talking about:

<details>
<summary>`Dockerfile`</summary>

```Dockerfile
FROM python:3.7-alpine

WORKDIR /mkdocs/

# dependencies
RUN pip install mkdocs

# configure mkdocs
RUN mkdir docs
COPY mkdocs.yml .

# serve development version
CMD mkdocs serve --dev-addr=0.0.0.0:80
```
</details>

<details>
<summary>`mkdocs.yml`</summary>
```yml
site_name: 'mkdocs'
```
</details>

<details>
<summary>`docker-compose.yml`</summary>
```yml
version: '3'
services:
  mkocs:
    build: .
    ports:
      - '8080:80'
```
</details>

Here’s how you can run it:

```bash
cd ./minimal-repro
docker-compose up --build
```

Notice the errors in the browser console? `livereload` doesn’t use the browser-facing ports, which is either a bug or a missing feature.

**Comment by waylan** [comment]
Ah, you are redirecting/remapping (??) the port. You did say that "The port outside of docker does not match the port inside of docker" but I understood that to be the problem, not the desired behavior. 

Regardless, I don't have a docker install available to test this on, so I still don't know what errors you are getting. But I'll take a guess. I'm assuming that the page initially loads fine, however errors appear in the console stating that it cannot connect to the reload server and live reloading never works. Am I correct or are you having a different problem?

Assuming I'm correct, the live-reload server consists of two servers: 

1. A flat file server. This serves the actual files.

2. A websocket server. After a page is loaded, a script (which the flat file server injected into the page) connects to the websocket and listens for messages from the server telling it to reload the page.

As I understand it, both servers use the same IP and port  (which is provided in the `--dev-addr` option), I'm not sure if you need to do any additional docker configuration for the websocket to work, or if this is a bug in the livereload server.

In any event, this is an upstream issue you need to work out with python-livereload first. Once you can get that working, we can talk about any additional config options we may need to add to our wrapper.

**Comment by waylan** [comment]
For what it's worth, python-livereload's [server.serve][1] method accepts a `liveport` option which sets the port for the websocket separate from the file server port. Looking at the code, it appears that if the user does not define the option, then the same port as the file server is used. If the ports match, then the websocket handler is included in the same server as the file handler (with each request routed to the appropriate handler). However, if the ports do not match, then two server instances are created (one with the file handler and the other with the websocket handler).

The most that we could do would be to add an option to accept and pass on the `liveport` option. But its not clear why that would be necessary.

Is the problem that Docker can't handle both the websocket and file servers on the same port or is it simply that the websocket isn't working with Docker regardless of which port its on? If it's the former, then we should add the `liveport` option), but if its the latter, then there is nothing we can do except perhaps suggest that the user adjust their docker config.

This needs testing, which I will not be doing as I don't use Docker and have no need for it.

[1]: https://github.com/lepture/python-livereload#serverserve

**Comment by dodekeract** [comment]
@waylan The only place where anything goes wrong is in the frontend, the moment that `livereload` tries to connect. Since the port isn’t taken from the URL (no idea why that’s not the default TBH), it’ll try to connect to `localhost:80` (in my example)`, even though `localhost:8080` would be correct.

`livereload` serving on the same port as the files are hosted is the correct behavior and should be kept. The incorrect behavior occurs when it tries to connect to its internal port.

Is there any way to let the frontend always connect to the domain/port combination that’s shown in the browser’s address bar? That should work in any setup.

**Comment by waylan** [comment]
@dodekeract thanks for the clarification. You have verified that this is an upstream issue with [Python-livereload][1]. Any changes to address your issue will need to be made by that project. Please report the issue there.

> Since the port isn’t taken from the URL (no idea why that’s not the default TBH)

Btw, when looking through their code, I noticed that they do something [slightly differently][2] when using port `80` than with any other port. It may be as simple as not using port `80` to get everything working.

[1]: https://github.com/lepture/python-livereload
[2]: https://github.com/lepture/python-livereload/blob/master/livereload/server.py#L224-L229
