### ISSUE TITLE
Possible to use liquid tags on .md file?

### ISSUE THREAD

**Issue by dimative** [mkdocs/mkdocs#1635]
Hello. I want to use liquid tags to in my .md files. 

{% capture example %}
{% for color in config.theme.bs-colors %}
<span class="badge badge-{{ color.name }}">{{ color.name | capitalize }}</span>
{% endfor %}
{% endcapture %}

like this. Is it possible?

**Comment by waylan** [comment]
This is a duplicate of #304, and is not likely to be implemented outside of a plugin.
