### ISSUE TITLE
Use `rel=external` on external links

### ISSUE THREAD

**Issue by ppKrauss** [mkdocs/mkdocs#1639]
In any hipertextual redaction and final layout is important to distinguish external links and local-document (or local-hypertext) links... There are a way to show with different styles the local and external links?

(if not, it is a suggestion for issue)

-----

* External link (`http://external`)
* Local page link (`here`)
* Intra-link (`here#here`)

Most important to distinguish external from others... If possible, a little distinction between local-page and intra-link.

**Comment by waylan** [comment]
Sorry but I don't follow. Is this a question, a bug report or a feature request?

**Comment by ppKrauss** [comment]
Hi @waylan, well... Is a  **feature request**.

**Comment by ppKrauss** [comment]
Request to mkdocs generate HTML with attribute `rel`  on links, `rel=external`  when the link is external. See https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types

**Comment by waylan** [comment]
I've recently given this some consideration myself. It seems like a reasonable request and expectation, especially as we are already determining whether each link is an internal or external link.

One way to accomplish that is by setting `rel=external` on external links.

Another option would be to replicate Sphinx, which sets `class="link external"` or `class="link internal"` on all links (IIRC).  A benefit of that solution would be that themes which clone Sphinx themes (such as `readthedocs`) already include CSS for styling internal and external links differently. However, that in itself isn't a reason to chose this option.

Personally, I'm inclined to go with `rel=external` as that is the more semantic and universally understood method for identifying external links.

**Comment by waylan** [comment]
Markdown links are handled by the private Markdown [extension][1] so any changes to the Markdown output would happen there. Any other links (such as navigation) would be controlled by theme templates.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/pages.py#L188

**Comment by berot3** [comment]
Hi! Not sure, but I think this would make it easier to mark all external links in mkdocs as external (with a icon/symbol or so), right?

But at least there are workarounds: https://gitter.im/squidfunk/mkdocs-material?at=5d9dd20192920c36a13b7dd5

It would be great if this would be already handled by mkdocs of course.

**Comment by ppKrauss** [comment]
Hi @berot3 , your comment make sense, but ... hum... This is my personal view:

* it is not a good practice to use regular expression (checking value-by-value about `http|https|ftp`) in a CSS selector.
* there are situations where we can express local site with different subdomain (ex. API), so it is not a good heuristic.

My purpose is to do it explicitly by Python analysis (as mkdocs configurations), not after by complex CSS.

**Comment by berot3** [comment]
hi @ppKrauss im open for any solution of course 😄 

but at the moment your solution is not ready yet, right? So all I have is a workaround with css.

**Comment by Stanzilla** [comment]
This is actually a pretty good usecase for a plugin but it would also be nice baseline.

Considering that there could be an option to attach a class `external` and then maybe also a `target="_blank"` and `rel="noopener` to them.

**Comment by squidfunk** [comment]
Update: If you're a user of [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), the privacy plugin offers this exact functionality – it allows to attach additional attributes to external links like [`target="_blank"`](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#+privacy.external_links_attr_map) or [`rel="noopener`](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#+privacy.external_links_noopener).

**Comment by pawamoy** [comment]
We'll close this as out of scope for MkDocs core as it is solvable with plugins, see some plugins' approach:

- https://github.com/JakubAndrysek/mkdocs-open-in-new-tab
- https://squidfunk.github.io/mkdocs-material/plugins/privacy/ (sponsors only)

We can however re-open if someone wants to work on that (adding `rel="external"` to external links, thanks to the private Markdown extension within MkDocs' code, mentioned by @waylan).
