### ISSUE TITLE
v1.0.4 breaks root-relative markdown links

### ISSUE THREAD

**Issue by zbjornson** [mkdocs/mkdocs#1641]
#1623 made it so links like `[foo](/foo.md)` are no longer converted to proper links. We always use a leading `/` so that it's easier to move our pages around (no hunting for `..` to add or remove). Is this intended behavior? It seems like a really subtle distinction to use for doc page vs. non-doc page links.

**Comment by zbjornson** [comment]
Got it, thanks. I had interpreted "relative" in the context of URLs (the [WHATWG URL spec](https://url.spec.whatwg.org/#url-writing) defines a "path-absolute URL" string, i.e. one beginning with U+002F `/`, as a "relative-URL string" and not absolute). It's convenient to have root-relative links in mkdocs, if you'd consider supporting it again in the future.

**Comment by waylan** [comment]
This is a duplicate of #1592. The reasons are discussed in detail there. We will not be reconsidering.

**Comment by waylan** [comment]
>  I had interpreted "relative" in the context of URLs (the WHATWG URL spec defines a "path-absolute URL" string, i.e. one beginning with U+002F `/`, as a "relative-URL string" and not absolute). 

For the record, internal links within MkDocs documents are not web URLs. They are local paths. A relative path on the local file system would never start with a slash. Therefore, any URL that starts with a slash is considered to be a web URL. Local paths are converted to web URLs while web URLs are not converted, but expected to already be in the correct format. Therefore, if you want to start your links with slashes, then you should use either `[foo](/foo/)` or `[foo](/foo.html)` depending on how you have `use_directory_urls` configured.
