### ISSUE TITLE
hightlight.js not loading with ReadTheDocs theme and http server

### ISSUE THREAD

**Issue by DDorch** [mkdocs/mkdocs#1646]
In the file  mkdocs/mkdocs/themes/readthedocs/base.html, the url used for loading hightlight.js are not complete: 

```html
{%- if config.theme.highlightjs %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  {%- for lang in config.theme.hljs_languages %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/{{lang}}.min.js"></script>
{%- endfor %}
```
The protocole is missing causing pages serves by http server to try loading to `http://cdnjs.cloudflare.com...` which is not correct.

The code should be changed to:
```html
{%- if config.theme.highlightjs %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  {%- for lang in config.theme.hljs_languages %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/{{lang}}.min.js"></script>
{%- endfor %}
```

**Comment by waylan** [comment]
I'm not seeing any problem. I've checked multiple browsers and they all make a `https` request. Which browser are you using and what error are you seeing (you may need to check your browsers dev tools for the error)?

**Comment by waylan** [comment]
For the record I have tested this using the local dev server (`http://127.0.0.1:8000/`) on both Windows and Mac with Chrome, Firefox and Safari. I have tried both with and without local cache. I have never seen a failure. In fact, the request for `highlight.js` has always been an `https` request. I don't even see a redirect from `http` to https`.

**Comment by geomunion** [comment]
I like this protocol-relative urls, but have a look at this:
https://stackoverflow.com/questions/28446314/why-use-protocol-relative-urls-at-all

If you visit your MkDocs site via HTTP, then assets from cdn are also requested via HTTP.
But because of HSTS (https://de.wikipedia.org/wiki/HTTP_Strict_Transport_Security) your Browser may choose HTTPS, if an asset was previously requested via HTTPS.

So - in this case - i prefer https:// urls

btw. : HTTP is still working - try:
`curl -vs "http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" > /dev/null`

**Comment by waylan** [comment]
> Why not writing the complete url? Is there any restriction?

That is what is recommended by the highlight.js documentation. But if `http` always needs to redirect to `https`, we might as well just include the scheme in the templates.

I just noticed that the [documentation][1] currently states:

> *Version 9.12.0 has not yet been updated on CDNs. Check back soon!*

Perhaps that is the problem.

[1]: https://highlightjs.org/download/

**Comment by waylan** [comment]
> I like this protocol-relative urls, but have a look at this:
https://stackoverflow.com/questions/28446314/why-use-protocol-relative-urls-at-all

After a review of the matte,r it appears that we should just use `https` on all of our CDN URLs.
