### ISSUE TITLE
Drop Python 2.6

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#165]
We should aim to drop Python 2.6, probably not in the next release, but the one after, or before 1.0 at least.
- We have a number of hacks in place to deal with posixpath problems.
- Python Markdown has dropped Python 2.6 support, so we currently can't use the latest version

Doing this will involve:
- Updating docs
- Removing 2.6 test runs
- Removing 2.6 hacks/fixes

**Comment by d0ugal** [comment]
Given that we have relaxed the python-markdown requirement on pythons greater than 2.6 I don't see a huge rush to do this. We may want to do this for python-markdown version 3 or mkdocs version 1

Changing the milestone to think about this later.

**Comment by d0ugal** [comment]
I am going to start moving towards this. Support will be dropped in MkDocs 0.16. We will display a warning to users in 0.15 if they are running Python 2.6.

**Comment by tomchristie** [comment]
:+1:

**Comment by d0ugal** [comment]
Mock also now doesn't support Python 2.6. #688
