### ISSUE TITLE
Markdown syntax for rendering Note block

### ISSUE THREAD

**Issue by diazgilberto** [mkdocs/mkdocs#1659]
I can't find in the documentation the syntax to render (warning, info, note, etc) block, like the following...

![screen shot 2018-10-13 at 8 12 21 pm](https://user-images.githubusercontent.com/9165819/46911549-e4406d80-cf24-11e8-898f-14445137a598.png)

**Comment by waylan** [comment]
This uses the [Admonition Extension][1], which is provided with Python-Markdown. Of course, you do need to [enable the extension][2] in the `mkdocs.yml` config file. Finally, the theme you are using needs to include some styles for admonitions (the built-in themes do).

[1]: https://python-markdown.github.io/extensions/admonition/
[2]: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by diazgilberto** [comment]
It worked perfectly. I will leave here how to include the extension in the `mkdocs.yml` for reference to others.

```yml
theme: readthedocs
markdown_extensions:
  - admonition
```

In your markdown file do the following...

```md
!!! warning
This is a warning for you.
```

**Comment by daviewales** [comment]
Note: The admonition must be indented by four spaces.

```
!!! warning
    This is a warning.
````

There can optionally be a blank line between the tag and the body.

```
!!! warning

    This is a warning with a blank line before it.
```
