### ISSUE TITLE
Check box support

### ISSUE THREAD

**Issue by diazgilberto** [mkdocs/mkdocs#1660]
Does mkdocs has support for check box? I can't find anything in the documentation and is not rendering `[x] some item`.

**Comment by over9001** [comment]
Yes!  :smile: 
Please have a look at this: https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#tasklist

**Comment by waylan** [comment]
Checkboxes are not a standard feature of Markdown. Therefore you will need to use a third party extension to add support.

**Comment by diazgilberto** [comment]
I'm not using the material css framework, instead I'm using the rtd theme and the checkbox is not rendering properly. 
Do you know which third party library I can use to create checkboxes inside the rtd theme?

**Comment by waylan** [comment]
Markdown extensions only render the HTML. If you would like them to be styled, then that is the responsibility of a theme. If you are using a theme which doesn't include support, then you will need to provide your own CSS rules through [theme customization][1].

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

**Comment by sowmyamanojna** [comment]
The link posted by over9001 now points to [Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/). The current link is: https://squidfunk.github.io/mkdocs-material/reference/lists/#definition-list.
