### ISSUE TITLE
Livereload need to work on after save file

### ISSUE THREAD

**Issue by dimative** [mkdocs/mkdocs#1663]
Hello Guys.
I am new for MK Docs. I need to work livereload feature after save file. How can i do it. Have any config file?
Thanks

**Comment by waylan** [comment]
I’m not sure I understand what you are asking. Could you provide an example?

**Comment by dimative** [comment]
When i type something on my markdown file, mkdocs reload my browser. I want to reload browser on after save file. sorry my poor english.

**Comment by waylan** [comment]
Our livereload server is a light wrapper around [lepture/python-livereload]. If you found a bug with the server, you may want to report it upstream.

[lepture/python-livereload]: https://github.com/lepture/python-livereload/
