### ISSUE TITLE
How do I now **not** build many pages that I don't want?

### ISSUE THREAD

**Issue by twardoch** [mkdocs/mkdocs#1665]
After the `pages` to `nav` change postulated in https://github.com/mkdocs/mkdocs/issues/699 MkDocs now compiles all pages in the source folder. This may be OK for some users but not for others. 

For example, my team is using a private Github Wiki to develop end-user documentation for a software project. 

- we have some wiki pages that are intended to be published as standalone pages, 
- we have other pages that are "in-development" and should not be deployed at all (or until we deem them "ready") 
- we have some Markdown files which are "snippets" that are being inlined into other pages via Markdown plugins, and they shouldn't be built as standalone pages at all
- we have some pages with editorial notes and discussions

In older MkDocs, the `pages` section of the config was a convenient way to define which are ready, and to give them structure. 

Now MkDocs also builds all those unfinished, internal and snippet pages. In addition, it also throws tons of warnings for invalid links when building those pages that are never intended to be built — which makes catching the actual invalid links hard. 

Instead of "opt-in", the system became "catch-all". So: 

1. How do I use the "opt-in" mode? 
2. If there is no way to use the "opt-in" mode, how do I "opt-out" of building some pages?

**Comment by twardoch** [comment]
Ps. Also, in fact, we’re building documentation for several different products from the same wiki. We have some 400 Markdown files in the wiki, and the docs for one product is built from approx. 280 of those files, the docs for another product is built from 200 of those files, and docs for the third product is build from about 100 of those files — many but not all of those overlap. 

It’s nonsensical that MkDocs now builds all 400 pages for all three products.

To me, the whole point of using MkDocs was that it allowed me to have one large collection of Markdown files, and then have several YAML configuration files that build just the right stuff. 

"Opt-out" would also be nonsensical — I have several YAML config files, in each of them the `pages` section defines that should be **included**, and I wouldn’t want to **in addition** put the stuff that should be **excluded**, because that’s duplicate data.

**Comment by froschdesign** [comment]
@twardoch 
> …the whole point of using MkDocs was…

Please keep mind: before the current version, it was always a development version – 0.x. This means: "Anything may change at any time."

> How do I use the "opt-in" mode?

You can use a script that is called before the documentation is created. Copy all relevant files (listed in your config) to a temporary directory and use this as your build directory.

**Comment by waylan** [comment]
This sort of feature could be implemented as a plugin using the `on_files` event. That event can alter the files collection for a build to add or remove files from the collection and was created for this very sort of thing. What you are doing is a very customized use which was never officially supported, so a custom plugin would not be an unusual requirement here.

**Comment by wouter-veeken** [comment]
@waylan 
> What you are doing is a very customized use which was never officially supported, so a custom plugin would not be an unusual requirement here.

While I appreciate that it may not be within the scope of your intentions, building multiple outputs from single-sourced content is an extremely common use case for serious/professional/fulltime documentation writers. 

Could this not be handled with frontmatter, somehow?

**Comment by waylan** [comment]
> Could this not be handled with frontmatter, somehow?

Possibly, but only through a plugin.

**Comment by twardoch** [comment]
@waylan I'll write the plugin but could you possibly point me to a skeleton off how to do it?

**Comment by waylan** [comment]
@twardoch the documentation is [here][1] and the Search Plugin (see [source][2]) provides a comprehensive example of how a plugin should be structured. There are a couple ways one could implement a plugin to optionally include/exclude pages:

1. Alter the files collection with the [on_files][3] event. A general purpose plugin might have plugin config settings for `include` and `exclude`, which would accept a list of files or directories. The plugin would then alter the files collection by adding and/or removing files from the [files collection][4] within the `on_files` event. Note that, as documented in the source comments, [File][5] objects have 4 file paths associated with them, but those paths do not need to be associated with config settings such as `site_dir`. They could point anywhere.
2. Use a file's front-matter to exclude it from the built site. This would likely require the [on_post_page][6] event. Note that "[i]f an empty string is returned, the page is skipped and nothing is written to disc." The idea being that within the event, check `page.meta` for a specific key/value, and either return `output_content` or  an empty string.

Note that the first solution alters the files collection early in the build. Therefore, auto-generated navigation is affected and excluded pages are never built. The second solution would build every page (and include them all in auto-generated navigation) and only exclude a page by discarding it after the page has finished rendering. While the second solution would be much simpler to build, it would be much less useful.

[1]: https://www.mkdocs.org/user-guide/plugins/#developing-plugins
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/contrib/search/__init__.py
[3]: https://www.mkdocs.org/user-guide/plugins/#on_files
[4]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/files.py#L16
[5]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/files.py#L85
[6]: https://www.mkdocs.org/user-guide/plugins/#on_post_page

**Comment by twardoch** [comment]
Thanks, that is very helpful.

**Comment by wouter-veeken** [comment]
For reference, several static site generators allow you to specify `status:
draft` in the frontmatter to prevent a page from being published.

Great to hear this is being picked up!
