### ISSUE TITLE
Canonical tag is missing on the Read the Docs theme

### ISSUE THREAD

**Issue by stsewd** [mkdocs/mkdocs#1667]
On the mkdocs theme there is this 

https://github.com/mkdocs/mkdocs/blob/ff5a65c4500468e313c22d34e03b74e7a4cbe789/mkdocs/themes/mkdocs/base.html#L10

But on the reatheocs theme there isn't

I can help fixing this if the issue is correct :)

**Comment by waylan** [comment]
You appear to be correct. And in fact, the upstream theme does include such a link. So yeah, this should be added. A PR is welcome.
