### ISSUE TITLE
Only warn the user about files in the output directory that wont be overwritten

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#167]
As per @tomchristie's [comment](https://github.com/tomchristie/mkdocs/pull/154#issuecomment-59035198), we can expand on the additions in #154 by only warning the user when files wouldn't be overwritten (i.e. stale files that no longer exist in the docs).

**Comment by waylan** [comment]
Now that "clean" is the default (see #997), we issue a warning by default when the user uses `--dirty`. Therefore, I'm closing this as it offers no additional value.
