### ISSUE TITLE
Links with hex encoded characters do not work (specifically %20)

### ISSUE THREAD

**Issue by simonpoole** [mkdocs/mkdocs#1670]
For the app Vespucci (see [vespucci.io](https://vespucci.io/)) we use mkdocs to create the website and a pegdown based system to use the same markdown files for on device  documentation.

For various reasons the file names of the individual documents contain spaces and it would be difficult to avoid this. Inter document links work with no issue on device by encoding the spaces as %20, however this does not work with mkdocs because the logic in https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/pages.py line 217 does not decode the path before checking if the corresponding file exists. 

Naturally the same issue exists for other hex encoded characters and for using "+" as a space replacement. 

PS: yes, I know it works if one does not encode the spaces, however that is not "valid" markdown and causes issues with other markdown parsers, for example pegdown.

**Comment by waylan** [comment]
> that is not "valid" markdown

There is some [disagreement][1] about that, even among versions of the reference implementation.

> ... and causes issues with other markdown parsers, for example pegdown.

That is true and a real concern. Personally, I never use spaces in my paths and generally consider them a bad idea. But of course, others do use spaces and MkDocs should support that.

And you are correct, the way to address this is to...

> decode the path before checking if the corresponding file exists.

I suppose we should also be encoding the URLs that we generate.

[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfoo%5D(foo+bar)

**Comment by simonpoole** [comment]
@waylan there's a reason I put "valid" in quotes :-). On output the links seem to be correctly encoded as far as I've checked, Wrt a fix: it isn't quite clear to me if there are any performance concerns if there are not, then simply decoding all paths before tacking on the directory and so on, would be the simple fix (and essentially what the money patch I'm using right now does).
