### ISSUE TITLE
Image size in mobile

### ISSUE THREAD

**Issue by NBajanca** [mkdocs/mkdocs#1674]
When I'm using small images (in my case 25px square) it looks great on the Desktop. 
However, when I get my mobile the width goes to 100% and the image is completely distorted. 

The change I see is, in the desktop I don't ``width`` defined in ``img`` css.
In mobile ``img`` css has ``width: 100%;``.

In a mobile, this is applied to the image:

    .rst-content img {
        max-width: 100%;
        height: auto !important;
    }
    img {
        max-width: 100%;
        height: auto;
    }
    @media screen and (max-width: 768px)
    img {
        width: 100%;
        height: auto;
    }

In a desktop:

    .rst-content img {
        max-width: 100%;
        height: auto !important;
    }
    img {
        max-width: 100%;
        height: auto;
    }

Is there something I can do or markdown?
Is this related with read the docs?

**Comment by waylan** [comment]
There are a few ways this might be addressed:

1. If this is an oversight of the theme, then a change to the theme might be warranted. However, the `readthedocs` theme is a clone of the upstream theme, so if it is not addressed upstream, we won't be addressing it here.

2. You could use [theme customization][1] to override the CSS of the theme with your own rules.

3. You could use raw HTML in your Markdown and set the width of an image manually:

        <img width="25px" src="path/to/img.jpg" />

    However, you need to be careful with this. As the documentation [warns][2]:

    > [A]s all raw HTML is ignored by the Markdown parser, MkDocs is not able to validate or convert links contained in raw HTML. When including internal links within raw HTML, you will need to manually format the link appropriately for the rendered document.

In the end, option 2 is probably the best approach.

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme
[2]: https://www.mkdocs.org/user-guide/styling-your-docs.md#customizing-a-theme

**Comment by NBajanca** [comment]
Hello @waylan and thanks for the fast response.

I've searched readthedocs CSS and can't find the code doing this. 

I've tried the second approach, and can't make it work. 

If I do something like the following, all images get 25px width (not the objective!), because I've no way to give classes or ids to images.

    img {
        width: 25px; 
        height: auto;
    }

In the following code sample, nothing changes. Meaning I get ``width:100%".

    img {
        max-width: 100%; 
        height: auto;
    }

I've tried the third approach, and it doesn't work. The attributes get overwritten!

**Comment by waylan** [comment]
> I've tried the third approach, and it doesn't work. The attributes get overwritten!

Ah right. You may need to use `style="width:25px;"` to override a CSS rule.  In any event, you would need to define a new `width`. That is why your attempt at option two is failing. You are not overriding the previously defined `width`. But this is not the correct forum for asking for help with CSS. And I'm not an expert. However, I am certain that with the correct rules, you can get your desired result.

**Comment by NBajanca** [comment]
Yes, you're right. Not the right place, I will post a question on SO and comment here with the answer afterward. By the way, ``style="width:25px;"`` works! I should have remembered that...
Thanks
