### ISSUE TITLE
Error with search option 

### ISSUE THREAD

**Issue by y2kkarthik** [mkdocs/mkdocs#1677]
I am using windmill theme for mkdocs to generate static webpages. Good news is everything works charm as expected however I have an issue with search option.

When I search for any resources the url is changed to http://<domain>#.<key>
Please notice a dot(.) between domain and key which is causing the problem. When I checked search.html,  I could see key is present without dot(.) which is correct

Wondering where an extra dot(.) is getting appended during the search. Any leads on this issue would be highly appreciated

PS: I do not have any fancy configurations in mkdocs.yaml and I have kept very basic

Regards,
Karthik

**Comment by waylan** [comment]
The Winddmill theme re-implements the client side search. Presumably any bugs would be in the theme itself. I would suggest [reporting][1] the issue upstream. For that matter, it appears the the theme has not been updated for MkDocs version 1.0.  You may need to use MkDocs 0.17 with that theme.

[1]: https://github.com/gristlabs/mkdocs-windmill/issues

**Comment by y2kkarthik** [comment]
Thanks for your response. I have reported an issue upstream. Further regarding mkdocs version, I am using pip to install mkdocs. How I enforce to use v0.17?

Regards,
Karthik

**Comment by waylan** [comment]
See the [pip docs][1]:

    pip install mkdocs==0.17

[1]: https://pip.pypa.io/en/stable/user_guide/#installing-packages

**Comment by y2kkarthik** [comment]
Thanks @waylan. Changing mkdocs version to 0.17 fixed the search issue
