### ISSUE TITLE
Is there a way to support image size adjustment? 

### ISSUE THREAD

**Issue by Code-Egg** [mkdocs/mkdocs#1678]
For example  `![](https://example.com/qqq.img =150x150)` works on some markdown platform  but not on mkdocs. 

Or is there any plugin support this? 

Any advice, apprentice.

**Comment by waylan** [comment]
That is a non-standard Markdown feature and is therefore not supported by default. As documented, MkDocs uses the [Python-Markdown][1] library for processing Markdown and [fully supports][2] Python-Markdown [extensions][3]. There may be a [built-in][4] or [third-party][5] extension which offers a solution that works for you, Alternatively, you can [write your own][6] extension, which implements whatever behavior you want.

As Markdown behavior is an upstream issue, I'm closing this.

[1]: https://python-markdown.github.io/
[2]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
[3]: https://python-markdown.github.io/extensions/
[4]: https://python-markdown.github.io/extensions/#officially-supported-extensions
[5]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
[6]: https://python-markdown.github.io/extensions/api/

**Comment by wilhelmer** [comment]
You can use the [attr_list](https://python-markdown.github.io/extensions/attr_list/) extension to achieve this.
Syntax:
`![](https://example.com/qqq.img){: style="height:150px;width:150px"}`

**Comment by Code-Egg** [comment]
Nice, it's a solution.

**Comment by binnyg** [comment]
This isn't working

**Comment by waylan** [comment]
@binnyg did you [enable the extension][1] in your `mkdocs.yml` config file?

[1]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by binnyg** [comment]
I know I am missing something but it worked with the extension. Thank you.
```
markdown_extensions:
  - attr_list
```
