### ISSUE TITLE
Convert internal links always to relative paths

### ISSUE THREAD

**Issue by sander76** [mkdocs/mkdocs#1679]
I know there is a lot discussion about relative vs absolute paths here already, but I don't seem to find my issue here. So here I go:

There are situations where it is convenient to use absolute links inside your markdown document. For example where you have an image folder where you can refer to regardless of where your document is located.

I am pretty sure that MkDocs < 1 converted these link to relative links.
MkDocs 1 does not.
Depending on your server setup (but in my case due to using WeasyPrint to create pdf's) these absolute links can cause errors of the target not being found.

I am not sure there are situations where you *do* want to keep the absolute link, but I am certain in my situation I would really like to have the option to always have my internal links converted to relative links.

**Comment by waylan** [comment]
> I am not sure there are situations where you do want to keep the absolute link

There absolutely are as discussed in #1592, which is why we have the current behavior and will not be changing it.

**Comment by sander76** [comment]
Alright.
