### ISSUE TITLE
How to include sql files in the build process?

### ISSUE THREAD

**Issue by fabiojaniolima** [mkdocs/mkdocs#1683]
How to use MkDocs to generate web pages from SQL files?

My Structure:

  - README.md
  - SQL (dir)
    - file.sql
    -  file2.sql

**Comment by waylan** [comment]
MkDocs only generates pages from Markdown files. Any other documents in the `docs_dir` are copied as-is. And we have no intention of changing that. However, I suppose you may be able to implement something with a plugin.

**Comment by ivishalgandhi** [comment]
i had similar requirement released a plugin for sqlite https://pypi.org/project/mkdocs-sql/
