### ISSUE TITLE
How to include reference-style links from common file

### ISSUE THREAD

**Issue by mloskot** [mkdocs/mkdocs#1686]
_(Originally posted to the mailing list as [Include reference-style links from common file](https://groups.google.com/forum/#!topic/mkdocs/DdH8gEmLsbA))_

I have a chapter1.md file with list of reference-style links at the bottom, e.g.:

```
[git log]: https://git-scm.com/docs/git-log
[git push]: https://git-scm.com/docs/git-push
```

Now, I'd like to have access to those references in `chapter2.md`, ideally, without copying the references.

Is there any way to include the references from a common file in both, `chapter1.md` and `chapter2.md`?
Or, have it pre-configured in `mkdocs.yml` somehow?

While searching around, I've learned there is this markdown-include extension, presumably it's this one https://github.com/cmacmackin/markdown-include.
That sounds good, but all suggestions I found were 2+ years old, and the extension seems not actively maintained.

Is there a more current alternative to solve the inclusion?

**Comment by waylan** [comment]
That sort of thing is a non-standard Markdown feature and is only supported by third party extensions to Markdown. Personally, I am not aware of any extensions except the `markdown-include` one.

**Comment by mloskot** [comment]
I see. Thanks for the answer.
