### ISSUE TITLE
Feature request: Minify HTML output on build

### ISSUE THREAD

**Issue by coliff** [mkdocs/mkdocs#1690]
I'd love the ability to minify the HTML file output when building. The static site generator Hugo has this functionality by running `hugo --minify` from the command line. I'd love to see something similar (`mkdocs build --minify`).

Minifying the HTML means smaller file sizes and faster downloads for users.

**Comment by waylan** [comment]
This sounds like an excellent feature for a plugin.

**Comment by byrnereese** [comment]
I whipped this up for you: https://github.com/byrnereese/mkdocs-minify-plugin

It is very bare bones right now, but it is a start.

**Comment by coliff** [comment]
This is awesome! It works **_exactly_** as I had hoped. I don't consider it 'bare bones' and can't really think of much to improve it. It just works.

I opened a PR for the README. Thanks for creating this. 👍 

I wonder if there should be a suggested/recommended plugins section on the MkDocs site. Neat plugins like this might not get much attention without it.

**Comment by froschdesign** [comment]
@coliff 
> I wonder if there should be a suggested/recommended plugins section on the MkDocs site.

Look at the Wiki: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Comment by wilhelmer** [comment]
Minifying JS files on build is now also possible: https://github.com/wilhelmer/mkdocs-minify-js

**Comment by byrnereese** [comment]
@wilhelmer Would you be interested in merging your plugin with the other minify plugin (maintained by me)? It makes sense that we have a single plugin for all minification needs. We could also allow for the minification of css too.

**Comment by wilhelmer** [comment]
@byrnereese Good idea. I have sent you a PR. If you accept it, I will delete my repo.

**Comment by byrnereese** [comment]
@wilhelmer PR merged. Thank you for such a complete contribution.

**Comment by wilhelmer** [comment]
@byrnereese Could you please merge my second PR? Right now the plugin doesn't work as advertised. Also, I've simplified the code a lot. Thanks!

**Comment by byrnereese** [comment]
@wilhelmer Done. 0.2.1 is now available.
