### ISSUE TITLE
Is it possible to add the same file twice in nav?

### ISSUE THREAD

**Issue by cakrit** [mkdocs/mkdocs#1691]
We saw a strange behavior, when the same file was added twice in the nav section. The second link was great, but the first one was pointing to nothing (label "None" and navigation didn't lead to the directory).
The theme used is Material. It's not important because we don't really need anything like that, but is it a limitation? I haven't found anything related here.

**Comment by waylan** [comment]
The `nav` is simply an iterable which contains references to `Page` instances. There isn't be any reason why a class instance couldn't be referenced in multiple places...

Except that the `Page` instance does contain some navigation specific data. For example, `parent`, `children`, `previous_page`, `next_page`, and `active` are all attributes of the the `Page` instance and can only every be set for a single location within the `nav`. Therefore, it would be impossible to get it to work completely with the current API.

Given that this has never come up before, I'm not inclined to try to support this.

**Comment by cakrit** [comment]
Thanks, I really doubt anyone would need such a feature anyway.
