### ISSUE TITLE
Build throws warnings on 'node_modules' packages readme

### ISSUE THREAD

**Issue by alexandrasoni** [mkdocs/mkdocs#1700]
I have multiple packages installed in mkdocs 'custom_dir', where I also override the base.html, footer.html, etc. I set my 'docs_dir' to use a custom directory, other that 'docs' and the build still goes through 'node_modules' folder. 

Is there any way mkdocs can look at only the 'docs folder' and not 'node_modules'?

**Comment by waylan** [comment]
If you don’t want MkDocs to scan your `node_modules` directory then that directory must not be within the directory pointed at by `docs_dir`. There is no way to “exclude” files or subdirectories within `docs_dir`.

**Comment by alexandrasoni** [comment]
Thanks for the answer! My `node_modules` directory is actually within `custom_dir` under `theme`, not under `docs_dir. Project structure:

```myproject/
├── mkdocs.yml
├── docs
│ └── index.md
│ └── otherpage.md
│ └── ...
├── custom_dir
│ └── base.html
│ └── node_modules
│ └── ...
```
