### ISSUE TITLE
Using custom_dir for theme throws an error

### ISSUE THREAD

**Issue by dimitarsp** [mkdocs/mkdocs#1701]
Hi, I am trying to use the cinder theme from a local directory as opposed to using from the site-packages folder. This is due to the inability to overwrite specific files with the custom_dir option in mkdocs.yml.

I have placed a folder called cinder in the root mkdocs directory and I have included the following in mkdocs.yml as per all the information i could find on the issue:

```
theme:
     name: null
     cutom_dir: 'cinder'
```

I get the following error: 
`ERROR   -  Config value: 'theme'. Error: At least one of 'theme.name' or 'theme.custom_dir' must be defined.`

Just to make sure that it isn't something related to the specific theme, I also tried to use provided custom theme from the mkdocs website: https://github.com/mkdocs/mkdocs-basic-theme. I also get the same error by simply running mkdocs from cmd in the unzipped directory.

**Comment by szpeter80** [comment]
There is a typo, imo it should read "cuStom_dir"

**Comment by dimitarsp** [comment]
@szpeter80 thank you for pointing out the obvious and resolving my issue. This may be the dumbest issue, I've submitted
