### ISSUE TITLE
Google Analytics is not tracking documents site

### ISSUE THREAD

**Issue by virtualdvid** [mkdocs/mkdocs#1702]
I setup google analytics as you show in your documentation:

`google_analytics: ['UA-xxxxxxxx-x', 'hostname']`

Then I used `mkdocs gh-deploy` to deploy the website but google analytics is not tracking the site. To solve this I went to the `index.html` and deleted:

```
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-xxxxxxxxx-x', 'hostname');
    ga('send', 'pageview');
</script>
```

then I used the code that GA provides as the first item into the `<head>`:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxxxxxxxxx-x"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-xxxxxxxxx-x');
</script>
```

It is working now, How can I avoid to replace these lines when I use `mkdocs gh-deploy`?

Thanks!

**Comment by waylan** [comment]
It appears that Google updated their [instructions][1] at some point. I suppose we need to update the templates.

[1]: https://developers.google.com/analytics/devguides/collection/gtagjs/

**Comment by coliff** [comment]
gtag is different to analytics.js. If you don't need to use Google AdWords or Google Optimize or other Google services then using gtag instead is unnecessary. If you use gtag implementation it actually loads analytics.js anyway. The fastest way to implement Google Analytics is with the newer async snippet referenced here: https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet
This is recommended by HTML5 Boilerplate and used by major projects like Bootstrap etc.
I can open a PR for this.

**Comment by vijaypolimeru** [comment]
@virtualdvid How much time it took for Google to track your website or any content in your website

**Comment by virtualdvid** [comment]
@vijaypolimeru that's immediately. Once you setup the code. GA starts tracking your website

**Comment by harelba** [comment]
For anyone interested, I've worked around a similar issue when converting my site to use mkdocs material theme.

I've added the following [main.html](https://github.com/harelba/q/blob/master/mkdocs/theme/main.html) to the a subfolder of `doc/` called `theme`, and added `"custom_dir: 'theme'` to the mkdocs.yml file under the theme key.

You can also see examples of sending GA events in this [JS file](https://github.com/harelba/q/blob/master/mkdocs/docs/js/google-analytics.js). I've added this file in mkdocs.yml under `extra_javascript`.

Hope this can help

**Comment by sorenwacker** [comment]
To have that working a certain theme has to be used??

**Comment by virtualdvid** [comment]
It's been years since I worked on a project that uses google analytics.
