### ISSUE TITLE
Partial word search only works it we search the start of the word, not the end

### ISSUE THREAD

**Issue by NicolasMassart** [mkdocs/mkdocs#1704]
Hi, here's my setup:
- Mkdocs 1.0.4
- Theme Material form https://github.com/squidfunk/mkdocs-material
- Hosting on readthedocs.com at https://pantheon.readthedocs.io

**Issue** : when using the search box, if we look for pages containing the word "eth_sendRawTransaction" by searching "eth_send" it will find results however, if we search with "RawTransaction" no result is displayed even if we have pages with words containing this substring.

**Expected behaviour:** any part of a word may be used as a search string even if the start or end is missing.

**Current behaviour:** we can only search word either by the exact word or by a substring containing the beginning of the searched word.

Thanks for your help.
Nicolas.

**Comment by martinbira** [comment]
Not sure that this issue is directly related to MkDocs but rather [Lunr.js](https://github.com/olivernn/lunr.js) or [Material for MkDocs](https://github.com/squidfunk/mkdocs-material).

**Comment by waylan** [comment]
MkDocs uses [Lunr.js][1] for search. By Default, Lunr.js defaults to using whitespace and hyphens as word separators, however, you can customize that behavior by setting the [plugin.search.separator][2] config setting. For example, to use the underscore as an additional separator:

```yml
plugins:
    - search:
        separator: '[\s\-\_]+'
```

However, be aware that the Material theme reimplements much of the search plugin itself and may behave differently as explained in its [documentation][3]. For example, it appears to use the `extra.search.tokenizer` setting to define word separators.

Given the above, you should probably report any search issues with the Material Theme, to the [Material theme project][4]. I'm closing this as an upstream issue.

[1]: https://github.com/olivernn/lunr.js
[2]: https://www.mkdocs.org/user-guide/configuration/#separator
[3]: https://squidfunk.github.io/mkdocs-material/getting-started/#site-search
[4]: https://github.com/squidfunk/mkdocs-material/issues

**Comment by NicolasMassart** [comment]
Thanks. I will do that.
