### ISSUE TITLE
Need a way to access the path to a file via plugin hook

### ISSUE THREAD

**Issue by byrnereese** [mkdocs/mkdocs#1708]
I am the author of a new plugin: git-committers

My plugin has the need to be able to determine the path to the file being rendered within the `on_page_context` hook.

Right now I have a special function to help find the current page in the tree, and from that determine the actual file path. I then use this path to look up the files commit history in github. 

It would be ideal if the path to the file being rendered was passed to the hook. For example:

```
    def on_page_context(self, context, page, config, nav):
        if not self.enabled:
            return context
        file_name = context['file_path']
        // do my stuff
```

One downside of my current approach is that any file that is not found within the nav tree is skipped by my plugin, which is not desirable. 

I can see the value of a number of paths being made available to the template:

```
page_context = {
   file_path: 'docs/some_dir/index.md',
   file_path_abs: '/home/user/projects/my_docs_prjk/docs/some_dir/index.md',
   nav: { .... },
   // etc
}
```

**Comment by waylan** [comment]
The [page][1] object has everything you need under the [page.file][2] attribute, which points at an instance of the [File][3] class. As the doc-string for that class states:

```
 File objects have the following properties, which are Unicode strings:

    File.src_path
        The pure path of the source file relative to the source directory.

    File.abs_src_path
        The absolute concrete path of the source file.

    File.dest_path
        The pure path of the destination file relative to the destination directory.

    File.abs_dest_path
        The absolute concrete path of the destination file.

    File.url
        The url of the destination file relative to the destination directory as a string.
```

Therefore `page.file.src_path` and `page.file.abs_src_path` should get you what you want.

Unfortunately, much of this stuff has not yet been documented yet, You need to go spelunking in the source code. Improving this documentation is part of #1629.

> One downside of my current approach is that any file that is not found within the nav tree is skipped by my plugin, which is not desirable.

That should not be happening. The "page" events should be called on all rendered Markdown pages, not just pages listed in the nav. If you can provide a minimal, verifiable, reproducible example, then we may have a bug.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/pages.py#L22
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/pages.py#L25
[3]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/files.py#L85

**Comment by byrnereese** [comment]
This worked wonderfully. Thank you.
