### ISSUE TITLE
are sphinx themes also mkdocs themes?

### ISSUE THREAD

**Issue by simkimsia** [mkdocs/mkdocs#1710]
I found http://www.writethedocs.org/guide/tools/sphinx-themes/ and I saw that guzzle theme is not on the wiki for mkdocs theme.

Can i check if guzzle is also a mkdocs theme?

**Comment by waylan** [comment]
> are sphinx themes also mkdocs themes?

No.

A few Sphinx themes have been cloned as MkDocs themes, but that requires a lot of work. The CSS and JS can usually be uses as-is, but the HTML templates would need to be completely recreated from scratch.

**Comment by simkimsia** [comment]
Thanks for answering @waylan
