### ISSUE TITLE
Generate hyperlinks for bare URLs

### ISSUE THREAD

**Issue by ryantuck** [mkdocs/mkdocs#1711]
Apologies if this is a duplicate, but I can't find any existing issue that addresses this.

GitHub will generate a hyperlink from a bare URL that I have in my markdown. I'd like for mkdocs to be able to do the same.

For example, if my markdown contents look like:

```
To find stuff online, go to https://google.com
```

I would expect it to render like so:

To find stuff online, go to https://google.com

Currently, mkdocs does not appear to do this, and instead simply treats that URL as just text.

**Is there a flag I could set in `mkdocs.yml` that would allow for hyperlink generation from bare URLs?**

**Comment by ryantuck** [comment]
I did just discover [in the markdown spec](https://daringfireball.net/projects/markdown/syntax#autolink) that markdown has specific syntax for automatic links, implemented like so:

```
To find stuff online, go to <https://google.com>
```

For what it's worth, I'd still love to see bare links be supported. It looks like `python-markdown` [does not support it](https://github.com/Python-Markdown/markdown/issues/678), but the [MagicLink](https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/) extension does.

**Comment by waylan** [comment]
You are correct, Markdown does not support plain text links unless they are wrapped in angle brackets. You will need to install and [enable][1] a third party extension to get such a feature. As MkDocs fully supports using third-party Markdown extensions, there is no further action for us to take.

[1]: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by MasterScrat** [comment]
FYI the relevant Markdown extension would be PyMdown  MagicLink:

https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/

**Comment by johan456789** [comment]
Setting to enable MagicLink in mkdocs is
```yaml
markdown_extensions:
  - pymdownx.magiclink
```
