### ISSUE TITLE
Add flag for external links to open in new tabs

### ISSUE THREAD

**Issue by ryantuck** [mkdocs/mkdocs#1712]
I'd like to be able to set a flag in `mkdocs.yml` (or have this be default behavior) to open external links in new tabs, like so:

```
open_external_links_in_new_tab: true
```

I imagine this may require use of a `python-markdown` extension, though it's not obvious on first glance that one currently exists.

First off, does this already exist (assuming it doesn't)?

If I were to write an extension, would the maintainers be open to implementing this as an optional feature?

**Comment by waylan** [comment]
You are correct that this would need to be implemented as a Markdown extension. As you can [include any third-party extension][1] in MkDocs already, there are no changes necessary for it to work.

Note that as a general rule, we will not consider any requests to change Markdown behavior in MkDocs. All such requests will be denied. Any changes to the Markdown parser should be directed upstream to the Python-Markdown project and any extensions can be developed separately from either project. Therefore, we don't need to make any changes to MkDocs to support your desired features.

[1]: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions
