### ISSUE TITLE
livereload broken with LiveReload 2.6.0

### ISSUE THREAD

**Issue by gu1ll0me** [mkdocs/mkdocs#1722]
mkdocs version: 1.0.4

LiveReload 2.6.0 "[changes logic of live port](https://github.com/lepture/python-livereload/blob/master/CHANGES.rst)".

With 2.5.2, my browser try to get this URL: `https://.../livereload.js?port=5509`

With 2.6.0: `https://.../livereload.js?port=`. The port is missing.

**Comment by waylan** [comment]
Thanks for the report. I'm assuming this is related to lepture/python-livereload@ba2152c5 but I'm not certain. Further investigation is required.

**Comment by oprypin** [comment]
This became obsolete because this entire part of the implementation was replaced.
