### ISSUE TITLE
support various source code in addition to markdown file

### ISSUE THREAD

**Issue by laoshaw** [mkdocs/mkdocs#1725]
mkdocs is great to deal with markdowns, for developers we sometimes have source code mixed with md files, say a github repo that has many md files and source code, can mkdocs convert those source code their a syntax-highligted version of html, so we can browser markdown and source code together?

even better, if it detects a html, it shall treat that as a html just generated.

then we can have a truly great tool that deals with markdown, html and source-code files.

**Comment by waylan** [comment]
This sort of feature should be implemented via a plugin. In fact, as you can see in #206, one of the primary motivations for starting work on the Plugin API was this sort of feature.
