### ISSUE TITLE
AttributeError: 'list' object has no attribute 'children'

### ISSUE THREAD

**Issue by www0488** [mkdocs/mkdocs#1727]
Steps:

1. Input command mkdocs build --theme rtd-dropdown

2. Message received "AttributeError: ' list' object has no attribute 'children' "

Then I tried to change back to mkdocs by command Input command mkdocs build --theme mkdocs but it did not worked well.

My goal is to make an outlines sidebar, how can I do it in other option?

**Comment by www0488** [comment]
Problem solved! But now I'm facing a new issue. Right now I'm using the mkdoc theme rtd-dropdown and I can only make up to maximum 6 "#", is there any chance I can change the "#" limitation up to like 10? Do I need to edit the custom Theme file?

**Comment by waylan** [comment]
The `rtd-dropdown` theme is a third party theme which we have no affiliation with. Please take this issue upstream tot he developers of that theme.
