### ISSUE TITLE
Wrong language codes

### ISSUE THREAD

**Issue by cocoatomo** [mkdocs/mkdocs#1729]
The language code list at [lang section](https://www.mkdocs.org/user-guide/configuration/#lang) contains two errors.

`du: Dutch` should be `nl: Dutch` and `jp: Japanese` should be `ja: Japanese`.

ref. https://www.loc.gov/standards/iso639-2/php/English_list.php

**Comment by waylan** [comment]
The abbreviations we use are the abbreviations supported by [Lunr Languages][1]. As it turns out, Lunr Language treats `ja` and `jp` as aliases, so we could change that. However, they use `da`, but not `nl`. There is nothing we can do to change that. I would suggest reporting the issue upstream.

[1]: https://github.com/MihaiValentin/lunr-languages

**Comment by trel** [comment]
filed nearly a year ago - https://github.com/MihaiValentin/lunr-languages/issues/43

**Comment by cocoatomo** [comment]
Thank you for your comments. I understand where language names are come from.
I will take action on lunr-languages repository.

**Comment by cocoatomo** [comment]
I submitted the PR to lunr-languages.
https://github.com/MihaiValentin/lunr-languages/pull/50

**Comment by cocoatomo** [comment]
My PR is closed, but MihaiValentin created more appropreate diff and commited it to resolve the issue.

**Comment by waylan** [comment]
Thanks for the update. For reference, the relevant change was made in 
MihaiValentin/lunr-languages@b38058e1c, which appears to be included in the now released version 1.1.0 of lunr-languages. A PR is welcome here to update MkDocs to use the updated version along with the newly corrected language code.

**Comment by backtrackbaba** [comment]
@waylan  If nobody has taken this up I'd like to give this a try!

**Comment by jimporter** [comment]
Assuming this is still open by the time I finish fixing #770, I'm going to take this and fix it so we can close out the 1.1 milestone. If someone else wants to work on this though, feel free to take it!

**Comment by waylan** [comment]
@jimporter feel free to take this. Then we can release version 1.1.

**Comment by ofek** [comment]
I'm very excited for the next release!
