### ISSUE TITLE
GitHub reports security vulnerability in pyyaml, recommends >=4.2b1

### ISSUE THREAD

**Issue by SueChaplain** [mkdocs/mkdocs#1730]
We are currently a little backlevel, using pyyaml 3.12 as required by MkDocs 1.0.4, but it looks like we won't fix this by moving to the latest MkDocs level.

Are there plans to update dependencies? 
Can anyone confirm whether upgrading just pyyaml >=4.2b1 causes any problems please?

**Comment by waylan** [comment]
I'm not aware of any version of PyYAML greater than 3.13 (with a release date of 2018-07-05) as listed [here][1]. And we specificly support for `pyyaml>=3.12` so the only restriction is that older versions are not supported. However, we will accept any newer version. Could you provide some more information about this "recommendation"?

Or is this perhaps a duplicate of #1529? If so, I would recommend ignoring the warning for the reasons stated in that issue.

[1]: https://pyyaml.org/

**Comment by facelessuser** [comment]
As for whether upgrade will cause problems, if you are relying on the MkDocs ability to run arbitrary Python code, then it might break for you if it is indeed using the "safe" load by default now.

**Comment by SueChaplain** [comment]
Thanks everyone for your comments. I'll watch the PyYAML project and MkDocs project and pick up later levels when they are ready.
