### ISSUE TITLE
pandoc rendering

### ISSUE THREAD

**Issue by jacob-vintercapital** [mkdocs/mkdocs#1732]
I write in a markdown file where I mix in some latex syntax. I export the file using pandoc to .pdf and .html and it looks great (for example -- is converted to em-dash; and \pagebreak is rendered in the pdf but not in the HTML; and I can use math like $e^2$ or even pandog-fignos to get nice captions on my figures). However, when the same markdown files are used in mkdocs the pandoc commands the sntax is ugly (for example \pagebreak is left as is, and the pandog-fignos is clearly not supported).

I tried to make a workaround where I go from .md to .html via pandoc and then point to the .html files in my mkdocs YAML file. But then the HTML did not render according to the styling provided by mkdocs.

**Comment by mitya57** [comment]
You will need to enable some math extension in your mkdocs.yml, such as [pymdownx.arithmatex](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/) (or one of the extensions listed in the [wiki](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#math--latex)).

Please see arithmatex’ documentation — you will also need to alter your template to add loading of MathJax.js and a configuration block for it.

**Comment by waylan** [comment]
> \pagebreak is left as is, and the pandog-fignos is clearly not supported

Those are non-standard Markdown features which are not supported by most markdown implementations. As @mitya57 mentions, you can use MathJax to enable math support.

For complete documentation on what MkDocs supports see the [Writing with Markdown][1] section of the docs.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown
