### ISSUE TITLE
documentation error: pages not list of page objects, but of file objects

### ISSUE THREAD

**Issue by rkoe** [mkdocs/mkdocs#1736]
The documentation about "pages" on https://www.mkdocs.org/user-guide/custom-themes/ is wrong.
It says:

> pages
> A list of page objects including all pages in the project.

But in reality, pages is a list of file-objects, which also contain the page objects.
The page-object can be accessed by pages[i].page.

**Comment by waylan** [comment]
The documentation is correct in that it describes the expected behavior. If the `pages` template variable does not actually contain what is described, then that is a bug. Thanks for the report.

**Comment by fhiegel** [comment]
It seems that "pages" are file-object. I tried to use the "pages" collection on my project :

**Using pages as page-objects :**
```jinja
<h3>Pages</h3>
<ul>
  {% for item in pages %}
  <li>{{ item.title }}</li>
  {% endfor %}
</ul>
```
**Output :**
![image](https://user-images.githubusercontent.com/7289459/109068518-42cea680-76f0-11eb-9445-8da0dcc63973.png)

**Using pages as file-objects :**
```jinja
<h3>Pages</h3>
<ul>
  {% for item in pages %}
  <li>{{ item.page.title }}</li>
  {% endfor %}
</ul>
```
**Output :**
![image](https://user-images.githubusercontent.com/7289459/109068705-84f7e800-76f0-11eb-8b83-051cc6049598.png)

Using MkDocs on windows with "serve" command with version :
```shell
mkdocs, version 1.1.2 from [...]\Python39\site-packages\mkdocs (Python 3.9)
```

**Comment by waylan** [comment]
After reviewing the code, yes the documentation is wrong. There is no "pages" collection. It seems the variable name was poorly chosen. Perhaps we should alias it as `files`. Also, it appears that we don't actually document `File` objects, which we should do.

**Comment by waylan** [comment]
Took another look at this. The name `pages` is correct as the list only contains `File` objects for pages. Other types of files are not included. However, the documentation is misleading.
