### ISSUE TITLE
Hidden directories are not working in static_templates

### ISSUE THREAD

**Issue by gabriel-naressi** [mkdocs/mkdocs#1738]
I am uploading a mkdocs site to Gitlab Pages with CI building and publication process.

Now I wish to use my own domain with SSL enabled with a Let's Encrypt certificate following this tutorial:
https://about.gitlab.com/2016/04/11/tutorial-securing-your-gitlab-pages-with-tls-and-letsencrypt/

But I need to create a fixed html page under .well-known/ folder to enable Let's Encrypt verify my domain, and I have not found how to do it with mkdocs. When I try to expose a .directory, a can't retrieve my index.html page:

![image](https://user-images.githubusercontent.com/13473807/52221675-cfe40000-2888-11e9-9f68-09eafdf25204.png)

My config in mkdocs.yml is:

```
static_templates:
    - .teste/index.html
```
It is possible to create a html page in a "hidden" directory with mkdocs?

**Comment by waylan** [comment]
No, MkDocs ignores all dot file/directory names. In other words, if a filename or directory name within your `docs_dir` begins with a dot, MkDocs will not copy it to your site.

However, this should be overridable with a plugin. If the given path is a common one, a third party plugin may make sense for many users.

**Comment by gabriel-naressi** [comment]
@waylan what plugin?

**Comment by waylan** [comment]
I'm not aware of any existing plugin. One would need to be developed. I was pointing out that such a plugin, if it was developed, might have a wide appeal. For more information on plugins, see the [documentation][1], as well as a [list of known plugins][2].

[1]: https://www.mkdocs.org/user-guide/plugins/
[2]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Comment by snim2** [comment]
@waylan would it be easier to write a plugin or to patch `mkdocs`? This is a real blocker for me, so I'd be interested in working on this...

**Comment by waylan** [comment]
We will not be patching MkDocs. This is an intended design decision. I suspect a plugin would be very simple for this sort of feature.

**Comment by snim2** [comment]
Ok, thanks.

**Comment by snim2** [comment]
OK, since we had this discussion, GitLab (where my MkDocs site is hosted) has brought out a feature where they will register and serve an SSL cert for you, which means that I won't need the extra plugin. 

@gabriel-naressi if you are in the same situation, just go to **Settings->Pages** in your GitLab repo and the new features are obvious and [well documented](https://gitlab.com/help/user/project/pages/custom_domains_ssl_tls_certification/lets_encrypt_integration.md).

**Comment by gabriel-naressi** [comment]
@snim2 I haven't seem this feature before. GitLab is where my site is hosted too, so everything works well for me.

**Comment by gabriel-naressi** [comment]
@snim2 thank you so much 🖤
