### ISSUE TITLE
Config value: 'plugins'. Error: The "jekyll-redirect-from" plugin is not installed

### ISSUE THREAD

**Issue by barreeeiroo** [mkdocs/mkdocs#1743]
When building MKDocs with jekyll-redirect-from plugin, it fails and returns the following error:

`ERROR   -  Config value: 'plugins'. Error: The "jekyll-redirect-from" plugin is not installed`

Repository is public, so you can check there `_config.yml` and `mkdocs.yml`: https://github.com/Kodular/Documentation
Also, builds are done by Travis, which can be found here: https://travis-ci.com/Kodular/Documentation

**Comment by waylan** [comment]
Is `jekyll-redirect-from` an "MkDocs" plugin which registers itself as a Python entry point under the  `mkdocs` namespace? If not, then MkDocs will never recognize it as a plugin. MkDocs certainly does not recognize or work with Jekyll plugins.

**Comment by barreeeiroo** [comment]
I don't think so
I have just removed it, as we can live without it
