### ISSUE TITLE
search failed with `</head>`  in one file

### ISSUE THREAD

**Issue by AllanChain** [mkdocs/mkdocs#1744]
I am using mkdocs 1.0.4 and when I run `mkdocs serve`, it constantly (the last time I tested, five times when just opening the index page and searching) prints out the following exception.
```
Uncaught exception GET /search/search_index.json (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/search/search_index.json', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tornado/web.py", line 2528, in get
        yield self.flush()
File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tornado/web.py", line 994, in flush
        start_line, self._headers, chunk, callback=callback)
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tornado/http1connection.py", line 412, in write_headers
        data += self._format_chunk(chunk)
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tornado/http1connection.py", line 424, in _format_chunk
        "Tried to write more data than Content-Length")
    tornado.httputil.HTTPOutputError: Tried to write more data than Content-Length
```
And I find out that it is because I have a `</head>` tag in one file and **it is** back quoted.

How should I include a `</head>` tag or could you fix that?

**Comment by waylan** [comment]
Can you provide a minimal example of the Markdown content which is causing this error?

**Comment by AllanChain** [comment]
Quite simple test:

- test/
    - docs/
        - index.md (with a title and a back quoted `</head>`)
        - b.md (just a title)
    - mkdocs.yml (just site_name)

**Comment by waylan** [comment]
Sorry, but you didn't answer my question. I'm still left to guess the content of your `index.md` file. It is perhaps this:

```md
# Page Title

</head>
```

or

```md
# Page Title</head>
```

Or at least some variation thereof?

Either way, I should point out that that will result will be invalid HTML. Note that the Markdown parser does not validate raw HTML. It is the document authors responsibility to ensure all raw HTML is valid. Given this results in invalid HTML, I'm fine with an error being raised as it forces you to fix the HTML to make it valid.

**Comment by AllanChain** [comment]
Sorry, I should be more specific.
```
# Title
`</head>`
```
And it displayed well when opening the page.

I think it is the right way to include the tag by using ` `` `

**Comment by waylan** [comment]
Hmm, I can't seem to reproduce the error.

```bash
$ mkdir test
$ cd test
$ mkdir docs
$ echo 'site_name: Foo' >> mkdocs.yml
$ echo "# Page title
\`</head>\`" >> docs/index.md
$ echo "# Other Title" >> docs/b.md
$ mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/waylan/Code/test/site
INFO    -  Documentation built in 0.17 seconds
$ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Documentation built in 0.11 seconds
[I 190209 22:15:49 server:283] Serving on http://127.0.0.1:8000
INFO    -  Serving on http://127.0.0.1:8000
[I 190209 22:15:49 handlers:60] Start watching changes
INFO    -  Start watching changes
[I 190209 22:15:49 handlers:62] Start detecting changes
INFO    -  Start detecting changes
```

If you remove `` `</head>` `` from the document, does the error go away?

**Comment by AllanChain** [comment]
Yes, error goes away when `</head>` removed.

I've tested on Anaconda and the same error appeared.

That's strange. Does things like system language setting matter? (it is said that it "does not currently include support for Chinese or other Asian languages")

**Comment by waylan** [comment]
I thought I remembered see the `tornado.httputil.HTTPOutputError: Tried to write more data than Content-Length` error before, and in fact, it was reported in #1351, albeit for a different file. In that case the problem was related to a third party JS library, while in this case it appears to be related to the MkDocs generated search index. Therefore, that report doesn't appear to be of much help.

As I can't replicate the error personally, it is not clear to me what is causing the problem. It occurs to me it could be any one of the following:

1. A bug in the live-reload and/or tornado server, which should be reported upstream. You might want to try running `mkdocs serve --no-livereload` and see if the error persists.
2. A configuration error or dependency version mismatch in @AllanChain's environment. I would suggest creating a new clean virtualenv, installing MkDocs and then trying to run `mkdocs serve` on the project and see if the error occurs. If not, then this is your problem.
3. A bug in MkDocs' search index creation code. But why can't I reproduce it? In my attempt above, I even tested search and it worked fine with `` `</head>` `` in a page. I could even get search results for "head" which pointed at the appropriate section of the appropriate page. My best guess is that `` `</head>` `` is a red-herring and the real problem is either 1 or 2.

**Comment by AllanChain** [comment]
It seems like by using `--no-livereload`, the error goes away but WARNING appeared.
And tested in a virtualenv, the error is still there.

Maybe it is a bug in livereload, though I can not figure out why it is different on different computers.

**Comment by waylan** [comment]
Based on the paths in the error message, I'm assuming you are on some Linux distribution. I have tested on Mac and Windows. And given the error, my guess is that whatever distribution you are using is reporting the file size in some way that is tripping up the server. IIRC, the server asks the OS for the file size of a file to include in the responce headers. Then, if the actual size of the file differs when actually reading and serving the file, the error/warning is raised. But I don't know what `` `</head>` ``has to do with that.

Another test might be to build, but not serve with MkDocs (`mkdocs build`), then use [python-livereload][1] directly to serve the built site and see if the error occurs then.

[1]: https://github.com/lepture/python-livereload

**Comment by AllanChain** [comment]
I built the site and served with livereload and problem is still there.

After built, I was able to see `search_index.json`, which has `</head>` in it. And that is the problem according to the message.
```
{"config":{"lang":["en"],"prebuild_index":false,"separator":"[\\s\\-]+"},"docs":[{"location":"","text":"fgg","title":"fgg"},{"location":"#fgg","text":"","title":"fgg"},{"location":"b/","text":"Page title </head>","title":"Page title"},{"location":"b/#page-title","text":"</head>","title":"Page title"}]}
```

**Comment by waylan** [comment]
So, I checked the contents of the `search_index.json` file in my testing and I get (in relevant part):

```
{"location":"b/","text":"Page title /head","title":"Page title"}
```

Notice that the angle brackets are stripped out (`/head`). Whereas @AllanChain is getting the angle brackets included (`</head>`). But the search index is supposed to strip out angle brackets for each entry in the index. And that uses Python's standard library HTMLParser.

Which version of Python are you using? It occurs to me that HTMLParser can differ from version to version and as your `</head`> is invalid HTML, it could be confusing things in your version.

Although, the HTML content of the page should contain `<p><code>&lt;/head&gt;</code></p>`, so there are no angle brackets to remove. Can you confirm the "content" of the built page in `site` actually contains the correct output from Markdown.

**Comment by AllanChain** [comment]
As shown in the error message above, I am using python3.7

And content in `index.html` is correct.

**Comment by oprypin** [comment]
Could you please try if this issue reproduces now?
(I'd try myself, but I see that even previously it was not reliably reproducible.)

If not, I'd guess that so much has changed that this became obsolete.

**Comment by AllanChain** [comment]
`mkdocs==1.2.1` is not having this issue. And `mkdocs==1.0.4` is still having the same issue under my new environment. So I can confirm that the issue has been fixed.
