### ISSUE TITLE
Automatic nav not working properly

### ISSUE THREAD

**Issue by rajanasrallah** [mkdocs/mkdocs#1746]
Hi,
I'have the following docs folder structure
docs/
    index.md
    global-npm.md
    wing-extensions.md
    landspaces/
        README.md
        stable.md
When I launch the site with mkdocs server and the click on wing-extension it added to browser url
http://127.0.0.1:8000/wing-extensions/
Now if I click on global-npm it also added to url like this
http://127.0.0.1:8000/wing-extensions/global-npm.md instead of http://127.0.0.1:8000/global-npm.md

Regards,
Raja

**Comment by froschdesign** [comment]
@rajanasrallah 
Do you work with a custom template? If so, please look in the documentation. There you will find a template filter that describe your problem: https://www.mkdocs.org/user-guide/custom-themes/#template-filters

**Comment by rajanasrallah** [comment]
@froschdesign 
Yes, I'm using meterial theme.

**Comment by froschdesign** [comment]
@rajanasrallah 
> …I'm using meterial theme.

You mean the "[Material for MkDocs](https://github.com/squidfunk/mkdocs-material)" theme? That's not a custom theme and the filter is already used there.

Example: https://github.com/squidfunk/mkdocs-material/blob/163438a425d17e4156d95d6eeaf92588c80e1398/material/partials/nav.html#L3

Which version of the material theme do you use?

**Comment by rajanasrallah** [comment]
@froschdesign 

Yes, the version is 2.0.4

**Comment by froschdesign** [comment]
@rajanasrallah 
You must update the template to version 3.x, otherwise you can not use it with the current version of MkDocs 1.x.

**Comment by waylan** [comment]
I am closing this as an upstream issue. @froschdesign  please follow up with [squidfunk/mkdocs-material](https://github.com/squidfunk/mkdocs-material).

**Comment by rajanasrallah** [comment]
@froschdesign 
After upgrading to verion 3.0.1, it works fine
