### ISSUE TITLE
directory browsing

### ISSUE THREAD

**Issue by tomkralidis** [mkdocs/mkdocs#1747]
Using 1.0.4, I'm putting together a website/documentation using mkdocs, great project! I'm migrating part of a site which includes a directory tree of PDF files.  Does mkdocs allow for making these directories browseable?  This would save me from writing Markdown traversing the entire tree.

**Comment by waylan** [comment]
No, this is not something MkDocs provides out-of-the-box. Although I would imagine a [custom plugin][1] should be able to accomplish this. I suppose a custom Markdown [extension][2] would be another way to address this.

[1]: https://www.mkdocs.org/user-guide/plugins/#developing-plugins
[2]: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions
