### ISSUE TITLE
Imagines showing locally but not online

### ISSUE THREAD

**Issue by lrdegeest** [mkdocs/mkdocs#1750]
I am trying to build a site for my course using mkdocs (https://suffolkecon.github.io/tech-support/). When I build locally using `mkdocs serve`, all images are where they should be. But when I push to Github, most images do not appear, while some do.  

Even though the site is a project site (user.github.io/project), I can only build the site using `mkdocs gh-deploy --remote-branch master`, even though the instructions (https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages), as I understand them, suggest one only needs to run `mkdocs gh-deploy`. 

Lots of other weird things. For instance, when I click "home", it takes me to one of the subpages, not "home" (https://suffolkecon.github.io/tech-support/), which is specified in the yml. 

Any idea why *some* images might not be showing? So far as I can tell, all the paths are correct. I notice that many images do not appear in the "site" folder after building, but I have no idea why.

**Comment by waylan** [comment]
> Even though the site is a project site (user.github.io/project), I can only build the site using `mkdocs gh-deploy --remote-branch master`, even though the instructions (https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages), as I understand them, suggest one only needs to run `mkdocs gh-deploy`.

You understood correctly. In fact, by deploying to your master branch, you removed the source files and now only have the built site. In other words, you broke your own project, which I suspect the problem. The source files are contained in the `master` branch, while the deployed files belong in the `gh-pages` branch. You might want to make sure your settings on Github point to the correct branch for GitHub Pages.

**Comment by lrdegeest** [comment]
Sorry but I really do not understand how the `master` and `gh-pages` branch are supposed to play together. 

According to GitHub the site is hosted from `gh-pages`:

<img width="672" alt="screen shot 2019-02-17 at 10 51 19 am" src="https://user-images.githubusercontent.com/10857097/52915616-5bf02180-32a4-11e9-95aa-ea3f96f13f6a.png">

In my `master` branch I have all the source files:

<img width="691" alt="screen shot 2019-02-17 at 11 02 24 am" src="https://user-images.githubusercontent.com/10857097/52915626-775b2c80-32a4-11e9-932e-82c2791f20c9.png">

and then I run `mkdocs gh-deploy` from inside the `master` branch:

<img width="909" alt="screen shot 2019-02-17 at 11 02 52 am" src="https://user-images.githubusercontent.com/10857097/52915632-8e9a1a00-32a4-11e9-8412-6d412a223ba4.png">

but it does not work. 

What vexes me are the mkdocs instructions: 

<img width="857" alt="screen shot 2019-02-17 at 10 49 04 am" src="https://user-images.githubusercontent.com/10857097/52915644-a7a2cb00-32a4-11e9-8fd3-184eceb8548d.png">

specifically "After you checkout the primary working branch (usually master)..." Am I not supposed to run `gh-deploy` from `master`?

**Comment by SuffolkEcon** [comment]
The more I read your comment the less I understand it. Why exactly does deploying to the `master` delete the source files? What exactly are "source" versus "deployed" files? Because for this project, everything that is in `master` *is* the project and documentation, all in one. It began by cloning a copy of the Material theme, updating it with my content, and then trying to host it on Github.

**Comment by lrdegeest** [comment]
I just tried a fresh start. I forked a copy of the Material theme's github repository, cloned it locally, and ran `mkdocs gh-deploy`. Says a site is built, but still nothing. Can you provide some very basic pointers to get started? Because this is baffling.

**Comment by lrdegeest** [comment]
Started from scratch and got it to work. In case anyone else runs into the same issue, jere is what I did: 

1. Make empty repository on Github
2. Clone to laptop
3. Add all source files
4. Run `git add`, `git commit`, `git push`
5. Run `mkdocs gh-pages`
6. Go to repository settings on Github and change page hosting to `gh-pages`
7. Refresh webpage

All this was done from the `master` branch - I never once worked in the `gh-pages` branch. 

Not sure if my procedure was correct form, but it was the only way I could get the site to work.

**Comment by waylan** [comment]
Glad you figured it out. The important thing to remember is that GitHub's documentation is written from the perspective of someone who is using the builtin Jekyll engine. In that case, you would push the "source" files to the gh-pages branch and then GitHub would run those through Jekyll and deploy to the site. However, when using MkDocs you push the already built site to `gh-pages` and the "source" files are on the `master` branch.
