### ISSUE TITLE
Collapsable bullets inside markdown are not working when installing with pip

### ISSUE THREAD

**Issue by cloud-rocket** [mkdocs/mkdocs#1751]
I am trying to use collapsible bullets inside my page:

<details>
  <summary>Click to expand!</summary>
  
  ## Heading
  1. A numbered
  2. list
     * With some
     * Sub bullets
</details>

For some reason this is working when installing mkdocs from Ubuntu repo (`apt install mkdocs`) which installs version 0.16.3, but it is not working when install mkdocs with `pip install mkdocs` (I tried both versions 0.16.3 and 2.0.3. I am using default theme in both cases.

When installing with PIP - the characters inside the bullet are displayed as-is (markdown) and not parsed. 

Any ideas?
Tnx

**Comment by waylan** [comment]
I'm not aware that MkDocs does or ever has supported collapsible bullets.

> the characters inside the bullet are displayed as-is (markdown) and not parsed.

This sounds like a Markdown issue which should be taken upstream. However, you did not provide enough information to be sure. At a minimum, you need to provide the Markdown source, the actual HTML generated, and the HTML you expected. All three must be as text in code blocks (no screenshots, etc).

**Comment by facelessuser** [comment]
It may simply be that Markdown is treating those HTML elements as block; therefore, it will not parse the content inside without using something like the `extra` extension: https://python-markdown.github.io/extensions/extra/#python-markdown-extra.

Additionally, you could use an extension to handle them, I have an extension that treats them similar to admonitions: https://facelessuser.github.io/pymdown-extensions/extensions/details/. Keep in mind, the document has them styled as that is how the Material theme does them, but you can have simple styling like GitHub as well.

The problem with details in general is that not all browsers support them, so you may need to use a polyfill if your theme doesn't already provide one. 

Anyways, I would look into either the Python Markdown built in `extra` extension or the `details` extension. But you might need an additional polyfill for your theme as well if it doesn't handle them in all browsers.

**Comment by waylan** [comment]
> It may simply be that Markdown is treating those HTML elements as block

I expect this is probably the case, but without more information, I can't be sure.

In any event, this seems to be an upstream issue, so I'm closing it.
