### ISSUE TITLE
Pages deprecated but ability to generate YAML gone?

### ISSUE THREAD

**Issue by DutchessNicole** [mkdocs/mkdocs#1752]
Hi,

I'm working on a document storage solution where we want to create subsections of our total document collection.
The reason for this is that we only want to generate certain parts of our documents for various use cases: End users can only see one part, admins another part and developers everything.

I've found a plugin (https://pypi.org/project/mkdocs-exclude/) that excludes certain files (based on regexes or globbing) from the build process, however it doesn't also trim the navigation section. This means that it leaves dangling links to files that are not physically there.

I've tried to get the plugin developer to change the functionality so that it also removes the nav sections that are taken out while the build happens, but they refused to do so.

So now I'm trying to work on a different solution, where I add a script that generates the navigation section on the fly. I'll run that when the CI pipeline fires, it generates the navigation for us and that then gets built.

Two problems with this are:
the mkdocs.yml becomes useless for development, as the navigation section needs to include a placeholder that is eventually replaced with the navigation structure:
```
nav:
  placeholder
```
Of course the mkdocs serve command will choke here.
One way to work around this is to have a commented nav line that is replaced, however that does mean that the dev server view no longer looks like the actual built pages.

Second:
Creating the yaml structure out of a find command is a pain.
We use several levels of directories to sort our documents, so for each level I'd have to conditionally apply whitespace, colons and check for the availability of .md files. 
The older *pages* section had a possibility to add arrays for each file, but it seems that the newer nav: section doesn't accept those anymore.

Is there a way to get nav: to accept the same list of arrays that pages did?

Below is the prototype script I'm currently building to generate the nav section:
```  bash
#!/bin/bash

FILES=`find docs -iname \*.md -printf "%P\n"`
OUTPUT=""

MKDOCS_FILE_TPL=mkdocs.yml.tpl
MKDOCS_FILE=mkdocs.yml

echo -ne ${FILES}

for line in ${FILES}; do
	[[ ${line} ]] || continue
	[[ ${line} = "#"* ]] && continue

  echo "${line}"

  IFS='/' read -a filearray <<< "${line}"

  # echo ${filearray[0]} ${filearray[1]} ${filearray[2]} ${filearray[3]}

  FIRST=${filearray[0]}
  SECND=${filearray[1]}
  THIRD=${filearray[2]}
  FORTH=${filearray[3]}

	LINE_OUTPUT="- [ \"${FIRST}\""

	if [[ ! -z ${SECND} ]] ; then
		LINE_OUTPUT="${LINE_OUTPUT}, \"${SECND}\""
	fi
	if [[ ! -z ${THIRD} ]] ; then
		LINE_OUTPUT="${LINE_OUTPUT}, \"${THIRD}\""
	fi
	if [[ ! -z ${FORTH} ]] ; then
		LINE_OUTPUT="${LINE_OUTPUT}, \"${FORTH}\""
	fi
	LINE_OUTPUT="${LINE_OUTPUT} ]"

	OUTPUT="${OUTPUT}\\n${LINE_OUTPUT}"
done

echo -ne ${OUTPUT}

if [[ ! -z ${MKDOCS_FILE} ]] ; then
	sed "s/^  navigation_string/${OUTPUT}/" ${MKDOCS_FILE_TPL} > "${MKDOCS_FILE}"
fi
```

it works on a template file that is used for substitution with sed as the substituting agent

``` yml
site_name: Documentation

repo_url: <repourl>
repo_name: <reponame>
edit_uri: <edituri>

nav:
  navigation_string

theme: material

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.details
  - attr_list

plugins:
  - search
  - exclude:
      glob:
```

**Comment by DutchessNicole** [comment]
the output of the above shell script is akin to 
``` yaml
- [ "admin", "index.md" ]
- [ "user", "index.md" ]
```

Which **should** have worked were it not for the fact that nav doesn't accept it anymore.

**Comment by waylan** [comment]
> ```
> - [ "admin", "index.md" ]
> - [ "user", "index.md" ]
> ```

That format was [deprecated][1] four years ago in version 0.13. The release notes even stated that support would be removed in version 1.0. I suspect that if we knew it would take so long to get to version 1.0, we would have removed support much earlier.

As [documented][2], your config should look like this:

```yaml
- admin: index.md
- user: index.md
```

Or if you want more formatting syntax (remember, YAML is a subset of JSON):

```yaml
- { "admin": "index.md" }
- { "user": "index.md" }
```

[1]: https://www.mkdocs.org/about/release-notes/#change-the-pages-configuration
[2]: https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation

**Comment by trel** [comment]
"YAML is a subset of JSON"

![](https://media.giphy.com/media/mjCaQoS4O7jEs/giphy.gif)

**Comment by DutchessNicole** [comment]
Well the thing is I don't want more formatting syntax: I want less.

the examples I gave were very simple, but you can imagine that some of the paths may be 4 or 5 items in length. Stuffing them all into an array is not much of an issue (my script manages that quite easily), but with the additional requirement of indentation, nesting and the possibility of multiple .md files within a single directory I'd end up either making one beast of a nested if-statement block (no thanks!) or a quite nasty recursive function.

And then I have to make sure to remove double paths, because I'd end up with entire double paths every time two or more files share a common path.
Of course if two files share a filename (which is entirely likely, with multiple pages describing the same functionality from multiple perspectives) it becomes very tricky very quickly.

**Comment by waylan** [comment]
@DutchessNicole the thing is that this change is now 4 years old and had been documents the entire time. We are not going to revert it now.

Secondly, it seems to me that it would be a lot easier to create a plugin which modifies the nav rather than writing a shell script which generates it. For that matter, a Python script which generates the nav would be easier as Python dicts map directly to JSON objects.
