### ISSUE TITLE
Ignore broken symlinks

### ISSUE THREAD

**Issue by dbeecham** [mkdocs/mkdocs#1753]
Very similar to #639, but not a duplicate.

This is my `mkdocs.yml`:

```
site_name: site
theme: readthedocs
docs_dir: .
site_dir: /var/www/
nav:
    - myprject: myproject/docs/readme.md
```

I build using `mkdocs build --config-file mkdocs.yml`

This is my error:

```
/mnt # mkdocs build --config-file mkdocs.yml -c
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /var/www
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - README.md
[...]
  - uboot/test/py/README.md
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/usr/lib/python3.6/site-packages/mkdocs/commands/build.py", line 285, in build
    files.copy_static_files(dirty=dirty)
  File "/usr/lib/python3.6/site-packages/mkdocs/structure/files.py", line 44, in copy_static_files
    file.copy_file(dirty)
  File "/usr/lib/python3.6/site-packages/mkdocs/structure/files.py", line 178, in copy_file
    utils.copy_file(self.abs_src_path, self.abs_dest_path)
  File "/usr/lib/python3.6/site-packages/mkdocs/utils/__init__.py", line 120, in copy_file
    shutil.copyfile(source_path, output_path)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/buildroot/package/skeleton-init-sysv/skeleton/dev/log'
```

That file, `/mnt/buildroot/package/skeleton-init-sysv/skeleton/dev/log` is a symlink to `../tmp/log`, which does not exist.

**Comment by waylan** [comment]
Generally we take the position that all files in your `docs_dir` will be copied to your `site_dir`. If you have a broken symlink, then presumably you don't want that file to be included. Therefore the symlink should not be present in your `docs_dir`. In other words, the fix is to remove the broken symlink.

**Comment by dbeecham** [comment]
Ok! Why does Sphinx follow symlinks instead of simply copying them?

**Comment by waylan** [comment]
I can't speak for Sphinx. That is a different project, with different goals. It is important to remember that we don't do something a certain way just because some other project does. We do what makes sense for your project within the goals of our project.

**Comment by dbeecham** [comment]
Sorry, I meant mkdocs, not Sphinx.

**Comment by waylan** [comment]
MkDocs is a "static site generator." The contents of the `site_dir` is a complete, standalone static site. It is expected that users will deploy that dir and all of its contents to a server. And local symlinks won't be useful to that server.

**Comment by dbeecham** [comment]
Ok. They could be though? The symlinks could theoretically point to somewhere that only makes sense in site_dir, but not in docs_dir? How do you deal with recursive symlinks? E.g. a symlink to parent directory.

**Comment by waylan** [comment]
Are you suggesting that you want to create a relative symlink in your `docs_dir` which is relative to the `site_dir` and then expect MkDocs to copy it as-is so that it points to a file from the `site_dir`? That is not something that we are interested in supporting.

**Comment by dbeecham** [comment]
All right.

Following symlinks by default seems unintuitive to me personally, but I guess it's a choice of style.

My scenario is this: We have a product, and this product consists of many repositories (a bunch of software packages), each with some documentation tied to that repository (each repository has a `docs`-folder with some markdown files). The product itself has a "master" repository with git submodules for each software that the product contains. The problem for me is that I don't have absolute control over what's in the submodules - the specific bit of software that `mkdocs` fails to deal with is buildroot, and buildroot has symlinks which only makes sense in the finished product.

I guess that `mkdocs` isn't really designed for our use case though. I can compile the documentation fine using https://github.com/apenwarr/mkdocs-exclude.
