### ISSUE TITLE
Will not deploy to gh pages after minimal changes

### ISSUE THREAD

**Issue by rjseymour66** [mkdocs/mkdocs#1758]
This is similar to #1297 - I replied to that thread but wanted to post here as well in case this is a new issue or there is no response because that issue is closed.

I successfully deployed to github pages a week ago, no problems. I made some minor revisions to the docs today and received the following errors when entering `mkdocs gh-deploy`:

`Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/2.7/bin/mkdocs", line 10, in <module> sys.exit(cli()) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 764, in __call__ return self.main(*args, **kwargs) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 717, in main rv = self.invoke(ctx) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 555, in invoke return callback(*args, **kwargs) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mkdocs/__main__.py", line 187, in gh_deploy_command gh_deploy.gh_deploy(cfg, message=message, force=force, ignore_version=ignore_version) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mkdocs/commands/gh_deploy.py", line 82, in gh_deploy if not _is_cwd_git_repo(): File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mkdocs/commands/gh_deploy.py", line 18, in _is_cwd_git_repo stdout=subprocess.PIPE, stderr=subprocess.PIPE) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__ errread, errwrite) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child raise child_exception UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)`

I have not made any changes to my computer, to python, to anything. I just fixed some grammatical things in the existing docs. `mkdocs serve` and `mkdocs build' both work.

I started a new mkdocs project to test if I accidentally hit a wrong key or something, and I could not deploy to gh pages with that project. I received the same errors.

What can I do? I am not a developer, so I have no idea how to fix this error and have not done anything to cause it. Please help!

**Comment by rjseymour66** [comment]
Every file in the project folder is UTF-8

**Comment by waylan** [comment]
Thanks for the report (an opening a new issue).

Based on the Traceback, it appears that the `gh_deploy` script is failing when it attempts to call a `git` command via a subprocess. It is the `git` command which is not being decoded properly. Presumably, one of the arguments being provided to it is not properly encoded. What arguments are you providing on the command-line and what do you have set in our config?

That said, it is perplexing as it appears the error is occurring when calling [_is_cwd_git_repo][1]. However, that command is not build from user provided variables, so the error makes no sense. Unless you called `gh_deploy` from outside a git repo? If so, then we have a bug in that the command is failing to properly report that.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/commands/gh_deploy.py#L16

**Comment by rjseymour66** [comment]
These are the exact steps that created this error:
1. Make changes in Atom editor.

Then, in the terminal:
2. Enter `git status`
3. Enter `git add .`
4. Enter `git commit -m "commit message"`
5. Enter `git push origin master`
6. Enter `mkdocs gh-deploy --clean`
Result: Error message

I have also entered `mkdocs gh-deploy` for step 6, and I have entered `mkdocs build` before the `gh-deploy` command.

I have no special configurations, and I have only called the command from within the root folder of the correct repo. Nothing really special going on with my repo.  Here is a [link to the repo](https://github.com/rjseymour66/RSO-docs), if it helps.

NOTE: Almost all of the most recent commits are just minor changes to test if I can deploy. There have been no issues pushing to the repo, only deploying to gh pages.

Please let me know if you need any other info.

**Comment by waylan** [comment]
Can you provide your Python and MkDocs versions? What is the output of the following
two commands:

```bash
python -V
mkdocs -V
```

**Comment by rjseymour66** [comment]
Python 2.7.13

mkdocs, version 1.0.4 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mkdocs (Python 2.7)

**Comment by waylan** [comment]
I'm closing this as we were never able to replicate the error. Additionally, we dropped support for Python 2.7 some time ago.
