### ISSUE TITLE
Use first heading from docs in navigation

### ISSUE THREAD

**Issue by bih** [mkdocs/mkdocs#1762]
Hey!

It looks like there isn't a way to configure Mkdocs to automatically generate a left hand sidebar based on a sorted list of the first `<h1>`, `# Title` or `Title\n====` of the markdown files. In the case of subfolders, the name would be inferred from the subfolder.

For example (files and their corresponding file contents):
```
docs/index.md
  # Homepage
  This is the contents of this file.
docs/api/version.md
  # Current Version
  The version is 1.0.0
docs/api/design.md
  # Design Decisions
  We made a few design decisions. Here's why: ....
```

This with a `mkdocs.yml` as such:

```yaml
docs_dir: ./docs
```

Should generate:

```
- Homepage
- Api
  - Current Version
  - Design Decisions
```

Does anyone know if there's an extension for this, or a flag in `mkdocs.yml` that we can enable for this? Happy to contribute and investigate adding this into Mkdocs ourselves.

**Comment by waylan** [comment]
What do you mean by "sidebar?" Or more specifically, which theme are you using? Note that the sidebar in each of the two included themes are very different things:

* In the `mkdocs` theme the sidebar consists of the Table of Contents for that specific page. It lists the headings on that page only.
* In the `readthedocs` theme the sidebar is the global site navigation which lists all pages in the navigation.

Without clarification, I'm not certain I understand your request.

That said, here are [multiple ways][1] to define a Page Title. However, a page can only have one title. Therefore, the one title is used everywhere when referencing a page. Note, that the various methods of defining a title are checked in order, with the first defined method used. So if you want to use the first `<h1>`, then don't define a title in the `nav` setting of the `mkdocs.yml` config file or in the pages meta-data. There is no need for a setting. Simply define the title in the one location you prefer.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data

**Comment by waylan** [comment]
> In the case of subfolders, the name would be inferred from the subfolder.

As the the docs [explain][1]:

> By default `nav` will contain an alphanumerically sorted, nested list of all the Markdown files found within the `docs_dir` and its sub-directories.

If you are auto-generating your navigation (leave the `nav` setting undefined), the subfolder's title is determined in the same way as a page. Of course, as there is no meta-data or Markdown content, and  no title is defined in the config, then it skips directly to using the directory name.

[1]: https://www.mkdocs.org/user-guide/configuration/#nav

**Comment by bih** [comment]
Ah looks like what I was asking is already implemented. In this case, I will close this. Thanks so much for the very prompt response! :)
