### ISSUE TITLE
Bad escaping with ≥markdown-3

### ISSUE THREAD

**Issue by zx2c4** [mkdocs/mkdocs#1768]
When my package manager updates me to markdown-3.0.1, all of my code fields have the > replaced with literal `&lt;` and such. It seems like there's too much escaping going on. Is this a markdown 3 bug or a mkdocs bug with the new package?

**Comment by waylan** [comment]
You don't provide enough information to be sure, but this sounds like a Markdown issue. Please report the issue to the Python-Markdown project. In doing so, you will need to provide a sample Markdown input, the HTML output you are getting, and the HTML output you expect.

**Comment by facelessuser** [comment]
There's a known bug in 3.0.1 that causes this in code blocks. It is fixed in the future 3.1 release.
