### ISSUE TITLE
Keep the Sidebar Always Expanded

### ISSUE THREAD

**Issue by Ad-An** [mkdocs/mkdocs#1769]
I am interested in the sidebar at the left of the screen and not the TOC. I use directories to store my files so I have to expand multiple entries to open the files I want.  How can I have the list always expanded and show all the nested files by default?

**Comment by waylan** [comment]
This is theme specific. Which theme are you using?

**Comment by Ad-An** [comment]
I am using the material theme, I didn't know it was theme specific.

**Comment by waylan** [comment]
Please take this to [squidfunk/mkdocs-material][1].

[1]: https://github.com/squidfunk/mkdocs-material
