### ISSUE TITLE
ERROR   -  Config value: 'pages'. Error: Invalid pages config

### ISSUE THREAD

**Issue by Jessespace** [mkdocs/mkdocs#1770]
When I run **mkdocs serve**,got  error:
`INFO    -  Building documentation... 
ERROR   -  Config value: 'pages'. Error: Invalid pages config. {<class 'list'>} {<class 'dict'>, <class 'str'>} 
Aborted with 1 Configuration Errors!`

**mkdocs.yml:**
`site_name: keras
pages:
- [index.md, Home]
- [about.md, About]
- [about.md, About]
theme: readthedocs
`
**Ubuntu14.04 Python 3.5 mkdocs-1.0.4**

**Comment by martinbira** [comment]
Pages is now `nav` as of MkDocs 1.0.
https://www.mkdocs.org/about/release-notes/#major-additions-to-version-10

**Comment by froschdesign** [comment]
@Jessespace 
The configuration for your pages are wrong. Use:

```yaml
nav:
    - Home: index.md
    - About: index.md
```

Compare with the documentation: https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation

@martinbira 
`pages` works also but with a warning message.

**Comment by Jessespace** [comment]
> @Jessespace
> The configuration for your pages are wrong. Use:
> 
> ```yaml
> nav:
>     - Home: index.md
>     - About: index.md
> ```
> 
> Compare with the documentation: https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
> 
> @martinbira
> `pages` works also but with a warning message.

Thanks,it works.

**Comment by froschdesign** [comment]
@Jessespace 
Please close this issue.
