### ISSUE TITLE
Feature request: Open browser automatically

### ISSUE THREAD

**Issue by peaceiris** [mkdocs/mkdocs#1772]
My implementation is #1771 

We can open the default browser automatically with the following commands when the local server starts.

- `mkdocs serve -o`
- `mkdocs serve --openbrowser`

Is this feature acceptable?

**Comment by waylan** [comment]
For future reference, there was no need to open this issue after you opened the PR. The PR can serve as both the feature request and solution all on its own. However, you might have opened an issue to inquire about interest in the feature before doing any work. In doing so you would have learned that I have no interest in the feature and might have then decided to not do the work. As it is, the work is done now and I was willing to review it. The point is, this issue now serves no purpose. Therefore I am closing it.

**Comment by peaceiris** [comment]
I took just a few minutes to implement #1771 and opened it to show the prototype. This issue was opened to inquire about interest in the feature.

Thank you for your useful feedback!

**Comment by pylang** [comment]
I use pyinvoke to compose commands and would like to see this feature included in some way.  Example:

```
> mkdocs serve -b 
```

The latter would start the server and open the tab automatically in the default browser when ready.   It's akin to [nikola's auto browse command](https://nikola.readthedocs.io/en/latest/manual/#all-you-need-to-know).
