### ISSUE TITLE
Navigation on Windows becomes Relative links

### ISSUE THREAD

**Issue by drwharris** [mkdocs/mkdocs#1773]
>mkdocs --version
mkdocs, version 1.0.3 from c:\program files\python\python37\lib\site-packages\mkdocs (Python 3.7)

I have the following mkdocs.yml:

```
##### Project setup and theming.
site_name: New Site
theme: cinder
extra:
  theme_inverse: true
strict: true
nav:
  - "Page 1": "one.md"
  - "Page 2": "two.md"
  - SubMenu:
      - "Page 4": "four.md"
      - "Page 5": "five.md"
#####

```
When I build this under linux (Ubuntu) all is fine, however when I build this under Windows all generated links are relative to the page I am on eg; Click on "Page 1" and I go to /one/. If I then click on SubMenu and click Page 4, the link is for /one/four/ and I get a 404.

Is this a configuration issue? Am I doing something wrong?

Andrew

**Comment by waylan** [comment]
Do you have the latest version of the theme installed? I am not able to replicate the behavior you describe and the only difference appears to be that I am not using the Cinder theme. You might want to address this issue upstream with the [Cinder theme][1].

[1]: https://github.com/chrissimpkins/cinder

**Comment by drwharris** [comment]
Yep...that was it :| Thank you!
