### ISSUE TITLE
Search does not handle hyphenated words in queries

### ISSUE THREAD

**Issue by kcboyle** [mkdocs/mkdocs#1784]
We have a lot of hyphenated words that are common in our queries. Is there a way we can configure mkdocs to allow these hypens in the search query? (below are a couple photos of what happens). We tried adding the following to our mkdocs.yml, and it didn't appear to do anything, but it could just be our not understanding the plugin
```
plugins:
- search:
    separator: '[\s]+'
```

<img width="1212" alt="Screen Shot 2019-04-19 at 3 06 16 PM" src="https://user-images.githubusercontent.com/1361223/56444161-d5ac8780-62b4-11e9-94cf-aa9fb9b0da13.png">
<img width="980" alt="Screen Shot 2019-04-19 at 3 06 29 PM" src="https://user-images.githubusercontent.com/1361223/56444163-d6ddb480-62b4-11e9-93a6-8374dbd2bc97.png">

**Comment by waylan** [comment]
The search plugin is a light wrapper around [lunr.js][1]. The `separator` setting is simply passed on to lunr.js as-is. What lunr.js does with that setting is outside our control. If you have an issue with how lunr.js is tokenizing hyphenated words, then I would suggest taking that up with the lunr.js project. If they help you work out a value for `separator`, then you should be able to just use that value in your mkdocs config.

Note that the `separator` value is assigned to `lunr.tokenizer.sepatator`. As the [lunr.js docs][2] explain:

> This tokenizer will convert its parameter to a string by calling toString and then will split this string on the character in `lunr.tokenizer.separator`. Arrays will have their elements converted to strings and wrapped in a `lunr.Token`.

Of course, this is speaking about JavaScript objects, to the value needs to be the string representation of a valid JavaScript regular expression. Personally I would have assumed `'[\s]+'` would work.

[2]: https://lunrjs.com/docs/lunr.html#.tokenizer
[1]: https://lunrjs.com/docs/index.html

**Comment by kcboyle** [comment]
Sure. We can go talk to the lunr.js team and see what's up. Thank you for such a timely response!
