### ISSUE TITLE
Generate list of files within the current directory

### ISSUE THREAD

**Issue by skdelphix** [mkdocs/mkdocs#1787]
We are using mkdocs with mkdocs-material and awesome-pages-plugin. We've received notes from several users that they expect to be able to go to http://docs-site/Some_Directory/ and see a list of 'child pages.' I know mkdocs doesn't have a concept of child pages per se, but I'm curious if there's a way to:

- Insert a list of child pages of the current working location (e.g. index.md inside of docs/Some_Directory would list all children of Some_Directory)
- Automatically generate an index.md with this list if none exists (not as important)

**Comment by waylan** [comment]
This is a feature offered by static file servers. As MkDocs generated a static site which is intended to be served by a static file server, this should be something you can do. However, the feature is not connected to MkDocs in any way and is completely dependent upon the server you are using. For example, see Apache's [Directory Listing] documentation. Note that you can provide a template to control the look. Of course, MkDocs' theme files won't help much there, but you could conceivably create a template which matched a MkDocs theme. Of course, the specific options available to you will depend on the host you are using. For example, some Apache hosts won't allow to to enable the feature, or they won't allow you to provide your own template. Other servers may have similar options which the host may or may not allow you to use/customize. 

Given the above, I suppose it may make sense to provide a page which is generated by MkDocs. That seems like a great feature for a [plugin][2]. As I don't have any need for it, I'm not likely to do the work myself. But, of course, anyone can create a third-party plugin. If you do, feel free to list it on the [wiki][3] so others can find it.

[1]: https://wiki.apache.org/httpd/DirectoryListings
[2]: https://www.mkdocs.org/user-guide/plugins/#developing-plugins
[3]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Comment by waylan** [comment]
I should also note that such a feature does not make sense to be included in MkDocs proper. MkDocs does not care about the structure of the files. You can have a nested navigation with a flat file structure or a flat navigation with a nested file structure. Therefore, this sort of feature only makes sense as a third party plugin.  Given the above, I am closing this issue.
