### ISSUE TITLE
Use highlight.js in local network

### ISSUE THREAD

**Issue by ceranco** [mkdocs/mkdocs#1789]
Hi,
I'm using mkdocs on a local network so I have no access to the CDN that hosts *highlight.js*. 
I tried adding it locally using `extra_javascript`, but the script is added in the `body` tag and `hljs.initHighlightingOnLoad();` is called in the `header` tag which then says that *hljs is not defined*.

Is there any way to resolve this issue and serve the script locally?

**Comment by waylan** [comment]
You can use [theme customization][1] to override the `libs` [block][2] of the template and redefine that section of the `header`. In fact, the documentation [demonstrates][3] overriding the `libs` block specifically, albeit with a slightly different end goal. In your case, simply copy the entire contents of the `libs` block to your custom `main.html` file should contain a copy of everything in the parent block with your changes (replace the CDN URL with a local URL).

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme-custom_dir
[2]: https://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks
[3]: https://www.mkdocs.org/user-guide/styling-your-docs/#combining-the-custom_dir-and-template-blocks

**Comment by waylan** [comment]
I almost forgot. There is also the theme option to disable highlight.js completely: [theme.highlightjs][1]. Setting that to `False` will completely remove any reference to highlight.js from the page including the call to `hljs.initHighlightingOnLoad();`. Of course, of you want to use highlight.js, then that may not be as helpful. However, it occurs to me that you could use that setting to remove the default CDN call to the script, and then use `super` to avoid redefining the entire block in your custom override.

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#mkdocs

**Comment by ceranco** [comment]
Thanks for the info, I'll take a look and respond tomorrow.

**Comment by ceranco** [comment]
Hi @waylan,
Your solution worked perfectly!
I used theme customization to replace the usage of google fonts at the same time.

**Comment by zimocode** [comment]
@ceranco 
Hi, I got the same problem. Could you please give me some sugesstions?
>make the nessecary changes (replace the CDN URL with a local URL).
