### ISSUE TITLE
Implement reusable themes with `theme_url`

### ISSUE THREAD

**Issue by micahhausler** [mkdocs/mkdocs#179]
I was thinking about how to reuse a custom MkDocs theme on multiple projects without copying files or using a git submodule, and it occurred to me that the [`jinja2.PackageLoader()`](http://jinja.pocoo.org/docs/dev/api/#jinja2.PackageLoader) could be used instead of the filesystem loader in [`build.py`](https://github.com/tomchristie/mkdocs/blob/b764af72abd1f30c707ac728ea192e6ccfe32d24/mkdocs/build.py#L167)

This could be as simple as:

https://pypi.python.org/pypi/my-mkdocs-theme
```
setup.py
my_mkdocs_theme/
    __init__.py
    version.py
    templates/
        css/
        fonts/
        img/
        js/
        base.html
        content.html
        nav.html
        search.html
        toc.html
```
And in each of my projects that use `my-mkdocs-theme`, 
`mkdocs.yml`
```yaml
template_pkg: my_mkdocs_theme
```
`requirements.txt`
```
my-mkdocs-theme==0.0.1
```

Thoughts?

**Comment by d0ugal** [comment]
Closing in favor of #476
