### ISSUE TITLE
Read the Docs theme search base doesn't extend main.html

### ISSUE THREAD

**Issue by ceranco** [mkdocs/mkdocs#1791]
`search.html` in the Read the Docs theme extends `base.html` instead of `main.html`.
This means that the changes made in a custom `main.html` aren't reflected in the search page, and that the `search.html` template needs to be completely replaced.

**Comment by ceranco** [comment]
I'd like to contribute a PR for this.
Should create a new branch?

**Comment by waylan** [comment]
A PR is welcome. Yes, you should create a new branch for your PR which we will merge into master if/when we accept the PR.
