### ISSUE TITLE
Livereload enters infinite loop when copying directory

### ISSUE THREAD

**Issue by nathanlesage** [mkdocs/mkdocs#1793]
Hello, and first of all thank you for this great project! It's so damn easy to write a nice documentation using MkDocs 😊

However, I noticed a thing. As I tend to keep my development files out of the cloud, but the documentation in, I resorted to the following workflow:

1. Start up the livereload server: `mkdocs serve`
2. Possibly do some changes to the CSS, the config, etc. All doing fine, and livereload does what its name says.
3. Work on the documentation in my Cloud folder w/ external application.
4. When I'm done, I run a script that recursively copies over **all** Markdown files to the appropriate `docs`-directory.
5. Livereload enters an infinite loop and I have to restart the server.

---

I think it's obvious what's happening here: When the bulk copying begins, livereload detects that a file has been changed on disk, then attempts to reload, but while reloading, it detects that more files have been altered, as the `rsync -R` command continues to copy over files, and then livereload becomes confused and hurt itself. 🐍

_(I'm using `rsync` as I do some filtering of the files)_

---

Possible solutions:

1. There must be a possible function calling itself, but as far as I'm concerned Livereload is itself another plugin, right?
2. Add a short delay to allow the file system to finish up the copying operation before attempting to live reload (seems the easiest solution to me)
3. Detach the file watcher from the live reload -- as soon as a file change is detected, immediately begin live reloading but `lock` the live-reloader until it returns successfully. If a file changes in the meantime, add a variable `reloadAfterLock` (or something) that is being checked once the reload finishes, so that a second reload can be done, if there are multiple files changed.

---

Additional information:

* Platform: macOS 10.14.4
* MkDocs version: 1.0.4 (installed via Homebrew w/ Python 3.7.3)

**Comment by waylan** [comment]
McDocks `serve` command is a light wrapper around [lepture/python-livereload][1]. This sounds like an upstream issue. If the upstream lib has a way to address this, then we should use it. If not, then you should take this upstream.

See also #1479 which may be somewhat related.

[1]: https://github.com/lepture/python-livereload

**Comment by nathanlesage** [comment]
Hm, I see what you mean. For now I've simply copied over the full directory to my cloud to avoid the issue (besides, it's nothing as bad as preventing development), but would you mind investigate? I'm not nearly as good in Python as necessary to test out various things :/

**Comment by VigneshVSV** [comment]
Just noting that this is an issue (probably with the upstream lib) also in 2024.
