### ISSUE TITLE
Ability to access the <h1> page title, as opposed to page title in mkdocs.yml

### ISSUE THREAD

**Issue by byrnereese** [mkdocs/mkdocs#1795]
In my install, the page titles I use in mkdocs.yml are very short and abbreviated. My page title is always the `<h1>` tag I put at the top of the page. 

I am curious if there is a way via the mkdocs templating language to access this longer page title?

I know I could use the page.meta.page_title to achieve that result, or I could use javascript to set the value in `<html><title>My longer title</title></html>`

**Comment by waylan** [comment]
There are [multiple ways][1] to define a Page Title. However, a page can only have one title. Therefore, the one title is used everywhere when referencing a page. Note, that the various methods of defining a title are checked in order, with the first defined method used. So if you want to use the first `<h1>`, then don't define a title in the `nav` setting of the `mkdocs.yml` config file or in the pages meta-data.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data

**Comment by byrnereese** [comment]
So one solution would be to include a `title=Custom page title` in my page meta variables? That would have precedence over the page title in mkdocs.yml?

**Comment by waylan** [comment]
> So one solution would be to include a `title=Custom page title` in my page meta variables? That would have precedence over the page title in mkdocs.yml?

Well, as explained in the documentation linked above, the title defined in `nav` gets presence and will be assigned to `page.title` (and used for global navigation) regardless of any meta-data. So if you really want two titles, then that would be one way to accomplish that.

**Comment by wilhelmer** [comment]
You can do that via Jinja in your template:
```jinja
{% extends "base.html" %}
{% if page.toc | first is defined %}
{% set _title = page.toc.items[0].title %}
{% else %}
{% set _title = page.title|striptags %}
{% endif %}

{% block htmltitle %}
<title>{{ _title }}</title>
{% endblock %}
```

**Comment by waylan** [comment]
Oh yeah, I forgot the [`page.toc`][1] object exists. You can use that to get the headings for the page. To confirm that the first heading is an `<h1>` heading, you can check that `page.toc.items[0].level == 1`. But that doesn't address whether the first item in the `toc` is actually the first item on the page. For example, the first element of a page could be a paragraph with the second element being an `<h1>` and the `toc` would not reflect that. 

[1]: https://www.mkdocs.org/user-guide/custom-themes/#pagetoc

**Comment by wilhelmer** [comment]
Yeah but all he wants is the first <h1>, so it doesn’t really matter where on the page it is, I think.

**Comment by waylan** [comment]
When we use the `<h1>` to determine the page title, we require the `<h1>` to be the first element on the page. If it is not, then we do not use that method to determine a page title. My assumption is that @byrnereese is looking to emulate the same behavior. Of course, if he doesn't care about that, then that makes things even easier for him.

**Comment by wilhelmer** [comment]
I see – you are always looking for the most universal solution, which makes mkdocs so great for so many of us.
However, I think @byrnereese will be fine with the simple solution:

> My page title is always the <h1> tag I put at the top of the page.

**Comment by MtShan** [comment]
wilhelmer, thank you for your advice. My propblem was solved.
I overwrited overrides/main.html as following your advice and it works well.
What I wanted is exactly same as what byrnereese wrote:
> My page title is always the \<h1\> tag I put at the top of the page.
> a shorted page title to appear in my navigation. And a longer page title to be used in the <title> tag of the page.
