### ISSUE TITLE
Markdown-Include configuration 'inheritHeadingDepth' error

### ISSUE THREAD

**Issue by mollieswenson** [mkdocs/mkdocs#1796]
I have the markdown-include extension working, but when I try to add the `inheritHeadingDepth: True` config value, I get an error. I'm guessing I just don't have the config syntax right. Can anyone advise? Thanks :)

From my mkdocs.yml

```
markdown_extensions:
    - markdown_include.include:
        base_path: docs
        inheritHeadingDepth: True
```
Config instructions: https://github.com/cmacmackin/markdown-include#configuration
I have tried formatting the YML several different ways with no luck. 

Debug says:  
```
DEBUG   -  Config value: 'markdown_extensions' = [{}, u'extra', u'admonition', {}, u'sane_lists']
```

And the error:

```
ERROR   -  Config value: 'markdown_extensions'. Error: inheritHeadingDepth
[E 190516 17:55:31 ioloop:801] Exception in callback <bound method type.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "c:\python27\lib\site-packages\tornado\ioloop.py", line 1229, in _run
        return self.callback()
      File "c:\python27\lib\site-packages\livereload\handlers.py", line 67, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "c:\python27\lib\site-packages\livereload\watcher.py", line 73, in examine
        func and func()
      File "c:\python27\lib\site-packages\mkdocs\commands\serve.py", line 107, in builder
        site_dir=site_dir
      File "c:\python27\lib\site-packages\mkdocs\config\base.py", line 210, in load_config
        "Aborted with {0} Configuration Errors!".format(len(errors))
    ConfigurationError: Aborted with 1 Configuration Errors!
```

**Comment by waylan** [comment]
Have you provided the complete `markdown_extensions` section of your config? According to the DEBUG message you should have some additional extensions listed (extra, admonition, and sane_lists). I just want to eliminate any other problems.

Also, have you tried wrapping `markdown_include.include` in quotes?  I'm wondering if the dot is confusing YAML.

Finally, have you tried lowercasing `True`? It should work capitalized, but YAML doesn't require that.

**Comment by Yc-Chen** [comment]
I have the same issue and I found out it has to do how you install the mkdocs. My environment is macos and I installed it using `brew`. Then I did

```sh
vim $(which mkdocs)
```
On the first line it says:
```
#!/usr/local/Cellar/mkdocs/1.0.4_1/libexec/bin/python3.7
```

So it turns out brew installs a standalone python for mkdocs. That means, **you should install `markdown-include` to the same python as `mkdocs`.**

Then I did:
```
/usr/local/Cellar/mkdocs/1.0.4_1/libexec/bin/python3.7 -m pip install markdown-include
```
Then it loads the package!
