### ISSUE TITLE
mkdocs converting files which are not under nav configuration

### ISSUE THREAD

**Issue by yyilmaz** [mkdocs/mkdocs#1801]
Hi everyone,
I am trying to build multiple websites from the same markdown document directory by supplying multiple mkdocs.yaml file(which references different markdown files). But when I build the website, I notice that markdown converts and pushes all markdown files under site output folder. Is there any option which prevents mkdocs from converting files that are not included under nav section?

**Comment by waylan** [comment]
No, this is not supported. If you do not want a file to be "built" then it must not exist in the `docs_dir`. There are no plans to change this in the future.
