### ISSUE TITLE
Relative links are broken in 1.x

### ISSUE THREAD

**Issue by danielhoherd** [mkdocs/mkdocs#1802]
# Description

Relative links are broken in 1.x. They worked fine in 0.17.x and prior.

# Test scenario

mkdocs.yml

```yaml
---
site_name: relative url bug example
```

docs/foo.md

```markdown
[check out page bar](bar)
```

# Expected behavior

Page site/foo/index.html contains URL:
```
<a href="../bar">check out page bar</a>
```
which is effectively site/bar

# Actual behavior

Page site/foo/index.html contains URL:
```
<a href="bar">check out page bar</a>
```
which is effectively site/foo/bar

# Further info

Testing several versions shows:

version | status
------- | ------
0.16.0  | `<a href="../bar">check out page bar</a>`
0.17.3  | `<a href="../bar">check out page bar</a>`
0.17.4  | `<a href="../bar">check out page bar</a>`
0.17.5  | `<a href="../bar">check out page bar</a>`
1.0.0   | `<a href="bar">check out page bar</a>`
1.0.1   | `<a href="bar">check out page bar</a>`
1.0.2   | `<a href="bar">check out page bar</a>`
1.0.3   | `<a href="bar">check out page bar</a>`
1.0.4   | `<a href="bar">check out page bar</a>`

# Speculation

The [1.0. release notes](https://www.mkdocs.org/about/release-notes/#version-10-2018-08-03) say "A new [url](https://www.mkdocs.org/user-guide/custom-themes/#url) template filter smartly ensures all URLs are relative to the current page (#1526)." I thought this was a bug in the themes, but looking at how they work, it looks like the problematic logic is somewhere inside the generation of `page.content`.

**Comment by waylan** [comment]
Things are working exactly as they are supposed to. You are missing the file extension. There is no page `bar`, but there is a page `bar.md`. MkDocs only knows how to convert links which exist, so it doesn't know what to do with `bar`. Note that all of the examples in the [docs][1] include the local file extension. This provides the added benefit that when browsing the source documents (on GitHub or in your text editor) the links work as well.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/

**Comment by danielhoherd** [comment]
Oh, nice! I've been doing it wrong for years. I verified that it does work with the file extension. Thanks!
