### ISSUE TITLE
Error when deploying to GitHub Pages

### ISSUE THREAD

**Issue by OfficialCRUGG** [mkdocs/mkdocs#1803]
Hey there! I get an error, when I try to deploy to GitHub Pages. I did it several times yesterday,but for some reason it doesn't work anymore now. I use Windows 10 and MkDocs Version 1.0.4 with Python 2.7.16 and pip 18.1.
This is the complete output I get (Repo names etc. changed):
```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: C:\Users\Me\Documents\Git\repo\site
WARNING -  Version check skipped: No version specificed in previous deployment.
INFO    -  Copying 'C:\Users\Me\Documents\Git\repo\site' to 'gh-pages' branch and pushing to GitHub.
fatal: update_ref failed for ref 'refs/heads/gh-pages': cannot lock ref 'refs/heads/gh-pages': unable to resolve reference 'refs/heads/gh-pages': reference broken
ERROR   -  Failed to rebase gh-pages branch.
error: cannot lock ref 'refs/heads/gh-pages': unable to resolve reference 'refs/heads/gh-pages': reference broken
Failed to process commit.
ERROR   -  Failed to deploy to GitHub with error:
warning: ignoring broken ref refs/heads/gh-pages
error: src refspec gh-pages does not match any
error: failed to push some refs to 'https://github.com/user/repo.git'
```
There are now changed being made on GItHub as well.

**Comment by waylan** [comment]
My best guess is that you have a problem with your `gh-pages` branch (a corrupt or missing reference?). Try deleting the local branch and then re-fetching it from GitHub:

```bash
git branch -D gh-pages
git fetch origin gh-pages:gh-pages
```

Be sure to run the above from any branch other than the `gh-pages` branch. You should now have a fresh copy and reference to the `gh-pages` branch. From your `master` branch you should now be able to run `mkdocs deploy`.

**Comment by OfficialCRUGG** [comment]
I don't have a local gh-pages branch?!

**Comment by waylan** [comment]
If it was working before, then you should. Unless you were using a non-standard setup. I'll need some more information:

1. What config values do you have set for the `remote_branch` and `remote_name` settings? 
2. What specific command did you use? 
3. Are you deploying to project pages or organization or user pages?

**Comment by casperdcl** [comment]
Have same error here: https://circleci.com/gh/openworm/openworm_docs/567 desipite having a github ssh user key with rewad/write access (https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys)

**Comment by casperdcl** [comment]
actually my comment is more https://github.com/mkdocs/mkdocs/issues/1413

**Comment by waylan** [comment]
I'm closing this issue due to a lack of information. The original poster never responded with the requested information.

@casperdcl I have likewise not received a full report from you. Have you tried everything suggested in this and #1413? What is the result of each attempt? I would suggest opening a new issue with a full report rather than reporting "me too" to old issues.

**Comment by OfficialCRUGG** [comment]
I didn't reply, because this is the first time I'm getting a notification for this after my last reply.
For the three questions you asked me, @waylan:
1. I don't know what you're talking about
2. `mkdocs gh-deploy`
3. Project page

**Comment by waylan** [comment]
>> 1. What config values do you have set for the `remote_branch` and `remote_name` settings?
>
>  1. I don't know what you're talking about

These settings should be defined in your `mkdocs.yml` config file as [documented][1]. Alternatively, they can be passed in as options to the `mkdocs deploy` command. However, based on your response, it would seem you have not specified them at either location. That being the case, we can assume the default values for each are being used. Given that you are deploying to a project page, the defaults should be correct and this probably not the cause of your problem.

[1]: https://www.mkdocs.org/user-guide/configuration/#remote_branch
