### ISSUE TITLE
When click upper-left corner icon, the page change to 0.0.0.0:8080

### ISSUE THREAD

**Issue by bq1028** [mkdocs/mkdocs#1809]
Hi,  thank you for what  you did  on this nice  project. but now i need your help on below issue.

When I click upper-left corner icon, the page change to 0.0.0.0:8080
I  start the service as below:
mkdocs serve -a 0.0.0.0:8080   and the server behind nginx reverse proxy.

the theme i used is material

I  test the other theme like mkdocs and bootstrap4,  there is no such problem (no change any settings)

the test site is https://www.nowellzhang.top/

**Comment by bq1028** [comment]
Hi All, 
I fixed this problem using below way:
Change run mode from dev to prod,  namely
````
mkdocs serve -a 0.0.0.0     // (dev mode)
mkdocs build                     //( prod mode)
http-server . -p 8080 

```

**Comment by waylan** [comment]
Please note that the MkDocs server is not intended to be used this way. It is intended to be a development server only which only serves requests on the local machine. It should never be proxied through a production server. We do not support that use and do not guarantee that it will continue to work in the future.

If you are using nginx, then you should configure it to serve the static files generated by the `mkdocs build` command, not proxy to the MkDocs server.
