### ISSUE TITLE
Document how to write custom themes.

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#181]
We need a section in the MkDocs docs for "Theme authors" - what files they need, what context variables etc. are availabe for them.

**Comment by d0ugal** [comment]
I've started an experiment here: https://github.com/d0ugal/mkdocs-basic-theme

I think it is probably easier to demonstrate this stuff than document it in prose. Thoughts?

**Comment by d0ugal** [comment]
(It isn't fully functional yet, but not far off either)

**Comment by waylan** [comment]
Wow, that will be extremely helpful. I'd still like to see some prose in the docs, but the basic example is great for more advanced users.

**Comment by d0ugal** [comment]
We aso need to cover how to package themes if #530 lands.

**Comment by d0ugal** [comment]
With the addition of 43c64ab7669c6d4a492763b08c4b0918a0154248 and https://github.com/mkdocs/mkdocs-basic-theme, I think this is covered well enough for now.
