### ISSUE TITLE
Case insensitivity on Windows?

### ISSUE THREAD

**Issue by k4kfh** [mkdocs/mkdocs#1810]
I don't know if this is an issue that is realistic for mkdocs to try to handle, but it is a little annoying. If you have ``somePicture.png`` referenced in your markdown, and the path is exactly right but the actual file is named ``somePicture.PNG``, mkdocs will give errors about files not being found and the files will not show correctly in the browser either.

Maybe there could be some additional logic in the path verification where if the Markdown references ``somePicture.png``, but only ``somePicture.PNG`` exists, just print a warning to the console and rename the file to ``somePicture.png``? I doubt there are very many mkdocs users who actually care about the case of their image file extensions.

**Comment by waylan** [comment]
MkDocs is designed to work the same on all systems, As on many systems (and on web servers) `somePicture.png` and `somePicture.PNG` are considered different files, then MkDocs considers them different files. MkDocs behavior is not "annoying," it is altering you to a potentially real problem you will face when you upload your site to a web server.
