### ISSUE TITLE
Search does not find code with colons

### ISSUE THREAD

**Issue by Phrogz** [mkdocs/mkdocs#1812]
I'm writing documentation for a Lua API. Lua uses syntax like `foo:bar()` for some methods.

I have a heading documenting a call using this markdown:

```md
## `app:setTimeout(callback, delay)`
```

When I enter `setTimeout` in the Search box, this heading is not found. Only a related topic (`clearTimeout`) which mentions `setTimeout` directly is displayed as a search item.

**Comment by Phrogz** [comment]
I'm guessing that the colon is not being treated as a word boundary, and so something like `app:setTimeout` is being added to the search index. Is there some way to force colons to be treated as a word boundary?

**Comment by Phrogz** [comment]
FWIW, this is in the `search_index.json`:

```json
{
   "location":"application-script.html#appsettimeoutcallback-delay",
   "title":"app:setTimeout(callback, delay)",
   "text":"Invoke a function ( callback ) once after delay milliseconds. When invoked the function will be passed the application table as its sole parameter. This function returns a token value that may be passed to clearTimeout() to cancel the invocation before it occurs."}
```

**Comment by waylan** [comment]
You can define the word [separator][1] used for search in your config. Note, however, that we are using lunr.js for search. Some anything other than MkDocs simply passing their settings on to you should be taken upstream to lunr.js.

[1]: https://www.mkdocs.org/user-guide/configuration/#search

**Comment by Phrogz** [comment]
Adding the following to my `mkdocs.yml` fixed it for me. Thank you!

Perhaps consider if the default `separator` setting is sufficient? For example, even `foo(bar)` will not match foo with the default.

```yaml
plugins:
  - search:
      separator: '\W+'
```

I will close this issue as solved for me. However, if you feel that the default separator should be changed, feel free to re-open and use this to track that change.

**Comment by waylan** [comment]
The default is set by lunr.js. If you would like to suggest that the default be changed, then I suggest you take that upstream.
