### ISSUE TITLE
Jumping to search results does not work

### ISSUE THREAD

**Issue by Apromixately** [mkdocs/mkdocs#1814]
It seems that clicking on search results will scroll such that the search result is at the top of the screen but then put the navigation bar over it. At least I am having this problem with the docs for nalgebra. I think plain anchors have the same problem: https://nalgebra.org/rustdoc/nalgebra/base/type.Matrix4.html#method.new_rotation

I have this problem with an up-to-date Firefox.

**Comment by waylan** [comment]
This is not specific to search; any hash link will exhibit the same behavior. Regardless, this would be a theme specific issue. Please report this to whatever theme you are using.

**Comment by Apromixately** [comment]
@waylan Is there a simple way for me to find out which theme that page is using?

**Comment by froschdesign** [comment]
@Apromixately
This is a custom theme. See: https://github.com/rustsim/nalgebra.org
