### ISSUE TITLE
Question: Can the source be RestructuredText (rst)?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [mkdocs/mkdocs#1817]
Is it possible to have the source in restructuredtext? Or does it have to be Markdown only?

How hard would it be to implement support for restructuredtext?

**Comment by waylan** [comment]
MkDocs only supports Markdown and there are no plans to support anything else.  I suppose it might be possible to create a plugin which added support for rst, but that wasn’t what the plugin API was designed for and it would always feel like a hack. I wouldn’t recommend trying it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tset-Noitamotua** [comment]
All right. Thank you for clarification.
