### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by winterwolf** [mkdocs/mkdocs#1819]
Ubuntu 18.04
mkdocs, version 1.0.4 from /usr/local/lib/python2.7/dist-packages/mkdocs (Python 2.7)

<pre><font color="#A6E22E"><b>luarocks@MAINFRAME</b></font>:<font color="#66D9EF"><b>~/Загрузки</b></font>$ mkdocs new test
INFO    -  Creating project directory: test 
INFO    -  Writing config file: test/mkdocs.yml 
INFO    -  Writing initial docs: test/docs/index.md 
<font color="#A6E22E"><b>luarocks@MAINFRAME</b></font>:<font color="#66D9EF"><b>~/Загрузки</b></font>$ mkdocs build
Traceback (most recent call last):
  File &quot;/usr/local/bin/mkdocs&quot;, line 10, in &lt;module&gt;
    sys.exit(cli())
  File &quot;/usr/lib/python2.7/dist-packages/click/core.py&quot;, line 722, in __call__
    return self.main(*args, **kwargs)
  File &quot;/usr/lib/python2.7/dist-packages/click/core.py&quot;, line 697, in main
    rv = self.invoke(ctx)
  File &quot;/usr/lib/python2.7/dist-packages/click/core.py&quot;, line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File &quot;/usr/lib/python2.7/dist-packages/click/core.py&quot;, line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File &quot;/usr/lib/python2.7/dist-packages/click/core.py&quot;, line 535, in invoke
    return callback(*args, **kwargs)
  File &quot;/usr/local/lib/python2.7/dist-packages/mkdocs/__main__.py&quot;, line 166, in build_command
    raise SystemExit(&apos;\n&apos; + str(e))
UnicodeDecodeError: &apos;ascii&apos; codec can&apos;t decode byte 0xd0 in position 28: ordinal not in range(128)
<font color="#A6E22E"><b>luarocks@MAINFRAME</b></font>:<font color="#66D9EF"><b>~/Загрузки</b></font>$ 
</pre>

**Comment by waylan** [comment]
Hmm, it appears that the error is raised by the click lib, which suggests this could be an upstream issue. Although, we shouldn't be passing strings in `ascii` to click, so that may be the cause of the error. I notice that you are using Cyrillic in your path, so that could be connected to the issue as well. This is likely another issue of the English alphabet mapping one-to-one from ASCII to Unicode, which causes these sorts of problems to go undetected.

Thanks for the report. we'll have to do a little investigating to determine the cause.

**Comment by winterwolf** [comment]
@waylan the problem in the cyrillic letters. Try yourself - copy some word, like "Загрузки" and create directory with that name, then reproduce my steps.

**Comment by waylan** [comment]
> Maybe this bug is fixed in Python 3, I don't know. It is installed in my system, but I have no idea how to switch between Python versions.

Note that Python 2.7 is being deprecated in a few months. Usually you can access Python 3 with `python3`. If you want to install to Python 3, use `pip3`. However, the `mkdocs` command will only be associated with one version. You can always specify which Python to use with a command by using the `-m` flag (so long as the command is installed for that version), like this: `python3 -m mkdocs`.

**Comment by winterwolf** [comment]
@waylan I didn't know about pip3, thank you a lot! Now everything works fine.
