### ISSUE TITLE
Search works only with English words

### ISSUE THREAD

**Issue by winterwolf** [mkdocs/mkdocs#1821]
All Russian words in the topics are automatically converted to numbers. In my Russian wiki search doesn't work at all.

**Comment by winterwolf** [comment]
For example:

![screenshot](https://user-images.githubusercontent.com/42620439/60387970-6ec8fd00-9ab3-11e9-8923-d918719690ff.png)

"Модифицированные правила" converted to "#_9".

**Comment by waylan** [comment]
Have you set the [`search.lang`][1] setting to `- ru`? If so, then the problem should be reported upstream to [MihaiValentin/lunr-languages][2].

[1]: https://www.mkdocs.org/user-guide/configuration/#lang
[2]: https://github.com/MihaiValentin/lunr-languages

**Comment by winterwolf** [comment]
@waylan Sorry, my bad, didnt know about it. Thank you again! :+1:
