### ISSUE TITLE
Config and meta variables are not escaped properly in the default themes

### ISSUE THREAD

**Issue by comp500** [mkdocs/mkdocs#1822]
Following from squidfunk/mkdocs-material#1117, I found numerous places in the mkdocs-material theme where escaping is insufficient for `config.*` and `page.meta.*` variables. @squidfunk subsequently pointed out that these issues also exist in the mkdocs default themes.
 
These variables are passed from the config file and page metadata without any escaping or modification. This may be desirable for including HTML in the config file, but escaping is required if quotes, brackets or ampersands are to be used (e.g. a site name with an ampersand in it) in any of these variables.

Some of the places where this can be found in the default themes are as follows:

`config.site_author`, `config.site_name`, and `config.site_description`, identical in the readthedocs theme
https://github.com/mkdocs/mkdocs/blob/a84b5a27df9b0ed90c4718871e4b60d8735c416b/mkdocs/themes/mkdocs/base.html#L4-L17

`page.meta.source` however it is unclear if this should allow HTML, for example links
https://github.com/mkdocs/mkdocs/blob/a84b5a27df9b0ed90c4718871e4b60d8735c416b/mkdocs/themes/mkdocs/content.html#L3-L5

`config.site_name`
https://github.com/mkdocs/mkdocs/blob/a84b5a27df9b0ed90c4718871e4b60d8735c416b/mkdocs/themes/readthedocs/base.html#L114-L118

I think we have three options:
1. Escape all these occurrences in all the default themes (and mkdocs-material) so that they are handled correctly, potentially removing usage of HTML where it is not needed.
2. Escape all `page.meta.*` and `config.*` variables in mkdocs itself, removing support for HTML in them. (Jinja's `safe` filter could be used in the theme to allow HTML if needed)
3. Specify in documentation that configuration and metadata should be treated as HTML and escaped by the user. (using `&quot;` for example, however the escaping required varies between themes and variables)

It may also be unclear, for option 1, which variables should be escaped and should not be escaped, and if some variables are left unescaped issues may be encountered when the user enters brackets or ampersands into them. We must ensure that other mkdocs themes handle this correctly as well.

**Comment by waylan** [comment]
Can you provide some examples of actual problems that escaping would prevent?

**Comment by comp500** [comment]
I don't have any specific examples, but there are probably many cases where you would want to include quotes in the site description or site author, which would produce invalid HTML due to being in a meta tag content attribute.

**Comment by waylan** [comment]
While we may traditionally expect a config value to only be used in a specific way, we should never force that use. Therefore any and all escaping should happen in the theme, which makes it completely user overridable (with theme customization). Of course, patches are welcome.
