### ISSUE TITLE
How to configure for structured nav

### ISSUE THREAD

**Issue by leonardean** [mkdocs/mkdocs#1825]
Is there a way to configure structured Nav item names and orders. The doc only describes plain level nav configuration. Thx!

**Comment by froschdesign** [comment]
> The doc only describes plain level nav configuration.

The documentation also contains description for nested sections: "[User Guide > Writing your docs > Configure Pages and Navigation](https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation)"

**Comment by leonardean** [comment]
> > The doc only describes plain level nav configuration.
> 
> The documentation also contains description for nested sections: "[User Guide > Writing your docs > Configure Pages and Navigation](https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation)"

I see, missed that. Many thanks.
