### ISSUE TITLE
Allow repo_url, repo_name and site_url to be passed in as command args to mkdocs build.

### ISSUE THREAD

**Issue by skyscooby** [mkdocs/mkdocs#1827]
Many CI systems including GitLab expose their project's Pages path and Repository path as environment variables. 

For GitLab this would be so CI jobs defined in .gitlab-ci.yml could be ran like:
mkdocs build --repo-url="$CI_PROJECT_URL" --site-url="$CI_PAGES_URL" --repo_name="$CI_PROJECT_PATH"

While the variables may be different they are generally available for many CI systems.

This would be really nice as a boilerplate mkdocs.yml file would suffice for every project without the need to customise each file with the appropriate URL (and improve portability as no need to update those if we ever move the project).

This can be done today using envsubst and a template as a prior step to the build but its a little smelly that way..

**Comment by boldmonkey** [comment]
A more generic form of this might be to provide environment variable substitution in the `mkdocs.yml` file along [these lines](https://www.elastic.co/guide/en/beats/winlogbeat/current/using-environ-vars.html).

This would achieve the goal of being able to inject build specific configuration like `site_url` etc, but would also allow users to eliminate repetition in `mkdocs.yml` by replacing parts of a configuration value, such as a version number, that may occur in multiple places by referencing a single environment variable.

I've been considering doing something like this myself with a plugin that uses the `on_config` hook to perform post-YAML parsing substitutions on each configuration item, so I'd be happy enough to go down that path.

**Comment by warmfusion** [comment]
This is actually already possible thanks to the comment on https://github.com/mkdocs/mkdocs/issues/1195

on our mkdocs.yaml we've got this setup;

``` yaml
site_name: !!python/object/apply:os.getenv ["CI_PROJECT_PATH"]  
repo_url: !!python/object/apply:os.getenv ["CI_PROJECT_URL"]
repo_name: !!python/object/apply:os.getenv ["CI_PROJECT_PATH"]
```

if the environment variables aren't defined mkdocs throws some errors, but it makes project builds nice and simple.

**Comment by waylan** [comment]
I'm going to close this in favor of environment variables. With #2267 there is a cleaner way to define environment variables (which retains types) and provide fallback values if a var is not defined.
