### ISSUE TITLE
Github accounts with 2FA can't `gh-deploy` due to authentication error.

### ISSUE THREAD

**Issue by Sonofotis** [mkdocs/mkdocs#1831]
# Github accounts with 2FA can't `mkdocs gh-deploy` due to authentication error.

A coworker needed to deploy a few changes made on our repo to a custom domain. 

Mkdocs was working fine on his system, he could serve, make changes e.t.c. but every time he tried to run `mkdocs gh-deploy` the following error would appear:
```
ERROR   -  Failed to deploy to GitHub with error: 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/<repo>'
```
The username and password were not incorrect, found no information online about anyone else incurring this error with mkdocs so we started to troubleshoot it.

## Problem & Temporary Fix
Disabling 2FA on his github account removed the authentication error.
Now as a temporary solution we remove 2FA from the github account, `gh-deploy` the changes and then add the 2FA back.

**Comment by waylan** [comment]
We [vendor][1] a copy of [davisp/ghp-import][2]. Unless they have made recent changes to address this, I would expect the same problems to occur there as well. However, I don't see any mention in their list of issues.

I'm curious if the problem persists when you use ghp-import directly. Try this (after installing ghp-import):

```
mkdocs build
ghp-import -p -r REMOTE -b BRANCH site
```

You may need to adjust and/or add some options. But does the same problem present itself?

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/utils/ghp_import.py
[2]: https://github.com/davisp/ghp-import

**Comment by koddr** [comment]
Similar error, how to fix it (without disable 2FA, of course).

**Comment by waylan** [comment]
You can remove MkDocs and ghp-import from the authentication process by doing something like this:

```
mkdocs build
ghp-import site
git push origin gh-pages
```

Notice that `git` itself is responsible for deploying.  Once you get that working, I expect that the `gh-deploy` command will work as well.

**Comment by koddr** [comment]
@waylan thx, but I found another solution :)

Create branch `gh-pages`, set to it my GitHub Pages settings:

![Screenshot 2020-01-04 at 01 22 32](https://user-images.githubusercontent.com/11155743/71752599-b54b4a00-2e90-11ea-89a7-32350a9a5a8e.png)

And create `Makefile` with:

```makefile
.PHONY: gh-pages

gh-pages:
	rm -rf ./site \
	&& mkdocs build \
	&& git checkout gh-pages \
	&& cp -R ./site/* ./ \
	&& rm -rf ./site \
	&& git add . \
	&& git commit -m "Update docs" \
	&& git push
	@echo "[✔️] Docs was created and wait for deploy to gh-pages branch!"
```

Next, just run `make` on root folder of my project (where `mkdocs.yml` and `./docs` with `*.md` files).

**Comment by asr-enid** [comment]
FYI since I stumbled across this too. You can address this without the need for any patches / workaround by using personal access tokens

https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line

**Comment by waylan** [comment]
As GitHub is [deprecating][1] the use of passwords for pushing via HTTP, personal access tokens will be required going forward. That being the case, there is nothing for us to do here as the tokens already work. Therefore, I am closing this.

[1]: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
