### ISSUE TITLE
Lunr Search breaks on adding HTML code snippets

### ISSUE THREAD

**Issue by ankitind** [mkdocs/mkdocs#1832]
If any markdown files contains HTML elements like Head, Body - the search breaks. 

The error message it throws is
```
Uncaught exception GET /search/search_index.json (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/search/search_index.json', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):

```

-- Markdown file Starts -- 

A sample markdown file that can break the Search Index 
## Basic theme

The simplest `main.html` file is the following:

```django
<!DOCTYPE html>
<html>
  <head>
    <title>{% if page.title %}{{ page.title }} - {% endif %}{{ config.site_name }}</title>
  </head>
  <body>
    {{ page.content }}
  </body>
</html>
```

The body content from each page specified 

--- Markdown file Content Ends --
Taken from 
https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/custom-themes.md

A similar issue was raised in #1774

**Comment by ankitind** [comment]
Not able to reproduce

**Comment by waylan** [comment]
Note that putting `<head>` and `<body>` tags in your Markdown body will result in invalid HTML. The user is responsible for ensuring that any raw HTML they use in their Markdown documents is valid. We cannot be responsible for any breakages which are caused by user error.
