### ISSUE TITLE
Plugin development debugging/tests

### ISSUE THREAD

**Issue by zayd62** [mkdocs/mkdocs#1834]
Hi there

im writing a plugin and i was wondering how i would go about debugging (particularly vscode) as well as writing and executing unit tests for the plugin. i know that python has a built in unittest and doctest but i was wondering if perhaps you could discuss this or perhaps point me towards resources that could help

Many thanks

**Comment by waylan** [comment]
The search plugin, which is included with MkDocs has extensive tests. I would suggest [browsing the source][1] for ideas as a place to start. As you can see, they are simply standard Python unittests. 

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/tests/search_tests.py

**Comment by zayd62** [comment]
Alright, ill check out the source code for the test samples. 

How about debugging. im using vscode for writing the plugin and i want to use the built in debug tools in vscode

my current way of doing things is a little script that uninstalls my plugin and installs with ```pip install -e``` and then running ```mkdocs build```

**Comment by waylan** [comment]
I have only ever used Python's standard debugging tools. I would suggest searching for how to use your tool to debug Python. Whatever standard answer you get there will work for MkDocs as MkDocs is just standard Python.
