### ISSUE TITLE
Individual TOC-depth for each Navigation Section

### ISSUE THREAD

**Issue by Breee** [mkdocs/mkdocs#1838]
Hey, we want to set the TOC-depth for each Navigation-item Indiviually. 

Something like: 

```
nav:
  - Home: 
        - 'index.md'
        - toc_depth: 4
  - Installation:
      - 'Preliminaries': 'installation/preliminaries.md'
      - 'Configuration': 'installation/configuration.md'
      - 'Deployment': 'installation/deployment.md'
      - toc_depth: 2
  - Usage:
      - 'API Queries': 'usage/api_queries.md'
      - 'FAQ': 'usage/faq.md'
      - 'Requirements': 'usage/requirements.md'
       - toc_depth: 3
  - Contribute:
      - 'to Docs': 'contribute/to_docs.md'
``` 

Is there a plugin / extension which is capable to do that?

**Comment by waylan** [comment]
All of the known plugins are listed on the [wiki](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins). If it is not listed there, then we don't know about it and presumably it does not exist.

**Comment by Breee** [comment]
As the dev of mkdocs, 
would you recommend to fork and alter mkdocs directly or rather writing a plugin?

I think all that has to be done is altering the toc_depth before the toc section is built. 
It would be nice of you if you could point me to the code which is responsible for that :)

**Comment by waylan** [comment]
The TOC depth is controlled completely within the theme templates (for example see the [readthedocs theme][0]). The [page.toc][1] object holds the full TOC for each page. It is in the template where the depth is restricted.  Therefore, all you need is to either [customize a theme][2] (using the appropriate [template block][3]), or [create your own custom theme][4]. No need to make any changes to the code or create a plugin.

The one area where you may have a problem, is defining the depth for each page. There is no way to include that information in the global `nav` object. I would suggest using the [meta-data][5] for each page. For anything else, you would need a plugin. Not sure how that would work though.

[0]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/toc.html#L5
[1]: https://www.mkdocs.org/user-guide/custom-themes/#pagetoc
[2]: https://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme-custom_dir
[3]: https://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks
[4]: https://www.mkdocs.org/user-guide/custom-themes/
[5]: https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data
