### ISSUE TITLE
code blocks lost css style

### ISSUE THREAD

**Issue by Rominez** [mkdocs/mkdocs#1839]
I tried to use ubuntu command line and run 'mkdocs build', copy 'site' floder to my tomcat server. All of the `<code>` html element ( code blocks,  ``` in markdown ) lost their css style.   
My mkdocs version is 1.0.4, and no same problem on windows.

**Comment by Rominez** [comment]
one more question: I can just use 'navigator.clipboard' when my server is created by 'mydocs serve' command line on windows.

**Comment by waylan** [comment]
Is the browser reporting any errors? If so, what errors? Use the browser's dev tools to check.

**Comment by Rominez** [comment]
[Reply waylan](https://github.com/mkdocs/mkdocs/issues/1839#issuecomment-520248867)
TypeError: navigator.clipboard is undefined. I want use it to copy something in event, but the navigator.prototype seems something different, there have no clipboard.
And there no other errors looked like something about css style lost.

**Comment by waylan** [comment]
I can't replicate the problem. Can you point me to a publicly available copy of the site which exhibits the problem?

**Comment by Rominez** [comment]
[Reply waylan](https://github.com/mkdocs/mkdocs/issues/1839#issuecomment-520462925)  
Sorry, I'm too busy this days. Here is my note site [link](http://45.77.86.10/note/). This site is generate by mkdocs 1.0.4 on windows, you can open the Chrome DevTools command line and type 'navigator.clipboard'.

**Comment by waylan** [comment]
I see no problems with the provided link and the two links appear to link to the came location.

I do notice that you have some non-ASCII (unicode) text in your pages. This could be a cause of the problem if you have not saved your Markdown files as UTF-8. The fact that you are getting different results on different systems further supports the theory that you have an encoding problem. MkDocs only supports UTF-8 encoded Markdown files. If that is not the default on one or other of your systems, you will need to force the files to be saved as UTF-8.

Finally, I have no idea why you keep referring to 'navigator.clipboard'.

**Comment by Rominez** [comment]
I just checked my ubuntu system, it's en_US.UTF-8.  And all of my Markdown files is UTF-8 (no BOM) encoded. Should I config something others before run 'mkdocs build'? 

About clipboard api, I want use it in extra javascript file to make some personality extend function.
