### ISSUE TITLE
[Feature]  RSS wanted!

### ISSUE THREAD

**Issue by RoseauHan** [mkdocs/mkdocs#1844]
Thanks for your great work!😘
I am using mkdocs in my [knowledge share site](https://roseauhan.github.io/cookbook-material/).

I want to know if exist RSS support? if so, how can I use it correctly?
if not, could you please add offical rss support?

Thank you for your great work again!

**Comment by waylan** [comment]
There is currently no support, nor are there any plans to add support. That said, you probably could create an RSS feed with a [static template][1]. However, what would the "entries" contain? We don't track changes and there is no dated content. 

[1]: https://www.mkdocs.org/user-guide/configuration/#static_templates

**Comment by RoseauHan** [comment]
All right, I will learn it myself. Thank you anyway.

**Comment by froschdesign** [comment]
@RoseauHan 
Take a look at the static site generator [Hugo](https://gohugo.io/). There will you find [RSS support](https://gohugo.io/templates/rss/). Maybe it helps you.

**Comment by RoseauHan** [comment]
> @RoseauHan
> Take a look at the static site generator [Hugo](https://gohugo.io/). There will you find [RSS support](https://gohugo.io/templates/rss/). Maybe it helps you.

Thank you!

**Comment by wsmckenz** [comment]
@waylan "However, what would the "entries" contain? We don't track changes and there is no dated content." Almost everybody's content is coming from git, no? Wouldn't a pattern of one item per markdown page and last commit date in git as the date/time make sense? Seems like it would be a plugin more than a template.

**Comment by Guts** [comment]
I wanted a RSS feature too, so I developed a plugin using git log: https://github.com/Guts/mkdocs-rss-plugin
Feel free to use, report issues and PRs are welcome :).
Hope it helps!
