### ISSUE TITLE
Switching between multiple mkdocs project setups

### ISSUE THREAD

**Issue by dennisvanlith** [mkdocs/mkdocs#1845]
Once you open up you terminal and type `mkdocs serve`. It picks up the set up project and builds it up in localhost. Very nice for a single setup project. As far as I know there is no way two switch between multiple setup projects of mkdocs.

I was looking into the `mkdocs -h ` section and I could not find a way to switch between multiple setup's of mkdocs. I currently running a second setup and switching between those two is becoming a quite a ordeal. Right now I have to make a new project copy all my documents in the folder (sometimes even needs debugging), and serve the next project.

I would be a great addition to just have to switch between multiple projects by simply enter something like `mkdocs switch {project name}` in the terminal. This will change the existing primary project with the new. And when entering `mkdocs serve` it will launch the switched project. 

Just my two thoughs...

**Comment by waylan** [comment]
Sounds like you want the `-f/--config-file` option. Simply point that option at a different config file, and you will get the project associated with that file.

Note that all paths within a config file **must** be relative to the config file. However, you can have multiple config files with any name you want so long as you properly point to them with the `-f` option. Using `mkdocs.yml` at the filename is only the default if another name is not specified.
