### ISSUE TITLE
more than one Google-Analytics-Property-ID

### ISSUE THREAD

**Issue by rwoldu** [mkdocs/mkdocs#1847]
Hi everybody,
can you tell me if it is possible to add more than one PropertyID for Google Analytics?
Example: within the mkdocs.yml:

google_analytics:
  - 'UA-36723568-3'
  - 'UA-36723568-4'

**Comment by waylan** [comment]
No, that is not supported. You would likely need to use [theme customization][1] to override the `analytics` [template block][2].

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme-custom_dir
[2]: https://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks

**Comment by rwoldu** [comment]
Thank you very much, I will try that out

**Comment by rwoldu** [comment]
fyi: it worked by using this script in the analytics block: https://stackoverflow.com/questions/23749392/name-spaced-accounts-not-working-under-universal-analytics
