### ISSUE TITLE
Strict mode ignores missing .md for anchor links

### ISSUE THREAD

**Issue by martinbira** [mkdocs/mkdocs#1848]
## Description

If an anchor is present in a link, strict mode does not give a warning and exit if the filename does not include `.md`, resulting in incorrect link targets.  May be related to https://github.com/mkdocs/mkdocs/issues/658

### Steps to reproduce the bug

1. Have a page with a link as `filename.md#target`
2. Run `mkdocs serve`
3. Set config to `strict:true`
4. Change URL to `filename#target`
5. Live reload is not stopped.

### Package versions

* Python:  3.6.1
* MkDocs:  1.0.4
* Theme: Material for MkDocs 4.4.0

**Comment by waylan** [comment]
This is correct behavior, Strict mode only confirms internal links and all internal links *must* include the file extension. Any link which does not include the file extension is assumes to be something other than an internal link and is not checked.

**Comment by martinbira** [comment]
Noted! Will close the issue.

**Comment by martinbira** [comment]
@waylan 
Before opening another issue regarding Strict Mode again I thought I'd post a thought here. I've been thinking a bit about it and undefined links lately. I posted to the Google Group but it does not seem that active and I haven't found an issue directly related to this here.

To facilitate link re-use and increase findability for our documentation contributors, all our links are as references and are declared at the bottom of each `.md file`, such as:  

`[bar]: ../my/target.md "It's an alt text"`

Strict mode notices when the link target is incorrect when using references, but if my reference, `[bar]`, is missing or incorrect, strict mode does not catch this. Basically: 
This [foo][bar] will render the text as it is written if I forget to declare the reference entirely or if I misspell it as `[barrr]: ../my/target.md`

Is this intended behaviour?

**Comment by waylan** [comment]
Yes, that is intended behavior. MkDocs is not a Markdown linter. However, when building, it needs to transform links. To do so, it looks up the path in the collection of pages and then uses the built URL for that page. If it is not able to find a matching page, it raises a warning. Of course, if there is no link for `[bar]` defined, then it doesn't transform that link and therefore can't check it. If you want to lint your Markdown, then I would suggest a [linting tool](https://github.com/DavidAnson/markdownlint).
