### ISSUE TITLE
Feature request: Compile other custom error pages

### ISSUE THREAD

**Issue by StephenTaylor-Kx** [mkdocs/mkdocs#1856]
Parts of our site (covering licensed add-ons) are protected by basic authentication. We want to replace the webserver’s default 401 error page with a custom page, as we already do for 404s. 

Specifically: where `custom_theme/401.html` now compiles `site/404.html` a sibling file `custom_theme/xxx.html` will compile `site/xxx.html`. 

A partial workaround: writing `docs/401.md` compiles `site/401/index.html`. This is only partial, because the way the file is served makes the nav links relative to the referring page, not the site root.

**Comment by waylan** [comment]
This should already be possible. You simply need to list the templates in the [theme.static_templates][1] config setting. As long as the filename follows the pattern `xxx.html` (where `xxx` is a three digit number), and the template is available in the theme dir or `theme.custom_dir` MkDocs will recognize it as an error template and built it correctly.

[1]: https://www.mkdocs.org/user-guide/configuration/#static_templates

**Comment by StephenTaylor-Kx** [comment]
Excellent – thank you! 

I take it the default value of `static_templates` is `404.html`, as I previously had no `static_templates` section. 

Hadn’t connected the custom error page with static templates; might have found this without help if the [example](https://www.mkdocs.org/user-guide/configuration/#theme) had mentioned `404.html`.

Again, thank you for the swift response.

**Comment by waylan** [comment]
> I take it the default value of `static_templates` is `404.html`, as I previously had no `static_templates` section.

The default is [defined][1] by the theme. In the case of the included themes (`readthedocs` and `mkdocs`), the default happens to be `404.html`. However, other themes may or may not include that as a default.

> might have found this without help if the example had mentioned `404.html`.

Fair point. Of course, PRs are welcome to improve the documentation.

[1]: https://www.mkdocs.org/user-guide/custom-themes/#static_templates
