### ISSUE TITLE
Readthedocs theme serves css from root, not site_url

### ISSUE THREAD

**Issue by ayjayt** [mkdocs/mkdocs#1858]
I have a site_url set to "https://dev.mysite.com/mkdocs/" but readthedocs theme is still trying to serve css from "/css/*.css". I'd expect it to serve it from "/mkdocs/css/*.css".

Thanks for your time,

**Comment by waylan** [comment]
Actually is serves the CSS from the relative URL `css/theme.css` (not the lack of slash at the start, which makes it a relative URL, not an absolute URL):

```html
<link rel="stylesheet" href="css/theme.css" />
<link rel="stylesheet" href="css/theme_extra.css" />
```

At least that is what is used from the homepage. From a nested page (such as `/about/contributing/` in my test) you might find:

```html
<link rel="stylesheet" href="../../css/theme.css" />
<link rel="stylesheet" href="../../css/theme_extra.css" />
```

And that will give you a relative URL to the same files. It doesn't matter what the `site_url` is, it should always point to the correct relative location. If that is not happening for you, please use your browser's `view source` tool and provide the HTML you are getting and the URL of the page which that HTML appears in.

**Comment by ayjayt** [comment]
Alright, so I've attached the logs, command, and source (as txt if github didn't like the extension),
It's listening on localhost:8050 which is being served by reverse proxy @ mkdocs.ajpikul.com/mkdocs w/ password `dev`.

If I don't serve it off a subdirectory (ie just a subdomain), then I get relative paths.

[mkdir.log](https://github.com/mkdocs/mkdocs/files/3572242/mkdir.log)

[source.txt](https://github.com/mkdocs/mkdocs/files/3572245/source.txt)
[mkdocs.sh.txt](https://github.com/mkdocs/mkdocs/files/3572246/mkdocs.sh.txt)
[source.txt](https://github.com/mkdocs/mkdocs/files/3572247/source.txt)

**Comment by ayjayt** [comment]
I found some confounding issue with the reverse proxy so put this on hold... I'll resolve it by the end of tomorrow and either ping you again and leave it open with further info or I'll detail the issue/solution here and close it. If that's okay.

**Comment by waylan** [comment]
> It's listening on localhost:8050 which is being served by reverse proxy 

If you are using the included server, this is not a supported use case and is not guaranteed to work. The dev server is only for development on the local machine. It is not expected to serve anything outside of that. Please use a real server to serve the built site. We will not "fix" any  issues related to this use case.

**Comment by ayjayt** [comment]
I'm just surprised that the HTML generator isn't somehow seperated from the dev server.. I feel like it should always gennerate the same HTML.
