### ISSUE TITLE
"unfolded by default" section in nav

### ISSUE THREAD

**Issue by smarie** [mkdocs/mkdocs#1861]
Is there a way to configure the `nav` so that a section with sub-pages appears "unfolded" by default ? For example the "examples/recipes" section in https://smarie.github.io/python-valid8/

**Comment by waylan** [comment]
That would be a theme specific feature. It is not supported in the two included themes (`mkdocs` and `readthedocs`). For other themes, you would need to check with the specific theme you are using.

Regardless, note that there is no way to associate any settings/config with individual items in the `nav` in the `mkdocs.yml` config file. Therefore, if a theme did offer such a feature, that theme would need to provide some other mechanism for the user to define which section(s) should be "unfolded by default." I'm sure it's possible, but I suspect you will not find many, if any, themes which offer such a feature.

There are no plans to add such a feature to the included themes.

**Comment by smarie** [comment]
Too bad...
But thanks for the fast answer !
