### ISSUE TITLE
Fix `mkdocs` theme inheritance

### ISSUE THREAD

**Issue by waylan** [mkdocs/mkdocs#1865]
In #1597 we updated Bootstrap from 3.0.3 to 4.1.3. However, when we did so, we renamed some files (`css/bootstrap-custom.min.css` => `css/bootstrap.min.css` and `js/bootstrap-3.0.3.min.js` => `js/bootstrap.min.js`). The problem is that other themes inherit from the `mkdocs` theme with the old file names. The renaming in #1597 breaks those themes. 

On the one hand, the new names make more sense. On the other hand, we promised forward compatibility with version 1 and there is no easy way (that I'm aware of) to gracefully deprecate the old filenames. We need to resolve this conflict before releasing version 1.1. In other words, this is a blocking issue to releasing version 1.1.

I see a few possibilities:

1. Revert the filenames. Yes, that means a file named `bootstrap-3.0.3.min.js` would actually contain a different version of Bootstrap, but it would be the easy fix."
2. Leave the change in-place and document it for third party themes. In practice, this probably would not be too disruptive as the only themes I'm aware of which make use of inheritance are [mkdocs-bootswatch][1] and [mkdocs-bootstrap][2], both of which are maintained by the MkDocs team.
3. Some other solution I haven't thought of.

If we go with option 1, then a PR to this repo would address the issue. If we go with option 2, then we would need a PR updating the release notes here as well as a PR each for mkdocs-bootswatch and mkdocs-bootstrap.

[1]: https://github.com/mkdocs/mkdocs-bootswatch
[2]: https://github.com/mkdocs/mkdocs-bootstrap

**Comment by waylan** [comment]
For an example of how a theme inherits from the `mkdocs` theme, see mkdocs/mkdocs-bootstrap#22. In that PR, all common files between the two themes were removed from the child theme and the [mkdocs_theme.yml][1] config file was updated to indicate that the theme inherits from `mkdocs`. The only files remaining are the ones which override/replace the behavior in the parent theme.

The problem exists in the [main.html][2] template where `styles` and `libs` blocks are defined which override the blocks from the `mkdocs` theme. In each block, the old filenames are used. But in the current codebase, this would result in 404s.

[1]: https://github.com/mkdocs/mkdocs-bootstrap/pull/22/files#diff-1148036bbce8b114082a6d03e4e3cea4
[2]: https://github.com/mkdocs/mkdocs-bootstrap/pull/22/files#diff-76ffc1343ec2342f4ca2cdaa96038bc7

**Comment by trel** [comment]
are symlinks an (evil) option?

**Comment by waylan** [comment]
> are symlinks an (evil) option?

An interesting hack, which I hadn't considered. Not sure if I like it or not. Regardless, I foresee 2 possible issues with this:

1. How to we do symlinks with a PyPI release? Its easy with git, but most users install from PyPI.
2. We try to maintain the same behavior across all platforms. How would this work on Windows?

Maybe there are ways to work around these issues but I don't know what they are and haven't looked into it.

**Comment by waylan** [comment]
> We need to resolve this conflict before releasing version 1.1. In other words, this is a blocking issue to releasing version 1.1.

Interestingly, all but one of the open issues in the [1.1 milestone][1] are related to the `mkdocs` theme. The time I have to give is very limited these days (all I have time for is reviewing PRs), so any help from others to do the work is appreciated. 

[1]: https://github.com/mkdocs/mkdocs/milestone/11

**Comment by Ajwerth** [comment]
I think going with option 2 makes the most sense, having a file name specify one version and then having code from a different version could potential cause more confusion and headaches for others down the line than having to update their version of a theme. 

So I guess the question is how bad would it be to go back on the promise forwards compatibility?

Ultimately its your decision but I'm willing to help out with either of the options. I'm also happy to help out with the 2 themes that will need to be updated if you go with option 2.

**Comment by waylan** [comment]
@Ajwerth if your willing to do the work on option 2, I'll be happy to review it. The holdup for me is that I simply haven't had the time to do the work.

**Comment by Ajwerth** [comment]
Sure thing I'll take this one.

**Comment by Ajwerth** [comment]
@waylan I updated the styling section of the docs and opened a PR #1897.

I'll read through more of the docs to see if its relevant to mention anywhere else, let me know if there are any oth specific sections that you think should make mention of this change.

**Comment by jimporter** [comment]
One option for long-term support might be to copy the "classic" mkdocs theme somewhere else so people can just inherit from that instead. This would give people a simple way to update their theme so it works long-term: just change the base to `mkdocs-classic`.

As an example of a place where this would be helpful, the Amelia and Readable themes in mkdocs-bootswatch don't have Bootswatch 4 versions (not that I can tell, anyway), so they can't inherit from the new mkdocs theme; they either need to inherit from a hypothetical `mkdocs-classic` or stop inheriting at all.

**Comment by marcelstoer** [comment]
@waylan you just referenced this from #588. This comment is OT here but that other issue is now locked. The link to the 1.1 milestone is wrong; it should be `/milestone/11` rather than `/milestone/1.1` in the URL.

**Comment by jimporter** [comment]
@waylan in #588, you mentioned that fixing this was a priority for releasing v1.1 of MkDocs. I think my PRs (https://github.com/mkdocs/mkdocs-bootstrap/pull/28 and https://github.com/mkdocs/mkdocs-bootswatch/pull/58), plus my "classic" fork of the Bootstrap themes (https://github.com/jimporter/mkdocs-bootswatch-classic) should resolve this issue.

Just let me know if there's anything I should change in those PRs. Once things are ready, I'd be happy to hand over the `mkdocs-bootswatch-classic` repo. In the meantime, I'll see if there's anything I can do about the other v1.1 blockers.

**Comment by waylan** [comment]
Great. I'll review those when I get some time.
