### ISSUE TITLE
Can I override the template used to render a specific page using page metadata?

### ISSUE THREAD

**Issue by jduprey** [mkdocs/mkdocs#1866]
I feel certain I read this somewhere under theme customization, can I override the template used to render a specific page using page metadata?

e.g.
```
---
title: ...
description: ...
template: page-template-1
---

# Title
This page is supposed to be rendered using `page-template-1`
...
```

**Comment by waylan** [comment]
Yes, as documented on the [Writing Your Docs][1] page. If the theme doesn't already contain the templates you want to use, you'll need to use the [custom_dir][1] to provide your templates.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data
[2]: https://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme-custom_dir

**Comment by jduprey** [comment]
Thank you!  Yes. That was it, I read it, closed the page and then couldn't find it again.  My eyes must have skipped over it 10 times.
