### ISSUE TITLE
Navigation Page tree- How can we include all docs under a directory?

### ISSUE THREAD

**Issue by adibrastegarnia** [mkdocs/mkdocs#1868]
Hi
Is there a way that we can include all of the docs under on directory to avoid list all of the markdown files (i.e. using `nav` option in the mkdocs yaml file)?

For example, suppose under docs, we have a folder name `foo` and under that directory we have test1.md, test2.md files. I would like to include all markdown files under the directory without listing all of them.

**Comment by waylan** [comment]
This is a duplicate of #714.
