### ISSUE TITLE
Theme "united" not supported by my mkdocs version

### ISSUE THREAD

**Issue by Shantha93** [mkdocs/mkdocs#1870]
Can somebody please help me out with the version of mkdocs that will support this theme. I need to some how build my md files defined for this theme.

**Comment by waylan** [comment]
If you are referring to [this theme](https://mkdocs.github.io/mkdocs-bootswatch/#united), then the latest version of the theme should work just fine with the latest version of MkDocs. If it’s not then I would suggest filling a bug report with that theme. Be sure to include the version you have installed of both MkDocs and the theme. It would also help to include any errors you are getting. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
