### ISSUE TITLE
Support additional directories to be included with `docs_dir`

### ISSUE THREAD

**Issue by deuill** [mkdocs/mkdocs#1873]
(Apologies if this has already been answered in previous issues, I couldn't find anything relevant).

I'm attempting to integrate `mkdocs` in a project which already has a set structure, and documentation at the level of each module (in the form of a `README.md` file). This setup has been good, as it helps in both organization, and with keeping the documentation current with regards to code changes.

For example, this is what the project tree looks like:

```
├── doc
│   ├── about.md
│   └── index.md
├── example
│   ├── simple
│   │   └── ...
│   └── README.md
├── lib
│   ├── http
│   │   ├── ...
│   │   └── README.md
│   ├── log
│   │   ├── ...
│   │   └── README.md
│   └── README.md
├── mkdocs.yml
└── README.md
```

Currenty, `mkdocs.yml` is configured with a `docs_dir: doc` directive, which is where user-level documentation, guides, etc. will be placed, but I'd love to be able to include files in the `example` and `lib` directories above, which I currently cannot. That is, a `nav` directive such as this:

```yaml
nav:
  - General:
    - About: about.md
    - Examples: example/README.md
  - Library:
    - About: lib/README.md
```

Won't pull in these `example` and `lib` directories.

Is there any way to pull these additional directories in, as they might've been sub-directories of the `docs_dir` directory, without resorting to symlinks or any such hacks?

**Comment by waylan** [comment]
You can use symlinks, which is expressly supported (we don't consider it a hack). Or you could create a plugin (or use an existing third party plugin if a suitable one exists) which allows you to include outside files. In fact, this is one of the anticipated use cases for the [on_files][1] event. That being the case, we do not anticipate adding such a feature to MkDocs itself. This is something that can be addressed by plugins.

[1]: https://www.mkdocs.org/user-guide/plugins/#on_files

**Comment by deuill** [comment]
I guess symlinks are orthogonal to `edit_uri` as well, though perhaps strange outside the context of `mkdocs`. Thank you for the quick reply and the `on_files` plugin recommendation, I'll work with both solutions and see which fits best!
