### ISSUE TITLE
mkdocs start error following pages exist in the docs directory, but are not included in the "nav" configuration:

### ISSUE THREAD

**Issue by dangtd77** [mkdocs/mkdocs#1875]
I get the following error when I start mkdocs.  Now this works fine on one computer and not another. One computer I am running python 3.5.1 and one I am running 3.7.4.  I think that is the only difference.  

This is the error
```
mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - index.md
  - management.md
  - tech.md
WARNING -  A relative path to 'docs/index.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING -  A relative path to 'docs/tech.md' is included in the 'nav' configuration, which is not found in the documentation files
[I 191002 17:30:02 server:296] Serving on http://127.0.0.1:8000
[I 191002 17:30:02 handlers:62] Start watching changes
[I 191002 17:30:02 handlers:64] Start detecting changes
[I 191002 17:30:05 handlers:135] Browser Connected: http://localhost:8000/
[I 191002 17:30:06 handlers:135] Browser Connected: http://localhost:8000/
```

this is what my .yml file looks like
```
site_name: Interview

nav:
- HR: 'docs/index.md'
- TECH: 'docs/tech.md'
- Management: '/docs/management'
```

Again, this is working on one computer.  I tried to uninstall phyton 3.7 and install the same as I have on my other computer but 3.5.1 have been superseded and I couldn't seem to get an exe file for it
pip version 19.2.3 on both computers 

So when I go to localhost:8000 the first page shows up "index", but if I go to the nav on the page and click the HR item, I get a 404, all of the nav items I get a 404. 

Thanks for any help

**Comment by waylan** [comment]
If you indent the nav items in the config file, does that resolve the issue. My guess is that you have a different version of PyYAML installed on each system which is parsing the config file differently. For the record, well for,Ed yams would require the indentation. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangtd77** [comment]
I get the same error with the below config: 

```
site_name: Interview

nav:
      - HR: 'docs/index.md'
      - NBCTECH: 'docs/tech.md'
      - Management: '/docs/management'
```
Python 3.7.0a4 (v3.7.0a4:07c9d85, Jan  9 2018, 06:16:56) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import request
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'request'

**Comment by waylan** [comment]
I just looked closer at your config. You must not include `docs/` in the `nav`. All documents are assumed to be in `docs/` already. The nav is the one place in the config where paths are not relative to the config file. Rather, they are relative tot he `docs_dir`.

**Comment by dangtd77** [comment]
So I just tried both ways and still getting the same error
```
site_name: Interview

nav:
      - HR: '/index.md'
      - TECH: '/tech.md'
      - Management: '/management'
```
```
site_name: Interview

nav:
      - HR: 'index.md'
      - TECH: 'tech.md'
      - Management: 'management'
```
Why do you think it works on my other computer with the `docs/` in there?

**Comment by waylan** [comment]
As documented, all paths must be relative, so the paths which start with a slash would be wrong. Also I note that you are missing the file extension for the third file (it should be `management.md`.)

I would expect the following to work:

```yaml
nav:
    - HR: 'index.md'
    - TECH: 'tech.md'
    - Management: 'management.md'
```

That assumes your files are arranged like so:

```
- mkdocs.yml
- docs/
    - index.md
    - tech.md
    - management.md
```

If you are still having problems, please provide the **entire** output of all of the following commands on both the working and the non-working systems:

```
python --version
mkdocs --version
mkdocs build
```

**Comment by dangtd77** [comment]
Yeah, still having the problem.  not sure why the .md was missing on management, its there in mkdocs.yml  most of missed it when coping. 

Here is the output, mkdocs --version didn't work

```
C:\Users\td\interview>python --version
Python 3.7.0a4
```
```
C:\Users\td\interview>mkdocs --verion
Usage: mkdocs [OPTIONS] COMMAND [ARGS]...
Try "mkdocs -h" for help.

Error: no such option: --verion
```
```
C:\Users\td\interview>mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: C:\Users\td\interview\site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - index.md
  - management.md
  - tech.md
```
```
C:\Users\td\interview>mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - index.md
  - management.md
  - tech.md
[I 191003 16:30:31 server:296] Serving on http://127.0.0.1:8000
[I 191003 16:30:31 handlers:62] Start watching changes
```

Thanks again for your help!!

**Comment by waylan** [comment]
You misspelled “version”.  Please try `mkdocs version` again. Also what do you get for the following?

```
ls
ls docs/
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangtd77** [comment]
You know what I noticed, the folder `site`, which I don't have on my other computer, has the below structure.

```
- sites/
	- index.html 
	- tech/
		- index.html
	- management/
		- index.html
```

so obvioulsy... 
index under sites having index.md content
tech/index.html having tech.md content
management.html having management.md content



```
C:\Users\td\interview>mkdocs --version
mkdocs, version 1.0.4 from c:\users\dangt\appdata\local\programs\python\python37-32\lib\site-packages\mkdocs (Python 3.7)
```

```
C:\Users\td\interview>ls
'ls' is not recognized as an internal or external command,
operable program or batch file.
```


```
C:\Users\td\interview>ls docs
'ls' is not recognized as an internal or external command,
operable program or batch file.
```

I much appreciate the help.

**Comment by waylan** [comment]
I'm sorry, I should have noticed you have Windows paths there. Instead of `ls` you should be using `dir`:

```
dir
dir docs`
```

Also, the structure of the `site` dir is not relevant to the problem. That is related to the [use_directory_urls][1] setting.

[1]: https://www.mkdocs.org/user-guide/configuration/#use_directory_urls

**Comment by dangtd77** [comment]
no problem, here you go

```
C:\Users\td\interview>dir
 Volume in drive C is Local Disk
 Volume Serial Number is 0A18-A088

 Directory of C:\Users\td\interview

10/03/2019  04:29 PM    <DIR>          .
10/03/2019  04:29 PM    <DIR>          ..
10/03/2019  06:27 PM    <DIR>          docs
10/03/2019  04:30 PM               126 mkdocs.yml
10/03/2019  04:29 PM    <DIR>          site
               1 File(s)            126 bytes
               4 Dir(s)  142,350,467,072 bytes free
```

```
C:\Users\td\interview>dir docs
 Volume in drive C is Local Disk
 Volume Serial Number is 0A18-A088

 Directory of C:\Users\td\interview\docs

10/03/2019  06:27 PM    <DIR>          .
10/03/2019  06:27 PM    <DIR>          ..
09/30/2019  09:26 PM            15,294 index.md
10/01/2019  03:42 PM                 0 management.md
10/03/2019  06:29 PM            19,377 tech.md
               4 File(s)         53,298 bytes
               2 Dir(s)  142,340,894,720 bytes free
```

**Comment by waylan** [comment]
I have no idea what the problem is. The fact that it works on another system suggests the problem is with the system itself, not with MkDocs. Perhaps your filenames are being encoded with some non-standard encoding or something?

**Comment by alper4** [comment]
> 
> 
> Yeah, still having the problem. not sure why the .md was missing on management, its there in mkdocs.yml most of missed it when coping.
> 
> Here is the output, mkdocs --version didn't work
> 
> ```
> C:\Users\td\interview>python --version
> Python 3.7.0a4
> ```
> 
> ```
> C:\Users\td\interview>mkdocs --verion
> Usage: mkdocs [OPTIONS] COMMAND [ARGS]...
> Try "mkdocs -h" for help.
> 
> Error: no such option: --verion
> ```
> 
> ```
> C:\Users\td\interview>mkdocs build
> INFO    -  Cleaning site directory
> INFO    -  Building documentation to directory: C:\Users\td\interview\site
> INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
>   - index.md
>   - management.md
>   - tech.md
> ```
> 
> ```
> C:\Users\td\interview>mkdocs serve
> INFO    -  Building documentation...
> INFO    -  Cleaning site directory
> INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
>   - index.md
>   - management.md
>   - tech.md
> [I 191003 16:30:31 server:296] Serving on http://127.0.0.1:8000
> [I 191003 16:30:31 handlers:62] Start watching changes
> ```
> 
> Thanks again for your help!!

3.7.0.a4 is an alpha version of Python 3.7, you should not be using it in production.

**Comment by waylan** [comment]
> 3.7.0.a4 is an alpha version of Python 3.7,

Good catch. I missed that. Based on this, I'm closing this issue.

**Comment by dangtd77** [comment]
I'm using this now: 
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

still having the name problem

**Comment by waylan** [comment]
Could you please copy and past the content of your `mkdocs.yml` file into a comment?

**Comment by dangtd77** [comment]
Let me know if you need anything else

```
site_name: Interview

nav:
- 'docs/index.md'
- 'docs/tech.md'
- 'docs/management'
```

**Comment by froschdesign** [comment]
@dangtd77 
Please see in documentation the [explanation for the navigation configuration](https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation):

> A simple navigation configuration looks like this:
>
> ```yaml
> nav:
>   - 'index.md'
>   - 'about.md'
> ```
> All paths in the navigation configuration must be relative to the `docs_dir` configuration option. If that option is set to the default value, `docs`, the source files for the above configuration would be located at `docs/index.md` and `docs/about.md`.

This means your navigation configuration is wrong. Remove `docs` from your pages and use only `index.md`, `tech.md`, etc.

**Comment by waylan** [comment]
@froschdesign is correct. You should have:

```yml
site_name: Interview

nav:
    - index.md
    - tech.md
    - management.md
```

**Comment by dangtd77** [comment]
So that is interesting, we have tried it both ways, please see above for reference. 

But now when I removed the docs/.. path, the second nav item isn't showing up correctly, see image below. 

![asdf](https://user-images.githubusercontent.com/30243361/67601687-f57ca680-f742-11e9-80aa-5305ea10f0db.PNG)

I just added a four nav item to see if that would make a difference and it also doesn't show up, see error below.

This is the error message I get when I do not have docs/ path
```
mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - management.md
  - sitecore.md
WARNING -  A relative path to 'management' is included in the 'nav' configuration, which is not found in the documentation files
WARNING -  A relative path to 'sitecore' is included in the 'nav' configuration, which is not found in the documentation files
[I 191025 16:20:06 server:296] Serving on http://127.0.0.1:8000
[I 191025 16:20:06 handlers:62] Start watching changes
[I 191025 16:20:06 handlers:64] Start detecting changes
```
This is what it looks like when I added four nav item
![asdf1](https://user-images.githubusercontent.com/30243361/67602111-f104bd80-f743-11e9-8679-522adaaf7565.PNG)


Again, this is working on my other computer and this is how my mkdocs.yml file looks
```
site_name: Interview
nav:
    - 'docs/index.md'
    - 'docs/tech.md'
    - 'docs/management.md'
    - 'docs/sitecore'
```

and this is the mkdocs serve on my other computer.  it works just fine
```
mkdocs serve
INFO    -  Building documentation...
WARNING -  Config value: 'nav'. Warning: Unrecognised configuration name: nav
INFO    -  Cleaning site directory
[I 191025 16:27:19 server:283] Serving on http://127.0.0.1:8000
[I 191025 16:27:19 handlers:60] Start watching changes
[I 191025 16:27:19 handlers:62] Start detecting changes
[I 191025 16:27:30 handlers:133] Browser Connected: http://127.0.0.1:8000/
```

This is what it looks like on my other computer 

![asdf2](https://user-images.githubusercontent.com/30243361/67602848-86ed1800-f745-11e9-884e-700aaefd18ac.PNG)

**Comment by waylan** [comment]
Are you sure that all lines of the nag include the file extension? Because in every example you posted at least one line is missing `.md`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangtd77** [comment]
yeah, so that was it.  I guess reinstalling fixed my initial problem and the problem was I was missing the .md on the last nav items.  weird because it works on my other computer without the .md.  THANK YOU FOR YOUR HELP

**Comment by ssbarnea** [comment]
I have a suspicion that there is still a bug in this area.

```yaml
nav:
  - Rules:
      - rules/index.md # <-- failed
```

```yaml
nav:
  - Rules:
      - index: rules/index.md # passed
```

I mentioned these in case someone else ends up with same issue. If that also fixes their problem, we can probably agree that the bug is still here.

**Comment by smhr** [comment]
I also have this issue with `mkdocs, version 1.5.3` and `Python 3.12.0`.

My directory structure is:

```
├── docs
│   ├── index.md
│   └── softwares
│       └── modules.md
├── mkdocs.yml
├── README.md
└── requirements.txt

2 directories, 5 files
```

This `mkdocs.yml` works correctly:

```yml
site_name: Documentation Project
nav:
   - Home: index.md
   - softwares:
       - Modules: 'software/modules.md'
theme: material
```
But this one:
```yml
site_name: Documentation Project
nav:
   - Home: index.md
   - softwares:
       - Modules: 'modules.md'
theme: material
```
gives the following error:
```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/hosaini/work/nhpcc-docs/site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
             - softwares/modules.md
WARNING -  A relative path to 'modules.md' is included in the 'nav' configuration, which is not found in the documentation files.
INFO    -  Documentation built in 0.35 seconds
```

**Comment by pawamoy** [comment]
It does not sound like a Material problem. Please open a new issue here with all the necessary information: your MkDocs.yml, your directory and files structure, your MkDocs and Python versions, and your operating system.

**Comment by pawamoy** [comment]
@smhr I don't see any issue in your comment. You must indeed use the path `software/modules.md`, not just `modules.md`.
