### ISSUE TITLE
Markdown literal blocks do not result in literals when they contain templating symbols.

### ISSUE THREAD

**Issue by tasadar2** [mkdocs/mkdocs#1887]
We have attempted to escape these symbols as html, backslashes, doubling braces, and other techniques. But all the typical escaping mechanisms result in displaying the escape symbols.
Is there an available method to escape the templating mechanism?

For example, the following literal block
```
    ```yml
    store:
      key: plugins-{{ epoch }}
    ```
```
is rendered by mkdocs as the following
```
    ```yml
    store:
      key: plugins-
    ```
```
The expected result would be to show exactly what is contained within the literal block.

**Comment by waylan** [comment]
Hmm, MkDocs does not run any templating again Markdown content, so this shouldn't be happening. Are you using any third-party Markdown extensions or MkDocs' plugins?

Also, could you please provide the HTML generated for the code block? Perhaps you will need to use your browser's "view source" feature. Please copy the HTML as text and place it in a code block in a comment.

**Comment by tasadar2** [comment]
You are correct, I did not realize this project was using plugins. For reference, the problem plugin was `macros` which relies on jinja. The source in my example could be escaped with `key: plugins-{% raw %}{{ epoch }}{% endraw %}`.
