### ISSUE TITLE
Plugin development question

### ISSUE THREAD

**Issue by jldiaz** [mkdocs/mkdocs#1891]
First of all, thank you for creating and maintaining mkdocs. It is a wonderful tool. 

I wrote a plugin whose goal is to generate "on the fly" a Tags page, collecting all tags declared in the Yaml header of the `.md` files in the documentation.

If you are interested in a more detailed description, or the code, you can find it at https://github.com/jldiaz/mkdocs-plugin-tags

I had some doubts about which would be the best approach to do it.

* Use the `on_files()` event, to "manually" parse the yaml headers, collect the relevant data, create a `tags.md` file with the data found, and add that file to the `files` list. This is the approach I used, and it works, but I'm not satisfied having to do all the work "manually", since mkdocs already does the Yaml metadata extraction (but still not at this stage).
* Use the `on_page_markdown()` event, to have access to `page.meta`, which simplifies the extraction of the yaml data, and looks more logical. In addition, it provides a `page.title` which would be difficult to obtain by the first method.

However, in the second method, although I can collect all the relevant data in a easier way, I don't know how to generate the final `tags.md` file. I guess that `on_post_build()` could be a good place, but this event does not receive a  `files` parameter, and it is nevertheless too late to add any file, since all have been processed.

Any idea?

PS: Please excuse me for posting a question here. I don't know which would be the proper forum. The google group is not longer working, and I think that the irc channel is not a good place for elaborated explanations (and also, the question and the answers would be lost, since there is no log in the channel).

**Comment by waylan** [comment]
If you look at the [search][1] plugin which ships with MkDocs you will notice that it makes use of multiple events so that it can do various bits and pieces of its functionality at the appropriate time in the build process. Any common state among those different events are simply stored on the `plugin` class instance. In fact, the `on_pre_build` event simply creates `self.search_index` which is an empty index instance. Then, `on_page_context` adds the content for each page to that index one at a time, and `on_post_build` writes the index to disk as a single file after all pages have been processed. I would image your plugin would work very similarly, although perhaps using different events.

Note also that the `search` plugin does not add files to the files collection, but simply writes directly to disk itself (although it does use the `on_config` event to add `static_templates` and `extra_javascript` entries). Depending on how your extension works, that may or may not be appropriate for you.

Regarding the Google Group, the issue with that was brought to our attention in #1889 and should be resolved now. If you are still having trouble accessing the group, please follow us in that issue.

Hope that helps.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/contrib/search/__init__.py

**Comment by jldiaz** [comment]
Thank you, waylan. I understand that the strategy followed by search plugin is very similar to the second approach in my question. I can also use different events to create data, fill it, and finally generate the "tags" page. However, building that page in the `on_post_build` event has some drawbacks:

* The page is generated in HTML instead of markdow. In addition to the syntax (I would prefer to use a markdown template, and I think it would be preferable for the final user too), this causes more problems:
* The page will not integrate with the theme (unless the theme has special support for the "tags page", and currently no one has it, obviously). Generating the tags page in markdown causes it to be processed as content by mkdocs engine, and thus it will appear automatically with header, footer, nav, and toc.
* The page will not appear in the nav (unless I add it somehow in the `on_nav` event)

So I devised a third approach, which will have the best of both worlds:

* `on_files` I can add the `tags.md` file (if it exists) to the files list, so it is processed even if it is not in the docs folder. I can also store a hash of the file contents.
* `on_page_markdown` I can collect al appropriate metadata
* `on_post_build` I can overfwrite the `tags.md` file with the actualized metadata,  **and** if the contents changed (which I can check via the hash), I trigger a new build.

Is it possible to trigger a new build? Do you find this approach reasonable?

PS: Google Group works again. Would it be preferable to move this thread to the group?

**Comment by waylan** [comment]
If that works for you, you can do whatever you want. It is your plugin. Personally, I find generating Markdown to be too limiting and prefer to generate HTML directly. I would have expected you to use a [static_template][1]. Also, as a reminder, you can include non-pages in your `nav` config. Of course, that won't work for an auto-generated nav. But then there is the `on_nav` event which could be used to insert an item into the nav.

The thing about the above approach is there is no need for a second build. As a reminder, some users report having thousands of pages in a single project. They would find the additional slowdown of waiting for two builds to be unacceptable.  Besides, Its not clear to me how you would initiate a second build from a plugin.

[1]: https://www.mkdocs.org/user-guide/configuration/#static_templates

**Comment by jldiaz** [comment]
@waylan Thank you again. To initiate a second build I did a `mkdocs.commands.build.build(config)` (passing as `config` the same received in `on_post_build`. Of course that could cause a recursion loop, but I only run that command if the "tags.md" file changed.

Currently it is working, but I admit that the second build is a clumsy solution. I've read about `static_template` but didn't fully understand its purpose, nor how to inject the metadata collected by my lugin. I have to experiment a bit and try to find some plugin/theme which uses it.

**Comment by waylan** [comment]
For an example of a `static_template` see the [site index][1] for Python-Markdown, which is defined in the [mkdocs-nature][0] theme in [sitemap.html][2]. That template loops through all items in the nav and lists them in a nested list in the body of the page. Note that the template makes use of template inheritance so, while its not defined within the template, the page gets the standard page header, footer, etc.

As mentioned previously, the search plugin also optionally includes support for a static_template. The `readthedocs` theme included with MkDocs makes use of it with its [search.html][3] page.

[1]: https://python-markdown.github.io/sitemap.html
[0]: https://github.com/waylan/mkdocs-nature
[2]: https://github.com/waylan/mkdocs-nature/blob/master/nature/sitemap.html
[3]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/search.html

**Comment by azaroth42** [comment]
@jldiaz I have almost the exact same scenario, except I want to build an index page with pointers to the examples in the documentation. Then if you know which class or property you're looking for, you can go to the index and get pointers to all of them.

Did you come up with a more elegant solution than just building twice?
