### ISSUE TITLE
Changing Top Bar color

### ISSUE THREAD

**Issue by condor-the-bird** [mkdocs/mkdocs#1893]
Hi there, I configured the custom_dir option, cloned the default folder from this repository and managed to change fonts, link colors, but not the top bar color. Where is it in the base.css? Or is it imported from elsewhere?

**Comment by waylan** [comment]
I assume you are referring to the `mkdocs` theme. Note that `base.css` contains overrides to the defaults set in the `bootstrap.css` file. Therefore, not all rules are found in `base.css`, only those that differ from bootstrap's defaults. IIRC the top bar color is defined by bootstrap.

Regardless, I would suggest using your browser's "inspect" tool to get a list of all CSS rules applied to any element on a page. Depending on which browser you are using, you may need to enable your browser's dev tools to have access to the "inspect" tool.  See your browser's documentation for details.
