### ISSUE TITLE
URL names lose camel case on Netlify, but OK on local dev and on GitHub pages

### ISSUE THREAD

**Issue by matthewcornell** [mkdocs/mkdocs#1899]
I'm loving MkDocs - thanks for the cool tool!

I've explored deployment on both Netlify ( https://docs-zoltardata-staging.netlify.com/datamodel/ ) and GitHub Pages ( http://reichlab.io/docs.zoltardata/DataModel/ ), as well as local serving, and I see that the camel case name scheme we chose (e.g., `HomePage.md`), is not translating consistently to these sites. GitHub Pages and local serving do preserve the case, but Netlify does not:

- http://127.0.0.1:8000/HomePage/
- http://reichlab.io/docs.zoltardata/HomePage/
- https://docs-zoltardata-staging.netlify.com/homepage/

(Source is at https://github.com/reichlab/docs.zoltardata/ )

Would you please help me:

- Is this behavior wrong, i.e., should case be preserved?
- Why is Netlify different?
- Is there a configuration setting that makes it consistent on Netlify?
- What file naming convention do others in the community use? I see your own user guide ( https://github.com/mkdocs/mkdocs/tree/master/docs/user-guide ) uses lower case with hyphens.

Thanks very much.

**Comment by waylan** [comment]
I checked your Netifly hosted site and the URLs in the navigation are all CamelCased but when clicked on, the CamelCased requests get redirected to a lowercase version of the URL. To see what I mean, from the [homepage][1] look at the "next" link at the bottom right of the page. The URL for that link is `https://docs-zoltardata-staging.netlify.com/ModelDetailPage/`. Note that CamelCase is preserved (as it is for all internal links on all pages of the site). However, if you request that URL, the response returned is as follows (irrelevant headers omitted):

```
HTTP/2.0 301 Moved Permanently
location: /modeldetailpage/
```

Of course, your browser will automatically request the new location so the redirect is transparent to the user. This makes it easy to assume (incorrectly) that the lowercase URL was originally requested when the link was clicked. For the record, I used by browser's "inspect" tool to debug this.

It appears that Netifly does not allow any files on their service to use CamelCase, Presumably they are rewriting CamelCased filenames to lowercase on upload to their service. This is completely within the control of Netifly and not related to MkDocs at all. I have not used Netifly personally and therefore not familiar wiht the options they offer. You might want to check their documentation (and/or support) to see if they have a setting you need to change. If not, you could leave things as is (they do work with the redirects, after all) or you can switch to using lowercase for your filenames. The choice is yours.

As an alternative, I should note that Netifly is not actually altering filenames, but directory names. It may be there there policy is to require all directory names to be lowercase, but they will allow CamelCase file names. If that is the case, you could turn off MkDocs' config setting [use_directory_urls]. Then you would get `https://docs-zoltardata-staging.netlify.com/ModelDetailPage.html` as a URL The point being that `/ModelDetailPage.html` is a file name, while `/ModelDetailPage/` is a directory which the server interprets as a request for the file at `/ModelDetailPage/index.html`. On the other hand, this may make no difference if Netifly maintains the same policy of lowercasing filenames as it does for directory names.

[1]: https://docs-zoltardata-staging.netlify.com/homepage/

**Comment by matthewcornell** [comment]
Thanks for the awesome reply! Any thoughts re: *.md file name conventions?

**Comment by waylan** [comment]
> Any thoughts re: *.md file name conventions?

No not really, I know some people have strong options about that, but I'm not one of those people. MkDocs itself will work with whatever you choose.
