### ISSUE TITLE
Is there a way to copy raw static files into the generated site?

### ISSUE THREAD

**Issue by mikehearn** [mkdocs/mkdocs#1901]
I'd like to include non-mkdocs generated HTML into my static site, so I can include JavaDocs and the like. There doesn't appear to be any way to do this  as far as I can tell so far, other than editing the site dir after generation. But the `gh-deploy` command is indeed, so useful, that I'd really like to have mkdocs understand this pattern so I don't have to do the deploy manually.

**Comment by waylan** [comment]
Any non-Markdown files included in the `docs_dir` are copied as-is. Simply include the files in your `docs_dir` and they will be copied over.

If you would like to do anything outside of that, a [plugin][1] would address those needs. Personally, I'm surprised I don't see one listed on the [wiki][2] that does this already.

[1]: https://www.mkdocs.org/user-guide/plugins/
[2]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Comment by mikehearn** [comment]
Ah, I'm an idiot. It *does* work. Sorry. I think I was getting confused because I expected `mkdocs serve` to rebuild the site in the site directory, as it talks about cleaning the site directory and building the docs when it starts up. I looked inside it and didn't see my files being copied across, and I'd made a mistake in the URL I was opening so got a 404. Together these two things confused me. But experimenting more, I see that `mkdocs serve` must be using an in-memory site build or putting it somewhere else, as the site directory doesn't actually get created at all.

**Comment by waylan** [comment]
Yes, the `serve` command creates a temporary directory and does not use the `site` dir.

**Comment by DearVikki** [comment]
hhhhh
