### ISSUE TITLE
readthedoc theme not collapse inactive folders

### ISSUE THREAD

**Issue by laoshaw** [mkdocs/mkdocs#1904]
After I clicked an article, on the left all folders will be laid out, I would expect only the folder where the file is read will not be collapsed. This makes my left column super long. Tested with master branch, 1.0.4 release does not have this issue.

**Comment by waylan** [comment]
The `readthedocs` theme is a clone of the the default theme used by the Read the Docs service. Therefore, its behavior copies the upstream theme. The changes in the master branch were made to bring the theme inline with the behavior of the upstream theme. The only way we will change it is if you can demonstrate that the upstream theme behaves differently,

That said, there are a number of new settings available in the master branch for the theme. Perhaps one of them will address your concern. They are documented in [docs/user-guide/styling-your-docs.md][1]. Specifically, I would look at the `collapse_navigation` setting.

[1]: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/styling-your-docs.md#readthedocs

**Comment by laoshaw** [comment]
yes I tried that option and it did not help. also I believe the upstream readthedocs will not open all directories by default, it will only open the one that contains the page been read.

**Comment by chuckwagoncomputing** [comment]
I believe we are having the same issue at [rusEFI](https://wiki.rusefi.com/). Even worse, the sidebar automatically scrolls to the first opened folder. It's very annoying.

**Comment by oprypin** [comment]
This is fixed as https://github.com/mkdocs/mkdocs/issues/3292#event-11028761202

Try out mkdocs master and let me know if it works
```bash
pip install git+https://github.com/mkdocs/mkdocs.git
```
