### ISSUE TITLE
Encoded URLs not recognized as internal links

### ISSUE THREAD

**Issue by dlevene1** [mkdocs/mkdocs#1908]
Hey,

I'm trying to link images so in my editor and mkdocs serve, they work - but I can't get both to work due to the way the pages are being created/rendered.

An example is as follows;

Directory structure of
```
docs/manuals/version/guides/guide1.md
```
Inside guide1.md I have a relative link of
```
![](img/image2.png)
```
and the image resides in 
```
docs/manuals/version/guides/img/image2.png
```

This renders fine in my editor and makes sense.. also follows the directions here;
https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-images-and-media

But when I start up mkdocs serve, it doesn't work.. it also displays the following
```
WARNING -  Documentation file 'manuals/version/guides/guide1.md' contains a link to 'manuals/version/guides/img/image2.png' which is not found in the documentation files.
```
Then when I visit the mkdocs serve webpage and open the image in a new tab it has this URL.
```
http://localhost:8000/manuals/version/guides/guide1/img/image2.png
```
Which is a 404.

Its taken the page name and put it in the path to the image, which looks to be expected as the URL for the page is located here
```
http://localhost:8000/manuals/version/guides/guide1/
```
and the image is still located at this URL, its just missing the guide1 in the path below.
```
http://localhost:8000/manuals/version/guides/img/image2.png
```

I can make it so it works on the website, which is the important part, but then i need to manually modify the links etc..  Also, the WARNING message is still display even when the images correctly render in mkdocs serve

Any idea why this might be happening or what config may influence this generation?

```$ mkdocs -V
mkdocs, version 1.0.4 
```

Thanks
David

**Comment by waylan** [comment]
Could you please provide the HTML for the link to the image? I would like to see what path is being generated there.

**Comment by dlevene1** [comment]
Hey,

Here's a couple of links..  Let me know if you need any other information.

First one in the .md is
```
![Dynamic Port forwarding](./img/Tunnel%20-%20MobaXterm%20PR%20Tunnel.png)
```
second one is
```
![Prod Tunnel 1](img/Tunnel%20-%20MobaXterm%20PROD_1.png)
```

```
<img alt="Dynamic Port forwarding" src="./img/Tunnel%20-%20MobaXterm%20PR%20Tunnel.png" />
<img alt="Prod Tunnel 1" src="img/Tunnel%20-%20MobaXterm%20PROD_1.png" />
```

When open image in new tab it goes to.
http://localhost:8000/manuals/1.5/guides/AccessingDashboards/img/Tunnel%20-%20MobaXterm%20PR%20Tunnel.png
http://localhost:8000/manuals/1.5/guides/AccessingDashboards/img/Tunnel%20-%20MobaXterm%20PROD_1.png

**Comment by waylan** [comment]
Do you have the [use_directory_urls][1] setting defined in your `mkdocs.yml` config file? Any other custom settings?

[1]: https://www.mkdocs.org/user-guide/configuration/#use_directory_urls

**Comment by waylan** [comment]
Those links are URL encoded. I’m wondering if that is contributing to the problem. Could you post the warning messages for those links? That will show the path being used internally.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dlevene1** [comment]
use_directory_urls is not set - so would be using defaults.

```
$ grep use_dir mkdocs.yml
$
```

Found out the issue - in my .md files I was referencing the files with %20% i changed it to a space and it worked as expected. Looks like .md rendered files correctly seeing %20% as a space and convert it.. where when generating the pages it was taking it literally as %20% and not finding the file and pointing it to the wrong spot(?)

let me know if you need any more information but you should be able to reproduce this by having a picture filename with spaces in it and in the .md code reference the picture using %20%

**Comment by waylan** [comment]
I suspected that was the problem. However, it should work with encoded URLs, so this is a bug.

**Comment by dlevene1** [comment]
Thanks for your help! appreciate it.

**Comment by waylan** [comment]
I can't seem to replicate this. We already call [unquote][1] in all paths and we have [tests][1] for this very situation.

[1]: https://github.com/mkdocs/mkdocs/blob/7b68f7b828f29dffe2603117660bb9442d9348a3/mkdocs/structure/pages.py#L224
