### ISSUE TITLE
[readthedocs] limit headers level shown in side bar

### ISSUE THREAD

**Issue by rockandska** [mkdocs/mkdocs#1909]
Hi,

Is there anyway to limit the headers level shown in side bar with version 1.0.4?
Actually, the template show the top level too in sidebar but should not since it's only the title of the document.

Will be great to be able to set a min and max level.

Regards

**Comment by waylan** [comment]
The theme in version 1.0.4 is based on a very old version of the upstream theme and offers almost no customization. A number of updates have been added in #1594 which will be available in the next release.
