### ISSUE TITLE
Copy content of file instead of symlinks

### ISSUE THREAD

**Issue by NicolasMassart** [mkdocs/mkdocs#1912]
Hi, I have an issue with symlinked custom template files.
I read the few issues and PRs about wymlinks already done in this project but they don't seem to fox my issue.

## Context

I have a Git submodule in my projects with all the files they have in common. The submodule includes CI files, MD files, but also some mkdocs files like custom_theme html files.
These custom html files, overriding mkdocs default templates are symlinked from the /docs/custom_theme folder. I use symlinks as I want the files in my common submodules to be accessible in different places of my project and not in only one place. I for instance have readthedocs.yml that has to be at the root.

## Issue

With the default MkDocs, when I run `mkdocs build` or `mkdocs serve` it complains about the files it's not able to find:
```
mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/nicolas/Develop/doc.ethsigner/site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - index.md
Traceback (most recent call last):
  File "/Users/nicolas/Library/Python/3.7/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/mkdocs/commands/build.py", line 285, in build
    files.copy_static_files(dirty=dirty)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/mkdocs/structure/files.py", line 44, in copy_static_files
    file.copy_file(dirty)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/mkdocs/structure/files.py", line 178, in copy_file
    utils.copy_file(self.abs_src_path, self.abs_dest_path)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/mkdocs/utils/__init__.py", line 120, in copy_file
    shutil.copyfile(source_path, output_path)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nicolas/Develop/doc.ethsigner/docs/custom_theme/404.html'
```
here the 404.html file as it's a symlink:
```
ls -la docs/custom_theme/
total 72
drwxr-xr-x   7 nicolas  staff    224 Nov 28 01:35 .
drwxr-xr-x  10 nicolas  staff    320 Nov 28 01:35 ..
lrwxr-xr-x   1 nicolas  staff     28 Nov 28 01:35 404.html -> common/custom_theme/404.html
lrwxr-xr-x   1 nicolas  staff     26 Nov 28 00:23 assets -> common/custom_theme/assets
-rw-r--r--   1 nicolas  staff  32988 Jul 25 15:58 favicon.ico
lrwxr-xr-x   1 nicolas  staff     29 Nov 28 00:23 main.html -> common/custom_theme/main.html
lrwxr-xr-x   1 nicolas  staff     28 Nov 28 00:23 partials -> common/custom_theme/partials
```

## fix idea

Of course I worked on a fix: https://github.com/NicolasMassart/mkdocs/commit/77f38ffa84ac845e495242b21ba44f162d688286 that I wrote based on a [StackOverflow answer](https://stackoverflow.com/questions/4847615/copying-a-symbolic-link-in-python), but as I'm not not an experienced developper, it seems very risky...

It works for me, but I have little or no idea of the risks or the side effects of this fix.
Any feedback is welcome.
Of course if you think it's a valid fix, I will provide it as a PR and make sure it follows the rules to contribute to this project.

Thanks.

**Comment by waylan** [comment]
We are already using `shutil.copyfile`, which copies the contents of a file. In fact, it actually opens and reads the contents from the source file and then writes the contents to a new file. In contrast, your "fix" uses `shutil.copy` which would undo the fix in #1294.

Given the above, I'm confused by this issue. In Python 3 a new argument was added to the [shutil][1] functions: `follow_symlinks`, which defaults to `True` and copies the content of a symlink, not the symlink itself. In fact, the Stackoverflow answer you linked to notes that `follow_symlinks=True` does not exhibit the problem reported there, only `follow_symlinks=False`. However we are using `follow_symlinks=True` so we shouldn't have this problem.

**Comment by NicolasMassart** [comment]
That's exactly why I asked, it looked strange to me too as I read these previous issues too.
But the fact is that I have this issue, even with latest MkDocs, if I don't add the parameter.
The error I pasted in the issue is really what I got first and if was fixed with my ugly change.
Confusing.
What would you need me to provide as debug infos?
A sample project that fails?

**Comment by waylan** [comment]
> ```python
> if os.path.islink(src):
>     linkto = os.readlink(src)
>     os.symlink(linkto, dst)
> ````

This "fix" of yours does not copy the contents, it creates a new symbolic link from the `site_dir` to the original file location. In other words, MkDocs already does what you are requesting and your proposed fix us doing the opposite.

I am also curious about the use of [os.path.islink][1] as the documentation for that seems to indicate that it only returns `True` when the link points to a directory. I see some of your links point to directories, but others to files. I'm wondering if it is even working as you intended. In contrast, [os.is_symlink] seems like it might be a better solution if that is what you want.

I was curious if perhaps the problem was that you had broken links, but if that "fix" is working, then the links could not be broken. I have no idea what is going on here. Perhaps a minimal sample project that fails would be helpful. I think the most helpful would be the terminal commands used to create both the project and the links.

[1]: https://docs.python.org/3/library/os.path.html#module-os.path
[2]: https://docs.python.org/3/library/os.html#os.DirEntry.is_symlink

**Comment by waylan** [comment]
For the record, we will not accept your proposed fix. As explained above, it is making copies of the links (not the file contents). our users should be able to copy the `site_dir` to a server and symbolic links will often break things. We need the actual contents of the files to be copied to the `site_dir`. We may need to do something different that what we have now (although it's not clear what so far), but your proposed fix is definitely not it.

**Comment by waylan** [comment]
So I just took another look at this and have determined that you must have something wrong in your config settings. The file which is raising the error is a theme template. And theme templates should never be copied. Instead they should be read by Jinja2 to render pages. If MkDocs is attempting to copy them, then MkDocs does not recognize that they are part of the theme. I will need to see your `theme` config as a minimum to understand what is going on here.

**Comment by NicolasMassart** [comment]
I made some more testing. So two colliding issues. The symlinks were not good on my side and mkdocs seems to have issues to handle some directory structure with symlinks. I will create a new ticket for the second one once I will clearly see how it happens. Thanks.
