### ISSUE TITLE
where have about API document?interface document!

### ISSUE THREAD

**Issue by jingyuexing** [mkdocs/mkdocs#1913]

**Comment by waylan** [comment]
Are you asking for the API which MkDocs provides or for how to generate documentation from code?

For the former, see our [plugins][1] and [template][2] documentation.

For the latter, there are a few third party plugins available: [mkautodoc][3] and [automacdoc][4]. I have not used either of them personally and cannot speak to either, but they are the only two I'm aware of.

[1]: https://www.mkdocs.org/user-guide/plugins/
[2]: https://www.mkdocs.org/user-guide/custom-themes/#template-variables
[3]: https://github.com/tomchristie/mkautodoc
[4]: https://github.com/AlexandreKempf/automacdoc/

**Comment by pawamoy** [comment]
I've also developped [mkdocstrings](https://github.com/pawamoy/mkdocstrings) 😛

**Comment by jingyuexing** [comment]
> Are you asking for the API which MkDocs provides or for how to generate documentation from code?
> 
> For the former, see our [plugins](https://www.mkdocs.org/user-guide/plugins/) and [template](https://www.mkdocs.org/user-guide/custom-themes/#template-variables) documentation.
> 
> For the latter, there are a few third party plugins available: [mkautodoc](https://github.com/tomchristie/mkautodoc) and [automacdoc](https://github.com/AlexandreKempf/automacdoc/). I have not used either of them personally and cannot speak to either, but they are the only two I'm aware of.

tanks！

**Comment by jingyuexing** [comment]
> I've also developped [mkdocstrings](https://github.com/pawamoy/mkdocstrings) 😛

thanks your reply text
