### ISSUE TITLE
Is it possible to use a query string on the URL for search?

### ISSUE THREAD

**Issue by dellagustin-sap** [mkdocs/mkdocs#1917]
I wanted to have something like <protocol+domain+path>?search=<search terms>
My use case is to create a custom search engine in my browser for convenience, like <protocol+domain+path>?search=%s

I could not find if this is possible in the documentation.

**Comment by waylan** [comment]
That is theme dependent. The search plugin simply provides the mechanism to do search. But the search interface is provided by each individual theme. For example. the `mkdocs` theme provides a pop-up search modal on every page and does not support using query strings (nor does it make sense to).  However, the `readthedocs` theme provides a `search/search.html` page and that page accepts query strings.

If you are using a third party theme, you will need to check with that theme. As a general rule, I would expect any theme which sets [theme.include_search_page][1] to `True` to support query strings. However any theme which sets that to `False` would not. Note that this setting is set by the theme, not by the user, so you need to look for themes which set it to `True`.

Be warning however, that the above assumes that themes are using the plugin's provided solution. Not all do. For example, the `material` theme provides their own search solution which works differently. In that case, you would need to ask the developers of the theme.

[1]: https://www.mkdocs.org/user-guide/custom-themes/#include_search_page

**Comment by dellagustin-sap** [comment]
Thanks for the quick reply, we are using `material` which also have a solution similar to the `mkdocs` in terms of usability, it presents the results in a drop down directly below the search box.

Regarding:
> he mkdocs theme provides a pop-up search modal on every page and does not support using query strings (nor does it make sense to).
I disagree it does not make sense, as per the use case I presented.
Also, one could want to send a link to another person with a pre-filled search box, the user would land in the page with the search box pre-filled and the results shown.

It is a pitty there is no standard related to the search query, but, as you suggested, I will search for this information on the `material` theme documentation.

Thank you!
