### ISSUE TITLE
Inquiry: Rendering Support for GitLab Flavored Markdown syntax

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [mkdocs/mkdocs#1928]
It seems that my site generated from Mkdocs got some syntax to be rendered as plain text because I am deploying the documentation site using GitLab CI. Did I need to add this code on every single Markdown file? Do you have any plan to support GitLab Flavored Markdown in the future or do I need to do some workarounds like this one below?

```markdown
!!! note "Some GitLab Flavored Markdown syntax was rendered as plain text."
    If you see this notice, it because Mkdocs doesn't support some GitLab Flavored Markdown
    syntax. Please see this issue at https://github.com/mkdocs/mkdocs/issues/1927 for more
    information regarding the rendering issue. In a meanwhile, open this article in GitLab
    by clicking the :pencil: button at the top of every article.
```

## Additional links and Resources
GitLab Pages website with issue(s): <https://madebythepinsteam-devlabs.gitlab.io/official-handbook>
Source code: <https://gitlab.com/MadeByThePinsTeam-DevLabs/official-handbook>
Merge Request: <https://gitlab.com/MadeByThePinsTeam-DevLabs/official-handbook/merge_requests/4> and <https://gitlab.com/MadeByThePinsTeam-DevLabs/official-handbook/merge_requests/1>
GitLab Flavored Markdown: <https://docs.gitlab.com/ee/user/markdown.html>

**Comment by facelessuser** [comment]
Mkdocs used Python Markdown, not Gitlab flavored Markdown. You should not use syntax that Python Markdown does not support unless you are using an extension for Python Markdown that adds support for the desired syntax.

I see that footnotes in your site are not rendering, did you forget to enable the footnotes extension? https://python-markdown.github.io/extensions/footnotes/

**Comment by waylan** [comment]
@facelessuser is correct. More information is provided in the [documentation][1], including the extensions MkDocs enables by default and links to lists of other extensions which may be available to you. You can enable Markdown extensions with the [markdown_extensions][2] config setting in your `mkdocs.yml` file.

I'm closing this as there is no actionable item here and the question is already answered in the documentation.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown
[2]: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions
