### ISSUE TITLE
Regression: Hover state for headers' permalinks is weird again (see #843)

### ISSUE THREAD

**Issue by jimporter** [mkdocs/mkdocs#1931]
I'll leave it up to others to determine how big of an issue this is, but the patch in #1387 mostly-regressed #843.

To see the issue in action, go to https://www.mkdocs.org/#great-themes-available and put your mouse to the right of "Great Themes Available" (say, above the phrase "Choose between"). Notice that "Great Themes Available" displays its permalink icon.

Now, do the same but for "Host Anywhere" (put your mouse just above, say, "Github pages"). Notice that "Host Anywhere"'s permalink isn't displayed, but "Great Themes Available"'s **is**.

The difference between this and #843 is that this now only applies when you're just above the heading for the current `#ref` in the URL.

The old screenshot I posted should illustrate the issue:

![The problem](https://cloud.githubusercontent.com/assets/826865/13341512/11db9a9c-dbff-11e5-92fd-6c220312f50c.png)

**Comment by waylan** [comment]
Groan. I don;t think this is not a high priority. It took me a while to even see what the problem was after reading the report. Weirdly, it seems inconsistent. Some headers seem to have a larger "hover area" than others.

Nevertheless, if a fix is provided, we would happily merge it. A PR is welcome.

**Comment by jimporter** [comment]
Good news! It turns out that in the intervening years since I wrote the initial CSS hack, there's now an actual CSS property for this: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding

Patch forthcoming...
