### ISSUE TITLE
Deleting a generated file when serving MkDocs

### ISSUE THREAD

**Issue by christo-ph** [mkdocs/mkdocs#1933]
Hi,

I am writing a plugin which generates some output files (images). Those are located under the docs directory. It's called `out`

If `out` is not present when calling `python -m mkdocs serve`, it is creating the file and serving regularly.

While `mkdocs serve` is running, and I do remove a file or folder from `out`, `serve` is going into a never ending loop.

Is there a way to circumvent that?

Edit: This happens as well, when creating a new file within `out` while serving

**Comment by waylan** [comment]
Your plugin should never write to the `docs_dir`. Each time a file is written, the server's file watcher will start a reload, which will cause the file to be written again, which causes another reload, and the loop continues.

Instead, you should create [File][1] objects which point their `src_path` to the original file location and the `dest_path` to the appropriate location in the `site_dir`. Then add each of those file objects to the `files` collection (using the [on_files][2] event).  When MkDocs copies files and builds pages, it will include your added files in the built site without any need to copy them to the `docs_dir`.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/files.py#L87
[2]: https://www.mkdocs.org/user-guide/plugins/#on_files

**Comment by christo-ph** [comment]
ok thanks for explanation. In this case I have to change the behavior of my plugin accordingly.
