### ISSUE TITLE
mkdocs serve which file has changed

### ISSUE THREAD

**Issue by christo-ph** [mkdocs/mkdocs#1934]
Is it possible to get the information which file(s) have changed with the live-reload feature of mkdocs?

or is there an event which covers this?

**Comment by waylan** [comment]
As documented, the [on_serve][1] event provides access to the `livereload.Server` instance. The liverelaod server is a light wrapper around [lepture/python-livereload][2], where you can find documentation for the server and file watcher. Note that the `on_serve` event is the very last event called within the build process, so I doubt you could use it to alter the build in any way. It is provided to add additional files to be watched (presumably in conjunction with adding files to the files collection as I describe in #1933).

You may be able to do other things with the server instance, but that outside the scope of the provided event and not something we are likely to officially support.

[1]: https://www.mkdocs.org/user-guide/plugins/#on_serve
[2]: https://github.com/lepture/python-livereload

**Comment by christo-ph** [comment]
Thank you. As my plugni generates files (Plantuml images, external from .md documents) it could be a possible solution to use `on_serve`.

Currently I compare modification dates of source and generated file to see if a build is necessary.
