### ISSUE TITLE
Binary distributions, like Hugo does (and their .deb works well)

### ISSUE THREAD

**Issue by DaniellMesquita** [mkdocs/mkdocs#1941]

**Comment by waylan** [comment]
There are various volunteers who provide and maintain system specific packages for MkDocs. However, it is impossible for the core team to provide such packages for every system out there. As volunteers working in our spare time, we concentrate on the Python package only. If your favorite system doesn't have an up-to-date package, then you are free to provide and maintain it yourself within the confines of the (very liberal) license.
