### ISSUE TITLE
filename contains dot can not find file

### ISSUE THREAD

**Issue by mouday** [mkdocs/mkdocs#1943]
filename which markdown file contains dot `.` can not find file

eg:
```
vue.js.md
```
change name to 
```
vue-js.md
```
this is ok

why not auto append `.md`

**Comment by waylan** [comment]
How are you using the filename like this?  Is this a page inn your `docs`? It is listed in your `nav`? it is a link in your Markdown?

**Comment by mouday** [comment]
in my markdown file ,just like 
```
[vue.js.md](vue.js)
```
i got a warning
```
not find file vue.js
```

**Comment by waylan** [comment]
Does a file named `vue.js` exist? If so, where is it located in relation to your markdown file? Without a complete picture of what you have, we cannot help you. You need to provide everything we need to reproduce your exact situation.
