### ISSUE TITLE
markdown convert to html lose enter

### ISSUE THREAD

**Issue by mouday** [mkdocs/mkdocs#1944]
my markdown file:
```
1、this is first line;
2、this is second line.
```

convert to html like
```
1、this is first line;2、this is second line.
```
i wish keep two line , not one line;
do you know , how do it?

**Comment by waylan** [comment]
The Markdown [rules][1] require a dot (`.`) rather than a comma (`,`) after the list number:

```
1. this is first line;
2. this is second line.
```

If you want any other behavior, that is something which will require you to create your own custom Markdown extension and is outside the scope of help we can provide here.

[1]: https://daringfireball.net/projects/markdown/syntax#list

**Comment by mouday** [comment]
@waylan  
My want to write common text, but a list , maybe  like this:
```
this is first line;
this is second line.
```
number just to let you see it beautiful

**Comment by waylan** [comment]
How to force a line break is explained in the [rules][1]:

> When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

However, you can alter that behavior with a Markdown extension. Perhaps the [new line to break][2] extension would be of interest to you. See the [documentation][3] for how to enable extensions in MkDocs.

As an aside, these are basic Markdown concepts which apply to all Markdown implementations and are not unique to MkDocs. This is not really the place to ask for help with Markdown.

[1]: https://daringfireball.net/projects/markdown/syntax#p
[2]: https://python-markdown.github.io/extensions/nl2br/
[3]: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by mouday** [comment]
thank you very much, i got it

**Comment by mouday** [comment]
mkdocs.yml setting is ok

```
markdown_extensions:
  - codehilite
  - nl2br
```
thanks again !
