### ISSUE TITLE
mkdocs serving on glitch.com

### ISSUE THREAD

**Issue by manatlan** [mkdocs/mkdocs#1946]
Hi .. i'm using the wonderful glitch.com to host my mkdocs ...
(using "mkdocs serve")

Its really useful (combination of mkdocs+glitch) ... but clicking on the top-left icon try to redirect to "127.0.0.1:8000" (the default dev-addr)
see : https://reqman-docs.glitch.me/

how to avoid that, and redirect to https://reqman-docs.glitch.me/ ?
is it possible ?

**Comment by waylan** [comment]
`mkdocs serve` is intended for development only and we do **not** support its use in production. If you are using it behind a proxy, we suggest you stop. MkDocs is a "static site generator" only. You generate static HTML which is then served by a production level static file server.

In fact, the `serve` command overrides some config settings and alters the behavior slightly to ensure that it works for development. We will not entertain changing that as doing so would enable use in a way that we are not willing to support.

**Comment by manatlan** [comment]
you're right ...
Now I use nodejs (on glitch) to serve the mkdocs renderer site (pretty easy), and better
https://reqman-docs.glitch.me/
the "problem" is gone
