### ISSUE TITLE
Add link to plugins wiki page in docs

### ISSUE THREAD

**Issue by twardoch** [mkdocs/mkdocs#1948]
On https://www.mkdocs.org/user-guide/plugins/ add:

```
The [MkDocs Plugins](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins) wiki page lists many 3rd-party plugins that you can use.
```

**Comment by waylan** [comment]
That’s an excellent idea. A PR is always welcome. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by twardoch** [comment]
OK, I’ve created a PR https://github.com/mkdocs/mkdocs/pull/1950 (and refactored/extended the https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins page )

**Comment by waylan** [comment]
Awesome job with the wiki page. Thanks. 👍 💯 🥇
