### ISSUE TITLE
dev_addr support for folders

### ISSUE THREAD

**Issue by Stanzilla** [mkdocs/mkdocs#1949]
Currently trying to serve mkdocs locally from a subfolder to emulate a production environment but 

`dev_addr: '127.0.0.1:8000/docs'` throws `ERROR   -  Config value: 'dev_addr'. Error: '8000/docs' is not a valid port` any way this could be changed?

**Comment by waylan** [comment]
No this is not supported and is out of scope for the server we provide It is also not necessary. All internal links should be relative links anyway so they will all work regardless of whether the production site is in a subfolder or not.

The few places where this actually matters (like error pages), we already do the 'right thing' based upon the `site_url` setting (for example, set it to `https://example.com/docs/`). However, when the dev server is used, that setting is overridden to ensure everything works from the server root.

If you really want to test that things work from a subdir, then do a normal `build`, then use a third party server to test. Any basic static file server will work, including Python's built in server, tornado's server (which is a dependency of MkDocs) or the livereload server (which is also a dependency).

**Comment by Stanzilla** [comment]
okay my usecase was mainly serviceworker scope testing
