### ISSUE TITLE
installation instructions incomplete?

### ISSUE THREAD

**Issue by wtholliday** [mkdocs/mkdocs#195]
Hi, I followed the instructions for installing mkdocs. mkdocs seems to be installed:

```
$ pip show mkdocs
---
Name: mkdocs
Version: 0.10
Location: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requires: Jinja2, Markdown, PyYAML, watchdog, ghp-import

$ mkdocs help
-bash: mkdocs: command not found
```

Do I need to add something to my path to get this working?

thanks!

**Comment by byhoratiss** [comment]
I have the same issue.
```
user@desktop:~$ pip show mkdocs
---
Name: mkdocs
Version: 0.11.1
Location: /home/user/.local/lib/python2.7/site-packages
Requires: Jinja2, Markdown, PyYAML, watchdog, ghp-import
user@desktop:~$ mkdocs
mkdocs: no se encontró la orden
```

**Comment by d0ugal** [comment]
@byhoratiss Let's see if we can figure this out with some more info.

Can you show me the output of these commands:

- `python --version`
- `pip --version`
- `export | grep ^PATH=`

**Comment by byhoratiss** [comment]
@d0ugal Yeah, sure.
```
user@desktop:~$ python --version
Python 2.7.8
user@desktop:~$ pip --version
pip 6.0.8 from /usr/local/lib/python2.7/dist-packages (python 2.7)
user@desktop:~$ export | grep PATH
declare -x COMPIZ_BIN_PATH="/usr/bin/"
declare -x DEFAULTS_PATH="/usr/share/gconf/ubuntu.default.path"
declare -x MANDATORY_PATH="/usr/share/gconf/ubuntu.mandatory.path"
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
declare -x XDG_SEAT_PATH="/org/freedesktop/DisplayManager/Seat0"
declare -x XDG_SESSION_PATH="/org/freedesktop/DisplayManager/Session0"
```

**Comment by d0ugal** [comment]
Okay! So, you have the latest pip which is good and a new-enough Python 2.7.

So, the issue here as far as I can tell is that the Python bin dir isn't being added to the path. I have no idea why this would be the case, but I don't think it is an issue with MkDocs itself and rather something in your setup.

**Comment by byhoratiss** [comment]
Can't figure out what is the right solution. Any ideas?

**Comment by d0ugal** [comment]
@byhoratiss How did you install python and pip? What OS are you on? Is it just the default OS one?

**Comment by byhoratiss** [comment]
@d0ugal 
OS: Ubuntu 14.10
Python was already installed, and I have 2.7 & 3.4.
I installed pip by doing ```sudo apt-get install python-pip python-dev build-essential```

**Comment by d0ugal** [comment]
I really have no idea I'm afraid. I on Fedora but I use [pyenv](https://github.com/yyuu/pyenv) to install and manage Python versions. From my previous experiences tho' I'd think that what you have done should work with no problems.

**Comment by byhoratiss** [comment]
:(

I'll have to find another way to build my docs.
Thanks for your time!

**Comment by d0ugal** [comment]
@byhoratiss Did you try with Python 3.4?

**Comment by d0ugal** [comment]
Closing this as there isn't a way for me to progress here - appears to be an environment issue. Happy to re-open if more info is provided.

**Comment by abethman** [comment]
I had the same problem on Ubuntu 15.04. The solution was to uninstall the Ubuntu's own `python-pip` package and instead install pip as described at http://wiki.ubuntuusers.de/pip:
`wget https://bootstrap.pypa.io/get-pip.py`
`sudo python get-pip.py`
After that I could do a
`sudo pip uninstall mkdocs`
and then
`sudo pip install mkdocs`
Now everything seems to work fine.

**Comment by byhoratiss** [comment]
I believe that I ended up doing something like this.
It wasn't related to an issue with mkdocs installation, but with pip instead.

Maybe it could be useful to include this case in the "installation problems" section inside docs.

**Comment by d0ugal** [comment]
Sounds reasonable. See #529

**Comment by k4kfh** [comment]
I ended up doing almost exactly what @abethman described. I adjusted a few things per suggestions from the console apps themselves, and ended up with this:

```bash
wget https://bootstrap.pypa.io/get-pip.py
sudo -H python get-pip.py
sudo -H pip uninstall mkdocs
sudo -H pip install mkdocs
```

Following that, ``mkdocs`` seems to work just fine from any folder I tried. I am on Ubuntu GNOME 15.04, amd64. I did this with Python 2.7.9. Maybe we could put together an automated installer for Ubuntu as a GitHub gist? Not sure if it's needed, but if that's the only way we can have a turn-key install that's a good way to go.

Great docs software, by the way. I switched from Slate because my project was growing too big for Slate's one-page structure, and I'm loving mkdocs so far.

**Comment by muhe31** [comment]
`sudo easy_install mkdocs` worked for me.

**Comment by zsynacl** [comment]
I had the same problem. `pip3 install mkdocs` didn't work, but I solved the problem after `sudo pip3 install mkdocs`

WLS: Ubuntu 18.04
Python 3.6

**Comment by chuan-325** [comment]
> I had the same problem on Ubuntu 15.04. The solution was to uninstall the Ubuntu's own `python-pip` package and instead install pip as described at http://wiki.ubuntuusers.de/pip:
> `wget https://bootstrap.pypa.io/get-pip.py`
> `sudo python get-pip.py`
> After that I could do a
> `sudo pip uninstall mkdocs`
> and then
> `sudo pip install mkdocs`
> Now everything seems to work fine.

I was inspired by the solution, then I **reinstall the `mkdocs`** as the last two command, and it works! Thanks a lot.

OS: Linux 16.04 LTS, Windows Subsystem Linux
Python: 3.8.8
Pip: 21.0.1, installed by curl script
