### ISSUE TITLE
How to add a watched directory

### ISSUE THREAD

**Issue by pawamoy** [mkdocs/mkdocs#1952]
The docs says:

> The serve event is only called when the serve command is used during development. It is passed the Server instance which can be modified before it is activated. For example, additional files or directories could be added to the list of "watched" files for auto-reloading.

How can I add files or directories?

I tried this:

```python
    def on_serve(self, server, config, **kwargs):
        for element in self.config["watch"]:
            server.watch(element)
        return server
```

With this in my `mkdocs.yml`:

```yaml
plugins:
  - search
  - mkdocstrings:
      watch:
        - src/mkdocstrings
```

It detects the changes, but since I gave no function to `server.watch(dir, func)`, the site is not rebuilt.

I checked the source code of `mkdocs`, and I see that you are using a local function that we cannot reuse ourselves without rewriting it:

https://github.com/mkdocs/mkdocs/blob/262c2b70f3b1a450d685530610af3f28e12f9c9f/mkdocs/commands/serve.py#L120-L137

and

https://github.com/mkdocs/mkdocs/blob/262c2b70f3b1a450d685530610af3f28e12f9c9f/mkdocs/commands/serve.py#L69

What would be the best way to add a directory with this same `builder` functionality? Should I simply copy paste it?

**Comment by waylan** [comment]
> you are using a local function that we cannot reuse ourselves without rewriting it

That would appear to be an oversight on my part. The intention was that this could be done just as you attempted. I missed that the `builder` function needs to be passed to each call to `server.watch`. Therefore, this is a bug.

**Comment by pawamoy** [comment]
I managed to hack it anyway, but am waiting for an official change in mkdocs :slightly_smiling_face: 

```python
    def on_serve(self, server, config, **kwargs):
        builder = list(server.watcher._tasks.values())[0]["func"]
        for element in self.config["watch"]:
            server.watch(element, builder)
        return server
```
