### ISSUE TITLE
Navigation: Using autodetection but naming directory structure

### ISSUE THREAD

**Issue by jevin36** [mkdocs/mkdocs#1955]
Hi,
I am having a structure in my docs like this:

```
docs/
docs/mytest/somecontent.md (having a headline 1: My Content)
```
so the navigation will look like this:
```
mytest
- My Content
```

I still want to use the autodetection of mkdocs so the navigation elements are created automatically but I also want to give the directory an explicit name in the navigation e.g.

My Test
- My Content

Is that already possible?

**Comment by waylan** [comment]
Have you tried it? The  autogenerated nav will mirror the directory structure. Subdirectories will become sub-sections within the nav. The name of the sub-section is be drawn from the directory name.

Be aware, however, that most themes only support two levels of navigation (root plug one level of seb-sections). So if you have anything deeper than that, the theme may not display it correctly.

**Comment by jevin36** [comment]
The navigation element (concerning the directory) will generated but I like to give directories technical english names rather than e.g. german names. So maybe my example was bad. Having a structure like

```
docs/
docs/functional/somecontent.md (having a headline 1: My Content)
```

results in a navigation:
`Functional -> My Content`

but I'd like it to be
`Funktionale Beschreibung -> My Content`

so it would mean defining a name for the "functional" directory

**Comment by waylan** [comment]
Auto-generation is all or nothing. However, there may be some [third party plugins][1] which offer a solution for you.

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#navigation--page-building
