### ISSUE TITLE
Add possibility to build certain pages as php files rather than html

### ISSUE THREAD

**Issue by angelobanse** [mkdocs/mkdocs#1957]
It would be nice to be able to build certain pages as .php instead of the conventional .html

It would be enough for the extension of the desired generated pages to end in **.php** nothing more (as is known, you can write pure html and save it as a `.php` file and it should work fine).
This would allow to insert php code inside the markdown and thus add functionalities to our pages.

**Comment by froschdesign** [comment]
> This would allow to insert php code inside the markdown and thus add functionalities to our pages.

MkDocs is a _static_ site generator. You should add your additional functionalities to MkDocs via plugin or extend the templates – before anything is rendered.

**Comment by waylan** [comment]
I agree with @froschdesign. MkDocs is a "static site generator." Generating PHP is out-of-scope. However, if you can get it to work with plugin, you are certainly welcome to.

**Comment by almostengr** [comment]
@angelobanse  I was able to get it to generate PHP pages. If you are still interested in getting this to work, please message me on Twitter or via my website

**Comment by ajh123** [comment]
@almostengr Can you have a look at the message on Twitter I sent you (from @op_hulme)
