### ISSUE TITLE
readme.md failed to become index

### ISSUE THREAD

**Issue by ytianxia6** [mkdocs/mkdocs#1959]
my files are :

```
mkdocs.yml
docs/
    readme.md
```

my mkdocs.yml is 
```
nav:
- Home: readme.md
```

after build, the public dir is :
```
404.html
css\
fonts\
img\
js\
readme\
  index.html
...
```

the readme.md is compile to readme/index.html

**Comment by waylan** [comment]
Not sure how I missed this before. In any event, as indicated by every example in the [docs][1], `README` must be all-caps. It is `index.md` or `README.md`.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#index-pages
