### ISSUE TITLE
TOC with snippets

### ISSUE THREAD

**Issue by davidhrbac** [mkdocs/mkdocs#1963]
TOC should include headings from snippet but it does not.

![image](https://user-images.githubusercontent.com/728971/72792659-ac50cb80-3c39-11ea-92f5-5cce50077c5e.png)

We do include the file like this:

```Markdown
---8<--- "resource_accounting.md"
```

File resource_accounting.md:

```Markdown
# Resource Accounting Policy

## Wall-Clock Core-Hours WCH

The wall-clock core-hours (WCH) are the basic metric of computer utilization time.
1 wall-clock core-hour is defined as 1 processor core allocated for 1 hour of wall-clock time. Allocating a full node (16 cores Anselm,  24 cores Salomon)
for 1 hour amounts to 16 wall-clock core-hours (Anselm) or 24 wall-clock core-hours (Salomon).

## Normalized Core-Hours NCH

The resources subject to accounting are the normalized core-hours (NCH).
The normalized core-hours are obtained from WCH by applying a normalization factor:
```

**Comment by facelessuser** [comment]
This is not an issue with snippets as much as you shouldn't have more than 1 level 1 header in a document. I suspect if you copied and pasted the snippet content into the document, the results would be the same.

**Comment by facelessuser** [comment]
Just to show an example, I use headers in snippets [here](https://github.com/facelessuser/wcmatch/blob/master/docs/src/markdown/_snippets/posix.txt). And in the results, we can see that the headers appear in the TOC [just fine](https://facelessuser.github.io/wcmatch/glob/#posix-character-classes).

FYI, I am also the author of the snippets extension you are using, and obviously a user of MkDocs as well, so working behavior between the two is important to me.

**Comment by waylan** [comment]
As @facelessuser demonstrated that when there is no issue with how MkDocs is handling things, I'm closing this. If you need help in using the extension, please request help from the extension project.

 If the concern is that MkDocs requires properly nested headings, then I will refer you this [this explanation][1]:

> Note that ReStructured (used by Sphinx) raises an error if headers are not perfectly nested. Markdown is much more forgiving. However, for the TOC to work correctly, you need proper nesting. There is no reasonable way to have the TOC guess every possible scenario. Therefore, the only solution to your problem is to ensure your headers are properly nested.

[1]: https://groups.google.com/forum/#!topic/mkdocs/4f5BERsZTBc
