### ISSUE TITLE
Autogenerate content like automodule in sphinx?

### ISSUE THREAD

**Issue by Darel13712** [mkdocs/mkdocs#1966]
Hello, I really want to use your package over sphinx, but all I could find on autodoc is an old user repo.

Is there any way to grap docstrings from my project files?

**Comment by Darel13712** [comment]
Oh, I found answers saying that you don't want this in your package. Other question -- how do you write docs without it? Do you just copy-paste docstrings from code to documentation?

**Comment by waylan** [comment]
@Darel13712 there are two schools of thought on this. The MkDocs team prescribed to the idea that documentation should not be generated from doc strings, but be written as user focused prose.

That said, you will find a few [plugins][1] which offer ways to include doc strings in your MkDocs documents without manual copying. Perhaps one of those will serve your needs.

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins
