### ISSUE TITLE
Theme-option to specify theme-specific assets to not be copied

### ISSUE THREAD

**Issue by squidfunk** [mkdocs/mkdocs#1980]
For the latest Material theme, I'm switching to an SVG-based approach for FontAwesome which will reduce the payload by a huge margin, i.e. the SVGs are directly included from the Jinja templates, and thus must be distributed with the theme:

```jinja
<a href="{{ social.link }}" target="_blank" rel="noopener" class="md-footer-social__link">
  {% include "assets/images/icons/fontawesome/" ~ social.icon ~ ".svg" %}
</a>
```

The problem is, that on `build`, MkDocs will copy over all SVG files that are part of the theme, thus the build takes quite long and there're a lot of unnecessary file that should not be part of the build.

I've skimmed through the docs but didn't find an option to say: please don't include files under this directory. Ideally, as a theme author, I would like to specify which theme files are only necessary during build time and need not be distributed.

**Comment by squidfunk** [comment]
... what solves the issue at least symptomatically is if I rename all `*.svg` . files to `*.svg.html` – MkDocs will not copy the files anymore into the `site` directory – but that's a rather less ideal solution.

**Comment by waylan** [comment]
Any file or directory which starts with a dot (`.`) is ignored by MkDocs. So long as the content is included by Jinja, that should work fine for you. 

It appears that this behavior is not documented. We probably should do that. For the record, the ignored files are defined here:

https://github.com/mkdocs/mkdocs/blob/2fca717794c0c2e581b8ba17149bc292edeb83e4/mkdocs/structure/files.py#L67-L69

**Comment by squidfunk** [comment]
I didn't know about that, but it's perfect! Super elegant solution!

**Comment by squidfunk** [comment]
... uh, but could it be that this only applies to files on the root level of the theme?

**Comment by waylan** [comment]
> ... uh, but could it be that this only applies to files on the root level of the theme?

If it does, then that is a bug.

**Comment by squidfunk** [comment]
Just tested it – it only works for the top-level. I'm opening a new issue.
