### ISSUE TITLE
No-op code snippet in nav.py? (Page objects for files not in nav seem to be discarded)

### ISSUE THREAD

**Issue by maxalbert** [mkdocs/mkdocs#1983]
While debugging an issue with two mkdocs plugins that aren't working well together, I stumbled across [L120-123](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/nav.py#L120-L123) in `mkdocs/structure/nav.py`), which read as follows.
```python
# Any documentation files not found in the nav should still have an associated page.
# However, these page objects are only accessable from File instances as `file.page`.
for file in missing_from_config:
    Page(None, file, config)
```
The last line doesn't seem to have any effect: the `Page` object is constructed and then immediately discarded.

Should it instead be assigned to something (e.g. to `file.page` as seems to be implied by the comment)?
```python
for file in missing_from_config:
    file.page = Page(None, file, config)
```
I hope I'm not misinterpreting what's happening here, I hope a core developer can clarify the intention of this part of the code. Many thanks!

**Comment by waylan** [comment]
That's not necessary. As a `Page` instance always requires a `File` object, it does the assignment internally.

https://github.com/mkdocs/mkdocs/blob/61105ce56deb6f461ed6a076f095ea926e7572d2/mkdocs/structure/pages.py#L19-L22

Therefore, simply by creating a `Page` instance, it is available in the `files` collection through it's associated `File` instance at `file.page`. So long as that connection exists, Python will not garbage-collect it. However, if that connection is broken, then, yes, the instance would be discarded.

**Comment by maxalbert** [comment]
Ah yes of course, thanks for pointing that out. I had even seen this association between files and pages in both `files.py` and `pages.py`, but somehow it didn't register with me that this would mean the `Page` instance created in L123 will be preserved (and assigned to the `file` object) even if it appears to be discarded in this context.

Upon re-reading the comment in L120-121, it does even hint at that connection, although it didn't fully click for me when I read it. I just submitted PR #1984 with a minor rephrasing of the comment, just to make things extra clear.

Anyway, thanks for the help! I'm closing this issue because everything does work as expected. :)
