### ISSUE TITLE
Make site name clickable

### ISSUE THREAD

**Issue by saket** [mkdocs/mkdocs#1990]
Is there a way to include the site name in the clickable region? The logo for our docs site is a bit small and I've seen people try clicking the site name to go home.

**Comment by waylan** [comment]
Which theme are you using? In both of the builtin themes (`mkdocs` and `readthedocs`) the site name is clickable. If you are using any other theme, then you should take this to the developers of that theme.

**Comment by saket** [comment]
Whoops didn't realize this was a theme related issue. Will move this to `material`. Thank you!
