### ISSUE TITLE
Add release note pointing to mkdocs-bootswatch-classic?

### ISSUE THREAD

**Issue by jimporter** [mkdocs/mkdocs#1993]
With the update to Bootswatch 4.1.3, the mkdocs theme (and the variants in [mkdocs-bootswatch](https://github.com/mkdocs/mkdocs-bootswatch)) look (and work) a bit different. It would probably be useful to point users to the [mkdocs-bootswatch-classic](https://github.com/jimporter/mkdocs-bootswatch-classic) themes if they want to use the old styles with MkDocs 1.1. I'm also happy to hand over the mkdocs-bootswatch-classic repo to the mkdocs Github org so that all this stuff is in one place and it's easier for potential contributors to find it.

**Comment by waylan** [comment]
@tomchristie could we create a new repo at `mkdocs/bootswatch-classic` so @jimporter can transfer his repo? The "classic" themes keep bootstrap 2 while `mkdocs-bootswatch` is being updated to bootstrap 4. 

If @jimporter is willing, I'd be happy to have him added as a maintainer of all three repos (`mkdocs/bootstrap`, `mkdocs/bootswatch` and `mkdocs/bootswatch-classic`). He has created most of the PRs for them recently.

**Comment by jimporter** [comment]
So long as I can continue my usual practice of helping out on MkDocs and then fading off into the sunset for a year or so, I don't mind being a maintainer. I've got a lot of other projects to steward already, so I have to be careful about adding more commitments. :)

**Comment by tomchristie** [comment]
@waylan I've switch up permissions on the core team to admin, and allowed repo creation. Let me know if I've missed anything.

**Comment by waylan** [comment]
Thanks @tomchristie. 

@jimporter as I understand it, you need to initiate the move as you own the source repo and you need write access to the new repo to complete the move. Therefore, I have created a repo at [mkdocs/mkdocs-bootswatch-classic][1] and invited you as a maintainer. If you accept the invitation, you should be able to initiate a move from `jimporter/mkdocs-bootswatch-classic` and transfer the repo to the new one in the `mkdocs` org.  If you encounter any problems, let me know.

[1]: https://github.com/mkdocs/mkdocs-bootswatch-classic

**Comment by jimporter** [comment]
@waylan Ok, [mkdocs/mkdocs-bootswatch-classic](https://github.com/mkdocs/mkdocs-bootswatch-classic) should be good to go. The only thing left that I can think of (aside from releasing 1.0) is to update `.travis.yml`: mkdocs/mkdocs-bootswatch-classic#1.

**Comment by waylan** [comment]
I manually deployed the docs. We just need a release and then we can link to the project.

**Comment by pawamoy** [comment]
The issue looks stale to me. Four years have passed since this documentation request was made so it wouldn't be very useful to update the release notes now. Feel free to comment further if you disagree, we can re-open!
