### ISSUE TITLE
generate or link to API docs

### ISSUE THREAD

**Issue by jkmacc** [mkdocs/mkdocs#20]
First, this is a very promising package!  Thank  you!

I would like to replace Sphinx with mkdocs, but Sphinx is able to autogenerate API docs from package docstrings.  This would be very laborious to reproduce in mkdocs, I think, but perhaps mkdocs could easily link to existing _html_ pages (API pages generated by Sphinx).  

Apologies if this is trivial to do, and I just haven't figured it out yet.

Thanks again!

**Comment by rossant** [comment]
I'd also have been interested in this. If this can be of any use to anyone, I've written an [extremely basic automatic API doc generator](https://github.com/kwikteam/phy/blob/master/tools/api.py) that extracts docstrings of modules, functions, classes, methods, and properties, and outputs an `api.md` document. This document can then be used in mkdocs. There's probably some more work to do to make it prettier...

**Comment by d0ugal** [comment]
@rossant If you are generating a Markdown file, why don't you just create that in your other documentation and have it built by MkDocs. Then you don't need to do any extra linking.

**Comment by raghakot** [comment]
I wrote a simple generator to generate API docs by parsing source. https://github.com/raghakot/mkdocs-apidocs

I came here looking for a solution, couldn't find anything satisfactory online and built my own. Hope it helps others who stumble here looking for a workaround.

**Comment by MechCoder** [comment]
@rossant I am using your automatic doc generation for one of my projects. Thanks for your work!
