### ISSUE TITLE
Files in links produce misleading WARNINGS 

### ISSUE THREAD

**Issue by gdiamond** [mkdocs/mkdocs#2003]
The warning _WARNING -  Documentation file '<FILE>.md' contains a link to '<LINKED_FILE>' which is not found in the documentation files._ is displayed in the console even though the LINKED_FILE exists.  
1. The link is to a markdown file whose name contains one or more dots beyond the one found in _.md_, ( i.e. scim-1.1-apis.md).
2. The link is to a non-image or markdown file, (i.e. file.zip, file.war, file.jar, file-1.1.jar)

Running [example.zip](https://github.com/mkdocs/mkdocs/files/4246460/example.zip) produces 
```bash
12:16 $ mkdocs -V
mkdocs, version 1.0.4 from /usr/local/lib/python3.7/site-packages/mkdocs (Python 3.7)

12:16 $ mkdocs serve 
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
WARNING -  Documentation file 'get-started/provisioning-architecture.md' contains a link to '../develop/scim-1.1-apis' which is not found in the documentation files. 
WARNING -  Documentation file 'get-started/quick-start-guide.md' contains a link to '../assets/attachments/org.wso2.carbon.identity.sample.extension.authenticators-5.9.0.jar' which is not found in the documentation files. 
WARNING -  Documentation file 'learn/writing-a-custom-oauth-2.0-grant-type.md' contains a link to '../assets/attachments/custom-grant.zip' which is not found in the documentation files. 
WARNING -  Documentation file 'learn/writing-a-custom-oauth-2.0-grant-type.md' contains a link to '../assets/attachments/custom-grant-1.0.0.jar' which is not found in the documentation files. 
[I 200224 12:20:03 server:296] Serving on http://127.0.0.1:8000
[I 200224 12:20:03 handlers:62] Start watching changes
```

I believe 1 is what was reported in #1943 but with a working example.

**Comment by gdiamond** [comment]
@waylan Thanks for the dope slap.  I'm now seeing that it how it should be done and how I have my example set up are not correct.  I still think there is a problem because everything works when browsing my example but I get the warnings when I build/serve.  I will study my example further and report back if I can produce a valid example of the possible bug.

**Comment by waylan** [comment]
It works when you are browsing because you used the "converted" URLs. However, MkDocs isn't able to match those to any existing files so it issues the warnings.

**Comment by daxm** [comment]
I feel this issue still exists in mkdocs v1.3.0.  I'm linking to a `user-data.cfg` file that exists in the /docs directory.  After the referencing link is rendered to HTML the link works but I still get an error during each build.

Notice that the link ISN'T to an image or markdown file.  Just a file for downloading.

```
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /app/site
WARNING  -  Documentation file 'BranchConnector.md' contains a link to '../user-data.cfg' which is not found in the documentation files.
INFO     -  Documentation built in 0.44 seconds
```

**Comment by rogoit** [comment]
Try absolute path like

`![Add Git Project](/img/blank-project.png)`
