### ISSUE TITLE
Possible to detect in template when served locally?

### ISSUE THREAD

**Issue by abiro** [mkdocs/mkdocs#2006]
Hi,

I have a widget in my template that loads an iframe from an external URL. I'd like to disable this when working with Mkdocs locally. Is it possible to detect somehow in a template if the page is served locally with `mkdocs serve`?

Thanks,
Agost

**Comment by waylan** [comment]
No. As a reminder, MkDOcs is a ***static** site generator*. The site is built once and then served statically. The templates would no even be available by the time a server request is received. This sort of thing is out-of-scope for a static site generator.

Yes, the included dev server exists, but that is only for development purposes and intentionally emulates production behavior.
