### ISSUE TITLE
Estimate for next release?

### ISSUE THREAD

**Issue by uliska** [mkdocs/mkdocs#2008]
Is there any estimate about the next release of MkDocs?

I am contributing to `mkdocs-git-authors-plugin` and are starting to get problems with the difference between the PyPi version 1.04 and current master of MkDocs, basically due to the dropping of Python2 support (see https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/15).

I think it would be good to know if any new MkDocs release is "imminent" (whatever that means) to decide whether it makes sense to directly target the new version of if we have to somehow support both versions of the code.

**Comment by waylan** [comment]
We just released version 1.1 a few days ago (Feb 22).

**Comment by uliska** [comment]
OMG, sorry for the noise.

I *did* check the repository for tags - but the remote pointed to my fork ...
