### ISSUE TITLE
Pull alternate themes into separate package.

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#201]
We probably shouldn't try to maintain any more than two themes in the core package.
I'd recommend that we conside doing the following:

* [ ] Pull the bootswatch themes into a separate package. (We might even consider rebasing the git history after that as it's unnecessarily large)
* [x] Remove mention of the non-existent "ghostwriter" theme.

**Comment by d0ugal** [comment]
Done! https://github.com/mkdocs/mkdocs/commit/ff05df30dd2de8840fb185363afa41a5517a69ef
