### ISSUE TITLE
ReadTheDocs - Last item in navigation cut off

### ISSUE THREAD

**Issue by movedoa** [mkdocs/mkdocs#2012]
![grafik](https://user-images.githubusercontent.com/13309951/75665342-4c0b6b80-5c74-11ea-8cb0-9cc1c6151c10.png)

The last item is not fully visible when scrolling all the way down.

**Comment by waylan** [comment]
Yes, I can see the same behavior. A PR is welcome.

**Comment by nathanlesage** [comment]
I just opened a PR in order to fix this issue: https://github.com/mkdocs/mkdocs/pull/2297
