### ISSUE TITLE
ReadTheDocs - Click on page title in navigator doesn't open page

### ISSUE THREAD

**Issue by movedoa** [mkdocs/mkdocs#2013]
Clicking on the label of a node that is just a folder/category in the navigation doesn't expand/select the node.

I would expect the node to expand and select the first page.
https://sphinx-rtd-theme.readthedocs.io behaves as expected.

**Comment by waylan** [comment]
I do not see the behavior you describe. Could you provide more details? I assume you mean `Theme Documentation` or `Demo Documents`. Or are you referring to something else?

**Comment by movedoa** [comment]
Here you can see what i mean, i can only expand the nodes when clicking the +.
But maybe this is just anohter symptom of #2010

![Exp](https://user-images.githubusercontent.com/13309951/77535328-b93ca600-6e9a-11ea-85ac-ddb1da7d6c77.gif)
