### ISSUE TITLE
REQUEST: mkdocs serve should have an option to open a browser window to the serving address

### ISSUE THREAD

**Issue by Nickheythatsme** [mkdocs/mkdocs#2016]
When developing with many node tools (build react app, angular, etc), the browser window will automatically open to the address the app is being hosted at.

This would be a nice option to add to `mkdocs serve`. Maybe adding the `-o` or `--open` flag will make the browser open.

**If others agree, I'd like to open a PR to add this functionality.** I would use [webbrowser](https://docs.python.org/3.7/library/webbrowser.html) module to implement this.

**Comment by waylan** [comment]
This was previously attempted in #1771. Personally, I don't see the need for this for the reasons described there. That said, I'd be willing to consider a solution if it worked well and addressed the concerns the solution in #1771 was missing (like tests).

**Comment by Nickheythatsme** [comment]
Thanks for the info @waylan. Also appreciate everything you've done for mkdocs, love the tool.

I'll check out how far I get addressing the concerns in #1771  and submit a PR if I think it's addressed the concerns. I'll close this issue.

**Comment by andrewimeson** [comment]
This now exists from #3500

**Comment by hb20007** [comment]
Indeed, this now exists with the `-o`/`--open` flag syntax suggested here.
