### ISSUE TITLE
Keep underscore in file name

### ISSUE THREAD

**Issue by raybuhr** [mkdocs/mkdocs#2017]
Hi, I'm a big fan of `mkdocs` and have used in various projects for years. I never needed to do this before, but I can't for the life of me figure out how. I have pages representing database tables with underscores in the name, for example `some_schema.some_table.md`. When I build the site, that gets rendered as `Some schema.some table` when I would prefer to keep it as is. How can I turn off that underscore/title replacement?

**Comment by waylan** [comment]
I assume you are referring to the page title. It is a common convention that filenames will represent spaces as underscores. Therefore, when converting back from a filename to a title, MkDocs does the reverse and converts underscores to spaces. It also upcasts the first character, which you may not want either.

However, note that using the filename to determine the title of a page is a fallback if no other method is used. All of the ways to define a page title are defined in the [documentation][1]. The other methods do not do any conversion, but retain the original formatting. Therefore, I suggest using whichever method works best for you.

**Comment by raybuhr** [comment]
Thanks for the reply. I was thinking about page title and item in the table of contents.

Your link to documentation wasn't a real link, but I took another glance and the only thing I could find is about creating a theme -- https://www.mkdocs.org/user-guide/custom-themes/#pagetitle

I guess that means I need to fork an existing theme or create my own in order to handle how file name gets rendered?

**Comment by waylan** [comment]
> Your link to documentation wasn't a real link

Sorry, I apparently forgot to include the link. Fixed now. And repeated here: https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data

> I guess that means I need to fork an existing theme or create my own in order to handle how file name gets rendered?

No, the theme has no control of how the title gets created. The theme simply gets access to the title through the variable at `page.title`. At that point, any conversion has already happened.

**Comment by raybuhr** [comment]
Just want to say that adding in the YAML style metadata for page title did the trick for me. Thanks!
