### ISSUE TITLE
codeblocks in info/warn/note blocks are rendering as inline code

### ISSUE THREAD

**Issue by Andre601** [mkdocs/mkdocs#2019]
I can't for sure tell, if this is caused by MkDocs, the theme used for it (Material) or actually even caused by the custom css utilized.

The issue I face is, that when I use code blocks inside boxed (`!!! <type> ["<title>"]`), that it won't render those as a code block, but instead as inline code.
In addition does the color seem to not use the actual one set for inline color (It is a bright gray instead of a dark one, which is prefered.

This is the part I have for displaying the code block in the box:
```
!!! example "Example-JSON request"
    ```json  
    {  
      "avatar": "https://cdn.discordapp.com/avatars/204232208049766400/ae7f2e5247a05791dbf0ef96243622c2.png",  
      "message": "This is an example message.",  
      "nameColor": "hex:ff0000"  
      "username": "Andre_601"  
    }  
    ```
```

But the result is like this:
![image](https://user-images.githubusercontent.com/11576465/76202434-1971ed80-61f5-11ea-86ad-749dc2c57599.png)

My personal guess is, that the css is changing it somehow?
I use two .css files for changing the Material theme:
- [main.css](https://github.com/purrbot-site/Docs/blob/master/docs/assets/css/main.css)
- [dark.css](https://github.com/purrbot-site/Docs/blob/master/docs/assets/css/dark.css)

I actually got those from another project, which uses MkDocs and the Material theme to provide documentation and interestingly enough do code blocks inside boxes work in their docs, which confuses me even more.

I create and edit the pages on my Desktop and host the site using github-pages, which I deplay using the `mkdocs github-deploy` command.

**Additional information**
- Python version: 3.7.6
- Pip version (if important): 20.0.2
- MkDocs version: 1.1

**Comment by facelessuser** [comment]
Are you using the `fenced_code` extension or the `pymdownx.superfences` extension? The former I don't think will work nested in admonitions, but the latter will: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/

**Comment by Andre601** [comment]
I in fact don't.
I'll take a look and see if this will fix my issue.

**Comment by facelessuser** [comment]
Fenced block code is not enabled by default, so you have to enable at least one of those extensions, but if you want to nest fenced code in other structures, SuperFences is probably the way to go.

**Comment by Andre601** [comment]
This indeed fixed my issue. Thanks a lot.

**Comment by waylan** [comment]
For the record, the documentation for the [fenced code block extension][1] states (in a red warning no less):

> **Warning:** Fenced Code Blocks are only supported at the document root level. Therefore, they cannot be nested inside lists or blockquotes. 

Being nested inside an admonition is **not** at the root level.

[1]: https://python-markdown.github.io/extensions/fenced_code_blocks/#syntax
