### ISSUE TITLE
mkdocs serve not working on Windows VM

### ISSUE THREAD

**Issue by rachel-rigdon-sp** [mkdocs/mkdocs#2024]
I'm trying to just see my local builds on my Windows VM, but whenever I run `mkdocs serve`, it shows me an older version of my docs. I can build them with no problem to the site directory, but I can't see them in my local browser. I get this: 

```
[I 200317 10:54:25 server:296] Serving on http://127.0.0.1:8000
[WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

Is this related to my VM? Do I need to change ports somehow?

This seems potentially related to this issue? https://github.com/mkdocs/mkdocs/issues/1239

Using: 
VS Code
Markdown
Mkdocs
Windows

**Comment by rachel-rigdon-sp** [comment]
I fixed it. I had to close some of the 8000 ports.

**Comment by waylan** [comment]
There are a couple possible factors.

1. The fact that the error message mentions "sockets" suggests this may be related to the livereload feature. Try running the server with the `--no-livereload` option and see if that resolves the issue. Of course, you will need to manually refresh your browser after each change is saved as the live-reload feature is disabled.

2. It's not clear from your report, but if you are attempting to run the server on the VM, but the browser in your host OS, then that is not a supported use-case. Both the browser and server need to be running on the same system.
