### ISSUE TITLE
Browser Connected message whenever I change pages in the local serve version

### ISSUE THREAD

**Issue by rachel-rigdon-sp** [mkdocs/mkdocs#2025]
I'm working in VS Code and have run `mkdocs serve`. It's working great but every time I navigate between pages on the local browser version, it shows me this line in my VS Code terminal: 

`[I 200318 10:41:09 handlers:135] Browser Connected: http://127.0.0.1:8000/page.html `

This is new behavior and I'm not sure what I did to change it -- any advice on how to make it stop repeating the Browser Connected message in the terminal when I navigate between pages?

VS Code
macOS Catalina

**Comment by rachel-rigdon-sp** [comment]
I was just looking at my Python terminal and not the zsh.

**Comment by waylan** [comment]
This is all related to the upstream package, [lepture/python-livereload][1] of which we provide a light wrapper. Presumably any behavioral changes would need to be made upstream.

[1]: https://github.com/lepture/python-livereload
