### ISSUE TITLE
mkdocs in a subdir

### ISSUE THREAD

**Issue by Mopster** [mkdocs/mkdocs#2026]
I might be missing something very obvious here. We have a Symfony project and want to offer the mkdocs site in a subfolder : www.domain.com/solutions/index.php

My doc structure : 

- docs
  - solutions
    - EN
      - ....
    - JA
      - ...
    - index.md

mkdocs.yml is in the root of the project

```
docs_dir: docs/solutions/
site_dir: web/solutions/
```
I run `mkdocs build` in the the project root, and it generates the html files etc...

The problem is all the links in the html files (links to CSS, JS and other page) start as `en/folder/page.html` and `ja/folder/page2.html` while I need all those links to be prefixed by 'solutions/` is there any way to get this ?

**Comment by waylan** [comment]
That is not necessary. The URLs are all relative. In other words, MkDocs is aware of the location of the current page and builds the URL to ensure it points from the current location to the other location. Therefore, they will work correctly regardless of whether they are hosted in a sub-directory or not. However, you will need to properly set the `site_url` setting: `https://example.com/solutions/`. Note that the sub-directory is included there. That won't change how the links get rendered, but it will ensure everything does work as it should.

**Comment by Mopster** [comment]
It seems it's not possible to add a relative URL to the `site_url`. The problem is that URL is different for each customer, we run a multi-tenancy system based on the subdomain, we can't put it on a unique URL since we want to make authentication required to access the pages (using the Symfony authentication and firewall). Is there a way ?

**Comment by waylan** [comment]
It sounds to me like you need to use multiple MkDocs projects. Each one would have a unique `site_url`.

**Comment by Mopster** [comment]
We run the multi-tenant system out of a single repository/document root (with multiple DB's, connection based on subdomain). So having a different config for each unique `site_url` is not possible.
Would it be possible to expand the config to allow a `site_path` parameter which would be default empty, and have it appended to the `site_url` ?

**Comment by waylan** [comment]
Having  separate config for each is the only way it will work.
