### ISSUE TITLE
links build correctly only when there are no space/tabs starting line

### ISSUE THREAD

**Issue by ldelaprade** [mkdocs/mkdocs#2031]
```
Local link test [here](./test/new.md) # This one works

    Local link test [here](./test/new.md) # This one does not because line starts with blanks

```
mkdocs build correcly for the first:
```
<p>Local link test <a href="test/new/">here</a></p>
```
but the  the second sentence is compiled as:
```
<pre><code>Local link test [here](./test/new.md)

Local link test [here](./test/new.md)
</code></pre>
```

**Comment by waylan** [comment]
This is the correct behavior. As explained in the [rules][1], any lines indented by four spaces or one tab are code blocks and must not be parsed as Markdown.

[1]: https://daringfireball.net/projects/markdown/syntax#precode
