### ISSUE TITLE
Appveyor configuration/builds look to be broken

### ISSUE THREAD

**Issue by ScriptAutomate** [mkdocs/mkdocs#2032]
This may be due to my lack of experience with Appveyor, but each PR doesn't look to be kicking off the most current Appveyor configuration.

The latest PR, #2030, kicked off a build that failed. Though, the build is running some older version of the Appveyor configuration.

- [Broken build associated with](https://ci.appveyor.com/project/d0ugal/mkdocs/builds/31718635) #2030 
  - Notice that it is running 2.7 / 3.3 / 3.4 tests, which should no longer be part of the build
- [Current Appveyor configuration: 3.5 - 3.7 tests and flake8](https://github.com/mkdocs/mkdocs/blob/master/appveyor.yml)
- [An example of a previously completed build that looks like it is using the current config properly](https://ci.appveyor.com/project/d0ugal/mkdocs/builds/31398770)

I'm not sure if this is related or not, but the latest changes have not been pushed to the website. If broken builds prevent any pushes to live, this may continue to be a problem.

**Comment by waylan** [comment]
Yeah, I noticed that Appveyor haven't been reported in PRs lately, but haven't investigated. @d0ugal I believe Appveyor is configured through your account. Can you provide any helpful information here?

By the way, it may be more useful to switch to GitHub's [new platform][1], which supports running Windows/Linux/MacOS instances. That would also allow the same organization permissions to carry over.

[1]: https://github.com/features/actions

**Comment by d0ugal** [comment]
I removed appveyor and added it to my account again. I restarted some of the failed builds. Hopefully that helps.

+1 to moving infra

**Comment by waylan** [comment]
Hmm, that doesn't appear to have resolved the issue. The [latest build'[1] is still failing. And it is clear it is trying to run an old configuration.

```
C:\Python34\Scripts\tox.exe -e flake8;
C:\Python34\Scripts\tox.exe -e py27-integration;
C:\Python34\Scripts\tox.exe -e py34-integration;
C:\Python34\Scripts\tox.exe -e py33-unittests;
C:\Python34\Scripts\tox.exe -e py27-unittests;
C:\Python34\Scripts\tox.exe -e py34-unittests;
```

Well, that is part of an old config (`py33-unittests` but no `py33-integration`). The current config has a matrix of the following tox environments:

```
py35-integration
py35-min-req
py35-unittests
py36-integration
py36-min-req
py36-unittests
py37-integration
py37-min-req
py37-unittests
py38-integration
py38-min-req
py38-unittests
flake8
```

[1]: https://ci.appveyor.com/project/d0ugal/mkdocs

**Comment by waylan** [comment]
As per the [build history][1], it now appears that AppVeyor is only running jobs on commits to master and tags, but not on PRs. At least all of the recent commits (from merged PRs) are passing. In any event, I have been playing with GitHub Actions recently. I expect I'll be switching over soon.

[1]: https://ci.appveyor.com/project/d0ugal/mkdocs/history

**Comment by oprypin** [comment]
There's no appveyor in this repo anymore, I think
