### ISSUE TITLE
https://mkdocs.org causes security error while https://www.mkdocs.org doesn't

### ISSUE THREAD

**Issue by Andre601** [mkdocs/mkdocs#2037]
When connecting to https://mkdocs.org, does the anti-virus (in my case Kaspersky Internet Security) report the URL as "not secure"?
When you, however, connect to https://www.mkdocs.org does this warning not appear.

This also is made clear, when posting both links into a Chat (e.g. Discord): https://mkdocs.org doesn't load/display any meta/og information, while https://www.mkdocs.org does.

I suggest fixing this issue, as I assume people will prefer using mkdocs.org over www.mkdocs.org

**Comment by waylan** [comment]
I assume this is related to which of the two URLs the certificate is registered with. In any event, @tomchristie this is something you will need to address.

**Comment by tomchristie** [comment]
Not sure I can *easily* do much about that.
Short: Don't link to mkdocs.org - it's not the right address. 😃💛
