### ISSUE TITLE
Lists behavior as in GitHub?

### ISSUE THREAD

**Issue by stepan-3** [mkdocs/mkdocs#2038]
Is there a way to make a list behavior the same way as in GitHub?

Now, MkDocs doesn't make a list if there is no leading blank line before list items. For example: 

```
This is a list:
* Item1
* Item2
```

..wouldn't be converted to a list.

And this code would be converted to a list as there is a blank line before list items:

```
This is a list:

* Item1
* Item2
```

**Comment by waylan** [comment]
We follow the rules [here][1], which is the authority on Markdown. GitHub follows a variant defined [here][2]. We do not follow that spec. If you would like to alter the default behavior, you are welcome to [create your own extension][3], or if one already exists, use an existing [third party extension][4].

[1]: http://daringfireball.net/projects/markdown/syntax
[2]: https://github.github.com/gfm/
[3]: https://python-markdown.github.io/extensions/api/
[4]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions

**Comment by cnglen** [comment]
Any plugins?
