### ISSUE TITLE
Website certificate

### ISSUE THREAD

**Issue by Veldhoen** [mkdocs/mkdocs#2039]
May not be a proper github issue, but I noticed there is a problem with the certificate for your website https://www.mkdocs.org/ 
I got a security warning in Firefox.

**Comment by squidfunk** [comment]
Works on my machine. Valid until May 1.

**Comment by waylan** [comment]
No issues for me in Firefox or Safari either.

Are you sure you used the `www` address? See #1626.

**Comment by Veldhoen** [comment]
> Are you sure you used the `www` address? See #1626.

Ahh yes, omitting the www was the problem. I hadn't noticed the earlier issue, sorry!

**Comment by waylan** [comment]
Closing this as a duplicate of #1626.
