### ISSUE TITLE
TOC runs off the page for long documents

### ISSUE THREAD

**Issue by wtholliday** [mkdocs/mkdocs#204]
If you have enough parts in your document, the TOC becomes taller than the screen and sections can't be accessed. Is there something I can configure?

![categories](https://cloud.githubusercontent.com/assets/841144/4962866/b42b3c28-66ec-11e4-8cd6-8d6639996506.png)

**Comment by prantlf** [comment]
I don't see it happening at least with the readthedocs theme.  The navigation items are in a scrollable list.  The readthedocs theme is more suitable if there are many articles in the navigation than the mkdocs theme, which uses (non-scrollable) menu dropdowns at the top.

**Comment by d0ugal** [comment]
This happens on *every* theme except readthedocs. I tried to set `overflow: scroll` but either it isn't that simple or I tried the wrong elements.

Here is an example, it is easy to reproduce if you just copy and paste a section a ton of times to make the TOC really long.

https://dl.dropboxusercontent.com/u/14255217/Screenshots/Screenshot%202015-04-09-20.58.23.Google-chrome.png

**Comment by d0ugal** [comment]
This will now be handled in the theme repos. https://github.com/mkdocs/mkdocs-bootswatch/issues/2 and https://github.com/mkdocs/mkdocs-bootstrap/issues/3

**Comment by tomchristie** [comment]
> "This will now be handled in the theme repos."

Presumably we have the issue for the built-in `mkdocs` theme still tho?

**Comment by d0ugal** [comment]
I think somebody fixed it for MkDocs. But I am not 100% sure.

**Comment by d0ugal** [comment]
Confirmed. This is still an issue on the mkdocs theme.

**Comment by shichao-an** [comment]
I've tried adding the following CSS to `bs-sidebar` (in site's `custom.css`) as referenced [on stackoverflow](http://stackoverflow.com/a/21697661/1751342) and it seems to work, at least on the flatly theme that I used. 

```css
.bs-sidebar {
  overflow-y: auto;
  max-height: 100%;
}
```

You can view my result here: https://notes.shichao.io/apue/ch8/

**Comment by jamesadevine** [comment]
@d0ugal Hey!

Really impressed with mkdocs as a whole, a really cool project, with really nice documentation! :Smiley:

In #696, I just wanted to add that perhaps using the viewport height to side the `bh-sidebar` would be better. 90% of the page is different to 90% of the viewport height!

```css
.bs-sidebar.well {
    padding: 0;
    max-height:85vh;
    overflow-y: auto;
}
```

This results in a pretty nicely side sidebar that grows proportionally with the window.

**Comment by d0ugal** [comment]
@jamesadevine Interesting. I wasn't aware of vh units. It looks like IE and Edge only partially support this which is a concern and I don't have access to either to test it out. Happy to accept a pull request if you are able to test on IE and provide screenshots before/after.

**Comment by d0ugal** [comment]
Although, it looks like they they both support `vh` - so a pull request would be the way to go here.

**Comment by jamesadevine** [comment]
@d0ugal happy to oblige, I will make a pull request when I have a sec :smiley:

I will also provide screenshots of before and after for verification.
