### ISSUE TITLE
list of content (all articles) in page

### ISSUE THREAD

**Issue by mikch06** [mkdocs/mkdocs#2041]
Hi, i'm not sure if this is the right place but i couldnt' find it in de documentation. 

Is it possible to have an automatic list like a toc in a page?
But a collection of all articles?

I like to have some kind of a categeory or article list autmatic generated as a table of content. 
I tried something mit page.meta but i couldn't manage it.

Thanks for your help.
Regards 
Michael

**Comment by waylan** [comment]
The navigation in the `readthedocs` theme combines a pages TOC with the global navigation. Is that what you mean? For example, see [nav.html][1] and note that [toc.html][2] is included on line 12.

Or perhaps you mean you want to include a list within a page. In that case you can use a [static_template][3] to define the contents of a page. Of course, that means the page is not a Markdown document, but a Jinja template. For an example, see https://github.com/waylan/mkdocs-nature/blob/master/nature/sitemap.html

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/nav.html
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/toc.html
[3]: https://www.mkdocs.org/user-guide/configuration/#static_templates

**Comment by mikch06** [comment]
Hi @waylan , thanks a lot.
i think this could be some kind of a solution. 
I will try your recommendations next time if i can find some time. 
Thanks a lot!

**Comment by mikch06** [comment]
I checked your nature theme, very nice.
And i understand you. 
But i'm looking for something which collects and list all articles automatically. Background ist to just write a new markdown page and run a script to autogenerate the page. 

Thx.

**Comment by waylan** [comment]
MkDocs does nothing to alter the content of a Markdown page (other than run it through Python-Markdown). If you would like to do something like that, then you will need to use a Plugin. You can find a [list of known third party plugins][1] or you can [create your own][2].

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins
[2]: https://www.mkdocs.org/user-guide/plugins/#developing-plugins

**Comment by mikch06** [comment]
Thanks a lot, 
yes, i think i'll do that!
