### ISSUE TITLE
Deprecated --theme-dir is still listed as CLI option

### ISSUE THREAD

**Issue by jaredlll08** [mkdocs/mkdocs#2042]
Hey, I am busy migrating my project from v0.16.3 to v1.1 and it seems that the command line argument `-e / --theme-dir PATH` has been removed, I am defining a custom theme using the theme block and the `custom_dir` but the way we have things setup require us to use use the `--theme-dir` config as well, I don't suppose there is a replacement for that argument is there?

Thanks!

**Comment by waylan** [comment]
No, not directly. `theme_dir` was replaced by `theme.name` where name is an entry_point which points to an installed theme. Therefore, you would need to make the content of `theme_dir` its own Python package/theme, install it, and then set `theme.name` to the name of that theme. This is documented under [Packaging Themes][1] in the documentation.

[1]: https://www.mkdocs.org/user-guide/custom-themes/#packaging-themes

**Comment by jaredlll08** [comment]
Thanks, I was able to solve my problem, but the information out there is still rather confusing,
`mkdocs build -h` lists `-e --theme-dir` as an option still, but then says it doesn't recognise it, can get a bit confusing.

**Comment by waylan** [comment]
> `mkdocs build -h` lists `-e --theme-dir` as an option still

That is a bug. That option should be removed.
