### ISSUE TITLE
ENHANCEMENT REQ: Make sections clickable links that default to index or first child 

### ISSUE THREAD

**Issue by jmdye** [mkdocs/mkdocs#2044]
It would be really nice to not have to create a custom theme or extend the templates just to get a section to act as a clickable link which defaults to an index.html at the root of that section or the first child link or page as defined in the nav config. Take the following example:

Given a nav config of:
```
Nav:
  - Home: index.html
  - User Guide: 
    - ‘Writing your docs’: ‘/user-guide/writing-your-docs.md’ 
    - ‘Styling your docs’: ‘/user-guide/styling-your-docs.md’
  - About:
    - ‘License’: ‘/about/license.md’
    - ‘Release notes’: ‘/about/release-notes.md’
```
And a directory structure of:
```
Project
├── mkdocs.yml
├── .gitignore
├── docs
     ├── index.md
     ├── user-guide
         ├── index.md
         ├── writing-your-docs.md
         ├── styling-your-docs.md
     ├── About
         ├── index.md
         ├── license.md
         ├── release-notes.md
```
The root/home page of the site is obviously going to be at `docs/index.html` and we know that most web servers are going to return an `index.html` for any the root of any directory, so why should any customization at all be required for making a section a clickable link that navigates to the index.html at their root?

To take it a step further, in the absence of an `index.html` at the root of those directories, it would be far more intuitive if the sections still remained clickable links and just defaulted to the first child that were a page or link.

**Comment by simonvanderveldt** [comment]
Just went looking for this, was surprised that `index.md` in a subdirectory results in a `subdirectory/index` page instead of the subdirectory becoming a page one can open with the contents from `index.md`.

**Comment by waylan** [comment]
First of all, this sort of feature is completely theme dependent. In other words, there are no changes that need to be made to MkDocs for a theme to support this. Which leaves us to discuss each theme in turn:

1. The `readthedocs` theme is a clone of the Sphinx of the same name which is the default theme for the ReadTheDocs service. As it is a clone, it only includes features from the upstream theme. The Upstream theme does not include this feature, therefore, the MkDocs clone does not either.
2. An attempt was made to update the `mkdocs` theme to support this feature in #1042 however a number of issues were encountered and the attempt was abandoned. The reasons are detailed in the discussion of #1042, but in short, it was determined that the feature didn't fit with the general layout of the `mkdocs` theme.
2. IIRC, a discussion about adding this feature to the most popular third-party theme ([Material][1]) resulted in the same conclusion by the developers of that theme: that the feature doesn't fit with that theme.

In the end, the best solution would be for someone to develop a new theme from scratch which incorporates the feature from the beginning. However, MkDocs is developed by volunteers who work on it in their spare time. I certainly don't have the time to work on a new theme myself. Therefore, the best path forward would be for someone to develop a third party theme which supports the feature. I haven't checked, but it is possible that [some][2] already do.

[1]: https://github.com/squidfunk/mkdocs-material
[2]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
