### ISSUE TITLE
1.1 update adjusted side nav of readthedocs - less/no indentation

### ISSUE THREAD

**Issue by geyerbri** [mkdocs/mkdocs#2045]
It appears that the most recent update to mkdocs altered the previous indentation styling of the nav sidebar for readthedocs theme. Any idea what might be going on, and what could be done to restore the older version of indentation, while benefiting from the rest of the 1.1 update?

Here is the site, deployed with 1.0.4: https://chi-initiative.github.io/kora-documentation

Here is a temporary site, deployed with 1.1: https://geyerbri.github.io/kora-nav-test/

(edit: change terminology "compiled" to "deployed")

**Comment by waylan** [comment]
The change is consistent with the behavior of the [upstream][1] Sphinx theme. So in this case, the change was a bug fix. If you would like to change it back, then that would be a theme customization you would need to do locally.

[1]: https://sphinx-rtd-theme.readthedocs.io/en/stable/
