### ISSUE TITLE
Mkdocs CSS and icons are not in effect

### ISSUE THREAD

**Issue by soodifficult** [mkdocs/mkdocs#2056]
I configured the CSS and logo according to the documentation. The directory structure is as follows：
- docs
  -  css
    - docs.css
  -  img
    - favicon.ico
  - index.md
- sites
- mkdocs.yml

And the result like this
![image](https://user-images.githubusercontent.com/32888185/78984083-05a10a80-7b58-11ea-97cf-896606984d25.png)

But it should be like this
![image](https://user-images.githubusercontent.com/32888185/78984096-0b96eb80-7b58-11ea-8e44-b0b1f9689373.png)

BTW, could the mkdocs have the version control?
![image](https://user-images.githubusercontent.com/32888185/78984110-16ea1700-7b58-11ea-8816-8b66e1328417.png)

**Comment by waylan** [comment]
How did you link to your images?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by soodifficult** [comment]
It's said MkDocs will automatically detect and use that file as your favicon icon. Does not it?

**Comment by soodifficult** [comment]
![image](https://user-images.githubusercontent.com/32888185/79058755-81a86900-7ca4-11ea-89d4-013dead8fc49.png)

**Comment by waylan** [comment]
The `favicon.ico` is the image that is displayed in the browser tab, not the logo displayed on the page.

This one:

![Screen Shot 2020-04-12 at 10 14 51 PM](https://user-images.githubusercontent.com/78846/79086807-63c21f00-7d0b-11ea-8f6c-1aeb0f3a4d2d.png)

For a logo, you will need to check the documentation for the specific theme you are using. Neither of the built-in themes include support for a logo.

**Comment by soodifficult** [comment]
ok, thanks. But why the css not in effect? While it in effect, the right of the page should be full.
![image](https://user-images.githubusercontent.com/32888185/79090400-25b11380-7d7c-11ea-8ec9-e89426793f80.png)

**Comment by waylan** [comment]
@soodifficult your last comment is discussed in #2049. Please limit discussion of that matter to that issue.
