### ISSUE TITLE
MkDocs overrides folders that it shouldn't

### ISSUE THREAD

**Issue by Andre601** [mkdocs/mkdocs#2058]
I want to combine my API documentation and the wiki made with MkDocs in the same `docs` folder.
I want to have the built index.html in the docs folder (as a welcome page of sorts) while keeping the wiki related stuff inside a wiki folder and all API documentation in a api folder.

So you can imagine the structure as follows:
```
|- docs
    |
    |- index.html
    |- api
    |   |
    |   |- <My API docs>
    |
    |- wiki
        |
        |- <My Wiki>
```

I have setup MkDocs with the following folder structure. Note that this is **not** in the docs folder, but instead in a separate folder called wiki.
```
|- wiki
    |
    |- mkdocs.yml
    |- docs
    |   |
    |   |- index.md
    |   |
    |   |- wiki
    |       |
    |       |- <My Wiki>
    |
    |- theme
        |
        |- <Custom Theme stuff>
```

So in total the entire folder structure of my project is like this:
```
|- project
    |
    |- docs
    |   |
    |   |- index.html
    |   |
    |   |- wiki
    |   |   |
    |   |   |- <My Wiki>
    |   |
    |   |- api
    |       |
    |       |- <My API docs>
    |
    |- wiki
        |
        |- mkdocs.yml
        |
        |- docs
            |
            |- index.md
            |- wiki
            |   |
            |   |- <My Wiki>
            |
            |- theme
                |
                |- <Custom Theme stuff>
```

----
## The issue
When building the pages using `mkdocs build` does MkDocs delete the entire api folder, which contains all api documentation I have.
This is frustrating as I then have to rebuild those separately, which costs me time.

Is there any setting to ignore specific folders in the build-directory, so that won't be removed/altered?
If not, could this be added as a feature, as this is quite annoying?

**Comment by waylan** [comment]
The build directory it completely deleted and rebuilt with each build. My suggestion would be to write a custom script which copies the mkdocs build from a temporary dir to your final location on each build. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Andre601** [comment]
Is there any alternative like f.e. building the API files in the wiki directory (where mkdocs.yml is located) and make MkDocs include this folder just as that: As a folder with files in it (and without altering them)?

**Comment by waylan** [comment]
That should be possible with a plugin

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Andre601** [comment]
I just now discovered that the `build` and the `gh-deploy` command both have a `--dirty` argument.
If I understand this correctly would this argument make MkDocs not override existing files/folders unless those got changed?
Because that would be exactly what I was looking for.

**Comment by waylan** [comment]
Yes, that is their purpose. However, they do not build a production ready site. Their only purpose is when developing/writing a single page. For example, if you were to change the title of a page, that change would only be reflected on the one page and all other pages would still contain the old title. Therefore, the expectation is that a "clean" build would be run before deployment.

What you want to do can only be done in a safe way from a plugin. We will not be adding a built-in feature for this.
