### ISSUE TITLE
ReadTheDocs theme: Page does not expand to whole viewport

### ISSUE THREAD

**Issue by pranabdas** [mkdocs/mkdocs#2059]
Hello, I am seeing some page layout inconsistency in MkDocs while using *readthedocs* theme. Why there is grey area on the right of the page while serving the page via localhost? I do not see such while uploaded to GitHub and served via readthedocs.io There the page stretches over the whole viewport. 

<img width="400" alt="mkdocs" src="https://user-images.githubusercontent.com/31024886/79035850-d096c580-7bf4-11ea-8b43-5e93f85ecd82.png">

This issue was not there in the earlier version 1.0.4 of MkDocs.  Replacing the *readthedocs* theme folder from earlier version resolves the issue. Would you please look into issue with current version? Thank you.

**Comment by froschdesign** [comment]
Duplicate of #2049

**Comment by pranabdas** [comment]
This issue was not there in the previous version of MkDocs (I tested on version 1.0.4). One temporary workaround would be to install previous version of MkDocs. 
```
pip uninstall mkdocs 
pip install -Iv mkdocs==1.0.4
``` 
If your project dependent on the latest version of MkDocs, go to the themes folder (`.../python3.7/site-packages/mkdocs/themes/` in my case) and backup *readthedocs* theme folder. Later install latest version of MkDocs, and replace the *readthedocs* theme folder.
