### ISSUE TITLE
Plugins and strict mode

### ISSUE THREAD

**Issue by pawamoy** [mkdocs/mkdocs#2064]
Is there a recommended way for plugins to plug themselves on `mkdocs` logging system? I'm particularly interested in making the build or serve commands fail when I log a warning.

Looking at the code, I see that I can simply do

```python
import logging

from mkdocs.utils import warning_filter

log = logging.getLogger(__name__)
log.addFilter(warning_filter)
```

...and then use `log.warning("message")` normally.

Is this the recommended method or is there a better way?

Also, it seems that warnings only will be counted:

```python
if record.levelno == logging.WARNING
```

Shouldn't errors and critical errors be counted as well, to make the build/serve commands fail?

Happy to send the following patch if yes :smile:!

```python
if record.levelno >= logging.WARNING
```

**Comment by waylan** [comment]
> ...and then use `log.warning("message")` normally.
> 
> Is this the recommended method or is there a better way?

Yes, that is the standard way in Python and we are doing nothing different here.

> Shouldn't errors and critical errors be counted as well, to make the build/serve commands 
fail?

No, we handle warnings separately from errors. Warnings only get counted in `strict` mode, whereas errors get accounted for regardless of strict mode. In other words, an error will always cause a failure, while a warning will only cause a failure in strict mode. The code you are referencing is what forces warnings to look like errors when in strict mode.

**Comment by pawamoy** [comment]
Ah I understand better now. It makes sense.

Then how can I make the build fail from my plugin when I issue an error? Logging an error does not make it fail :confused: 

Should I simply raise an exception?

**Comment by waylan** [comment]
Yes, raise an exception.

**Comment by pawamoy** [comment]
OK thanks

**Comment by oprypin** [comment]
Oh woops, didn't notice this conversation, and posted https://github.com/mkdocs/mkdocs/issues/2082. I expand on more issues there, and I feel this is not sufficiently resolved.

**Comment by pawamoy** [comment]
Indeed, I realized yesterday that my logs now do not follow the verbose option. Plugins logging should be at least documented :slightly_smiling_face: I'll continue on your issue.
