### ISSUE TITLE
Better deployment integration with Github

### ISSUE THREAD

**Issue by root-ansh** [mkdocs/mkdocs#2072]
Hi Team! So i have been using this product for more than a year now, and i absolutely love it! This has been the most manageable solution for a decent static website for me as of now.  

Every aspect of this product is good, but I was wondering if the integration with gh-pages could be made a little more automated.  

Like if I have a website deployed on gh-pages, and somebody wants to edit a small typo in one of the pages. The process to fix that typo would go something like this:  

1. They will make a PR changing the markdown file in the `docs` .  
2. I will be reviewing their PR and manually merging it  
3. i will be then pulling the changes on my local system  
4. then i would be doing `mkdocs gh-deploy` which would generate new web page and deploy it

is there a way i could  skip steps 3 and 4 and make the website automatically generate  as soon as a new change is made in the `docs` folder ?

**Comment by waylan** [comment]
Yes, you can configure a CI server to pull the changes, build, and push. See Github's documentation on [webhooks][1] for details. Note that the details depend on which CI server you are using and are not specific to MkDocs. So long as you can get GitHub and your server to talk to each other, an automated call to `mkdocs gh-deploy` will work.

[1]: https://help.github.com/en/github/extending-github/about-webhooks

**Comment by root-ansh** [comment]
oh okay i have heard about those. would give them a try, thanks!
