### ISSUE TITLE
Change default navigation icon

### ISSUE THREAD

**Issue by ghost** [mkdocs/mkdocs#2075]
I want to change the default hamburger icon in the navigation to something else. On big screens it has a side navigation, but on smaller screens it becomes hidden with a hamburger icon to toggle show / hide.

I know this is standard but Im already using this icon on my side and I want to swap it with another icon for the mkdocs. Is that possible and if yes how can i do this?

Thanks for all answers!

**Comment by waylan** [comment]
See [Customizing a Theme][1] in the documentation for various ways in which a theme can be customized.

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme
