### ISSUE TITLE
Disabling building for markdown not specified in `nav`

### ISSUE THREAD

**Issue by nfalliere** [mkdocs/mkdocs#2080]
I've been looking for a flag to disable the processing for input *.md files present in the docs/ folder, but not explicitly specified in the "nav:" section of the configuration file.

Any way to do that, either through flag, config, plugin, or code tweak?

**Comment by waylan** [comment]
That would be something a plugin could do. I am not sure if any plugins exist which do so. You can find the list of known plugins in the [wiki](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins)

**Comment by nfalliere** [comment]
Thank you @waylan for providing this wiki link, I found that [mkdocs-exclude](https://github.com/apenwarr/mkdocs-exclude), listed on the page, provides exactly the functionality I was looking for!
