### ISSUE TITLE
Code fragments suddenly on single line

### ISSUE THREAD

**Issue by bvdberg** [mkdocs/mkdocs#2083]
I am using mkdocs for [c2lang.org](c2lang.org/site). When I upgrade to Ubuntu 18 (and now to 20) mkdocs suddenly started putting all my code fragments on a single line. I have used Docker with Ubuntu 16 to work around the issues, but it's becoming too much. I tried many different things, but none seem to help. Please see the difference between the [working version](http://www.c2lang.org/site/introduction/code_fragments/) and the non_working. For the non-working, please clone git@github.com:c2lang/documentation.git and run the mkdocs in documentation/

Please note I'm still using the 'pages' option (and not 'nav') because I'm using the workaround in Ubuntu 16.

**Comment by waylan** [comment]
Can you please provide me with an example? Provide the Markdown source, the expected HTML and the actual HTML. You may need to use your browser's 'view source' feature. And please don't provide the source for an entire page, but only one small relevant section.

**Comment by bvdberg** [comment]
Ok, so the markdown of a small fragment looks like:

NOTE: I had to replace the backtics, because github also interprets them..
```
3BACKTICS c
func void demo_if(i32 a) {
    if (a > 0) {
        // ..
    } else {
        // ..
    }
}
3BACKTICS
```

The HTML code I get _in both cases_ is:
```
<pre><code class="c">func void demo_if(i32 a) {
    if (a &gt; 0) {
        // ..
    } else {
        // ..
    }
}
</code></pre>
```

Looking at the diff in generated files, I when I overwrite the css/theme.css, my code fragment is suddenly expanded, not not colored and good looking. The minimal set of file I need to replace to have the old looks is:
css/theme.css
js/jquery-2.1.1.min.js  (orig size: 84Kb new size 137Kb, same filename)
js/theme.js

So it appears the jquery and theme do something. I can supply both files if you think that helps, but both contain very longs lines of (to me) gibberish...

**Comment by waylan** [comment]
This is theme specific. Which theme are you using?

**Comment by bvdberg** [comment]
ahh nice, 4 backtics :+1: 
I'm using readthedocs.

The weird thing is that this issue popped up when updating from Ubuntu16 (mkdocs version mkdocs, version 0.14.0) to Ubuntu 18 (cannot find version easily) and later 20, which has _mkdocs, version 1.0.4_

Is there a way to add the theme and js files in my archive, so I can just use those?

**Comment by waylan** [comment]
Do you have the [`fenced_code`][1] extension [enabled][2] in your config file? Being able to enable extensions was added after 0.13.0 so I assume you are, but it doesn't hurt to check. 

I have found the `mkdocs` packages provided by system specific package managers to be problematic. Those packages are all created and maintained by third parties who are not members of the dev team. We only have control of and officially support the packages distributed on PyPI.

Do you see the same behavior when installing MkDocs from PyPI with `pip install mkdocs`? If this is unique to the Ubuntu package, then you will need to report it to the package manager.

[1]: https://python-markdown.github.io/extensions/fenced_code_blocks/
[2]: https://www.mkdocs.org/user-guide/configuration/#formatting-options

**Comment by bvdberg** [comment]
I'll try the pip option tomorrow! thx for your help so far!

**Comment by bvdberg** [comment]
I will try ..
