### ISSUE TITLE
Is there a way to render a raw markdown file in Mkdocs?

### ISSUE THREAD

**Issue by SamazoOo** [mkdocs/mkdocs#2084]
Is there a way to render a raw markdown file in Mkdocs?

I would like to render a raw file for example with a link https://raw.githubusercontent.com/mkdocs/mkdocs/master/README.md
Is it possible?

Thanks!

**Comment by waylan** [comment]
To "render" a Markdown file means to convert it to HTML. I suppose you mean to ask if there is a way to copy a raw Markdown file without rendering it? 

If that is your question, the answer is: Officially no. However, MkDocs identifies Markdown files by their file extension. If you included a Markdown document which did not use one of the known file extensions for Markdown (for example you used `.txt`) then that would get copied, but not rendered to HTML. Alternatively, a plugin could instruct MkDocs to not render certain documents. I don't recall if one exists, but you can find the list of known plugins is in the [wiki][1].

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Comment by SamazoOo** [comment]
I mean that if there are any way to do something like

nav:
    - Home: index.md
    - About: https://raw.githubusercontent.com/mkdocs/mkdocs/master/README.md

I would like to show different readme markdowns from different projects inside a Mkdocs. It's like to put together all info across some projects.
I guess that the problem is that every time any README has changed, I have to build Mkdocs to get the new info. But, that's normal.

Thank you!

**Comment by waylan** [comment]
No, out-of-the-box, MkDocs only gets its sources from files within the `docs_dir`. However, alternatives are possible with a plugin.

> I guess that the problem is that every time any README has changed, I have to build Mkdocs to get the new info. But, that's normal.

Yes, that is how a "static site generator" works. If you don't want that workflow, then perhaps you shouldn't be using a static site generator.

**Comment by SamazoOo** [comment]
Thanks! I found mkdocs-snippet-plugin for that.

https://github.com/mprivat/mkdocs-snippet-plugin
