### ISSUE TITLE
Prevent capitalisation of directory names in menu

### ISSUE THREAD

**Issue by mlevit** [mkdocs/mkdocs#2086]
I've noticed that when `nav` is not specified and mkdocs generates the navigation for me, it removes underscores (_) and capitalises the first letter. Is there a possibility to prevent this behaviour to happen:

![image](https://user-images.githubusercontent.com/233717/80673605-0e4f8580-8af3-11ea-876e-c40ca74bdd7f.png)

This is what the directory structure looks like:

![image](https://user-images.githubusercontent.com/233717/80673641-27f0cd00-8af3-11ea-88b9-c4cf8ed67868.png)

**Comment by waylan** [comment]
The only way to control the formatting of section names in the nav is to define them in the config.

**Comment by mlevit** [comment]
@waylan that's not possible for me as the markdown files are auto-generated using a Python script, and hence I don't know how many pages I'm going to have.

I need mkdocs to pick up everything that is generated (which it's doing) but I just don't want mkdocs to change the naming conventions I use (i.e., lower case and non-caps).

**Comment by waylan** [comment]
No, this is not supported.

**Comment by mlevit** [comment]
@waylan do you think we could tweak

```python
def dirname_to_title(dirname):
    """ Return a page tile obtained from a directory name. """
    title = dirname
    title = title.replace('-', ' ').replace('_', ' ')
    # Capitalize if the dirname was all lowercase, otherwise leave it as-is.
    if title.lower() == title:
        title = title.capitalize()

    return title
```

so it takes only modifies the paths when a variable in the config file is set to true?

**Comment by waylan** [comment]
We try to keep the number of config settings to a minimum. In fact, any recent changes to the config settings have been to remove settings, not add them. I would suggest exploring using a plugin to accomplish what you want.

**Comment by zgramana** [comment]
The current behavior violates the Principle of Least Astonishment, as navigation menu options in the vast majority of English sites (at least) are in proper case instead of sentence case. One expects proper case to be the default behavior if it cannot be configured. If there is a strong use case for sentence case, perhaps let those people then implement a plugin.

**Comment by lstagner** [comment]
I just ran into this issue. I would also prefer it to not capitalize and remove the underscores from the files/directories. I have a script that creates a markdown file from each source file and the capitalization and lack of underscores makes things look awkward

**Comment by amanbolat** [comment]
I had the same problem, so I found a plugin that solves the problem.
[lukasgeiter/mkdocs-awesome-pages-plugin](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin)

After installing the plugin I added the `.pages` file inside the `docs` folder with content:

```yaml
nav:
    - About: index.md
    - SSH: ssh
    - ...
```

The result:

![image](https://user-images.githubusercontent.com/15110242/163663156-ed0a645a-06ae-47f2-85a5-07bc395a7dcc.png)

**Comment by pawamoy** [comment]
Similar to #1289, see comment https://github.com/mkdocs/mkdocs/issues/1289#issuecomment-2057015122. Additionally, it's partially solved by the awesome pages plugin. For the reasons mentioned here and in the linked comment, we'll close as out of scope for now. Feel free to comment further or ask to re--open if you'd like to work on that.
