### ISSUE TITLE
[Feature Request] Hashtags

### ISSUE THREAD

**Issue by domenecsos** [mkdocs/mkdocs#2087]
In the hope that his is the correct channel for a feature request :)

A hashtag as in social media, so that writing #whatever in markdown generates an HTML link to a page (say /hashtags/whatever) with a list of pages containing said hashtag. 

The /hashtags/whatever page for a #whatever hashtag would be composed of:
- The usual navigation, but filtered to only pages with the hashtag
- In the body:
      - For each page containing the hashtag, a header
      - Under the page header, each of the paragraphs containing the hashtag. 
            - Clicking on them would navigate to said paragraph in the page. 
            - This would requiere to add a #whatever_number anchor in HTML
            - _number just in cases there is more than a #whatever in markdown
- The hashtag pages could be preexisting /hashtags/whatever.md pages that would generate their markdown and then the list of hashtagged pages described above.

Just for fun, /hashtags could show a hashtag cloud, linking to each hashtag page and/or a hashtag list.

I'd like to help with development, but all the Python I've done is Jython for configurin Weblogic :) I have some pseudocode in mind, if this helps.

Thanks for considering.

**Comment by waylan** [comment]
Sounds like a great candidate for a Markdown extension and/or MkDocs plugin.

In fact, the Mkdocs documentation makes use of the GitHub specific Markdown extension [Python-Markdown/github-links][1], which offers some of the requested features. See the [config file][2] and the [release notes][3] for the examples of use.

Of course, that doesn't provide a hashtag cloud.  Seems to me something like that would be out-of-scope for a "static site generator" but a MkDoc [plugin][4] could certainly be used. This would need to be a third-party plugin. We will not be adding this to MkDocs directly. 

[1]: https://github.com/Python-Markdown/github-links
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml#L38-L40
[3]: https://www.mkdocs.org/about/release-notes/
[4]: https://www.mkdocs.org/user-guide/plugins/

**Comment by domenecsos** [comment]
Thanks for considering, waylan. I'll check that documentation to see if I can get close without touching code. I'm a very senior Java architect, but totally ignorant of Python (unless you count Jython for administering Weblogic ;)

**Comment by oprypin** [comment]
This will not be in MkDocs core, can be a plugin
