### ISSUE TITLE
Navigation and TOC like readthedocs

### ISSUE THREAD

**Issue by htleeab** [mkdocs/mkdocs#2088]
I'm considering switch to mkdocs from sphinx, but cannot solve the navigation issue.
This is a [sample](https://machine-learning-note.readthedocs.io/en/latest/) built with sphinx + [recommonmark](https://github.com/readthedocs/recommonmark)+ readthedocs theme+ readthedocs host
readthedocs theme should support 
1. multi-level nav
1. clickable index links/page
1. auto-generate TOC with sub-level

recommonmark do not have nav config. Its TOC is based on list of link inside xxx.md file.  For example, `index.md` points to `generative_models/index.md`, which points to `generative_models/GAN/index.md`, which points to  `generative_models/GAN/GAN_image2image.md` 

If using custom theme that render first index page as clickable link, I still need write the links twice (nav config + index.md).
Is it possible to generate navigation and TOC like recommonmark does without write links twice?

**Comment by waylan** [comment]
Sphinx and MkDocs do some things very differently and features don't always translate well from one to the other. MkDocs navigation is defined in the config file as [documented][1].

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
