### ISSUE TITLE
"There is no disk in the drive" error 

### ISSUE THREAD

**Issue by pylang** [mkdocs/mkdocs#2090]
FYI: I got this error after installing the latest version of mkdocs (1.1) and running the dev server:

    > mkdocs serve

The issue doesn't seem [python related](https://bugs.python.org/issue22739).

The new install included:

    - mkdocs=1.1
    - mkdocs-material=5.1
    - mkdocs-material-extensions=1.0b2

Workaround: downgraded to version mkdocs < 1.1 and mkdocs-material < 5.

No errors.

No error.

**Comment by waylan** [comment]
Could you please provide the entire error with traceback?

Also, I do not see any relation between this and the linked Python bug report.

**Comment by pylang** [comment]
There was no traceback; only a popup with the error mentioned.  I've moved on since.  

I submitted the issue so you have the bug documented should another issue arise.

Closing.
