### ISSUE TITLE
Create and use local plugins

### ISSUE THREAD

**Issue by aklajnert** [mkdocs/mkdocs#2091]
As the [documentation](https://www.mkdocs.org/user-guide/plugins/) mentions, the plugin has to be a separate Python package which has to be registered in the `entry_points`.  

In my case, I have a simple script that does some pre-build operations on the documentation sources. The only way to run it automatically, for now - is to create another package that would register itself as the plugin. 

How about allowing to load plugins that are just local files? E.g. `- docs.custom_plugin::MyPluginClass` would load `MyPluginClass` from the `docs/custom_plugin.py`. Of course, the `MyPluginClass` should follow the plugin API by inheriting the `BasePlugin` class.

**Comment by waylan** [comment]
If we were to support such a feature, it would need to be in a separate directory from the documentation (just like a theme's `custom_dir`). However, it is not much work to make a local package, which ensures the code is on the PYTHONPATH. 

Personally, my vote is to not do this. It is much cleaner with all Python code being installed.

**Comment by aklajnert** [comment]
Since the directory containing `mkdocs.yml` is already in `PYTHONPATH`, it should be fairly easy to import local plugins by referencing its path. I don't understand why it has to be a separate directory, I think it can be wherever the user want it.  

I know that creating an installable package is not much work, but it feels a bit unnatural. If you work on a library, you can't add plugin entry point to the `setup.py` of the package to avoid registering (and possibly shadowing) internal plugin in people's environment.

**Comment by aklajnert** [comment]
For now, I've created a generic plugin that allows calling any code from within the project as a hook. In case anybody needs it, you can find it here: https://pypi.org/project/mkdocs-simple-hooks/

**Comment by waylan** [comment]
Awesome. I love this being a plugin. Be sure to add it to the [list on the wiki][1] (if you haven't already).

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Comment by GeneralZero** [comment]
For those that want to do a plugin locally here are the steps to get it to work. First make sure you add the folder with the extension into the PYTHONPATH. I did this through the following command. ```export PYTHONPATH=`pwd` ```

**mkdocs.yml:**
```yml
markdown_extensions:
[...]
  - common_fix:CommonFixExtention
```

**common_fix.py:**
```python
from markdown.preprocessors import Preprocessor
from markdown.extensions import Extension
import re

class CommonFixExtention(Extension):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def extendMarkdown(self, md):
        """ Add FencedBlockPreprocessor to the Markdown instance. """
        md.registerExtension(self)

        md.preprocessors.register(NewLineAfterList(md), 'common_fix', 5)


class NewLineAfterList(Preprocessor):
    """ Skip any line with words 'NO RENDER' in it. """
    def run(self, lines):
        new_lines = []
        not_empty_last_line = True

        for line in lines:
            if bool(re.search(r'^[ ]{0,3}((\d+\.)|[*+-])[ ]+(.*)', line)) and not_empty_last_line:    
                # Append a new line before the list if the previous one was empty
                new_lines.append("")  
                new_lines.append(line)
                #print("Found Line: {}".format(line))
            
            else:
                new_lines.append(line)
            
            not_empty_last_line = (line.strip() != '')

        return new_lines

def makeExtension(**kwargs):  # pragma: no cover
    return CommonFixExtention(**kwargs)
```

**Comment by waylan** [comment]
@GeneralZero, you appear to be discussing Markdown extensions while this issue is about MkDocs plugins. The two are very different things.

**Comment by thesuperzapper** [comment]
For those who come across this issue, as of MkDocs 1.4 there is a native [`hooks` feature](https://www.mkdocs.org/user-guide/configuration/#hooks)!
