### ISSUE TITLE
High CPU Load

### ISSUE THREAD

**Issue by petrmachcz** [mkdocs/mkdocs#2092]
A have High CPU Load (> 20 %) with MkDocs + Material on Lenovo T460s (i5-6200U, 20 GB Ram). Notebook is hot, fan is humming and battery discharges quickly. 

High load occurs during `mkdocs serve`. If I use `mkdocs serve --no-livereload`, load is OK.

High load happens even with minimal content.

SITE-TEST:
```
    docs:
        index.md
    mkdoc.yml
```

index.md:
```
# Hello World
```

mkdoc.yml
```
site_name: Test
theme:
    name: material
    language: cs
```

Load is normal, if I remove theme material.

My enviroment:

```
C:\Users\petrm>python --version
Python 3.8.2
```

```
C:\Users\petrm>python -m pip show mkdocs
Name: mkdocs
Version: 1.1
Summary: Project documentation with Markdown.
Home-page: https://www.mkdocs.org
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: c:\users\petrm\appdata\roaming\python\python38\site-packages
Requires: PyYAML, livereload, lunr, Markdown, click, tornado, Jinja2
Required-by: mkdocs-material
```

```
C:\Users\petrm>python -m pip show mkdocs-material
Name: mkdocs-material
Version: 5.1.4
Summary: A Material Design theme for MkDocs
Home-page: https://squidfunk.github.io/mkdocs-material/
Author: Martin Donath
Author-email: martin.donath@squidfunk.com
License: MIT
Location: c:\users\petrm\appdata\roaming\python\python38\site-packages
Requires: pymdown-extensions, mkdocs, Pygments, mkdocs-material-extensions, markdown
Required-by: mkdocs-material-extensions
```

```
C:\Users\petrm>systeminfo

Host Name:                 T460S-WIN
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Uživatel systému Windows
Registered Organization:
Product ID:                00342-50620-20329-AAOEM
Original Install Date:     29.10.2019, 23:22:13
System Boot Time:          22.04.2020, 12:13:28
System Manufacturer:       LENOVO
System Model:              20FAS47X00
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 78 Stepping 3 GenuineIntel ~2300 Mhz
BIOS Version:              LENOVO N1CET45W (1.13 ), 02.06.2016
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             cs;Čeština
Input Locale:              cs;Čeština
Time Zone:                 (UTC+01:00) Praha, Bratislava, Budapešť, Bělehrad, Lublaň
Total Physical Memory:     19 907 MB
Available Physical Memory: 14 060 MB
Virtual Memory: Max Size:  22 851 MB
Virtual Memory: Available: 16 008 MB
Virtual Memory: In Use:    6 843 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\T460S-WIN
```

**Comment by squidfunk** [comment]
Related to #2601

**Comment by waylan** [comment]
> If I use `mkdocs serve --no-livereload`, load is OK.
>
> Load is normal, if I remove theme material.

Those are the two factors. The material theme has a lot of files, and watching a lot of files puts extra strain on the system. Especially if the system doesn't have an API for watching files. While Windows does have an API, my understanding is that it is less performant than Linux and Mac and you should expect more strain.

Overall, there is not much we can do. We only provide a light wrapper around [lepture/python-livereload][1]. Any performance issues with the watcher should be addressed there. The theme could reduce the number of files, but then you would loose the features it offers (besides that would be something to discuss with the Material devs, not here). That only leaves #2061 as something we can do. Therefore, I am closing this as a duplicate.

[1]: https://github.com/lepture/python-livereload

**Comment by squidfunk** [comment]
Wouldn't it solve the problem if we exclude theme files from `mkdocs serve`?

**Comment by waylan** [comment]
> Wouldn't it solve the problem if we exclude theme files from `mkdocs serve`?

That is certainly an option. However, when I'm working on a theme (editing templates or CSS) I want to have the theme files watched. Of course, I'm only ever working on smaller themes with only a few files, so it's a non-issue for me.

Perhaps the default should be to not watch theme files. Then we could add an option to include theme files for those occasions were it is desired.

**Comment by squidfunk** [comment]
That sounds like a great idea. I think for most of tauthors, watching theme files isn’t necessary. So I guess this could be implemented as an enhancement?

**Comment by waylan** [comment]
Actually, I'm going to classify this as a performance improvement and include it in the next buggies release. See #2094.

**Comment by petrmachcz** [comment]
Thanks you.

**Comment by dato** [comment]
I hope #2094 can be merged and released soon. Patching it locally, it solves my problem.

Some data: I tend to leave my `mkdocs serve` permanenty running in a systemd --user unit, because I edit several websites several times a week. With the patch, after 19hs up, CPU time _without having edited the site_ is 12 minutes. Another instance without the patch, 155 minutes CPU time (without having edited the site too).

Many thanks for diagnosing and proposing a fix. Being able to patch locally is already a great relief.

-----
(FWIW I must also note that 12 minutes/day is still one an order of magnitud above what `jekyll serve` [from which I am migrating] consumes [roughly 1min/day when idle, for the same sites].)

**Comment by waylan** [comment]
FYI, for anyone who has experienced performance issues with the server. We are looking at replacing the server with a different implementation which should address the concerns raised here. See #2385 for details and feel free to test and provide feedback there.
