### ISSUE TITLE
Three-level navigation expands question

### ISSUE THREAD

**Issue by wxy1234567890** [mkdocs/mkdocs#2096]
## Details

 when I use the readthedocs  theme and  run at http://127.0.0.1:8000/.
The three-level navigation expands some levels. The page looks bad.

## Expected Result

*I wanted to expands by default the first item, however, some other items expand*

how can I solve this problem.

**Comment by waylan** [comment]
As the [documentation][0] explains, the theme is (emphasis added)...

> A clone of the default theme used by the [Read the Docs[[1] service, which offers the same restricted feature-set as its parent theme. Like its parent theme, **only two levels of navigation are supported**.

That being the case, if yo use 3 or more levels of navigation, nothing will display correctly. You **must** rearrange your navigation to 2 levels or use a different theme.

[0]: https://www.mkdocs.org/user-guide/styling-your-docs/#readthedocs
[1]: https://readthedocs.org/
