### ISSUE TITLE
Use python static typing info

### ISSUE THREAD

**Issue by Yajo** [mkdocs/mkdocs#2097]
If your python project uses things such as [mypy](http://mypy-lang.org/) or [pydantic](https://pydantic-docs.helpmanual.io/), or basically any [python types](https://docs.python.org/3/library/typing.html), IMHO mkdocs should render those in the docs. If possible, with links to the classes, at least if defined in this same project.

**Comment by pawamoy** [comment]
This should be transfered to [mkdocstrings](https://github.com/pawamoy/mkdocstrings) :stuck_out_tongue:

**Comment by waylan** [comment]
Sorry, but I don't see any actionable item here for MkDocs. You point to the mkdocsstrings plugin, which is one of [many doc generation plugins][1] for MkDocs. This plugins could certainly add such  feature if they desire, but there is nothing for MKDocs to do here. Or am I missing something?

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#api-documentation-building

**Comment by pawamoy** [comment]
No no you're right, that's what I meant by "this one can be closed": you can close this issue, it was supposed to be opened in mkdocstrings :slightly_smiling_face:
