### ISSUE TITLE
formatting issue in 'Writing Your Docs' section

### ISSUE THREAD

**Issue by zachvalenta** [mkdocs/mkdocs#2098]
It seems like the 'note' text block in [file layout](https://www.mkdocs.org/user-guide/writing-your-docs/#file-layout) should be formatted like its counterpart in [MultiMarkdown Style Meta-Data](https://www.mkdocs.org/user-guide/writing-your-docs/#multimarkdown-style-meta-data).

The Markdown for each looks the same, so not sure what's up, just wanted to bring it to your attention.

**Comment by waylan** [comment]
This is a duplicate of #2060 where it was fixed. The fix will go live on the site with the next release.
