### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by ericholscher** [mkdocs/mkdocs#21]
It would be great to support multiple languages of documentation. Presumably using something like gettext.

**Comment by majkinetor** [comment]
It seems like unicode is not supported. Both in yaml and md files I get the following error with cyrilic text:

```
Traceback (most recent call last):
  File "C:\Python34\Scripts\mkdocs-script.py", line 9, in <module>
    load_entry_point('mkdocs==0.11.1', 'console_scripts', 'mkdocs')()
  File "C:\Python34\lib\site-packages\mkdocs\main.py", line 60, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "C:\Python34\lib\site-packages\mkdocs\main.py", line 33, in main
    serve(config, options=options)
  File "C:\Python34\lib\site-packages\mkdocs\serve.py", line 82, in serve
    build(config, live_server=True)
  File "C:\Python34\lib\site-packages\mkdocs\build.py", line 266, in build
    build_pages(config)
  File "C:\Python34\lib\site-packages\mkdocs\build.py", line 206, in build_pages
    input_content = open(input_path, 'r').read()
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 28: character maps to <undefined>
```

**Comment by majkinetor** [comment]
When I change the code so that in `build.py` it is:

        input_content = open(input_path, 'r', encoding='utf-8').read()

it produces correct output. The similar changes should be done with yaml since it also tries to cp1252.

**Comment by d0ugal** [comment]
Interesting, thanks @majkinetor. I know some people have had success, for example: http://programming-pro-php.readthedocs.org/zh_CN/latest/

Can you report this in a new issue?

**Comment by majkinetor** [comment]
Thanks for the link.
I will try to find out what it is. I am not experienced in python, the thing behaves strange becuase utf-8 should be default mode... 

Will let you know if this is really an issue or something on my system...

**Comment by majkinetor** [comment]
More info.

I am on Windows 7 and this code work:

```
f = open('c:/test.md', encoding='utf-8')
o = open('c:/test_p.md', 'w',  encoding='utf-8')
o.write(f.read())
```
When I remove `encoding` parameter it doesn't work any more. `sys.getdefaultencoding()` returns `utf-8`. `Open` documentation states:

>The default encoding is platform dependent, but any encoding supported by Python can be passed. 

When I save in vim using `set bom` above code works, however, it still doesn't work in mkdocs without explicit settings and yaml reading fails in every case.
