### ISSUE TITLE
Website generated by mkdocs build not correct (Path issue?)

### ISSUE THREAD

**Issue by seekM** [mkdocs/mkdocs#2102]
My setting (using Windows 10):
```
PS C:\Users\User\Documents\music\tmp> python --version
Python 3.8.2
PS C:\Users\User\Documents\music\tmp> mkdocs --version
mkdocs, version 1.1 from c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\mkdocs (Python 3.8)
```

I have a simple `mkdocs.yml` file:

```
site_name: MkLorum
nav:
    - Home: 'index.md'
    - About: 'about.md'
```

with the corresponding `md` files.

Running `mkdocs serve` I can view the content of `about.md` at `http://127.0.0.1:8000/about/`.

However, after sucessfully  running `mkdocs build`, `file:///C:/Users/User/Documents/music/tmp/site/about/` (this is where clicking at "About" from the main page takes me) doesn't show any website. Instead it shows a view in which you can navigate the directory structure of the filesystem.

**Comment by waylan** [comment]
You have two options:

1. Put your built site behind a server, which will properly serve index files.

    As you are working on your site, we provide a `mkdocs serve` command so that you can browse your site behind a server. Of course, once you upload the built site to a server, that will be a non-issue anyway.

2. Disable the [use_directory_urls][1] config setting so that all files are written to `filename.html` rather than index files (filename/index.html).

    However, if you intend to use the built site without a server, then I should warn you that this is not an officially supported use case for MkDocs. While it will work if you disable `use_directory_urls`, other things will never work properly. For example, due to browser security settings, the search feature will never work without a server involved.

[1]: https://www.mkdocs.org/user-guide/configuration/#use_directory_urls

**Comment by seekM** [comment]
I wasn't aware that web servers work this way. I just deployed a test site to Github and I can browse the site there correctly. Thanks for your detailed answer!
