### ISSUE TITLE
Broken link in deploying documentation

### ISSUE THREAD

**Issue by seekM** [mkdocs/mkdocs#2104]
https://www.mkdocs.org/#deploying links to [GitHub project pages](https://help.github.com/articles/creating-project-pages-manually/) which doesn't work anymore. I'm not sure what the correct links is now -- maybe https://pages.github.com/?

**Comment by waylan** [comment]
Thanks for the report. GitHub is constantly refactoring their docs. Its hard to maintain a good link.

**Comment by KhushbuB** [comment]
I found [Creating a GitHub Pages site](https://docs.github.com/en/enterprise-server@2.22/github/working-with-github-pages/creating-a-github-pages-site) is the correct link.
