### ISSUE TITLE
Favicon.ico not picked up when using mkdocs serve

### ISSUE THREAD

**Issue by seekM** [mkdocs/mkdocs#2105]
I set up a minimal project following [the documentation](https://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme-custom_dir) to overwrite the favicon.

The favicon is overwritten successfully after running `mkdocs build`, but it is not (both not in the tab and in a bookmark) when viewing the site via `mkdocs serve`. I tested this using Firefox.

**Comment by waylan** [comment]
Did you clear your browser's cache?

Do you see a request for it in the server logs? What is the response given?

**Comment by seekM** [comment]
Apparently the cache wasn't cleared, I thought I had done this. Sorry. It is working as expected!
