### ISSUE TITLE
Prevent layout shifts by inserting width/height attributes on img/video tags

### ISSUE THREAD

**Issue by TheJaredWilcurt** [mkdocs/mkdocs#2107]
**What is layout shift:**

A "layout shift" is when loading a page, the content moves. For example, linking to the bottom of a long page of documentation with many images will show the correct section until the above images load in, pushing the content further down the view port.

* **More info on cumulative layout shifts:** https://web.dev/cls

* * *

One solution to this is to bake in height/width attributes into the markup.

```html
<img src="file.png" width="1280" height="720" alt="Example" />
<video src="file.mp4" width="1280" height="720" controls autoplay loop></video>
```

In [Firefox 69](https://bugzilla.mozilla.org/show_bug.cgi?id=1547231) and [Chrome 79](https://www.chromestatus.com/feature/5695266130755584), a new feature was added where the browsers will look at these attributes and calculate the correct aspect ratio while doing page layout. This results in the height of the image being predictable prior to any network requests being initiated for the image files. Thus allowing the layout of the page to be determined with just HTML and CSS. Any CSS applied to the element (such as `max-width: 100%` or `width: 300px`) will supersede the inline attributes. The inline attributes are only used for determining initial aspect ratios.

Since mkdocs statically generates the HTML it could look for all images/videos relatively linked in the markdown, then read the image/video files to find the dimensions and insert them into the outputted HTML.

Before switching to MKDocs, I was doing this in Node using the Node modules `image-size` (for png/gif) and `@ffprobe-installer/ffprobe` (for mp4). I assume there are similar Python libraries for detecting file dimensions.

**Comment by waylan** [comment]
Interesting. However, the body text of each page is generated by Markdown and Markdown doesn't offer this feature. 

> Since mkdocs statically generates the HTML it could look for all images/videos relatively linked in the markdown, then read the image/video files to find the dimensions and insert them into the outputted HTML.

That would require MkDocs to take the output of Markdown, parse it, then look for images, act on them, and serialize back to a string. Seems like a lot of work. As a reminder, unlike Node, Python doesn't get a built-in DOM for free. Instead we pass around a string of HTML.

Perhaps a better strategy would be to use a [Markdown extension][1]. MkDocs supports using any extension so long as it's installed, so we don't need to do anything here.

[1]: https://www.mkdocs.org/user-guide/configuration/#formatting-options
