### ISSUE TITLE
Can mkdocs support multi navigation for readthedocs theme

### ISSUE THREAD

**Issue by hpatil47** [mkdocs/mkdocs#2118]
Can mkdocs support multi navigation for readthedocs theme

**Comment by hpatil47** [comment]
We have created the custom theme with the help of mkdocs readthedocs theme, we are able to do two level navigation. but now we are trying to do 3rd level navigation. is it possible for read the docs theme ?

**Comment by waylan** [comment]
The readthedocs theme is a clone of the Spinx theme of the same name, As the upstream theme only supports tow levels, so does our clone. There are no plans to change that so long as that is the behavior of the upstream theme.
