### ISSUE TITLE
Conditions in mkdocs.yaml file

### ISSUE THREAD

**Issue by bilal-fazlani** [mkdocs/mkdocs#2119]
I want to be able to include or exclude pages from nav depending on an environment variable

**Comment by timvink** [comment]
That would be a great use case for a MkDocs plugin. There are already [quite some plugins](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins) around dealing with the navigation.

This feature might fit for example in [awesome-pages](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin)
