### ISSUE TITLE
How to add noindex and nofollow to docs?

### ISSUE THREAD

**Issue by niklasfjeldberg** [mkdocs/mkdocs#2120]
How do I add noindex and nofollow to docs?

**Comment by niklasfjeldberg** [comment]
I found out how to do this.

mkdocs.yml
`theme:
    name: readthedocs
    custom_dir: custom_theme/`

custom_theme/main.html
`{% extends "base.html" %}

{% block site_meta %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,noarchive,nofollow" />
{% endblock %}`

**Comment by challet** [comment]
It can even re-use the parent block output :

```py
{% extends "base.html" %}

{% block site_meta %}
    {{ super() }}
    <meta name="robots" content="noindex,noarchive,nofollow" />
{% endblock %}
```
