### ISSUE TITLE
can mkdocs serve on static site directly?

### ISSUE THREAD

**Issue by ozbillwang** [mkdocs/mkdocs#2121]
Since I have `build` the site. Could I `serve` the static site directly?

such as

```
mkdocs serve --site site
```

with that, I don't need build again and again.

currently everytime run `mkdocs serve`, it always runs `build` first

another interesting part is, I can't see the `site` folder when run `mkdocs serve`

```
bash-5.0# mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Documentation built in 0.09 seconds
```

So when run `mkdocs serve`, where can I get the cache for the static files?

**Comment by ldelaprade** [comment]
Mkdocs probably serve result from some memory cache. It does not dump compile result into 'site' directory.
I have 2 commands window open on my doc project:

Command prompt 1:
Current path at project root location, e.g. C:\myMkDocsProject
From there, you can run **'mkdocs build'**

Command prompt 2:
Current path at project site location, e.g. C:\myMkDocsProject\site
From there, you can run **'python -m http.server'**

You can then manually decide when to recompile.
In most case there's no need to restart python http server

**Comment by waylan** [comment]
`mkdocs serve` is intended for development only, not production. We do not support this use and strongly encourage you to use a production ready server instead.
