### ISSUE TITLE
livereload fails when mkdocs serve proxied under sub-path

### ISSUE THREAD

**Issue by themightychris** [mkdocs/mkdocs#2124]
I'm trying to provide a containerized development environment, where an HTTP proxy exposes a suite of services across various paths under a single HTTP port. For example, frontend is hosted at `/`, backend is hosted at `/api`, mkdocs is hosted at `/docs` -- all in live-reload configurations

MkDocs works almost entirely proxied under `/docs`, accept for this injected code (spacing added by me):

```html
<script type="text/javascript">
(function(){
  var s=document.createElement("script");
  var port=(window.location.port || (window.location.protocol == 'https:' ? 443: 80));
  s.src="//"+window.location.hostname+":"+port+ "/livereload.js?port=" + port;document.head.appendChild(s);
})();
</script>
```

All other static assets have relative prefixes generated:

```html
<link rel="stylesheet" href="../../assets/stylesheets/palette.a46bcfb3.min.css">
```

I haven't had any luck finding where in the mkdocs source that absolute path gets output, is it buried somewhere impossible to change in an external dependency?

**Comment by themightychris** [comment]
For anyone else trying to do this, here's a workaround that works (I'm templating a Caddyfile with Chef Habitat):

```handlebars
{{#with bind.docs.first}}
proxy /docs/ {{ sys.ip }}:{{ cfg.port }} {
    transparent
    without /docs/
}

rewrite /livereload.js /docs/livereload.js
proxy /livereload {{ sys.ip }}:{{ cfg.port }} {
    websocket
}
{{/with}}
```

**Comment by waylan** [comment]
Note that the included server is intended for use in development on the local machine only. We do not support any other use case and strongly suggest that you use a third party server which explicitly supports this sort of environment.

**Comment by themightychris** [comment]
@waylan thanks for the response! But I understand that

My use-case is an easy-to-use local development environment for beginners. Setting it up so that they only have to forward and open a single HTTP port which then contains a menu of all the available local services/endpoints help provide a way smoother experience for people that are just trying to run the app and edit some docs without learning Docker inside and out. It works really well and has been very effective at cutting down the time/headaches for new devs to get productive

The live-reload server is exactly what we want here, because it's for editors making changes locally to see their work live, this is not a production/deployment use case. The fix on mkdocs' end seems like it should be fairly simple

**Comment by waylan** [comment]
@themightychris I'm not sure I understand what your workaround is doing, but we only provide a very light wrapper around [lepture/python-livereload][1]. I suspect the issue is with that lib, not mkdocs. In fact, I suggest trying to use python-livereload directly and see if the issue persists. If so, please report the issue upstream.

[1]: https://github.com/lepture/python-livereload

**Comment by themightychris** [comment]
@waylan my workaround is making it so that the page loading `/livereload.js` works when the correct route is `/docs/livereload.js`

A fix would be to get the same logic that generates the `../../assets` path into there

I'm not a python developer so it's hard for me to parse what's going on in the deps. Is there any way for mkdocs to pass its calculated path prefix into the livereload lib to adjust the rendering of the `<script>` tag?

**Comment by waylan** [comment]
> @waylan my workaround is making it so that the page loading `/livereload.js` works when the correct route is `/docs/livereload.js`

The first problem is that the code which loads `livereload.js` is injected in the pages by the livereload server. That is solely the responsibility of the upstream library and outside our control. But, even if we overrode it and provided our own integrated solution, we would still have a problem as described below.

> A fix would be to get the same logic that generates the `../../assets` path into there

The logic for that is attached to the the [`site_url`][1] option. If the MkDocs root is at a subdir of your server, then the `site_url` should point at that subdir (`https://example.com/docs/`). When a subdir is detected in the `site_url` option, we adjust accordingly when generating links.

However, the dev server overrides the `site_url` setting with the `dev_addr` setting, and that does not include a subdir. Therefore, you loose that functionality when using the server. The server always assumes that MkDocs root is the same as the server root. If you are serving MkDocs on anything other than the server root, you cannot use MkDocs dev server, but need to provide your own separate server.

Additionally, I will reiterate, we do not support proxying of any kind. If you proxy  our server, you do so at your own risk. You are solely reasonable to debug and maintain a working solution. We cannot assist you with that. If you are "not a python developer" then I would suggest either using our server directly (not behind any other tools) or not using our server at all. 

[1]: https://www.mkdocs.org/user-guide/configuration/#site_url

**Comment by themightychris** [comment]
@waylan that's fair, was hoping it might be an easy fix, thanks for taking a look!

The proxy-level workaround isn't too tough and works well enough, hopefully any future travelers will find this thread
