### ISSUE TITLE
Dedicated search results page

### ISSUE THREAD

**Issue by paulmelis** [mkdocs/mkdocs#2126]
Hi, loving mkdocs so far in the brief period of using it! Having used RTD sites a lot I was wondering how difficult it would be to turn the live search results into a dedicated page, e.g. after pressing enter in the search box? 

The rationale for this is that you quite often don't find the right search result immediately and need to check out a number of page hits from the research results. Although it's possible to keep the current search result dialog open and right-click on a hit to inspect it this is a bit suboptimal. From a user's perspective it's quite natural when doing search to type the query and press enter to get the results, while with mkdocs you need to "learn" not to press enter and keep the dialog open. Actually, pressing enter in the search box does not really work intuitively, as it sometimes takes you to a page and sometimes doesn't? Hmm, while with the mkdocs-material theme it never seems to react to enter, so I guess it's theme dependent behaviour?

The other reason is that the search results are currently not a regular web page but a floating dialog which has slightly different behaviour than a regular page (e.g. uses a restricted region of space, can't be easily reopened after accidentally closing the tab, etc).

Ironically, while trying some queries on https://docs.readthedocs.io/en/stable/ to make a good comparison in writing this issue it seems RTD is now also using a pop-up live search dialog. I guess that's a nice way to narrow down your query interactively, but it luckily stills allows retrieval of a page of search hits when pressing enter.

Anyways, was just wondering what would be involved to have a press-enter-to-get-results-page?

**Comment by waylan** [comment]
While the `mkdocs` theme uses a modal for search results, the `readthedocs` theme uses an actual dedicated page. This is configurable via the `include_search_page` option of theme configs. Of course, this is set by the theme (not the user) as the theme also needs to provide a template for the search page.

**Comment by pawamoy** [comment]
Such a feature needs to be supported by themes. It's by the way already supported with the ReadTheDocs theme. We'll close this as out of scope for the default `mkdocs` theme (there's work in progress for a new default theme, tagging @tomchristie for consideration).
