### ISSUE TITLE
Enforce Space after Hash(es) for Atx-style Headers

### ISSUE THREAD

**Issue by flywire** [mkdocs/mkdocs#2127]
The following lines are both rendered as headers but the second one does not meet [Atx-style](https://daringfireball.net/projects/markdown/syntax#header).
~~~
# Heading

#text
~~~
Many existing headers are probably formatted without space so suggest an option to disable header rendering if no space after hash.

**Comment by waylan** [comment]
This is a markdown parsing issue, The parsing of Markdown is handled by the [Python-Markdown][1] project. Any issues should be reported there.

[1] https://github.com/Python-Markdown/markdown
