### ISSUE TITLE
Search engine not working well with French character accents

### ISSUE THREAD

**Issue by sundowndev** [mkdocs/mkdocs#2128]
### Expected behavior

Search with `é` to return results.

### Actual behavior

![image](https://user-images.githubusercontent.com/16480203/84799024-f331ca00-affb-11ea-81bd-cd8ec8a38c6d.png)

![image](https://user-images.githubusercontent.com/16480203/84799081-06449a00-affc-11ea-8364-4190c2657167.png)

However I get some results with `modèle`.

### Package versions

* Python: `python --version` 3.6.9
* MkDocs: `mkdocs --version` 1.1.2
* Material: `pip show mkdocs-material | grep -E ^Version` 5.3.0

### Project configuration

``` yaml
plugins:
  - search
  - minify:
      minify_html: true
```

### System information

* OS: Linux Ubuntu x86_64
* Browser: Mozilla Firefox 77.0.1 (64-bit)

**Comment by squidfunk** [comment]
The solution to the problem you're mentioning is known as [Transliteration](http://userguide.icu-project.org/transforms/general) and is not supported by lunr.js. It's, however, possible to achieve this with custom pipeline functions, transforming everything prior to indexing and search. This could be implemented as a custom pipeline function, but will not work with prebuilt indexes.
