### ISSUE TITLE
Use markdown in 404 page

### ISSUE THREAD

**Issue by pxeger** [mkdocs/mkdocs#2132]
Is it possible to use custom markdown for your theme's 404 page? I would like it to act like any other page, except for the fact that it is what appears when you go to a non-existent page. At the moment I have to override it in my theme, which means I have to write it in HTML.

**Comment by waylan** [comment]
No, this is not supported.

**Comment by pxeger** [comment]
So can it be?

**Comment by waylan** [comment]
Error pages are simply [static templates][1] with some extra special treatment (so that links work from any location). None of them get Markdown content and there are no plans to change that. In other words, we have no plans to implement your request.
