### ISSUE TITLE
Awesomepage x Search, or expose search indexing criteria as a plugin option

### ISSUE THREAD

**Issue by dgomesbr** [mkdocs/mkdocs#2133]
Hello, 

I'm the creator of http://awesome-aws-workshops.com/, which is an awesome page like catalog of AWS Workshops. The contents are pretty straightforward, a TOC, lot's of H2, and within each H2, I have lists of links.

The problem with that is that searching for an specific item will likely redirect the result to the same page to the H2 anchor. where I would love to be able to:

1. Expose the search indexing criteria, in my case `h2, h2 > ul > li`
2. Add a `css` or `data-search-result` attribute to the element(s) found
3. Create custom behavior for #2, in my case could be simply highlighting the element

Would that be possible? Is there a way to monkey patch search to do that if this don't go forward?

**Comment by dgomesbr** [comment]
Oh... any explanation?

**Comment by waylan** [comment]
Sorry, I went through a lot if tickets yesterday. Guess I missed adding a comment here.

This is a theme related issue with a third party theme. You need to address this issue with the theme, which it appears you have done. There is no action for us to take so the issue was closed.
