### ISSUE TITLE
Add 'nav' to on_env() event

### ISSUE THREAD

**Issue by timvink** [mkdocs/mkdocs#2141]
For one of my plugins ([mkdocs-enumerate-headings-plugin](https://github.com/timvink/mkdocs-enumerate-headings-plugin)) I need to know the order of pages as they occur in the navigation. For that, I need access to the `nav` after all other plugins have finished altering it in the `on_nav()` event.

I did achieved this using `on_config()` to alter the order of execution of plugins in `on_nav()` ([implementation](https://github.com/timvink/mkdocs-enumerate-headings-plugin/blob/master/mkdocs_enumerate_headings_plugin/plugin.py#L31)), but it feels hacky, and it might break if other plugins apply the same trick.

I'd much prefer to have access to `nav` in the `on_env()` plugin event (or even `on_post_page()` which is the event I'm actually using). Basically adding `nav = nav` here:

https://github.com/mkdocs/mkdocs/blob/ff0b7260564e65b6547fd41753ec971e4237823b/mkdocs/commands/build.py#L274-L276

Alternatively, a reference to the `nav` instance could be added to `config` (`config["nav"] = nav` above the `on_env` event)

I tried searching for similar issues but didn't manage to find a relevant discussion. Would this addition fit with the mkdocs design? If so, I'd be happy to work on a PR (with a little bit of guidance).

**Comment by oprypin** [comment]
On your plugin object, in `on_nav`, you can save `self._nav = nav`, and later access it as `self._nav` in `on_env`.

See also: [Diagram of control flow from a plugin's point of view](https://github.com/mkdocs/mkdocs/discussions/2386)

Basically each event seems to be receiving only the items "relevant" to it. As the design decision is not so clear-cut, and we're looking at a partly breaking change here, *and* there's an easy and completely fine substitute for it, I think this will not happen.
