### ISSUE TITLE
Add chat bots.

### ISSUE THREAD

**Issue by Amber1990Zhang** [mkdocs/mkdocs#2148]
I use the material theme.
### Description
I want to add a chat button for my doc site so that people can ask questions and get response more quickly. I want to use [Comm100](https://www.comm100.com/). I need somewhere to add the following code:

```html
<!--Begin Comm100 Live Chat Code-->
<div id="comm100-button-f87c9787-cf25-4f2b-b92a-b14da3805db6"></div>
<script type="text/javascript">
  var Comm100API=Comm100API||{};(function(t){function e(e){var a=document.createElement("script"),c=document.getElementsByTagName("script")[0];a.type="text/javascript",a.async=!0,a.src=e+t.site_id,c.parentNode.insertBefore(a,c)}t.chat_buttons=t.chat_buttons||[],t.chat_buttons.push({code_plan:"f87c9787-cf25-4f2b-b92a-b14da3805db6",div_id:"comm100-button-f87c9787-cf25-4f2b-b92a-b14da3805db6"}),t.site_id=40000004,t.main_code_plan="f87c9787-cf25-4f2b-b92a-b14da3805db6",e("https://vue.comm100.com/livechat.ashx?siteId="),setTimeout(function(){t.loaded||e("https://standby.comm100vue.com/livechat.ashx?siteId=")},5e3)})(Comm100API||{})
</script>
<!--End Comm100 Live Chat Code-->
```

**Does mkdocs support adding page elements and custom events?**

**Comment by martinbira** [comment]
This is not the correct place for Material related questions. The answer however lies in the following extension: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/

**Comment by Amber1990Zhang** [comment]
> This is not the correct place for Material related questions. The answer however lies in the following extension: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/

thanks for your reply. Am I supposed to ask a question on StackOverflow?

**Comment by martinbira** [comment]
Well, the Material issue board os a better idea :)

**Comment by facelessuser** [comment]
Yeah, the snippets extension could be used or template overrides depending on where you want the button to appear. This is kind of a custom thing though that you'd have to research some. I'm not sure the maintainers of mkdocs should be expected to offer consultation for custom solutions.

Stackoverflow or general message boards may be a more appropriate place to ask this, but I think from the two suggested solutions here, with minimal research, you should be able to pull off what you need.
