### ISSUE TITLE
how to update links in symlinked content?

### ISSUE THREAD

**Issue by roipoussiere** [mkdocs/mkdocs#2151]
this is my project structure:

```
- mkdocs.yml
- readme.md
- docs
    - index.md
    - install.md
    - img
        - image.png
```

Where `index.md` is a symlink of `readme.md`.

The `readme.md` file includes the image: `![](docs/img/image.png)`, and also a link to the install page: `[install](docs/install.md)`.

But those links are broken because `docs/docs` does not exit.

Is there a way to tell mkdocs to update links in the `index.md` file?

**Comment by waylan** [comment]
> Is there a way to tell mkdocs to update links in the index.md file?

No, there is not. Although, perhaps this could be done with a plugin.
