### ISSUE TITLE
Ordered List With Nested Code Block Not Rendering Properly

### ISSUE THREAD

**Issue by thewarden** [mkdocs/mkdocs#2153]
# Environment

* Arch Linux 5.7.7-arch1-1
* Chromium v83.0.4103.116
* Mozilla Firefox v78.0.2
* Mkdocs v1.1.2 
* Mkdocs theme default
* Mkdocs installed via `# pip install mkdocs`
* Python v3.8.3
* pip v20.1.1

# Issue

Creating an ordered list with a nested code blocks indented results in improperly rendered list. 

# Mkdocs Error

No errors were logged.

# Example Working In Github Issues

1. See what drives are available using "fdisk".
   ```
   fdisk -l
   ```   
   ```
   Disk /dev/sda: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
   Units: sectors of 1 * 512 = 512 bytes
   Sector size (logical/physical): 512 bytes / 512 bytes
   I/O size (minimum/optimal): 512 bytes / 512 bytes
   Disklabel type: dos

   Disk identifier: 0x7a21f024
   Device     Boot  Start       End   Sectors  Size Id Type
   /dev/sda1  *      2048    206847    204800  100M 83 Linux
   /dev/sda2       206848 943925247 943718400  450G 83 Linux
   ```
1. Wipe out the partition table on the drive you wish to install Arch Linux to, in this case "/dev/sda".

   `# dd if=/dev/zero of=/dev/sda bs=1M count=5000`
1. Reread the partition table and check that no partitions exist.
   1. `# hdparm -z /dev/sda`
   1. `# cat /proc/partitions`
   ```
   major minor  #blocks  name

     11        0    1048575 sr0
      8        0  976762584 sda
   ```

# Screenshots

## Source
![mkdocs-source](https://user-images.githubusercontent.com/2030217/87501943-97b82380-c61d-11ea-8442-c1914616d056.png)

## Mkdocs Rendered Results
![mkdocs-rendered](https://user-images.githubusercontent.com/2030217/87501957-9d156e00-c61d-11ea-9c0a-9cb898ca474d.png)

## Example Result In Atom IDE (markdown-preview)
![mkdocs-desired-example](https://user-images.githubusercontent.com/2030217/87501965-a1418b80-c61d-11ea-82d4-143f8f0d76e4.png)

**Comment by thewarden** [comment]
This appears to be an issue relating to python-markdown, https://github.com/Python-Markdown/markdown/issues/53. For whatever reason that maybe I'm not understanding, this issue doesn't appear like it will be resolved.

**Comment by thewarden** [comment]
I just found a workaround by using two indents (8 whitespace characters). Make sure to have a blank line above and below the code block. The other option is by using the extension [superfences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/).

Credit goes to Waylan Limberg @ [MkDocs - Google Groups](https://groups.google.com/forum/#!searchin/mkdocs/fenced$20code$20blocks%7Csort:date/mkdocs/cuKTr9cvhz0/q_5n2pojDAAJ).

**Comment by ftrader** [comment]
I've got a documentation set that seems to be affected by this same issue.
I find that rendering using mkdocs-1.1.1 produces well-formed ordered lists, but with 1.1.2 this problem showed up.

**Comment by waylan** [comment]
Please report any Markdown rendering issues upstream to [Python-Markdown](https://github.com/Python-Markdown/markdown/).

**Comment by PegasisForever** [comment]
Workaround:
Add following to mkdocs.yml
```yml
markdown_extensions:
  - pymdownx.superfences
```
