### ISSUE TITLE
Add Option to Set "Deploy From" Branch

### ISSUE THREAD

**Issue by reskin89** [mkdocs/mkdocs#2159]
Currently, mkdocs will always look at `master` branch to find build revisions on deploy.

An option such as `build-from-branch` or `deploy-from` should be added for those that are moving away from the `master` model as far as default branch naming is concerned, or simply if they do not use `master` as their main default branch.

**Comment by waylan** [comment]
I'm confused by this request. MkDocs always works on the working copy. If you want to use a different branch, just check out that branch. MkDocs has no internal reference to `master` or any other branch; with one exception, the [remote_branch][1] config option defines the branch to commit to when using `gh-deploy` and it is set to GitHub's default: `gh-pages`.

**Comment by oprypin** [comment]
I second that; MkDocs doesn't read from any particular branch but rather from currently checked out files, regardless of their origin. So there can't be such an issue. I think this should be closed unless the reporter provides clarification.

**Comment by reskin89** [comment]
I can't believe I forgot to update here. Definitely close this, this arose out of confusion of something operating off of a cache for deployment
