### ISSUE TITLE
The google_analytics config doesn't work

### ISSUE THREAD

**Issue by jeoygin** [mkdocs/mkdocs#216]
I try to use google analytics and I add a config in mkdocs.yml:

```
google_analytics: ['UA-xxxxxxxx-x', 'hostname']
```

However, it seems not work. So I find the config in source code and there are two places [config.py](https://github.com/tomchristie/mkdocs/blob/master/mkdocs/config.py#L25) and [build.py](https://github.com/tomchristie/mkdocs/blob/master/mkdocs/build.py#L134) setting google analytics. Obviously, they use the key 'google-analytics' instead of 'google_analytics'. Therefore the theme can't find config google_analytics.

**Comment by virtualdvid** [comment]
I setup google analytics as you show in your documentation:

`google_analytics: ['UA-xxxxxxxx-x', 'hostname']`

Then I used `mkdocs gh-deploy` to deploy the website but google analytics is not tracking the site. To solve this I went to the `index.html` and deleted:

```
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-xxxxxxxxx-x', 'hostname');
      ga('send', 'pageview');
  </script>
```

then I used the code that GA provides as the first item into the <HEAD>:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxxxxxxxxx-x"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-xxxxxxxxx-x');
</script>
```

It is working now, How can I avoid to replace these lines when I use `mkdocs gh-deploy`?

Thanks!
