### ISSUE TITLE
I've an issue using git hub pages.  The root sub folders are not visible

### ISSUE THREAD

**Issue by joaomarcos-dev** [mkdocs/mkdocs#2161]
Although the files index.html is reachable at https://username.github.io/reponame/, I can't access the sub folders like root/css-folder. I get a 404. The same for every source that is not in the root folder.

https://joaomarcos-dev.github.io/decade/

**Comment by facelessuser** [comment]
Most likely there is something in your environment or configuration that is wrong. Since you've posted neither, it is difficult to give any kind of direction except to say, you probably did something wrong 🙁 .

**Comment by joaomarcos-dev** [comment]
Thanks for the contribution @facelessuser. I am very new in git, git hub and git hub pages. I have searched for this error, but i could not find something that matched my case. There is no typo in the html tags. Accessing https://joaomarcos-dev.github.io/decade/ give me just the HTML and if I try https://joaomarcos-dev.github.io/decade/_src (where is the css files), it returns a 404. even though this _src folder is in the 'decade' repository. Some suggestion? I will try removing the repo end setting it all again. As you said, maybe a wrong configuration. I'll give a return.

**Comment by facelessuser** [comment]
I guess what I'm suggesting is that people can't help debug your problem unless you provide them with some kind of source to debug.

So, based on the site name you linked us to, I assume this is your project: https://github.com/joaomarcos-dev/decade. This is where we should have been linked at the start. That way we don't have to guess what your setup is.

With that out of the way, it appears you aren't even using MkDocs as I see no MkDocs configuration. As you were creating this issue on MkDocs, I was assumed you were having a MkDocs issue, but it appears you are asking a general HTML question.

This issue tracker is for MkDocs bugs, not general HTML questions. Those kinds of questions are better suited for sites like [Stackoverflow](https://stackoverflow.com/).

**Comment by joaomarcos-dev** [comment]
Oh, I'm so sorry for making you waste time. I didn't see that. I just clicked the green "new issue" button. I was thinking that this page was for all git hub related problems. I just begin learning and using git and git hub today. Sorry. Tks for trying to help.
