### ISSUE TITLE
does not parse titles from === style headings 

### ISSUE THREAD

**Issue by m-fonseca** [mkdocs/mkdocs#2162]
If a markdown file has a title like
```
This is a test
==============
```

instead of a title like
```
# This is a test
```
mkdocs fails to parse the title and uses 'Index'  for the auto generated link in the nav bar.

Thanks!

**Comment by waylan** [comment]
This behavior is exactly as [documented](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data).
