### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by pfuntner** [mkdocs/mkdocs#2163]
My team uses mkdocs to publish github markdown documents to a web site.  I made some changes to a document, they look great in github, but apparently mkdocs was confused and they don't look as expected on the website.

### Github view
<img width="690" alt="github view" src="https://user-images.githubusercontent.com/23261559/89059546-646cd880-d32f-11ea-99dd-18c295f3f090.png">

### Raw markdown source
<img width="946" alt="raw markdown" src="https://user-images.githubusercontent.com/23261559/89059688-a269fc80-d32f-11ea-987f-9b611ee54a11.png">

All the whitespace are blanks, not tabs.

### Apperance on website
<img width="609" alt="website view" src="https://user-images.githubusercontent.com/23261559/89059736-b9105380-d32f-11ea-975e-b4032d5c5be1.png">

## My issues with the behavior
1. The performatted monospaced section should be on two separate lines
2. The last two bullets are supposed to be sub-bullets - indented and starting from 1

**Comment by thewarden** [comment]
This is the same issue I was brought up in issue #2153. It seems to be a python-markdown issue that unfortunately doesn't seem like it will be resolved, https://github.com/Python-Markdown/markdown/issues/53.

**Comment by thewarden** [comment]
I just found a workaround by using two indents (8 whitespace characters). Make sure to have a blank line above and below the code block. The other option is by using the extension [superfences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/).

Credit goes to Waylan Limberg @ [MkDocs - Google Groups](https://groups.google.com/forum/#!searchin/mkdocs/fenced$20code$20blocks%7Csort:date/mkdocs/cuKTr9cvhz0/q_5n2pojDAAJ).

**Comment by mulderij** [comment]
Issue #2153 is about the second issue @pfuntner reports.
The first issue could be fixed (but probably is a work around) by overriding the css-code in theme.css for 'code, .rst-content tt,.rst-content code' by placing new css-code in theme_extra.css:
```css
code, .rst-content tt,.rst-content code {
  white-space:pre-wrap;
}
```
The code in theme.css causes the style to be `white-space: nowrap;`

**Comment by waylan** [comment]
Closing this as an upstream issue.
