### ISSUE TITLE
Allow config file with dot prefix: .mkdocs.yml

### ISSUE THREAD

**Issue by hugovk** [mkdocs/mkdocs#2164]
Many tools use period prefixes to hide their config files. For example, looking at this repo and another:

- `.appveyor.yml`
- `.codecov.yml`
- `.coveragerc`
- `.csslintrc`
- `.editorconfig`
- `.git`
- `.gitattributes`
- `.github`
- `.gitignore`
- `.idea`
- `.jshintignore`
- `.markdownlintrc`
- `.pre-commit-config.yaml`
- `.pytest_cache`
- `.readthedocs.yml`
- `.testmondata`
- `.tox`
- `.travis.yml`

Some of these, like [`appveyor`](https://www.appveyor.com/docs/build-configuration/#yaml-file-alternative-naming), [`codecov`](https://docs.codecov.io/docs/codecov-yaml#can-i-name-the-file-codecovyml) and [`readthedocs`](https://docs.readthedocs.io/en/stable/config-file/v2.html#configuration-file-v2), also allow prefixing the name with a dot or not.

It would be good if MKDocs would also allow `.mkdocs.yml`, so the config file can also be hidden along with other dotfiles.

Thank you!

**Comment by oprypin** [comment]
Seems like this request didn't get any other votes for it.

Even though this change opens a super easy way to implement this...
https://github.com/mkdocs/mkdocs/pull/2478/files#diff-4031d3aab66d0273fc07b42960722740d13c0e33b10d8b76dc1da9f2097e91c0R159 
... I'm still inclined to reject this request in the name of uniformity.

Note that you can specify the config file name manually via a command line flag. Or put it into a subdirectory.

The rejection is not final, further comments are welcome

**Comment by hugovk** [comment]
Thanks, I'll check the config flag. 

This suggestion was made in the name of uniformity, so the mkdocs config file doesn't stick out in a repo, compared with all the dotty ones above. 

And some popular ones allow both. IIRC, at least some started with only no-dot and later added a dot version for uniformity with other tools. 

> Some of these, like [`appveyor`](https://www.appveyor.com/docs/build-configuration/#yaml-file-alternative-naming), [`codecov`](https://docs.codecov.io/docs/codecov-yaml#can-i-name-the-file-codecovyml) and [`readthedocs`](https://docs.readthedocs.io/en/stable/config-file/v2.html#configuration-file-v2), also allow prefixing the name with a dot or not.

Thanks again! Not a huge problem if you choose not to implement this, and thanks for maintaining MKDocs!
