### ISSUE TITLE
if there is both index.md and README.md copy the README.md as is

### ISSUE THREAD

**Issue by aoloe** [mkdocs/mkdocs#2166]
I understand that when `index.md` is present, than it's preferred to the `README.md` file.

That's fine to me.

But if I have a `README.md` it's because I want it to be there!

Why?

I'm committing the HTML files to a Github repository and let a webhook deploy it to my site.
And I would love to have a friendly README.md in the repository, for those who stumble on it... (and for myself too...)

**Comment by gaborantal** [comment]
And what is the problem with that? My repository has a README.md and is not linked in `mkdocs.yml`, and it works fine.

**Comment by aoloe** [comment]
@gaborantal is your README.md copied in the output?

in my case it's just ignored... how can i get it to be copied?

**Comment by gaborantal** [comment]
Sorry if I'm missing some details, but what is the thing exactly you want to do/expect?

**Comment by martinbira** [comment]
That is the correct behaviour.

**Version 1.0.1 (2018-08-13)**
Bugfix: Exclude README.md if index.md is present (#1580).

**Version 1.0 (2018-08-03)**
A README.md file is now treated as an index file within a directory and will be rendered to index.html (#608).

**Comment by aoloe** [comment]
@martinbira , yes, i understand that this is the way mkdocs currently works.

i'm asking not to exclude README.md when index.md is present, but to copy it over as is. at least optionally.
this is useful when somebody pushes the static files to a remote git repository (for further deployment; like <https://gitlab.com/impagina/scribus-scripter-api-with-mkdocs>)

**Comment by waylan** [comment]
The assumption is that when both files are present, the README file is there for users to see when browsing the source files, not the built site. Therefore, there is no need to include the file in the built site.

**Comment by aoloe** [comment]
yes, but this is a "wrong" assumption!

i have three steps, when uploading my files to the production server:

- locally produce the site.
- commit the changes to git and push the to a service with webhooks.
- get the live site synchronized with the hml repository.

the "site" repository also deserves a readme file.

on top of it, i'd love to have the readme on the production site, if somebody (even my future self) stumbles on the production server and wonders how the site is being managed / has been generated.

i like to have a readme in every directory i create. and i don't think this is a bad habit.

i don't see how somebody would have both the index.md and README.md, if this is not exactly what the person wants, but i rest my case.
and will keeping on manually copying my README.md...

**Comment by waylan** [comment]
> and will keeping on manually copying my README.md

Then this sounds like a great feature for a third party plugin to implement.

**Comment by aoloe** [comment]
/me loves good default behaviors... as much as i like the idea of plugins, i'm too old for tracking obsolete third party plugins... sorry.
