### ISSUE TITLE
Icons having large size

### ISSUE THREAD

**Issue by SkuzzyxD** [mkdocs/mkdocs#2169]
Hey,
I made a documentation using mkdocs and deployed it on readthedocs.org
The issue with site is that the icons are getting extra large on mobile devices, but are normal on desktop.

![Screenshot_20200820-181031758](https://user-images.githubusercontent.com/23524935/90771457-eccc1100-e310-11ea-8766-eebf65c23078.png)

This is how it looks

**Comment by waylan** [comment]
We can;t be responsible for content provided by the user. You may need to define some custom CSS  (using [extra_css][1]) which addresses your specific content.

[1]: https://www.mkdocs.org/user-guide/configuration/#extra_css
