### ISSUE TITLE
Create google group for discussions.

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#217]
Also link to this and the IRC channel in both README and the front page of the docs.

**Comment by tomchristie** [comment]
Created: https://groups.google.com/forum/#!forum/mkdocs

Still need to...

- [ ] Add @d0ugal as an admin.
- [ ] Link to this from the documentation.

**Comment by d0ugal** [comment]
@tomchristie I'm doing a small refresh of the README, so I'll include this and I'll pop it in the docs too.

**Comment by tomchristie** [comment]
Sure thing. Ping me if/when I need to do the admin thing.

**Comment by d0ugal** [comment]
Ta, I think I'll also grab a Twitter account too since it doesn't look like we will get @mkdocs.

**Comment by d0ugal** [comment]
and we got our first email! That was fast, I only added it to the README so far.

**Comment by d0ugal** [comment]
Created https://twitter.com/mkdocsproject

**Comment by Mopster** [comment]
The group is currently not visible for non-members, by choice ? :-)

**Comment by d0ugal** [comment]
I suspect it was accidental - @tomchristie could you update it and/or add me as an admin?

**Comment by tomchristie** [comment]
@d0ugal - I've added you as an owner.

**Comment by d0ugal** [comment]
@tomchristie Thanks, did you see @tomchristie #405 - need your help there I think.
