### ISSUE TITLE
Webstorm autosave causes errors with mkdocs serve

### ISSUE THREAD

**Issue by OliverNChalk** [mkdocs/mkdocs#2175]
I've found an interesting issue where the autosaving on Webstorm2020.2 results in `mkdocs serve` not being able to locate the file. I am then able to fix this by opening the file in `vim` and then saving it again. What's also interesting, is that if I issue a manual save (Ctrl + S) from within Webstorm, then `mkdocs serve` is able to reload the file just fine (sometimes, it actually seems a bit inconsistent). I'll send this issue to the team at Webstorm but thought I'd post it here in case someone else could try to replicate the issue.

This is the console output of first autosave running and then myself manually saving the file via vim:
```
[I 200830 12:31:11 watcher:103] Running task: builder (delay: None)
INFO    -  Running task: builder (delay: None)
INFO    -  Building documentation... 
ERROR   -  Exception in callback BaseAsyncIOLoop._handle_events(3, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(3, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/oliver/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 139, in _handle_events
    handler_func(fileobj, events)
  File "/usr/lib/python3/dist-packages/pyinotify.py", line 1560, in handle_read
    self.process_events()
  File "/usr/lib/python3/dist-packages/pyinotify.py", line 1275, in process_events
    self._default_proc_fun(revent)
  File "/usr/lib/python3/dist-packages/livereload/watcher.py", line 215, in inotify_event
    self.callback()
  File "/usr/lib/python3/dist-packages/livereload/handlers.py", line 69, in poll_tasks
    filepath, delay = cls.watcher.examine()
  File "/usr/lib/python3/dist-packages/livereload/watcher.py", line 105, in examine
    func()
  File "/home/oliver/.local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/oliver/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 282, in build
    files.copy_static_files(dirty=dirty)
  File "/home/oliver/.local/lib/python3.8/site-packages/mkdocs/structure/files.py", line 42, in copy_static_files
    file.copy_file(dirty)
  File "/home/oliver/.local/lib/python3.8/site-packages/mkdocs/structure/files.py", line 177, in copy_file
    utils.copy_file(self.abs_src_path, self.abs_dest_path)
  File "/home/oliver/.local/lib/python3.8/site-packages/mkdocs/utils/__init__.py", line 139, in copy_file
    shutil.copyfile(source_path, output_path)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/oliver/proxima/aqueduct/Docs/index.md~'
[I 200830 12:31:30 watcher:103] Running task: builder (delay: None)
INFO    -  Running task: builder (delay: None)
INFO    -  Building documentation... 
[I 200830 12:31:30 handlers:92] Reload 1 waiters: /home/oliver/proxima/aqueduct/Docs/index.md
INFO    -  Reload 1 waiters: /home/oliver/proxima/aqueduct/Docs/index.md
[I 200830 12:31:30 handlers:135] Browser Connected: http://127.0.0.1:8000/
INFO    -  Browser Connected: http://127.0.0.1:8000/
```

Details:
```
OS: Ubuntu 20.04 1
Python: 3.8
MKDocs: 1.1.2
Webstorm: 2020.2
```

**Comment by waylan** [comment]
MkDocs only provides a light wrapper around [python-livereload][1]. Does this same issue exist when using python-livereload directly? If so, then this should be reported upstream.

[1]: https://github.com/lepture/python-livereload

**Comment by ktomk** [comment]
This might be related to the fact that Webstorm (or any other Idea IDE) autosave is creating a backup file first which is likely immediately removed after a successful save to form one transaction:

~~~
...
FileNotFoundError: [Errno 2] No such file or directory: '/home/oliver/proxima/aqueduct/Docs/index.md~'
                                                                                                    ^
                                                                                                    |
                                                           tilde ("~") added to standard filename --'
~~~

I'm also an Mkdocs and Phpstorm user and were now unable to reproduce this. Checked different autosave configurations and also with and without the _"Backup files before saving"_ option. No more tilde-suffixed files appear in the output.

@OliverNChalk if you would be so kind to verify this is still an issue on your end, that would be great for clarification.

(comment against mkdocs 1.1.2 and PhpStorm 2021.1.3 Preview - Build #PS-211.7442.14, built on May 20, 2021)

**Comment by OliverNChalk** [comment]
I no longer use the WebStorm IDE, so it wouldn't be that easy for me to verify. If you think it important I do I'm okay to re-install and have a poke around, otherwise I'm happy to mark this issue closed

**Comment by ktomk** [comment]
If you're happy I'm also happy to mark this issue closed.
