### ISSUE TITLE
Missing file in sitemap

### ISSUE THREAD

**Issue by vbd** [mkdocs/mkdocs#2177]
I link to a markdown file from `index.md` with `[test](test.md)`.
`test.md` is not listed in `mkdocs.yml` but exists in the `docs` folder.

Running `mkdocs build` and deploying it to my webserver, results in:
- Content of `test.md` is rendered as `test.html` and included in search results. That's ok!
- But `test.html` can't be found in `sitemap.xml` / `sitemap.xml.gz`

Any ideas? Thanks in advance.

**Comment by waylan** [comment]
This is the intended behavior. `sitemap.xml` replicates the site navigation. Therefore, any files not in the navigation defined in `mkdocs.yml` are no listed in `sitemap.xml`. 

That said, support for these "hidden" files was only recently added. When `sitemap.xml` was designed, all files were always listed in the nav. Perhaps we need to rethink `sitemap.xml`.
