### ISSUE TITLE
Debug local version of plugin

### ISSUE THREAD

**Issue by londonbreed** [mkdocs/mkdocs#2181]
I'm developing a plugin for mkdocs. I have all my code in a workspace in PyCharm. I can install the plugin then run it, but I'm debugging / editing the installed version. How can I get mkdocs to use my local copy, not the one that's installed?

**Comment by timvink** [comment]
Use `pip install -e .`

For more details, have a look at the contributing guidelines of existing plugins. Here's one of mine for example: https://timvink.github.io/mkdocs-git-authors-plugin/contributing.html
