### ISSUE TITLE
Hope the readthedocs theme supports gruvbox-dark and can highlight the code

### ISSUE THREAD

**Issue by heguohui2018** [mkdocs/mkdocs#2182]
Hope the readthedocs theme supports gruvbox-dark and can highlight the code

<img width="1070" alt="截屏2020-09-05 18 05 28" src="https://user-images.githubusercontent.com/35359288/92302876-73841d80-efa2-11ea-9526-0656984ee49d.png">

**Comment by waylan** [comment]
Syntax highlighting is provided by [highlight.js][1] in the builtin themes. Therefore, we offer whatever highlight.js offers. Please make any requests to that project for additional themes to syntax highlighting.

[1]: https://github.com/highlightjs/highlight.js
