### ISSUE TITLE
Accept only port number in `mkdocs serve -a` ?

### ISSUE THREAD

**Issue by fralau** [mkdocs/mkdocs#2183]
When using `mkdocs serve -a`, most of the time it is implicit we mean `localhost`.

Right now the format required is:

```
  -a, --dev-addr <IP:PORT>        IP address and port to serve documentation
                                  locally (default: localhost:8000)
```

(from help)

So most of the time we would type, e.g.

```sh
mkdocs serve -a localhost:8001
```

Only for a question of practicality, why not accepting a simple port number, e.g.

```sh
mkdocs serve -a 8001
```

It may seem a detail, but that little change could streamline things?

**Comment by SGA-Naoki-Matsumura** [comment]
It is very great issue.
Inside the docker container with binding localhost:8000, I cannot connect to mkdocs from the outside.
I use a workaround "mkdocs serve -a `hostname -i`:8000". 

I hope that I can specify only the port number.

**Comment by fralau** [comment]
h binding localhost:8000, I cannot connect to mkdocs from the outside.
> I use a workaround below:
> 
> ```
> mkdocs serve -a `hostname -i`:8000
> ```

@SGA-Naoki-Matsumura  Simple, but clever trick. 

I wrote my own utility: it looks up the port number in a `config.yaml` file. Or, if the info is not there, it tries all ports >=8000 until it finds a free one.

**Comment by waylan** [comment]
FYI, you can configure this with the [dev_addr][1] config setting. If you need the same non-default address/port every time. just set `dev_addr` in your config file. Then you don't need to specify other IP or port on the command line. The command line option is for those one-off unique situations where the little bit of extra typing isn't going to hurt anyone.

[1]: https://www.mkdocs.org/user-guide/configuration/#dev_addr

**Comment by fralau** [comment]
@waylan Thanks:  I wasn't aware of the the `dev_addr` config setting! It's cool.

I think my request to assume `localhost` by default in `mkdocs serve -a` (as a shortand) still has some merit?
