### ISSUE TITLE
mkdocs command not found error 

### ISSUE THREAD

**Issue by JeffGaly** [mkdocs/mkdocs#2184]
Hello Team,

I have installed the python,pip and mkdocs in my machine but I'm getting the below error 
**python version** : 3.7.2
**pip version** : pip 20.2.2 from C:\Users\adevika\AppData\Roaming\Python\Python37\site-packages\pip (python 3.7)
**path set to environment variable are** 
C:\Program Files\Python37\Lib
C:\Users\XXXXXXX\AppData\Roaming\Python\Python37\site-packages
C:\Program Files\Python37\Scripts
C:\Program Files\Python37\Tools\scripts

**Error** 
mkdocs version : 
 bash: mkdocs: command not found.

Any suggestions will be grateful.Thanks!

**Comment by JeffGaly** [comment]
@tomchristie Any suggestions will be grateful .

**Comment by nikita-fuchs** [comment]
Having the same issue.

**Comment by gaborantal** [comment]
This is not reproducable in this way. Do you use virtualenv? Can you show us exact logs of installing, what are in the packages folder and so on?

**Comment by fralau** [comment]
Just to save a few seconds, this is obviously a Windows OS.

**Comment by gaborantal** [comment]
That is obvious. But the other details are not. I tried to reproduce it, however I failed to do that. Mkdocs works just fine. I used Python 3.8 with correctly set PATH. I used a new, empty virtualenv, installed mkdocs and everything works like a charm.

I have an idea that I experienced a long time ago: the pip command may install things for a differenc Python than you are referring as `python`.  After installing mkdocs, please check `python -m pip list` comman whether mkdocs is installed for your Python version or not. And also check your PATH if it contains only one version of python or two, three. They might foul each other.

**Comment by fralau** [comment]
@gaborantal Indeed, "distinct Python environment" is the most plausible explanation for @JeffGaly's and and @nikita-fuchs's questions.

That may be crude, but I'd start with a `pip list | grep mkdocs` to see what's in that Python environment.

**Comment by gaborantal** [comment]
> 
> That may be crude, but I'd start with a `pip list | grep mkdocs` to see what's in that Python environment.

Yup, that might be a good idea, but in the classic Windows cmd, that won't work. It works with PowerShell (I guess) and Git bash.

**Comment by fralau** [comment]
Filters and (a crude version of) grep have been part of MS-DOS since its first versions in the 1980s. Unless Windows has removed them, that should still work?

**Comment by gaborantal** [comment]
I think it's a part of Unix-like OSs. I think the Windows equivalent version is something like `findstr` or similar. (I'm not really using batch for scripting).

**Comment by fralau** [comment]
I launched a VM to check... yep:

```dos
pip list | findstr mkdocs
```

or

```dos
pip list | find "mkdocs"
```
(quotes are apparently needed here)

I guess my memory betrayed me. 🤔

**Comment by nikita-fuchs** [comment]
I'm on windows only because my mac is in repair, sorry for causing this extra effort, but I need this for work now.
```
py -h
Python Launcher for Windows Version 3.7.8150.1013
```

PATH contains:
![image](https://user-images.githubusercontent.com/11761828/92715058-40a0a780-f35d-11ea-9772-02477d66ffe1.png)

After restarting powershell and the whole system, I still can't run `mkdocs`.

**Comment by fralau** [comment]
@nikita-fuchs The problem is presumably not Windows 🙂. It's a just a question of finding the right incantations.

Have you tried this?

```
pip list | findstr mkdocs
```

**Comment by nikita-fuchs** [comment]
Yep, says
```
mkdocs             1.1.2
```

**Comment by gaborantal** [comment]
The problem is that the PATH does not contain the place where the packaged are installed. Can you try `python -m mkdocs`  if it runs?

**Comment by ashton-arinze** [comment]
jkjhjk

> The problem is that the PATH does not contain the place where the packaged are installed. Can you try `python -m mkdocs` if it runs?
> 
> I think you should add the following ones to PATH:
> 
> * C:\Program Files\Python37\Lib\site-packages
> * C:\Program Files\Python37\Lib
> * C:\Program Files\Python37\DLLs

This did not work for me 🤕

**Comment by BoHuang2018** [comment]
I solved it by `pip3 install mkdocs`   The below is my python and pip environment
```
% pip --version      
pip 21.3.1 from /Users/username/Library/Python/3.8/lib/python/site-packages/pip (python 3.8)
% pip3 --version
pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
% python3 --version
Python 3.9.9
```

**Comment by yohanelly95** [comment]
I did the same command ` pip3 install mkdocs` now how do I run it? 

It keeps giving me errors `ERROR: unknown command "mkdocs"` or `zsh: command not found: mkdocs`

**Comment by BoHuang2018** [comment]
@yohanelly95  I experienced the same trouble on my another machine.  The reason was my Goland IDE. I relaunched Goland, and it was solved

**Comment by Waterkin** [comment]
> pip3 install mkdocs

Me too. I just can run mkdocs in the afternoon. Then, in the evening, It keeps giving me error `zsh: command not found: mkdocs`
