### ISSUE TITLE
Files in a directory called templates are ignored

### ISSUE THREAD

**Issue by gmazoyer** [mkdocs/mkdocs#2185]
In a project where the documentation files are located under `docs/`, it seems that files inside a sub-directory called `templates/` (path being `docs/templates/`) are reported as missing when referring to them in the configuration file.

The configuration is like:

```
<redacted>

nav:
  - Introduction: 'index.md'
  - Templating:
    - Writing Templates: 'templates/index.md'
    - Arista EOS: 'templates/arista-eos.md'
    - Cisco IOS-XR: 'templates/cisco-iosxr.md'
    - Juniper JUNOS: 'templates/juniper-junos.md'
    - Peering Request E-mail: 'templates/peering-request-email.md'

<redacted>
```

When trying to `build` or `serve`, the following warning are raised (using `mkdocs >= 1.0`).

```
WARNING -  A relative path to 'templates/index.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'templates/arista-eos.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'templates/cisco-iosxr.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'templates/juniper-junos.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'templates/peering-request-email.md' is included in the 'nav' configuration, which is not found in the documentation files
```

Please note that the `docs/` directory is also at the same level in the file system than another directory called `templates/`. So from a file system perspective it looks like:

```
 docs/
  `---- index.md
  `---- templates/
somedir/
someotherdir/
templates/
```

Is it a normal behavior or is it a corner case?

**Comment by gaborantal** [comment]
I think you use it wrongly. I tried to reproduce your problem, but I failed. Which mkdocs you are using? where is your mkdocs.yml located?

**Comment by respawner** [comment]
`mkdocs.yml` is located in the root directory of the project. I'm using the latest mkdocs version grabbed using pip3.

The weird thing is that it founds and parses all files to compile the documentation properly except the ones under `docs/templates/`.

**Comment by gaborantal** [comment]
Can you please upload a minimal example that reproduces the problem? I've had the same problem when I used an include plugin for Markdown. If the problem is reproduced, I'll try to create a PR for your problem.

**Comment by respawner** [comment]
Here you go a small example to reproduce the issue. I've been using a Markdown plugin but disabling it did not changed anything.

Here is the output when trying to run `mkdocs serve`:
```
~/mkdocs-issue-2185% mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
WARNING -  A relative path to 'templates/example-1.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING -  A relative path to 'templates/example-2.md' is included in the 'nav' configuration, which is not found in the documentation files
INFO    -  Documentation built in 0.06 seconds
[I 200911 12:18:55 server:335] Serving on http://127.0.0.1:8000
INFO    -  Serving on http://127.0.0.1:8000
[I 200911 12:18:55 handlers:62] Start watching changes
INFO    -  Start watching changes
[I 200911 12:18:55 handlers:64] Start detecting changes
INFO    -  Start detecting changes
^C[I 200911 12:18:56 server:358] Shutting down...
INFO    -  Shutting down...
```

[mkdocs-issue-2185.zip](https://github.com/mkdocs/mkdocs/files/5208305/mkdocs-issue-2185.zip)

**Comment by connerxyz** [comment]
Having a similar issue. Is there a solution?

**Comment by lukasgeiter** [comment]
I was looking into the source code out of curiosity...

This is where `templates` is excluded when searching for markdown files: https://github.com/mkdocs/mkdocs/blob/ff0b7260564e65b6547fd41753ec971e4237823b/mkdocs/structure/files.py#L218

And this is where the directory is actually used:
https://github.com/mkdocs/mkdocs/blob/ff0b7260564e65b6547fd41753ec971e4237823b/mkdocs/theme.py#L35

**Comment by connerxyz** [comment]
Considering how to resolve: Can we update the MkDocs config to include a `theme.templates` setting (similar to `static_templates`)? The default can be 'templates' to preserve backward compatibility, while allowing people who want a 'templates' part of their documentation to set it to something else.

**Comment by jordynniara** [comment]
I believe I'm having the same issue:
```` WARNING  -  Template skipped: 'templates/injectNavItems.html' not found in docs_dir.````
My directory looks like this:
````
| docs/
| ---- mdFiles/
| ---- templates/
| ---- index.md
| site/
| theme/
| mkdocs.yml
````

**Comment by Gresliebear** [comment]
When I create custom theme and I need a child template and pass content to that child template its picking up templates from the custom directory is this related?

**Comment by jboivin-done** [comment]
Just for people coming in lately:

The solution is to add an inverted exclusion.

See: https://www.mkdocs.org/user-guide/configuration/#exclude_docs
>So, in order to really start this config fresh, you'd need to specify a negated version of these entries first.
