### ISSUE TITLE
Building docs results in broken navigation

### ISSUE THREAD

**Issue by Discomnis** [mkdocs/mkdocs#2191]
Using:
Windows 10
Python 3.8
MkDocs v1.1.2

yml File is pretty basic:
    site_name: My App Documentation
    nav:
        - Home: index.md
        - 'Build\Deploy': buildDeploy.md
        - 'By Hand': byHand.md
    theme:
        name: readthedocs
        highlightjs: false

When using:
    python -m mkdocs serve

Then opening:  http://localhost:8000
In the browser.

The site works as expected, clicking on Page links takes you to the page.  Sweet.

When running:
    python -m mkdocs build

Then opening:
c:/MkDocs_MyApp/site/index.html
In the browser.

Clicking on page links shows a directory-browser-like view where you have to click on the index.html file within a folder that was generated for each page.

If there is some option during build or some additional config option you have to add, could you make this active/enabled by default?  I have no idea why it works when served but not when built and I can't find anything in the docs that explains this.

Love MkDocs otherwise!  Fantastic work.

**Comment by Discomnis** [comment]
Ok, so in Chrome dev Tools, I noticed an error:
Uncaught DOMException: Failed to construct 'Worker': Script at '(path)/site/search/worker.js' cannot be accessed from origin 'null'.
    at file:///(path)/site/search/main.js:95:22

After poking around on the web I found:
https://stackoverflow.com/a/33432215

So there is a way around this if you add a flag when launching Chrome, however I was hoping to use mkdocs as a lightweight in-place (as in withing my solution folder) way to make pretty docs that I could commit with my project.  If any other devs have to know about the flag and then set it before they can see the docs, I am pretty sure they just won't use the generated docs and will just view the markdown files manually in their preferred markdown editor.

That sort of defeats the purpose of using this tool.   Is there any way to integrate the stackoverflow solution into MkDocs so that Chrome (which most devs in my company use) works out of the box?

**Comment by Discomnis** [comment]
Interesting, adding the flag to chrome when launching gets rid of the error, but the navigation still doesn't work so back to being clueless.

**Comment by Discomnis** [comment]
Ok, so after poking around in the docs I discovered: 
use_directory_urls: false

This makes everything work both when serving the docs and when using the static site from a local browser.

So I think if this flag was made more prominent in the 'getting started' part of the docs, that would be all that the world needs to achieve a zen-like state of light weight pretty docs!

Either way, whether you decide to add to the docs or not, you can close this issue ;-)  Many thanks again for this great tool.

**Comment by ktomk** [comment]
Yes, to serve from the file-system (as well as from a webserver) the interoperable setting is `use_directory_urls: false` as outlined in the docs:

> The default style of `use_directory_urls: true` creates more user friendly URLs, and is usually what you'll want to use.

> The alternate style can occasionally be useful if you want your documentation to remain properly linked when opening pages directly from the file system, because it creates links that point directly to the target file rather than the target directory.

[ref](https://www.mkdocs.org/user-guide/configuration/#use_directory_urls)

When I started with mkdocs I found this visible as I was first skimming the settings, but yes, requires reading. Nevertheless I did use the default first then realizing afterwards (three months or so) that I want to have the `index.html` based URLs so the documentation is easily browse-able from the local file-system (as well). So right now I'm doing a migration: one build that contains both ways with two mkdocs builds and then merging. This does not work out of the box and I'm patching this more or less together with a shell script. Just writing this to share it's useful to decide on the `use_directory_urls` setting and it's consequences before publishing online if it should be one build in the project.

The other problem you might see with the worker/js error is that the search does not work when opening the files directly with your browser. Some browsers block access to scripts in a worker context (related to the `file://` scheme). There is a plugin for [mkdocs called localsearch](https://github.com/wilhelmer/mkdocs-localsearch) which enables search in those environments again with the help of the [squidfunk/iframe-worker javscript library](https://github.com/squidfunk/iframe-worker).

Requires extending the theme a bit but I found it straight forward to work with (I'm using the non-default material theme), find a description with the mkdocs-localsearch plugin.

One edge-case I was not able to fully resolve so far for a file-based mkdocs build is #2189 .

**Comment by waylan** [comment]
MkDocs is not intended to build documentation for browsing from the filesystem. The files need to be behind a server. As you noted some features require the browser's security features to be disabled in order to work without a server. We can't recommend that any one disable their browser's security features, therefore we don't support that sue case.

Of course, it is possible to make it work without disabling security features. You could disable the search plugin and set `use_directory_urls` correctly. But that is an advanced use case and not something we advertise in the getting started section of the docs.
