### ISSUE TITLE
adding-pages curl error

### ISSUE THREAD

**Issue by BlaneG** [mkdocs/mkdocs#2192]
The [Adding Pages](https://www.mkdocs.org/#adding-pages) example includes the following curl request:
```
curl 'https://jaspervdj.be/lorem-markdownum/markdown.txt' > docs/about.md
```

The curl command is not downloading the page as expected:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'https
```

I am using Python 3.8 and curl 7.71.1

**Comment by ktomk** [comment]
Just checked, it seems to work now, maybe a temporary DNS issue? Could you check again @BlaneG from your end?
