### ISSUE TITLE
mkdocs build -s -v no longer breaks on broken links

### ISSUE THREAD

**Issue by spbrogan** [mkdocs/mkdocs#2194]
I used to run mkdocs build -s -v to test my files and make sure all links were valid.  
Today i just realized it isn't working.  I see no error/warning when i include a bad link.  

My pip versions in my python 3.8.2 x64 environment are as follows.

Package                    Version
-------------------------- ---------
atomicwrites               1.4.0
attrs                      20.2.0
click                      7.1.2
colorama                   0.4.3
coverage                   5.3
flake8                     3.8.3
future                     0.18.2
iniconfig                  1.0.1
Jinja2                     2.11.2
joblib                     0.16.0
livereload                 2.6.3
lunr                       0.5.8
Markdown                   3.2.2
MarkupSafe                 1.1.1
mccabe                     0.6.1
mkdocs                     1.1.2
mkdocs-macros-plugin       0.4.15
mkdocs-material            5.5.14
mkdocs-material-extensions 1.0.1
more-itertools             8.5.0
nltk                       3.5
packaging                  20.4
pip                        19.2.3
pluggy                     0.13.1
py                         1.9.0
pycodestyle                2.6.0
pyflakes                   2.2.0
Pygments                   2.7.1
pymdown-extensions         8.0
pyparsing                  2.4.7
pytest                     6.0.2
pytest-cov                 2.10.1
pytest-html                2.1.1
pytest-metadata            1.10.0
python-dateutil            2.8.1
PyYAML                     5.3.1
regex                      2020.7.14
setuptools                 41.2.0
six                        1.15.0
termcolor                  1.1.0
toml                       0.10.1
tornado                    6.0.4
tqdm                       4.49.0

**Comment by ktomk** [comment]
@spbrogan are you able to detect broken links with other utilities despite mkdocs? Could you (were you able to) narrow the version of mkdocs that does not detect broken link for you any longer?

Did mkdocs (with -s -v) show dangling symlink warnings? Just asking out of curiosity.

What helped me in similar situations is to first copy all files recursively and then run the mkdocs build a bit more isolated. The `cp` utility does also warn about dangling symlinks (and also gives great control of handling symbolic links, e.g. for copying or for resolving before copying).

To break a build early, I also find the `find` utility helpful which is able to find broken symbolic links. Just commenting, your mileage may vary.

**Comment by oprypin** [comment]
Please provide more information.
What do the links look like, at the very least? Or, ideally the whole site.
Closing until then.
