### ISSUE TITLE
The sequence number of the ordered list may not be rendered correctly

### ISSUE THREAD

**Issue by CBPJ** [mkdocs/mkdocs#2195]
## Markdown code:
![image](https://user-images.githubusercontent.com/34758146/94240771-56f65800-ff46-11ea-9648-87fda44026e6.png)

## and the html page produced by mkdocs
![image](https://user-images.githubusercontent.com/34758146/94240987-a046a780-ff46-11ea-86e7-83eb5d4bc764.png)

## html:
![image](https://user-images.githubusercontent.com/34758146/94241496-4c888e00-ff47-11ea-971c-13f544ab390f.png)

## Github result:
![image](https://user-images.githubusercontent.com/34758146/94241154-ddab3500-ff46-11ea-804d-602c2fd959a5.png)

# My confusion:

It seems like that mkdocs created a `<ol>` label and lets the browser do the rest.

It's not a common markdown usage, and some [guidances](https://www.markdownguide.org/basic-syntax/#lists-1) also point out that this is the correct way to render the ordered list. But both github, vscode and typora render this like the example above.

Do you think mkdocs should modify its behavior?

mkdocs version: 1.1.2
theme: readthedocs
python markdown version: 3.2.2
MarkdownSafe version: 1.1.1

**Comment by facelessuser** [comment]
I think you are trying to nest code blocks under lists? If so, they should be indented 4 spaces under the list. This is, of course, assuming you are using the [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#nested-fence-format) extension.

**Comment by waylan** [comment]
Markdown parsing is handled by [Python-Markdown][1]. Please take and markdown parsing issues to that project.

[1]: https://github.com/Python-Markdown/markdown

**Comment by blakete** [comment]
Tabbing in my code blocks in the list fixed the number rendering for me.
