### ISSUE TITLE
keep README.md inside the site/

### ISSUE THREAD

**Issue by arjunskumar** [mkdocs/mkdocs#2197]
How can I keep README.md inside the site/ as every time I do mkdocs build, it cleans up the directory?

**Comment by ktomk** [comment]
On build, the site directory is cleared:

~~~
$  mkdocs build
INFO    -  Cleaning site directory 
...
~~~

From what I know there is not much that you can do about it (e.g. it's regardless the build is strict or not), so the easy way to do what you ask for is to copy the file out of the site directory and restore it after build.

In general in my opinion it's not worth to manage any files in the `site` folder manually.

Question would be why you ask how to keep a file in a directory which content gets entirely re-generated.

If you're looking to have a read-me when publishing to Github Pages (I can only guess here), here is how I'm currently do it including a `README.md`:

*  Generate the site into a sub-folder named `docs`.
*  Have the `README.md` next to it (not in it).
* Configure Github-Pages to serve from the `docs` directory [1].
* Mkdocs with `mkdocs gh-deploy` is not able to deploy such. A working alternative for me is `ghp-import` [2]

With this setup it is even possible to have the README.md for the documentation under version control.

Visiting the project page on the gh-pages branch shows a read-me to give a bit of context.

[1]: [Configuring a publishing source for your GitHub Pages site](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)
[2]: [c-w / ghp-import - Easily import docs to your gh-pages branch.](https://github.com/c-w/ghp-import)

**Comment by arjunskumar** [comment]
Thanks @ktomk

**Comment by ktomk** [comment]
@arjunskumar There was an imprecision in my last comment of which I just became aware:

Then you do not have strict mode in the configuration file, the build should work dirty, even if the site directory got mangled:

```
$  mkdocs build --dirty
```

**Comment by arjunskumar** [comment]
Thanks @ktomk
