### ISSUE TITLE
How to Get HTML files from MkDocs?

### ISSUE THREAD

**Issue by kumarkrish85** [mkdocs/mkdocs#2198]
In my project don't have GitHub page to upload the help doc. Can I get it as raw HTML file (**single page index.html also fine**) from mkdocs, so that I can launch the html file using Java without any server dependency?

Please help!

Regards

**Comment by squidfunk** [comment]
How about `mkdocs build`?

**Comment by facelessuser** [comment]
Yes `mddocs build` is the correct answer. As the output is a static site, there should be no problem wrapping whatever server you want around it as long as it serves up pages as expected per the directory URL configuration: https://www.mkdocs.org/user-guide/configuration/#use_directory_urls.

**Comment by kumarkrish85** [comment]
Thanks I used mkdocs build
