### ISSUE TITLE
htaccess best tool for redirects?

### ISSUE THREAD

**Issue by IdeaSandbox** [mkdocs/mkdocs#2200]
I'm migrating from Wordpress to Mkdocs. I know I'm going to need to do a bunch of redirects.

What is the right/best method, please?

- I've seen mention of redirects in Issue #45 (no solution), #1102 
- I've seen a plugin, but not sure how well it works, and I think it is still in beta -> https://pypi.org/project/mkdocs-redirects/
- I see the ReadTheDocs theme has some sort of built-in redirect tool -> https://docs.readthedocs.io/en/stable/user-defined-redirects.html

Any advice this group could provide would be terrific, please!

**Comment by ktomk** [comment]
Yes, Mkdocs creates a static site so the redirect capabilities remain on the webservers capabilities as redirects by a static site is negligible.

**Comment by IdeaSandbox** [comment]
@ktomk - thank you for your note. I'm more thinking about when I first launch the site, that slugs/URL will be different because I won't always want to follow or re-create the Wordpress set-up (categories/tags). So I'll need something at the start.

**Comment by ktomk** [comment]
Yes, sure, it's not even possible to build the same layout. That's why the clear yes to your question if .htaccess is the best tool for redirects.

**Comment by IdeaSandbox** [comment]
@ktomk awesome, thanks Tom!
