### ISSUE TITLE
 Markdown formatting rendering is incorrect on readthedocs compared to github/local editor.

### ISSUE THREAD

**Issue by LexiconCode** [mkdocs/mkdocs#2204]
## Details

* Read the Docs project URL: https://caster.readthedocs.io/en/latest/readthedocs/Customize_Caster/Creating_Hooks_and_Events/

I've tested with minimal edits to mkdocs.yml. e.g. pages: from nav

mkdocs v1.0.4 Python 2.7
mkdocs v1.1 Python 3.8

Testing procedure:

    pip install mkdocs==x.xx.x
    mkdocs serve
    Check documentation in question
    pip uninstall mkdocs-bootswatch mkdocs-bootstrap mkdocs -y
    Rinse and repeat for each mkdocs version

Notes

    The earliest mkdocs for the Python 3.8.2 is mkdocs 0.17.5 has the issue described in the OP.
    I've tried different browsers
    Python 2.7.X mkdocs 0.17.0 has the issue described in the OP.

## Expected Result

Markdown should render and display as it does in the local editor or on GitHub

## Actual Result

Bullet points and Numbered lists don't always display correctly. 

The following text is how the markdown should render.
---
## Creating Hooks and Events

Hooks are a new concept to Caster 1.x.x. The basic idea is that Caster itself defines "events." Event objects contain immutable information about the stuff going on in the "guts" of Caster. Those objects are fed to "hooks", user-defined listeners, which can do whatever they want with that event data.  

Hooks and Events make use of dependency injection and class inheritance through base classes. This design pattern coupled with loosely coupled code leads to less bugs and more productivity, and so the use of hooks rather than "guts" modifications is encouraged whenever possible. This should allow a decent amount of customization to happen without needing to make changes in the "guts" (Nexus, GrammarManager, CCRMerger, etc. of Caster. 

All new hooks are set to `false` by default unless they're defined as defaults in  `settings.toml`  under `default_hooks`. 

1. **Hook Runner Placement** 

   First to figure out what data you want to monitor In the source code and create a hook runner. For example printer hook monitors Enabled/Disabled rules states. See [grammar_manager.py](https://github.com/dictation-toolbox/Caster/blob/3ff4f7d7c9c01fec2059ffa5c4ca708fdb7d09ad/castervoice/lib/ctrl/mgr/grammar_manager.py#L151). A hook runner runs every time an event occurs. Printer Hook runner example `self._hooks_runner.execute(RuleActivationEvent(class_name, enabled))` .

   The Anatomy of hook runner:

   - `self._hooks_runner.execute`: executes the event as a hook runner

   - `RuleActivationEvent`: class name is the reference to the Event.

   - `(class_name, enabled)`: event data are variables from source code captured by the Event. 

    **Note**: Hook Runners can be reused to capture data throughout the source code in multiple functions assuming the observed data uses the same variables.

2. **Create a Event** 

   Create a Event and add to [Event types](https://github.com/dictation-toolbox/Caster/blob/master/castervoice/lib/merge/ccrmerging2/hooks/events/event_types.py). 

   - Events/Event types can be reused in hooks.

   - Don't forget to import the event at the location of your hook runner.

The event needs class name `RuleActivationEvent`,  event type `EventType.ACTIVATION` , and the variables (`class_name, enabled`). 

``` Python
from castervoice.lib.merge.ccrmerging2.hooks.events.base_event import BaseHookEvent
from castervoice.lib.merge.ccrmerging2.hooks.events.event_types import EventType

class RuleActivationEvent(BaseHookEvent):
    def __init__(self, rule_class_name, active):
        super(RuleActivationEvent, self).__init__(EventType.ACTIVATION)
        # Data from the hook runner
        self.rule_class_name = rule_class_name 
        self.active = active 
```

3. **Create a Hook**.

Hooks need class name `PrinterHook`, Event type `EventType.ACTIVATION` and a pronunciation`"printer"` 

Hook can be enabled/disabled while Caster is running. The get_pronunciation Is returned as `printer`
 
---
**How it actually displays on readthedocs.io**
![image](https://user-images.githubusercontent.com/24551569/78528510-30c8da00-77a5-11ea-849a-efc3cf64865b.png)

Original issue readthedocs
https://github.com/readthedocs/readthedocs.org/issues/6860

**Comment by waylan** [comment]
Please report any Markdown parsing issues upstream to [Python-Markdown][1]. However, note that GitHub uses a Commonmark parser and Python-Markdown is classic Markdown parser so there are some known differences.

[1]: https://github.com/Python-Markdown/markdown
