### ISSUE TITLE
Related to mkdocs Search - Search breaks when hosted in WPF ChromiumWebBrowser insdie Revit

### ISSUE THREAD

**Issue by dnenov** [mkdocs/mkdocs#2211]
This is more a cry for help than a bug report on mkdocs. We are experiencing a strange behavior when trying to host mkdocs in a ChromiumWebBrowser in WPF inside Autodesk Revit 'DockablePane' element. The problem only occurs when launched from within Revit - the exact same setup works fine with just the WPF.

This is a video demonstrating the issue, hopefully makes it easier to understand. The break occurs when a hit is found and before it is displayed.

https://www.youtube.com/watch?v=hvM9m43RR_w

It would be great if someone could kindly explain how Search is done - obviously a new panel is opened and gets focused. Then the search string is used to dynamically query results. The results are then displayed but I don't quite understand where exactly. I think this is where the implementation of Revit breaks somehow .. .

Any help is greatly appreciated!

**Comment by squidfunk** [comment]
> We are experiencing a strange behavior when trying to host mkdocs in a ChromiumWebBrowser in WPF inside Autodesk Revit 'DockablePane' element. The problem only occurs when launched from within Revit - the exact same setup works fine with just the WPF.

This can be considered an exotic use case, nothing the maintainers of the project are optimizing for. Additionally, this is clearly related to [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), so if the problem persists and you can create a minimal reproducible example, please open an issue over at our issue tracker.
