### ISSUE TITLE
Enabling TOC with toc_depth change sidebar menu sublinks

### ISSUE THREAD

**Issue by Mte90** [mkdocs/mkdocs#2215]
I am using as base the theme `readthedocs` and when I added this to `mkdocs.yml`:

```
markdown_extensions:   
- admonition   
- toc:       
    toc_depth: '2-4'
```

I have various `md` files with internally various headers with different levels.

So inside the pages we added `[TOC]` to print that list and with that settings we can avoid to first level header and more sublevels.
The issue happening is that header 2 level are not in the sidebar menu but just only header 3 are showed.

It is very strange that the settings of toc conflicts with the sidebar menu list.

**Comment by waylan** [comment]
I believe you are experiencing a conflict between the theme and the extension. The theme assumes level 1 headers exist and does not display them as there should be only one which is the page title. As the page title is already in the menu, it would be redundant to also display it in the TOC. Therefore, it skips the first level.

Therefore, you should assume that the first level will be skipped when defining your `toc_depth`. If you want levels `2-4` to be displayed, set the value to `1-4`. The theme will then ignore level 1 and display levels 2-4 as you desire.

**Comment by Mte90** [comment]
This works for the sidebar but if I want the first level not available for the TOC itself?
With that change we have the title page on the TOC itself but don't want it there, for this reason we have configured it in that way.

**Comment by waylan** [comment]
The theme assumes you have not included the TOC in the body of the document. Why would you want to in both locations? If you would like to include the TOC in the body of the document and exclude it completely from the navigation, you can set the [theme's][1] `titles_only` config option to `True`.

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#readthedocs

**Comment by Mte90** [comment]
I want the sidebar with some titles and inside the page the TOC with all of them without the firsts.

**Comment by waylan** [comment]
I suspect that is not possible. Note that the Markdown extension is developed separate from MkDocs. In fact, IIRC that specific feature of the extension is relatively new and the theme's existing behavior predates the feature in the extension. The two were never designed to work together.

Additionally, the TOC data does not include any indication of the h-level of each item. It only knows the hierarchy of the items in relation to eachother, not that the top level actually comes from an `h2` (for example). Therefore, there would be no way to have the theme only conditionally ignore the top level if it was from an `h1`, but not ignore it if it was from an `h2`.

Of course, a theme could have a config option which would enable/disable including the top level. However, the `readthedocs` theme is a clone of the Sphinx theme of the same name and the upstream theme doesn't have such a feature so we will not be adding that feature either. However, it could certainly be added to a third-party theme. I believe there are even a few forks out there of the `readthedocs` theme. Perhaps one of them has implemented the feature or would be wiling to.

**Comment by Mte90** [comment]
Ok the issue is clear, to me the issue is that the sidebar (that has a menu) has a setting parameter that conflicts with TOC itself.
