### ISSUE TITLE
Generating mkdocs incrementally

### ISSUE THREAD

**Issue by rubenssoto** [mkdocs/mkdocs#2220]
Hi,

Mkdocs are able to generate html site incrementally?
Im trying to use with a project that there are more than 1000 markdown files, so take a little longer to generate the docs and every time generate all docs, could be a problem.

thank you

**Comment by waylan** [comment]
You can use the `--dirty` flag with the `build` command to only build pages which have changed. However, be aware that if those changes require the navigation to be updated on every page, then you don't want to use the `--dirty` flag.
