### ISSUE TITLE
Add a option to only include title for search function

### ISSUE THREAD

**Issue by htynkn** [mkdocs/mkdocs#2221]
hey,

I'm working on a website which have too many articles, and we are using built-in search function.

Currently search function will include title and content which cause the search index data too big to load. It will cause a long time to init search function.

I would like to know if there is any way to only include title in search index? or is there any suggest to reduce the size of this data?

thanks :)

**Comment by waylan** [comment]
Currently, there is no way to do this. However, if you have a large amount of data, you might want to try using a [prebuilt index][1]. It reportedly improves search for large sites, YMMV.

[1]: https://www.mkdocs.org/user-guide/configuration/#prebuild_index

**Comment by squidfunk** [comment]
You can also post-process the `search_index.json` and set the `text` for all `docs`to `""`. Should be possible with a `jq` one-liner.

**Comment by squidfunk** [comment]
FYI, even simpler than I expected:

``` bash
jq '.docs[].title = ""' site/search/search_index.json
```

This will set the title to the empty string for each document. Just write that to a new file and rename it into `serarch_index.json`, and you're good to go. [jq](https://stedolan.github.io/jq/) is extremely powerfull.

**Comment by htynkn** [comment]
> FYI, even simpler than I expected:
> 
> ```shell
> jq '.docs[].text = ""' site/search/search_index.json
> ```
> 
> This will set the text to the empty string for each document. Just write that to a new file and rename it into `serarch_index.json`, and you're good to go. [jq](https://stedolan.github.io/jq/) is extremely powerful.

cool!

this works well in my website. thanks very much! :)
