### ISSUE TITLE
Return to home page by clicking on title or nav header

### ISSUE THREAD

**Issue by osresearch** [mkdocs/mkdocs#2225]
It seems the only way to return to the home page for a site is by clicking on the site icon; the site title in the navigation sidebar (`md-nav-title`) has an image, but the text of the site name is not in the `<a>` tag.  Similar in the header at the top has a clickable icon, but the `md-header-nav__tile` is not a link.

Is there an easy way to update the HTML to link the title as well? The icon is a small target compared to the text, so it might make it easier for site visitors to find their way back to the top level.

**Comment by waylan** [comment]
Which theme are you using?

**Comment by osresearch** [comment]
https://trmm.net/ is using the `theme: material`.  The relevant versions are:
```
% pip3 freeze --user | grep mkdocs
mkdocs==1.1.2
mkdocs-exclude==1.0.2
mkdocs-exclude-search==0.1.1
mkdocs-git-revision-date-localized-plugin==0.7.3
mkdocs-material==6.1.4
mkdocs-material-extensions==1.0.1
mkdocs-plugin-progress==1.2.0
mkdocs-redirects==1.0.1
```

**Comment by waylan** [comment]
The material theme is provided by a third party. Please take any issues involving that theme to that project.

**Comment by osresearch** [comment]
Sorry about misfiling it! Thanks for the pointer-- for future searchers I've filed it here https://github.com/squidfunk/mkdocs-material/issues/2044
