### ISSUE TITLE
Making New Line Does Not Render

### ISSUE THREAD

**Issue by BD103** [mkdocs/mkdocs#2226]
Hi. I've been experiencing some issues with using markdown and spacing. Look at my code and see the issue:
```markdown
help
me
please

- One
- Two
- Three

1. See that
2. This list
3. Does not render
4. Correctly
```
Then look at what it renders as:
![image](https://user-images.githubusercontent.com/59022059/98721600-e1601300-235e-11eb-9dc7-bcea0d32eb60.png)

Is there anything that I'm doing wrong, or is this a MkDocs issue?

**Comment by BD103** [comment]
I found a solution. I added empty lines between the text, but this still should get fixed.

**Comment by waylan** [comment]
MkDocs uses Python-Markdown to parse Markdown. All matters pertaining to the parsing of Markdown should be taken upstream to that project. That said, the current behavior is correct. See Python-Markdown/markdown#1058.

You may also benefit from [enabling][1] the [sane_lists][2] extension, which does alter the parser to be less surprising.

[1]: https://python-markdown.github.io/extensions/sane_lists/
[2]: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions
