### ISSUE TITLE
mkdocs-macros-plugin does not render variables or included files

### ISSUE THREAD

**Issue by VirginiaKelley** [mkdocs/mkdocs#2227]
This section of the Yml file gives errors:
  - macros:                   
      include_yaml: 
        - docs/_variables/general.yml 
      include_dir: docs/_snippets

WARNING -  Config value: 'plugins'. Warning: ('include_yaml', 'Unrecognised configuration name: include_yaml') 
WARNING -  Config value: 'plugins'. Warning: ('include_dir', 'Unrecognised configuration name: include_dir') 

in the MD
{{ myvariable }} does not render in Chrome (however works for other team members)
Includes do not work either

All installed OK under pip Python 39. Coworkers have Python 38. 

* If Python version is the problem, please make a code changing saying so on mkdocs build. Also what's the best way to unpip Python 39 without messing up MKdocs and other dependencies.

**Comment by waylan** [comment]
Please report any issues with a plugin to that project.
