### ISSUE TITLE
Nav elements randomly expanding

### ISSUE THREAD

**Issue by nikita-fuchs** [mkdocs/mkdocs#2234]
When clicking something in the navbar, individual elements in the nav unfold - but not all of them, a lot of unrelated ones though.

https://aeternity-js-sdk.readthedocs.io/en/latest/guides/contract-events/ <- try clicking a few nav elements. it's super annoying to have to collapse them all manually again, can that be some intentional setting ?

**Comment by waylan** [comment]
What does you `nav` setting look like?

If you have more than 2 levels of nesting it won't work correctly. As [documented][1] only two levels are supported. The additional levels can only be sections within a page. If you try to use more than that, the nav won't work correctly.

Note that this is a restriction of the upstream Sphinx theme. As we are cloning that theme, we will not entertain changing the behavior in this regard.

**Comment by nikita-fuchs** [comment]
aaaaah, damn - that is unfortunate, because we have so many individual files carrying individual documentation. So a solution would be customizing their builder to put everything in a large file rather and separate it through headings ?

**Comment by sim6** [comment]
The documentation referred by @waylan in https://github.com/mkdocs/mkdocs/issues/2234#issuecomment-731630814 maybe is https://www.mkdocs.org/user-guide/styling-your-docs/#readthedocs

**Comment by waylan** [comment]
Thanks @sim6 yes, that is what i intended to link to.

IN any event, due to the lack of actionable information, this is being closed. If the requested information is provided we can reconsider.

**Comment by Zylann** [comment]
I wonder if my problem is similar to this?

I just uploaded these docs: https://voxel-tools.readthedocs.io/en/latest/
As you will notice, a specific section will constantly unfold every item inside it (and it has a lot of items which makes it very bad), also preventing your current nav location to properly unfold.
You can get it into a "correct" state by folding the `Classes` nav and expanding your current page using the `[+]` icons, but as soon as you click on another top-level item, `Classes` expands again and the current page is unable to unfold.

**Comment by waylan** [comment]
@Zylann yes, the problem is that you have too many levels. You can only have two, but you have three. In other words, `Classes` can't have any children. Actually, as `Classes` is the only item at that level, I suggest removing it and having the list of classes listed directly under `API`. That should resolve your problem.

**Comment by Zylann** [comment]
> Classes can't have any children.

That also means you just can't have any child that has the folding feature :(
First level makes a non-clickable heading. Second level makes an item that is always visible in the side bar...
For me the whole point of using the third level was to get that folding capability. If I put classes at second level, they will all be shown all the time, and I don't want that.

**Comment by waylan** [comment]
@Zylann, sorry but that is how the upstream theme works. We just replicate it here. If that design doesn't work for you then I suggest trying a different theme. This limitation is theme specific and not a limitation of MkDocs in general.

**Comment by Zylann** [comment]
I could not find where that theme is developped. I found https://github.com/readthedocs/sphinx_rtd_theme but it's the one for Sphinx.
Otherwise I could try making my own but I have no idea yet if ReadTheDocs provides a way to do this.

**Comment by waylan** [comment]
The theme resides within MkDocs at [mkdocs/themes/readthedocs][1]. However, the CSS, JavaScript and Images are all copied as-is from the Sphinx theme at [readthedocs/sphinx_rtd_theme][2]. Presumably, the CSS and/or JavaScript would need to be updated to allow more levels and that is not something we are interested in doing. Of course, you are free to do so in a fork so long as you stay within the confines of the license.

[1]: https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/readthedocs
[2]: https://github.com/readthedocs/sphinx_rtd_theme
