### ISSUE TITLE
Currently there are two runtime locations where auxv data is parsed, `vsdo_linux_amd64.go`, and `os_linux_arm.go`. Adding arm64 will add a third location. This logic should be unified into a single file to be reused by all linux implementations.

### ISSUE THREAD

**Issue by chelli22** [mkdocs/mkdocs#2236]
Currently there are two runtime locations where auxv data is parsed, `vsdo_linux_amd64.go`, and `os_linux_arm.go`. Adding arm64 will add a third location. This logic should be unified into a single file to be reused by all linux implementations.

__Originally posted by @davecheney in https://github.com/golang/go/issues/9538__

**Comment by waylan** [comment]
Not sure what this has to do with MkDocs.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
