### ISSUE TITLE
MkDocs gh-deploy does not include CNAME if available.

### ISSUE THREAD

**Issue by jeremysprofile** [mkdocs/mkdocs#2237]
I have an example project:

```
.
├── .gitignore
├── CNAME
├── README.md
├── content
│   ├── 404.md
│   ├── about.md
├── layout
│   ├── base.html
│   ├── css
│   │   └── stylesheet.css
│   ├── cv.html
│   └── main.html
├── mkdocs.yml
```

Since this project deploys to a custom URL using GitHub Pages, it needs a `CNAME` file that points to my custom URL ["in the root of your publishing source"](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site).

Currently, gh-deploy does not support this. If I manually add the `CNAME` to the `gh-pages` branch, every future `mkdocs gh-deploy` will overwrite and remove it.

**I would like `mkdocs gh-deploy` to also move the `CNAME` file, if it exists, to the `site_dir`.
I'm willing to work on this, provided someone make some design decisions:**

* Where should gh-deploy expect the `CNAME` file to live? should it check everywhere in the repo? only in the root folder? only in theme.custom_dir? 
* Should this feature be gated behind a flag? I personally don't think so, as we can just do nothing if the file isn't found.
* What tests (if any) would you like to have around this feature?

**Comment by waylan** [comment]
As you can see, we have our CNAME file in the `docs` dir, which is the default name for the `docs_dir`. 

This is explained in the [documentation](https://www.mkdocs.org/user-guide/deploying-your-docs/#custom-domains).

You appear to be using a name other than `docs` (maybe content), so put it in the root of that directory.

**Comment by jeremysprofile** [comment]
Ugh. I can't believe I missed that. Thanks for pointing me in the right direction.
