### ISSUE TITLE
Allow Line Statements from Jinja2

### ISSUE THREAD

**Issue by jeremysprofile** [mkdocs/mkdocs#2240]
I much prefer the look of [line statements](https://jinja.palletsprojects.com/en/2.11.x/templates/#line-statements) in Jinja to the `{%` notation. It looks like [it's pretty easy to add support for this](https://jinja.palletsprojects.com/en/2.11.x/api/?highlight=environment#jinja2.Environment) to [theme.py](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/theme.py#L110).

Is there any chance MkDocs is willing to add this Jinja feature?

**Comment by waylan** [comment]
Personally, I fund that syntax repulsive. But that is just my personal opinion. In any event, I don't see any reason to add it.

**Comment by oprypin** [comment]
This will not be enabled by default (too dangerous at this point) and I also don't see any reasonable way to make it configurable. So as it stands, this will not happen. Further comments are welcome, though.
