### ISSUE TITLE
Home button requires an IP and not the host name

### ISSUE THREAD

**Issue by ryan-wolbeck** [mkdocs/mkdocs#2243]
Hello, 
Apologizes if this is just a user error, I'm just getting started with mkdocs. Great package by the way. I'm setting up mkdocs to run within docker and I'm having issues with the home button, image below
![image](https://user-images.githubusercontent.com/41489316/101073550-41fcfd00-3565-11eb-8eb4-e08c88afdaf8.png)

When I have the actual host name within my dockerfile, that would just spin until I set 
```bash 
network_mode: host
```
within my docker-compose.yml

I got it to work by adding the IP for the host explicitly with the dockerfile below
```bash
CMD ["mkdocs", "serve", "-f", "mkdocs.yml", "-a", "IPADDRESS:7003"]
```
whereas 
```bash
CMD ["mkdocs", "serve", "-f", "mkdocs.yml", "-a", "Hostname:7003"]
```
where IP is like 10.76.197.51 (fake) and the host name is something like lin2pr1pc1.

So while the docs are functional I think it would be nice to allow the host name to show through rather than the IP.

Versions:
```bash
mkdocs==1.1.2
mkdocs-material==5.2.3

Python : 3.7
````

Config file
```bash
site_name: Data Science Onboarding
theme:
    name: material
markdown_extensions:
    - attr_list
    - codehilite
    - admonition
    - footnotes
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: true
extra_css:
  - extra.css
```

Thanks!
Ryan

**Comment by waylan** [comment]
The host name is set with the [site_url][1] config setting. In fact, we will likely be making this setting required to avoid confusion in the future (see #2189). 

However, be aware that the `serve` command overrides that setting. Of course, the provided server is only intended as a dev server on the local machine. We do not officially support running the server from within a docker container or in any context in which the client is on a different system than the server. Instead, we recommend using a server which has been tested for production environments. When doing so, the `sire_url` setting will work as expected.

[1]: https://www.mkdocs.org/user-guide/configuration/#site_url
