### ISSUE TITLE
[question] How do i exclude rendering of specific files?

### ISSUE THREAD

**Issue by xcodz-dot** [mkdocs/mkdocs#2244]
For example I have:
```
docs
   +-- index.md
   +-- contents.md
   +-- downloads
       +-- template.md
       +-- somefile_to_download.md
mkdocs.yml
```

now the thing is I want every file to be copied to site but i do not want to render all files under downloads
basically, `template.md` should be `template.md` in site and not `template.html`

**Comment by waylan** [comment]
There is no builtin way to exclude pages from being rendered except to not include the in the `docs_dir`. However, there may be a few [plugins][1] which provide that functionality.

While this has been requested before, the use-case of downloads is a first. Guess I never considered anyone would provide a Markdown file as a "download."

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#navigation--page-building

**Comment by xcodz-dot** [comment]
I am just curious, btw thanks 😄
