### ISSUE TITLE
Can search also index raw html files in docs directory?

### ISSUE THREAD

**Issue by JoshuaMontgomery** [mkdocs/mkdocs#2245]
I think this is because the markdown preprocessor ignores these, but worth asking:

Is there a way to include raw HTML files that are in the docs directory in the search that is indexed by mkdocs?

**Comment by waylan** [comment]
No. The search index is built from Markdown pages only.

**Comment by JoshuaMontgomery** [comment]
Is that something that _could_ be addressed with an extension?

I'm just starting to familiarize myself with the limits of plugins/extensions, and could pick that up if it seems plausible.

**Comment by waylan** [comment]
I would image that is possible with a plugin but I can't say for sure.

**Comment by JoshuaMontgomery** [comment]
Ok, thanks!
