### ISSUE TITLE
`server.watch()`: ignore files or directories in watch list ?

### ISSUE THREAD

**Issue by fralau** [mkdocs/mkdocs#2247]
In the `on_serve()` method, I am having an unexpected functional issue with the `server.watch()`: in some cases where I indicate a directory I want to watch, there might be directorie or subdirectories in it that _may_ change at odd times (typically because they contain cache information), and that could create "race conditions" to the development web server (not sure how exactly, but it sure slows it down).

So I am faced with two choices: either 1) to stop watching that directory, and have to restart the server when I change a file in it. Or 2), try to live with the delays in page refresh caused by this exagerate changes to files. Since 2) is really a nuisance, I am putting it off.

One elegant solution could be to have a list of "ignore" patterns to the watch list, (as in `.gitignore`)? 

E.g. 

```python
server.watch(my_list, exception_patterns=['_foo*', 'bar.*'])
```

Could that make sense, for the project ?

**Comment by waylan** [comment]
The `server.watch` method is provided by [Python-livereload][1]. We simply provide access to the method through our Plugin API. Any changes to the method signature would need to be made there. However, as it turns out, it already accepts glob patterns, which may provide an alternate way to get what you want. Please follow up with the upstream project.

[1]: https://github.com/lepture/python-livereload#serverwatch

**Comment by fralau** [comment]
@waylan Thanks a lot for the pointer on Python-livereload. Indeed the globs could perhaps solve the issue. Otherwise, I will interact with that upstream project.

**Comment by AXGKl** [comment]
Hi,

> @waylan Thanks a lot for the pointer on Python-livereload. Indeed the globs could perhaps solve the issue. Otherwise, I will interact with that upstream project.

did you find a way to get mkdocs' livereload configurable? I see in `command/serve.yp` only hardcoded:

```python
    server.watch(config['docs_dir'], builder)
    server.watch(config['config_file_path'], builder)
```

I.e. not much room for reconfiguration / introduction of globs like

```python
    server.watch(config['docs_dir'] + '/**.md', builder)
```
