### ISSUE TITLE
build --minimal option

### ISSUE THREAD

**Issue by jmdye** [mkdocs/mkdocs#2251]
Can we have a `--minimal` option added to the `build` command which would only include in the built site those assets which are referenced in the templates, markdown files or classes applied to elements in the templates and markdown files. For example, if my `img` directory in `docs_dir` has 10 images in it, but only 3 of the 10 are actually used somewhere in the site, then there's no need to include them in the built site. 

It would be complicated but super helpful in minimizing the built size of a site.

**Comment by waylan** [comment]
This would require a major redesign as we do not track which assets have been linked and which have not. The general rule is that if you don't want files to end up in the built site, then do not include them in your `docs_dir`.
