### ISSUE TITLE
about toc

### ISSUE THREAD

**Issue by selfeasy** [mkdocs/mkdocs#2266]
if the toc is too long, when command "mkdocs serve"， open the browser， we can see the Table of contents in the left is also too long， can it be fixed with roll with some config？

**Comment by waylan** [comment]
Which theme are you using?

**Comment by selfeasy** [comment]
mkdocs theme

**Comment by waylan** [comment]
This was addressed in #696 way back in 2015. Or are you referring to something else?

**Comment by selfeasy** [comment]
thanks, i find the way to solve this problem, it works
