### ISSUE TITLE
Compiling SCSS/SASS with mkdocs

### ISSUE THREAD

**Issue by mottosso** [mkdocs/mkdocs#2276]
Hi all,

I've been struggling with this a few times in the past, and am back at it today.

```bash
.
├── mkdocs.yml
├── pages
│   ├── contact.md
│   ├── index.md
│   └── pricing.md
└── theme
    ├── css
    │   └── theme.css
    └── scss
        └── theme.scss
```

I'd like `scss/theme.scss` compiled  to `css/theme.css`. For this, I've got two pieces of machinery.

- [libsass](https://github.com/sass/libsass-python)
- Custom mkdocs plug-in

The plug-in looks like this.

1. on_files
2. Overwrite `theme.css` with output from libsass

```py
import os
import sys
import tempfile
import subprocess

from mkdocs import plugins, structure

class CompileSCSSPlugin(plugins.BasePlugin):
    def on_files(self, files, config):
        """Build our precious SCSS"""

        assets = os.path.join(os.getcwd(), "theme", "assets")
        scss = os.path.join(assets, "scss")

        tempdir = tempfile.gettempdir()
        theme = os.path.join(scss, "theme.scss")
        out = os.path.join(tempdir, "theme.css")

        sys.stdout.write("Compiling %s -> %s.." % (theme, out))
        if subprocess.check_call(["pysassc", theme, out]) != 0:
            sys.stdout.write(" failed\n")
            return files
        else:
            sys.stdout.write("\n")

        file = structure.files.File(
            "theme.css",
            src_dir=tempdir,
            dest_dir=os.path.join("theme", "assets", "css"),
            use_directory_urls=False
        )

        files.append(file)

        return files
```

The problem being that the overwriting of `theme.css` triggers another build, which builds another `theme.css` and another `theme.css` and another `theme.css` etc.

What I'd like to hear is either (1) I'm overlooking the built-in capabilities of mkdocs to build `scss` or `sass` files, or (2) there is some way of having `theme.css` only written to the *build directory* rather than my source directory, thus not interfering with livereload.

Is today my lucky day?

**Comment by waylan** [comment]
There are two additions to the next release (version 1.2) which may assist with this.

1. In #2094 we removed the theme from the watched files by default. A build will no longer be triggered by changes to theme files. Of course, you can revert to the old behavior with the `--watch-theme` flag.

2. In #2062 we added a `--wait` flag which allows you to set a delay between builds. If you set the delay to longer than the time it takes to complete a build, this should allow the build to finish without triggering a second build.

Both changes will be available in the next release. In the meantime, if you want to live on the edge, you can try them out by using the `master` branch here.

**Comment by waylan** [comment]
Regarding the solutions you were looking at:

> (1) I'm overlooking the built-in capabilities of mkdocs to build scss or sass files, 

No, this is not something we support directly. A plugin would be needed.

> or (2) there is some way of having theme.css only written to the build directory rather than my source directory, thus not interfering with livereload.

Why not have the plugin write to the `site_dir` directly? For example, If your theme only includes `theme.scss` but no `theme.css` files, then your plugin can read from `theme/scss/theme.scss` and and write to `site/css/theme.css`. So long as MkDocs never sees a `theme.css` file, there is no concern that your output will be overwritten. Of course, you'll want to avoid hardcoding `site`, but you can get the path from `config['site_dir']`.

With this approach, your plugin never writes to the theme directories and therefore will never trigger a second build. In fact, we are only adding the features which allow plugins to write to the source dirs now because we always expected that plugins would only write to the site dir.

**Comment by mottosso** [comment]
> A build will no longer be triggered by changes to theme files

I'd love to keep the ability to edit my theme at the same time, so I would probably use the old behavior.

> If you set the delay to longer than the time it takes to complete a build

That's interesting, that might help. It's not as important that it responds immediately, just that I don't have to return to the terminal per update.

> Why not have the plugin write to the site_dir directly?

Yes, exactly. That's what I've been looking for! That did the trick. 👍 

```py
# Changed
file = structure.files.File(
    "theme.css",
    src_dir=tempdir,
    dest_dir=os.path.join(config["site_dir"], "assets", "css"),
    use_directory_urls=False
)
```

Thanks, I'm all set. :)
