### ISSUE TITLE
Admonition block with code fences inside

### ISSUE THREAD

**Issue by myicq** [mkdocs/mkdocs#2278]
It's possible as mentioned here to use admonition by enabling the extension: "admonition". 

A block of admonition is done using indents like this:

!!! warning
    here is a warning

this is not a warning anymore

However I can't seem to find syntax to put a code fence inside a warning or note:

Trying something like this won't work:
```

!!! warning
     Do NOT try this python code:

	```python
	def fn():
		pass
	```
```	

The text is correctly rendered in `<code>` tags (except the "python" line is included), but outside the warning, it's rendered as
`<pre><code class="language-python">`

This seems like a bug in the renderer inside admonition ?

**Comment by waylan** [comment]
First of all, this is a matter for the upstream Markdown parser. Any issues should be reported upstream, not here. However, this is a known and [documented][1] limitation of fenced code blocks.

> Warning: Fenced Code Blocks are only supported at the document root level. Therefore, they cannot be nested inside lists or blockquotes. If you need to nest fenced code blocks, you may want to try the third party extension [SuperFences][2] instead.

Presumably this was closed for that reason.

[1]: https://python-markdown.github.io/extensions/fenced_code_blocks/#syntax
[2]: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
