### ISSUE TITLE
How to make these changes in default MkDocs theme 

### ISSUE THREAD

**Issue by asmita286** [mkdocs/mkdocs#2282]
I have a couple of doubts:

1. How can we specify logo to be shown at top left corner for the documentation (where the title "MkDocs" is shown)?
2. I have increased number of menus and also specified long title name at top left corner in place of "MkDocs". This makes menus overflow in second line. How can I decrease the left and right margin of the mkdocs pages so that the width of the actual / center documentation webpage will increase, making all menus to fit in the same line? Or is there any other more standard way around?

(I am using default mkdocs theme, which I guess is called as bootstrap.)

**Comment by waylan** [comment]
There are various ways you could accomplish these things. See the [Customizing a Theme][1] section of the documentation.

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

**Comment by asmita286** [comment]
Can you please point out one quick way? I guess I might have to add some CSS property to extra_css, but is there any documentation of what kind of CSS classes are suppported?  Or I have to reverse engineer, that is, check the class for served mkdoc site in F12 developer tool and then specify property for it in extra_css?

**Comment by waylan** [comment]
If a user wants to make customizations of a theme, they are certainly welcome to and we are happy to provide the mechanisms for them to do so. However, we assume the user knows how to work with HTML and CSS. Providing help with that is outside of the scope of help that can be provided here. You may be better served by asking your questions on a site like StackOverflow or another general purpose forum.

> is there any documentation of what kind of CSS classes are suppported?

No. Although, as the theme is based in Bootswatch/Bootstrap, you may find the documentation for those frameworks helpful. 

> Or I have to reverse engineer

Yes. Of course, with your browser's "inspect" tool, that should be pretty easy. You may also find the [templates][1] to be helpful.

[1]: https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/mkdocs

**Comment by fu-sen** [comment]
I'm digging up a little old Issue...

The logo image is implemented at the Bootstrap level:
https://getbootstrap.com/docs/4.2/components/navbar/#brand

It seems to be in demand. By being plugged in, it seems ideal that you can set it in `mkdocs.yml`.
Let's include it here. Developers will find it relatively easy to produce.
https://github.com/mkdocs/mkdocs/wiki/Plugins-Ideas

Note that Material Theme A has already implemented it:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo

**Comment by fu-sen** [comment]
I was touching Strapdown.js before looking at Mkdocs:
http://strapdownjs.com/
https://github.com/arturadib/strapdown

Strapdown.js adopts the Bootswatch theme. It also exists in the MkDocs theme.
This inspired me to become interested in MkDocs
https://github.com/mkdocs/mkdocs-bootswatch

And Strapdown.js does this, It's a very simple code:
https://github.com/joedf/strapdown-topbar/blob/gh-pages/assets/logo.js

It was an extra feature created by this project.
https://github.com/joedf/strapdown-topbar

**Comment by oprypin** [comment]
I think there is nothing actionable here. Themes indeed can be overridden, but as specified, helping users regarding HTML knowledge is out of scope.
