### ISSUE TITLE
auto-generated files trigger a live reload 

### ISSUE THREAD

**Issue by AnjoMan** [mkdocs/mkdocs#2284]
Ok, so i wrote an mkdocs plugin that dynamically builds some docs based on some input data. The basic structure of it is:

```python
class AutoDocumentExtension(mkdocs.plugins.BasePlugin):
    def on_pre_build(self, config):
        # generate some markdown and insert it into the docs tree
        with open(Path(config["docs_dir"]) / "special_folder" / "autogenerated_docs.md", "w") as f:
            f.write("# Automatic High-Quality Content!")
```

The issue i'm running into is that when i run `mkdocs serve` and then modify something in my docs source, the server gets stuck in a loop; it rebuilds the docs, which runs `on_pre_build`, rewriting `autogenerated_docs.md` which is detected by `livereload` and triggers a new build.

## What I've Tried

1. The first thing i tried was to have my plugin detect and not overwrite files. This obviously stops the boot cycle, but it means i would need to stop the server, find and delete all autogenerated files, and then restart the server any time i change the inputs to my plugin or modify its function.
2. Use a object variable to disable my prebuild step after serving, so that `autogenerated_docs.md` will only be made on the first build:
    ```python
    class AutoDocumentExtension(BasePlugin):
        def on_pre_build(self, config):
            if getattr(self, 'disable_autogenerated_docs'):
                  return
            ....
        def on_serve(self, server, config, builder):
             self.disable_autogenerated_docs = True
    ```
    This seems to not work, since there is no guarentee that the same plugin object will be used when the page is rebuilt.
2. Add the folder `special_folder` to the ignored directories using a method provided by `livereload` [here](https://github.com/lepture/python-livereload/blob/ecabebaeee2a40743f5a8216e1856c9f9150913f/livereload/watcher.py#L51). 
     ```python
     class AutoDocumentExtension(BasePlugin):
            ...
            def on_serve(self, server, config, builder):
                  server.watcher.ignore_dirs(Path(config["docs_dir"]) / "special_folder")
    ````
    This seems not to work, as `livereload` still checks files inside the directory to see if they've changed. it also wouldn't help me if the autogenerated files were mixed with other static files, since they would no longer be watched.
3. Using the `wait` command (which is [on the development branch of mkdocs](https://github.com/mkdocs/mkdocs/blob/520314fed933aed8de62b08dd7fc6e25c0ff482b/mkdocs/__main__.py#L130)) -- this also appears not to work, since the files are changed regardless of how long the reload function waits before running.

My question is, are there any features of mkdocs that are maybe not well documented and which address this issue? It appears there are ways to add files to the auto-reload mechanism, but not a way to ignore changes.

**Comment by waylan** [comment]
If the `--wait` flag is not working, please open a separate issue for that alone. As I noted in #2093: 

> Python-Livereload's documentation clearly stated that the value is seconds, but I'm wondering if perhaps its actually milliseconds. When I tried a really high number I did see a delay.

This is the first feedback I've received on it. So any additional info you could provide would be appreciated (in a separate issue).

That said, the `--wait` flag was added specifically to address this type of issue. Prior to adding the flag, there was no provision at all for adding, creating, or changing any files within the docs_dir during the build process. However, there are a few ways that users could work around that, as listed below:

1. Run a separate script to generate the documents. Run it once before running `mkdocs serve` and then while the server is running, you could run it multiple times. Of course, MkDocs will detect updates to the docs_dir by the script and rebuild. However, as the build does not invoke the script, there is no build loop to avoid.
2. Have the plugin generate the documents and write directly to the site_dir. This would require that whatever source the plugin used would need to be added to the watch list.
3. Presumably, a plugin could manually add page objects to the pages  collection which would then get rendered to the site_dir (but perhaps not even have a source file). The system was certainly designed with this in mind. However, I'm not sure if anyone has ever tried doing it this way.

Note that in solutions 2 and 3, nothing is ever written to the docs_dir. This is the way MkDocs is indented to be used. Anything else was a hack until we added the `--wait` flag.

Finally, I will note that we only provide a light wrapper around `livereload`. If you are encountering issues when modifying the `watcher` (such as ignoring files), then I suggest you take those issues upstream. For that matter, I could say the same about the `--wait` flag. We simply pass the value on to `livereload`. The only reason I ask for a separate issue above is so we can either remove it before release (if it is broken upstream) or (if `livereload` is actually expecting milliseconds) we can either update the documentation for the flag or convert seconds to milliseconds.

**Comment by AnjoMan** [comment]
> 3. Presumably, a plugin could manually add page objects to the pages collection which would then get rendered to the site_dir (but perhaps not even have a source file). The system was certainly designed with this in mind. However, I'm not sure if anyone has ever tried doing it this way.

This suggestion seems like it could be promising. I don't know if there is an event where i can modify the pages collection, but it seems like i could somehow add file items to the global files collection returned by [`on_files`](https://www.mkdocs.org/user-guide/plugins/#on_files)? I'll look into that.

> If the --wait flag is not working, please open a separate issue for that alone. As I noted in #2093:

 >>   Python-Livereload's documentation clearly stated that the value is seconds, but I'm wondering if perhaps its actually milliseconds. When I tried a really high number I did see a delay.

I tried the wait with a value of 50000 it doesnt affect the build loop in any way. it still runs the `builder` repeatedly every second:
```
[I 210112 16:00:19 handlers:64] Start detecting changes
INFO    -  Start detecting changes
[I 210112 16:00:28 watcher:110] Running task: builder (delay: 50000)
INFO    -  Running task: builder (delay: 50000)
INFO    -  Building documentation... 
[I 210112 16:00:31 watcher:110] Running task: builder (delay: 50000)
INFO    -  Running task: builder (delay: 50000)
INFO    -  Building documentation... 
[I 210112 16:00:35 watcher:110] Running task: builder (delay: 50000)
INFO    -  Running task: builder (delay: 50000)
INFO    -  Building documentation... 
[I 210112 16:00:38 watcher:110] Running task: builder (delay: 50000)
```

I wonder whether the feature even works on the `livereload` side? there are no unit tests there asserting it would work.

**Comment by waylan** [comment]
> I wonder whether the feature even works on the livereload side? there are no unit tests there asserting it would work.

If is doesn't work there, then we should remove it before we make the next release. No point in adding a new feature that doesn't work.

**Comment by AnjoMan** [comment]
Ok. i've opened a separate issue on the `wait` feature so someone can deprecate it. I'll close this since it seems like the question i had is covered by dev features. If i do get around to trying out the files object approach, i'll try to think about how to add some documentation of it so that others can make use of it as well.

**Comment by waylan** [comment]
> If i do get around to trying out the files object approach, i'll try to think about how to add some documentation of it so that others can make use of it as well.

By the way, #1629 defines a plan for including this information in the documentation. I don't expect you to take on the entire refactor described there, but anything you do work on would ideally fit into that plan. That said, the plan is not written in stone and subject to change; especially if we discover that the plan failed to account for something that we stumble upon whlle attempting to executing it.
