### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by greg-raven** [mkdocs/mkdocs#2287]
Is this project still active? There have been several updates to jQuery, Bootstrap, and Lunrjs that are not reflected in the core code base. What is needed to at least keep the project current with what the outside assets are doing?

**Comment by facelessuser** [comment]
From what I understand, the project is still active, particularly the core. If the theme assets are desired to be updated, I would consider a pull request.

Activity from the maintainers is usually based on their available time. Life can get quite busy, so community contributions are very valuable.

**Comment by waylan** [comment]
Yes, this project is active. However, we maintain it as volunteers in our spare time. Personally, MkDocs offers everything I need from it, so I'm not highly motivated to be adding new things. However, I do regularly review PRs and merge them if appropriate.

If there is something that you would like to se updated (such as a JavaScript library in the themes), then by all means open a PR and make the changes. I'll happy review it, and if it is good, merge it for inclusion in the next release.

I'm closing this issue as there is no actionable item here.
