### ISSUE TITLE
repo_url: is not taken literally

### ISSUE THREAD

**Issue by quizilkend** [mkdocs/mkdocs#2291]
Hello I have a question regarding the repo-url option of mkdocs.

I want to have a static link to PDF-files created out of the markdown files. I found that visually the repo_url is perfect for that. But when I put 

repo_url: https://gitlab.com/quizilkend/quizilkend.gitlab.io/-/jobs/artifacts/master/browse?job=pdfpages

in the mkdocs.yml
It gives me: https://gitlab.com/quizilkend/quizilkend.gitlab.io/-/jobs/artifacts/master/edit/master/docs/index.md

Is there a way to get exactly the written link on the web page?

Thank you very much
Samuel

**Comment by waylan** [comment]
The `repo_url` is preserved as-is. However, it would appear that you are seeing the "edit link" for the page. The "edit link" takes the `repo_url` and modifies it to point to the URL in the repo to edit that particular page. If you don't want an "edit link", then you would need to modify your theme to not display an edit link but instead the unmodified repo_url.

However, you don't mention which theme you are using, so it is difficult to say what would be involved in doing that. Some themes may have config settings to alter this behavior, whereas other themes would need you to provide your own template [customizations][1].

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

**Comment by waylan** [comment]
> The repo_url is preserved as-is. 

Well, there is one scenario where that is not true.

https://github.com/mkdocs/mkdocs/blob/269ec0857a7b613a66e0634b7b68606f21bbacca/mkdocs/config/config_options.py#L323-L331

As you can see in the above code, if there is an `edit_uri` set in the config and `repo_url` does not end with a `/`, then one is added to the end (on line 327). This is certainly the correct behavior when an `edit_uri` is set. To avoid that, be sure to not have an `edit_uri`. 

However, when the `repo_url` points to GitHub, Bitbucket, or Gitlab, then an `edit_uri` is automatically created for you if it is not set.  In other words, your problem wouldn't exit if you were using a link to some other, unknown host. That said, the auto-generated `edit_uri` is only created if the config option is set to `null` (the default). Therefore, you should be able to set `edit_uri` to a blank string to disable the whole thing. Like this:

```yaml
repo_url: https://gitlab.com/quizilkend/quizilkend.gitlab.io/-/jobs/artifacts/master/browse?job=pdfpages
edit_uri: ""
```

That said, some themes don't display the `repo_url`, but only the generated `edit_url` for each page. In that case, you may find that the link is missing completely as you have disabled edit links. That's the way it works in the `readthedocs` theme. However, the `mkdocs` theme will display the `repo_url` as a fallback. YMMV.

**Comment by waylan** [comment]
Sorry, I just remembered that this is all explained much more clearly in the Note in the documentation for [edit_uri](https://www.mkdocs.org/user-guide/configuration/#edit_uri). I should have just pointed you there.

**Comment by quizilkend** [comment]
Thanks for all the information. That was helpful.
I'm using the material theme. Actually it seems as if edit_uri is ignored under special circumstances. That is exactly what i want.
My settings are now as follows:

```
repo_url: https://gitlab.com/quizilkend/quizilkend.gitlab.io/-/jobs/artifacts/master/browse?job=pdfpages
repo_name: PDF-Download
edit_uri: ?job=pdfpages
```

Greetings!
Samuel
