### ISSUE TITLE
Search bar missing when running `mkdocs build`

### ISSUE THREAD

**Issue by guru-cloudknox** [mkdocs/mkdocs#2293]
So, when running the documentation locally through `mkdocs serve`, I am able to see and utilize the search.

![image](https://user-images.githubusercontent.com/50335486/105807605-332a3980-5f5b-11eb-8974-e52b0cf7e6b1.png)

However, after running `mkdocs build`, the search input goes missing.

![image](https://user-images.githubusercontent.com/50335486/105807661-4ccb8100-5f5b-11eb-84c8-1f2f89bcef3d.png)

When I go and inspect the html, it seems that the div for the search has a `hidden` attribute, but upon going into the `index.html`, I realize that there is no match for the string `hidden`, which leads me to believe that there is some javascript code affecting this. Please tell me what I am doing wrong. Thanks!

**Comment by waylan** [comment]
Your site must be served by a server for search to work. You cannot browse local files on the local file system (using `file://`) and have access the the search feature. This is enforced by your browser's security settings. We do not recommend disabling your browser's security settings.

Uploading the filed produced by `mkdocs build` to a server will result in search working, just as it does from the provided development server.

**Comment by squidfunk** [comment]
Just for the sake of completeness: with Material for MkDocs (that's what the OP is using) it's possible to make search work on `file://` with some effort:

https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#offline-search

**Comment by waylan** [comment]
Thanks @squidfunk. I had missed that those screenshots are of the Material theme. As this is related to a third party theme, I am closing this. Please follow up with the developers of the theme directly.
