### ISSUE TITLE
Feature request: anchor links beyond toc_depth

### ISSUE THREAD

**Issue by jmandel** [mkdocs/mkdocs#2294]
From the current docs:

> Note that MkDocs will not generate anchor links for levels outside the range defined with toc_depth. However, Material for MkDocs also allows to hide the table of contents on a specific page while keeping permalinks.

I have a use case where it's important that users can copy/share deep links at low levels (e.g., `h5`), even though we want the table of contents to remain uncluttered (e.g., `toc_depth: 3`). It would be really nice to (have an option to) generate anchor links at all levels, irrespective of what's in table of contents.

**Comment by waylan** [comment]
I see three issues with this request:

1. The request quotes from a third party extension's documentation. Any behavior specific to that extension needs to be directed to that extension.
2. The `toc_depth` option is not a MkDocs setting, but a setting of the [toc][1] extension for Python-Markdown. Any changes in behavior would need to be made there, not here.
3. If I am understanding correctly, the actual behavior is not as described. When using the `toc` extension, Markdown will assign an `id` to every header regardless of the `toc_depth` setting. The only thing the `toc_depth` setting controls is which levels are included in the table of contents. However, you can link to any level, regardless of whether it is in the table of contents. 

Regardless, you may want to use the `permalink` option of the `toc` extension to make it easier to discover the link for each header (although, it may be that your theme doesn't work well with permalinks; I don't know as I don't use that theme). For an example of how permalinks work, look at MkDocs' [Configuration][2] page. Note that the TOC only lists the sections, not each individual setting. However as you hover over the header for each individual setting, a little symbol appears to the right of it. That symbol is a link to that specific setting, which is there to make it easy for anyone to discover the link to that setting option, even though that link is not in the TOC.

[2]: https://www.mkdocs.org/user-guide/configuration/

[1]: https://python-markdown.github.io/extensions/toc/

**Comment by jmandel** [comment]
Thanks for the quick and thoughtful response! I'll close this issue and address with the theme :-)
