### ISSUE TITLE
FYI, I created: DocsMk – Standalone MkDocs.

### ISSUE THREAD

**Issue by ppo** [mkdocs/mkdocs#2295]
Template and CLI tool to manage a standalone MkDocs documentation.

https://github.com/ppo/docsmk

**Comment by waylan** [comment]
In the future please refrain from creating a new issue sold to make an announcement about third party projects. This is for reporting issues (bugs) or making feature requests.

If you would like other's to find you project you can list it on the [wiki][1] and/or announce it on the [mailing list][2], with of which are linked in our [README][3].

[1]: https://github.com/mkdocs/mkdocs/wiki
[2]: https://groups.google.com/forum/#!forum/mkdocs
[3]: https://github.com/mkdocs/mkdocs#mkdocs
