### ISSUE TITLE
Version differences in<details> section formatting?

### ISSUE THREAD

**Issue by zmontes-dev** [mkdocs/mkdocs#2298]
A colleague and I are trying to get some documentation up and running. In most details sections, markdown is not rendering. It is working on my computer and not on theirs. I am wondering what version differences or packages installed could be the cause. Another relevant aspect might be that I am running in a conda environment while they are not? We are both running on Windows

My mkdocs -V: `mkdocs, version 1.1 from c:\miniconda3\envs\mkdocs_env\lib\site-packages\mkdocs (Python 3.7)`
Theirs: `mkdocs, version 1.1.2 from c:\programdata\anaconda3\lib\site-packages\mkdocs (Python 3.7)`

Other things to note, I have made sure spaces and extra lines that can mess up formatting are fine. Like I said, it works on my computer. Please let me know what other info, if any, you will need to help us troubleshoot! Thanks

Image of error:

![error](https://user-images.githubusercontent.com/65970926/107425205-89f34f80-6ad3-11eb-98b3-1fdb6cfac392.jpg)

**Comment by facelessuser** [comment]
1. This would be an issue for https://github.com/facelessuser/pymdown-extensions not, mkdocs.
2. You would need to provide a minimal failing example for me (the author of the Details extension) so I could advise or debug if there was an actual issue.

Anyways, please provide a minimal example on the appropriate repository, and I'd be happy to help.

**Comment by zmontes-dev** [comment]
Okay, will do. Thank you
