### ISSUE TITLE
feature request: convert non-markdown source files

### ISSUE THREAD

**Issue by laoshaw** [mkdocs/mkdocs#2302]
Now mkdocs is restricted to pure markdown files.

I think it can be made even better, by working with other types of documents:

1. if it's PDF or other binary files, copy it over to sites directory so the user can still have all files together and can click and open them.
2. if it's source code(*.py, *.c, *.html, whatever), wrap it with a code fence block line and then generate the html, so the whole source code file becomes a markdown code block and can be read over the browser, with all syntax highlight work directly. for example I have a file my.py, mkdocs and add \```python to the start then append``` to the end of the file essentially convert it to a markdown file temporarily then generate html under sites directory.

this way, mkdocs can produce a site with markdown files, PDF etc and source code files. it's essentially a static github that supports various file types.

**Comment by waylan** [comment]
> if it's PDF or other binary files, copy it over to sites directory so the user can still have all files together and can click and open them.

This is already possible. Simply include the file int he docs dir. Any non-Markdown file will be copied as-is.

> if it's source code(*.py, *.c, *.html, whatever), wrap it with a code fence block line and then generate the html, so the whole source code file becomes a markdown code block and can be read over the browser, with all syntax highlight work directly.

This seems out-of-scope to me. Although it may be possible with a plugin. You are free to build one.

**Comment by laoshaw** [comment]
yes they're copied over to sites/ but I could not access them easily from the theme, will see if I am capable to work on a plugin, or just add some script to do the conversion before running mkdocs.

**Comment by waylan** [comment]
> I could not access them easily from the theme

You can always list them in your [nav][1] config setting. We can't list them automatically as we don't know which are intended to be listed and which are not.

In fact, we have received the opposite request more often: to not include any files which the user does not explicitly list. This request is in direct opposition to that more common request. In either case, a plugin would be the way to address these matters.

[1]: https://www.mkdocs.org/user-guide/configuration/#nav
