### ISSUE TITLE
How to override nav config so the exclude plugin works?

### ISSUE THREAD

**Issue by NavyaG-lab** [mkdocs/mkdocs#2315]
I have a scenario where in the mkdocs.yml, the nav is customized as per designed taxonomy. Now, we want to exclude some folders not to be rendered on the static site. For that, I used [mkdocs-exclude](https://pypi.org/project/mkdocs-exclude/) and removed links under the "nav" in the mkdocs.yml. As the files are in docs directory and not under nav, it's throwing error.

Could someone please help me how to achieve desired goal?
- Exclude the specific folders in the repo and remove some links from nav, so the static site renders only the desired content.

**Comment by NavyaG-lab** [comment]
> I have a scenario where in the mkdocs.yml, the nav is customized as per designed taxonomy. Now, we want to exclude some f

**Comment by NavyaG-lab** [comment]
I have a scenario where in the mkdocs.yml, the nav is customized as per designed taxonomy. Now, we want to exclude some folders not to be rendered on the static site. For that, I used [mkdocs-exclude](https://pypi.org/project/mkdocs-exclude/) and removed links under the "nav" in the mkdocs.yml. As the files are in docs directory and not under nav, it's throwing error.

Could someone please help me how to achieve desired goal?
- Exclude the specific folders in the repo and remove some links from nav, so the static site renders only the desired content.

**Comment by waylan** [comment]
The mkdocs-exclude plugin is developed by a third party. Please request assistance from the developer of the plugin directly.

**Comment by DariuszPorowski** [comment]
@NavyaG-lab

I developed a plugin for includes/excludes that supports nav filtering based on excludes because I had the same issue as you. Unfortunately, mkdocs-excludes looks like it is not maintained anymore.

You can find it here: https://github.com/DariuszPorowski/mkdocs-file-filter-plugin#navigation-filtering

It works for me, and I am happy to get feedback, idea, improvements, etc.

CC: @waylan
