### ISSUE TITLE
Is there a way that I can exclude certain folders to not render on static site

### ISSUE THREAD

**Issue by NavyaG-lab** [mkdocs/mkdocs#2316]
I have a case where the repo A contains XYZ folders. I want the content in Y folder not to render on the static site. How can it be aheived?

**Comment by waylan** [comment]
This is supported through plugins. You may find one which meets your needs in the [list on the wiki](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#navigation--page-building).
