### ISSUE TITLE
make mkdocs.yml optional

### ISSUE THREAD

**Issue by laoshaw** [mkdocs/mkdocs#2320]
assign a default value e.g. 'mkdocs' to its title variable in the code should be enough for that.

make it override-able via command line flags. it will be even nicer if I can designate docs directory at command line, e.g. 'mkdocs build -h my-site-title -t mytheme -m my-markdown-dir -d my-site-dir', this way is much better for scripting, as I don't need create a mkdocs.yml before I create a static-site quick

what about make those options to 'make serve' too? i.e. if I run 'make serve' it will invoke 'make build' first by default, so I can simply do: cd mydir; mkdocs serve -C .. without any mkdocs.yml, and I can pass args to mkdocs-build via mkdocs-serve too if wanted, e.g.  'make serve -C .. -- -h my-site-title -t mytheme -m my-markdown-dir -d my-site-dir'

**Comment by fu-sen** [comment]
Currently the minimum `mkdocs.yml` is only` site_name`, 
```
site_name: MkDocs
```

but it could default to <H1> in `index.md`.  Can this completely eliminate the files?

**Comment by polarathene** [comment]
You would be better suited to use something like a Docker image. You can containerize your MkDocs setup (like `mkdocs-material` does, and then extend that to an image that embeds a default `mkdocs.yml` file.

The `mkdocs-material` image by default will run `mkdocs serve`, so you can get focused on your docs straight away without any setup hassle. It does expect the `mkdocs.yml` file however, but as mentioned, you could extend the image to already provide your own default for that, or leverage other approaches (such as mounting a local `mkdocs.yml` file that all your instances share in common unless you need to specify a project specific one.

For example: `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material:latest` is all you need to get started, the directory that you run that command from will be added into the docker container at `/docs`, you can add your markdown files and anything else you would have for your project in that local directory.

To add a common `mkdocs.yml` file, just mount it like so: `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs -v "path/to/mkdocs.yml:/docs/mkdocs.yml" squidfunk/mkdocs-material:latest`. When you have a project specific one, remove that addition so it's like the earlier mentioned command, and add the `mkdocs.yml` file to the same directory that maps to the containers `/docs` dir.

If you need added clarification of other options in that command:

- `--rm`: Removes the container after you're done with it (internal state like files doesn't persist between runs).
- `-it`: Provides an interactive terminal session (this gives you stdout that you'd expect from running something via CLI).
- `-p`: Binds the container port 8000 to the host (you can view the docs at `http://localhost:8000`).
- `-v`: Mounts a volume into the container filesystem at the given path (`/docs`). Any changes locally will be reflected in the container for mounted directories, direct file binding will change inode and thus require restart (binds inode of dir or file).

---

Alternatively if your preference is scripting without leveraging Docker... just write a script that will generate `mkdocs.yml`, run the mkdocs command you want, and afterwards cleanup by removing the file? There's a variety of ways to approach that too.

**Comment by laoshaw** [comment]
yes I wrote a script to do that,just thought if mkdocs can do it out of box it will be nice
