### ISSUE TITLE
[question] File list

### ISSUE THREAD

**Issue by dosch** [mkdocs/mkdocs#2322]
Can MKDocs generate a page from a directory with all sorts of files in it?

I have a directory where I save all sorts of file for people to download: different svgs, zips, tars, jpgs etc. etc. Often with quick changing version numbers. 

Maintaining a table with correct links to every file is rather tedious... So I would like to link to the directory where people can use the naming of the respective files to figure out which one they need and download them

Thnx!

**Comment by waylan** [comment]
MkDocs will copy any files in your docs_dir to the site. However, MkDocs will not do anything else with non-markdown files. If you would like to auto-generate a list of files, then you would need to use a plugin for that.

**Comment by fu-sen** [comment]
Are you looking for something like Apache's `Options +Indexes` ? or 
https://vercel.com/docs/edge-network/directory-listing

I know someone who blogs on MkDocs. 
He seems to have manually generated a list of articles in `index.md`.
This idea can also be a means of auto-generation.

Ideally, it will be produced as a plug-in.

**Comment by fu-sen** [comment]
Added to Wiki. Expect the development of plugins:
https://github.com/mkdocs/mkdocs/wiki/Plugins-Ideas
