### ISSUE TITLE
Process the navigation object after the `on_nav` event

### ISSUE THREAD

**Issue by lyz-code** [mkdocs/mkdocs#2324]
MkDocs initializes and processes the `Navigation` object in the [`get_navigation`](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/nav.py#L99) function. If you want to add items with a plugin in the `on_nav` event, you need to manually run all the post processing functions such as building the `pages` attribute, by running the `_get_by_type`, ` _add_previous_and_next_links` or ` _add_parent_links` yourself. Additionally, when building the site you'll get the `The following pages exist in the docs directory, but are not included in the "nav" configuration` error, because that check is done *before* all plugins change the navigation in the `on_nav` object.

So my suggestion would be that the `get_navigation` function is split in two, one to initialize the `Navigation` object, and then another to process the navigation once all plugins have run the `on_nav` event.

**Comment by waylan** [comment]
The `Navigation` object is built from the `Files` collection. If you would like additional objects to be included in the navigation, then perhaps you should be creating `File` objects and adding them to `Files` in the `on_files` event.  Of if you would like to create non-file nav objects, perhaps modify `config['nav']` in the `on_config` event. Either way, they would get processed by `get_navigation`. 

However, if you want to manually generate nav objects, then use the `on_nav` event and manually create the objects. By this point, I'm assuming there would be no corresponding files, so the warning (note it is **not** an error) about a file without a corresponding nav object would not be an issue.

**Comment by lyz-code** [comment]
Thank you for the quick answer @waylan.

I tried to do as you said. I created the `File` objects in the `on_files` event and then created the `Section`, `Pages` and `SectionPages` elements from those items and added them to the `nav.items` list in the `on_nav` event. The problem was that I had then to manually run all the post processing functions mentioned before, or the navigation wouldn't work as expected and the footer wasn't created. And still had the building error.

That's why I thought doing the nav post processing functionality and the checking of nav items after the `on_nav` events on the plugins made sense.

I've made a [post in my blog about it](https://lyz-code.github.io/blue-book/linux/mkdocs/#adding-new-files) but in the end I did everything in the `on_config` event and tweaked the `config['nav']` element.  Probably it's not the best way to do it, but [it works!](https://github.com/lyz-code/mkdocs-newsletter).

I'm OK with closing the issue if you don't agree with the proposal.

Thanks for your help :)

**Comment by waylan** [comment]
>  I created the `File` objects in the `on_files` event 

My point was that that is all you should need to do as the `on_files` event is called before `get_navigation`. Then `get_navigation` would handle everything else for you. 

I suppose the tricky part here is related to the `nav` config. If it is empty, then `get_navigation` builds the `nav` from `Files` and you do get everything for free (which is the scenario I was considering above). However, if `nav` has items defined in it, then you would need to manually add the item to the `nav` in the `on_config` event by adding an entry to the `nav` (`{'title': 'path/to/page.md'}) so that `get_navigation` can properly associate it with your `File` object. I guess I didn't spell that out clearly. However, in the end it looks like you worked it out.

**Comment by lyz-code** [comment]
Exactly, that was exactly my case, the nav had already some items, so it didn't get autogenerated.

I guess that this is a corner case that hasn't appeared before, so it may not make sense to do the change in the code. 

If someone tries to do something like I did, they have this issue as documentation.

Thanks for your time

**Comment by oprypin** [comment]
@lyz-code This is a very insightful request, I also had the same problem in a plugin that takes over nav generation.
There are only hacky options:

1. In `on_nav`, ignore the supplied `nav` (and hope that no other plugins running before this one have `on_nav` handlers altering `nav`) and make your own nav dict, possibly based on `config["nav"]`, then pass that to `get_navigation` (which, yes, makes it run for the 2nd time).

2. In `on_files`, directly modify `config["nav"]` to become what you want (and hope that no other plugins running after this one have `on_files` handlers altering `files`), then rely on the fact that that will be passed to `get_navigation`.

Initially I went with the 1st one but now I'm finding that the 2nd one may be slightly better.
