### ISSUE TITLE
Enforce markdown inside html tags

### ISSUE THREAD

**Issue by matamadio** [mkdocs/mkdocs#2325]
Mkdocs is a great tool that saved me a lot of headache. However I'm found stuck on an issue: the docs pages contains very long tables which I'd like to contain in height, either by fixing height value and adding scrollbar via css, or by making them collapsible. 

But I found out that all markdown within the `<div>` or `<details>` tags is not translated as html by design. Is there a way to enforce the rendering of some markdown, or some other workaround? (excluding inserting the table as html)

```
<div class="scrollbar table-scroll">

| **Item** | **Item** | **Item** | **Item** | **Item** |
|:---:| --- | --- | --- | --- |
| data | data | data | data | data |
| data | data | data | data | data |
| data | data | data | data | data |
...
| data | data | data | data | data |

</div>
```

Expected result:
![immagine](https://user-images.githubusercontent.com/44863827/110677718-c4850080-81d5-11eb-9f25-9eafbe8378cb.png)

**Comment by facelessuser** [comment]
I'd use the `md_in_html` extension that comes with Python Markdown, then specify `<div class="scrollbar table-scroll" markdown="1">`.

**Comment by matamadio** [comment]
Thanks mate, your solution is what I was looking for!
Issue can be closed.
