### ISSUE TITLE
pointing to a jupyter notebook via relative path

### ISSUE THREAD

**Issue by sidhomj** [mkdocs/mkdocs#2326]
I'm making a docs page where I want one of my pages to point to a jupyter notebook in my repo.

right now, my yaml file reads as such:

```
nav:
    - Home: index.md
    - Getting Started: '../../tutorials/1 - Loading Data (Introduction).ipynb'
   
```

However, when trying to run the site, I get the following error:

```
 A relative path to '../../tutorials/1 - Loading Data (Introduction).ipynb' is included in the 'nav' configuration, which is not found in the documentation files
```

Any help would be appreciated to how to get this to work properly!

**Comment by waylan** [comment]
That is not an error or even a warning. It is simply an "info" message informing you that a nav item does not point to an internal page. If that is what you intended, then the message is confirming that things are working as you want.

**Comment by Megver83** [comment]
@waylan really? 'cause I've a similar configuration to this one mentioned in the [docs](https://www.mkdocs.org/user-guide/configuration/#documentation-layout)
```
site_url: https://example.com/foo/

nav:
    - Home: '../'
    - 'User Guide': 'user-guide.md'
    - 'Bug Tracker': '/bugs/'
```
but I get a **warning** which makes mkdocs fail with `--strict`

    WARNING  -  A relative path to '../' is included in the 'nav' configuration, which is not found in the documentation files

And `Home` doesn't even point to the upper directory. Kinda similar to #2185

**Comment by pawamoy** [comment]
Looks like the solution today is to use the validation settings: https://www.mkdocs.org/user-guide/configuration/#validation (`validation.nav.not_found`). Closing, feel free to comment further!
