### ISSUE TITLE
Download links

### ISSUE THREAD

**Issue by quizilkend** [mkdocs/mkdocs#2328]
Hello,

I'm not sure if this is the right place. But I do not have a google account, therefore I can't write in the discussion group.

Is there a possibility to inlcude a download link in a mkdocs page?

I tried with inline HTML, like  
`<a href="myFile.xml" download>Click to Download</a>`

But mkdocs seems to strip the `download` attribute.

Expected behavior:
If I click on the link, the browser asks me to download the file.

Experienced behavior:
The browser shows the contents of the xml-file.

I'm using mkdocs with the material-mkdocs theme on gitlab:
- mkdocs 1.1.2
- material 5.4.0
- markdown 3.2.1

Best regards
Samuel

**Comment by waylan** [comment]
> But mkdocs seems to strip the download attribute.

I can't replicate that behavior. In other words, it works just fine for me. Which versions of MkDocs and Markdown are you using?

**Comment by quizilkend** [comment]
Of course.

Sorry I didn't give this information in the first place.

I edited the first message accordingly.

Best regards.

**Comment by martinbira** [comment]
If you are using Material, I would suggest that you use the [Attribute List extension](https://squidfunk.github.io/mkdocs-material/reference/buttons/#attribute-list) and add `{  download }` after your regular markdown link, i.e. `[Click to Download](myFile.xml){ download }`. This should convert to `<a href="myFile.xml" download="download">Click to Download</a>` and trigger the download dialogue.

**Comment by quizilkend** [comment]
Okay I was very happy about the Attribute List extension.

But unfortunately it isn't working as expected.

If I click links now, it downlods the file but alters the filetype. I have download links to an `.ino` and an `.abp`-file.

The website is:
https://greiner.schule/nwt/raumluftampel/#quellen-und-weiterfuhrende-links

The markdown source of the links is:
```
  [Als ArduBlock-Datei](raumluftampel-assets/ArdublockAmpel.abp){ download }  
  [Als Datei für die Arduino-Entwicklungsumgebung](raumluftampel-assets/CO2-Ampel-deutsch.ino){ download }
```

The source of the generated html is:
```
<a download="download" href="../raumluftampel-assets/ArdublockAmpel.abp">Als ArduBlock-Datei</a><br />
<a download="download" href="../raumluftampel-assets/CO2-Ampel-deutsch.ino">Als Datei für die Arduino-Entwicklungsumgebung</a></p>

```

The `.abp` file gets downloaded as `.xml` and the `.ino` file gets downloaded as `.txt` (in Chrome).

**Comment by martinbira** [comment]
I tried your links with Chrome and I was able to Download both files in their native format without altering anything in the Chrome download dialogue.  So I cannot reproduce your error, perhaps it is a local setting in your browser/your computer.
![download-tests](https://user-images.githubusercontent.com/22232681/111604358-8ab78980-87d5-11eb-93fd-ad939ae80a90.png)

**Comment by quizilkend** [comment]
Okay, I guess it works now because I altered the markdown source to:
```
  [Als ArduBlock-Datei](raumluftampel-assets/ArdublockAmpel.abp){ download="ArdublockAmpel.apb" }  
  [Als Datei für die Arduino-Entwicklungsumgebung](raumluftampel-assets/CO2-Ampel-deutsch.ino){ download="CO2-Ampel-deutsch.ino" }
```

I wasn't aware that i have to pass the filename with the `download` attribute.

Thank you very much for your help!
