### ISSUE TITLE
Page title is not parsed as Markdown

### ISSUE THREAD

**Issue by dvershinin** [mkdocs/mkdocs#2343]
## Description

Suppose a Markdown file that starts with this title:

```markdown
# *openidc*: OpenID Connect Relying Party and OAuth 2.0 Resource Server implementation in Lua for NGINX / nginx-module-lua
```

The `<title>` of the HTML generated by mkdocs becomes: `*openidc*` as is instead of rendered in italic with `<em>`.

Same behavior with `_openidc_`.

My case is when I'm *not* specifying page title via mkdocs.yml. 

That is, this page is not in navigation at all, it is simply linked from another page.

The only customization/overrides I have is for `{% block announce %}`, and there isn't much in there.

For an idea, you can check `<title>` on [this page](https://nginx-extras.getpagespeed.com/lua/auto-ssl/). It is only linked from
a table [here](https://nginx-extras.getpagespeed.com/lua-scripting/) and not in navigation.

**Comment by waylan** [comment]
Yes, that is correct, the page title is not parsed as Markdown. In fact, the page title is determined before the source text of a page is converted from Markdown to HTML. This was an intentional design decision. It also avoids weird formatting in nav items as all nave items are plain text.
