### ISSUE TITLE
There is something wrong in normalize_path 

### ISSUE THREAD

**Issue by fengchenzxc** [mkdocs/mkdocs#2368]
Hello, I am from China. My mkdocs is installed with pip3, and my computer is a mac. Today I found that the ```mkdocs gh-deploy```  command has the following error:
![image](https://user-images.githubusercontent.com/41096522/115103998-58da4400-9f88-11eb-818b-085ec829c123.png)
I found that when reading the file path name, the Chinese colon ```：``` was changed to the English colon ```:```
I guess it may be a unicode encoding problem, so I followed up the bug step by step and found that ```gph_import.py``` called ```normalize_path``` function when reading the file,
So I continued to follow the ```normalize_path``` function, and found that the function will determine the system type, if it is darwin, use ```unicodedata.normalize("NFKD", dec(path))```
![image](https://user-images.githubusercontent.com/41096522/115104201-722fc000-9f89-11eb-9c2c-b4329c2a09c8.png)
So I commented this code, the bug was solved, maybe the file name unicode problem has been solved by MAC OS X today.
Hope to adopt:)

**Comment by waylan** [comment]
The `normalize_path` function was defined in `ghp_import.py`, which was a vendored copy of an old version of [ghp_import][1]. In #2257 we removed that vendored copy and now list the most recent release ghp_import as a dependency. The change will be included in the next release.

If the problem still exists in the upstream library, then the issue should be reported upstream. There is nothing for us to do here.

[1]: https://github.com/c-w/ghp-import
