### ISSUE TITLE
gh-deploy fails while running inside a github action

### ISSUE THREAD

**Issue by aahnik** [mkdocs/mkdocs#2370]
```shell
Run poetry run mkdocs gh-deploy
  poetry run mkdocs gh-deploy
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.4/x64/lib
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/runner/work/pyproject/pyproject/site 
INFO    -  Documentation built in 0.09 seconds 
WARNING -  Version check skipped: No version specified in previous deployment. 
INFO    -  Copying '/home/runner/work/pyproject/pyproject/site' to 'gh-pages' branch and pushing to GitHub. 
ERROR   -  Failed to deploy to GitHub with error: 
To https://github.com/aahnik/pyproject
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/aahnik/pyproject'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
 
Error: Process completed with exit code 1.
```

when I run the same command in my local machine, it works fine. Running the first time creates an orphan branch, and for subsequent runs, it adds commits to the gh-pages branch.

More details: [My workflow file](https://github.com/aahnik/pyproject/blob/83881ec8d0e34f5dcea469606b9fe9569b98fb59/.github/workflows/docs.yml) 
[Full Logs of the workflow](https://github.com/aahnik/pyproject/runs/2372344643?check_suite_focus=true)

**Comment by aahnik** [comment]
Actually this got solved by checking out all branches.

```yaml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

**Comment by Nthily** [comment]
thank you !! I encountered this error tonight too

**Comment by waylan** [comment]
Note that there was a regression in `gh-deploy` which has been fixed in #2444, and will be available when 1.2.1 is released. In 1.2, `--force` does not actually do a "force push " but rather only a "push" (and leaving off `--force` doesn't push at all). If you need to do a "force push", then you will need to stay on 1.1.2 until 1.2.1 is released. Sorry for the inconvenience.

**Comment by aahnik** [comment]
Thanks @waylan  for the clarification.

**Comment by waylan** [comment]
FYI, version 1.2.1 has been released.
