### ISSUE TITLE
[FR]: hljs_style for built-in rtd-theme

### ISSUE THREAD

**Issue by suitre77** [mkdocs/mkdocs#2393]
Hi,

would be nice if the hljs_style option is also available for the rtd-theme and not only mkdocs theme.

KR

**Comment by waylan** [comment]
The `readthedocs` theme is a clone of the Sphinx theme of the same name. We have only implemented features and options which are supported by the upstream theme. As this option is not available upstream, we will not be making it available here. That said some forks of the theme have been made and one of them may add such a feature.
