### ISSUE TITLE
Local development for subdirectory deployment is useless

### ISSUE THREAD

**Issue by unconed** [mkdocs/mkdocs#2394]
When deploying to e.g. a subdirectory on github pages, root-relative URLs will break. The rationale behind mandating relative URLs is explained here:
https://github.com/mkdocs/mkdocs/issues/1757

> we assume that users understand the basis of the command line, which includes an understanding of relative paths.

Regardless of the rationale, the current behavior is broken when trying to deploy to a subdirectory. I am opening this ticket because I just tried to write a doc on how to embed images and link to other pages in our mkdocs site, and discovered that the resulting process is tedious and error prone, defying basic common sense about how people do things.

When someone tries to embed an image, they will try one of two things:
`/images/image.png` or `images/image.png`

I guarantee you they will not think to try `../../images/image.png` until they hit the preview and see a broken image.

The same goes for linking to another page: only then they actually have to try and click the link to notice that it's broken. Most of the time they will not. So given that the `/images/image.png` and `/absolute/page/link` works fine locally, they will think everything is hunky dory and submit a docs MR that will break when deployed. Which won't be noticed until someone else tries to read/use the docs.

At the very least, setting `site_url` should force local dev to happen under the same `/subdirectory` path, so that local preview at least reflects the final result. If it doesn't, that defeats the entire purpose of a local preview. Right now, it appears to be a trap. And it's not like github pages are rarely used.

(Personally I would hope you'd understand that there are many kinds of paths in use on the web and in code, and people have solid reasons to want to use them when building a linked repository of knowledge, instead of mandating that they can't.

Thinking in terms of a root-relative URL is more intuitive, because you don't need to think about where you're linking from. It also means you can copy a piece of markdown from another page in my wiki without any of the links inside it breaking. All of these are good things when trying to produce sensible documentation with a team of homo sapiens instead of autistic robots.)

**Comment by waylan** [comment]
> The rationale behind mandating relative URLs is explained here:
> #1757
> 
> > we assume that users understand the basis of the command line, which includes an understanding of relative paths.

That is not the rational. However, that is an assumption that we make. The rationale is that relative paths also work when browsing the source documents here in GitHub (or whatever repo hosting site you use) as well as within your text editor (if your editor renders links clickable). The same goes for browsing the built site using `file://` locally. In each case, you need to use `../../images/image.png` not `/images/image.png` or `images/image.png`. In other words, we are using the only universally consistent method of linking between files within your documents. When a user uses those links it creates a better user experience in various different environments. So, yes, we expect our users to learn how to properly make relative links.

**Comment by BetterThanReal** [comment]
As someone who recently overcame a misunderstanding about how to have GitHub-hosted docs work seamlessly when deployed to GitHub Pages, I agree that relative paths are the only thing that make sense in the context of canonical reference authoring.

**Comment by oprypin** [comment]
> At the very least, setting `site_url` should force local dev to happen under the same `/subdirectory` path

That is done now, https://github.com/mkdocs/mkdocs/pull/2424
