### ISSUE TITLE
Define foldable (i.e., collapsable) sections in large mkdocs pages

### ISSUE THREAD

**Issue by vthierry** [mkdocs/mkdocs#2399]
Hi mkdocs,
 
  In large pages it would be really great some sections to be collapsable like https://squidfunk.github.io/mkdocs-material/reference/admonitions/ but whole standard section
  The markdown syntax could be similar 
??? ### "title"
     contents
 with the section title managed in the table of contents.
 
 Would this possible ? I can help also to co-develop (i am not familiar with mkdocs but with underlying technos i am).

Thanks in advance.

**Comment by facelessuser** [comment]
There is already an extension that can do this: https://facelessuser.github.io/pymdown-extensions/extensions/details/#syntax. Then it is simply up to the theme to provide appropriate styling.

**Comment by vthierry** [comment]
Thanks for your kind and quick answer, Isaac.

Yes, indeed. But up to my best knowledge if i try something like

```
??? faq "### Subsection title to create a sub-section"
        Here comes the text
```

it does not work, does it ?

**Comment by waylan** [comment]
This is something which would be implemented as a Markdown extension (and apparently at least one already exists). Any styling can be defined via `extra_css`. Therefore, there is no changes to be made to MkDocs itself. For that reason I am closing this.

**Comment by facelessuser** [comment]
Not it doesn't, I think I understand better what you are driving at now. While you can get away with some basic inline styling, block processors don't really touch the title. You can sneak in HTM as the title, and that will work:

```
??? note "<h2 id="myid">Subsection title to create a sub-section</h2>"
    Here comes the text
```

<img width="725" alt="Screen Shot 2021-05-08 at 10 12 54 AM" src="https://user-images.githubusercontent.com/1055125/117546103-ffdd5900-afe5-11eb-9d10-e8728d2504ea.png">

But you don't really get a collapsible section, more a collapsible box with a header for the title. Also, anytime you use raw HTML for a header, MkDocs won't see the header and it to the TOC 🤷🏻 .

In the end, you could maybe do this with some kind of extension, but again, your theme would need to add the appropriate styling.

**Comment by vthierry** [comment]
Thanks again Isaac, this completely clarifies the point. Best regards,

**Comment by facelessuser** [comment]
Granted you don't have to style details like a container and you could use a subtle style for sections, but the title not being seen by TOC is the big issue.

**Comment by vthierry** [comment]
Yes i confirm, i will think about this and share a solution if any.

On track could be to define a piece of javascript code on the resulting html, seems manageable because the html output looks well structured ... i'll need a few days to think and work on it ....

**Comment by vthierry** [comment]
Hi again Isaac, i come to an acceptable solution using a javascript hack  https://gitlab.com/mooc-nsi-snt/portail/-/blob/master/docs/assets/make_foldable.js adding a line of the form
<script src="./assets/make_foldable.js"/>
at the end of each *.md file and obtaining a result like that: https://mooc-nsi-snt.gitlab.io/portail/1_vous.html 

I gonna have no idea how to propose a clean mkdocs plugin if of any help, but i will ask a colleague in case

Best regards,

**Comment by facelessuser** [comment]
Glad you figured something out that works for you. Sometimes you just need something specialized for your own personal needs.
