### ISSUE TITLE
links go to broken page

### ISSUE THREAD

**Issue by thecraftman** [mkdocs/mkdocs#2415]
On our docs, when I click on this link: https://docs.axiom.co/data-shippers/api

and I click on anything under I click on any link under "Data Shippers" on the left nav, I go to a broken page. 

Still trying to figure out what causes this issue. 

Does it have to do with the relative path of the site overall? 

@waylan 

<img width="1440" alt="Screenshot 2021-05-19 at 16 59 43" src="https://user-images.githubusercontent.com/24816990/118845419-aa495c00-b8c3-11eb-9c26-6bd61197d3d7.png">

**Comment by BetterThanReal** [comment]
It looks like the navigation works now?
