### ISSUE TITLE
Is there a way to change the edit branch away from master?

### ISSUE THREAD

**Issue by xyeLz** [mkdocs/mkdocs#2416]
I apologize if I missed something in the documentation but when I select the pen to edit my page, it always tries to bring me to the "master" branch (which does not exist as we only have a main branch) which leads us to a GitHub 404 error page. Did I miss something here or has this not been addressed yet? Thanks!

**Comment by ktomk** [comment]
If you use a non-standard (mind the time of release) default branch on Github, you can not rely on the few _"known hosts (specifically GitHub, Bitbucket and GitLab) [that] the edit_uri is derived from the 'repo_url'"_ ([ref](https://www.mkdocs.org/user-guide/configuration/#edit_uri)) and you have to set the `edit_uri` yourself. 

This is also true if you use a non-standard "docs" directory.

~~~
repo_name: ktomk/pipelines
repo_url: https://github.com/ktomk/pipelines
edit_uri: ./edit/master
~~~
(Example: non-standard documentation root in a Github repository, docs folder is project root and default branch is master)

In your case you should adopt the values according to your repository, the `edit_uri` might be something like `./edit/main/docs` in your case.

**Comment by oprypin** [comment]
That answer is correct.
Myself, I use this for GitHub, as I find it less intrusive:

```yaml
edit_uri: blob/master/docs/
```
and indeed you can set any other branch than `master`
