### ISSUE TITLE
FEATURE REQUEST: Add drop down ability to navigation items

### ISSUE THREAD

**Issue by xyeLz** [mkdocs/mkdocs#2417]
Hi there! It would be great if the ability to drop down navigation items existed.

**Comment by oprypin** [comment]
I don't know what you're talking about. This is theme-specific. And the "mkdocs" theme does indeed implement navigation as dropdowns. Check out https://www.mkdocs.org/

**Comment by oprypin** [comment]
Feel free to provide further information, but right now there's nothing clear to do here
