### ISSUE TITLE
Performance of mkdocs serve is unreasonable

### ISSUE THREAD

**Issue by BetterThanReal** [mkdocs/mkdocs#2418]
Using the current version of MkDocs on Windows 10 with Python 3.9, I notice 10% to 20% CPU utilization, continually, when running `mkdocs serve` on a small project with less than 10 files.

For that much continuous CPU utilization, I would expect to be earning money from a crypto-miner.

**Comment by facelessuser** [comment]
Work is currently being done to implement a "better" serve: https://github.com/mkdocs/mkdocs/pull/2385.

I'm not certain as to how this new approach affects CPU utilization, but it may or may not be better. You are welcome to experiment with that branch if you like.

**Comment by waylan** [comment]
Closing this as a duplicate.

By the way, I suspect the continuous CPU utilization is because of the file watcher, which is constantly checking for changes to the files so it can auto reload them. You can disable that with `--no-livereload`.
