### ISSUE TITLE
Option to run `gh-deploy` and see diff prior to commit.

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#242]
When using `mkdocs gh-deploy` I'd sometimes like to be able to review the changeset to the `gh-pages` branch first, to ensure it all makes sense.

Right now it just commits and pushes everything. It'd be good if we could have a "build in `gh-pages` branch but don't commit/push" or similar.

**Comment by pawamoy** [comment]
IMO such diffs are really hard to read. Lots of files being renamed, added or deleted, mostly HTML, sometimes minified... 

The docs currently warn that you'll not be able to review before the site is pushed:

> Be aware that you will not be able to review the built site before it is pushed to GitHub. Therefore, you may want to verify any changes you make to the docs beforehand by using the build or serve commands and reviewing the built files locally.

I think this warning is enough.

My comment being the first one on this ticket from 9 years ago, without a single emoji reaction, shows that there's not a lot of interest for such a feature! I'd therefore say we can close this :slightly_smiling_face:
