### ISSUE TITLE
Re-building w/ symbolic links stopped working, regression after #2385

### ISSUE THREAD

**Issue by ktomk** [mkdocs/mkdocs#2425]
Since a444c43 in master using the local development server via `mkdocs serve` updating files that are symbolically linked is not triggering to rebuild (and therefore not reloading browser tabs).

On first glance this is due to the switch to watchdog for detecting file-system changes which needs more guidance to handle this file-type.

Preparing a PR with a patch.

Ref: a444c43474f91dea089922dd8fb188d1db3a4535

**Comment by ktomk** [comment]
@waylan this issue might need reopening, I don't know if its me and late, but the new changes doe not work the slightest for me :/ . Test setup is unchanged and I re-test according to my earlier notes, just symlinks don't work.

I have to re-check tomorrow with a pair of fresh eyes.

**Comment by waylan** [comment]
> 
> 
> @waylan this issue might need reopening, I don't know if its me and late, but the new changes doe not work the slightest for me :/ . Test setup is unchanged and I re-test according to my earlier notes, just symlinks don't work.
> 
> I have to re-check tomorrow with a pair of fresh eyes.


Well, that is concerning. Currently this would be the only thing holding up the 2.1 release. I just resolved the last couple items on the milestone.

Could you provide a reproducible test which fails (but previously passed)?

**Comment by ktomk** [comment]
@waylan please find a reproducible test that shows the failure with current HEAD and before that demonstrates it works:

https://github.com/ktomk/mkdocs-test/blob/master/NOTES

I made the test as minimal as possible to demonstrate the issue.

The test-setup could be further minimized, it's duplicated, just not the mkdocs version to install.

**Comment by oprypin** [comment]
@ktomk Thanks for the report.
The relevant information that I [got out of it](https://github.com/ktomk/mkdocs-test/blob/01c2b048da306400128ba705107d089df3f64d14/Makefile#L36) is just: `ln -s ../README.md docs/README.md`.
Namely, relative symlinks break it.
I will follow up on that in https://github.com/mkdocs/mkdocs/pull/2438

**Comment by ktomk** [comment]
@oprypin that can totally explain it as I'm using only relative symlinks in my earlier tests. this is good news, I couldn't explain myself the results for two days.
