### ISSUE TITLE
Creating a custom CLI command

### ISSUE THREAD

**Issue by anatoly-scherbakov** [mkdocs/mkdocs#2428]
**Context.** I am developing a plugin to MkDocs which is fetching machine-readable information from documentation files and composes this information into a searchable in-memory graph database, for analytics, queries, and rendering inside pages.

What I would like to do is to create a command option like

```bash
mkdocs query 'SELECT * WHERE { ?page a octa:Page }'
```

**Problem.** Overall, developing an MkDocs plugin is a great experience, but I know plugins do not support changing MkDocs CLI interface. I've been trying to write something like this in my plugin code:

```python
from mkdocs.__main__ import cli, common_config_options, common_options

@cli.command(name='query')
@common_config_options
@common_options
def query_command():
    print(f'I will run SPARQL query for you here!!!')
```

but to no avail because, when CLI is generated, plugins haven't been loaded yet.

Is there at all a method to create a custom CLI command? Thanks!

**Comment by oprypin** [comment]
There is no way to do this currently.
See also: https://github.com/mkdocs/mkdocs/discussions/2345

**Comment by oprypin** [comment]
There is no direct way to do this currently.
See also: #2345

You can do a workaround - make the plugin intercept a magic environment variable, in that case do its thing and stop MkDocs by raising `SystemExit`. So this would look like
`MY_MAGIC_QUERY=foo mkdocs build`.

*Then* you could make the plugin's package provide its own executable entry point named `mkdocs_magic_query` which only takes its argument and calls the subprocess as above.

**Comment by anatoly-scherbakov** [comment]
I see. Thank you for the hint! I decided to just go and create my own executable command, as a more user-friendly choice.

**Comment by waylan** [comment]
When the Plugin API was first proposed, I had intended to add a way for plugins to provide their own commands. However, that never got implemented. There are a few factors which contributed to that.

1. Currently, all plugins are only available if they are specified in the config file for a project. This would require a break from that mold. While doable, it presents an additional challenge. How do we handle two separate plugins which both implement the "foo" subcommand? Currently, the user would simply specify one of them in the config file. That doesn't work you need to load the plugin before the config file.
2. The plan was to eventually break the existing `gh-deploy` command out into a plugin which would be a subcommand of a more generic `deploy` command (`mkdocs deploy github [options]`). The assumption was that the new API would be developed in conjunction with this change. However, I just never got to it.

In the end, various third party library have built wrappers for various reasons and all of them have simply provided their own standalone commands. If we ever get to adding an API, any of these packages can always add on commands for integrated commands.
