### ISSUE TITLE
How to hide page title?

### ISSUE THREAD

**Issue by paulo-coutinho** [mkdocs/mkdocs#2429]
Hi,

How to hide page title?

If i remove "# Home" a new title appear with the name of file.

![image](https://user-images.githubusercontent.com/395096/120093173-d5675300-c0ee-11eb-8729-a4cf3e7d5b8e.png)

How i can remove it without hacks?

Thanks.

**Comment by waylan** [comment]
There are four ways to define a page tile as documented [here](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data). You could use either one of the first two of those options.

> 1. A title defined in the nav configuration setting for a document.
> 2. A title defined in the `title` meta-data key of a document.

In either case, do not include the title in the body of the document. So long as you have defined it in either the nav configuration for the meta-data for the page, the filename will not be used as the title.

Finally, I am moving this to a discussion as it is a support request.
