### ISSUE TITLE
Support embedded video

### ISSUE THREAD

**Issue by tobegit3hub** [mkdocs/mkdocs#243]
Now I try to add `<embed>` for videos in my pages. But it seems not to work.

**Comment by TurboCoder** [comment]
If you have your theme locally, and you're not using one of the defaults (if you have one of the defaults in a folder locally, there's no problem), you can simple transform everything with what you need.

In my case, i just generate the video based on an image, taking advantage of the alt and the src.

Key             | Description                                                                                |
--------------- | --------------------------------------------------------------------------------- |
ALT            | Meaning is a youtube video. `YOUTUBE`                                 |
SRC           | Id of the Video. `Will be the SRC in the IFRAME`                     |

```md
![ALT](SRC)
```

In base.js i just added this:
```javascript
// Load Videos in the Docs
$(document).ready(function () {
    $('img[alt="YOUTUBE"]').each(function () {
        var id = $(this).attr('src').substring(3, $(this).attr('src').length);
        var video = '<iframe style="width: 100%;height: 450px;" src="https://www.youtube.com/embed/' + id + '?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>';
        $(this).replaceWith(video);
    });
});
```

and in the anything.md
```md
![YOUTUBE](LRLQE2N0DKc)
```

**Comment by tylerlong** [comment]
The following works for me: 

```html
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
Your browser does not support the video tag.
</video>
```

I am writing documentation on readthedocs.org and chose mkdocs as the text engine. I found that I can write html tag directly in markdown.

**Comment by jediwarrior77** [comment]
Make mkdocs support video you brain dead rats it's 2020. What are you expecting 2100? Just wasted 3 hours on this pathetic open source shit.

**Comment by soulless-viewer** [comment]
So, now there is a simple solution:
[MkDocs Video plugin](https://github.com/soulless-viewer/mkdocs-video)

**Comment by oprypin** [comment]
Please don't use that plugin and instead just write HTML as shown right above.

Otherwise you'll just be limited to the arbitrary set of things that the plugin chose to implement.

E.g. causing confusion here https://github.com/mkdocs/mkdocs/discussions/3120

**Comment by soulless-viewer** [comment]
@oprypin 

Some MkDocs users don't want to waste time on their own implementation with HTML. It was for them that a plugin was created that covers **most of the details** regarding the video. So, I wouldn't be so critical.

Another pros of using the plugin is aesthetics. With the plugin, the user don't need to make a dirty mix from a clear md. It probably seems superfluous to someone, [right](https://pryp.in/)?

**Comment by Carunga** [comment]
@soulless-viewer 
I think I agree, I like using the plug-in and pure markdown way. Besides aesthetics and ease of use this maintains compatibility with your markdown-write of choice.

**Comment by Carunga** [comment]
Support for the loop (and some more) attributes has been added to the plugin.

**Comment by soulless-viewer** [comment]
> Support for the loop (and some more) attributes has been added to the plugin.

Thanks @Carunga for highlighting that 🫡
