### ISSUE TITLE
Allow navigation tree to diverge, then merge back

### ISSUE THREAD

**Issue by lifehackerhansol** [mkdocs/mkdocs#2432]
I am not entirely sure how to put this in words, but essentially there would be a page where it splits off into two different pages, but right after it would merge to one page. 

In my case, I have the structure of a certain guide, but there is one step in the guide that requires a different method depending on what software version the reader has. After said step in the guide, whichever one reader went through, they would then be directed back to the main guide path, where afterwards the steps are identical again.

Currently a mess of a repository, but I have my current example here: https://lifehackerhansol.github.io/Guide-3DS_mkdocs/user-guide/get-started

Here on this page, one would pick "Soundhax" or "Browser", then after that they would loop back to the "finalizing setup" page. Given that the page is identical in content, it wouldn't make sense to maintain a copy of them. Pressing "Next" in the "Soundhax" page leads them to the "Browser" page instead of "Finalizing Setup" as intended.

How would I go about this?

**Comment by oprypin** [comment]
MkDocs really wouldn't be able to provide a universal way to do this. The need is too specific.
A plugin is definitely possible to make, but I don't know any such existing plugin.
If you were to write a plugin, you'd need to manipulate `Page` objects of the `nav` and change their `next_page` property and such. Perhaps similarly to this code
https://github.com/oprypin/mkdocs-section-index/blob/bf8d0fd52825fd536f9fb47268d28f1eaac21b1b/mkdocs_section_index/plugin.py#L60
https://www.mkdocs.org/dev-guide/themes/#pagenext_page
