### ISSUE TITLE
GET /%E8%AE%A1%E7%AE%97/HTTP/1.1" code 404  does not support Chinese name md documents

### ISSUE THREAD

**Issue by quinnhao** [mkdocs/mkdocs#2463]
Questions are as follows:
I have encountered a problem when using Chinese to set the navigation, click on the navigation bar to prompt the page to display: 404-Not found

The CLI error is as follows: "GET /%E8%AE%A1%E7%AE%97/ HTTP/1.1" code 404

The mkdocs.yml configuration file is as follows:
```
site_name: My Docs
site_url: https://example.com/
theme:
name: material
nav:
- 首页: index.md
- 测试1: 测试1.md
- 测试2: 测试2.md
```

I tried windows system, ubuntu system, mac system, and I can’t quote markdown documents with using Chinese to set the navigation but I see other people’s blogs support Chinese, but theirs is not the latest version, the author is in the latest version. Do you choose not to support Chinese markdown documents?  

I checked the historical problem records, but did not find a clear instruction, if you know, please help me, thank you very much

**Comment by oprypin** [comment]
Sorry, my recent change broke serving files with non-English letters. The problem is not only for Chinese. I have suggested a fix for the code.

**Comment by quinnhao** [comment]
> Sorry, my recent change broke serving files with non-English letters. The problem is not only for Chinese. I have suggested a fix for the code.

Thank you, hope to solve this issues

**Comment by oprypin** [comment]
The fix is now included in the [latest release](https://github.com/mkdocs/mkdocs/releases/tag/1.2.2).

cc @144026 @EarthMan123

**Comment by Extious** [comment]
Why I still have this problems today ?
Here is my environment:
![Image](https://github.com/user-attachments/assets/23c7fd24-bad8-4dfe-806e-0d311bc27cf2)
