### ISSUE TITLE
update all jquery usage to remove quarantining

### ISSUE THREAD

**Issue by chris-twiner** [mkdocs/mkdocs#2467]
per #1763 the jquery versions used in *both* the readthedocs and the mkthdocs themes.  Locations:

  - https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/js/jquery-1.10.2.min.js
  - https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/js/jquery-2.1.1.min.js

This is triggering quarantines on mkdocs for any group using NVD (6.1 rating) or NexusIQ (9.8) rating.

I'll attempt to make a pull against this issue in the next days.

**Comment by oprypin** [comment]
And immediately reopening because this still applies to the "mkdocs" theme.

**Comment by squidfunk** [comment]
Resolved via #3649 🚀 Will be part of 1.6.0.
