### ISSUE TITLE
Generate reference index for the full documentation

### ISSUE THREAD

**Issue by fedelibre** [mkdocs/mkdocs#247]
Surprisingly, I coulnd't find anything about indices in this tracker nor in the roadmap.
Are you going to implement indices in the future? I think that it is a pretty basic feature for a doc tool.
I know at least two projects that support indices:
- [Sphinx indices](http://sphinx-doc.org/markup/misc.html?highlight=index#directive-index)
- [texinfo indices](http://www.gnu.org/software/texinfo/manual/texinfo/html_node/Indices.html#Indices)

I'd like to convert an existing documentation from texinfo to markdown/mkdocs and this feature would be probably a must for the switch.

**Comment by waylan** [comment]
In theory, this should now be possible with the [theme.static_templates][1] config setting. In the config do:

```yaml
theme:
    name: mkdocs
    static_templates: genindex.html
```

Then create a template named `genindex.html` which steps through the pages in the nav and generates an index which would be available at `/genindex.html`. The template could be part of a theme, or added to the [theme.custom_dir][2] by the user. A theme could also include the template by default (not requiring the user to list it in the config) by listing it under the `static_templates` setting of [mkdocs_theme.yml][3].

There may still be a few things missing however:

1. A way to include the page in the nav without theme customization (using block inheritance, etc.)
2. There may be a shortage of necessary data in the template context to accomplish this.
3. If we officially support this, it may make sense to include a working template in the built-in themes (which may or may not be included by default suing the  `static_templates` setting of `mkdocs_theme.yml`).

I'm leaving this issue open until the above are resolved.

[1]: http://www.mkdocs.org/user-guide/configuration/#static_templates
[2]: http://www.mkdocs.org/user-guide/configuration/#custom_dir
[3]: http://www.mkdocs.org/user-guide/custom-themes/#theme-configuration

**Comment by waylan** [comment]
This could also be addressed fully by a Plugin. Probably the easiest way to work around the issues mentioned above. If anyone wants this before we get to it, then feel free to implement a plugin and we might just use that as the default way to support the feature.

**Comment by waylan** [comment]
I have a working example [here](https://github.com/waylan/mkdocs-nature/blob/master/nature/sitemap.html). Note that the relevant config is [here](https://github.com/waylan/mkdocs-nature/blob/master/nature/mkdocs_theme.yml#L3-L4).

Finally, with #1504 the rendered page can be included in the nav. Therefore, all of the pieces to implement this via a theme are in place. That being the case, I'm closing this.
