### ISSUE TITLE
after mkdocs build，can't use serach function

### ISSUE THREAD

**Issue by m986883511** [mkdocs/mkdocs#2470]
![image](https://user-images.githubusercontent.com/34444109/122722302-1db80200-d2a4-11eb-98cd-e237083e9470.png)
as  you  can see the error.

the web see just ok, but can not use search, how to fix it?

**Comment by m986883511** [comment]
the probrom like https://github.com/mkdocs/mkdocs/issues/2191;
if I can set chrome flag, how to fix it ?
can someone help me.

**Comment by squidfunk** [comment]
See https://github.com/mkdocs/mkdocs/issues/2191#issuecomment-699893090. You can use `localsearch` and `iframe-worker`.

**Comment by m986883511** [comment]
> See https://github.com/mkdocs/mkdocs/issues/2191#issuecomment-699893090. You can use `localsearch` and `iframe-worker`.

thank you
