### ISSUE TITLE
Lunr updates and language support

### ISSUE THREAD

**Issue by randomJoe211** [mkdocs/mkdocs#2472]
@waylan Lunr has 4 releases recently, added official support for the Chinese language, and fixed some issues. Could you please merge the latest Lunr codes in a new version of mkdocs?

Using jp to search for Chinese characters really has some crazy issues...

Thank you so much!

**Comment by queensferryme** [comment]
Seconded! Really need official support for Chinese.

**Comment by noodlefighter** [comment]
+1

**Comment by FengUyu** [comment]
+1

**Comment by cooper-lzy** [comment]
Can we solve this problem as soon as possible? I need it!

**Comment by squidfunk** [comment]
Adding Chinese language support is not possible at this time, see https://github.com/mkdocs/mkdocs/issues/2509#issuecomment-882689383

**Comment by randomJoe211** [comment]
> Adding Chinese language support is not possible at this time, see [#2509 (comment)](https://github.com/mkdocs/mkdocs/issues/2509#issuecomment-882689383)

Thank you for looking into this anyway! Let's hope that a new way comes up as the solution...
