### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by soulless-viewer** [mkdocs/mkdocs#2475]
Hello Team.
Have there been any updates about video support?
How can I add a video on a MD page?

Many years have passed since this request was created...
[Issues-243](https://github.com/mkdocs/mkdocs/issues/243)

**Comment by oprypin** [comment]
Well indeed this issue is just a duplicate of #243
There is nothing that MkDocs should do about video, you can just insert the wanted HTML into your Markdown sources.

**Comment by soulless-viewer** [comment]
So, now there is a simple solution:
[MkDocs Video plugin](https://github.com/soulless-viewer/mkdocs-video)
