### ISSUE TITLE
Add option to search additional documentation paths 

### ISSUE THREAD

**Issue by chris-twiner** [mkdocs/mkdocs#2476]
When embedding Maven site / javadocs etc. it'd be great to allow searching of these embedded documents as well.

**Comment by chris-twiner** [comment]
Creating a wrapper plugin with this functionality seems to break material and ends up duplicating much of the code anyway so it makes more sense to add this to the base plugin.

**Comment by ms-lolo** [comment]
I would also love to have this functionality! We generate a lot of API docs using `sphinx` and would love to index the entire site together for better searching experiences. Our `sphinx` docs end up being a set of html files we copy in as a sub-folder of the greater `mkdocs` site so I would love to tell `mkdocs` to go scan an extra folder of html files.

**Comment by chris-twiner** [comment]
I've got code an implementation with meta page boosts, tags and external paths that works great but it definitely has to extend the core project, I've not found a way around the dependency on the search plugin in everything from material to mike.  It'll take some time to get a pull request together unfortunately.

**Comment by ultrabug** [comment]
@chris-twiner even if you do not make a PR, can you gist the code and share it so it can be looked at?

**Comment by pawamoy** [comment]
This can probably be implemented as a [hook](https://www.mkdocs.org/user-guide/configuration/#hooks) or plugin, by updating the `search_index.json` file in the [`on_post_page`](https://www.mkdocs.org/dev-guide/plugins/#on_post_page) or [`on_post_build`](https://www.mkdocs.org/dev-guide/plugins/#on_post_build) events. We'll close as out of scope.
