### ISSUE TITLE
Directory subsections

### ISSUE THREAD

**Issue by tripleo1** [mkdocs/mkdocs#2480]
i'm using nav nad I want to make a subsection that includes all the entries in a certain directory.

So like:

```
nav:
  - Subsection:
    - directory/
```

And under subsection, there would be all my posts from that directory, sorted, of course.
I don't think this is possible now, it only works when there is no `nav` to my knowledge.

Am I correct or would this be a new feature?

**Comment by oprypin** [comment]
There is no such feature.

[mkdocs-literate-nav](https://github.com/oprypin/mkdocs-literate-nav) plugin has this exact feature, though.
https://oprypin.github.io/mkdocs-literate-nav/#hybrid-nav

**Comment by tripleo1** [comment]
Thanks, I (over) looked that the other day to see if there was a feature 
like I was describing included, but it appears I will have to use this 
plugin.
