### ISSUE TITLE
HighlightJs in a restricted env

### ISSUE THREAD

**Issue by rwanito** [mkdocs/mkdocs#2482]
Hi !
I would like to use highlightjs in an offline environment.
But, by default it's cloudfare the CDN.
Is it possible to pack a basic version of this extension when we are offline ?

Thanks !

**Comment by oprypin** [comment]
This is a duplicate of #2482 - you can present your argument (and thumbs up) there instead.

**Comment by oprypin** [comment]
This is a duplicate of #2171 - you can present your argument (and thumbs up) there instead.
