### ISSUE TITLE
Different generated markup from serve and gh-deploy

### ISSUE THREAD

**Issue by ThomasArdal** [mkdocs/mkdocs#2488]
I have an issue where building my MkDocs site with a local `serve` and a `gh-deploy` running on GitHub actions produces different results.

The problem occurs when I embed markdown inside HTML elements like this:

```html
<div class="tab-content tab-content-tabbable">
  <div role="tabpanel" class="tab-pane active" id="setup2">
Add the following code to your `WebApiConfig.cs` file:
  </div>
</div>
```

When inspecting the output locally with `serve` the generated markup inside the `div` looks like this:

```html
<p>Add the following code to your <code>WebApiConfig.cs</code> file:</p>
```

This is what I want. When looking at the output generated from `gh-deploy` the generated markup inside the `div` looks like this:

```html
Add the following code to your `WebApiConfig.cs` file:
```

No `p` element and the `WebApiConfig.cs` part is not converted to a `code` element. It looks like the content inside the markup simply isn't converted from markdown to HTML.

Can you help figure out what is going on there?

I'm running on the following versions:
mkdocs-1.2.1
pymdown-extensions-8.2
markdown-fenced-code-tabs-1.0.5

Also, there's a verbose output from a build available here: https://github.com/elmahio/documentation/runs/3016788211?check_suite_focus=true

**Comment by oprypin** [comment]
Locally you have an old version of Python-Markdown, remotely you're always installing the latest version. The behavior you're complaining about as "bad" is the new and correct behavior. The relevant change is https://github.com/Python-Markdown/markdown/pull/803

To avoid surprises with dependency management, you should use a requirements file with pinned versions. As shown in the following guide (note that the rest of that site is not relevant at all): https://mkdocstrings.github.io/crystal/quickstart/python-dependencies.html

**Comment by ThomasArdal** [comment]
@oprypin Thank you very much for clarifying, Oleh. Just to make it clear, I was not complaining and/or suggesting something was "bad". Only looking for help ;)

Do you know if markup inside HTML elements is no longer supported with the new Python-Markdown? As you said, rolling back to the old version fixed my issue. But running on the old package is not a sustainable way to go, for obvious reasons.

**Comment by oprypin** [comment]
I don't know off hand exactly how it works. But you'll definitely need to enable the `md_in_html` extension. Some things to try would be:
* add an attribute to the top-level tag, e.g. `<div markdown=1`
* add this attribute to all enclosing tags
* add an empty line before and after Markdown (the latter is what helps when using GitHub's markdown)

**Comment by ThomasArdal** [comment]
Thank you so much. Will play around with your suggestions.
