### ISSUE TITLE
extra_css file not showing up in generated html files

### ISSUE THREAD

**Issue by inouthack** [mkdocs/mkdocs#2500]
using mkdocs ```bootstrap4``` theme.

in order to render the footer in a black background i have created a custom.css and added to mkdocs.yml file the following line
```
extra_css:
    - css/custom.css 
```

the content of custom.css is
```
footer.col-md-12 {
    background-color: black;
    color: white;
}
```

on generating the static site, there is no reference to ```css/custom.css``` in the generated html file

Couple of queries,
- will the custom CSS be rendered after the bootstrap4 <style> tag ?
- will the custom CSS fragment be part of <style> tag or referenced as src=css/custom.css
- is there a way to enable debugging beyond the usual ```--verbose``` option which just shows that the static content is copied

Thanks in advance for any pointers.

**Comment by oprypin** [comment]
Please provide a complete example site that shows the conditions in which this issue happens. It is up to you whether you want to share your real source site, or if you reduce it to a minimal example. But I need to be able to build it myself and observe the same issue.

I personally have done what you're describing and it always worked fine, so it's not possible that it's always broken, there has to be something special that you did.

If I have to guess what you did and spend time reconstructing such an example myself, that is a completely unsustainable form of providing free support. So I will not look into this unless an example is provided. Thanks for understanding.

**Comment by inouthack** [comment]
> Please provide a complete example site that shows the conditions in which this issue happens. 

Please find attached the complete code as learn.zip file, which i was working with to try and learn mkdocs+bootstrap4.

[learn.zip](https://github.com/mkdocs/mkdocs/files/6813096/learn.zip)

**Comment by oprypin** [comment]
OK I ran this and it adds the CSS just fine.

```bash
virtualenv venv
venv/bin/pip install mkdocs mkdocs-bootstrap4 mkdocs-minify-plugin
venv/bin/mkdocs build
```

`index.html` contains `<link href=css/custom.css rel=stylesheet>`

**Comment by inouthack** [comment]
@oprypin the only difference seen is

i'm using
mkdocs-theme-bootstrap4
https://pypi.org/project/mkdocs-theme-bootstrap4/

vs

you're using
mkdocs-bootstrap4
https://pypi.org/project/mkdocs-bootstrap4/

The latter page on pypi is barebone and gives the impression that the author has perhaps abandoned the project. Oh well !

**Comment by inouthack** [comment]
This note is to help anyone coming after me and facing the similar issue

the **mkdocs-bootstrap4** theme (used by oprypin) is incomplete (or maybe complete depending on the author). 

As a result

- the styling of the tables is not supported
- blockquotes will not work

If anyone wants to use proper styling as supported by bootstrap4, then i'd suggest using **mkdocs-theme-bootstrap4**
