### ISSUE TITLE
Language detected is wrong when using comments inside the block

### ISSUE THREAD

**Issue by luispcosta** [mkdocs/mkdocs#2517]
I've opened this ticket over at highlightjs and they suspect that this might have to do with mkdocs instead of highlightjs...

Whenever a code block contains code in comments, the CSS class(es) applied to the code block is of a different language which will naturally screw up the syntax and the visual apparence of the text.
I could reproduce this issue with, at least, objectivec and swift.

When writing:

![Screenshot 2021-07-22 at 09 12 50](https://user-images.githubusercontent.com/7049711/126608426-f01ba6c2-06eb-4000-b40e-867998192658.png)

And:

![Screenshot 2021-07-22 at 09 13 09](https://user-images.githubusercontent.com/7049711/126608463-efabeef2-5518-479d-b9b4-018924acecb1.png)

It produces the wrong highlighting:

![Screenshot 2021-07-22 at 09 14 10](https://user-images.githubusercontent.com/7049711/126608589-84f84698-01bd-4b51-9057-d70c9a88a8f7.png)

If we take a look at the classes added:

For the Objective-C block:
![Screenshot 2021-07-22 at 09 17 38](https://user-images.githubusercontent.com/7049711/126609042-e43cbd0f-a9f2-4c93-b44d-478c42d57c6e.png)

It's identifying the block as an SQL code block...

For the Swift Block:
![Screenshot 2021-07-22 at 09 18 04](https://user-images.githubusercontent.com/7049711/126609093-7e0a8693-7f42-4f47-9eb1-a448c3758744.png)

It's identifying the block as a bash code block...

If we remove the comments from the markdown

![Screenshot 2021-07-22 at 09 21 17](https://user-images.githubusercontent.com/7049711/126609552-7e6788a6-efcb-4d5e-8a6a-aab0ee48ea22.png)

**Expected behavior**
I expected the code blocks to appear correctly with the comment syntax.

**Additional context**
* I'm using mkdocs version 1.0.4 and pymdown-extensions 7.1 and Markdown 3.2.2.

**Comment by oprypin** [comment]
> they suspect that this might have to do with mkdocs instead of highlightjs...

Where did they say that?

From my surface knowledge of the integration, it shouldn't be possible for MkDocs to affect this choice.

And, what MkDocs theme is this?

Worth pointing out:
The HTML with classes already added is not actual HTML, it's the DOM at runtime already after modification by highlightjs. To them you should probably provide HTML from the page source, before such modifications.

I will not be able to look into this issue soon, but I will look eventually. Though as I said, I don't expect to find anything.

If you want to try to pin down the issue yourself, you should try manually using highlightjs (according to their instructions) by adding it to a new HTML page that also includes the same highlightjs version as your current theme. (and then, even nicer, also compare that with the latest highlightjs)

**Comment by facelessuser** [comment]
The real question is what does the raw HTML source look like? Not what you see in the browser inspector after highlightjs is done covering the code block.

If the raw HTML code looks exactly as it should for highlight.js, then it is their problem. If not, then we would have to dig deeper.

**Comment by luispcosta** [comment]
I found what the problem was. I was mixing highlight.js with other pymdownx extensions :) There is no issue with with mkdocs at all, sorry for the false alert.
