### ISSUE TITLE
Macros in Snippets does not work

### ISSUE THREAD

**Issue by randomJoe211** [mkdocs/mkdocs#2518]
I put some Macro variables in Snippets in the base_path, the Snippets works but the variables cannot be correctly parsed. Looks like mkdocs cannot deal with Macro variables in Snippets.

Please take a look into this issue. Thank you!

**Comment by oprypin** [comment]
OK first of all, what is "Snippets" and what is "Macro variables"? I can only guess that this is about some plugins, which main MkDocs repository is not concerned with (so, closing this issue). If you're hoping to get any help with them, you need to super carefully explain every such external concept, in addition to always providing a reproducible example, with what result you got and what result you expected. As is, this one-sentence "issue" report is insultingly insufficient.

**Comment by randomJoe211** [comment]
Sorry for the rudeness. I was still updating the description...should have been more careful while editing the issue description.

Macros means the mkdocs-macros-plugin: https://mkdocs-macros-plugin.readthedocs.io/en/latest/
Snippets means the PyMdown Snippets extention: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/

**Comment by oprypin** [comment]
As I understand, this is about the order of execution between the plugin and Markdown in general. The Macros plugin first, then Markdown. It would definitely make sense that it doesn't work. (specifically, if Macros can generate Markdown which then generate Macros, ..... that would not be a sound design)
You can ask for help in mkdocs-macros-plugin. But still, you'll need to provide a full example with full contents of each file (also mkdocs.yml)

**Comment by squidfunk** [comment]
This might help:
https://squidfunk.github.io/mkdocs-material/reference/variables/#using-variables-in-snippets
