### ISSUE TITLE
Read The Docs theme has an "edit on github" link

### ISSUE THREAD

**Issue by DannyBen** [mkdocs/mkdocs#252]
I think it is less appropriate to have such a link in MkDocs context.

**Comment by bachp** [comment]
Why not make it more generic? Many alternative hosting sites like bitbucket and gitlab also allow online edition of files.
So the link could just be to the files on the respective git front-end.

**Comment by d0ugal** [comment]
Indeed, it is already somewhat generic, but it would need to be expanded.

https://github.com/tomchristie/mkdocs/blob/master/mkdocs/themes/readthedocs/breadcrumbs.html#L7-L11
