### ISSUE TITLE
Missing logo in RTD theme

### ISSUE THREAD

**Issue by marcelstoer** [mkdocs/mkdocs#2537]
How would we go about adding the site/project logo top left in the RTD theme? I am a little confused where the logo actually comes from in projects on RTD that _do_ have one (such as [this](https://psyplot.readthedocs.io/en/latest/)).

https://www.mkdocs.org/user-guide/choosing-your-theme/#readthedocs -> 'include_homepage_in_sidebar' states

> Note that the site name/logo always links to the homepage

However, that appears to be the only place a logo is mentioned at all. At https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html#adding-a-logo (and some [SO questions](https://stackoverflow.com/q/59215996/131929)) it appears configuring logo is unrelated to RTD or MkDocs but is actually targeting Sphinx.

**Comment by gh640** [comment]
I guess the page you referred (https://psyplot.readthedocs.io/en/latest/) is likely built not with `sphinx` not `mkdocs`:

https://github.com/psyplot/psyplot/blob/master/docs/environment.yml

Regarding `mkdocs`, I believe we can override theme templates to customize parts:

- https://www.mkdocs.org/user-guide/customizing-your-theme/#overriding-template-blocks
- https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/base.html#L87-L89

**Comment by marcelstoer** [comment]
> https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/base.html#L87-L89

Right, thanks for this pointer. With this hint I was able to find the counter-part in the upstream theme, looks quite a bit more involved.

https://github.com/readthedocs/sphinx_rtd_theme/blob/e3fba141e906e181cdb8999fa3b79f7a4aab4701/sphinx_rtd_theme/layout.html#L133-L169 and specifically

```html
          {%- if logo %}
            {#- Not strictly valid HTML, but it's the only way to display/scale
                it properly, without weird scripting or heaps of work
            #}
            {%- if sphinx_version_info < (4, 0) -%}
            <img src="{{ pathto('_static/' + logo, 1) }}" class="logo" alt="{{ _('Logo') }}"/>
            {%- else %}
            <img src="{{ logo_url }}" class="logo" alt="{{ _('Logo') }}"/>
            {%- endif %}
          {%- endif %}
```
