### ISSUE TITLE
Plugin Idea: Backlinks

### ISSUE THREAD

**Issue by Jatin794** [mkdocs/mkdocs#2546]
The idea: It would be pretty convenient to see connections if we could add a section "Pages linking here" automatically to every page. Ideally across different base folders in docs, but even just the same section would be great

**Comment by oprypin** [comment]
It's certainly a nice idea.

But, as an issue for MkDocs repository, this is out of scope.
I'll migrate this to a Discussion (sorry, that looks a bit abrupt)
