### ISSUE TITLE
Remove 'entry_point' references in documentation

### ISSUE THREAD

**Issue by hwittenborn** [mkdocs/mkdocs#2558]
I started using `setup.py` files so I would be able to start creating MkDocs plugins (literally haven't touched them before this), and the following text in the documentation was causing me some issues for quite a bit (emphasis added on the affect string; see https://github.com/mkdocs/mkdocs/blob/master/docs/dev-guide/plugins.md#entry-point):

> Plugins need to be packaged as Python libraries (distributed on PyPI separate from MkDocs) and each must register as a Plugin via a setuptools **entry_point**.

It would be helpful if that would be changed to `entry point` or `entry_points` so it doesn't make the reader think that `entry_point` should be the text to add to a `setup.py` file. Albeit there's multiple examples of `entry_points` being used right below it, it still got me lost for a bit regardless, and I thus thought it merited a fix.

**Comment by ultrabug** [comment]
That's a very good point, thank you for taking the time to share your experience @hwittenborn
