### ISSUE TITLE
restrict header levels in TOC

### ISSUE THREAD

**Issue by xin-jin** [mkdocs/mkdocs#256]
I only need headers of levels 1 or 2 to be shown in TOC (as TOC would be too long if I have many subsections), but it seems that by default levels 1-4 would all show up. Is there an option to remove headers with levels >2 from TOC? Thanks.

EDIT: moreover, if I use the theme "readthedocs", all headers seems to be "of the same level" in the TOC.

**Comment by ePirat** [comment]
Why was this closed? I think this is a very important thing, specially for large docs, I do not want to be all h3 and h4's to be listed in the TOC (using RTD theme, where this has really a annoying impact, since it makes the sidebar super long)

**Comment by tverbeke** [comment]
@tomchristie The issue is still present in version 0.16.0 - I agree with @ePirat that it may be better to reopen for the same reasons.

**Comment by waylan** [comment]
I can't read @tomchristie's mind, but I know I'm not interested in developing a complex theme with many config settings that meets every conceivable need. Users can create their own [custom themes][1] (there is already a few [third party themes][2] which address some of these needs), and/or [override bits and pieces][3] of the existing themes to create whatever custom functionality they want/need. There is not any additional action we need to take to make that possible for users so there is no need to leave this issue open.

[1]: http://www.mkdocs.org/user-guide/custom-themes/
[2]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
[3]: http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

**Comment by tverbeke** [comment]
IMHO toc depth is not really 'every conceivable need' at least for a documentation system, but I can understand opinions diverge. On the other hand, the fact that in the 'readthedocs' theme all headers seem to be 'of the same level' in the TOC (as reported by the OP) is not a feature request, rather a bug.

**Comment by waylan** [comment]
The issues with the `readthedocs` theme are covered by #588. You should follow up there if the specific issue you are having is not already mentioned.

**Comment by tomchristie** [comment]
I'm not really spending time on MkDocs lately myself, so \<shrug>.
I assume this only applies to the RTD theme right? The `mkdocs` theme only displays 2 levels.

**Comment by funkyfuture** [comment]
am i wrong or could this rather simply be solved by restricting the items by their depth when the context is populated? rather than tinkering on the template level.

**Comment by waylan** [comment]
@funkyfuture the TOC is obtained from the TOC extension to the Markdown parser. Therefore, the entire TOC is already created before MkDocs ever sees it. Whether it is then restricted when the context is created or in the template is simply an implementation detail.
