### ISSUE TITLE
Manually specify page order / respect order in index.md

### ISSUE THREAD

**Issue by shafr** [mkdocs/mkdocs#2561]
Hello, is there a way to use order of pages specified in **index.md** or some other way ? 
There are already existing github pages with an order that is defined in index.md
I want to use mkdocs for display, but want to avoid going through hundred of pages & adding indexes to each of them.

**Comment by oprypin** [comment]
This description is unclear. Please show a decent-sized sample of files in your site. Show what you have and show what you want and what logic you want MkDocs to follow to get there.

> There are already existing github pages with an order that is defined in index.md

-No idea what this sentence is about

> want to avoid going through hundred of pages & adding indexes to each of them.

So wait, you have fully specified the page order but don't want to fully specify the page order, is that right? Particularly you don't want to use *mkdocs.yml* for page order?

If I guessed correctly, it seems there is a **plugin that allows exactly this: https://github.com/oprypin/mkdocs-literate-nav**

**Comment by shafr** [comment]
Sorry, I wasn't fully awake at 5 am when I wrote this. 😴

I'm looking into 2 possibilities now:
* generate pdf for whole site, using pandadoc  & github actions
* render readable pages using mkdoc. 

I'll look into plugin  that you had mentioned and would test both approaches in my branch

**Comment by shafr** [comment]
Thank you for reply.
Here is example documentation repository:
https://github.com/undergroundwires/CEH-in-bullet-points

Here is how repo is organized currently:
```
.
├── 01-introduction
│  ├── data-leakage-backup-and-recovery.md
│  ├── hacker-types.md
│  ├── hacking-stages.md
│  ├── identity-access-management-(iam).md
│  ├── img
│  │  ├── cia-triad
│  │  ├── cia-triad.png
│  │  ├── functionality-usability-security-triangle.drawio
│  │  ├── functionality-usability-security-triangle.png
│  │  ├── non-repudiation.drawio
│  │  ├── non-repudiation.png
│  │  └── risk-matrix.png
│  ├── incident-management.md
│  ├── information-security-controls.md
│  ├── information-security-overview.md
│  ├── laws-standards-and-regulations.md
│  ├── network-security.md
│  ├── penetration-testing-phases.md
│  ├── penetration-testing.md
│  ├── physical-security.md
│  ├── risk-management.md
│  ├── security-policies.md
│  ├── security-threats-and-attacks.md
│  └── threat-intelligence-and-forensics.md
├── 02-footprinting
│  ├── email-footprinting.md
│  ├── footprinting-overview.md
│  ├── network-footprinting.md
│  ├── search-engines-and-online-resources.md
│  ├── website-footprinting.md
│  └── whois-geoiplocation-and-dns-interrogation.md
```

Navigation / order of pages follows logic in README.md:
![image](https://user-images.githubusercontent.com/26896695/132172787-733d9f59-8cf6-46cd-b1d6-a9ed7dda5af8.png)

I'm looking for a way to convert existing repo into mkdocs. I'm getting this as a result:

![image](https://user-images.githubusercontent.com/26896695/132173297-992e15b6-b3a1-465a-887c-8a4084aa73fa.png)

**Comment by oprypin** [comment]
So indeed you just need https://github.com/oprypin/mkdocs-literate-nav

**Comment by oprypin** [comment]
Of particular note:
* https://oprypin.github.io/mkdocs-literate-nav/index.html#customizing-nav_file
* https://oprypin.github.io/mkdocs-literate-nav/index.html#explicit-nav-mark

**Comment by shafr** [comment]
Great, thank you!
