### ISSUE TITLE
Disable the live reloading in the production server

### ISSUE THREAD

**Issue by linxianmiao** [mkdocs/mkdocs#2572]
I use command `mkdocs serve --no-livereload` in a production environment，hoping to disable the `livereload.js`, but this does not take effect.
I use `docker` to deploy the project. My environment is `ubuntu:20.04`, and mkdocs's version is 1.2.2.
![livereload.js](https://user-images.githubusercontent.com/83006176/133420160-49eba023-8d43-44e2-9709-9f309a043614.png)

**Comment by facelessuser** [comment]
Modocs serve is not meant for a production environment, it is only meant for testing.

**Comment by oprypin** [comment]
OK sooo the title is misleading.

> "Disable the live reloading"

Live reloading is indeed disabled and there's no bug as far as I can tell, you're only complaining that the JavaScript is still being injected. But there is no strong argument that it's very important to avoid injecting it, and the codebase is much simpler as is.
(Feel free to provide arguments and then perhaps it will make sense to reopen this issue)

> "in the production server"

MkDocs doesn't ship with any "production server". In production you'd be better off with almost literally any other server, after a plain `mkdocs build`. The most similar (but still pretty bad) alternative would be `python3 -m http.server`.

**Comment by linxianmiao** [comment]
@oprypin That is what I mean, I feel sorry for my poor English!
