### ISSUE TITLE
Problems with GIT LFS appear as broken images

### ISSUE THREAD

**Issue by Anselmoo** [mkdocs/mkdocs#2577]
## Problem:
---

-  `*.png` images versioned with [GIT-LFS](https://git-lfs.github.com/) are broken link in my GitHub-pages, but fine in Github markdown itself.
-   `*.png` images versioned with regular git runs fine both fine; [like](https://anselmoo.github.io/spectrafit/examples/example1/)

## Question:
---

Is there any workaround for how to use Git LFS in `mkdocs`

![image](https://user-images.githubusercontent.com/13209783/133633929-16920dfc-79eb-42ff-b627-b0f3cf9aa77d.png)

thx in advance

**Comment by oprypin** [comment]
I don't know about Git LFS but I'd assume that it shouldn't matter. MkDocs just looks at the local disk and uses what is there.

Could you provide all steps to reproduce this issue, or an example repository?

**Comment by Anselmoo** [comment]
Sorry @oprypin, I finally found the issue is related to github pages. [https://github.com/git-lfs/git-lfs/issues/3498](https://github.com/git-lfs/git-lfs/issues/3498)
