### ISSUE TITLE
Consider using omegaconf while loading yaml files

### ISSUE THREAD

**Issue by sugatoray** [mkdocs/mkdocs#2586]
Omegaconf (github: `omry/omegaconf`) library adds extra flexibility to reuse defined fields in a yaml file as variables, while defining other fields. Also, you could use "resolvers" which are like `jinja2` filters to your yaml fields. 

All you would need is to place `omegaconf` to read in the yaml files (eg. `mkdocs.yml`).

- Omegaconf: https://github.com/omry/omegaconf

**Comment by oprypin** [comment]
Mm sorry, this is rejected, at least preliminary. It's not good when configuration is *too* flexible. Further comments are welcome.

**Comment by sugatoray** [comment]
@oprypin Hi, I didn't mean to make the configuration too flexible. But I was pointing to providing a mechanism to re-use previously defined field values, while defining other fields in `mkdocs.yml`. Please feel free to ask more questions. I believe that there was a gap in communication. And if you could see my point, perhaps you will find enough reason to consider this as a feature request.

**Comment by oprypin** [comment]
@sugatoray I think I see your point, I just don't see enough appeal for the average MkDocs site.
The most likely thing to convince me would be an amazing example of a realistic MkDocs config where this would be *so so* useful and clearly showing a normal config to be inferior. Note here that e.g. merely removing some duplication isn't automatically considered superior, as it's also more complicated to learn, which is a downside.

**Comment by sugatoray** [comment]
@oprypin Ok, I see your point here. Let me do some thinking on what a good compelling example could look like.
