### ISSUE TITLE
[Request] new_uri and button

### ISSUE THREAD

**Issue by Lombra** [mkdocs/mkdocs#2593]
Would be great if, in addition to the edit URI and accompanying button, there was one for adding new pages.

Preferably there would be a way to add a page for any given category.

**Comment by pawamoy** [comment]
What do you mean by "category"? Also, how would that URI be used in a given theme? Did you envision something like a "New page" button or link somewhere? Lots of questions here, it would help if you could give a concrete example :)

**Comment by Lombra** [comment]
A button or link somewhere, indeed. I just noticed I failed to include the word "button" after "accompanying".

Not sure what I was thinking when I wrote "category"! Folder is what I meant. So, passing the path to the `new_uri` (`create_uri` makes more sense probably?), just like `edit_uri` does.

Don't know how it would look, exactly. I suppose it depends on your navigation configuration. I'm not too familiar with MkDocs yet, but I started right away with the Material for MkDocs theme, which has all the folders and pages on the left by default. In that case I imagined a small + button on each folder. It might not make sense for other themes or configurations, or become too cluttered. Another option could be to have a single "global" button that just passes the path of the current page.

I've been searching for a good wiki/documentation platform for ages. The main downside of MkDocs for me is that it doesn't include its own editing facilities. The `edit_uri` parameter works well enough for editing existing pages, but I need a way to quickly create new pages, too.

**Comment by pawamoy** [comment]
Hmmm, the problem is that MkDocs is not meant for building wiki-like, interactive platforms. It's a static site generator.
I stumbled upon [wiki.js](https://js.wiki/) the other day which could be what you're looking for.

**Comment by Lombra** [comment]
Sure, I get that. I don't expect any editing facilities to be integrated, just a link to an external editing platform, as with `edit_uri`. I thought that since `edit_uri` is a thing, something like this wouldn't be too far fetched.

Otherwise I might look into implementing it as a plugin or something. Haven't looked into what plugins are capable of.

**Comment by oprypin** [comment]
At first glance, I'd say that this is squarely in plugin territory. But uh just at first glance.
*Unfortunately*, even if the plugin exposed such a property, themes would have no awareness of it. That's besides each theme clearly needing to make a decision on how to design such a button and where to put it. On top of all that, even if the plugin took up the work of trying to adapt each theme itself (assuming non-cooperativeness from external themes), MkDocs plugin system doesn't even have tools to accomplish that in a good way. I have run into this problem and only came up with a bit of a hack (though it is implemented quite reliably): https://github.com/oprypin/mkdocs-section-index/#implementation-within-themes -- in any case, this particular plugin would the best starting point for making a plugin for *this* request.

Or let's say if this feature *is* added to MkDocs core. Then each external theme would instantly become outdated or broken from not expecting this feature. So also maybe not very good.

So, with all this, I don't think this request is going to happen, at least not soon. I personally am not willing to go through the described upheaval myself :)

---

As for doing this just for yourself, I think the easiest bet would actually be to directly mod the theme.
https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
You certainly could hardcode some URL tweaking within Jinja logic.

> started right away with the Material for MkDocs theme

> In that case I imagined a small + button on each folder.

Seeing as the vast majority of the work in that case is up to the theme, and that MkDocs core support is needed merely to make the implementaton "non-hacky", *and* that MkDocs team generally  has no control over mkdocs-material, I am more certain that it's in your best interest to not pursue this feature request within MkDocs itself, but do something about the theme just for your own use case.

**Comment by squidfunk** [comment]
IMHO MkDocs is not a CMS.

**Comment by klml** [comment]
As already mentioned, mkdocs is not a CMS. Your "CMS" is a filesystem, filesystem with git or github/lab.  So if you use github/lab, you could just offer a link with pagetitle to the "add page" at github/lab, as workaround.

You could create a page or add to in your theme:

For Gitlab:
```html
<form action="https://gitlab.com/GROUP/PROJECT/-/new/master/" method="GET">
<input type="text" name="file_name">
<input type=submit value="new page">
</form>
```

For Github:
```html
<form action="https://github.com/GROUP/PROJECT/new/master" method="GET">
<input type="text" name="filename">
<input type=submit value="new page">
</form>
```

**Comment by Lombra** [comment]
(much later...)

I understand that it is not a CMS. Once again, I don't expect to be able to use MkDocs for editing my documentation. I am already using the web editor of my Git repository for that, and I expect to continue to do so.

So then, can someone explain what makes the existing `edit_uri` fundamentally different from the proposed feature?

That being said, I am open to looking into a theme specific solution.
