### ISSUE TITLE
Consider updating the default edit_uri when project is hosted on github, to match the new default branch (main)

### ISSUE THREAD

**Issue by smarie** [mkdocs/mkdocs#2597]
The default branch on github is now "main" and not "master".
The default behaviour of mkdocs for "edit_uri" could maybe be adapted accordingly.

Of course this means potential breaks when updating old repos that would not have made the change...

See also #2416
(please discard if already discussed, I could not find any past discussion about it)

**Comment by oprypin** [comment]
We can't just break existing usages.
Please instead set in your config:

```yaml
edit_uri: blob/main/docs/
```

**Comment by smarie** [comment]
> We can't just break existing usages.

well, this could have gone through a deprecation cycle for a couple versions, then be changed.
But ok, your decision of course. Thanks!
