### ISSUE TITLE
Allow plugins to detect `--dirtyreload`

### ISSUE THREAD

**Issue by timvink** [mkdocs/mkdocs#2600]
I maintain [a plugin](https://github.com/timvink/mkdocs-print-site-plugin) that relies heavily on the page events. A user using `--dirtyreload` will be presented with incomplete or emtpy results.

I'd like to be able to detect if the plugin is using used in dirty model. It might make sense to add it to the config (`config['is_dirty'] = dirty`) here:

https://github.com/mkdocs/mkdocs/blob/4ea78da2e93e1165c2600df5f5a66704ff8bc197/mkdocs/commands/build.py#L254-L260

Or have is accessible as a kwarg in relevant global events, for example adding `is_dirty` to `on_post_build`

https://github.com/mkdocs/mkdocs/blob/4ea78da2e93e1165c2600df5f5a66704ff8bc197/mkdocs/commands/build.py#L308-L309

Perhaps there's another way I'm not seeing?

**Comment by oprypin** [comment]
#2972 is a new development that goes in this direction but not quite. Suggestions are welcome how to elegantly also handle this.

**Comment by oprypin** [comment]
* #2972 now solves this issue
