### ISSUE TITLE
Common Header/Footer for every build html files

### ISSUE THREAD

**Issue by ghost** [mkdocs/mkdocs#261]
I have seen that after building it produces static html files, I have customized the footer but the problem is that i have to add this customized footer on every html page after building, is there any way to make a common header footer file and inherit it all files. Or any Alternative?

**Comment by sinkcup** [comment]
@IMTaqi use "copyright" in `mkdocs.yml` will be OK.
like this: http://openwrt.io/
code is here: https://github.com/openwrtio/portal/blob/1.0.0/mkdocs.yml
