### ISSUE TITLE
Mkdocs does not render a link if the page starts with a link

### ISSUE THREAD

**Issue by martinszeltins** [mkdocs/mkdocs#2629]
If i have this page content in `index.md` file and I run `mkdocs build` then the link will be removed.

````
https://www.google.com

Hello, world!
````

**Result:**

````
Hello, world!
````

**Expected result:**

````
https://www.google.com

Hello, world!
````

**Comment by oprypin** [comment]
Which theme? Do you also observe this if you try a different theme?

**Comment by martinszeltins** [comment]
Thanks @mondeja, that worked!
