### ISSUE TITLE
how to highlight code syntax?

### ISSUE THREAD

**Issue by fedelibre** [mkdocs/mkdocs#263]
Reading issue #183 , I understand that mkdocs supports syntax highlighting. And I see also the prettify.js files in all the themes.except readthedocs.

I  wonder where can I find the instructions about the use of prettify. Is it supposed to recognize the language automatically or should I specify the lang in the fenced block?
I've tried py, js, css but none works.

``````
```py
import this
print("Please document syntax highlighting in mkdocs")
```
``````

It would be worth adding some information in the documentation.
Thanks

**Comment by master317** [comment]
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        Hello World (from the view)
    </div>
</body>
</html>
