### ISSUE TITLE
Pages appear in alphanumerical order once uploaded to read the docs/github

### ISSUE THREAD

**Issue by ZenderB3D** [mkdocs/mkdocs#2631]
Hi!

I've been making a documentation and the time has come to upload it. I made most of it offline, using mkdocs serve to see what I made.

I tried both the nav: and pages: syntax but they both perform the same/are seemingly ignored once uploaded and build on read the docs but it does work properly in the local server.

This is the documentation in question:

https://pp-docs.readthedocs.io/en/latest/
https://github.com/ZenderB3D/pp_docs

Thank you for your time and help!

**Comment by oprypin** [comment]
This is something specific to how you're deploying to "readthedocs". That makes this issue not possible to work with in the context of MkDocs. You need to provide a locally reproducible issue. I certainly don't see any such issue locally.

I also see subtle differences in how the theme looks compared to the latest version. At the very least, your deployment is prior to commit https://github.com/mkdocs/mkdocs/commit/eb31d4c0d70259755b779bd6bf34609ac2adca7b which means it is version 1.1.2 or older. Latest is 1.2.3. Which also separately disqualifies your issue report.

| Latest/local version | Your version |
|--|--|
| ![image](https://user-images.githubusercontent.com/371383/138594229-e526a9bb-6a71-43b5-b58a-24982c29d277.png) | ![image](https://user-images.githubusercontent.com/371383/138594306-550af2c3-d6cb-4389-87ee-e06dfd004d60.png) |

**Comment by oprypin** [comment]
The correct syntax is indeed `nav:`, so at least try switching to that one, maybe there was some other problem and if you try it again, it will work.
