### ISSUE TITLE
Support custom directories to watch when running `mkdocs serve` 

### ISSUE THREAD

**Issue by steven-terrana** [mkdocs/mkdocs#2632]
Hello! 

Thanks for your work on `mkdocs`. 

I'm looking for feedback on the following feature request before putting effort into the development. 

## Feature

Add a `-w` / `--watch-dir` command line option to `mkdocs serve`. 

The directories (or globs?) provided would be watched and changes would trigger a rebuild/reload.

## Context

The problem i'm trying to solve is that i'm currently using the [mkdocs-gen-files](https://github.com/oprypin/mkdocs-gen-files) plugin to add markdown files from outside the `docs_dir` into the site. 

This works great when building the documentation, but doesn't work for local development via `mkdocs serve`. 

The current hack i'm using to get around this is to add the extra directory to watch via the `theme.custom_dir` property and then adding `--watch-theme` to `mkdocs serve`. 

it works but.. ew. :) 

<hr>

If this idea sounds like a feature you support, I'd be happy to give the implementation a shot!

**Comment by oprypin** [comment]
Yes, I think it's time to add this config.
It would probably be a config in YAML actually, named `watch`, with the flag `-w`/`--watch` augmenting it.

The watching implementation supports both files and directories seamlessly already.
So implementing it is easy, just adding a `watch` call. You could try doing that, yeah.

Note that there is "prior art": the "mkdocstrings" plugin basically decided to expose such functionality generically itself, even though it's not specific to the plugin.
https://github.com/mkdocstrings/mkdocstrings/search?q=watch
https://github.com/mkdocstrings/mkdocstrings/blob/0b4b2f5259f9607ecb82f11ae2372ddeb156bca9/src/mkdocstrings/plugin.py#L130-L132

So indeed, in the interest of not duplicating such plugin-specific configs, it's probably good to add this config generically.
