### ISSUE TITLE
Add option to always use filename in navigation

### ISSUE THREAD

**Issue by darkdragon-001** [mkdocs/mkdocs#2644]
I have a file `<section>/index.md` where meta _title_ is set to `<section>` and the document starts with `# <section>`. Nevertheless, I would like to have it displayed in the menu as `Index` since it looks weird to have the navigation menu
```
<section>
  <section>
  ...
```
I would prefer
```
<section>
  Index
  ...
```

I achieved it by removing the lines setting `self.title = self.meta['title']` and `self.title = get_markdown_title(self.markdown)` from `structure/pages.py > _set_title(self)`. Would be nicer if there was an option for that...

**Comment by oprypin** [comment]
This is not a direct reply to the request, but seems like an even better solution for your case would be https://github.com/oprypin/mkdocs-section-index

<pre><b>&lt;section&gt;</b>
  ...</pre>

**Comment by oprypin** [comment]
Readthedocs theme does not support deeply nested navigation in the first place.

OK:

* foo.md
* a/
   * index.md
   * c.md

Not supported:


* a/
   * b/
      * index.md
      * c.md

---

Consider instead mkdocs-material theme.
