### ISSUE TITLE
AttributeError: 'LiveReloadServer' object has no attribute 'watcher'

### ISSUE THREAD

**Issue by AninditaBasu** [mkdocs/mkdocs#2655]
Today, I upgraded mkdocs by running the `pip upgrade` command. Thereafter, on running `mkdocs serve`, I get this error:

`AttributeError: 'LiveReloadServer' object has no attribute 'watcher'`

On investigation, I found this issue: #2448. I've tried downgrading the upgrade, but I still get the same error.

**Comment by oprypin** [comment]
You're using a broken plugin or an outdated version of one. Why don't you post the whole error message, which surely includes a stack trace, including a clear pointer to which plugin it is???

**Comment by oprypin** [comment]
OK so indeed the message clearly shows that the error is in mkdocs-macros-plugin. I know it has a new version which fixes the problem. When upgrading any package, usually you should upgrade all of them to latest.
