### ISSUE TITLE
MkDocs doesn't deploy

### ISSUE THREAD

**Issue by Vaschex** [mkdocs/mkdocs#2659]
I just don't see the MkDocs theme at my [gh-pages site](https://vaschex.github.io/PartyService/) although it says that all checks have passed. I have this problem since a long time.

This is my repo: https://github.com/Vaschex/PartyService
MkDocs v1.2.2, Python v3.9

**Comment by oprypin** [comment]
This is something GitHub-specific.
The deployed branch is there
https://github.com/Vaschex/PartyService/tree/gh-pages
You just probably failed to tell GitHub that that's what it should serve
