### ISSUE TITLE
Markdown inside html 

### ISSUE THREAD

**Issue by PVasili** [mkdocs/mkdocs#2672]
How to use markdown inside html ?
for example:
```
<div class='row'>
…
!!! note ""
    Lorewm…
…
</div>

```

**Comment by facelessuser** [comment]
You may want to use the following extension: https://python-markdown.github.io/extensions/md_in_html/

**Comment by PVasili** [comment]
> You may want to use the following extension: https://python-markdown.github.io/extensions/md_in_html/

@facelessuser, thanks a lot!

`markdown = "1"`

helped me.

I think this needs to be added to the help?

**Comment by oprypin** [comment]
Generally MkDocs doesn't document features of Markdown, assuming that users will find Markdown documentation separately. This may be reconsidered, but as an overall policy rather than a one-off.
