### ISSUE TITLE
Implicit reference-style link containing backticks are broken

### ISSUE THREAD

**Issue by Ullaakut** [mkdocs/mkdocs#2676]
* Platform: Ubuntu 20.04 under WSL2
* Mkdocs version: `v1.2.3`

I'm rewriting this issue since I initially assumed this feature did not work, but it turns out it does in normal cases, and simply has a small bug.

When an implicit reference-style link is specified with backticks in it, the link does not work, while in other Markdown implementations this is not the case.

Example with GitHub flavored Markdown:

```markdown
This is a [`test`].

[`test`]: https://google.com
```

Results in:

This is a [`test`].

[`test`]: https://google.com

In Mkdocs v1.2.3, this does not seem to be the case.

**Comment by mondeja** [comment]
It seems [valid commonmark markup](https://spec.commonmark.org/dingus/?text=-%20%23%23%20I%27m%20really%20crazy%20testing%20this%20shit) and has been reported in https://github.com/Python-Markdown/markdown/issues/495

**Comment by facelessuser** [comment]
Keep in mind that Python Markdown is **not** a CommonMark parser.

**Comment by oprypin** [comment]
You'll have to refer to the issue that others linked. MkDocs doesn't control this, it's all Python-Markdown.
