### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by parisni** [mkdocs/mkdocs#2689]
So far, if one of the md file of my doc is modified, all the html files get modified, resulting in a large commit. Apprently the modification are essentialy random newlines.

Is there a way to avoid modifiyng every files when only in order not to flood commits when doc is modified ?

Thanks

**Comment by timvink** [comment]
This might be an issue with you git configuration. Are you on windows? Could be windows newlines being replaced by Unix newlines.

Also, you probably don't need to have generated artifacts like HTML under version control. You could .gitignore them as you can always rebuild them.

**Comment by parisni** [comment]
I'm on linux

In my use case, I publish the doc from master/docs folder.

**Comment by oprypin** [comment]
I haven't observed that this type of issue exists. I only saw that `sitemap.xml.gz` changes every time.
So, you'd have to provide some particular site as a reproducible example.  It could be a particular theme or plugin causing it. But I cannot guess it.

**Comment by leonardehrenfried** [comment]
@oprypin The changing of the `sitemap.xml.gz` is a little strange. 

Is there a way to disable the generation of the gzipped sitemap?

**Comment by oprypin** [comment]
Yes

**Comment by leonardehrenfried** [comment]
And would you be so kind and tell me how?  I cannot find anything on https://www.mkdocs.org/user-guide/configuration/
