### ISSUE TITLE
multiple directories for doc_dir

### ISSUE THREAD

**Issue by alexvoss** [mkdocs/mkdocs#2697]
I am looking for a way to generate a website from a set of pages that are shared between different organisations plus some that are specific to only one. The content for the latter should override any content with the same path for the former. It would be nice if docs_dir could accept a list of paths that are handled as described.

I have thought about alternatives such as putting the generic files into a subdirectory and using the git submodules functionality to manage the content but the resulting URLs would show the difference. Other alternatives such as symbolic links do not work on Windoze (right?).

Would the changes needed be limited to mkdocs/structure/files.py? I could have a go at making the necessary changes but wanted to hear people's thoughts first. Perhaps I am holding the wrong end of the stick...

**Comment by trel** [comment]
I think you're better off preparing the files/pages ahead of time, and then 'just running mkdocs' as is.

A general approach to having some common files in one place, and then organization-specific files in other places makes sense to me.   And then perhaps even the 'prepare' script can be parameterized to be used everywhere (only passing in a URL and/or title and/or directory).

There are many corner cases to adding more logic to the mkdocs configuration options.

**Comment by alexvoss** [comment]
Ok, appreciate that. A separate script would not work with mkdocs serve, which is a pity but no show-stopper. I may try to play with `mkdocs-macros-plugin` to see if that can help.

**Comment by timvink** [comment]
a separate script can work with MkDocs serve actually. See https://pypi.org/project/mkdocs-simple-hooks/

**Comment by alexvoss** [comment]
Closing this issue as it looks like a solution external to mkdocs is the way to go.
