### ISSUE TITLE
Plugin supports direct use of modules

### ISSUE THREAD

**Issue by Singein** [mkdocs/mkdocs#2707]
We can only develop a plug-in by packaging a module and declaring entry_points. How about supports direct use of modules? 
This is not troublesome, so do we consider adding a new way to mount plugins?

**Comment by oprypin** [comment]
I agree that requiring entry_points was too heavy-handed. But well, there is this plugin, which works fine to achieve this: https://github.com/aklajnert/mkdocs-simple-hooks

**Comment by timvink** [comment]
You can also have a look at pluglets by https://mkdocs-macros-plugin.readthedocs.io/en/latest/

**Comment by oprypin** [comment]
Since we're listing alternatives that involve Python code, there's also this slightly specialized one: https://github.com/oprypin/mkdocs-gen-files

**Comment by oprypin** [comment]
Solved in MkDocs 1.4
* https://github.com/mkdocs/mkdocs/pull/2978

**Comment by Singein** [comment]
nice work!
