### ISSUE TITLE
deployment failure

### ISSUE THREAD

**Issue by mrok-creator** [mkdocs/mkdocs#2731]
I try posted my repo to gh-pages get that attentification -
![image](https://user-images.githubusercontent.com/96112794/147609902-cd62a885-d705-413f-96c8-9728ae25ab71.png)
and it not changes to "published". 
Also  I get this: 
![image](https://user-images.githubusercontent.com/96112794/147609732-6828fd3a-a5f8-47f4-bf49-a559a41f198c.png)
 and link not worked (error 404)
![image](https://user-images.githubusercontent.com/96112794/147610055-c1ac73a9-59a5-45e7-af83-c5ca7b927ec6.png)

I already tried to recreate the repository, but nothing changed. Repo is public, you can chek it - 
[https://github.com/mrok-creator/goit-markup-hw-01](url)

**Comment by oprypin** [comment]
How exactly is this related to MkDocs?

**Comment by mrok-creator** [comment]
I used the Github manual to create the site, new user, recently started, did not create separate MkDocs

**Comment by mrok-creator** [comment]
1) create a repository on GitHub 
2) Through the application GitHub Desktop cloned an empty repository to my computer
3) choose the option to open it in VSCode 
4) then created files, added images
5) the GitHub Desktop app displays all the changes you made 
6) made a commit of changes
7) uploaded a push to the repository, also in the app.
8) uploaded the work to the git, then created a GitHub Page in the repository settings

Translated with www.DeepL.com/Translator (free version)

**Comment by oprypin** [comment]
None of your steps mention MkDocs. Why are you commenting on the repository of the MkDocs project?

**Comment by mrok-creator** [comment]
I created a question in the issue section to deal with the problem

**Comment by mrok-creator** [comment]
problam wasn't solved
