### ISSUE TITLE
site_url set, but it doesn't use the subdirectory

### ISSUE THREAD

**Issue by UCYT5040** [mkdocs/mkdocs#2748]
I have this in mkdocs.yaml.
```yaml
site_url: https://redacted/site/
```
When I go to /site, it shows requests like `[404]: GET /search/main.js - No such file or directory`. The page is unstyled and nothing works.

How can I fix this.

**Comment by oprypin** [comment]
Seems like you're not using the latest version of MkDocs

**Comment by UCYT5040** [comment]
I'm using pip install.

**Comment by oprypin** [comment]
OK. That's not happening to me.
If you want to provide more details so that it's possible to reproduce the problem, that'd be cool. If not, also cool.

**Comment by UCYT5040** [comment]
What kind of details?

**Comment by pawamoy** [comment]
Your MkDocs version. Whether you're serving the site locally or deployed it.

**Comment by UCYT5040** [comment]
Deployed (run command `php -S 0.0.0.0:5000`)
Version 1.2.3
`mkdocs, version 1.2.3 from /home/ucyt/.pyenv/versions/3.8.12/lib/python3.8/site-packages/mkdocs (Python 3.8)`

**Comment by UCYT5040** [comment]
When I go to `/site/` it seems to work, but not `/site`.

**Comment by UCYT5040** [comment]
Is there a way to make this work?

**Comment by pawamoy** [comment]
I have the same behavior locally, when serving. Suburls work both with and without trailing slash (when without, the slash is appended anyway), but indeed not for the home page. There I get a 404 without a slash. Stylesheets are still loaded though. I also note that on github.io, the slash is appended even on the home page.

**Comment by oprypin** [comment]
You deployed this to some server that can serve the path both with and without the slash. To MkDocs that is not the same thing and indeed it can't handle it. I was gonna say that there's no technical solution to that. But I guess each page could include a JavaScript snippet to add a slash to itself and reload. But that's not great. Instead your server really should be doing the redirection. Or just don't `use_directory_urls`

**Comment by tkoskela** [comment]
I'm having a similar issue to this one. I'm trying to deploy pages to a subdirectory on GitHub pages by adding `site_url` to my `mkdocs.yml`
```
site_url: https://myOrg.github.io/myRepo/subdirectory/
```
This works locally when I run `mkdocs serve`, I get 
```
INFO    -  [16:23:43] Serving on http://127.0.0.1:8000/myRepo/subdirectory/
```
When I run `mkdocs gh-deploy` it doesn't, I only get the default url
```
INFO    -  Your documentation should shortly be available at:
           https://myOrg.github.io/myRepo/
```

My mkdocs version is
```
$ mkdocs --version
mkdocs, version 1.5.3 from /home/.../python3.10/site-packages/mkdocs (Python 3.10)
```
