### ISSUE TITLE
new line in code block just doesn't work

### ISSUE THREAD

**Issue by marsupialtail** [mkdocs/mkdocs#2749]
I can't figure out how to have multi-line code blocks. 

~~~python
    a=1;  
    b=2
    c
~~~

renders as 
a=1; b=2 c

in a single line. Tried everything, like appending double space, or adding backslash. Nothing works. Using the latest mkdocs version

**Comment by facelessuser** [comment]
I assume you are trying to use fenced code blocks but are not enabling a fenced code extension: either [Codehilite](https://python-markdown.github.io/extensions/code_hilite/) or [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/). I personally recommend the latter, but I'm also biased as I'm the author of that extension.

**Comment by oprypin** [comment]
It just works, even with no extensions at all.

```markdown
    a=1;  
    b=2
    c
```

```markdown
~~~python
a=1;  
b=2
c
~~~
```

Either one works. That is indeed what you need to write, I don't know why it doesn't work for you.
What's the config?

**Comment by marsupialtail** [comment]
WHat about the config should I provide?

**Comment by oprypin** [comment]
Start from absolutely nothing. Create the files (at least `mkdocs.yml` and `docs/whatever.md`) in a way that still shows off the problem you claim. Provide the exact content of these files. Possibly also provide plugins if there are external references.

**Comment by facelessuser** [comment]
Fenced code is not part of the original Markdown spec. MkDocs, if not using a fenced code extension will render block (multi-line code blocks) as inline: https://johnmacfarlane.net/babelmark2/?text=%60%60%60%0Aa%3D1%3B++%0Ab%3D2%0Ac%0A%60%60%60

**Comment by facelessuser** [comment]
Without extensions, you'd have to indent
