### ISSUE TITLE
access theme files from mkdcos-macro

### ISSUE THREAD

**Issue by alanlivio** [mkdocs/mkdocs#2759]
Hi. 

The mkdocs-macros works great when using templates inside the docs folders. 
But I use mkdcos-material and want to include some templates from it inside my index.md.
More precisely, I want to use the [social.html](https://github.com/squidfunk/mkdocs-material/blob/master/material/partials/social.html) template.
So, inside my index.md I used
```
{% include "partials/social.html" %}
```
But I receive the following error:
```
get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: partials/social.html
```
How to proceed?
Best regards.

OBS: Originaly from [mkdcos-macros #121](https://github.com/fralau/mkdocs_macros_plugin/issues/121)

**Comment by oprypin** [comment]
This really is about the plugin and not about MkDocs.
I don't know why you were sent away from https://github.com/fralau/mkdocs_macros_plugin/issues/121

**Comment by pawamoy** [comment]
@alanlivio @fralau @oprypin, I'd say the issue simply comes down to the fact that the macros plugin and mkdocs+material theme do not share the same Jinja env and context. When doing `{% include "partials/social.html" %}` in a Markdown file, you are using the macros plugin context, which is not at all aware of any such template, since probably the Jinja environment does not have a FileSystemLoader pointing to Material's templates directory.

**Comment by fralau** [comment]
@pawamoy 

> the issue simply comes down to the fact that the macros plugin and mkdocs+material theme do not share the same Jinja env and context. 

This is correct and is often a source of confusion. 

> When doing {% include "partials/social.html" %} in a Markdown file, you are using the macros plugin context, which is not at all aware of any such template, since probably the Jinja environment does not have a FileSystemLoader pointing to material's templates directory. When you do the same thing in a custom template referenced in your theme settings, the context used is the one of mkdocs + theme configuration, in this case material, and it knows where to find the template. 

The mkdocs + theme configuration does these things without an issue. 

> You can probably configure the macros plugin to be able to find material's templates, but I'm not sure how.

This was never tried. Also, I am not completely sure why one would.

Especially when one is new with the mkdocs environment, it would be wise to do everything to remain simple and safe, i.e. to remain on the beaten path.

The proper way to manipulate the mkdocs-material environment would be to [extend the material theme](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme), according to the official instructions. There is a lot of HTML/css, etc. wisdom in that piece of software so if something is in the doc, it's for good reason.

Of course, one could attempt to hack the whole software stack by using one tool to do another tool's job. I would however not do that myself with a light heart.

**Comment by alanlivio** [comment]
Hi @fralau @oprypin @oprypin. Thank you for the discussion.

> The proper way to manipulate the mkdocs-material environment would be to extend the material theme, according to the official instructions. There is a lot of HTML/css, etc. wisdom in that piece of software, if something is in the doc, it's for good reason.
I understood. I try to follow this path of extending mkdocs-material.
Best regards.
