### ISSUE TITLE
Relative urls to different folders fail if current path and target path have the same filename

### ISSUE THREAD

**Issue by birdybro** [mkdocs/mkdocs#2762]
https://github.com/birdybro/MkDocs_MiSTer_old/commit/e3a8e44d00b23e21863c31da73391d302a5611b7

This is what I had to do to resolve the issue. Basically, testers noted that the relative url I was using was resulting in a 404, and in some browsers went totally zoomed in and got all bugged up.

I'm not incredibly technically inclined compared to others that submit issues here. I tested it by changing my syntax for the relative link just about every way I could imagine, and then realized I had a same-named file in `/basics/` and in `/advanced/`. Once removed the problem went away.

**Comment by oprypin** [comment]
Could you please explain again how to make this issue happen? The commit you linked is not possible to see anymore.

**Comment by birdybro** [comment]
Updated url and fixed the one above. I was forced to change it since I had to deprecate the old repo, sorry about that.

https://github.com/birdybro/MkDocs_MiSTer_old/commit/e3a8e44d00b23e21863c31da73391d302a5611b7
