### ISSUE TITLE
Feature request: 'weight' metadata

### ISSUE THREAD

**Issue by rudolfbyker** [mkdocs/mkdocs#2764]
This would allow us to sort pages without resorting to using 'nav' in the config. It would be very nice to be able to have the automatic nav, where the entire structure is determined by the filesystem alone, and still be able to sort pages.

**Comment by shu307** [comment]
I make a simple plugin, seems to work fine with my local docs.
[try?](https://github.com/shu307/mkdocs-nav-weight)

**Comment by pawamoy** [comment]
Would you like to add your plugin to https://github.com/pawamoy/best-of-mkdocs? You can add it at the end of the `nav-pages` category in `projects.yaml` :slightly_smiling_face:

**Comment by rudolfbyker** [comment]
The plugin works perfectly.

**Comment by pawamoy** [comment]
Thanks for coming back and closing the ticket @rudolfbyker!
