### ISSUE TITLE
Can i add html headers in toc of mkdocs?

### ISSUE THREAD

**Issue by asl369** [mkdocs/mkdocs#2770]
Hi, Will i be able to add html headers in toc of mkdocs?
For example
If i have #Heading1 and <h>Heading2<h> with html headers, is there any way that i could get Heading1 and Heading2 in TOC of mkdocs file?

**Comment by squidfunk** [comment]
The table of contents extension only processes Markdown headers, e.g.:

```
# Heading
## Subheading
...
```

If you're using HTML syntax to define headlines, the table of contents extension will ignore them.

```
<h1>Heading</h1>
<h2>Subheading</h2>
...
```

Thus, the answer to your question is no, the table of contents extension will ignore HTML headers.
