### ISSUE TITLE
Using phuel/tables_extended markdown extension does not work due to built-in table extension

### ISSUE THREAD

**Issue by pideu-mh** [mkdocs/mkdocs#2771]
<https://github.com/phuel/tables_extended> is an extended version of the regular tables extension which supports neat features like column and row spans.

Unfortunately this does not work out-of-the box.

I installed it as described on the project web page.

Then I made a minimal working example using `mkdocs new` and added `tables_extended` to the `markdown_extensions`. Then I added the sample table "Merging of columns or rows" from the _tables_extended_ page to `index.md` that uses the new features.

After using `mkdocs serve -v` the table is rendered, but using the regular _tables_ extension, not the  _tables_extended_ extension.

![grafik](https://user-images.githubusercontent.com/28350507/154947472-9c534cc9-daca-4558-83fb-b308e2a577f1.png)

In the verbose output I noticed that the _tables_ extension is mentioned before _tables_extended_, because it is a built-in extension.
```
DEBUG    -  Config value: 'markdown_extensions' = ['toc', 'tables', 'fenced_code', 'tables_extended']
```
Unfortunately I did not find a way of disabling the built-in _tables_ extension, so I had to modify `c:\Users\<User>\AppData\Local\Programs\Python\Python310\Lib\site-packages\mkdocs\config\defaults.py` directly.

https://github.com/mkdocs/mkdocs/blob/747320fff337cb8731ec6a480e0d21b88fc016ab/mkdocs/config/defaults.py#L92-L95

So I removed _tables_ from the _builtin_ array above and tried  `mkdocs serve -v` again. Then the table is rendered correctly:

![grafik](https://user-images.githubusercontent.com/28350507/154947586-d637ef1f-bd65-421e-9b78-c46dc439d5b6.png)

Of course it is not practical to modify _defaults.py_ directly, so the question is how `tables_extended` can be loaded so that is used instead of the built-in `tables`.

Maybe I am missing something obvious?

**Comment by oprypin** [comment]
I don't see any easy solution to this within MkDocs. The *tables_extended* extension could solve it from its side, though. The most direct approach which probably will work would be to make that extension have a higher priority, such as `75.1`. See here:

* https://github.com/phuel/tables_extended/blob/c52293a2695819b3e3c9f6633639119a35831557/build/lib/tables_extended.py#L354
* https://github.com/Python-Markdown/markdown/blob/af38c42706f8dff93694d4a7572003dbd8b0ddc0/markdown/extensions/tables.py#L219
* https://python-markdown.github.io/extensions/api/#registries

**Comment by pideu-mh** [comment]
> I don't see any easy solution to this within MkDocs. 

Thank you very much for your answer. I understand now that both extensions register to the same registry and are later called depending on their priority.

> The _tables_extended_ extension could solve it from its side, though. The most direct approach which probably will work would be to make that extension have a higher priority, such as `75.1`. See here:

Thanks for your suggestion. I tried it locally and I can confirm that it works as expected.

If this is the sensible thing to do to make this work, then I will file an issue at https://github.com/phuel/tables_extended
