### ISSUE TITLE
[BUG] mkdocs has no attribute `structure`

### ISSUE THREAD

**Issue by Mara-Li** [mkdocs/mkdocs#2809]
I have a package ([ezlinks](https://github.com/Mara-Li/mkdocs-ezlinked-plugin/)) where I do : 
```py
class FileMapper:
    def __init__(
        self,
        options: EzLinksOptions,
        root: str,
        files: List[mkdocs.structure.pages.Page],
        logger=None,
    ):
        self.options = options
        self.root = root
        self.file_cache = {}
        self.file_trie = pygtrie.StringTrie(separator="/")
        self.logger = logger

        # Drop any files outside of the root of the docs dir
        self.files = [file for file in files if root in file.abs_src_path]

        for file in self.files:
            self._store_file(file.src_path)
```
This permit to get a list of file. 

But, when I try to `gh-deploy` I have : `AttributeError: module 'mkdocs' has no attribute 'structure'`
I have no problem in `mkdocs serve` and in the 1.2.4.

What happened? What did I need to do to support the last update? Thanks.

**Comment by oprypin** [comment]
https://github.com/Mara-Li/mkdocs-ezlinked-plugin/blob/46c6519/mkdocs_ezlinks_plugin/file_mapper.py

You're using `mkdocs.structure` without `import mkdocs.structure`. If it ever worked, it was an accident. So, add `import mkdocs.structure` to your code to fix the bug in it.

**Comment by Mara-Li** [comment]
Thank you! It was strange that it works before ahah ^^
