### ISSUE TITLE
Reference style links not rendering correctly

### ISSUE THREAD

**Issue by demberto** [mkdocs/mkdocs#2812]
A link like this:

```markdown
[![Documentation Status][docs-shield]][docs-link]
```

gets displayed correctly on GitHub but not in Mkdocs regardless of the theme used

**Comment by oprypin** [comment]
This is not a sufficient reproduction.

I need to be able to run `mkdocs serve`, observe the actual result, and also I need to know what you expected instead and why

**Comment by demberto** [comment]
What can I do to get you a reproduction? Should I add a picture of what I expect vs. what I get?

**Comment by oprypin** [comment]
If I paste this into a project, I'll see just that. And it's expected. Same on GitHub:

[![Documentation Status][docs-shield]][docs-link]

**Comment by demberto** [comment]
I mean, you need to add real links below these. And when you do that you get the correct behaviour on GitHub or even VSCode's preview. But not in mkdocs.

However if I use normal `()` links there are no problems.

**Comment by facelessuser** [comment]
Mkdocs isn't what processes such links, that is Python Markdown, so even if this was a bug, this isn't really the right place for it.

With that said, I see no issues using this kind of link in MkDocs:

```markdown
[![Donate via PayPal][donate-image]][donate-link]
[![Discord][discord-image]][discord-link]
[![Build][github-ci-image]][github-ci-link]
[![Coverage Status][codecov-image]][codecov-link]
[![PyPI Version][pypi-image]][pypi-link]
[![PyPI Downloads][pypi-down]][pypi-link]
[![PyPI - Python Version][python-image]][pypi-link]
![License][license-image-mit]
```

<img width="620" alt="Screen Shot 2022-04-01 at 4 20 50 PM" src="https://user-images.githubusercontent.com/1055125/161349624-08174d15-8872-4dcb-9566-405e1b3ee8d5.png">

Now, there may be some kind of scenario that causes these links to break, but you'd have to identify that scenario and probably file a bug on Python Markdown once you do.

**Comment by oprypin** [comment]
Information not provided - can't do anything here.

**Comment by demberto** [comment]
@oprypin I shifted to HTML tables in the end, I couldn't figure out what the issue was, and its not reproducible either, some sort of caching issue I guess

**Comment by AmandaSatin** [comment]
By the way thank you so very much for your patience and understanding as it
means more time to gain leverage. I will have an actual tech support
employee
