### ISSUE TITLE
Code Block annotations for unsupported languages

### ISSUE THREAD

**Issue by AjaniBilby** [mkdocs/mkdocs#2828]
Currently, code annotations can only be placed within the region of a code block marked as a comment by the syntax highlighter.
This means however that you can't annotate the code of any language not natively supported by Pygments.

Obviously, this is a very edge case problem, as the only people who would come across this issue are either:
  a) someone developing a language
  b) someone writing about or documenting a very new language
The answer in both cases could just be "implement the syntax into Pygments", however ofc for early languages still heavily evolving their syntax - or prototype languages used for discussion purposes - this isn't really viable.

**Comment by pawamoy** [comment]
Wrong repository, [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations) are a specific feature of the Material for MkDocs theme: https://github.com/squidfunk/mkdocs-material 🙂

**Comment by AjaniBilby** [comment]
Whoops, I don't know how I ended up on the repo, my bad 😅
