### ISSUE TITLE
Add support for OIDC

### ISSUE THREAD

**Issue by timothydilbert** [mkdocs/mkdocs#2832]
### Description
It would be excellent if you considered implementing support for OIDC federated authentication. That way, when someone tries to view the MkDocs site, they would be redirected to the configured IdP, and need to authenticate in order to view the MkDocs site.

Having OIDC implemented using the Authorization Code + PKCE would allow the documentation to be protected, and portable to any web server without needing to involve a third-party service proxying the request to the underlying MkDocs site.

### Use Cases
I am constantly writing documentation for customers using MKDocs. The thing is, this documentation shouldn't always be accessible by anyone.

**Comment by oprypin** [comment]
How exactly can a **static site generator** put "authentication" into the HTML files that it produces?

**Comment by RafPe** [comment]
@timothydilbert  try to put something like https://github.com/oauth2-proxy/oauth2-proxy in front of it :)
