### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by EXPErdelfavero** [mkdocs/mkdocs#2841]
In user-guide/configuration.md, the string "parent configuration while which each site's primary" should be "parent configuration file which each site's primary".

Replace "configuration while" with "configuration file".

Sorry to not just submit this as a PR, but your contributing process is designed for code contributions, not so much for drive by typo fixes.

**Comment by dhirschfeld** [comment]
Hi @EXPErdelfavero :wave:
I'm not associated with the project, but it can help maintainers if you create a link to the source you're discussing - e.g.

![image](https://user-images.githubusercontent.com/881019/167976001-d098ba8d-72bb-4e75-9532-fbf5e7aa3362.png)

* https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet

When you choose `Copy permalink` from the dropdown it'll copy a url which you can paste in an issue and GitHub will then render the actual source code with a hyperlink to the file in question - e.g.

https://github.com/mkdocs/mkdocs/blob/cdf8a26cafa6af6cc78a45766dfec235bd7286cc/docs/user-guide/configuration.md?plain=1#L725-L726

**Comment by Fullchee** [comment]
Created a PR to fix this!
