### ISSUE TITLE
mkdocs

### ISSUE THREAD

**Issue by NikhilSardana18** [mkdocs/mkdocs#2845]
Can't understand this issue.
Config value: 'markdown_extensions'. Error: module
            'markdown.extensions.extra' has no attribute
            'MarkdownInHtmlProcessor
![Capture](https://user-images.githubusercontent.com/96880270/168497960-d3f4180d-776c-4894-8c3a-a1570eeb01a7.PNG)
'

**Comment by facelessuser** [comment]
Pretty sure `extrarawhtml` was removed in the most recent versions of Pymdown Extensions. Its whole purpose was to expose the raw HTML functionality that existed in Python Markdown as a standalone extension, but then Python Markdown finally made it a separate extension called `md_in_html`. You should use `markdown.extensions.md_in_html` now.

**Comment by NikhilSardana18** [comment]
Thanks it worked for me..
