### ISSUE TITLE
Disable color output in terminal when NO_COLOR is set

### ISSUE THREAD

**Issue by evanrichter** [mkdocs/mkdocs#2862]
It would be nice to turn off terminal colors sometimes, but there currently is no option to do that.

https://no-color.org/ is the closest thing to a standard I could find, and they recommend disabling color if the `NO_COLOR` environment variable is set (to any value).

**Comment by mondeja** [comment]
See also https://www.npmjs.com/package/supports-color (used by [chalk](https://www.npmjs.com/package/chalk) for NodeJS) and the Python port https://pypi.org/project/supports-color/ (unfortunately [not tested](https://github.com/shawwn/supports-color-python/tree/79339e63fbb589f335920379482bc306019d0869/tests) though), both check other cases in which terminals don't support colors.
