### ISSUE TITLE
Wiki themes page accidentally deleted

### ISSUE THREAD

**Issue by IgdaliasCabamba** [mkdocs/mkdocs#2871]
Hi guys, unfortunately I accidentally deleted the community themes page, please forgive me, it was an accident, I'm really sorry!

**Comment by pawamoy** [comment]
That's fine, the wiki is a git repo as well, everything can be reverted:)

**Comment by ultrabug** [comment]
Thanks for saying it out loud @IgdaliasCabamba :+1: I reverted it.

**Comment by IgdaliasCabamba** [comment]
Thanks!
