### ISSUE TITLE
Add scoop or winget installation options

### ISSUE THREAD

**Issue by wmstack** [mkdocs/mkdocs#2891]
It would be helpful if we can build markdown documentation without first having to install pip on our machines. I imagine not everyone who would want to use this project is a python developer, so I am asking that we cater for those as well.

# Proposal
Add a winget package that does not require admin rights to install. That is it should be a user scoped package. Also add a scoop package for mkdocs.

**Comment by fu-sen** [comment]
MkDocs is not the only pip. Many plugins and themes are also operated as pip packages.
In order for you to use MkDocs properly, pip's dependency will not go away.

Nevertheless, scoop also provides Python, so you may consider registering MkDocs on the scoop side. (I also use his scoop)
