### ISSUE TITLE
MyST parser feature

### ISSUE THREAD

**Issue by pypamart** [mkdocs/mkdocs#2898]
Hello Mkdocs teams,

Thank you very much for your great software!
It could be very nice to have the choice to select the MyST parser (https://myst-parser.readthedocs.io/en/latest/index.html).
Have you plan to implement this option?

Thank you

**Comment by oprypin** [comment]
Unfortunately, this is simply infeasible. MkDocs is fully tied to using Python-Markdown; that constitutes at least 50% of the overall functionality, including extensions. One can't just swap it out.

And, not that it needs to be additionally argued, but to me it seemed that the point of MyST to is to bring the syntax used with Sphinx closer to Markdown. But we already have Markdown, so is that something in need of solving?

**Comment by astrojuanlu** [comment]
On the other hand, support for MyST, or at least a migration path, would be helpful for people migrating from Sphinx.

**Comment by pawamoy** [comment]
I can see how useful a migration table would be here, something like:

sphinx feature / rst directive | mkdocs feature/plugin / markdown extension
--- | ---
autodoc | mkdocstrings
figure captions | some plugin
command-output | markdown-exec
etc. | etc.
