### ISSUE TITLE
Suggestion: option to specify a template folder structure on new site

### ISSUE THREAD

**Issue by myicq** [mkdocs/mkdocs#2919]
When using `mkdocs new my_brand_new_site`  the same structure is created every single time, as specified in `mkdocs\commands\new.py `.   I propose this to be extended so that a structure can be duplicated from a template directory, or perhaps some kind of packed structure / json / ... 

This way one could do  something along `mkdocs new -template "docsite1" -name "my_brand_new_site"`

**Comment by oprypin** [comment]
There are very many such templating projects already, they will simply work for this use case without needing any behavior specific to MkDocs. As an arbitrary example, there's *copier*.
There's absolutely no need to implement a bad subset of this functionality in MkDocs.
This is rejected.
