### ISSUE TITLE
Relative links in pages below the top-level document folder point to the wrong path

### ISSUE THREAD

**Issue by jdhoek** [mkdocs/mkdocs#292]
Relative image links in pages below the top-level document folder seem to point to the wrong path.
## Reproduction

I've created a minimal reproduction case:
https://github.com/jdhoek/mkdocs-test-relative-image-links

The reproduction case contains this file structure:

```
├── docs
│   ├── index.md
│   ├── subdir
│   │   ├── sub.md
│   │   └── sub.png
│   └── toplevel.png
└── mkdocs.yml
```

`mkdocs serve` and `mkdocs build` correctly process the Markdown files in the top-level folder `docs_dir`, but with the Markdown file in the sub-folder the relative image links are broken.

![mkdocs-relative-image-links](https://cloud.githubusercontent.com/assets/683699/5486734/3fd98a18-86aa-11e4-9243-059b656efa19.png)

**Comment by Mopster** [comment]
I came across this problem today, any eta on v0.12 ? :-) Currently I have to choose between working images in the GitHub repo or on the generated site :-)

**Comment by d0ugal** [comment]
@Mopster The 0.12.0 milestone is here. I've got it down to just a smallish number of bugs. https://github.com/mkdocs/mkdocs/milestones/0.12.0 - I am hoping to do it this weekend, but no guarantees ;)

**Comment by Mopster** [comment]
great! gonna show it off to the office today ;-)

**Comment by Atlas-Night-Out** [comment]
I also have these issues been trying loads of different ways to get images to show up on GitHub, with no luck. They work on a website domain and also in MKdocs server too just no luck at all in Github. Can anyone help me with this or is it not possible?

**Comment by lambdamusic** [comment]
I was able to get this working by using a relative path. Eg in `sub.md`: 

```markdown
![Screenshot](../../img/image.jpg)
```

Obviously not ideal cause each time one needs to remember the file location relative to the `img` folder.. but it works.

**Comment by alex20465** [comment]
I have the same issue, the solution is clear... just change the path.

BUT !  the relative paths markdown -> assets (./xy) is rendered correctly by almost every platform (github, gitea, vscode etc.)

once you copy a document structure to mkdocs, we have to change all paths basically to correct into "wrong" to the other platforms.

this quite sucks since the assets relative path is current to the markdown BUT incorrect after build.

**Comment by kuchaguangjie** [comment]
Does [this answer](https://stackoverflow.com/a/75092404/1568658) on SO fix your problem ?
