### ISSUE TITLE
Content Security Policy support for Google Tag Manager

### ISSUE THREAD

**Issue by swetankrathi** [mkdocs/mkdocs#2922]
I am trying to setup Google Tag Manager(GTM) using this config

```yaml
theme:
  name: readthedocs
  analytics:
    gtag: G-XXXXXXXXXX
```

However, this is working fine on local, there is Content Security Policy(CSP) issue with github pages as `https://www.googletagmanager.com` is not allowed in CSP.

Here is the screenshot
<img width="552" alt="Screenshot 2022-08-10 at 1 02 56 PM" src="https://user-images.githubusercontent.com/12524146/183846515-4e4de432-ad88-48db-85c2-c0faed52388a.png">

Can we add an option to config to allow `https://www.googletagmanager.com` in CSP? More on this can be found [here](https://developers.google.com/tag-platform/tag-manager/web/csp).

**Comment by tomchristie** [comment]
Let's close this off in favor of https://github.com/mkdocs/mkdocs/issues/3630

Including GA should be supported as a template override, not a config option.
