### ISSUE TITLE
py3x-unittests

### ISSUE THREAD

**Issue by Justman10000** [mkdocs/mkdocs#2952]
Hi, I have this problem with the command `python3 -m tox`:

> ERROR:  py37-unittests: InterpreterNotFound: python3.7
> ERROR:  py37-min-req: InterpreterNotFound: python3.7
> ERROR:  py37-integration: InterpreterNotFound: python3.7
> ERROR:  py37-integration-no-babel: InterpreterNotFound: python3.7
>   py38-unittests: commands succeeded
> ERROR:   py38-min-req: undefined
> ERROR:   py38-integration: undefined
> ERROR:   py38-integration-no-babel: undefined
> ERROR:   py39-unittests: undefined
> ERROR:   py39-min-req: undefined
> ERROR:   py39-integration: undefined
> ERROR:   py39-integration-no-babel: undefined
> ERROR:   py310-unittests: undefined
> ERROR:   py310-min-req: undefined
> ERROR:   py310-integration: undefined
> ERROR:   py310-integration-no-babel: undefined
> ERROR:   pypy3-unittests: undefined
> ERROR:   pypy3-min-req: undefined
> ERROR:   pypy3-integration: undefined
> ERROR:   pypy3-integration-no-babel: undefined
> ERROR:   black: undefined
> ERROR:   isort: undefined
> ERROR:   flake8: undefined
> ERROR:   markdown-lint: undefined
> ERROR:   linkchecker: undefined
> ERROR:   jshint: undefined
> ERROR:   csslint: undefined
> ERROR:   nobabel: undefined
> ERROR:   codespell: undefined

**Comment by Justman10000** [comment]
And yes, I have a local copy via git. Have the latest Python version (10.6)

**Comment by Justman10000** [comment]
And yes, I have a local copy via git and also ran the command in the directory of the copy. Have the latest Python version (10.6)

**Comment by oprypin** [comment]
I don't know why this would happen, never seen it.

As for `InterpreterNotFound` in particular, you could use `tox --skip-missing-interpreters`
