### ISSUE TITLE
Putting auto generated menu in number order rather than pages first, then folders

### ISSUE THREAD

**Issue by pomtom44** [mkdocs/mkdocs#2953]
Hiya

Im not sure if this is a theme problem, or a mkdocs problem, so I have posted in both git issues to cover my basis

I have my pages and folders numbered 1.1 1.2 1.3 etc
but at the moment its putting the pages first, then folders at the end
so my menu looks
1.1 - page
1.4 - page
1.2 - Folder
1.3 - Folder

I tried to make a custom nav in the yml but when I put it in, the menu disappears entirely from the theme
And I can't find any info on how to modify either the theme or a config to order it by number rather than type

Thanks in advance

**Comment by ultrabug** [comment]
Hi

There are plugins that help you get total control over nav ordering, such as https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin

That should help you; I'm closing since I don't have the feeling that this is a mkdocs related problem per se.
