### ISSUE TITLE
Plugin mkdocs-plugin-commonmark ?

### ISSUE THREAD

**Issue by emlaurent** [mkdocs/mkdocs#2961]
Hello,

I would like to use this mkdocs plugin 
https://github.com/soxhub/mkdocs-plugin-commonmark
"A plugin for mkdocs that swaps python-markdown for mistletoe to bring CommonMark support to mkdocs."
But it does not work properly because I have an error when add the plugin name in the mkdocs.yml file

This plugin does not appear in the mkdocs plugin page. Why ?

Thanks

**Comment by oprypin** [comment]
Umm I think you'll need to ask them

**Comment by pawamoy** [comment]
Feel free to send a PR to add the plugin on the [best-of-mkdocs](https://github.com/pawamoy/best-of-mkdocs) list. The wiki is also editable by anyone, you can add it there as well :slightly_smiling_face:
