### ISSUE TITLE
Feature Request: `on_cleanup` event type

### ISSUE THREAD

**Issue by steven-terrana** [mkdocs/mkdocs#2971]
Hello, 

I'm working on a plugin that creates temporary files that should be cleaned up at the end. 
i'm having an issue caused by `on_post_build` firing multiple times (as it should) during `mkdocs serve`. 
I'd like to propose an `on_cleanup` event type that runs once and only once at the end of either `mkdocs build` or `mkdocs serve`.

i'm happy to take a shot at implementing this first but would like some feedback on the idea before i try. 

<details><summary>alternatives considered</summary>

If i was able to determine the cli command that was executed (i.e., is this a `build` or a `serve`) within my implementation of `BasePlugin` then i'd have a suitable workaround - but i'm not seeing a way to cleanly determine this information. 

</details>

**Comment by pawamoy** [comment]
You could add an `on_serve` method to your plugin and set `self.serving = True` in there.

**Comment by steven-terrana** [comment]
unfortunately that doesn't work for this use case because of the ordering of events. 
the plugin creates files in the `docs` directory. 
I'm trying to clean them up at the completion of the command. 

because `on_serve` runs after `on_post_build`, i'd be deleting the files that may be needed again if something changes. 

From a performance perspective, it would be much better to defer cleaning up the files until the end of the command through an `on_cleanup` event.

**Comment by oprypin** [comment]
The issue that I see is, the `serve` command has no real "end" to it. It's not so reliable to detect Ctrl+C and do something then. Much more reliable to clean up right after a build.

And the other part is that MkDocs has been apparently shying away from even admitting that sharing state across builds can be a thing.

I would like to see your exact use case to convince me how it can be so important to not just clean up after every build.

---

And I agree that this suggestion can't work:

> You could add an `on_serve` method to your plugin and set `self.serving = True` in there.

**Comment by steven-terrana** [comment]
it's another take on aggregating content from multiple repositories. 

Prior to the build it clones the repositories (or if they already exist it does a git pull) within a temporary directory within `docs` so that as a user i can specify arbitrary locations within the navigation to add pages from multiple repositories. 

cleaning up in post build would mean needing to reclone the repositories every time a change occurs.

> the `serve` command has no real "end". It's not so reliable to detect Ctrl+C and do something then. Much more reliable to clean up right after a build.

I agree in general. But, to me, firing a common `on_cleanup` event post build and in the [catch/finally in serve.py](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/commands/serve.py#L104-L109) is at least a best-effort attempt. 

It could be documented that the `on_cleanup` event is a best effort for `serve` and works in most cases for a graceful shut down.

**Comment by oprypin** [comment]
Alright, that reasoning sounds good to me.

Just that at that point actually it would also make sense to make another change to the plugin system: keep the plugin object alive across builds. Because otherwise I was actually wondering: how *do* you realize in your case that it's the first build vs a followup build? And then somehow keep state between them. Off-hand I wouldn't know how to do it. Could you share?

**Comment by steven-terrana** [comment]
i haven't found anything that works. 
right now i'm taking the naive approach of "if the directory already exists, do a git pull" 

Agree that it would be really useful if the event functions in `BasePlugin` were given more context by both:
1. persisting the plugin object across the entire life of the command
2. passing in the command that was used `build`, `serve`, `new` etc

**Comment by squidfunk** [comment]
> Just that at that point actually it would also make sense to make another change to the plugin system: keep the plugin object alive across builds. Because otherwise I was actually wondering: how do you realize in your case that it's the first build vs a followup build? And then somehow keep state between them. Off-hand I wouldn't know how to do it. Could you share?

That would be awesome! Sharing state between builds would allow to make dirty rebuilds correct from a plugin perspective. I've had quite some fun building the built-in blog plugin for Material for MkDocs due to the inability to persist state in the plugin's scope.

**Comment by oprypin** [comment]
Cool!
So I will do it like that. 
There will be 3 one-time event methods: `__init__`, `on_startup(command: str)`, `on_shutdown()`.

Maybe the diretyreload part too.
Such feedback from plugin developers is very valuable 😊
dirtyreload is underused by me, so further such comments are also very welcome.

And.. will the source code of the blog plugin be possible to view or not? 😳

**Comment by squidfunk** [comment]
> And.. will the source code of the blog plugin be possible to view or not?

Of course, it's all Open Source, but you need to become a sponsor of my work, i.e. join the [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) program. The blog plugin will be reserved to sponsors until the [Piri Piri](https://squidfunk.github.io/mkdocs-material/insiders/#12000-piri-piri) funding goal is reached, as it's one of the biggest releases of the last two years. It was very tough to build, and I invested _a lot_ of time + there's probably more time that I need to pour into it once it gets adopted by users. You know how it is. Maintenance eats the most.

**Comment by oprypin** [comment]
* #2972
