### ISSUE TITLE
add option for strict mode format output to xUnit

### ISSUE THREAD

**Issue by anb0s** [mkdocs/mkdocs#2993]
When using strict mode it would be good to format the `WARNING` messages for parsing (e.g. with ´filename:line`) and generate xUnit compatible file to easily report in CI/CD systems like GitLab.

**Comment by tomchristie** [comment]
Suggest we close this as out of scope. If anyone is motivated by this, then welcome to [start a discussion](https://github.com/mkdocs/mkdocs/discussions) and provide some more substantial design details and demo example use cases.
