### ISSUE TITLE
Allow specifying verbosity in the config file

### ISSUE THREAD

**Issue by KevinMGranger** [mkdocs/mkdocs#3013]
I'm trying to diagnose an issue with a mkdocs plugin. I want verbose logs in the `readthedocs` build, but they don't let us specify `-v`. Putting a verbose option in the config file would fix that.

I acknowledge that this could be considered a readthedocs issue. I'm going to file an issue with them too-- hopefully both teams don't say it's the other's responsibility! 😆 

Edit: [readthedocs issue filed](https://github.com/readthedocs/readthedocs.org/issues/9678).

**Comment by oprypin** [comment]
MkDocs has a `-v` flag. You filed an issue on 'readthedocs' about the ability to specify this flag on 'readthedocs', so certainly it should be handled there
