### ISSUE TITLE
Link to paragraph on index.md breaks

### ISSUE THREAD

**Issue by odin568** [mkdocs/mkdocs#3015]
I try to link from a subpage to a paragraph on my root index.md:

`[MyLink](../index.md#contact)`

This results when clicking in a 404 trying to open the following URL:

`documentation#contact`

Correct would be to link to 

`documentation/#contact` (note the slash)

Just linking to the page itself works fine

`[MyLink](../index.md)`

`documentation/` (slash is in the link)

Anybody has a clue if I do anything wrong or if this is a bug?

I use mkdocs with Materials template. Can provide more if required.

**Comment by oprypin** [comment]
Hi. This sounds like something that's happening only in your specific case.
If you don't provide a way for me to see exactly what that case is, I can't start guessing.
Please provide a complete MkDocs site with `mkdocs.yml` that exhibits the problem, which page I should look at, what's going wrong there and what you expected to see instead.

**Comment by odin568** [comment]
Hi. Sorry for late reply. I stripped down the root issue into an example. The issue also happens with the default template, so not only with materials
[Documentation.zip](https://github.com/mkdocs/mkdocs/files/9857678/Documentation.zip)

**Comment by oprypin** [comment]
I see what's happening, OK. It is a general problem. Thanks for the report.

**Comment by odin568** [comment]
Thanks a lot for your effort! Looking forward to next release 🚀
