### ISSUE TITLE
Validate sub-command

### ISSUE THREAD

**Issue by userbradley** [mkdocs/mkdocs#3021]
I'm using mkdocs in a pipeline, and it would be awesome to have a command like the below

```shell
mkdocs validate
```

Which returns with either `ok` (`0`) or `failed` (`1`)

I know that we can use `mkdocs serve` or `mkdocs build` to do this, but both are a little annoying to deal with in a CI Pipeline.

Let me know if this does not seem like a usable feature!

**Comment by oprypin** [comment]
How exactly is `mkdocs build` annoying  and what exactly would `mkdocs validate` do differently?

**Comment by userbradley** [comment]
Sorry forgot to elaborate.

`build` will generate html files and write to disk

`serve` (especially in a CI pipeline) will create the site and serve it, which is then hard to escape from.

I would like the `validate` to check that the `mkdocs.yml` file is valid, and that the plugins as well as directories etc are valid.

**Comment by oprypin** [comment]
You can do `mkdocs build -d $(mktemp -d)`. Or just `mkdocs build` - I always do that in CI.

Unfortunately, I think this suggested command would create less value than overhead.

**Comment by userbradley** [comment]
I think you may be right on this one.

Thanks!
