### ISSUE TITLE
Mkdocs search plugin is unable to find Strings inside tables or long bodies

### ISSUE THREAD

**Issue by FranciscoMonteiro694** [mkdocs/mkdocs#3023]
Hi.

For some reason, the mkdocs search plugin is unable to search for a string inside a table. Is there any way to solve this?
I've tried to play with the "separator" configuration but unfortunately was unable to solve the issue.
I also found out that when the body is too large, the String doesn't appear on the search. However, if I use the browser ctrl + F to search, it appears both on the table and body.

I was using this page as reference https://www.mkdocs.org/dev-guide/plugins/

Thanks in advance for your help.

**Comment by rruiter87** [comment]
I have a similar problem [here](https://cookncode.com/TwinCatChangelog/tc3/#version-314020)

![image](https://user-images.githubusercontent.com/98890535/203719527-8d895f13-958e-4105-a9e1-0493d6cd6a8b.png)

Code text is sometimes ignored.

**Comment by FranciscoMonteiro694** [comment]
Hello,
Is there any update on this?

**Comment by pawamoy** [comment]
If you're using the Material for MkDocs theme, please reach out there, they use their own search plugin. If you're using one of the built-in themes, then no, there's no update :confused:

**Comment by pawamoy** [comment]
This probably won't be updated in the current search plugin (unless someone volunteers): lunr.js is unmaintained. For Material for MkDocs, see this issue: https://github.com/squidfunk/mkdocs-material/issues/6632. There's work in progress to build a new, better default theme, as well as to build a powerful, standalone search plugin (by @squidfunk). We'll close this as not planned, feel free to comment further.
