### ISSUE TITLE
After deployment javascript error: Uncaught TypeError: Cannot read properties of undefined (reading 'enable') at window.onload ((index):2030:39)

### ISSUE THREAD

**Issue by MircoBabin** [mkdocs/mkdocs#3036]
1. mkdocs build
2. deploy the website to a real webserver connected to the internet
3. browse the website. I observed the navigation was acting weird, with sometimes to much whitespace. I observed the javascript error in the javascript console

---

In the javascript console this error pops up:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'enable')
    at window.onload ((index):2030:39)
worker.js:57 All search scripts loaded, building Lunr index...
worker.js:84 Lunr index built, search ready
```
---

It seems SphinxRtdTheme.Navigation.enable(true); is executed before the script(s) are loaded.

---

![image](https://user-images.githubusercontent.com/8981285/200539171-7c877277-2cfc-4c6f-a27b-763959a5653f.png)

---

Configuration

```
site_name: Trip API
theme: readthedocs
extra_css: [extra.css]
nav:
- Introduction: 'index.md'
- Javascript Route calculation library: 'TripSoftwareModuleKm_v2.md'
- Portal Orderrequest (price): 'portal-orderrequest.md'
- Trip Touroperating: 'trip-touroperating.md'
- Requests [general]: 'request.md'
- Responses [general]: 'response.md'
```

**Comment by pawamoy** [comment]
Closing as stale, if you still encounter this please create a new issue with a reproducible example :slightly_smiling_face:
