### ISSUE TITLE
`gh-deploy` but don't push

### ISSUE THREAD

**Issue by keck-in-space** [mkdocs/mkdocs#3047]
Is there anyway to run `mkdocs gh-deploy` without pushing? Due to security issues around how my github repo is set up, I can't push from the command line in this way. It just errors out. I still like the fact that gh-deploy writes the site data to the correct branch however, and don't want to have to do that manually. I didn't see any override flag for pushing in the docs, but I wanted to check here. Thanks!

**Comment by keck-in-space** [comment]
https://github.com/mkdocs/mkdocs/blob/56b235a8ad43f2300d17f87e6fa4de7a3d764397/mkdocs/commands/gh_deploy.py#L132

I just changed this to `False` in the venv for the project and it will not attempt to push (just in case anyone else has this issue). It would still be nice to have this as a flag for gh-deploy. Perhaps a good PR for me later. 😄

**Comment by tomchristie** [comment]
No we don't have an option for that.
