### ISSUE TITLE
Markdown with liquid template is parsed unexpectedly

### ISSUE THREAD

**Issue by joshbranham** [mkdocs/mkdocs#3067]
We have examples in our markdown that include liquid templates. When rendering the docs, mkdocs appears to be parsing that liquid template.

Example of a markdown block using this:
````
### Examples

```liquid
{% capture category %}{{ entity | property_value: 'Category' }}{% endcapture %}
{% if category == 'Pants' %}
  Resolution A
{% elsif category == 'Shoes' %}
  Resolution B
{% else %}
  Unknown
{% endif %}
```
````

Error from mkdocs:
```
verbose: [docker/mkdocs] ERROR    -  Error reading page 'public/guides/workflow-templating.md': Command not supported: else
```

Is there a way to fully escape those code example blocks containing liquid templates such that mkdocs doesn't try to parse it?

**Comment by pawamoy** [comment]
Do you happen to use a plugin that would try and interpret this markup, such as mkdocs-macros-plugin for example :thinking:?

There's probably a Liquid tag similar to Jinja's `raw` tag, allowing to escape whole blocks of contents:

```liquid
{% raw %}
{% capture category %}{{ entity | property_value: 'Category' }}{% endcapture %}
{% if category == 'Pants' %}
  Resolution A
{% elsif category == 'Shoes' %}
  Resolution B
{% else %}
  Unknown
{% endif %}
{% endraw %}
```

**Comment by CasperGN** [comment]
@joshbranham did you ever come about a solution for this?
Stubled on the same issue also related to backstage.

**Comment by joshbranham** [comment]
> @joshbranham did you ever come about a solution for this?
> 
> Stubled on the same issue also related to backstage.

https://github.com/backstage/mkdocs-techdocs-core/issues/102
