### ISSUE TITLE
Document all configuration options

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#307]
Some of the [configuration options](https://github.com/tomchristie/mkdocs/blob/0.11.1/mkdocs/config.py#L10) are not documented.

- [x] `copyright`
- [x] `google_analytics` (only mentioned in the release-notes)
- [x] `repo_name`
- [x] `extra_css` (only mentioned in the release-notes)
- [x] `extra_javascript` (only mentioned in the release-notes)
- [x] `include_nav` (this is only supported by the mkdocs theme)
- [x] `include_next_prev` (this is only supported by the mkdocs theme)
- [x] `include_search` - This will be handled in #222.
- [x] `include_sitemap` - this feature doesn't exist next.

**Comment by EdyJ** [comment]
Just wanted to point out that google_analytics is implemented on the MkDocs theme only. Should I open  an issue on this?

**Comment by d0ugal** [comment]
@EdyJ Yes please, it should be added to the ReadTheDocs theme at least.
