### ISSUE TITLE
Feature: Allow external links in automatically generated nav

### ISSUE THREAD

**Issue by bluenick2k17** [mkdocs/mkdocs#3074]
# Allow external links in automatically generated `nav`

One problem statement that I've had with Mkdocs is that I do not have an ability to add external links to automatically generated navigation (when you don't provide a `nav` object in the configuration file). I'm interested to get feedback on adding this feature.

If it would be desired, then I am happy to work on getting this implemented.

## Proposal

The easiest solution I can think of would be to allow an additional kind of file in the site generation, `*.url` files. If a `*.url` file is found in the regular docs directory structure, then a [link object](https://www.mkdocs.org/dev-guide/themes/#link) will be added to the nav object with the `title` being the name of the file and the `url` being read from the file.

Here is a small example directory structure:
```
home/
about/
├─ index.md
├─ My_Link.url
```

Contents of `My_Link.url` (which should be a [known format](https://fileinfo.com/extension/url) on Windows/Mac/Linux operating systems), and is the default for internet shortcuts on Windows:
```
[InternetShortcut]
URL=https://github.com
```

**Comment by wilhelmer** [comment]
I like the idea of individual `*.url` files following the "when `nav` is omitted, each file is a nav entry" paradigm, but using this Windows/IE-derived INI-based clunky file format doesn't feel pretty modern to me.

Also, I think using the file name as the nav title will cause all kinds of problems. You already illustrated that in your sample directory structure – should `My_Link.url" create a nav entry of "My Link"? So you'll drop the underscores during build? What if I do want an underscore in my title? What if I want some special char that my web server doesn't support? What if I don't want capitalization in my file names?

So I'd at least add a `title=My Link` entry in the url file. But I think I'd rather not use the url format at all and go for some kind of hidden dot file (`.url`, similar to Git's `.gitconfig` or `.gitmodules` files) that contains all external links for a directory.

**Comment by bluenick2k17** [comment]
@wilhelmer thanks for the input! Thoughts below:

> I like the idea of individual `*.url` files following the "when `nav` is omitted, each file is a nav entry" paradigm, but using this Windows/IE-derived INI-based clunky file format doesn't feel pretty modern to me.

It's not a great format, and not a big deal to me if it was implemented with some other thing instead (maybe an arbitrary `.link` extension for example with a simpler file). The reason why I chose `*.url` specifically is because it provides windows users the ability to natively add links by dragging bookmarks, while still providing MacOS/Linux users the ability to open them by clicking on them. Although its clunky, it at least provides some native simplicity for some users. For those not able to do so natively, link files can still be created without too much hassle and can be double-click-opened.

> Also, I think using the file name as the nav title will cause all kinds of problems. You already illustrated that in your sample directory structure – should `My_Link.url" create a nav entry of "My Link"? So you'll drop the underscores during build? What if I do want an underscore in my title? What if I want some special char that my web server doesn't support? What if I don't want capitalization in my file names?
>
> So I'd at least add a `title=My Link` entry in the url file. But I think I'd rather not use the url format at all and go for some kind of hidden dot file (`.url`, similar to Git's `.gitconfig` or `.gitmodules` files) that contains all external links for a directory.

Yes, I believe the name `My_Link.url` should create a nav entry of `My Link`. This is the [same logic](https://github.com/mkdocs/mkdocs/blob/56b235a8ad43f2300d17f87e6fa4de7a3d764397/mkdocs/utils/__init__.py#L377-L385) that the markdown pages use to do their titles when building nav. I would rather keep Pages working similar to links so it is intuitive.

IMO - I don't think that having multiple URLs in one file would really remain in the same spirit as the pages with generated nav.

**Comment by ultrabug** [comment]
Did you consider adding this feature to interested users as part of an external plugin @bluenick2k17 ?

I have a doubt that it should be a core MkDocs feature tbh.
