### ISSUE TITLE
Feature: supress 0.0.0.0 dev_addr warning 

### ISSUE THREAD

**Issue by tomers** [mkdocs/mkdocs#3079]
I am running `mkdocs` as docker:
```
docker run --rm -t -p 8000:8000 -v $(PWD):/docs squidfunk/mkdocs-material
```
However. I get the following error
```
WARNING  -  Config value 'dev_addr': The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server.
            However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
INFO     -  Building documentation...
```
This error is reasonable when running the server in the host, but it is not reasonable when it is being run in a container, since in the default docker network, we must serve 0.0.0.0.

In order to supress this warning, I had to run in host network, and override the default `CMD` (note that I use [mkdocs-material/](https://squidfunk.github.io/mkdocs-material/)):
```
docker run --rm -t -p 8000:8000 -v $(PWD):/docs --network host squidfunk/mkdocs-material serve --dev-addr=127.0.0.1:8000
```

I think it would be useful to just add a configuration option or an environment variable which supresses that warning.

**Comment by pete312** [comment]
Judging by this tread https://github.com/mkdocs/mkdocs/issues/2108 i doubt you are going to get this request.  I'm not sure why you need that either.  It's a warning that flask also spits out. Its not stopping you from doing stuff.

**Comment by tomers** [comment]
> Judging by this tread #2108 i doubt you are going to get this request. I'm not sure why you need that either. It's a warning that flask also spits out. Its not stopping you from doing stuff.

Ok, got it. I'll stick with my current workaround. Thanks!
