### ISSUE TITLE
Support .order file

### ISSUE THREAD

**Issue by rafalschmidt97** [mkdocs/mkdocs#3080]
Hi, do you have any plans to add or have seen an extension which adds support for `.order` file?

I would love to move from azure wiki pages to mkdocs but don't want to manually create `nav:` section.
https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops#order-file

The .order file defines the sequence of pages within the wiki. The following visual shows an example of a wiki TOC and it's corresponding .order file.
The default hierarchy is in alphabetical sequence, however you can change this hierarchy in the .order file. For more information about how to reorder wiki pages, see [Add and edit wiki pages, Reorder a wiki page](https://learn.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=azure-devops#reorder-a-wiki-page).

**Comment by pawamoy** [comment]
If you have just one `.order` file, converting it to MkDocs navigation is pretty easy.
If you have order files in many subdirectories (not sure that's how they are used), there's [mkdocs-literate-nav](https://github.com/oprypin/mkdocs-literate-nav) which you could find interesting.

**Comment by oprypin** [comment]
There is no plan to support this. A plugin could do it.
