### ISSUE TITLE
mkdocs serve windows 10 doesn't work

### ISSUE THREAD

**Issue by Gresliebear** [mkdocs/mkdocs#3084]
I created mkdocs documents folder with the command 

`mkdocs new my-project`

and then I ran 'mkdocs serve' I will get 

```
mkdocs : The term 'mkdocs' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was         
included, verify that the path is correct and try again.
At line:1 char:1
+ mkdocs serve
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (mkdocs:String) [], CommandNotFoundException
 
```

I solved my own issue 

if you followed the[ installation instructions ](url)

run 

```
python -m pip install mkdocs
python -m mkdocs 
```

And modify the command for Windows from 

`mkdocs serve`

to

`python -m mkdocs serve `

it will work!

![image](https://user-images.githubusercontent.com/13157730/210245250-3c429c33-3985-4f7b-b9fd-464f4c4dacb6.png)

I just wanted to make this issue to save others time looking for a solution because I didn't find one immediately on google

**Comment by pawamoy** [comment]
When you install a Python package with pip, it adds an executable path in the Scripts folder of your current Python environment (be it the system one, a pyenv one, or a manually created virtual environment). You need to add this Scripts folder to your PATH environment variable to be able to call `mkdocs` directly.
