### ISSUE TITLE
Lost edit icon in mkdocs 1.4.2

### ISSUE THREAD

**Issue by floriandeboissieu** [mkdocs/mkdocs#3095]
Hi and many thanks for this very useful package.

In last mkdocs version (1.4.2) the edit icon (pencil) disappeared. I tested back with mkdocs 1.4.1, the edit icon is there on top right of each page.

The config on which I tested includes `repo_url` and `edit_uri` and my `repo_url` is starting by https://gitlab.com.

**Comment by oprypin** [comment]
You'll have to share a site (complete sources) on which this happens so I can see it for myself

**Comment by martinbira** [comment]
@floriandeboissieu You don't happen to use the Material for MkDocs theme and upgrade to version 9? If so, see https://squidfunk.github.io/mkdocs-material/upgrade/#upgrading-from-8x-to-9x regarding the edit icon.

**Comment by floriandeboissieu** [comment]
@martinbira You are right, it was due to Material update, sorry and many thanks to you and @oprypin for your reactivity.

**Comment by AlexFreik** [comment]
What was the solution? I recently rebuild my docs with new material version and the edit page "pencil" disappeared...
