### ISSUE TITLE
Code block scroll bars

### ISSUE THREAD

**Issue by jkmacc** [mkdocs/mkdocs#31]
I see that long lines in a code block will wrap, like this (Chrome on Mac):

![image](https://f.cloud.github.com/assets/874390/2196517/91725ba4-98b0-11e3-9632-fe4969029de6.png)

instead of use horizontal scroll bars, like this:

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu urna fringilla, pellentesque mi in, rhoncus ipsum. Nullam est mauris, ornare sed hendrerit nec, rutrum in dui.

This may be just a preference, but I think scroll bars make code blocks easier to read.  Is there a way to enable scroll bars, or is just how Python Markdown renders?

**Comment by d0ugal** [comment]
This appears to be resolved in master
