### ISSUE TITLE
Admonitions break numbered list

### ISSUE THREAD

**Issue by kamieniarz** [mkdocs/mkdocs#3106]
If I add admonition in the middle of numbered list it breakes it. Example of the code:
```
1. Something1
2. Something2
3. Something3
!!! info inline end "admonition test"
5. Something5
6. Something6
```

As the output there's sth like:
1. Something1
2. Something2
3. Something3

admonition test

1. Something5
2. Something6

For the record: images don't break the thing

**Comment by facelessuser** [comment]
Admonitions are blocks, and because it is a block, it is not part of the paragraph preceding it. And subsequent blocks in a list should be indented 4 spaces.

```
1. Something1
2. Something2
3. Something3

    !!! info inline end "admonition test"

5. Something5
6. Something6
```

**Comment by kamieniarz** [comment]
@facelessuser if I do so `!!! info inline end "admonition test"` becomes a part of `Something3` so in fact admonition doesn't exist

**Comment by kamieniarz** [comment]
As I said in the issue: I want to have a list with 1-6 points with admonition in the middle. Currently I can't do it cause admonition splits the numbers of the list to 1-3 and 1-2

**Comment by oprypin** [comment]
I think you can just use this extension and the new list will just start from 5 like you want
https://python-markdown.github.io/extensions/sane_lists/

**Comment by oprypin** [comment]
And what @facelessuser is saying is the **actual** answer but it seems like you are not really trying to follow it
