### ISSUE TITLE
<h1> appears randomly on some pages but not others

### ISSUE THREAD

**Issue by thomiz** [mkdocs/mkdocs#3108]
Some of my generated pages includes a h1page tiltle but some do not. file:

~~~html
<h1>Begreper</h1>
~~~

They are configured the same way in the mkdocs.yml

~~~
- Prinsipper og metode:
   - Begreper: Begreper.md
   - Metode og forvaltning: Metode-og-forvaltning.md
   - Arkitekturprinsipper: Arkitekturprinsipper.md
~~~

And no Title is defined in the markdown of any of them.

**Comment by thomiz** [comment]
Looks like the problem is as follows:
* pages without heading in the markdown on level 2 or 3, title is not used for generating h1 heading in the html
* pages with heading in markdown on level 2 or 3, uses the title for generating a h1 heading in the html
* pages with markdown heading on level 1, uses the markdown heading for h1 heading in the html (title is not used)

~~~md
# heading level 1
## heading level 2
### heading level 3
~~~

**Comment by oprypin** [comment]
I think this is specific to mkdocs-material. Otherwise let me know which theme.

**Comment by thomiz** [comment]
You might be right. It is using mkdocs-material the problem appears. I will try adding an issue to material repo instead.
