### ISSUE TITLE
Value is not accepted. Valid values: "blog"

### ISSUE THREAD

**Issue by QuantFreedom1022** [mkdocs/mkdocs#3113]
i am getting vscode telling me that there are some problems with trying to add some plugins to my code ... it says i need to type something like blog but when i type blog it gives me an error when i want to go to the serve because i am not a sponsor therefore i don't have the pluggin 

how do i get it to stop saying pluggins i do actually have installed are causing an error

![image](https://user-images.githubusercontent.com/95321908/214948438-98132cea-3d0a-4304-b84a-8d0e412c3278.png)

**Comment by pawamoy** [comment]
You are probably using the JSON schema provided by the Material for MkDocs theme. Note that this schema does not contain all MkDocs plugins. It actually only contains a few. You could ask the maintainers of mkdocs-video and mkdocs-section-index (@oprypin) to send PRs to mkdocs-material, adding their own schema to the global one.
