### ISSUE TITLE
problem:I can't use strikethrough in the website which i made

### ISSUE THREAD

**Issue by leiliusi** [mkdocs/mkdocs#3122]
I can't use strikethrough in the website which i made.

**Comment by pawamoy** [comment]
Please show your mkdocs.yml configuration and some Markdown contents.

**Comment by leiliusi** [comment]
`site_name: leiliusi的妙妙屋
site_url: https://leiliusi.github.io
theme: readthedocs

nav:
- Home: index.md
- 天国的luogu题解:
    - P1469: ac.md
`

the website is in"https://leiliusi.github.io/"
.Andthe problem is in "P1469" .

**Comment by pawamoy** [comment]
Please show the Markdown you're using to write strikethrough text. You're probably missing the `pymdownx.tilde` extension in your configuration, see https://facelessuser.github.io/pymdown-extensions/extensions/tilde/.

**Comment by leiliusi** [comment]
I have sovled my problem.Thank you.The way is useful for me.

Timothée Mazzucotelli ***@***.***> 于2023年2月12日周日 19:20写道：

**Comment by pawamoy** [comment]
Great! Can you close this issue then? Thanks
