### ISSUE TITLE
How to remove font-awesome?

### ISSUE THREAD

**Issue by WangPingGang** [mkdocs/mkdocs#3128]
I don't want include font-awesome in my Local Files deploy to reduce files size? How can i do it?

**Comment by pawamoy** [comment]
You could either use a short shell script to delete them prior to deployment, or write a [hook](https://www.mkdocs.org/user-guide/configuration/#hooks) that removes these files/folders from the files collection using the [`on_files`](https://www.mkdocs.org/dev-guide/plugins/#on_files) event.

@tomchristie I'll go ahead and close this, but feel free to reopen if you want to consider this for the current themes or for a new one :slightly_smiling_face:
