### ISSUE TITLE
Readthedocs Theme: Force break of inline code

### ISSUE THREAD

**Issue by ePirat** [mkdocs/mkdocs#313]
Using the ReadTheDocs theme, inline code

    `code`

should be forced to break, so that it does not break the responsive layout.

**Comment by d0ugal** [comment]
So, this is an issue if the line is too long? Any ideas how you would fix it in CSS?

**Comment by ePirat** [comment]
Just use `word-wrap: break-word;` so it will break even in the middle of words.

**Comment by tomchristie** [comment]
Wouldn't we want horizontal scrolling instead. I don't think we should *ever* wrap code lines.

**Comment by ePirat** [comment]
@tomchristie I strongly disagree. Scrolling might be fine for blocks of code (even there most of the time it annoys me), but it definitely isn't for inline code.
Indentation should not matter for inline code, so I see absolutely no problem with breaking it to the next line.
What actually never should be done is logical separation, i.e. `if (superman)` vs. `if (super-[newline]man`. So setting `hyphens: none;` might be a good idea for code.

**Comment by tomchristie** [comment]
A screenshot example would probably be a good idea. I'd expect inline code to fall onto the next line as a single block if it's too long, no?

**Comment by d0ugal** [comment]
I think the issue is when the single block is winder than the width of the device.

**Comment by ePirat** [comment]
Currently:

![Screenshot of current behaviour](https://cloud.githubusercontent.com/assets/323210/5635693/b0a389ba-95eb-11e4-9b0a-2621ef2cbdc6.png)

With `word-wrap: break-word;`

![Screenshot](https://cloud.githubusercontent.com/assets/323210/5635698/cd2779f2-95eb-11e4-9300-0bf63aecd84b.png)

**Comment by tomchristie** [comment]
Okay, that's super helpful. Second case to compare here would be when the block is inline with text before.

Say we have...

    this is some text `and-an-`
    `[newline]inline-block` more text

We wouldn't want that kind of wrapping. However [this](http://www.w3schools.com/cssref/tryit.asp?filename=trycss3_word-wrap) makes it look to me like the `break-word` behavior is correct.

![screen shot 2015-01-07 at 09 03 21](https://cloud.githubusercontent.com/assets/647359/5643114/177a7c74-964c-11e4-9049-c3ff6dcf6aeb.png)

The long word still starts on a newline, and only breaks if it's longer than the entire viewport which is what I'd want to see.
