### ISSUE TITLE
code blocks display error

### ISSUE THREAD

**Issue by mcxinyu** [mkdocs/mkdocs#3130]
For example, the following code is correct in github, but wrong in mkdocs.

    ```http request
    GET https://github.com/api/auth/test
    Authorization: Bearer *********
    ```

github:
![image](https://user-images.githubusercontent.com/9566116/221342318-8c61731e-e431-431d-b86e-c83bd37d3153.png)

mkdocs:
![image](https://user-images.githubusercontent.com/9566116/221342353-b9f30b48-d197-4904-b033-6cf3a5a01af3.png)

**Comment by jasonren0403** [comment]
try only use http

```md
```http
GET https://github.com/api/auth/test
Authorization: Bearer *********
```
```

**Comment by mcxinyu** [comment]
> try only use http
> 
> ```lisp
>     ```http
>     GET https://github.com/api/auth/test
>     Authorization: Bearer *********
>     ```
> ```

The highlight effect does not change (invalid)

![image](https://user-images.githubusercontent.com/9566116/221733319-5aca3ceb-3090-420b-9e0e-c56c8f44cd54.png)


expected effect
![image](https://user-images.githubusercontent.com/9566116/221733447-32333202-fbec-4c4c-8c21-9077df330700.png)

**Comment by mcxinyu** [comment]
any progress?

**Comment by pawamoy** [comment]
Pygments only provide the `http` lexer. Try to open an issue there maybe.
