### ISSUE TITLE
nav layout in documentation causing errors

### ISSUE THREAD

**Issue by SamIsConfused69** [mkdocs/mkdocs#3131]
I'm following the nav documentation at: https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation

My config file is as follows:
```
site_name: Music Theory

site_url: 

theme:
 name: material

features: navigation.top

nav:
- Home: index.md
- About: about.md
- 'Four Part':
- Introduction: ./fpvl/introduction.md
- 'Basic Chords': ./fpvl/basic-chords.md
- Cadences: ./fpvl/cadences.md
```

'Four Part' should be a parent "section", and Introduction, Basic Chords and Cadences the child items in the menu.

But this causes the following error in terminal:
`ERROR    -  Config value 'nav': Expected nav to be a list, got None
Aborted with 1 Configuration Errors!
 `
Any ideas what I'm doing wrong? I have the latest versions of Python and MKDocs installed. Thanks!

**Comment by pawamoy** [comment]
You need to indent the items below "Four part" to make them nested pages. It's supposed to be intuitive but YAML has not always been praised for its simplicity :smile:

**Comment by SamIsConfused69** [comment]
Thanks for the reply! 

I updated my config to:
```
site_name: Music Theory

site_url: 

theme:
 name: material

features: navigation.top

nav:
- Home: index.md
- About: about.md
- 'Four Part':
 - ./fpvl/introduction.md
 - Basic Chords: ./fpvl/basic-chords.md
 - ./fpvl/cadences.md
 - ./fpvl/supertonic-triad.md
```

But that causes the following error:
```
Sam-iMac:Music-Theory Sam$ mkdocs serve
Error: MkDocs encountered an error parsing the configuration file: while parsing a block mapping
  in "/Users/Sam/Documents/Music Theory/Music-Theory/mkdocs.yml", line 1, column 1
expected <block end>, but found '<block sequence start>'
  in "/Users/Sam/Documents/Music Theory/Music-Theory/mkdocs.yml", line 14, column 2
```

**Comment by pawamoy** [comment]
You need at least two spaces of indentation.

**Comment by SamIsConfused69** [comment]
Wow... I was fiddling with this for hours today and last night... you're totally right.

Thank you for the help!

**Comment by pawamoy** [comment]
You're welcome :) thank you for coming back and closing the issue!
