### ISSUE TITLE
CI linter + hatch run all fails currently

### ISSUE THREAD

**Issue by hendrikp** [mkdocs/mkdocs#3138]
There seems to be some change/update to the used linter/ci scripts. Which makes the CI checks fail.

`mkdocs/livereload/__init__.py:140: error: Cannot assign to a method  [assignment]`

I noticed it during submitting a PR. (multiple other PR are also blocked by that one). See https://github.com/mkdocs/mkdocs/actions/runs/4331570345/jobs/7563490326

Maybe a small fix, but would be best if someone who knows that line can adjust it.

**Comment by oprypin** [comment]
New version of mypy. Fixed in https://github.com/mkdocs/mkdocs/commit/25cfda3fe76371a8805a05cda7834178623a7338
