### ISSUE TITLE
Documentation for private functions

### ISSUE THREAD

**Issue by chechu-arias** [mkdocs/mkdocs#3147]
Hi, I would like to add to the documentation of Mkdocs my private functions without changing the function name. Can I do this? And if so, how would I do that?

**Comment by pawamoy** [comment]
You might have found out this is actually related to mkdocstrings and not MkDocs, and the way to do that is to change/reset the default filters, documented here: https://mkdocstrings.github.io/python/usage/#globallocal-options (search for "filters").
