### ISSUE TITLE
The first line of the md file cannot use this format A:B, otherwise this line will not be displayed.

### ISSUE THREAD

**Issue by Zacharia2** [mkdocs/mkdocs#3160]
The first line of md file in Mkdocs cannot use this format A:B, otherwise this line will not be displayed. Where A and B are consecutive strings of any length.

Like this: 

aaa:bbbbbb

**Comment by pawamoy** [comment]
`aaa:bbbb` is probably interpreted as [front-matter](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data). Per the docs, try to add a blank line at the top to disable parsing this line as metadata.

**Comment by Zacharia2** [comment]
Yes, thanks
