### ISSUE TITLE
[Feature Request] Add way to treat `.mjs` files as JavaScript

### ISSUE THREAD

**Issue by andynameistaken** [mkdocs/mkdocs#3164]
- Currently (`mkdocs==1.4.2`) there is no possibility of [treating `.mjs` files as JavaScript](https://github.com/mkdocs/mkdocs/blob/56b235a8ad43f2300d17f87e6fa4de7a3d764397/mkdocs/structure/files.py#L268-L270). Do you have plans to add support for them?
- Current implementation doesn't allow [`mermaid.js` mind-map support](https://github.com/squidfunk/mkdocs-material/discussions/5125#discussioncomment-5168717)
- [Probably it is good to consider how to handle ems modules in near future](https://github.com/squidfunk/mkdocs-material/discussions/5125#discussioncomment-5168585)

**Comment by oprypin** [comment]
What *does* it mean to support mjs files?

* Just adding .mjs to the place that you linked?
https://github.com/mkdocs/mkdocs/blob/56b235a8ad43f2300d17f87e6fa4de7a3d764397/mkdocs/structure/files.py#L268-L270

* Does it intersect in any way with https://github.com/mkdocs/mkdocs/issues/2850 ?

* Anything else?

Please spare no details in your explanation, I really don't know much on this topic.

**Comment by oprypin** [comment]
I'm still hoping to receive further info on this issue, otherwise I don't know how to proceed

**Comment by andynameistaken** [comment]
Hi, sorry for long hiatus. Sadly, everything I know is  in this [link](https://github.com/squidfunk/mkdocs-material/discussions/5125#discussioncomment-5168717). 
From what I understand .mjs files are JavaScript files used by MermaidJS for generating diagrams.  I don't know if adding support for extension allows script execution (although it looks like it) - I am just a user of [material theme](https://github.com/squidfunk/mkdocs-material) for mkdocs and I wasn't able to render mind maps. @squidfunk will have more needed insight into this issue.

**Comment by squidfunk** [comment]
Thanks for the mention! If a file in `extra_js` has an `.mjs` ending, we need to add `type=module` to the `script` tag. This would need to be supported by themes. However, MkDocs would need to treat `.mjs` files as JavaScript files and copy them as well. Once MkDocs will copy `.mjs` files, we can add support in Material for MkDocs to add `type=module`.

**Comment by oprypin** [comment]
This piece of code keeps getting linked:

https://github.com/mkdocs/mkdocs/blob/56b235a8ad43f2300d17f87e6fa4de7a3d764397/mkdocs/structure/files.py#L268-L270

But, fun fact, it is never used. There is currently no behavior in MkDocs that treats a `.js` file format any differently than any other `.foo` file format.
(Technically, in `mkdocs serve` there actually *is* such a distinction, but that's separate)


So nothing is stopping themes from already hardcoding a different treatment for files in `extra_javascript` ending `.mjs`.
But would be better if themes *didn't* hardcode this and there was a standard way to define this.

* How themes look now:
  ```jinja
    {%- for path in extra_javascript %}
      <script src="{{ path }}"></script>
    {%- endfor %}
  ```
* BAD: hardcoding option
  ```jinja
    {%- for path in extra_javascript %}
      <script src="{{ path }}"{% if path.endswith('.mjs') %} type="module"{% endif %}></script>
    {%- endfor %}
  ```
* GOOD: wait for a MkDocs update and gather the info from it.
  ```jinja
    {%- for script in extra_javascript %}
      <script src="{{ script.url }}"{% if script.type %} type="{{ script.type }}"{% endif %}></script>
    {%- endfor %}
  ```
  Or, in fact, why not standardize it:
  ```jinja
    {%- for script in extra_javascript %}
      {{ script |script_tag }}
    {%- endfor %}
  ```
* OK: be ready for a MkDocs update but also hardcode the behavior in the meantime.
  ```jinja
    {%- for script in extra_javascript %}
      <script src="{{ script }}"{% if script.type == 'module' or (script.type is undefined and script.endswith('.mjs')) %} type="module"{% endif %}></script>
    {%- endfor %}
  ```

**Comment by squidfunk** [comment]
> ``` jinja
>   {%- for script in extra_javascript %}
>     {{ script | script_tag }}
>   {%- endfor %}
> ```

AFAIK, there's no canonical way to know whether a file is ESM or CJS without analyzing its contents or relying on some external information like `type: module` in `package.json`. I understand this proposal in a way that the `script_tag` filter decides whether to add type="module"` or not. I don't think that will work.

**Comment by oprypin** [comment]
The higher-level view of this plan is to add this functionality to MkDocs:

```yaml
extra_javascript:
  - some_cjs.js
  - some_implicitly_esm.mjs
  - path: some_explicitly_esm.js
    type: module
```

**Comment by oprypin** [comment]
Linked a pull request accordingly.
