### ISSUE TITLE
Empty link target should not assume link to same page 

### ISSUE THREAD

**Issue by pesho-ivanov** [mkdocs/mkdocs#3165]
The empty link `[text]()` doesn't seem to be documented in [Markdown](https://daringfireball.net/projects/markdown/syntax#link). Currently mkdocs interprets it as a link to the current page (similarly to how github does).

Nevertheless, I find the approach of [mdBook](https://github.com/rust-lang/mdBook) much better: it is interpreted as a missing (draft/todo) link and is visualized pale:
![image](https://user-images.githubusercontent.com/110152/227528432-13e339bf-bbd6-4e02-8c2e-222bde6ad8e8.png)

**Comment by oprypin** [comment]
If GitHub does this, I'm not sure why MkDocs shouldn't do the same.

Furthermore, MkDocs does not use Markdown links for the navigation chapters, so the part about using this for "paleness" is not applicable.
