### ISSUE TITLE
Unhighlighted code breaks the RTD theme

### ISSUE THREAD

**Issue by ePirat** [mkdocs/mkdocs#319]
When using the `no-highlight` class to prevent highlight.js to guess a specific highlighting, it works fine, but causes the Read the Docs theme to break, due to the absence of the hljs class I guess:

```html
<pre>
    <code class="no-highlight">[…]</code>
</pre>
```

looks like this:

![Screenshot illustrating the problem](https://cloud.githubusercontent.com/assets/323210/5634871/0073d2d6-95e4-11e4-87d3-d64941745b13.png)

**Comment by ePirat** [comment]
This happens too when javascript is disabled.

**Comment by d0ugal** [comment]
Fixed by https://github.com/mkdocs/mkdocs/pull/416
