### ISSUE TITLE
customize `site_url` config key via build arguments

### ISSUE THREAD

**Issue by kskarthik** [mkdocs/mkdocs#3197]
I don't know if this can be done via an other way already but, This option would be helpful for CI/CD setup.

Hugo has this kind of option:

The command can be like: `mkdocs build --site_url=https://example.com/page/`

For now i did a hack with `sed` https://gitlab.com/kskarthik/lts-docs/-/blob/main/.gitlab-ci.yml

But a build flag would be really helpful. I am willing to work on this & submit the patch myself with little guidance :grinning:

**Comment by pawamoy** [comment]
I believe you can do that using an environment variable: https://www.mkdocs.org/user-guide/configuration/#environment-variables.

```yaml
site_url: !ENV [SITE_URL, "https://default.url.com/"]
```

**Comment by kskarthik** [comment]
This is great! Thank you for the doc link!
