### ISSUE TITLE
could we remove the limitation of `Markdown <3.4` in pyproject.toml?

### ISSUE THREAD

**Issue by dantezhu** [mkdocs/mkdocs#3214]
python-markdown added a lot of useful features after 3.4, if there is no conflict, could we remove the limitation of `Markdown <3.4` in pyproject.toml?

**Comment by dantezhu** [comment]
thanks you very much

**Comment by oprypin** [comment]
Could you name those features? My impression was quite the opposite.

**Comment by dantezhu** [comment]
> Could you name those features? My impression was quite the opposite.

emm, such as add support of customizing footnotes' format:

```
SUPERSCRIPT_TEXT: The text string that links from the position in the document to the footnote definition. Defaults to {}, i.e. only the footnote’s number.
```

Thus I can change the footnotes' format:
```
'footnotes': {
    'SUPERSCRIPT_TEXT': '[{}]',
},
```
<img width="406" alt="image" src="https://user-images.githubusercontent.com/1105212/236610026-71761407-4b27-4014-bfa5-81b89772b95a.png">

**Comment by dantezhu** [comment]
> Could you name those features? My impression was quite the opposite.

@oprypin It seems that you don't like the new version of python-markdown very mouch, would you mind telling me why?
