### ISSUE TITLE
Inheritance, deep merging, and arrays

### ISSUE THREAD

**Issue by pawamoy** [mkdocs/mkdocs#3216]
I'm using configuration inheritance as explained in the Material for MkDocs docs: https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#built-in-plugins. UPDATE: docs contents changed since then.

To avoid duplicating the whole `plugins` config in both files (`mkdocs.yml` and `mkdocs.insiders.yml`), I switched to the map YAML syntax for plugins. Unfortunately the syntax is not understood by the JSON schema provided by Material for MkDocs. This is annoying, but not critical. I opened an issue on their repo: https://github.com/squidfunk/mkdocs-material/issues/5455.

It raised another, more important issue: [some plugins can be registered more than once](https://github.com/mkdocs/mkdocs/pull/3027). This is officially supported by MkDocs. And this is incompatible with the map syntax, as declaring your plugins as a map does not allow you to register a plugin more than once. So now I want to go back to using a list rather than a map, since I might need to declare some plugins twice later.

After I read everything I could about the subject, here's what I think and what I would like: to avoid duplication between config files, I'd like MkDocs to **also merge lists/arrays**. This can be done following this logic:

- for each item, if it is not present in the parent list, add it (by "present", we mean to check for presence of its main, single dict key)
- if it is present, and is not recognized as supporting multiple instances, merge it in the parent (it will require to find the right item in the parent list, but that's easy)
- if it is present, and recognized as supporting multiple instances, add it to the parent list without merging

Current code is using mergedeep, while deepmerge seems like it provides the strategies for this, see https://github.com/toumorokoshi/deepmerge. Or we could start with something simpler like just concatenating arrays.

Another, more generic solution I thought about would be to create a way for users to add their own YAML tags/features to the MkDocs YAML loader, for example with specific Python entry-points (just like MkDocs plugins, but for the YAML loader). It would for example allow user to add an `!include` tag to the loader that could be used to solve this particular issue.

Or this feature could help also: https://github.com/mkdocs/mkdocs/issues/2624

WDYT?

/cc @squidfunk

**Comment by oprypin** [comment]
>  I'd like MkDocs to also merge lists/arrays

Then there's no way to *replace* a list from the parent config, only add to it. A behavior that people may be relying on, meaning it's an unacceptable breaking change.

I've been looking more towards `!include`, though it has its own problems.

**Comment by squidfunk** [comment]
I'm not sure whether inheritance accounts for [anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/) (keeping them), but if it would, we could just use anchors to deduplicate configuration. I'm using them heavily when defining layouts in YAML in the new social card plugin, as the `yaml` package supports them. I second that deep merging arrays is probably not a good idea.

**Comment by tomchristie** [comment]
I'm reviewing this and having a hard time wrapping my head around the request.
(I can see the rest of you have figured it out, but allow me a little grace here. 😅)

Could you give a super simple example of a config that you would like to behave differently?

**Comment by pawamoy** [comment]
Sure!

```yaml
# mkdocs.base.yml
plugins:
- plugin1
    config: a
- plugin2
    config: b
- plugin3
- pluginN
- plugin20
```

```yaml
# mkdocs.yml
INHERIT: mkdocs.base.yml

plugins:
- plugin_that_only_exist_when_material_insiders_in_used
# I don't want to duplicate the whole plugin list
# so I wanted MkDocs to merge the two plugin lists
# instead of having the base one completely overwritten by this one
```

Note that since then, @squidfunk released the `group` plugin which solves the initial situation differently :slightly_smiling_face: 

I believe users who upvoted the issue had the same use-case, which is solved by the `group` plugin, so we can probably close this.

**Comment by Blacksmoke16** [comment]
I guess another use case would be for the https://squidfunk.github.io/mkdocs-material/plugins/projects plugin. I.e. being able to inherit a set of base plugins, then allowing each child to define additional ones and/or modify the configuration of those plugins.

From what I can tell that's a use case I don't think would be solved the the `group` plugin?

**Comment by squidfunk** [comment]
@Blacksmoke16 Since you're mentioning [the projects plugin](https://squidfunk.github.io/mkdocs-material/plugins/projects/): you can specify a function in [`projects_config_transform`](https://squidfunk.github.io/mkdocs-material/plugins/projects/#config.projects_config_transform) to apply non-persistent transformations to projects' `mkdocs.yml`, i.e., make changes that are only necessary when you build things together. I just wanted to mention it for completeness.

And yes, [the group plugin](https://squidfunk.github.io/mkdocs-material/plugins/group/) was born out of many requests on our issue tracker to share configuration between Insiders and the community edition, and since almost all of my latest work centers around plugins, this plugin solved almost all problems users where having when trying to make their project build with Insiders and the community edition.

**Comment by squidfunk** [comment]
Additionally, we need a solution for Markdown extensions and more, [as was just raised on our issue tracker](https://github.com/squidfunk/mkdocs-material/issues/7040).
