### ISSUE TITLE
Syntax Highlighting Broken?

### ISSUE THREAD

**Issue by jprichardson** [mkdocs/mkdocs#322]
Hi, I upgraded to 0.11.1 but syntax highlighting appears to not work anymore. Is there something that I'm doing wrong? Repo here: https://github.com/cryptocoinjs/cryptocoinjs.com (latest version with broken highlighting not pushed)

**Comment by d0ugal** [comment]
@jprichardson It might be an issue with that theme. Can you send me a screenshot of it and/or try another one like mkdocs/readthedocs?

**Comment by jprichardson** [comment]
Ok, I just tried changing the theme from `flatly` to `readthedocs` and it worked with the new theme. Why would that matter?

**Comment by d0ugal** [comment]
The syntax highlighting is done from the theme with JavaScript. Although you can enable it as a markdown extension too if the theme doesn't support it.

I don't know why it stopped working for that theme tho' - that certainly would be a bug if it is the case.

**Comment by jimporter** [comment]
It probably stopped working because the Bootswatch themes weren't updated. I use the Yeti theme and see the same thing, although I haven't had time to make a full PR. I'll do that now.

**Comment by jimporter** [comment]
Er... maybe I won't. Since the last time I looked at it, the required change went from one line per file to way more than I have time to look into now.

Given that all the Bootswatch themes are just palette swaps of the Mkdocs theme, maybe it would make sense to have them all get built from the same code so that they stay in sync. I know there's talk about moving those themes out of the main repo, but maybe a better way would just be to allow themes to have customizable palettes.

**Comment by jodeleeuw** [comment]
+1 for having this issue after upgrading.

**Comment by royrusso** [comment]
+1

**Comment by svenhofstede** [comment]
+1

**Comment by d0ugal** [comment]
Can anyone verify this is an issue with the current git master?

**Comment by svenhofstede** [comment]
Tested using the latest git master

Code highlighting NOT working for the bootstrap theme and all the bootswatch themes
Code highlighting working for readthedocs and mkdocs (default) theme

**Comment by d0ugal** [comment]
aha, thanks - I didn't realise it was limited to those themes, that confused me. I'll investigate. Thanks for checking.

**Comment by d0ugal** [comment]
@svenhofstede Can you re-test? I believe I've fixed all the themes now.

**Comment by svenhofstede** [comment]
I copied over all the new Themes files from Master branch to my local machine. I tested markdown files that previously did not have code highlighting for the previously mentioned themes. 

**All code samples are now properly highlighted**

Tested following code syntax

* HTML 
* CSS
* JavaScript

Tested the following themes

* Bootstrap
* Yeti
* United
* Amelia

Thanks a lot @d0ugal

**Comment by d0ugal** [comment]
Awesome, thanks for the thorough test @svenhofstede
