### ISSUE TITLE
After building mkdocs, sub pages cannot access CSS

### ISSUE THREAD

**Issue by laolang2016** [mkdocs/mkdocs#3231]
environment:

- mkdocs                     1.4.3
- mkdocs-material            9.1.11
- mkdocs-material-extensions 1.1.1

`http://localhost:3000/fltk/hello-world` can not found `main.85bb2934.min.css ` , because the css url is `<link rel="stylesheet" href="assets/stylesheets/main.85bb2934.min.css">`
but url `http://localhost:3000/assets/stylesheets/main.85bb2934.min.css ` is woking

How to update sub page's stylesheet path with absolute path?

**Comment by oprypin** [comment]
This needs a full site to be able to reproduce - mkdocs.yml and the files that exist in docs dir

**Comment by laolang2016** [comment]
Thank you. Already solved. After building, you need to copy mkdocs.yal to the site directory, otherwise you can only use npm's serve in the site directory
