### ISSUE TITLE
Repo Link missing in readthedocs theme if custom repo_name used

### ISSUE THREAD

**Issue by sumebrius** [mkdocs/mkdocs#3259]
The readthedocs theme is missing a fallback option for the repo link if `repo_name` is not set to one of 3 predefined providers (GitHub, BitBucket, or GitLab).

It would make sense if the `repo_name` has been customised to display the custom name with a generic git icon (eg. [this one](https://fontawesome.com/icons/git-alt?f=brands&s=solid))

**Comment by oprypin** [comment]
Contribution welcome - the file is mkdocs/themes/readthedocs/versions.html
