### ISSUE TITLE
Error got after installation: import 'Sequence' from 'collections'

### ISSUE THREAD

**Issue by ArnaudBand** [mkdocs/mkdocs#3277]
After installing mkdocs using ``` sudo apt install mkdocs``` which shows that I've install it successfull, the problem comes when I was checking the version by ```mkdocs --version```, after it, it has display
````
mkdocs --version
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 3, in <module>
    from mkdocs.__main__ import cli
  File "/home/arnaud/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 16, in <module>
    from mkdocs import config                                 # noqa: E402
  File "/home/arnaud/.local/lib/python3.10/site-packages/mkdocs/config/__init__.py", line 2, in <module>
    from mkdocs.config.defaults import DEFAULT_SCHEMA
  File "/home/arnaud/.local/lib/python3.10/site-packages/mkdocs/config/defaults.py", line 1, in <module>
    from mkdocs.config import config_options
  File "/home/arnaud/.local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 2, in <module>
    from collections import Sequence, namedtuple
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

````

**Comment by oprypin** [comment]
https://github.com/mkdocs/mkdocs/commit/21b3d1d431f8a9bef0450c21ee5dc60c8242c8cd#diff-9b08eb7cf7e5540d5bb1fb2352bfdceacca95fd230fe41d4072fa2982adcb13c
The code snippets indicate that you're using a version of MkDocs that is *at most 1.1.2*, released on May 14, 2020.
You are using it with Python 3.10, released on October 4, 2021.
That is the problem.

**Comment by pawamoy** [comment]
If the version of MkDocs provided by your OS repositories (through apt) is too old, try to reach out to the MkDocs package maintainers for this OS (not sure how to find that information).

**Comment by oprypin** [comment]
FWIW from the fact that the paths refer to `.local`, I think what's happening is that the distro-installed package provides merely the "shim" `/usr/bin/mkdocs` but it actually imports and runs fully from the local-user-installed mkdocs library

**Comment by pawamoy** [comment]
Good point @oprypin.

@ArnaudBand try to clean up your environment. Uninstall both with apt and pip (`pip uninstall mkdocs`, or `rm -rf /home/arnaud/.local/lib/python3.10/site-packages/mkdocs` if pip cannot find it), then reinstall it with your preferred method.
