### ISSUE TITLE
Hooks scripts can't really use imports

### ISSUE THREAD

**Issue by oprypin** [mkdocs/mkdocs#3281]
It would be nice if the files that are used as hooks would have the ability to import files relative to them or maybe relative to the root. But currently the only way to achieve this is with this workaround first:

```python
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

import something_from_the_directory
```

**Comment by Andre601** [comment]
What exactly does that mean? Putting the `sys.path.insert(...)` at the top of the file above the imports or smth?

**Comment by oprypin** [comment]
Yes, if they don't work otherwise

**Comment by Andre601** [comment]
Okay. Tho this one doesn't seem right because `sys` and `os` aren't recognized and throw errors when using `mkdocs serve`, so this may not work reliably or for all python versions?

I have Python 11 on a windows 10 PC.

**Comment by oprypin** [comment]
OK I'll edit the example to be clearer

**Comment by robtaylor** [comment]
would also be nice to be able to import from the mkdocs.yml location - so that can be top level and the hooks can live in a subdir
