### ISSUE TITLE
Feature Request: Support overriding configuration with mkdocs.override.yml file

### ISSUE THREAD

**Issue by pereorga** [mkdocs/mkdocs#3299]
## Feature Description

This feature involves the introduction of a `mkdocs.override.yml` file that can be used to override the settings in the main mkdocs.yml configuration file. This override configuration file would allow developers to disable or modify certain settings, such as plugins, on their local development environment without affecting the main configuration file. For example, Docker Compose does this via `docker-compose.override.yml`.

## Use Case

This feature would be particularly useful in scenarios where developers need to disable certain plugins or settings locally for testing or development purposes. For example, a developer might want to disable a plugin that is very slow or that it doesn't work properly in his platform, or some other operation that is not necessary for local development. This is especially useful considering the fact that complex types such as lists and key/value pairs cannot be defined within a single environment variable in [pyyaml-env-tag](https://github.com/waylan/pyyaml-env-tag).

By placing the `mkdocs.override.yml` file in the `.gitignore`, developers can ensure that their local configuration changes do not impact the main project configuration and are not inadvertently committed to the repository.

## Proposed Implementation

I must admit that I'm not aware of the complexity that this feature might entail in terms of implementation. The idea is that when MkDocs loads `mkdocs.yml` file, it could look for a `mkdocs.override.yml` file in the same directory. If the override configuration file is found, MkDocs would apply the settings from the override file, overriding any conflicting settings from the main configuration file.

**Comment by oprypin** [comment]
This is pretty much all supported, just with 2 extra steps to take:

* The file needs to also contain `INHERIT: mkdocs.yml`
* You need to pass `-f mkdocs.override.yml`

https://www.mkdocs.org/user-guide/configuration/#configuration-inheritance

**Comment by pereorga** [comment]
Thanks @oprypin. I see this mostly covers this need. It's only a bit annoying to pass `-f mkdocs.override.yml` every time, considering there may be build scripts in the project calling mkdocs directly. But I understand this particular need may not be very common.
