### ISSUE TITLE
Option to prefix absolute links with sub-page or turn them relative.

### ISSUE THREAD

**Issue by Andre601** [mkdocs/mkdocs#3308]
## Problem

Using absolute URLs may not work, if the final page is on a sub-page. For example, if a page is hosted on `https://example.com/blog` will an absolute URL such as `/foo/bar` result in a link pointing to `https://example.com/foo/bar`, breaking sites.

## The idea

An option should be added which would do either one of two things:

- Prepend the sub-page to the absolute URLs, so that `/foo/bar` turns into `/blog/foo/bar`
- Turn the absolute path into a relative path, meaning that the link `/foo/bar` located in `/docs/example/index.md` becomes `../foo/bar`

## Why?

The usage of relative URLs can be tedious. While text editors such as VSCode may offer QoL stuff such as displaying folders and files when creating a relative path, is that feature not available for everyone obviously.

In addition can a relative URL also cause issues when you move pages around, as it would then require to edit any relative URL in all moved pages to match the new path (or edit relative paths pointing to the moved pages/files).

With having MkDocs deal with it, I could simply provide `/assets/img/cat.png` and no matter where I move the page, the link would properly resolve to the right relative path (or absolute path if the prepending option is used) reducing headaches when trying to resolve relative paths...

**Comment by GrammAcc** [comment]
Hi, @oprypin I would be happy to take a crack at a PR for this feature if no one is working on it yet.

I prefer to use absolute paths in my documentation to make it easier to move things around, and I think having namespaced prefixes like in a Flask Blueprint but just for internal URL resolution would be helpful for versioning docs or just organizing large sites.

I think the specifics of how to achieve this without a lot of extra config or breaking relative links as mentioned in #1592 will need to be ironed out, so I can take a look at the related source code after work and put together a quick design proposal if that would help.

Let me know if I'm good to proceed. Thanks!

**Comment by oprypin** [comment]
Hi @GrammAcc thanks for your interest.  Hmm most likely I'll prefer to write this myself, I have all the context and an idea in mind.

**Comment by GrammAcc** [comment]
> Hi @GrammAcc thanks for your interest. Hmm most likely I'll prefer to write this myself, I have all the context and an idea in mind.

No problem. Thanks for confirming!
