### ISSUE TITLE
Add Line numbers to Info text about unrecognized relative links

### ISSUE THREAD

**Issue by Andre601** [mkdocs/mkdocs#3311]
Mkdocs currently gives the following output for a not recognized relative link:
```
INFO    -  Doc file 'posts/some-doc-file.md' contains an unrecognized relative link '../some-other-doc-file', it was left as is.
```
While this already helps in finding possible broken/faulty links can it still be tedious if the file in question is large in content.

Because of this would I like to propose to add the Line number at which this link was found, if this is technically possible.
It would help speeding up the process of finding these links significantly.

**Comment by oprypin** [comment]
Sadly I think this might not be possible to achieve. Python-Markdown, especially preprocessors, make no attempt to preserve the original line number as they're rewriting to some intermediate representation.

**Comment by Andre601** [comment]
That's understandable...

I would ask in the python markdown repo if it could perhaps receive some API additions to make it possible to get the line numbers for the unparsed file, but in all honesty do I think this to be wasted time in the end.
