### ISSUE TITLE
Is there a way to see exactly which `page_markdown` event is being ran for each plugin?

### ISSUE THREAD

**Issue by flynneva** [mkdocs/mkdocs#3333]
We have this warning being printed out when debug logging is enabled, right before the build "hangs" on a specific file:

```
[ DEBUG    ][ mkdocs.plugins ][ plugins.py:517  ] Running 6 `page_markdown` events
```

But it doesn't tell me which of our plugins it is currently running / which plugin is causing the build to stall.

Could we potentially add another debug print (or alter the existing one) to show which `page_markdown` event is being ran? Or is it up to each plugin to add another debug print within their individual `page_markdown` method(s)?

**Comment by flynneva** [comment]
I think what I'm asking for is to add one more `debug` print here within the loop of [line 505 of the `mkdocs/plugins.py` file](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/plugins.py#L505) that includes the name of the plugin that is being ran

**Comment by oprypin** [comment]
There is currently no way to do it. Indeed you can just edit MkDocs like this to achieve this effect.

```patch
diff --git a/mkdocs/plugins.py b/mkdocs/plugins.py
index eeb7139e3..faef28683 100644
--- a/mkdocs/plugins.py
+++ b/mkdocs/plugins.py
@@ -503,6 +503,7 @@ class PluginCollection(dict, MutableMapping[str, BasePlugin]):
         if events:
             log.debug(f'Running {len(events)} `{name}` events')
         for method in events:
+            log.debug(f"Running `{name}` event from '{method.__module__}'")
             if pass_item:
                 result = method(item, **kwargs)
             else:
```

And I intend to add something a bit more robust for the next release
