### ISSUE TITLE
Tables not work on os X

### ISSUE THREAD

**Issue by huangyg11** [mkdocs/mkdocs#337]
I use os x lion, python 2.7.5, pip 1.5.6, mkdocs==0.11.1.

I download repo and run `mkdocs serve`. Add a test.md file under docs dir.

the tables look like this

![2015-01-29 17 33 27](https://cloud.githubusercontent.com/assets/5545682/5955419/93e93b40-a7dd-11e4-8c0e-5db9bc0751bc.png)

and I add the line `theme: readthedocs` to the mkdocs.yml. And the table become this

![2015-01-29 17 37 25](https://cloud.githubusercontent.com/assets/5545682/5955432/bb50ff74-a7dd-11e4-9ee4-427a4a0544d5.png)

At first, I even think it is not a table. But I check the html, it is really a table. 

The problem is both themes don't have the alignment and pipe line as documented in http://www.mkdocs.org/user-guide/writing-your-docs/#markdown-extensions

**Comment by dhhagan** [comment]
Just to clarify, this is not a browser-specific (OSx) bug, but one related to the theme (readthedocs), as far as I can tell.

**Comment by nprintz** [comment]
I believe dhhagan is correct. The content is correctly being put into `<table>` elements, but the readthedocs styling does not appear to be applied.  

It should look like this (example from the [sublime text readthedocs page](http://sublime-text-unofficial-documentation.readthedocs.org/en/sublime-text-3/editing/editing.html#using-the-mouse)):   

![screen shot 2015-03-05 at 17 44 12](https://cloud.githubusercontent.com/assets/7231007/6517312/50d11bbe-c35f-11e4-9990-b8e3b95b63b3.png)

**Comment by workergnome** [comment]
I was also having this problem, but using the github version rather than the released version resolved the issue for me.

**Comment by nprintz** [comment]
I just reinstalled mkdocs using the github source, and this resolved the issue for me as well.

**Comment by d0ugal** [comment]
Thanks for confirming the fix @workergnome and @nprintz
