### ISSUE TITLE
`enabled` setting for all plugins

### ISSUE THREAD

**Issue by oprypin** [mkdocs/mkdocs#3386]
It seems that so many plugins have an `enabled` setting these days that we may as well just add it in MkDocs. It will not run the plugin at all then. But if a plugin already has this setting explicitly, then MkDocs will not do anything, so the plugin can still decide what to do when it's disabled.

**Comment by pawamoy** [comment]
Yep, definitely agree. This will standardize the way to enable/disable plugins, which would be a great thing to have.

**Comment by ultrabug** [comment]
Likewise, I think that'd be useful

**Comment by squidfunk** [comment]
> But if a plugin already has this setting explicitly, then MkDocs will not do anything, so the plugin can still decide what to do when it's disabled.

Yes, yes, yes. That would be amazing. If this would mean that we can drop the boilerplate we have to write in each and every event handler of the plugin, so the event handlers are not registered in the first place, this would be absolutely amazing:

``` py
def on_files(self, files, *, config):
    if not self.config.enabled:
        return

    # Do stuff
```
