### ISSUE TITLE
No search modal/keyboard shortcut support for the readthedocs theme?

### ISSUE THREAD

**Issue by rmscode** [mkdocs/mkdocs#3397]
Followed the documentation closely. Spent a fair amount of time on Google to find no helpful info . . . shortcuts and the search popup modal only work when I have the mkdocs theme activated . . . absent when I have readthedocs active.

**Comment by pawamoy** [comment]
The original ReadTheDocs theme does not have a search modal (not sure about shortcuts), so the MkDocs theme based on it won't have one either I suppose.

**Comment by rmscode** [comment]
> The original ReadTheDocs theme does not have a search modal (not sure about shortcuts), so the MkDocs theme based on it won't have one either I suppose.

Thanks for the reply. Thats a bummer. I really like the theme.
