### ISSUE TITLE
relative links WARNINGs starting with 1.5.x

### ISSUE THREAD

**Issue by andboss** [mkdocs/mkdocs#3408]
We have new warnings that are pointing to dynamic (imported) content via [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin). The content is there and must be found.

```
WARNING -  Doc file 'README.md' contains a relative link 'applications/sdc-dca/index.md', but the target is not found among documentation files.
WARNING -  Doc file 'troubleshooting.md' contains a relative link 'applications/sdc-dca/FAQ.md', but the target is not found among documentation files.
```

This was not reported before 1.5.x 

Is there an issue with the sequence the plugin hooks were called?

Thanks!

**Comment by andboss** [comment]
another investigation, but will open new issue if wanted is: the WARNINGs reported are now not failing the build in strict mode - will check the docs again, may be a config issue at our side :)

**Comment by oprypin** [comment]
Could you please add a mkdocs site that has these warnings in mkdocs 1.5 but not 1.4 so that I could observe the issue for myself? The fact that the warnings weren't there before is surprising to me, I'd expect them to be there before as well

**Comment by andboss** [comment]
We have now investigated more deeply and see configured hook issue on our side that prevents mkdocs to report the relative link issues for some time (3 weeks) and after fixing the hook they now appeared together with parallel mkdocs 1.5 upgrade -> no issue in mkdocs!

Sorry to bother you with this!
