### ISSUE TITLE
problem with config in command line 

### ISSUE THREAD

**Issue by lifenglifeng001** [mkdocs/mkdocs#341]
If I run the follow command in current development version:

mkdocs serve --config=/home/lf/git/mywork/bb/bog/mkdocs.yml

it will raise error:

    Config file 'mkdocs.yml' does not exist.
But if I run the same command use version 0.11.1

Everything is OK

Is there any thing wrong with code below in [config](https://github.com/tomchristie/mkdocs/blob/master/mkdocs/config.py#L79)
    
    if 'config' in options:
        filename = options.pop('config')
Should it be:
    
    if 'config' in options:
        filename = options.get('config')

Because when we run `mkdocs serve` , we will execute this block of code two times,   filename  will use the default `mkdocs.yml` in the second time,  this file may not exist.

**Comment by d0ugal** [comment]
Interesting, I don't think that part of the code is an issue tho' - I'll need to take a look.

**Comment by d0ugal** [comment]
Actually, I take that back - you are completely right.
