### ISSUE TITLE
TypeError: argument of type 'ConfigDirPlaceholder' is not iterable

### ISSUE THREAD

**Issue by pawamoy** [mkdocs/mkdocs#3414]
In Griffe I use `if ":" in import_path:` to know if I should split the given path.
This path can be passed from `mkdocs.yml`.
I tried using for example `!relative $config_dir/scripts/griffe_extensions.py:DeprecatedExtension`, and I got this type error (title).

Should we add `__iter__`/`__contains__` methods to the `_DirPlaceholder` class?

To reproduce:

```python
from mkdocs.utils.yaml import ConfigDirPlaceholder
from mkdocs.config import load_config
path = ConfigDirPlaceholder(load_config())
":" in path
```

**Comment by pawamoy** [comment]
Actually it can also be fixed in Griffe.

```diff
     # If it's a dictionary, we expect the only key to be an import path
     # and the value to be a dictionary of options.
     if isinstance(extension, dict):
         import_path, options = next(iter(extension.items()))
+        import_path = str(import_path)

     # Otherwise we consider it's an import path, without options.
     else:
         import_path = str(extension)
         options = {}

     # If the import path contains a colon, we split into path and class name.
     if ":" in import_path:
         import_path, extension_name = import_path.split(":", 1)
     else:
         extension_name = None
```

But if I understand correctly, placeholders are supposed to behave like strings, and therefore be iterable?

**Comment by oprypin** [comment]
Could you specify your MkDocs config :sweat_smile:  

It seems to me like you are trying to pass a `!relative` item to a plugin, but plugins should process paths correctly as relative, without resorting to this tag; this tag is intended only for configs of `markdown_extensions` that don't have this access.

https://github.com/mkdocs/mkdocs/blob/00b648f0884244a139f034554b59a032113176f6/docs/user-guide/configuration.md?plain=1#L1010

So if you can, and if you have a plugin, please relativize all paths without expecting `!relative`

---

It has been noticed that `ConfigDirPlaceholder` can sometimes be passed into parts that expect a full range of operations as a string, but it is not intended to fully copy all operations of a string.

https://github.com/mkdocs/mkdocs/issues/2154#issuecomment-1586369216

Here's why I think it makes sense: if you are expecting any PathLike object, your code will fail both with pathlib.Path and with ConfigDirPlaceholder in the same way. So you should just call str() on it first.

**Comment by pawamoy** [comment]
I see, thanks, that makes sense.

See https://github.com/Python-Markdown/markdown/pull/1379#issuecomment-1752125287 (and the previous comments) as for why I tried using `!relative` in a plugin config.

**Comment by pawamoy** [comment]
I'll probably declare Griffe's config in Griffe, which mkdocstrings-python will import and use as subconfig in its own config, which mkdocstrings will import and use as subconfig in its own config, along with any other found handler. Fun times ahead!

**Comment by pawamoy** [comment]
> if you are expecting any PathLike object

Griffe actually expects a string, which can be a file path. So in some cases, mkdocstrings-python should relativize the path (because it's a relative path), and in other cases it shouldn't (module dotted path). That means I'd have to duplicate some logic from Griffe into mkdocstrings-python, which is really not great :thinking:

**Comment by pawamoy** [comment]
Would look like this:

```python
import os
from types import issubclass
from griffe.extensions import Extension, load_extensions, ExtensionNotLoadedError
from mkdocs.config.base import Config, ValidationError
from mkdocs.config.config_options import BaseConfigOption, ListOfItems, Optional, File


class Extension(File):
    def pre_validation(self, config: Config, key_name: str):
        super().pre_validation(config, key_name)
        self.exists = False

    def run_validation(self, value: object) -> Extension:
        value = super().run_validation(value)
        try:
            return load_extensions(value)
        except ExtensionNotLoadedError:
            if os.path.isabs(value):
                raise
            if isinstance(value, str):
                return load_extensions(os.path.join(self.config_dir, value))
            if isinstance(value, dict):
                path, options = next(value.items())
                return load_extensions({os.path.join(self.config_dir, path): options})


class GriffeConfig(Config):
    extensions = Optional(ListOfItems(Extension))
    ...
```

I can move all these comments somewhere else as they're a bit off-topic with the original issue.
