### ISSUE TITLE
Security contact for vulnerability report

### ISSUE THREAD

**Issue by jorgectf** [mkdocs/mkdocs#3418]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/code-security/repository-security-advisories/creating-a-repository-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) containing a security email address to send the details to, and/or enable [Public Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) so we can submit the details.

If you prefer to contact us by email, please reach out to [securitylab@github.com](mailto:securitylab@github.com) with reference to `GHSL-2023-208`.

Thank you,

GitHub Security Lab

**Comment by oprypin** [comment]
Thanks. "Private vulnerability reporting" enabled. Is that sufficient?

**Comment by jorgectf** [comment]
Thank you @oprypin, that is great.
