### ISSUE TITLE
Don't trigger rebuild for given files / directories that are being watched?

### ISSUE THREAD

**Issue by pmeier** [mkdocs/mkdocs#3433]
This is basically the same as #2247. However, that was closed with the argument being that `mkdocs` is not in control of the watching logic, but rather [`python-livereload`](https://github.com/mkdocs/mkdocs/issues/2247#issuecomment-740119567). This is no longer true after that dependency was removed in #2385, hence this issue.

For me this is needed to avoid infinite loops when using `mkdocs serve`. I have hooks that generate files to be rendered as part of the documentation. These files are ignored by git, but are still present inside the `docs` folder. The hooks are stored alongside them. In this setup, if something triggers a rebuild, we enter an infinite rebuild loop:

trigger rebuild -> run hook -> generated file triggers rebuild -> run hook -> ...

I've solved this for now by monkeypatching the livereload server at runtime through an `on_serve` hook:

```python
from pathlib import Path

import pathspec

HERE = Path(__file__).parent
DOCS_ROOT = HERE.parent

with open(DOCS_ROOT / ".gitignore") as file:
    GITIGNORE = pathspec.PathSpec.from_lines(
        pathspec.patterns.GitWildMatchPattern, file
    )


def on_serve(server, config, builder):
    def callback_wrapper(callback):
        def wrapper(event):
            if GITIGNORE.match_file(
                Path(event.src_path).relative_to(config.docs_dir).as_posix()
            ):
                return

            return callback(event)

        return wrapper

    handler = (
        next(
            handler
            for watch, handler in server.observer._handlers.items()
            if watch.path == config.docs_dir
        )
        .copy()
        .pop()
    )

    # The callback getting wrapped can be found at
    # https://github.com/mkdocs/mkdocs/blob/828f4685f29dd9e986f18306d58d1cb383d00222/mkdocs/livereload/__init__.py#L142-L148
    handler.on_any_event = callback_wrapper(handler.on_any_event)
```

The snippet above works by checking each path of changed files against `docs/.gitignore`. But there is nothing special about this. `callback_wrapper` can handle any kind of ignoring logic.

The only other option I see is to store my hooks outside of `docs/`. But I don't want that, because the hooks are very much part of the documentation.

**Comment by oprypin** [comment]
Please don't write files into the docs dir as part of the process that builds files based on the docs dir. It is pretty much doing the right thing: the docs *did* change, so let's rebuild. What are you trying to achieve?

**Comment by oprypin** [comment]
Same situation as this: https://github.com/mkdocs/mkdocs/discussions/2544#discussioncomment-1207512

**Comment by pmeier** [comment]
> What are you trying to achieve?

Document part of the package that have the description as part of the code, but are not covered regular Python dosctrings. For example, documenting a CLI or a REST API.

> Please don't write files into the docs dir as part of the process that builds files based on the docs dir.

That is not uncommon though. For example [`mkdocs-gallery`](https://smarie.github.io/mkdocs-gallery/) stores generated files to be rendered [by default in `docs/generated`](https://smarie.github.io/mkdocs-gallery/#a-basics). They only avoid the infinite loop because they have additional logic based on checksums to [prevent rebuilding a gallery that hasn't changed](https://smarie.github.io/mkdocs-gallery/#a-mkdocs-serve-mode).

**Comment by pmeier** [comment]
`https://github.com/oprypin/mkdocs-gen-files/` seems to be what I'm looking for.

**Comment by oprypin** [comment]
Yes, mkdocs-gallery is doing this totally wrong as well. To be fair, adding files is not easy and not documented...

**Comment by pmeier** [comment]
Closing this since `mkdocs-gen-files` works for my use case and thus circumvents the original problem all together. Thanks for the pointers @oprypin!

**Comment by oprypin** [comment]
Nice, https://github.com/Quansight/ragna/pull/93 looks great 🤩
