### ISSUE TITLE
Mkdocs plugin loggers don't use `extra` kwarg formatting messages

### ISSUE THREAD

**Issue by mondeja** [mkdocs/mkdocs#3461]
When a logging call is raised from a plugin, the `extra` argument is ignored by formatting on build output.

### Current behaviour

```
WARNING -  Delimiter {delimiter_name} '{delimiter_value}' of '{directive}' directive at {relative_path}:{line_number} not detected in
           the file{plural_suffix} {readable_files_to_include}
```

### Expected behaviour

```
WARNING -  Delimiter start '<--start-->' of 'include' directive at index.md:10 not detected in the file included.md
```

### Context

- See https://docs.python.org/3/library/logging.html#logging.debug for documentation about the `extra` kwarg.
- See https://docs.astral.sh/ruff/rules/logging-f-string/#why-is-this-bad and https://pypi.org/project/flake8-logging-format/ for rationales about why to use the `extra` kwarg instead of directly format strings.

Additionally, I would like to add that it allows for better testing of messages. For example, consider [this patch](https://github.com/mondeja/mkdocs-include-markdown-plugin/pull/178/files#diff-8ce1986ff76740128d0ebf361baa099ef5adb08036d6b163d44f282b7bff7deaR173-R188).

**Comment by oprypin** [comment]
> Expected behaviour

Expected behavior for which piece of code?

& I think you're confusing something about the `extra` parameter. Have you tried using it outside of mkdocs? I'm pretty sure it won't work like that either

**Comment by mondeja** [comment]
> & I think you're confusing something about the `extra` parameter. Have you tried using it outside of mkdocs? I'm pretty sure it won't work like that either

Oops, is tightly binded to the formatting scheme, right? Sorry for the noise, closing this...

**Comment by oprypin** [comment]
`extra` is for parameters that might be appropriate for **every** log message. The example shows `user_id` - it's a good example, because for a website a user id may indeed be present in almost every log. Then the logging configuration can choose to either print the user id somehow at the beginning in every message, or not print it.

**Comment by oprypin** [comment]
Using arguments instead of f-strings might still be valid, but last I checked it's not really viable to solve. Let me look again

**Comment by oprypin** [comment]
I think this is the relevant documentation. Looking
https://docs.python.org/3/howto/logging-cookbook.html#formatting-styles

**Comment by oprypin** [comment]
Yes so there are some super complicated solutions to make other formatting styles work, but this part is unchangeable **about the `log` methods**:

* **They accept only positional arguments**. `extra` is for something else
* **They are hardcoded to use `%s` formatting.**

So these two are pretty much the only reasonable options:

```python
log.info("see %s", stuff)
log.info(f"see {stuff}")
```

I settled on one of them. Yes it has some performance disadvantages but big advantages in development.

**Comment by mondeja** [comment]
Thanks for the detailed explanation! 👍🏼
