### ISSUE TITLE
Directories are always put last in automatic navigation

### ISSUE THREAD

**Issue by bjan-sag** [mkdocs/mkdocs#3470]
My project directory is laid out like this:

```console
$ tree
.
├── docs
│   ├── a
│   │   └── index.md
│   ├── b.md
│   └── index.md
└── mkdocs.yml

2 directories, 4 files
```

And the automatic navigation is rendered like this:
![image](https://github.com/mkdocs/mkdocs/assets/78591212/59dd5644-2e39-499d-8107-3c04a2efdf30)

**Why is "A" put last?** Is there any option to sort everything alphabetically? As I have a lot of files in the real repo, writing a `nav` manually is not feasible. 

I'm on Linux, latest MkDocs (1.5.3).

**Comment by nielsnl68** [comment]
Hugo did have an option to set the weight of a page in the metadata section that would be nice to have.

**Comment by tomchristie** [comment]
You probably need to be using the `nav` config to ensure you've got exactly the ordering you're intending.

**Comment by GeneralZero** [comment]
I wrote a hook to fix this if anyone needs it. This makes Directories before single pages. 

**mkdocs.yml:**
```yaml
...
hooks:
  - plugins/reorder_nav.py
...
```


**reorder_nav.py:**
```python
def on_nav(nav, config, files, **kwargs):
	nav.items = _process_nav_items_recursive(nav)
	return nav

def _process_nav_items_recursive(nav_items):

	nav_folders = []
	nav_files = []

	for nav_item in nav_items:
		if nav_item.children:			
			# If there is more than one child, we want to recurse over them so that
			# we can collapse folders of single pages at any depth in the tree.
			nav_item.children = ( _process_nav_items_recursive( nav_item.children ) )
			nav_folders.append(nav_item)

		else:
			# No child items, just add this directly.
			nav_files.append(nav_item)

	return nav_folders + nav_files
```
