### ISSUE TITLE
dynamic site_dir with configurable prefix

### ISSUE THREAD

**Issue by anb0s** [mkdocs/mkdocs#3473]
We are deploying the same site to different locations with different base URL `site_url`, e.g.

- for internal dev at own GitLab:
  - `https://my-product.docs.my-gitlab.io/v1.0.0/`
  - `https://start.docs.my-gitlab.io/docs/`
- for public dev:
  - `https://my-product.sub-dev.my-domain.com/v1.0.0/`
  - `https://start.sub-dev.my-domain.com/docs/`
- for public prod:
  - `https://my-product.sub.my-domain.com/v1.0.0/`
  - `https://start.sub.my-domain.com/docs/`

The build is done in a GiLab pipeline, configuring the `site_url` from repo's pages-url  `https://my-product.docs.my-gitlab.io` and appended version via mike for a release tag, e.g. `https://my-product.docs.my-gitlab.io/v1.0.0/`. The site build time is an issue (many docus and  PDF build).

The `site_url` option is configured at build time and results in static link in the HTML pages. The relative navigation etc. is working fine, but in combination of multi-repo import and macro variables that are deriving references to imported docs from `site_url` we have some issues that links are pointing to thebase  URL `https://my-product.docs.my-gitlab.io/v1.0.0/` and therefore not valid in other 5 deployments.

Is some dynamic resolution approach or changing base `site_url` during deployment possible?

P.S.: i have implemented external script changing the links before deployment, but search for better clean way...

**Comment by anb0s** [comment]
may be related to #3308

**Comment by oprypin** [comment]
you can configure like this:

```yaml
site_url: !ENV [MKDOCS_SITE_URL, https://my-product.docs.my-gitlab.io]
```

This has a default value and you can override it with an environment variable
```console
$ export MKDOCS_SITE_URL=https://my-product.sub-dev.my-domain.com/
$ mkdocs build
```

**Comment by anb0s** [comment]
yes, i know, but it not dynamic it's static defined for the build...

**Comment by anb0s** [comment]
found how it can done via hook and plugin with relative paths, still statically during build, but could be added to mkdocs:
https://foosel.net/til/how-to-make-mkdocs-support-siteurl-relative-urls/

**Comment by anb0s** [comment]
already mentioned here: https://github.com/mkdocs/mkdocs/issues/1592#issuecomment-1655757970

will try the plugin also, but still dynamic approach would be good...
