### ISSUE TITLE
Pass LAZY_OL=False to the OListProcessor  through mkdocs config in order to preserve numbering in ordered lists?

### ISSUE THREAD

**Issue by renevanderark** [mkdocs/mkdocs#3474]
Is it not possible to pass pass the following option for the OListProcessor (LAZY_OL = False) through mkdocs config somehow?

https://github.com/Python-Markdown/markdown/blob/master/markdown/blockprocessors.py#L337

Setting it to False had exactly the desired numbering effect for me. 

The example here was built with the setting set to `True` hard-hacked into the markdown pip package installed on my local machine:
https://teaching-myself-godot.github.io/rewriting-zelia-tutorial/day-5/#setting-up-the-slimegd-script

_Originally posted by @renevanderark in https://github.com/mkdocs/mkdocs/discussions/2838#discussioncomment-7611632_

**Comment by oprypin** [comment]
* Answered here https://github.com/mkdocs/mkdocs/discussions/2838#discussioncomment-7611897
