### ISSUE TITLE
Start the default browser, when starting the `mkdocs serve` command?

### ISSUE THREAD

**Issue by fralau** [mkdocs/mkdocs#3495]
See discussion in #3494 

It would be good to open the page in the default browser, when typing `mkdocs serve` (as happens when running the `jupyter notebook` command.

### Various points
1. This should be done once, not every time a change is detected.
2. Make it work by command-line option and config file : opt-in (initially) and then opt-out (if successful).
3. I have experimented with code, and one of the problems I met was with async: the time it might take for the page to load on the browser, versus the time it takes for the server to start.

**Comment by oprypin** [comment]
I'll implement this :+1:

**Comment by oprypin** [comment]
OK let's say the URL is already open in a tab, what should it do then? Just not open the browser? I think that's worse than opening the browser even if the tab will be duplicated. Unfortunately there's no implementation for "focus an existing tab if possible".

**Comment by fralau** [comment]
It makes a sense: a duplicated tab should not be a big deal.

**Comment by oprypin** [comment]
> one of the problems I met was with async: the time it might take for the page to load on the browser, versus the time it takes for the server to start.

Hmm for me it worked reliably. Could you try my pull request and see if you run into such issues with it?

**Comment by pawamoy** [comment]
> I think that's worse than opening the browser even if the tab will be duplicated.

Well if it stays opt-in, I don't mind, as I won't use the feature.

**Comment by hb20007** [comment]
This feature now exists with the `-o`/`--open` flag.
