### ISSUE TITLE
use_directory_urls

### ISSUE THREAD

**Issue by rockma** [mkdocs/mkdocs#350]
When **use_directory_urls** is set to *false* links should be in the form of "*folder/index.html*" but not all links are changed. Some links remain as just "*folder/*"

**Comment by logemann** [comment]
same here. Just changed to use_directory_urls: false but with no effect. The menu on the left still links to "whatever/" instead of "whatever/index.html"

I definitely need that to bundle my static html in my java app.

**Comment by d0ugal** [comment]
Sounds like a bug in the TOC code.

**Comment by logemann** [comment]
i would fix it but python is really not my game ;-)

**Comment by d0ugal** [comment]
Can you show me an example of this? I've tried to recreate this with the version in git master and I've not been able. I'll close this, but happy to reopen if you can provide more info.
