### ISSUE TITLE
Publish personal GitHub pages

### ISSUE THREAD

**Issue by jiahao** [mkdocs/mkdocs#354]
I've switched over to using mkdocs for [my personal page](http://jiahao.github.io) and am really liking the output.

I'd like to request that `gh-deploy` be extended to support personal GitHub pages also. Unlike project pages, personal pages must have repository names `<username>.github.io`, and the project is published to the `master` branch instead of `gh-pages`. Everything works fine if I do it manually so I presume supporting personal pages automatically should not be too difficult.

Edit: I have a hacky Makefile that emulates `gh-deploy` (assumes that the markdown source is on a branch called `mkdocs` and deploys to `master`):

```make
site:
	git checkout mkdocs
	mkdocs build
	git checkout master
	cp -R site/* .
	rm -rf site
	echo Ready to commit and push
```

**Comment by d0ugal** [comment]
Seems reasonable. Currently our deploy code is really simple. How can we detect if it is a personal repo vs a project repo? By looking at the structure of the remote? I'd be happy to do this, but I don't want it to be a config option, so how can we figure it out automatically?

**Comment by jiahao** [comment]
Thanks for looking into this request. As far as I understand, a GitHub user can only have one personal repo, and that repo must be named `<username>.github.io`. So whether a repo is personal or project should be quite straightforward to determine from the upstream GitHub URL.

**Comment by peter1000** [comment]
Publish personal GitHub pages: I would vote for such an option too.

**Comment by mickeyl** [comment]
This would also support organization pages!

**Comment by d0ugal** [comment]
Ok, by looking at my personal repo, I think this is how we need to do it.

Look at the output of `git config --get remote.origin.url` which has the format `git@github.com:d0ugal/d0ugal.github.com.git`

if it is USERNAME/USERNAME.github.com.git - then we can assume it is a personal/repo pages and push to `master`

**Comment by d0ugal** [comment]
Or, alternatively, we could just add the branch as an arguement to the gh-deploy command so you specify master. i.e. `mkdocs gh-deploy --remote-branch master`

**Comment by mickeyl** [comment]
Agreed. The latter would provide more flexibility.

**Comment by d0ugal** [comment]
I also think the latter is also safer. I'm a bit scared about wiping the master branch on a repo by incorrectly guessing the URL. So lets have the user provide it. :)
