### ISSUE TITLE
Integrate with custom GPT for "asking the docs"

### ISSUE THREAD

**Issue by otisg** [mkdocs/mkdocs#3577]
I think this would be a killer feature.
Allow one to integrate their mkdocs with e.g. OpenAI where one can build a custom GPT (e.g. from docs), so that in addition to the regular mkdocs search -- or maybe in place of is -- one can prompt/query the docs using the custom GPT behind the scenes.

**Comment by otisg** [comment]
@oprypin this already exists?

**Comment by pawamoy** [comment]
I've seen some examples, yes: https://pdm-project.org/latest/ (enable all Javascript and click on the robot head in the bottom right corner). The sources for the chat window seem to be here: https://github.com/pdm-project/pdm/blob/main/chatbot/app.py. 

Let me move this to a discussion.
