### ISSUE TITLE
False positive `relative_to_docs` absolute path validation warning

### ISSUE THREAD

**Issue by Blacksmoke16** [mkdocs/mkdocs#3589]
When running mkdocs@e755aaed7ea47348a60495ab364d5483ab90a4a6, I see the following warning in the logs:

```txt
WARNING -  Doc file 'architecture.md' contains a link '/framework/Events/Request/', but the target
           'framework/Events/Request' is not found among documentation files.
```

My validation is setup as:
```yaml
validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  not_found: warn
```

I have the link in the markdown setup like `[ATH::Events::Request](/framework/Events/Request/)`, which does work correctly. The `framework` path is setup via a https://squidfunk.github.io/mkdocs-material/plugins/projects/. I should also call out I'm using `section-index`. I'm kinda unsure if this is an `mkdocs` issue, or a `section-index` issue, or an `mkdocs-material` issue, so I'd figure I'd start here...

This can be produced by checking out the `website-integration` branch in https://github.com/athena-framework/athena, and running `SHARDS_OVERRIDE=shard.dev.yml shards update` then `make build` or `make serve`.

EDIT: I guess you need to be an `mkdocs-material` insider to actually be able to reproduce it :/
EDIT2: Also tried pointing the URL at `/framework/Events/Request/index.html` but that also produced the same warning.

**Comment by oprypin** [comment]
It is expected that a link ending with `/` or `.html` will always be wrong (unless you've actually put a .html document into docs). Links need to be always to .md files that exist in docs dir.

See previously https://github.com/mkdocs/mkdocs/releases/tag/1.5.0#expanded-validation-of-links  "Validated links in Markdown"  - and the same applies to the newly enabled absolute links

**Comment by Blacksmoke16** [comment]
Okay, but it seems no matter what I use, it produces the same warning. I can see the file in `site/Framework/Events/Request/index.html`. So that should map to `/Framework/Events/Request/index.md`; but seems only URL that actually works is `/Framework/Events/Request` with or without a trailing `/`. 

NOTE: I changed something in the sub-project to make the url have a capitalized `Framework` in the URL, but that didn't change anything.

**Comment by Blacksmoke16** [comment]
@oprypin Seems this is a https://squidfunk.github.io/mkdocs-material/plugins/projects/ specific thing. Only seems to happen when pointing to a file a part of a sub-project. Imma close and open an issue over there.

**Comment by oprypin** [comment]
Just from that plugin's concept, I guess the whole point is to split up sites into sub-sites, and validation is not really possible to implement fully correctly without running some part of the build process of MkDocs (files get added dynamically) for the other sites. So the correct mode for that plugin may be `absolute_links: ignore` 😬

**Comment by OmarTawfik** [comment]
@oprypin I'm seeing the same issue, but for a different use case (without plugins):

> Doc file 'user-guide/index.md' contains an unrecognized relative link './foo/', it was left as is. Did you mean './foo/index.md'?

We have `use_directory_urls: true`, and we want to keep using `./foo/`, instead of `./foo/index.md`. The links are actually compiled correctly, and the resulting site works! so I'm not sure if the warning is useful here.

Since `mkdocs` already works correctly with this input, I do believe it is a false positive indeed. The `not_found` validation is very useful otherwise.

**Comment by pawamoy** [comment]
I believe the rationale is that it's easier for MkDocs to detect and validate links when they use `/index.md`. That also makes validation more robust against configuration changes, like switching from directory URLs to non-directory ones.

**Comment by OmarTawfik** [comment]
> like switching from directory URLs to non-directory ones.

In that case, the warning should be conditional on that flag `use_directory_urls` IMO. This is a valid user scenario, and is already supported and working correctly in the compiled site. It is only validation that is incorrectly flagging the link as broken.
