### ISSUE TITLE
404 page has wrongly linked css

### ISSUE THREAD

**Issue by legoraft** [mkdocs/mkdocs#3593]
When you run `mkdocs build` within your directory, the `404.html` page that is generated by default doesn't link to the css correctly. It uses a `/` before the path, causing it to not find the css file. The fix would be to remove the slash in front of the path.

The css in the `index.html` file is linked as follows:

```html
<head>
    <link rel="stylesheet" href="css/theme.css" />
    <link rel="stylesheet" href="css/theme_extra.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github.min.css" />
</head>
```

In the `404.html` file it is linked differently, causing it not to work:

```html
<head>
    <link rel="stylesheet" href="/css/theme.css" />
    <link rel="stylesheet" href="/css/theme_extra.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github.min.css" />
</head>
```

I removed the extra script and meta tags for clarity.

**Comment by oprypin** [comment]
This was probably done for a good reason.

Both of these pages need to be able to refer to the root styles:

https://example.github.io/path
https://example.github.io/path/path

They are replaced with the raw contents of 404.html and if that page does not include the leading slashes, then the latter page will be broken.

Make sure that you configure `site_url` correctly though, that may fix this for you.

**Comment by tomchristie** [comment]
Thanks @oprypin, yep.
