### ISSUE TITLE
Modify theme

### ISSUE THREAD

**Issue by HelloGrayson** [mkdocs/mkdocs#36]
Wondering how to apply some additional CSS to a theme? Thanks

**Comment by Mopster** [comment]
:+1: I'm also looking to just edit the colors

**Comment by d0ugal** [comment]
This feature landed - CSS files included in your `docs_dir` will automatically be included. We use it in the MkDocs documentation for example: https://github.com/mkdocs/mkdocs/tree/master/docs/css

I don't think this was ever documented tho' and I've not actually used it myself... :)

**Comment by d0ugal** [comment]
Actually, I did add it to the docs but the MkDocs website needs to be updated - https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md#extra_css

**Comment by Mopster** [comment]
Thanks, I was mainly looking at the docs on the website (bit lazy). It works, but the headers of the 'readthedocs' theme have their colors overriden by css in the html pages unfortunately:

```
  <style>
    body {font-size: 90%;}
    pre, code {font-size: 100%;}
    h3, h4, h5, h6 {color: #2980b9; font-weight: 300}
  </style> 
```

Should I open a new issue for this ?

**Comment by d0ugal** [comment]
Yes please - a new issue would be great. I didn't know we still had CSS in the HTML - we should move that.
