### ISSUE TITLE
Search for .config/mkdocs.yml

### ISSUE THREAD

**Issue by bersace** [mkdocs/mkdocs#3601]
Hi,

Thanks for mkdocs, it's awesome.

mkdocs requires a `mkdocs.yml` file at root of project. This clutters root directory.

I suggest to search for `.config/mkdocs.yml` as described in https://github.com/pi0/config-dir .

The `.config` directory is already supported by many tools in JS world. Thanksfuly, `.config` is very universal as a name and match almost every langage ecosystem semantic.

Regards,
Étienne

**Comment by pawamoy** [comment]
You can actually pass the path to the config file with the `-f` option :slightly_smiling_face: 
While I'm whole-heartedly  for this config standard (though I'd prefer using `config` without a dot), it's not a top priority to us since you can use `-f`.

**Comment by tomchristie** [comment]
Thanks @pawamoy.

Closing since we probably don't want extra styles here. Having consistency across different projects is a good thing.

The command line flag seems sufficient here for cases where you don't want the default config file name.

**Comment by bersace** [comment]
Hi,

It's not just about `-f`. It's also a matter of setting `docs_dir`, `sites_dir` and relying on defaults. The idea of the .config movement is to unclutter projects root to focus of README and other top level files and directory while keeping tooling out of the way.

For now, it's hackish to use `.config/mkdocs.yml`.

**Comment by squidfunk** [comment]
@bersace just our of curiosity, how would you expect/imagine paths to be resolved? For instance, `mkdocs.yml` defines `docs_dir` and `site_dir`, and if those would be located outside of `.config` (which they probably will), should the author need to set `../docs` and `../site` or should MkDocs somehow infer the repository root or use the current working directory?

**Comment by bersace** [comment]
> @bersace just out of curiosity, how would you expect/imagine paths to be resolved? For instance, `mkdocs.yml` defines `docs_dir` and `site_dir`, and if those would be located outside of `.config` (which they probably will), should the author need to set `../docs` and `../site` or should MkDocs somehow infer the repository root or use the current working directory?

I'd expect mkdocs to use `.config` **parent** as reference directory. This is what I've implemented in temBoard. I don't think `.config` is a data directory like `docs_dir` and `site_dir` are.

**Comment by squidfunk** [comment]
Hmm, that might be too implicit, or is this standardized somewhere, i.e. that files are always referenced from the parent directory of the `.config` directory? Can there be subfolders in the `.config` directory? [It doesn't look that widely adopted](https://github.com/pi0/config-dir).

**Comment by bersace** [comment]
> Hmm, that might be too implicit, or is this standardized somewhere, i.e. that files are always referenced from the parent directory of the `.config` directory? Can there be subfolders in the `.config` directory? [It doesn't look that widely adopted](https://github.com/pi0/config-dir).

That's a good point. I raised the discussion at https://github.com/pi0/config-dir/discussions/17
