### ISSUE TITLE
Control the mkdocs gh-deploy command to run on "main" branch only 

### ISSUE THREAD

**Issue by duanxli** [mkdocs/mkdocs#3633]
We want to set the control of the branch where contributors can deploy the gh pages. How can we specifically limit it to `main `branch only? Right now, the `mkdocs gh-deploy `command can be run against any checked out branch. We want to set the limit that the command can only be run against `main `branch.

**Comment by pawamoy** [comment]
`mkdocs gh-deploy` uses Git under the hood. If you want to prevent pushes to other branches than main, I'm afraid that is not possible. You can play with Git and/or GitHub features regarding branch protection, or use a wrapper script/command that makes sure `mkdocs gh-deploy` is only ever run against the `main` branch.

We're internally discussing about the future of the `gh-deploy` command, and will probably not implement any new feature for it in the coming days, so I'll close this as not planned, but feel free to comment further.
