### ISSUE TITLE
Remove jQuery dependency from mkdocs theme

### ISSUE THREAD

**Issue by oprypin** [mkdocs/mkdocs#3648]
Just as a reminder.

This is now easy to do, there are just some basic usages in base.js

* Ref https://github.com/mkdocs/mkdocs/pull/3493

> as of Bootstrap version 5, jQuery was dropped as a dependency

**Comment by squidfunk** [comment]
Thanks for noting! Fixing this would close:

- #2467

**Comment by squidfunk** [comment]
I've created a PR #3649 that removes jQuery from the mkdocs theme – feedback appreciated! If the PR would considered to be merged, I believe we could close this issue, as well as #2467.

**Comment by tomchristie** [comment]
Neat. 👍🏼

Custom theme overrides might be relying on this, so any migration notes/changelog would need to call it out clearly and show users exactly how to re-include it within their theme.

**Comment by squidfunk** [comment]
Jup, good catch. Users might have relied on jQuery being available. The question is if the maintainers of MkDocs consider customizations to be part of the public API, or an implementation detail. I'm leaning toward the latter, as it's not documented that jQuery is guaranteed to be available.

**Comment by oprypin** [comment]
https://github.com/mkdocs/mkdocs/pull/3631/commits/cc81c7013680b96c834bd292419f0013b74d7b35
