### ISSUE TITLE
Not all headers are automatically linked

### ISSUE THREAD

**Issue by LPGhatguy** [mkdocs/mkdocs#367]
I have an API reference site for a project that's hosted on ReadTheDocs using mkdocs as the documentation engine. Headers that contain things like `<code>` blocks aren't linked, while all others seem to be.

I can reproduce this locally with a plain mkdocs install using the RTD theme.

Here's an example:
http://carbon.lpghatguy.com/en/latest/Classes/Collections.Tuple/

All three of the methods in that page should be automatically linked in the sidebar navigation, but only the one without any fancy decoration is. All of them have been given valid HTML ids, so they're possible to link, they just aren't.

The markdown for that page, which works around a couple RTD bugs and doesn't look that great, is here:
https://raw.githubusercontent.com/lua-carbon/carbon/master/docs/Classes/Collections.Tuple.md

**Comment by d0ugal** [comment]
I think I've seen this before and I think it happens when a page doesn't contain a top level `# title` as yours doesn't - you add it with HTML directly.

I can't explain why it chooses the titles it does, that is strange.

**Comment by d0ugal** [comment]
Just having a look at this - I think you managed to work around the problem? The current link looks great.

If this still needs looking into, can you comment with a link to a problem area or provide some markdown with the issue. Thanks.

**Comment by LPGhatguy** [comment]
I ended up just redoing the entire website using HTML links instead; this way, nothing gets linked at all, but I needed it for other requirements.

**Comment by d0ugal** [comment]
Thanks - I've got a failing test case. The problem is using regular expressions to parse HTML which is never a good idea. Working on a fix.

**Comment by d0ugal** [comment]
That was a pretty easy fix in the end :) Just waiting for CI to verify.
