### ISSUE TITLE
Works without search box and full content table

### ISSUE THREAD

**Issue by mingzhou** [mkdocs/mkdocs#370]
I followed this [guide](http://www.mkdocs.org/#getting-started). However, I cannot see neither the search box nor the full content table. Is there anything I missed? Thanks a lot!

\![qq 20150318234840](https://cloud.githubusercontent.com/assets/1262067/6712778/6cf70244-cdc9-11e4-9cee-60b1d11abe15.png)

**Comment by d0ugal** [comment]
This is an issue with the ReadTheDocs theme in the latest release, it has been fixed in git master.
