### ISSUE TITLE
AttributeError: 'EntryPoints' object has no attribute 'get' in xarray.backends

### ISSUE THREAD

**Issue by wonr469** [mkdocs/mkdocs#3707]
![屏幕截图 2024-05-20 180443](https://github.com/mkdocs/mkdocs/assets/169145025/3c766bb7-2fd6-4573-83c6-578d4b4bd6a8)

**Comment by pawamoy** [comment]
Sorry, this has nothing to do with MkDocs. Also please paste text rather than screenshots :)
