### ISSUE TITLE
Should the markdown renderer treat a single line break as <br>?

### ISSUE THREAD

**Issue by UnrealStars** [mkdocs/mkdocs#3708]
Hi, I'm using Mkdocs to write books
I converted the previous ". txt" to ". md"
Now there is a question:
There are a lot of line breaks in ". txt"
If we follow the standard Markdown syntax
I need to add two spaces at the end of each line and then press Enter

I would like to process individual line breaks as\<br>
Just like here in GitHub, it can wrap lines without adding two spaces
Alternatively, adding such an option in "mkdocs. yml" can enable

I am a beginner at Mkdocs
Did I miss anything
How to achieve such a thing

I am using the "mkdocs material" theme
I couldn't find the relevant settings

Related links:
https://github.github.com/gfm/#example-673
https://meta.stackexchange.com/questions/26011/should-the-markdown-renderer-treat-a-single-line-break-as-br
https://stackoverflow.blog/2009/10/15/markdown-one-year-later/

**Comment by pawamoy** [comment]
I invite you to look for a Python-Markdown extension that enables this behavior :) This won't be enabled or changed by MkDocs itself so I'll close this :)

**Comment by UnrealStars** [comment]
For those who are also looking for this issue
In fact, MkDocs already supports this feature
You just need to add in "mkdocs. yml":
```
Markdown_extensions:
-Markdown. extensions. nl2br
```
It works well as expected!
