### ISSUE TITLE
Cannot get mkdocs to recognize the caseinsensitive plugin

### ISSUE THREAD

**Issue by ASRFS** [mkdocs/mkdocs#3711]
I'm trying to use mkdocs to display a body of Markdown documentation that already exists. Unfortunately, some of the pages are `index.md` and others are `Index.md`, and the links to those pages likewise vary. Yes, I know this is all kinds of terrible (https://github.com/mkdocs/mkdocs/issues/1320), but it's also the situation I'm currently in, and it's not feasible to fix it for a bunch of reasons.

I tried to solve it by installing the caseinsensitive plugin (https://github.com/TheMythologist/mkdocs-caseinsensitive-plugin), but when I try `mkdocs serve` it fails with an error stating `Config value 'plugins': The "caseinsensitive" plugin is not installed`.

I've tried a fresh build, but I can't get it to work.

I've looked for other solutions, and found https://github.com/mkdocs/mkdocs/issues/212, but it's not clear from that what I should actually _do_ or whether it will solve my specific problem.

Do you have any suggestions? Thanks for any help you can give.

**Comment by pawamoy** [comment]
Hello @ASRFS, sorry for the troubles you're having. Let me move this to a Q/A discussion.
