### ISSUE TITLE
Please allow running MkDocs with Docker and strict mode

### ISSUE THREAD

**Issue by louwers** [mkdocs/mkdocs#3724]
Currently it seems impossible to run MkDocs from Docker.

We don't want to impose the burden of configuring a Python environment to contributors to our documentation (our community consists mainly of JavaScript and/or C++ developers), so we use use a Docker container that packages MkDocs (for Material).

Unfortunately, after enabling strict mode we are now greeted with this error

```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material

WARNING -  Config value 'dev_addr': The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only.
           Please use a third party production-ready server instead.

Aborted with 1 configuration warnings in 'strict' mode!
```

And the container fails to start. See also https://github.com/squidfunk/mkdocs-material/issues/7197 and https://github.com/mkdocs/mkdocs/issues/2108

When I use

```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material serve
```

The server running inside the Docker container cannot be accessed from outside Docker.

**Comment by pawamoy** [comment]
I'll paste my [comment from last year](https://github.com/mkdocs/mkdocs/issues/2108#issuecomment-1682428136) since it didn't get an answer there:

> Is it mandatory for you to serve in strict mode? Can't you check your docs without setting the IP address to 0.0.0.0 first, and if they raise no warning you know you can serve them without strict mode?

What I mean is:

- when writing docs and enabling live-reload, *serve* without strict mode
- once you're satisfied, *build* in strict mode (or commit, push, and let CI do that)

**Comment by louwers** [comment]
The result will be that people work with dev server locally, make a PR, and only find out during a CI run that their changes have problems with strict mode. It's an unnecessary inconvenience.

**Comment by pawamoy** [comment]
I see, thanks. Yes, that's what I expected. Mainly, it's convenient to serve the docs both to preview and check correctness (no warnings) at the same time. I'm personally OK with adding a way to disable this warning. I'm just not sure what's the best way to do that. Several options (that can be mixed together):

- CLI flag
- config option
- more specifically, validation option
- env var

The CLI flag seems to strike the right balance between ease of use/implementation and explicitness.

**Comment by louwers** [comment]
Any of those options would be great! Maybe `--allow-unsafe-server-bind`? That looks scary enough to make sure people don't use MkDocs as a production server.

**Comment by pawamoy** [comment]
It's a good name :+1: 

@tomchristie what's your take on this?

**Comment by squidfunk** [comment]
I'd also love to see progress on this topic. It's been reported by many users and I think we have a very low hanging fruit here to substantially improve the DX and UX of MkDocs 🤟

**Comment by tomchristie** [comment]
> what's your take on this?

I'd suggest we simply don't enforce the check against `0.0.0.0`. (https://github.com/mkdocs/mkdocs/pull/2022)
Less config is better. Less code is better.

**Comment by squidfunk** [comment]
I've sent a PR in https://github.com/mkdocs/mkdocs/pull/3784.
