### ISSUE TITLE
Default theme: N and P keys no longer work

### ISSUE THREAD

**Issue by nandoflorestan** [mkdocs/mkdocs#3728]
Using mkdocs 1.6.0, the default theme is much better than the one in 1.5.x. It has dark mode, awesome!

If you press ? it displays a few keyboard shortcuts.

But if you press the N key to go to the next page, or the P key to go to the previous page, nothing happens, and you get this error in the console:

Uncaught DOMException: Document.querySelector: '.navbar a[rel="next"]:first' is not a valid selector
    <anonymous> http://127.0.0.1:8000/js/base.js:60

**Comment by pawamoy** [comment]
Sounds like it comes from the move from JQuery to vanilla Javascript. Tagging @squidfunk.

**Comment by squidfunk** [comment]
Another problem: When you click on the "User guide" and "Developer guide" tabs, an error is triggered in the console. Sending a fix. Note that we normally would use [optional chaining](https://caniuse.com/mdn-javascript_operators_optional_chaining), but I'm not sure which browsers MkDocs wants to support, so I'm going for a good ol' conditional branch.

**Comment by nandoflorestan** [comment]
I am impressed by how quickly a solution was presented. Thank you! Hoping for a point release of mkdocs soon.

**Comment by squidfunk** [comment]
Yes, a release would be great! [Looking at the changeset](https://github.com/mkdocs/mkdocs/compare/0998fec7eb32d269f02c6d87071d6163c251db30...master), it looks like a patch release would follow semantic versioning, except maybe for [changing the output of `sitemap.xml`](https://github.com/mkdocs/mkdocs/compare/0998fec7eb32d269f02c6d87071d6163c251db30...master#diff-3075b69cf0972652f2752f4f8d3efc1fcfc2ecdbc4415af625bdfaa5fb2948dd), but `changefreq` is a no-op for search engines anyway. Thus, 1.6.1 should be good to go, even after merging #3729 and #3730, as no change adds new or breaks existing behavior ☺️

Let's hope the maintainers also see it that way ☺️

**Comment by squidfunk** [comment]
@tomchristie friendly ping ☺️ would be great to have those fixes released 🚀

**Comment by squidfunk** [comment]
Thanks! However, as I mentioned in https://github.com/mkdocs/mkdocs/issues/3728#issuecomment-2158727044, #3730 was only bycatch, so this issue, IMHO, cannot be considered resolved and should be reopened, since the corresponding fix  was not merged yet. The relevant PR is #3729.
