### ISSUE TITLE
Getting starting page asks user to download some suspicious content.

### ISSUE THREAD

**Issue by benreynwar** [mkdocs/mkdocs#3739]
https://github.com/mkdocs/mkdocs/blob/master/docs/getting-started.md?plain=1#L84
```
curl 'https://jaspervdj.be/lorem-markdownum/markdown.txt' > docs/about.md
```
The content of this file looks suspicious.  Probably best not to be grabbing something from a random website in the getting started tutorial.

**Comment by benreynwar** [comment]
The content of the file is different everytime I grab it, and seems to be a mixture of latin and c code.

**Comment by pawamoy** [comment]
This URL generates Markdown content in the "Lorem ipsum" style (nothing suspicious). Maybe we could avoid relying on a third-party website for the Getting Started guide though :+1:

**Comment by benreynwar** [comment]
Yep.  It just made me nervous initially to see c code in the file when I wasn't expecting any.

**Comment by janbrasna** [comment]
There is alternative https://brettterpstra.com/md-lipsum/ with more complex markdown syntax examples … but truth is maybe instead of generating random content from elsewhere a gist hosted by mkdocs to wget (that can be previewed etc. and is consistent) might be better.

**Comment by tomchristie** [comment]
Okay, so I don't think we'd have any objection to someone switching the docs to using a static downloadable gist here. That'd likely have longevity. Perhaps also with a nice call out to `https://brettterpstra.com/md-lipsum/` as an alternative. Pull requests accepted, otherwise let's keep this closed and tidy in the meantime.

**Comment by janbrasna** [comment]
OK actually the code fences are not that bad as that is quite a common content for mkdocs (:) but there's a bigger issue — the generator includes external links that are also random words — and such often lead to NSFW/scam/malware sites so I'm going to PR this out only to local links to be on the safe side.
