### ISSUE TITLE
Suggested description change for use_directory_urls

### ISSUE THREAD

**Issue by ronzulu** [mkdocs/mkdocs#3797]
Firstly, thanks so much for this great tool and all the effort that has gone into it.

When hosting on S3 as a static website, this needs to be set to false. I couldn't work it out until @squidfunk explained it to me https://github.com/squidfunk/mkdocs-material/discussions/7406.

Of course it's my fault for not reading this section fully, but when I saw the word `style` in `This setting controls the style used for linking to pages within the documentation.`, I just thought it related to something stylistic, and didn't read further.

Can I suggest the wording to be changed to:
This setting controls the directory structure of the generated documentation, and thereby the style used for linking to pages.

Also, regarding: "The alternate style..." changed to `use_directory_urls: false`
The alternate style can be useful if you want your documentation to remain
properly linked when opening pages directly from the file system, because it
creates links that point directly to the target *file* rather than the target
*directory*.

Suggested change:
The `use_directory_urls: false` setting is needed when the documentation is hosted on systems that can't access the file `X\index.html` when given the URL `X`. When set to `false`, no additional `X` directory is created, and the file is simply stored as `X.html`. Links are created that point directly to the target *file* rather than the target *directory*.

For example, this needs to be set to `false`when opening pages directly from the file system. It is also needed if publishing the documentation to a static S3 website.

**Comment by pawamoy** [comment]
Hi @ronzulu, thanks for the feedback. Documentation improvements are always welcome, would you like to send a pull request?

**Comment by tomchristie** [comment]
Closed via https://github.com/mkdocs/mkdocs/pull/3798
