### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by mickeyl** [mkdocs/mkdocs#380]
I'm integrating a mkdocs into a project that contains a lot of generated (API) documentation. It's quite cumbersome to list all of those files in the mkdocs.yml (yes I could generate that as well from a .in file) – I wonder whether we could perhaps have some kind of wildcard support?

**Comment by d0ugal** [comment]
I think at the moment, no - we don't want to add this. I can see it being useful, but it is an extra complexity. If anything, we should revisit this after #6 is closed. At the moment you can either define the full pages config, or none of it.

I realise generating the index is a bit of a pain, but that is probably the best option for now.

**Comment by mofosyne** [comment]
Really hoping this feature is revisited again now that #6 is closed.

It's indeed a pain for smaller adhoc projects when you can't just organize by folder and include it via wildcard.

**Comment by oprypin** [comment]
But indeed you should just use mkdocs-literate-nav or mkdocs-awesome-pages-plugin. This will be left to plugins.
