### ISSUE TITLE
Differences in localhost:8000 and "real" output

### ISSUE THREAD

**Issue by mickeyl** [mkdocs/mkdocs#381]
For some reason, there seem to be a difference between how the site looks in `mkdocs serve`mode and on the 'real' site. Here are screenshots for reference – note that the "good" one is the one without a visible scrollbar.

![bildschirmfoto 2015-03-29 um 12 51 56](https://cloud.githubusercontent.com/assets/167469/6885147/a6d13da8-d612-11e4-90d7-de0ea84e32a2.png)
![bildschirmfoto 2015-03-29 um 12 51 33](https://cloud.githubusercontent.com/assets/167469/6885148/a6f75e3e-d612-11e4-82b9-8f09884f24d0.png)

**Comment by d0ugal** [comment]
How odd. Are these both built with the same version? I see that the "Index" link is missing on the scrollbar version too.

**Comment by mickeyl** [comment]
Yes, it's the same version (the actual screenshot was done before I added the index link).

You can see it live by viewing [www.freesmartphone.org](http://www.freesmartphone.org) vs. [source code at github]https://github.com/freesmartphone/freesmartphone.github.io/tree/master). In the "local" case both mkdocs serve as well as locally opening the browser and viewing index.html are looking good.

**Comment by d0ugal** [comment]
Thanks - I'll give it a test and see if I can figure it out.

**Comment by d0ugal** [comment]
I can't reproduce this locally with the latest git master, let me know if the upcoming 0.12 doesn't fix it for you.

**Comment by mickeyl** [comment]
0.12 fixed this. Thanks a lot.

**Comment by d0ugal** [comment]
That was lucky :(
