### ISSUE TITLE
How to hide MKDocs TOC for just one page

### ISSUE THREAD

**Issue by Skrillx13** [mkdocs/mkdocs#3813]
I have this really styled front page, but theres the TOC render which is an issue cus it looks really ugly. Is there any way to get rid of the TOC for just that one page?

**Comment by pawamoy** [comment]
Given you've asked about landing pages on Material for Mkdocs (https://github.com/squidfunk/mkdocs-material/discussions/7390), I suppose you're using the `mkdocs-material` theme, and therefore that would be a question to ask on their tracker. But you want you want to do is actually documented on their site: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=hide#hiding-the-sidebars. Closing!

**Comment by Skrillx13** [comment]
No I'm asking for the MKDocs theme, my documentation does not use Material for MKDocs

**Comment by pawamoy** [comment]
In that case, you might try to hide with CSS! It looks like MkDocs itself is doing just that:

```css
body.homepage>div.container>div.row>div.col-md-3 {
    display: none;
}
```

:slightly_smiling_face:

**Comment by Skrillx13** [comment]
alright thanks. Ill try this later given i dont have time right now

**Comment by pawamoy** [comment]
I'll move this Q/A, and if CSS doesn't work for you, feel free to open a new feature request!
