### ISSUE TITLE
support to drafts

### ISSUE THREAD

**Issue by fedelibre** [mkdocs/mkdocs#385]
Would you ever consider support for drafts?

What I have in mind is actually simple (I hope): a document marked as draft should be visible when `mkdocs serve` is running, but it should not be built when running `mkdocs build`.
This would allow to work on a draft document and see the results, without affecting the built website.

A document may be marked as draft in the mkdocs.yml file.

**Comment by d0ugal** [comment]
I don't see value in this. I wouldn't commit a draft document to my master branch unless it were good enough to be displayed. So I think this process would be better handled in git or somewhere else other than MkDocs.
