### ISSUE TITLE
Getting started tutorial. Cannot download about.md in correct way

### ISSUE THREAD

**Issue by vitavin** [mkdocs/mkdocs#3862]
Hi!

Something wrong with instruction:
https://www.mkdocs.org/getting-started/#adding-pages
I've done this curl-command but got something like report in about.md-file:
`curl 'https://jaspervdj.be/lorem-markdownum/markdown.txt' > docs/about.md`

Please check!
Screenshot is attached.
![Code_0p5KtzMTlr](https://github.com/user-attachments/assets/8775adfa-9d44-4043-9b7c-d5b6ae5fb0b7)

**Comment by vitavin** [comment]
I found solution - on Windows you should use "curl.exe" instead of "curl"
May be you should be noticed in tutorual. 

Thanks.

**Comment by pawamoy** [comment]
Thanks for coming back with the solution :slightly_smiling_face: I think we'll leave the docs as they are.

**Comment by vitavin** [comment]
> Thanks for coming back with the solution 🙂 I think we'll leave the docs as they are.

anyway I've sent  Pull Requets with sollution, feel free to reject it :)
