### ISSUE TITLE
Different HTML between `mkdocs build` and `mkdocs gh-deploy`

### ISSUE THREAD

**Issue by Silvanoc** [mkdocs/mkdocs#3873]
I am having a very weird behavior with `mkdocs gh-deploy`.

I get the expected HTML if I run `mkdocs build` locally or in a GitHub workflow. `mkdocs serve` also delivers what I expect. But `mkdocs gh-deploy` is building it somehow differently and I get different HTML (I have had a look at the source in the browser) and it's broken.

**Comment by pawamoy** [comment]
Hi @Silvanoc, thanks for the report. We will only be able to help if you can provide a minimal reproducible example of the issue you are experiencing.

**Comment by Silvanoc** [comment]
> Hi @Silvanoc, thanks for the report. We will only be able to help if you can provide a minimal reproducible example of the issue you are experiencing.

I don't think I can easily provide a minimal reproducible example. I am generating one of the MarkDown documents, but not pushing it to the repository. The example that I have is not "minimal", but is [public](https://github.com/Silvanoc/margo-specification/tree/pre-draf). As source for the GH-Pages I have configured GitHub Actions and I have [one running `mkdocs gh-deploy](https://github.com/Silvanoc/margo-specification/blob/327844e525567d26ae11766bb6008cebd2484c7e/.github/workflows/pages.yml#L148).

I can also try to diagnose it myself (Python programmer) with some little help... I was expecting `mkdocs gh-deploy` to somehow run [`mkdocs build` functionality](https://github.com/mkdocs/mkdocs/blob/7e4892ab2dd4a52efd95a9de407eee63310e0780/mkdocs/commands/build.py#L249) under the hood and then provide it to GitHub. But it looks as if the HTML is being built completely differently.

**Comment by pawamoy** [comment]
Yes, `mkdocs gh-deploy` does the same thing as `mkdocs build` under the hood, it simply *also* pushes the built site to a specific Git branch.

I'm afraid you'll have to diagnose yourself, yes, or find a way to build a minimal example :sweat_smile: You could maybe start by describing *how* the HTML looks different? Is the site deployed on a public URL? Can you share it? Have you tried force-refreshing the page in your browser?

**Comment by Silvanoc** [comment]
Apparently it has been a caching problem somewhere along the chain... I think that the generated MarkDown was not in place and that lead to the broken HTML that was cached. Sorry for the disturbance!

BTW, amazing software and amazing support!! 💯 🚀

**Comment by pawamoy** [comment]
Thanks for the kind words, and for reporting back and closing :+1:!
