### ISSUE TITLE
Title is used as a section if file is in subdirectory

### ISSUE THREAD

**Issue by workergnome** [mkdocs/mkdocs#392]
Assuming I have a file at `research/stats.md` and a config line:

```
pages:
- ["research/stats.md", "Stats about Our Collection"]
```

I would assume that it would generate a top-level nav item titled  "Stats about Our Collection".

In reality, it generates a section **Stats about Our Collection** with a sub-item titled **stats**.

I'm 90% sure this has to do with the logic in [nav.py](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/nav.py#L212-L218) around `child_titles`.

**Comment by d0ugal** [comment]
Hmm, this is an interesting one :) I've got a failing test case, but not quite figured out a fix yet. It seems that the current logic assumes that if the path contains a `/` that you want it to be nested, which I agree, doesn't seem correct.
