### ISSUE TITLE
Inline CSS for headers in 'readthedocs' template

### ISSUE THREAD

**Issue by Mopster** [mkdocs/mkdocs#393]
The headers of the 'readthedocs' theme have their colors overriden by css inside in the html pages making it unable to override the default css using a custom CSS file.

```
  <style>
    body {font-size: 90%;}
    pre, code {font-size: 100%;}
    h3, h4, h5, h6 {color: #2980b9; font-weight: 300}
  </style> 
```

**Comment by d0ugal** [comment]
Thanks!
