### ISSUE TITLE
mkdocs.org isn't updating

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#405]
I guess this is due to the transition from @tomchristie's account to the MkDocs org. The changes are available at http://mkdocs.github.io/mkdocs/

@tomchristie Can you update DNS settings? I guess that is what we need.

**Comment by tomchristie** [comment]
I'll try to do this later today. Welcome to ping me repeatedly until complete.

**Comment by d0ugal** [comment]
@tomchristie thanks!

**Comment by d0ugal** [comment]
@tomchristie ping :)

**Comment by d0ugal** [comment]
@tomchristie Sorry :) I want to get this updated so the release notes for an incoming 0.12 release will be up.

**Comment by d0ugal** [comment]
This is now done.
