### ISSUE TITLE
Question: Reference headers / markdown anchor

### ISSUE THREAD

**Issue by peter1000** [mkdocs/mkdocs#421]
hi @d0ugal 

I thought you might be more knowledge able and maybe could help me to solve this.

Is there a way to reference Headers like alos headers `h4, h5, h6`.

Something similar to pythons documentation: ¶ Permanent link to this definition:
e.g. https://docs.python.org/3/library/gzip.html#gzip.GzipFile.peek

Do you know if I can write such in markdown that it works with all the different MkDocs themes?

If you look at: http://docilejl.readthedocs.org/en/latest/api/Docile/  I would like to add a **¶** Permanent link to this definition after: `meta()`.

This should work across all the MkDocs themes.

Any idea would be much appriciated.   https://github.com/MichaelHatherly/Lexicon.jl/issues/43

**Comment by d0ugal** [comment]
You can add this to your mkdocs.yml

    markdown_extensions: ['toc(permalink=true)', ]

Note this method will be deprecated in the future when #351 is done but realistically that will be a while away.

Does that do what you need?

**Comment by peter1000** [comment]
I will have to check this out - Thanks for your help

**Comment by MichaelHatherly** [comment]
@d0ugal, thanks for the pointer. Much appreciated.

**Comment by d0ugal** [comment]
No problem. For future reference we have a new mailing list which is good for this stuff. https://groups.google.com/forum/#!forum/mkdocs
