### ISSUE TITLE
Document which Markdown extensions custom themes should support.

### ISSUE THREAD

**Issue by waylan** [mkdocs/mkdocs#426]
The [Roadmap](https://github.com/mkdocs/mkdocs/wiki) states in part:

> - Markdown files will support admonition, fenced code blocks, and tables.

Fenced code blocks and table are already among the built-in extensions which everyone gets by default (and cannot even turn off). However, the [Admonition](https://pythonhosted.org/Markdown/extensions/admonition.html) extension is not currently on that list. That extension generates the same HTML as rST admonitions and the CSS to style them can be copied over easily.

While it is true that any user can add the `"admonition"` extension to their config, because it is not included by default, none of the existing themes include support for admonitions. If this was included by default, then the themes would more likely include support.

Or, perhaps as an alternative, the docs on themes should specify that support should be included in themes and said support be added to all built-in themes but the actual use of the extension could be left as a config option (as it is now). I would be completely okay with that. What I really want it for the themes to include support out-of-the-box.

**Comment by d0ugal** [comment]
I'd be happy for it to be added to the default extensions. I would mostly be concerned about support in the MkDocs and ReadTheDocs themes initially.

**Comment by d0ugal** [comment]
Incidentally, we need to do something about the Roadmap. It hasn't been updated for a long time.

**Comment by facelessuser** [comment]
> none of the existing themes include support for admonitions

FYI, Readthedocs theme actually does support admonitions already (which I use) as it is usually used with Sphinx.  So admonitions using the Sphinx class names work just fine.

Try something like:

```
!!! tip "Tip"
    This is a tip
```

or

```
!!! danger "Danger"
    This is a note
```

**Comment by d0ugal** [comment]
This is essentially done now that our only two builtin themes are MkDocs and ReadTheDocs. See an example [on mkdocs.org](http://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages) and [on readthedocs](http://mkdocs.readthedocs.org/en/latest/user-guide/deploying-your-docs/#github-pages).

That means the only outstanding possible item is this:

> perhaps as an alternative, the docs on themes should specify that support should be included in themes

Which I would be happy to see included. We should state the included extensions and then list a few others that are commonly added and describe what is required.

**Comment by xguse** [comment]
@facelessuser's solution is NOT working for me with 

```
    mkdocs (0.15.3)                - Project documentation with Markdown.
      INSTALLED: 0.15.3 (latest)
    mkdocs-material (0.2.4)        - A material design theme for MkDocs
      INSTALLED: 0.2.4 (latest)
    mkdocs-bootstrap (0.1.1)       - Bootstrap theme for MkDocs
      INSTALLED: 0.1.1 (latest)
    mkdocs-bootswatch (0.4.0)      - Bootswatch themes for MkDocs
      INSTALLED: 0.4.0 (latest)
```

I provide the following code:

```
# Documentation for [gmm-to-gff-transcripts-vs-snps-data](https://github.com/CacconeLabYale/gmm-to-gff-transcripts-vs-snps-data)

This is the documentation of the raw data input needed to replicate the analysis depected in the [gmm-to-gff-transcripts-vs-snps](https://github.com/CacconeLabYale/gmm-to-gff-transcripts-vs-snps) repository.
Here, we explain where each source data file came from as best we can.

Each data file will have its own section.

!!! note "Note"
    This __only__ the docs for the DATA. The Docs for the analysis should be located in the [gmm-to-gff-transcripts-vs-snps](https://github.com/CacconeLabYale/gmm-to-gff-transcripts-vs-snps) repo.



!!! note "Note"
    Any extra CSS or JavaScript files will be added to the generated HTML
    document after the page content. If you desire to include a JavaScript
    library, you may have better success including the library by using the.
```

And it results in the following rendering:
![](http://imgur.com/a/NEa1N)

**Comment by facelessuser** [comment]
@xguse, Admonitions, what you are trying to use, are not specific to MkDocs, but are an extension that is built into Python Markdown, which MkDocs uses.  I don't know how your mkdocs.yml file is configured, or how MkDocs is out of the box (because I always configure my extensions how I like them).

With that said, If you add this to your mkdocs.yml file, does it work?

```yml
markdown_extensions:
  - markdown.extensions.admonition
```

I use mkdocs on all of my github projects, and I assure you, admonitions DO work.

**Comment by xguse** [comment]
I will try that. Thank you.

Do you know if the configuration you mention is in the documentation? I searched but may have done so poorly. If not,  once I get it to work, I will submit a PR for the docs with it described as I found it to work.

Thanks again.

**Comment by facelessuser** [comment]
Extensions are documented here in the Mkdocs docs: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions

I believe they list these links as well, but I will post them here:

- Here are all the standard Python Markdown extensions: http://pythonhosted.org/Markdown/extensions/index.html

- Here all all the listed 3rd party extensions (but I am sure there are others not listed here): https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions

- Also, if you want something not currently available, you can also write your own; I've done that myself as well.

**Comment by Diamondketo** [comment]
Sorry to revive old issue. I had this issue but realize `markdown_extensions` was tabbed and was under the `extra`

`markdown_extensions:
  - markdown.extensions.admonition`

**Comment by waylan** [comment]
As MkDocs' Markdown behavior is now [documented][1], there isn't really a need for anything else.

[1]: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/writing-your-docs.md#writing-with-markdown
