### ISSUE TITLE
Lua Syntax Highlighting

### ISSUE THREAD

**Issue by LPGhatguy** [mkdocs/mkdocs#427]
Using GitHub-style labeled fenced code blocks, mkdocs doesn't seem to like Lua very much.

I use the following markdown:

	```lua
	print("Hello, world!")
	```

And get HTML that looks like

```html
<code class="lua hljs vbnet">
<span class="hljs-keyword">print</span>
(<span class="hljs-string">"Hello, world!"</span>)
</code>
```

The language aside from Lua that highlight.js picks up seems to be random, and I've observed `perl` and `vbnet` so far. The highlighting does not seem to ever be Lua. Highlight.js supports Lua according to [their website](http://highlightjs.org), and their examples seem to work just fine, but mkdocs (with fenced code blocks) does not work.

I initially reported this bug with readthedocs over at [their issue tracker](https://github.com/rtfd/readthedocs.org/issues/1193) and they referred me here.

**Comment by waylan** [comment]
@LPGhatguy what is the HTML generated by mkdocs before any manipulation by JavaScript?

**Comment by LPGhatguy** [comment]
Before JS manipulation, it looks like

```html
<pre><code class="lua">
print("Hello, world!")
</code></pre>
```

**Comment by d0ugal** [comment]
Hmm, interesting. So it looks like highlight.js is overwriting the one you provide. I'll take a look.

**Comment by d0ugal** [comment]
I've asked about this upstream at highlight.js - https://github.com/isagalaev/highlight.js/issues/816

**Comment by d0ugal** [comment]
This was fixed by https://github.com/mkdocs/mkdocs/commit/9302e1351f75c78e2d3dc56ab0987971cd9082c5

**Comment by LPGhatguy** [comment]
Awesome! Thanks for fixing my edge case issues so quickly.

**Comment by d0ugal** [comment]
No problem, I've been doing lots with MkDocs lately, so you got luck there ;)
