### ISSUE TITLE
Distribute as NuGet package to cater for the Visual Studio crowd

### ISSUE THREAD

**Issue by dazinator** [mkdocs/mkdocs#429]
Many visual studio developers won't touch any third party tool or library unless its distributed on https://www.nuget.org as a NuGet package.

I'm not too familiar with python dev, but as long as you can call the NuGet commandline exe during your builds then it should be relatively easy to produce a NuGet package containing mkdocs, and publish it to NuGet.org.

If its something you are interested in, I'd be willing to have a go at a PR if you could point me to the appropriate file that is run during builds from which I'd need to add these exe calls..

**Comment by d0ugal** [comment]
I don't know enough about the Windows world, but I hear people are having success installing and using MkDocs with chocolatey by doing something like:

    choco install python pip
    pip install mkdocs

I do not have the capacity to package the project in another way at the moment, I don't really have capacity to support windows, but I try despite not being a windows users. Realistically we need somebody that is able to help with general Windows support and Windows specific packaging too.
