### ISSUE TITLE
TOC generated from directories broken on Windows

### ISSUE THREAD

**Issue by prantlf** [mkdocs/mkdocs#434]
I am happy that mkdocs can build a nested TOC structure automatically.  I maintain the right directory structure and do not use the `pages` property in ``mkdocs.yml`.  It works well, when I build the project on Linux:

![image](https://cloud.githubusercontent.com/assets/733193/7047344/45f18036-de0c-11e4-9146-287b9524315f.png)

Building on Windows apparently does not recognize backslashes as directory separators:

![image](https://cloud.githubusercontent.com/assets/733193/7047378/7b4b9b68-de0c-11e4-9947-42b6b79dd160.png)

I use mkdocs 0.11.1.

**Comment by prantlf** [comment]
More thorough searching among the issues and pull requests revealed others, which may suffer from the path parsing/computing problems: #306 and #396.

**Comment by prantlf** [comment]
I cloned this repository and tested with the current master by:

    pip install -e ...\mkdocs

and the problem is gone.  Great!

Are you planning to relase 0.11.2 soon?  Thanks!.

**Comment by d0ugal** [comment]
We are planning a 0.12 release soon. Just a few things to work out. https://github.com/mkdocs/mkdocs/milestones/0.12.0
