### ISSUE TITLE
theme_extra.css: bootstrap themes

### ISSUE THREAD

**Issue by peter1000** [mkdocs/mkdocs#438]
customary theme *mkdocshelptheme* contains only a `theme_extra.css` file.

1.
This works but the `theme_extra.css` is copied to: **site** plus the `mkdocshelptheme` folder is also  copied to **site**

`mkdocs.yml` 
```
theme:               bootstrap
theme_dir:         docs/mkdocshelptheme
```

the `index.html` as an entry to: 
```
<link href="./mkdocshelptheme/theme_extra.css" rel="stylesheet">
```
so why is the `theme_extra.css` also copied to the root of **site** ?

2.
This does **not** work. The `theme_extra.css` is copied to: **site**.

`mkdocs.yml` 
```
theme:               bootstrap
theme_dir:         mkdocshelptheme
```

the `index.html` as  **no** entry with any reference to `theme_extra.css`

**Comment by d0ugal** [comment]
You shouldn't put your theme in the docs folder. See for example in this project, there is a docs directory and a docs_theme.

https://github.com/tomchristie/django-rest-framework

If you *really* want to do this, you could call it "docs/.theme" and as it starts with a '.' it wont be copied. However, this is only true of the latest git master.

**Comment by d0ugal** [comment]
See also #440

**Comment by peter1000** [comment]
Sorry I might have not be clear in my first comment:

Basically I do not want to create a complete new theme: but only add a simple extra css.

content of `theme_extra.css`
```
.lexiconanchor:before {
    content: "";
    display: block;
    margin-top: -75px;
    height: 75px;
}
```

Maybe I'm wrong but I understood that one has to define a `theme` togehter with an additional `theme_dir` to do this.

There is a problem if I have a file structure like you suggested:

```
├── docs
│   ├── api
│   │   └── Lexicon.md
│   ├── index.md
│   └── manual.md
├── mkdocshelptheme
│   └── theme_extra.css
└── mkdocs.yml
```

The `theme_extra.css` is copied to: site which seems to be correct.
But the problem is that the `theme_extra.css` is nowhere referenced in the `index.htnl` or anywhere else and is not applied.

**Comment by d0ugal** [comment]
Which theme are you modifying?

**Comment by d0ugal** [comment]
If you only want to add some CSS, you can place the CSS file in your docs file and it will be automatically copied over and included. Doing it with a custom theme requires a slight extra step.

**Comment by peter1000** [comment]
thanks - I will have to test this - would be great if that works.

**Comment by d0ugal** [comment]
We use it here for example: 
https://github.com/mkdocs/mkdocs/tree/master/docs/css 

Which is automatically added here: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/base.html#L19-L21

**Comment by peter1000** [comment]
Thanks like this using the extra css is much better adding an theme_dir.
