### ISSUE TITLE
`mkdocs new` broken under python2

### ISSUE THREAD

**Issue by hakase** [mkdocs/mkdocs#441]
current master, python 2.7.9 virtualenv
only top directory and mkdocs.yml created, no docs dir or index.md

```
(karasu)[lashni@orphan src]$ mkdocs new karasu
Creating project directory: karasu
Writing config file: karasu/mkdocs.yml
Traceback (most recent call last):
  File "/home/lashni/dev/karasu/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.11.1', 'console_scripts', 'mkdocs')()
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/main.py", line 74, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/main.py", line 58, in main
    new(args, options)
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/new.py", line 47, in new
    open(config_path, 'w', encoding='utf-8').write(config_text)
TypeError: must be unicode, not str
```

current master, python 3.4.3 virtualenv, files/dirs created successfully
```
(test)[lashni@orphan src]$ mkdocs new karasu
Creating project directory: karasu
Writing config file: karasu/mkdocs.yml
Writing initial docs: karasu/docs/index.md
```

**Comment by hakase** [comment]
mkdocs.yml in python2 virtualenv is also blank, no "site_name: My Docs"

**Comment by d0ugal** [comment]
hmm, good catch. Thanks.

**Comment by waylan** [comment]
Sorry about that. I've been working in an all-Unicode-all-the-time environment for so many years that I forgot to check whether you actually had all Unicode when I was working on #428. @d0ugal I see you worked out a fix for this. Although, I'm curious why you are explicitly passing each literal string through `compat.unicode`. Why not just do `from future import unicode_literals` and then all literal strings would be Unicode all the time. I have found that when working in code that runs on both PY2 and PY3, that makes life significantly easier.

**Comment by d0ugal** [comment]
@waylan good point, that would be a better fix. I was moving a bit too quick. I'll look into improving it, thanks.
