### ISSUE TITLE
generate redirect map to simplify moving documents around

### ISSUE THREAD

**Issue by SvenDowideit** [mkdocs/mkdocs#45]
this has always been a pain

**Comment by ergonlogic** [comment]
Redirects are pretty easily achievable with inline HTML.

Say you have a page at `old.md`, and you've moved the contents to `new.md`. Just keep the `old.md` file with the following content:

    <meta http-equiv="refresh" content="0; url=new" />

**Comment by mstenta** [comment]
I would vote to re-open this. I'm considering converting a website to Mkdocs, but there are a lot of old URLs that need to be redirected. I'm not sure I can justify making the switch unless redirects are made possible.

@ergonlogic's suggestion works for the occasional path change, but isn't scalable if you're trying to maintain links from an old site.

**Comment by waylan** [comment]
> @ergonlogic's suggestion works for the occasional path change, but isn't scalable if you're trying to maintain lots of links from an old site.

How would you address this then? Seems to me the best way would be via server configuration, but that is different for different servers. If your server allows it, you could just drop a config file right in your `docs_dir` which would get uploaded with your site to the server. MkDocs doesn't need to do anything.

And if such a feature were to be addressed by MkDocs, it seems to me that this would be a good candidate for a Plugin (see #206).

**Comment by mstenta** [comment]
I agree that the *best* way is via server configuration. However, one of the strengths of Mkdocs is the fact that it can be used with Github Pages - which does not allow access to any server configuration. So it would be nice if Mkdocs had a way to handle redirects itself. Jekyll provides a plugin that does this in essentially the same way that @ergonlogic described, but it builds the files automatically from a list you provide: https://github.com/jekyll/jekyll-redirect-from

It sounds like this would be a great candidate for a Mkdocs plugin.
