### ISSUE TITLE
Add Bootswatch Paper theme to mkdocs

### ISSUE THREAD

**Issue by KamranMackey** [mkdocs/mkdocs#453]
I really love that Bootswatch theme, and would like it a lot if it was added to mkdocs' list of themes.

**Comment by d0ugal** [comment]
We don't want to add any more themes to MkDocs. We are working on a way to make it easier for people to use themes that are [not included with MkDocs](https://github.com/mkdocs/mkdocs/pull/424). After this happens, we will actually [move most of the themes outside of MkDocs](https://github.com/mkdocs/mkdocs/issues/201). When this happens, we should refresh all the themes to recent versions of bootswatch and add the new themes that we don't currently support.
