### ISSUE TITLE
mkdocs build exits with 0 even if error occurs

### ISSUE THREAD

**Issue by jtauber** [mkdocs/mkdocs#456]
I just tried hooking up the Pinax docs to Travis to catch any PRs that fail to build but when testing it found that even though `mkdocs build` will report an error, it exits with code 0 so Travis still thinks it passed.

Is there any way to get `mkdocs build` to exit with non-zero on error (or even warning, optionally)?

**Comment by d0ugal** [comment]
Unfortunately, no, there isn't a good way to do this at the moment. This is a result of us doing out own simple CLI argument parsing. It will most likely be something we can fix with #450 which I hope to land soon.

I'd be happy to take any suggestions for a quick fix until that lands as I can see this would be frustrating.

**Comment by d0ugal** [comment]
This should be resolved by f496c4524f1d76aee5cb22c1d7a919a41d2120c7
