### ISSUE TITLE
Put list of pages

### ISSUE THREAD

**Issue by somenxavier** [mkdocs/mkdocs#460]
Hi,

Is it possible to generate a list of pages of all the site? Is it possible to generate a list of tags and when you press you could get all the pages (paginated) which contain this tag?

**Comment by d0ugal** [comment]
No, not at the moment. This starts to sound like a feature from a generic blogging engine which is something we are not trying to be.

**Comment by ci5er** [comment]
@somenxavier 

If this is the kind of thing you need, you might look into Pelican:
  - http://docs.getpelican.com/en/latest/content.html

**Comment by d0ugal** [comment]
+1 for Pelican, it is great.

**Comment by somenxavier** [comment]
@d0ugal : not, I don't want a blog engine. I just want a way to classify my documents. I plan to have a lot of documents and I want to put metadata in them. I plan to use it for storing mathematical documents. So I need something like `tags: cone, volume, equations`, `author:Dan Meyer`, `date: 2015-04-17`, `level: grade 6h`. And I want to classify the documents according to these fields.

So I need to obtain a lists of used fields and list pages according to them. At least, I need to obtain the list of the pages for using in templates.

Do you understand?

**Comment by d0ugal** [comment]
Yup, that makes sense and I can see that it is a bit more relevant. However, it is still a feature more common with CMS systems. We don't currently have anything like this or plans for it yet.

I guess something like this is most likely to work via search eventually.

**Comment by somenxavier** [comment]
A pitty to hear this
