### ISSUE TITLE
Help!!! Adding table of content to index.md

### ISSUE THREAD

**Issue by Collizo4sky** [mkdocs/mkdocs#466]
Hi, am new to mkdoc. How do i automatically add table of content to the index.md file? i.e i want it the TOC to be on the doc index page just like at http://phpmyadmin.readthedocs.org/en/latest/

Please help.

**Comment by Collizo4sky** [comment]
I tried [TOC] an it worked.

**Comment by d0ugal** [comment]
Great, that was fixed by 0.12 I think.

**Comment by d0ugal** [comment]
FWIW, phpmyadmin don't use MkDocs so you won't be able to replicate it exatly unless you use Sphinx.

**Comment by Collizo4sky** [comment]
@d0ugal how do i know the version of Mkdoc am running? FYI i installed it via Pip. No luck searching for it.

**Comment by d0ugal** [comment]
See http://www.mkdocs.org/about/release-notes/#upgrading

**Comment by Collizo4sky** [comment]
One last question @d0ugal is there a mkdoc config for adding disqus to all pages? 

Is adding the disqus code to all build site pages the only way?

**Comment by d0ugal** [comment]
I'm not aware of any way to add Disqus without a custom theme.

**Comment by ci5er** [comment]
You would need to register w/ Disqus. They have various plugins for tools in PHP land.

Here, you would need to add a script in a div to the theme you use. The details are found here:
  - https://help.disqus.com/customer/portal/articles/472097-universal-embed-code

**Comment by Collizo4sky** [comment]
@ci5er can you please explain in bits how i can achieve this?

**Comment by ci5er** [comment]
I don't understand the question. If this explanation below doesn't get you there, I don't know what to tell you.

You register here:
  - https://disqus.com/websites/

Then you copy this into your theme (replacing '<example>'" in the html fragment below) with your registered short-name (from above):
```
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = '<example>'; // Required - Replace '<example>' with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
```

**Comment by Collizo4sky** [comment]
I understand perfectly. i guess the problem is i don't know how mkdocs really works.

This is what i have done.


I have downloaded the readthedocs theme, added it to my folder with the following structure

|- docs
|- readthedocs
|- mkdocs.yml

I edited the base.html and added the disqus code


I added `theme_dir: 'readthedocs'` to mkdocs.yml


Each time i run `mkdocs serve` i get the following error


```
Traceback (most recent call last):
  File "c:\Python34\Scripts\mkdocs-script.py", line 9, in <module>
    load_entry_point('mkdocs==0.11.1', 'console_scripts', 'mkdocs')()
  File "c:\Python34\lib\site-packages\mkdocs\main.py", line 60, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "c:\Python34\lib\site-packages\mkdocs\main.py", line 33, in main
    serve(config, options=options)
  File "c:\Python34\lib\site-packages\mkdocs\serve.py", line 82, in serve
    build(config, live_server=True)
  File "c:\Python34\lib\site-packages\mkdocs\build.py", line 266, in build
    build_pages(config)
  File "c:\Python34\lib\site-packages\mkdocs\build.py", line 201, in build_pages

    build_404(config, env, site_navigation)
  File "c:\Python34\lib\site-packages\mkdocs\build.py", line 188, in build_404
    output_content = template.render(global_context)
  File "c:\Python34\lib\site-packages\jinja2\environment.py", line 969, in rende
r
    return self.environment.handle_exception(exc_info, True)
  File "c:\Python34\lib\site-packages\jinja2\environment.py", line 742, in handl
e_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Python34\lib\site-packages\jinja2\_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "c:\Python34\lib\site-packages\mkdocs\themes\mkdocs\404.html", line 1, in
 <module>
    {% extends "base.html" %}
  File "readthedocs\base.html", line 75, in <module>
    {% include "breadcrumbs.html" %}
  File "readthedocs\breadcrumbs.html", line 4, in <module>
    {% for doc in current_page.ancestors %}
  File "c:\Python34\lib\site-packages\jinja2\environment.py", line 397, in getat
tr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'current_page' is undefined
```

**Comment by Collizo4sky** [comment]
I have narrowed down the error to readthedocs base.html. i think there is an error with the tags.

I replaced the code with the basic 

```
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    {{ content }}
  </body>
</html>
```


And it worked fine.

**Comment by d0ugal** [comment]
I'd recommend learning about jinja2 templates if you want to work on custom themes. http://jinja.pocoo.org/docs/dev/
