### ISSUE TITLE
Install via Python Wheel

### ISSUE THREAD

**Issue by rcorzogutierrez** [mkdocs/mkdocs#468]
create a universal wheel distribution

**Comment by d0ugal** [comment]
Sure, happy to do this. Do you know what I need to do?

**Comment by d0ugal** [comment]
What is the advantage of a wheel for an all Python lib anyway?

**Comment by d0ugal** [comment]
Looks like this is a good primer for the advantages. http://pythonwheels.com

**Comment by rcorzogutierrez** [comment]
Wheels allow you to provide a binary distribution of the package with all dependencies already compiled.
Providing wheels will save a lot of installation time and will not require a working compiler.

**Comment by d0ugal** [comment]
@rcorzogutierrez Do wheels also bundle the dependancies? I didn't know that.

**Comment by d0ugal** [comment]
I just checked and it seems they don't include the dependencies - so that wont help with the few users that have issues with one of our dependencies. The main advantage from what I can tell is that the setup.py isn't executed on the machine getting the install, so there is no arbritary setup code being used by the end users. That is neat.

**Comment by rcorzogutierrez** [comment]
I really have not built one, but its documentation (https://wheel.readthedocs.org/en/latest/) describes the dependencies are included running the command
```
# Build a directory of wheels for pyramid and all its dependencies
pip wheel --wheel-dir=/tmp/wheelhouse pyramid
```

**Comment by d0ugal** [comment]
I think that creates a wheel for each dependency, rather than one wheel for all of them. Anyway, I will try it out soon and see.

**Comment by d0ugal** [comment]
See #469 wheels will be created when we next do a release.

**Comment by rcorzogutierrez** [comment]
the project readthedocs had already built a wheel to mkdocs, 6 months ago
[readthedocs](https://github.com/rtfd/readthedocs.org/tree/master/deploy/wheels).

**Comment by d0ugal** [comment]
@rcorzogutierrez Sure, I could do one now but I don't see a rush. The tangible benefit for a all Python library is really minor.

**Comment by d0ugal** [comment]
I think that is what you are suggesting anyway? I'm not really sure what to take from the last comment :)

**Comment by d0ugal** [comment]
I don't think they use those wheels, or hope they done. That version is really old.

**Comment by rcorzogutierrez** [comment]
I follow with great attention your project, I feel great. I thank you for all the answers to my questions

**Comment by d0ugal** [comment]
Thanks :)
