### ISSUE TITLE
Would it supports pdf output?

### ISSUE THREAD

**Issue by gahoo** [mkdocs/mkdocs#480]
mkdocs makes writting documents less painful. It's great.
I tried using xhtml2pdf to convert the built site/index.html. But I got the following errors which seems related to the mkdocs theme css:
```
xhtml2pdf.w3c.cssParser.CSSParseError: Selector Pseudo Function closing ')' not found:: (u':not(', u'[controls]){display:')
```
It would be great if building PDF is supported.

**Comment by d0ugal** [comment]
It sounds like they don't support some of the more advanced CSS we use. I'd suggest making a theme specific to PDF generation.

**Comment by itfanr** [comment]
Did someone success to generate a whole pdf  with many html pages ?

**Comment by waylan** [comment]
@itfanr #374 and #526 both offer more discussion about this and related issues. And both end by pointing to https://github.com/jgrassler/mkdocs-pandoc. Don't know if it will work for your needs (I haven't used it), but its the only working solution I'm seen mentioned.

**Comment by itfanr** [comment]
@waylan  Thank you.
