### ISSUE TITLE
Option to remove "Docs Build Date"

### ISSUE THREAD

**Issue by ymmt2005** [mkdocs/mkdocs#489]
Everytime `mkdocs build` runs, it updates "Docs Build Date" line in the generated HTML.
As we are pushing the site to a Git repo (for GitHub pages), this behavior produces
unnecessary diffs.

Any chance can we remove "Docs Build Date" line?

**Comment by d0ugal** [comment]
There isn't any way to remove it at the moment other that customising the theme.

It might make sense to only include this on the home page which would at least remove the duplication an make the diff much smaller.

**Comment by d0ugal** [comment]
See #490.

**Comment by ymmt2005** [comment]
@d0ugal Wow!
I'm going to try it.  Thank you!

**Comment by d0ugal** [comment]
@ymmt2005 It will still cause you to have a diff on the home page, but I think that is a reasonable compromise?

**Comment by ymmt2005** [comment]
@d0ugal 
Reasonable for us.  Confirmed that only /index.html have the version and the build date.
Thank you for your great product!
