### ISSUE TITLE
Option: parent homelink

### ISSUE THREAD

**Issue by Hernrup** [mkdocs/mkdocs#52]
In most cases you dont serve the documentation as a standalone website but it is instead linked from some other master site. 

I suggest to include a config value in mkdocs.yml that, when set, renders a return link to the parent site in a, for the theme, appropriate location.

**Comment by jniggemann** [comment]
I have the same usecase and second this idea.

**Comment by d0ugal** [comment]
How would this look in the current themes? Can anyone show a good example? If it doesn't need to be included in the current themes it could easily be acomplshed with #144

**Comment by jniggemann** [comment]
@d0ugal I hacked the theme I use to implement this, take a look at http://hz6.de/obnam/index.html
The upper left corner shows the link "back" (or "up", or whatever you may call it)...

**Comment by d0ugal** [comment]
I'd be happy to see this added by using `{{ config.extra.homepage }}` or something similar. For this to happen, we need a few things:

- Support added to the MkDocs and ReadTheDocs themes.
- Documentation added for customising the themes. The idea of config.extra is that it is an area where themes can get extra information but it isn't expected that all themes will support it. So we need to start making it clear what does and doesn't support it when we add new features based on this.

**Comment by tomchristie** [comment]
I'd suggest that we just do a much better job of documenting the themes and demonstrating how to override parts of the theme templates.

**Comment by d0ugal** [comment]
That makes sense, we should then close this in favour of https://github.com/mkdocs/mkdocs/issues/607
