### ISSUE TITLE
Download as Dash docset?

### ISSUE THREAD

**Issue by tylerFowler** [mkdocs/mkdocs#520]
It'd be really nice to be able to download a docset as a Dash (as in the Mac app) docset.

Instructions are detailed at https://kapeli.com/docsets#dashDocset

Obviously it can be done manually just fine (most likely, haven't tried yet), but it'd be a nice convenience.

**Comment by d0ugal** [comment]
Yup, this would be a nice addition. I've marked this as something for the 1.0 release, that doesn't necessarily mean it needs to wait until then if somebody else can help out with the work.

We would probably want to use [doc2dash](https://github.com/hynek/doc2dash) for this. Whatever we go for, we should make make it works with [Zeal](http://zealdocs.org/) too.

**Comment by d0ugal** [comment]
Moving this to Post 1.0 as it isn't critical for a stable MkDocs release. I think it is likely that this should be done in a MkDocs extension.

**Comment by matrixise** [comment]
not critical, but whishlist, because I am in italy for two weeks and I use internet from my phone with my laptop but the roaming is really expensive. and I use dash with the local documentation.

A script to convert mkdocs to dash will be really appreciated. Thank you.

**Comment by wbob** [comment]
for people searching: from MWers [docker-docset](https://github.com/MWers/docker-docset) that converted Dockers (former?) MkDocs Documentation to Docset, I gathered a buildscript: [mkdocs-docset](https://github.com/wbob/mkdocs-docset) - I also tried doc2dash via Sphinx' markdown support and got almost there but the table of contents. I didn't try a route via mkdocs-pandoc

**Comment by oprypin** [comment]
This seems too specific to support in MkDocs core. Maybe it can be a plugin or an external solution.
