### ISSUE TITLE
GitHub embedded gists not rendered correctly in readthedocs theme

### ISSUE THREAD

**Issue by shichao-an** [mkdocs/mkdocs#521]
It seems the embedded GitHub gists does not show correctly. I tested with "mkdocs serve" locally against the master branch. You can see the following screenshot.

![screen shot 2015-05-12 at 10 59 46 pm](https://cloud.githubusercontent.com/assets/5781687/7604690/233cce92-f8fb-11e4-8022-f41160f1b846.png)

**Comment by d0ugal** [comment]
I'm not all that familiar with using gists like this. What did you add to your markdown for this? Just so I have a way to reproduce it locally.

**Comment by shichao-an** [comment]
Sorry for me not putting code snippet. Just simply put a javascript with src to the gist js. Here is the md snippet I used for the screenshot:

```
### `stat`, `fstat`, `fstatat`, and `lstat` Functions

<script src="https://gist.github.com/shichao-an/dd0cdd90a54848ff3018.js"></script>

* `stat`: returns a structure of information about the named file
* `fstat`: returns a structure of information about the given file descriptor
* `lstat`: similar to `stat`, returns information about the symbolic link, not the file referenced by the symbolic link
* `fstatat`:  return the file statistics for a pathname relative to an open directory represented by the fd argument; the flag argument controls whether symbolic links are followed
```

**Comment by d0ugal** [comment]
Aha, thanks. So I guess our CSS is clashing with theirs somehow. I'll take a look.

**Comment by facelessuser** [comment]
Seems like some internal borders need to be removed from `td` and  `tr` tags, and `table` background and `tr` backgrounds need to be synced up with whatever syntax color scheme is being used.

**Comment by waylan** [comment]
Hmm, this is an interesting problem. As mkdocs supports the Markdown [Tables][1] Extension (it is included out-of-the-box and cannot be disabled), each of the themes include some basic table styling CSS. As there is no unique identifiers on the tables generated by Markdown (nor should there be), the CSS rules generically apply to all tables on the page (or at least all tables within the content div). Naturally, those rules are conflicting with the Gist. Personally, it would seem to me that the CSS for the Gist  should cancel out all other styling (do a reset for the specific tables it provides) to avoid this situation. Therefore, I would be inclined to consider this a bug upstream. But, then again, I haven't actually looked at the source. Maybe a reordering of the various CSS files (accounting for the "cascade" part of "Cascading Style Sheets" ) would address this issue.

[1]: https://pythonhosted.org/Markdown/extensions/tables.html

**Comment by facelessuser** [comment]
> Therefore, I would be inclined to consider this a bug upstream. 

I would be inclined to agree, but I am also not a web designer.  But for a workaround, you could use some custom CSS to adjust the borders of `tr` and `td` elements under the `.gist-file` (or whatever seems appropriate), and also tweak the `table` and `tr` backgrounds to be match.

Now should mkdocs directly address this...
There will probably always be an issue of a user embedding **something** in the these kinds of docs as you cannot account for all things that will get embedded, and not everything that gets embedded will be always be styled to work in **all** situations.  Whether a specific issue needs to be directly addressed by mkdocs vs the users vs provider of the embedded content is what I guess needs to be evaluated.  I imagine this may vary depending on the situation.

I don't really know what the way to go on this is.  I did a little research and found some posts like this from 2 years ago: http://www.dinochiesa.net/?p=984.  They had CSS interference as well.  Even if we patch this in this theme, github can turn around and tweak their style again (they seem to like doing that).  Meh, if it were me, I'd probably just custom patch  my theme if I was going to be embedding gists and move on.

**Comment by d0ugal** [comment]
Yup, we need to draw the line somewhere. Inserting JavaScript into your Markdown that pulls in HTML and CSS could do anything. We can't support that. This is when you should use [extra_css](http://www.mkdocs.org/user-guide/configuration/#extra_css) and add something like this to your docs.

    .rst-content .gist table {
        margin-bottom: 0;
    }

That at least partially fixed it for me, I didn't fully test.
