### ISSUE TITLE
Decode error when using letters like åäö (Windows)

### ISSUE THREAD

**Issue by danielrodin** [mkdocs/mkdocs#531]
When using letters like åäö in markdown the following error occurs:

    build_result = _build_page(page, config, site_navigation, env, dump_json)
    File "C:\Python34\lib\site-packages\mkdocs\build.py", line 178, in _build_page

    input_content = open(input_path, 'r', encoding='utf-8').read()
    File "C:\Python34\lib\codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 20: invalid
    continuation byte

Environment is Windows 8.1 and Python 3.4. Mkdocs version is current master branch version.

**Comment by waylan** [comment]
@danielrodin Are you sure that the file is saved as utf-8? If not, then you need to fix that. However, if that is not the problem, can you provide a simple example of a Markdown file which raises this error so that we can reproduce it?

**Comment by danielrodin** [comment]
@waylan I reproduced the error in a simple scenario as follows. I copied index.md to a subfolder called Test, then I added the char Ö to the header through Nodepad in Windows.

**Comment by d0ugal** [comment]
This works fine on Linux and OSX. it does seem that the file is not UTF-8, I don't know how you ensure that it is UTF-8 tho'

**Comment by danielrodin** [comment]
@d0ugal @waylan The file was ANSI and when I saved it as UTF-8 it worked. So as you suggested the problem was that the file was not UTF-8. Thanks.

**Comment by ci5er** [comment]
@danielrodin - Tactically, with notepad, this is what you do: Open the file in Notepad. Click 'Save As...'. In the 'Encoding:' combo box you will see the current file format (probably 'ANSI') and the options. Select the correct one ('UTF-8', probably at the bottom) and you'll be good. 

For mkdocs project knowledge-base purposes, I'll say this: Text files in Windows don't have a format. There's an unofficial convention that if the file starts with the BOM codepoint in UTF-8 format (http://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) that it's UTF-8, but that convention isn't universally supported.

To check your file out, open it in a hex editor and make sure that the first three bytes are a UTF8 BOM (`EF BB BF`)

N.B. Those same bytes are used by pretty much any extension of ASCII, e.g. Shift-JIS (Japanese), so, YMMV.

**Comment by facelessuser** [comment]
Every file has a format, even in windows, but I can't remember the name of the format off the top of my head.

UTF8 files don't have to have a bom either; they are optional.

The best advise is to use a good editor that allows you to set the encoding, and view the encoding easier.  If you are looking for something free Notepad++ is decent.

**Comment by kasperkowalski** [comment]
The problem described in #362 
Solution: https://github.com/lepture/python-livereload/issues/111

**Comment by d0ugal** [comment]
and it will be fixed when the next python-livereload release comes out which should be soon. https://github.com/lepture/python-livereload/issues/105
