### ISSUE TITLE
Examples of integrating 3rd party libraries with MkDocs.

### ISSUE THREAD

**Issue by bwmarrin** [mkdocs/mkdocs#540]
I've been toying with a handful of 3rd party javascript libraries to find some suitable for adding into my documentation.  I thought I would share the examples I've created - just in case someone else might find them useful.

http://bruce.marriner.us/MkDocsPlus/

the raw files can be found here on Github - https://github.com/bwmarrin/MkDocsPlus

I plan to add a few more examples to the site over the next few weeks or so.  I know it's nothing super special and I hope the name is okay - I could change it to someone else easily.

**Comment by d0ugal** [comment]
Very cool - good to see that they mostly work well! We should think about creating a wikipage or something to collect community resources and sites.

**Comment by d0ugal** [comment]
I started a page here: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Users

**Comment by d0ugal** [comment]
We may want to link to this from the MkDocs documentation. I'll think about this and try to add other interesting projects.

**Comment by bwmarrin** [comment]
Thanks :) I agree about linking it from the documentation.  Since some of it will probably be helpful to any new users.   If I run across anything MkDocs related I'll let you know so it can be added to the Wiki :)

**Comment by d0ugal** [comment]
I would like to allow anyone, with a GitHub account, edit the wiki. I'm not sure if I can do that or not? I see the wiki as being a place for community contributed information rather than official information which would be in the docs.

**Comment by bwmarrin** [comment]
Awesome, then I'll just edit away if I find something handy.  Thanks d0ugal.
