### ISSUE TITLE
Support a configurable maximum depth for navigation sidebar

### ISSUE THREAD

**Issue by akvadrako** [mkdocs/mkdocs#544]
It would be nice for the navigation sidebar to only show the top-level of headers when a entry is expanded.

**Comment by bwmarrin** [comment]
Having an option (or a few) to control the behavior of the automatically generated menu could be handy for sure. As a work around (or permanent solution) @akvadrako  you can use the *pages* configuration option to set the menu items manually.  With that, you could enforce that only the "top level" are listed.

**Comment by akvadrako** [comment]
@bwmarrin, I wasn't very clear. I have updated the description. I already do use the pages option, but it doesn't allow me to control the second-level headings, which are displayed when I expand a top-level TOC entry.

**Comment by bwmarrin** [comment]
Ah, I understand exactly now.  I agree, I thought it would do that myself too when using smaller sub-headings on a page.  I would think it probably should be a default to only show the top level of headings inside a document.

**Comment by d0ugal** [comment]
If I remember correctly, by default H1 and H2's are shown. This is up to the theme, and it decides how much it wants to show this.

**Comment by JeremieGuez** [comment]
If we want to display also h3 and h4, what is the best way ? I am trying to do it since 1 hour ;)

**Comment by waylan** [comment]
This behavior is completely controlled by the theme templates. Anyone should be able to use [theme customization][1] to replace the relevant parts of the template with one which provides the desired behavior.

[1]: http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

**Comment by JeremieGuez** [comment]
Thanks, but your link is not working

**Comment by waylan** [comment]
How is the link not working? I just checked and it works fine for me.

**Comment by JeremieGuez** [comment]
I delete my comment..

**Comment by waylan** [comment]
For any who are interested in the feature request to provide a config setting which controls depth, this could conceivably be accomplished with the work done in #1201 (when that is available in a release). In that refactor of theme handling, we are adding the ability for themes to have their own config settings. Therefore, if a theme included support for such a setting, it could work. However, this is completely contained within the theme. You would need to use a theme which specifically implemented the feature. Not all themes will get the feature by default and if no theme authors chose to add support, then we'll be in the same place we are now. The work in #1201 simply makes it possible for a theme to add support.
