### ISSUE TITLE
Update ReadTheDocs to use latest MkDocs

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#554]
This is really an upstream issue, but I want to track it here for downstream users.

**Comment by d0ugal** [comment]
readthedocs.org is currently running `0.11.1` this means that they are [missing all of these lovely commits](https://github.com/mkdocs/mkdocs/compare/0.11.1...master) which is roughly half of the MkDocs git history (based on number of commits).

**Comment by d0ugal** [comment]
After I roll a 0.13.0 release in the next few days I will be working on updating readthedocs to use it, currently there are problems due to the theme customisations they make.

**Comment by ericholscher** [comment]
:+1: Happy to merge & deploy the new version when it's ready.

**Comment by d0ugal** [comment]
@ericholscher Thanks! Can we define what blocks are needed from themes so they work on ReadTheDocs? See https://github.com/mkdocs/mkdocs/issues/355 and https://github.com/rtfd/readthedocs.org/issues/978#issuecomment-62574931. I want to add blocks and reduce the duplication of the theme that you guys have - this should then reduce the risk of us breaking something if you only inject into small defined areas. We can then document that and add support in other themes.

**Comment by d0ugal** [comment]
See https://github.com/rtfd/readthedocs.org/pull/1305

**Comment by d0ugal** [comment]
This just landed in ReadTheDocs! w00t!

**Comment by deejay1** [comment]
Seems like this has regressed in the latest master...

**Comment by d0ugal** [comment]
@deejay1 What has?

**Comment by deejay1** [comment]
@d0ugal mkdocs documents have problems with links not having trailing slashed and resulting in having "somedirectoryindex.html" in them

**Comment by d0ugal** [comment]
@deejay1 That sounds unrelated to this issue - can you open a new one with an example? It might be that this is a problem with RTD itself and it needs to be reported upstream (we have not changed anything lately)

**Comment by deejay1** [comment]
@d0ugal Ah sorry, got a bit confused with the links back and forth on that issue and commented on the wrong project :/
