### ISSUE TITLE
'Rollup' or 'Expand' function in multi-level ToC?

### ISSUE THREAD

**Issue by ProfYaffle** [mkdocs/mkdocs#556]
The new multi-level ToC is a great addition, so thanks for that.

However - there's always a 'but' ;-) - you now can quickly end up with a really long table of contents that disappears off the bottom of the screen. It would be useful to have a rollup function, therefore - perhaps presume the sublevels to be collapsed until \<some event\>.

I think it's limited to the readthedocs theme and not mkdocs or a theme that uses cascading menus by default (I don't think any of the others support multi-level anyway).

**Comment by d0ugal** [comment]
Yup, that's a fair point. Upsteam added this recently for the Sphinx version of the theme. See for example: http://pip.readthedocs.org/en/stable/

It may be that we can sync with upstream and get this feature, plus other fixes.

**Comment by ProfYaffle** [comment]
Yes, that's exactly what I was thinking of. Too slow, obviously...

**Comment by d0ugal** [comment]
So, this is specific to the Read The Docs theme. It should be solved with: #588
