### ISSUE TITLE
Roll 0.13.0 Release

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#559]

**Comment by d0ugal** [comment]
Trying to figure out if there is something we can do to fix #547 before releasing.

**Comment by d0ugal** [comment]
`0.13.0` has been released!

**Comment by Collizo4sky** [comment]
Great.... i will update via pip

**Comment by trel** [comment]
congrats!  thanks!

**Comment by waylan** [comment]
Awesome. Thanks for the work on this. I expect that Python-Markdown will be using this to generate our docs with the next release.

**Comment by d0ugal** [comment]
Thanks all - let me know if you run into any issues!
