### ISSUE TITLE
in minimal mkdocs.yml file... "ERROR   -  Config value: pages"

### ISSUE THREAD

**Issue by trel** [mkdocs/mkdocs#562]
Congrats on 0.13 today!

Am playing with the site navigation and have run directly into a wall.

I was using the automatically generated navigation, which is working fine, but I want to reorder some of the automatic listing and then realized the only way to do this for real was to define the entire navigation.

I then hit the ```ERROR   -  Config value: pages``` error below and began to narrow the focus... until I have a single `site_name` and `pages` entry, and mkdocs fails.

I'm running 0.13 in a virtualenv - any ideas?  The error message says I have an error, but the output it gives hasn't clued me into what I've done wrong.

It smells like a python/virtualenv/version thing...

```
(venv) $ pip install --upgrade mkdocs
Requirement already up-to-date: mkdocs in ./venv/lib/python2.7/site-packages
Requirement already up-to-date: click>=4.0 in ./venv/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: ghp-import>=0.4.1 in ./venv/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: Jinja2>=2.7.1 in ./venv/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: livereload>=2.3.2 in ./venv/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: Markdown>=2.3.1 in ./venv/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: PyYAML>=3.10 in ./venv/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: six>=1.9.0 in ./venv/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: tornado>=4.1 in ./venv/lib/python2.7/site-packages (from mkdocs)
Requirement already up-to-date: markupsafe in ./venv/lib/python2.7/site-packages (from Jinja2>=2.7.1->mkdocs)
Requirement already up-to-date: backports.ssl-match-hostname in ./venv/lib/python2.7/site-packages (from tornado>=4.1->mkdocs)
Requirement already up-to-date: certifi in ./venv/lib/python2.7/site-packages (from tornado>=4.1->mkdocs)
Cleaning up...
```

```
(venv) $ cat mkdocs.yml 
site_name: MyTest

pages:
- 'testing.md'
```

```
(venv) $ mkdocs build
ERROR   -  Config value: pages. Error: Invalid pages config. set([<type 'str'>]) set([<type 'unicode'>, <type 'dict'>]) 
Error: Errors found in the config file.
```

**Comment by d0ugal** [comment]
Ah, sorry. This is a silly mistake on my end. I'm rolling out a bug fix release just for this. Expect a 0.13.1 to arrive within the next hour.

**Comment by d0ugal** [comment]
I am just waiting for CI to confirm my fix on Windows. Once it passes on #565 I'll push the release

**Comment by d0ugal** [comment]
MkDocs 0.13.1 is now available on PyPI. Please upgrade and let me know if you run into any other issues.

**Comment by trel** [comment]
confirmed - works as expected.
