### ISSUE TITLE
http and https links displayed as raw text instead of link

### ISSUE THREAD

**Issue by femtotrader** [mkdocs/mkdocs#563]
Hello,

http:// and https:// links in Markdown file are considered as raw text on ReadTheDocs but as link on GitHub.

see
http://pandas-datareaders-unofficial.readthedocs.org/en/latest/todo/
and compare to:
https://github.com/femtotrader/pandas_datareaders_unofficial/blob/master/docs/todo.md

It seems to be a mkdocs issue according https://github.com/rtfd/readthedocs.org/issues/1091#issuecomment-67693833

Kind regards

**Comment by d0ugal** [comment]
I can't confirm for sure, but I'm not aware of anything in standard Markdown which means all URLs should be converted into links. @waylan Do you happen to know?

**Comment by ProfYaffle** [comment]
Dunno if it's documented or if it's meant to, but simply putting the link in angled brackets will work in standard markdown. Try it on <https://daringfireball.net/projects/markdown/dingus>.

**Comment by d0ugal** [comment]
Yup, we are consistent with that. This shouldn't create a link and doesn't.

    http://mkdocs.org

This should and does.

    <http://mkdocs.org>

Thanks @ProfYaffle - that is a handy site to test with!

**Comment by femtotrader** [comment]
Thanks. It solved my problem.

**Comment by waylan** [comment]
Glad everyone figured this out, but yes, this is another example of GitHub not following the [rules][1].

[1]: http://daringfireball.net/projects/markdown/syntax
