### ISSUE TITLE
unordered list depth problem

### ISSUE THREAD

**Issue by femtotrader** [mkdocs/mkdocs#564]
Hello,

it seems that there is a problem with unordered list depth.

compare
http://pandas-datareaders-unofficial.readthedocs.org/en/latest/todo/
with
https://github.com/femtotrader/pandas_datareaders_unofficial/blob/master/docs/todo.md

I was expecting same results.

It seems to be a mkdocs issue according https://github.com/rtfd/readthedocs.org/issues/1093#issuecomment-105707665

Any idea ?

**Comment by d0ugal** [comment]
Sorry, but this isn't a bug. It is that GitHub doesn't follow the standard Markdown rules. See https://github.com/mkdocs/mkdocs/issues/545 and https://github.com/waylan/Python-Markdown/issues/3 (We use Python Markdown for rendering).

**Comment by femtotrader** [comment]
Thanks. I changed to 4 spaces and it works fine both on GitHub and ReadTheDocs.

**Comment by d0ugal** [comment]
Great!
