### ISSUE TITLE
Copyright not displayed with readthedocs theme

### ISSUE THREAD

**Issue by timbarber** [mkdocs/mkdocs#568]
It seems the copyright footer is not displayed when using the readthedocs theme. I have tried a few different themes and it then appears as expected.

I just noticed #554, perhaps this will fix it?

Cheers

**Comment by d0ugal** [comment]
@timbarber Is this when you host it on ReadTheDocs or when you build it locally? If it is when you host it on ReadTheDocs, then, yes, #554 should fix it.

**Comment by timbarber** [comment]
@d0ugal, this is happening locally when running 'mkdocs serve'.

**Comment by d0ugal** [comment]
@timbarber I just checked, it seems it was never added to the ReadTheDocs theme. We should do that.

**Comment by d0ugal** [comment]
It should just be a case of adding something like this:

            {% if copyright %}
                <center>{{ copyright }}</center>
            {% endif %}

To https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/base.html

**Comment by d0ugal** [comment]
Fixed by #584
