### ISSUE TITLE
0.13.2 not running on OS X

### ISSUE THREAD

**Issue by Duvel** [mkdocs/mkdocs#576]
Hi,

When I run mkdocs on OS X I get this error:

Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 7, in <module>
    from mkdocs.cli import cli
  File "/Library/Python/2.7/site-packages/mkdocs/cli.py", line 11, in <module>
    from mkdocs import serve
  File "/Library/Python/2.7/site-packages/mkdocs/serve.py", line 6, in <module>
    from mkdocs.config import load_config
  File "/Library/Python/2.7/site-packages/mkdocs/config/__init__.py", line 1, in <module>
    from mkdocs.config.base import load_config
  File "/Library/Python/2.7/site-packages/mkdocs/config/base.py", line 17, in <module>
    class Config(six.moves.UserDict):
AttributeError: '_MovedItems' object has no attribute 'UserDict'

Kind regards,

Remco Schoen

**Comment by d0ugal** [comment]
This is the same as #570. For some reason you have an old version of `six` (actually, you must have two installs of `six`). If you use this command you can find out where it is and what version it is.

    python -c 'import six; print(six.__version__); print(six.__file__)'

**Comment by Duvel** [comment]
That gives me:
1.4.1
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.pyc

Now I'll see how I can delete that package.

**Comment by d0ugal** [comment]
You can see somebody on the mailing list solved it. Sounds like a similar setup. https://groups.google.com/forum/#!topic/mkdocs/6IXq0PWVt6I

**Comment by Duvel** [comment]
I think this is the default setup on OS X, so maybe more of these will happen.

I solved it like this:
    cd /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/
    sudo mv six.pyc six.pyc.old
    sudo mv six.py six.py.old

After that it is good:
    $ python -c 'import six; print(six.__version__); print(six.__file__)'
    1.9.0
    /Library/Python/2.7/site-packages/six.pyc

The suggested replace on the mailing list I find suboptimal.

**Comment by d0ugal** [comment]
aha, I had no idea OSX shipped six. I might see if we can support 1.4 which seems to be the version people get.

**Comment by d0ugal** [comment]
I agree, manually updating this is horrible.

**Comment by facelessuser** [comment]
How much of six do you use? Or would it make sense to just define a couple compatibility things yourself?  I've used six before, but I often am only using maybe 3 or 4 things, so most of the time I usually just define the compatibility access myself and avoid the dependency.  Not sure how much you rely on it though.

I've personally never run into problems on OSX, but that is because I install a later version of Python along side the the shipped one and make the newer version my default.

**Comment by d0ugal** [comment]
We don't use much of six, we originally had a compat.py file and didn't use six but it drove me mad.

It did get quite big. https://github.com/mkdocs/mkdocs/blob/0.12.2/mkdocs/compat.py

**Comment by waylan** [comment]
Curious, the [setup.py][1] script lists the dependency correctly (`six>=1.9.0`). Wonder why six is not being upgraded on install?

In any event, I agree with @facelessuser -- you probably don't need six. In fact, I do the [same thing][2] with Python-Markdown. All I need is three variables:

```python
PY3 = sys.version_info[0] == 3

if PY3:
    string_type = str
    text_type = str
    int2str = chr
else: 
    string_type = basestring
    text_type = unicode
    int2str = unichr
```

You probably only need the first two. And maybe a `byte_type` -- although I found it pretty easy to get around any need for that.

[1]: https://github.com/mkdocs/mkdocs/blob/master/setup.py#L67
[2]: https://github.com/waylan/Python-Markdown/blob/master/markdown/util.py#L7

**Comment by d0ugal** [comment]
and do you just handle the conditional importing on each package within the project?

**Comment by facelessuser** [comment]
I handle the conditional importing myself within my project.  It is never so much that I am like "Oh, I need a whole library to do this".  Like I said, I've was tempted to use six before, but every time I go that route, I realize how little I actually pull from it, and then I just do it manually and kick six to the curb.  Even when I used six, I sometimes needed additional compatibility logic outside of six.  Meh, that's just me though; I try to limit the dependencies I carry around if it's easy to do myself.

**Comment by d0ugal** [comment]
Okay, let's see if we can do something about that. #583
