### ISSUE TITLE
gh-deploy assumes docs dir is located in repository root

### ISSUE THREAD

**Issue by gitblit** [mkdocs/mkdocs#578]
`gh-deploy` is assuming the `docs` directory is located in the root of the repository.  In my case, I've located my project/site sources in a subdirectory (e.g. `/site/docs`) and the following check causes `gh-deploy` to immediately terminate:

https://github.com/mkdocs/mkdocs/blob/master/mkdocs/gh_deploy.py#L10

I'm not sure if there are other downstream failures from this initial termination, but it would be nice to be able to use `gh-deploy` in this scenario.

**Comment by waylan** [comment]
Is this the same as #543? If so, I suppose this could be better documented.

**Comment by d0ugal** [comment]
Somewhat related, but this is worse :smile: If I had the following layout

    /project/
    /project/.git <- this is the repo
    /docs/
    /docs/mkdocs.yml
    /docs/source/ <- the markdown files

You would need to be in the directory above the mkdocs.yml for gh-deploy to be happy. So, we should use this:

    git rev-parse --is-inside-work-tree

**Comment by gitblit** [comment]
:+1: That would be super.
