### ISSUE TITLE
Either don't use six or support an older version (like 1.4)

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#583]
This is causing quite a few users problems, particularly on OSX.

See #576, #590 and [a mailing list post](https://groups.google.com/forum/#!topic/mkdocs/6IXq0PWVt6I). There are possible workarounds for this in the issues and email thread.

**Comment by samhatfield** [comment]
For what it's worth, I'm working on Linux Mint and I also had some issues. My system was using the six stored in `/usr/lib/python2.7/dist-packages`, which was about 1.5, even if a newer one was installed to `/usr/local/lib/python2.7/dist-packages` via pip. Eventually I had to rename the six files in the first directory to force it to use pip's version.

**Comment by d0ugal** [comment]
@samhatfield Thanks, we are trying to resolve this ASAP in #585. I'll probably roll a new release shortly after as this is causing issues for lots of people. I had no idea six was treated specially by different OSes.

**Comment by d0ugal** [comment]
This is now fixed in master, I'll be working on releasing very soon.
