### ISSUE TITLE
search encoding bug

### ISSUE THREAD

**Issue by huglester** [mkdocs/mkdocs#586]
Hello,

for example you search for:
`some fonts`
it becomes
`some+fonts`
when you press enter again, it becomes
`some%2Bfonts`

cheers

**Comment by d0ugal** [comment]
Ah, that it annoying. I guess this happens on the ReadTheDocs theme?

**Comment by ProfYaffle** [comment]
Confirmed here with the RTD theme. The space gets converted to "+", and then to %2B (so still "+"), and then each successive 'enter' adds a %25 ("%"?) - so:

some text
some+text
some%2Btext
some%252Btext
some%25252Btext
...

System, FWIW:

```
wibble:~$ mkdocs --version
mkdocs, version 0.13.3
wibble:~$ python --version
Python 2.7.6
wibble:~$ uname -a
Linux Romulus 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ian@Romulus:~$ 
```

**Comment by d0ugal** [comment]
Thanks, good catch. I can see how that would happen. I'll look into a fix if nobody else does it first :)

**Comment by samhatfield** [comment]
I think I fixed it... See [my commit](https://github.com/samhatfield/mkdocs/commit/8cf56b397b54b5cc2c75590e1bbe02dbb141cdc0). I gather the plus replacement is necessary because GET forms encode their data with a different encoding specification to JavaScript's `decodeURIComponent`?

**Comment by d0ugal** [comment]
@samhatfield Yup, that makes sense. Looks good, can you open a pull request?
