### ISSUE TITLE
Broken Links in mkdocs Documentation

### ISSUE THREAD

**Issue by ProfYaffle** [mkdocs/mkdocs#593]
[Contributing](http://www.mkdocs.org/about/contributing/) includes links to 'virtualenv', 'Tox' and 'Travis', linking to about/virtualenv, about/tox and about/travis, respectively. 

Unfortunately, all of those files seem to have slipped off together for a quiet drink and not left any contact details...

https://github.com/mkdocs/mkdocs/tree/master/docs/about

**Comment by d0ugal** [comment]
Oh, good spot. Not sure how I managed that. They should link to:

https://testrun.org/tox/latest/
https://virtualenv.pypa.io/en/latest/
https://travis-ci.org/mkdocs/mkdocs

**Comment by d0ugal** [comment]
Fixed. Turns out it was a syntax issue. :relaxed:
