### ISSUE TITLE
Remove stack trace for socket errors with mkdocs serve

### ISSUE THREAD

**Issue by samhatfield** [mkdocs/mkdocs#596]
I often forget I already have a server running on localhost:8080, and whenever I run `mkdocs serve` I get a huge stack trace with a '[Errno 98] Address already in use' at the end. I think we should just catch socket errors and spit out the error message, like for `ConfigurationError`. [Here's](https://github.com/samhatfield/mkdocs/commit/2032e6beebe3ccf1ae8f7491151a76ec71a1839b) what you could do. Should we catch all socket errors though? Or just keep 98 and re-throw the rest?

**Comment by samhatfield** [comment]
I meant port 8000, not 8080.

**Comment by d0ugal** [comment]
Ha, I often do this too. Or i have another tool running on 8000 and forget.

I think we should catch it and just output an error message.

**Comment by waylan** [comment]
@samhatfield why not create a pull request with your proposed change? That seems like the most sensible fix to me.

**Comment by d0ugal** [comment]
I think @samhatfield is [learning GitHub](https://github.com/mkdocs/mkdocs/pull/591#issuecomment-108844684), but yeah, go ahead and open a pull request :) It is best to propose changes with pull requests so we can easily review/merge.

Another addition to the release notes would be great too!

**Comment by waylan** [comment]
Sorry if my tone was off. I noticed that @samhatfield had asked for feedback on his proposed change. However he hadn't received any feedback specifically about that (at least by my reading) -- only that the general request was reasonable. I was trying to tell him that I thought his proposed change looked good and he should submit a PR. Of course, final approval comes from @d0ugal so I did not give any definitive statements regarding whether such a PR would be accepted.

**Comment by d0ugal** [comment]
Not at all :) it was useful, I actually missed the link to the commit when I read it too quickly. So glad you mentioned it, I thought it was just a very reasonable suggestion.

**Comment by samhatfield** [comment]
I was just about to submit a PR earlier, but then I saw that `socket.error` is a deprecated alias of `OSError` as of Python 3.3. OSError seems too broad to catch, and I couldn't find any appropriate subclasses. If you guys think it's fine as it is though, I'll submit a PR.

**Comment by waylan** [comment]
Well, for Python < 3.3 we would still need to catch the `socket.error` so it doesn't  cause any harm to leave it in. It appears that up through [3.6][1] `socket.error` will still be in the code base--it just inherits from a different parent class. So I would say leave it as-is.

Although, an argument could be made to catch all errors on the command line (except when in debug mode) and only output the message. However, I expect that would be a more complex issue that should be implemented across the entire CLI.

[1]: https://docs.python.org/3.6/library/socket.html#socket.error

**Comment by samhatfield** [comment]
Sure thing, #600 submitted.

**Comment by d0ugal** [comment]
Merged. Thanks!
