### ISSUE TITLE
meta page_title

### ISSUE THREAD

**Issue by robodude666** [mkdocs/mkdocs#599]
Is MkDocs intended to ignore the `page_title` meta tag and expects the theme to use it if it wants, or is it a bug that the template's `page_title` doesn't get replaced with the meta tag's contents if it exists?

**Comment by d0ugal** [comment]
Where did you see page_title? That isn't a MkDocs feature that I'm aware of :)

**Comment by d0ugal** [comment]
You are probably looking for https://github.com/mkdocs/mkdocs/issues/316

**Comment by robodude666** [comment]
I was looking through the code/docs, but that issue seems to answer it. It's not a fully implemented feature :smile:.

**Comment by d0ugal** [comment]
If it is referenced in the documentation we should fix that.

**Comment by robodude666** [comment]
There's a block in the [writing-your-docs.md](https://raw.githubusercontent.com/mkdocs/mkdocs/cb0846ab4ce228a4f9552c61164d7c58cb00bf87/docs/user-guide/writing-your-docs.md) that's commented out with lorem ipsum:

```
<!--
#### Page metadata

Unum errem propriae vis cu, et deseruisse interpretaris eam. Illum graecis per an, ludus laoreet repudiare nec an, molestie recteque et eam. Purto duis rationibus id eum, pro et amet appetere referrentur, minim impedit ad ius. Et nostrud perfecto sapientem vix, et dicit impedit consequat vim. Vis liber blandit no.

At mel verear persius torquatos, his dolores sensibus id, alia urbanitas in usu. Te pri cibo blandit. Debet dolore periculis ei pro, eu vis vidit ignota, vim natum dicta cu. Et appareat delicata vix, mei at solum lorem quodsi, verterem electram sit eu. Eius malis cum an, pro malorum euripidis ad, oblique appetere est cu. Eos ei fugit deterruisset. Vix ei aliquip dolorem, usu te euripidis reformidans, volumus pertinacia ea eam.

    page_title: Lorum
	page_description: "lorum ipsum dolor"
	source_files: example.js, lorum.js

	# Lorum Ipsum

	Unum errem propriae vis cu, et deseruisse interpretaris eam. Illum graecis per an, ludus laoreet repudiare nec an, molestie recteque et eam.
-->
```

**Comment by d0ugal** [comment]
Hah, wow. I didn't know that existed. We should delete it.

**Comment by d0ugal** [comment]
I'm not at a computer to do it now, so hopefully I'll remember tomorrow or somebody can send a PR :)
