### ISSUE TITLE
Allow nav links with depth > 2

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#6]
The default theme doesn't necessarily need to deal with styling them, but they should at least be allowed.

**Comment by OscarOrSomething** [comment]
So is this being done? When will it be released, I need it for a project I'm documenting

**Comment by d0ugal** [comment]
Nobody is currently working on this to my knowledge, but yes, it is still wanted.

**Comment by jeoygin** [comment]
I modified pages config to support this. Actually it's a backwards incompatible change. 

The pages config looks like:

```yaml
- Home: index.md
- Technology: 
  - Python:
    - Installation: tech/python/install.md
    - Tutorial: tech/python/tutorial.md
  - Ruby:
    - Installation: tech/ruby/install.md
    - Tutorial: tech/ruby/tutorial.md
```

I'm wondering whether this config is acceptable.

**Comment by d0ugal** [comment]
@jeoygin That structure is very like what I had imaged. It represents the pages as a tree which makes far more sense to me. So, yes, I think making a change like that would be a good idea. However, I'm not sure we want to make it before a 1.0 release given that it is backwards incompatible. I don't want to support two formats either ideally.

**Comment by ericholscher** [comment]
+1 on this :) 

The Sphinx theme has never really supported it, but it would be easy enough in the bootstrap ones with the third level being a nav menu popout to the right on the dropdown.

**Comment by jimporter** [comment]
This seems like a great way to format the yml, and it's definitely a lot more readable.

> However, I'm not sure we want to make it before a 1.0 release given that it is backwards incompatible.

"Before 1.0" really seems like the best time to do it. If you go by "semantic versioning", anything can change at any time before 1.0, but once you release 1.0, the API needs to remain backwards-compatible until 2.0. I think most people should be ok with things being in flux before 1.0. I generally just stick to a given git revision if I'm not in the mood to deal with breaking changes at the moment.

**Comment by d0ugal** [comment]
Sure, bad wording perhaps. I mean that we would make that change with 1.0, thus not breaking it until then.

**Comment by jimporter** [comment]
Ok, that sounds reasonable, as long as this isn't blocking something else. :)

**Comment by benwerd** [comment]
+1 to all of this. We're using MkDocs with the RTD theme over on http://docs.withknown.com/ and multi-level documentation would be very much appreciated. Rather than very long pages with lots of subheadings, we'd find it useful to point to nested sub-pages.

I think more control over the navigation in general would be welcome. For example, our initial testing suggests that having subheadings displayed in the left-hand navigation on short pages is confusing; it'd be awesome to be able to control the level of detail.

**Comment by d0ugal** [comment]
@benwerd I'm surprised that you find the subheadings confusing. That level of control would probably need to be done in a custom theme.

**Comment by benwerd** [comment]
@d0ugal I didn't find it confusing, but people I tested with did.

**Comment by d0ugal** [comment]
Noted, thanks. I'm surprised they did then :)

**Comment by tobegit3hub** [comment]
Wow, looking forward to a pull-request so that everybody can use it :+1:

**Comment by moxiegirl** [comment]
+1 on seeing that PR

**Comment by ergonlogic** [comment]
https://github.com/mkdocs/mkdocs/issues/6#issuecomment-68661197 makes a lot of sense to me. It's essentially what I tried initially, and was surprised that it wasn't supported.

It'd be good to get this in sooner rather than later. Perhaps we could add a configuration option that defaults to the current behaviour, but allows more depth. This'd avoid backward-compatibility breakage, but give those who need it access to this feature. Switching which is default at some later point, and deprecating the current behaviour becomes much less disruptive.

**Comment by d0ugal** [comment]
The problem with the solution in https://github.com/mkdocs/mkdocs/issues/6#issuecomment-68661197 is that it requires the user to enter the title for every page. That would stop us doing #316. Something like this could possibly work, but it isn't as nice.

    - Home: index.md
    - Technology: 
      - tech/something.md
      - Python:
        - tech/python/install.md
        - tech/python/tutorial.md:
            title: Python Tutorial
      - Ruby:
        - tech/ruby/install.md
            title: Ruby Tutorial
        - tech/ruby/tutorial.md

The only things stopping this, is that I've yet to see a fully thought through structure for a new pages config.

**Comment by ergonlogic** [comment]
For my part, I'd certainly prioritize allowing more depth to menus over a small convenience shortcut. But I don't really see why it'd be either/or. I think it'd be important to support https://github.com/mkdocs/mkdocs/issues/73 too. It seems like this could work:
```
- Home: index.md
- Technology: ~
  - Python: tech/python.md
    - tech/python/install.md
      - tech/python/install/debian.md
    - Tutorial: tech/python/tutorial.md
  - Ruby: ~
    - Installation: tech/ruby/install.md
    - tech/ruby/tutorial.md
```

**Comment by ergonlogic** [comment]
This would probably work (as it's valid yaml, unlike my previous suggestion):
```
- Home: index.md
- Technology: ~
  submenu:
    - Python: tech/python.md
      submenu:    
        - tech/python/install.md
        - Apt Install: tech/python/install/debian.md
    - Tutorial: tech/python/tutorial.md
  - Ruby: ~
    - Installation: tech/ruby/install.md
    - tech/ruby/tutorial.md
```

**Comment by ergonlogic** [comment]
I've started tinkering with this is in [my fork](https://github.com/ergonlogic/mkdocs/tree/dev/6)

So far, it continues to work as normal, but also supports a new config option and menu format:
```
use_new_menu: True
pages:
- Home: index.md
- Technology: tech.md
- Python: tech/python.md
- tech/python/install.md
 [...]
```

Obviously, no hierarchy to the navigation yet.

**Comment by d0ugal** [comment]
@ergonlogic Neat - that looks interesting. I'll take a look.

**Comment by funkybaboon** [comment]
+1 for a PR on more levels to navigation

**Comment by d0ugal** [comment]
In #482 I've started some work towards this. The initial change is to the pages configuration, I've restructured in a backwards compatible way to more easily allow nav depth > 2. At present that PR doesn't allow you to do that, but I think the pages structure does work well towards it - that is the next task. However, I'd like some review on the current proposed new pages config first.

Lots more detail on #482.

**Comment by tobegit3hub** [comment]
Great! I like the new configuration very much :+1:

**Comment by ergonlogic** [comment]
It's great to see this change, but it doesn't really resolve the actual feature request...

**Comment by d0ugal** [comment]
@ergonlogic why not?

**Comment by vimishor** [comment]
@d0ugal Maybe has something to do with the statement 

> This change restructures the pages configuration, but doesn't yet
allow users to add further levels in the navigation.

from PR #482 , although I see some screenshots in the same PR with navigation depth > 2

At least I thought the same think as @ergonlogic until I've seen those [screenshots](https://github.com/mkdocs/mkdocs/pull/482#issuecomment-98087113).

**Comment by ergonlogic** [comment]
Right, the commit that closed this issue clearly stated that it "doesn't yet allow users to add further levels in the navigation." My mistake :)

**Comment by d0ugal** [comment]
Ah, fair point. Sorry, I meant to reference with the first commit and close with following one but forgot.

**Comment by btiernay** [comment]
Is this ticket related to http://www.mkdocs.org/user-guide/writing-your-docs/#multilevel-documentation
> Note: At present MkDocs only supports a second level of navigation.

? If not, where can I go to follow that feature. I think this would be very useful. Thanks for such a great project!

**Comment by waylan** [comment]
@btiernay, Yes, this removed that restriction. While the change has been committed to the development version, a new release has not been made which contains the feature. If you would like to begin using it now, you will need to install the development version directly from GitHub (if cloning is beyond you, then the command `pip install https://github.com/mkdocs/mkdocs/archive/master.zip` should do the trick). However, be aware that this is the development version and is not guaranteed to be stable. That said, more people testing the code base and reporting back helps improve it and move things toward the next release.

**Comment by btiernay** [comment]
Awesome, thanks so much for the info!

**Comment by xvilo** [comment]
+1
