### ISSUE TITLE
docs versioning

### ISSUE THREAD

**Issue by huglester** [mkdocs/mkdocs#614]
Hello,

has anyone though about versioning the doc files?
What I  mean, sometimes we have older modules - older docs. and newer modules, and newer docs for these modules.

It would be nice, to have a version switcher in theme. (if more than one version available) for current module.

What do you think?

Thanks

**Comment by d0ugal** [comment]
See #193. tl;dr - yes we want it. How and when? Not sure yet.

**Comment by mattcarronflypay** [comment]
Hi @d0ugal has there been any progress on versioning at all or maybe a neat way of supporting it with the current mkdocs?

**Comment by mattcarronflypay** [comment]
Ah I have just found http://d0ugal.github.io/mkdocs-versioned/ which addresses this issue. Cheers! :)

**Comment by d0ugal** [comment]
@mattcarronflypay See the warning "This work is experimental and should be viewed as a very early alpha, that sortof works."

This was closed as a duplicate of #193
