### ISSUE TITLE
Question: Can I get help to create a search engine?

### ISSUE THREAD

**Issue by kikar** [mkdocs/mkdocs#623]
I really like the search engine implemented in the default theme, and I would like to use the same in the docs I'm building. Problem is I need to use a bit of customization.

Did you write the code for it? Could you give me a hand?

**Comment by d0ugal** [comment]
We use http://lunrjs.com/. Our integration is mostly https://github.com/mkdocs/mkdocs/blob/master/mkdocs/assets/search/mkdocs/js/search.js and https://github.com/mkdocs/mkdocs/blob/master/mkdocs/search.py
