### ISSUE TITLE
`use_directory_urls` option has no effect

### ISSUE THREAD

**Issue by thiagomael** [mkdocs/mkdocs#63]
According to the [documentation](http://www.mkdocs.org/user-guide/configuration/#preview-controls), setting the option `use_directory_urls` to **false** in the `mkdocs.yml` file should cause all links to pages within the documentation to point to their target _files_ rather than the target _directories_ (the default), but this configuration is having no effect in the html output.

**Comment by woter1832** [comment]
Has this regressed?
It's making to difference to the URLs.

**Comment by pawamoy** [comment]
Hi @woter1832, please open a new issue with a minimal reproducible example 🙂
