### ISSUE TITLE
Figure Captions

### ISSUE THREAD

**Issue by jdittrich** [mkdocs/mkdocs#630]
For showing examples and annotating them I would like to be able to caption images. 

Currently there is only the possibility to format the line following an image e.g. in italic, however text is still easily confused with any other italic text, styling is not easily done and it is semantically not correct. 

[Pandoc](http://pandoc.org/README.html#extension-implicit_figures) wraps images in a `figure` or `div` tag and adds an additional `figcaption` or `p` tag containing the alt-Text (the text in the squared brackets of an image definition) – which is probably a good solution.

**Comment by facelessuser** [comment]
This is all controlled by Python Markdown, not MkDocs.  You can write your own extension for Python Markdown to get your desired functionality and then add it under `markdown_extensions` in your `mkdocs.yml` file.

**Comment by d0ugal** [comment]
Yeah, it looks like this extension would do what you want. https://github.com/helderco/markdown-figures

**Comment by Jackiexiao** [comment]
use this extension instead: https://github.com/stuebersystems/mkdocs-img2fig-plugin

**Comment by vasvir** [comment]
I would suggest to use https://github.com/Jackiexiao/mkdocs-img2figv2-plugin since it fixes the very annoying bug https://github.com/stuebersystems/mkdocs-img2fig-plugin/issues/4
