### ISSUE TITLE
How to build API reference docs

### ISSUE THREAD

**Issue by twiecki** [mkdocs/mkdocs#641]
Along with documentation, sphinx can auto-generate references by walking through the files and looking at the doc-strings. Is this possible or are there any plans to add this?

**Comment by d0ugal** [comment]
This isn't currently possible and we have no plans to add it to MkDocs itself. I would like to see this happen via the extension API when we add one. See #206.

**Comment by d0ugal** [comment]
FWIW, API docs (and a general plugin API) is something that I really want in some cases. So it is bubbling up in priority for me but I have a few critical things I need to take care of first. So I have no idea when I would have time to take it on.

**Comment by waylan** [comment]
It is interesting to note that some people consider it bad form to generate documentation from code. For example, [this states][1] (emphasis in original):

> If your documentation is generated from source code, I am immediately skeptical. You should use words to communicate with your users, and those words shouldn’t live in your source code. **If you included all of the things needed to document a project in source, your code would be unreadable.**

> So please, use a tool that allows you to write prose documentation outside of your source code. Your users will thank you.

I realize that that is an opinion, which you are entitled to disagree with. And I expect this feature will continue to be requested until it is made available, regardless of how it is implemented (as a plugin, a Markdown extension, or built-in). But it is an opinion that many people share. In fact, that post links to a few supporting resources which, in turn, link to more people/projects who share the same opinion.

[1]: http://ericholscher.com/blog/2014/feb/27/how-i-judge-documentation-quality/#prose

**Comment by d0ugal** [comment]
Yeah, I almost totally agree. They are not a replacement to well written docs. So if all your docs are generated from code, then I think you are doing it wrong :)

However, I do like them as an additional resource to prose documentation. Personally, for example, I find them particularly useful when I know a project well but I just want to look up something I've not used in a while.

**Comment by waylan** [comment]
Can't say I disagree with you @d0ugal. Just thought that is might be good to have that stated somewhere to point people to if/when the need arises. If you read my post carefully, I indicate no opinion of my own.

**Comment by d0ugal** [comment]
Yup, I thought that was the case :)

**Comment by kernc** [comment]
User's manual is one thing, and API reference (docstrings) is another. A minimally usable documentation tool should be able to produce a HTML of the latter. Period.

**Comment by d0ugal** [comment]
> User's manual is one thing, and API reference (docstrings) is another. A minimally usable documentation tool should be able to produce a HTML of the latter. Period.

@kernc This isn't a helpful addition to the discussion. MkDocs has proven that automatically creating an API reference isn't required to be minimally usable given that we have many users. This means your claim is false**.**

Please do join the conversation and suggest ways to make this happen. You may find the discussion about a plugin API useful. See #206. I imagine that a plugin to create API reference docs would be popular and useful to a number of people.

**Comment by samuelcolvin** [comment]
Is there any progress on this? 

I'm assuming not built in or this issue would be closed/referenced; but I wondered whether any external plugin had implemented this?

**Comment by gilbsgilbs** [comment]
@samuelcolvin you may want to have a look at [pydoc-markdown](https://github.com/NiklasRosenstein/pydoc-markdown). I wasn't really convinced by the approach they were taking, but it seems that they're preparing a deep rework in the next major release. Need to keep close eyes on this project.

**Comment by waylan** [comment]
A list of all known plugins can be found on the [wiki][1], which is publicly editable. Please feel free to update the list with any missing plugins.

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Comment by nealmcb** [comment]
There are now a number of options that seem relevant, listed on the wiki.
See [MkDocs Plugins · mkdocs/mkdocs Wiki](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#api-documentation-building)

I suggest highlighting the plugin architecture, and linking to that section, in the MkDocs documentation. Right now it only points to the wiki for themes, but there is so much more now!

**Comment by encukou** [comment]
The list is now at: https://github.com/mkdocs/catalog?tab=readme-ov-file#-api-documentation-building
