### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by jspizziri** [mkdocs/mkdocs#649]
This is more of a support question/feature inquiry:

First, big fan of this tool, keep up the great work!

We currently have documentation in 100 different places organizationally and I want to unify it. My question is, I would like to leverage this tool to do documentation on a large scale (documentation for designers, ..., etc.). To do that, I would need to be able to edit users/groups and permissions to protect certain assets from certain users. Is this or will this be possible?

Also, the ability to edit the md inline would be a plus too (although the philosophy of this project might disagree, and there are a lot of technical constraints that likely arise). Some might say just to use a standard CMS for something like this however, I think that CMS's are overly complicated and something that simply stores .md files in a git repo would be ideal.

**Comment by d0ugal** [comment]
> To do that, I would need to be able to edit users/groups and permissions to protect certain assets from certain users. Is this or will this be possible?

No, that isn't possible and is out of scope for MkDocs. You could come up with a process that works around it tho' - something like GitHub and pull requests or your favourite review tool could make it work. Then all changes are reviewed by your trusted group.


> Also, the ability to edit the md inline would be a plus too

Editing Markdown outline is also out of scope, I assume you want to be able to edit the Markdown in the browser by editing the titles and have it written back to the markdown files? I can only see that being useful in a very very small number of cases and I think it would often go wrong.

**Comment by ci5er** [comment]
It might be kind of out-of-scope for this group, but you can do interactive editing w/ StackEdit (stackedit.io), and that syncs w/ DropBox and Google Drive. CouchDB, too, IIRC. Both Google Drive and DropBox can sync with Github. You might need a Zapier thingie for DropBox. And you can pull the repo's and build w/ MkDocs from there. YMMV.

**Comment by d0ugal** [comment]
+1, there are plenty of tools for collaborative editing of text files. MkDocs doesn't want to try and compete here.

**Comment by jspizziri** [comment]
Thanks guys! I figured it was out of scope but I wanted to make sure. Also thanks for pointing me in the right direction!
