### ISSUE TITLE
Create marketing materials for MkDocs. Logo, website, new theme? [Help needed]

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#655]
MkDocs could do with a logo. At the moment we use the icon from a font, but it looks quite bad as a logo.

Maybe we can find somebody that would like to contribute to a project and has the skills.

**Comment by d0ugal** [comment]
We could probably also do with a one page marketing/landing page website to show off the project and then have the docs at /docs/ or something.

**Comment by d0ugal** [comment]
and we could probably even do with a nicer, more custom default documentation theme...

I might be hoping for a bit much now :)

**Comment by robodude666** [comment]
Snazzy.

>We could probably also do with a one page marketing/landing page website to show off the project and then have the docs at /docs/ or something.

`mkdocs.org/docs/en/1.0/` :+1: :grinning:

**Comment by d0ugal** [comment]
> mkdocs.org/docs/en/1.0/

Exactly. The version and language thing is a whole other problem tho' :)

**Comment by salazarp** [comment]
Hi! Using mkdocs for a little while now and loving it. I can't contribute to the code just yet, but in the meantime I thought I'd give it a go with a concept for the logo (just a draft for the moment). 

It tries to convey the hardship of creating good documentation by liken it to the work of monks at their scriptoriums, but with a modern twist. Maybe not that well executed, but hey. Hope some other ideas start coming soon --the current logo can really do with some work ;)


![mkd-proto](https://cloud.githubusercontent.com/assets/4543956/8745284/8abdb70a-2c7e-11e5-92dd-ff81dc03acda.png)

**Comment by d0ugal** [comment]
@salazarp Hey. That is really cool. It is great to start getting some ideas out there. I think we need to also make sure we think about the new overall website and how it would work with a logo.

**Comment by georgesuba** [comment]
hey chaps, 

@d0ugal I don't think so font awesome icon of the book looks bad specially for documentation project, but this is just my personal opinion :)

I've created something like landing page for mkdocs and you can see it here: http://demo.topfreelancer.co.uk/mkdocs/ - its just one static page and of course if you would like it, we can work on it till your final likes.. @salazarp Hi! I would say your logo is brilliant but when I adjust the picture to the size - its too small and it does looks a bit not okay. 

Regards the themes for mkdocs: sure, just let me know what are you looking for and let me see what I can do for this awesome project. 

ps: feedback to landing page is very welcome. feel free to comment and give out suggestions. Thanks.

**Comment by salazarp** [comment]
hey @georgesuba! I completely understand, no worries ;)

Resizing the logo should not be a problem since the original is in .svg format, so should scale well. But to be honest, I think the drawing is too complex to work as a logo anyways. It was mostly meant to showcase an idea, and as a way to kickstart contributions (poking at that "I can do better" reflex that many have).

Also, I do like the fontawesome icon too (I was thinking of github's own book icon, which is a bit lame) but nice as it is, it doesn't do much to differentiate mkdocs, so I still think a change is in order.

Re: the landing page, it looks quite smart. I've ran it through PageSpeed Insights to see how it fares on mobiles and it shows loading way too many fonts (7 OpenSans + 5 Raleway variants) --I'd definitively optimise that.  As a thought, maybe we could even try to avoid the toll of Bootstrap in the landing page(?) That would get us better loading speeds (esp. from mobiles) and also improve pagerank a bit (not vital, but nice to have.)

**Comment by georgesuba** [comment]
@salazarp hi, sure resizing is not a problem, but I think it was too small that's all :) Thank you for feedback and I understand what are you saying :) but please bear in mind that site is maybe not 100% fast as it can be as I am hosting it from home and my uplink is not as same as somewhere in DC and on top of that if your location is in USA or else then EU it will be defo slightly slower load for you. Pagerank can be improved sure, but that is up to d0ugal, also I can minimize scripts etc however I decided to wait what guys will say, so I don't waste time on it ;)

**Comment by d0ugal** [comment]
@georgesuba Hey, I will look at this in the next few days. I was travelling and I am at EuroPython now so very busy. Thanks for the effort you put into getting this idea together!

**Comment by d0ugal** [comment]
@georgesuba Some feedback quickly.

- I think it looks good, nice and clean. It is perhaps a bit generic. What theme is this based on? What is the license for it?
- We really need a logo of some sort, and the design needs to go with that. The book isn't terrible, it just is generic and not recognisable. It would be nice to get to a point where the logo can be displayed on it's own and people will know it is MkDocs.
- I find the "mkdocs is ..." changing thing to be a bit annoying after a while, maybe it is too fast? or maybe we should just drop it
- I think it probably needs more colour
- http://gohugo.io/, https://middlemanapp.com/ https://readthedocs.org/ - They are similar or related projects, I like their websites. They are also quite simple, but they are more colourful and/or are based around a nice logo

**Comment by robodude666** [comment]
FWIW, I personally like mkdoc's current website. And while it could use some "modernization", I think it demonstrates that mkdocs eats its own dog food and does a good job of introducing new users to how easy it is to use. The simple website is one of the things that initially attracted me to try mkdocs, and hope that stays the same. Hugo's website looks beautiful, but there's too much marketing crap.

Perhaps for the logo a simple `Mk` over a document would suffice? Certainly would go with the recent "modern" website trend of taking the first letter of your name and making that your logo :wink:.

**Comment by salazarp** [comment]
Hi, just bumping the thread with a few more ideas for the logo (greyscale for the moment, colour can be applied later). I'm not a designer, as you may notice :)

Any creative around that can help with a quick sketch...? Cheers!


Dark1 | Dark2 | Dark3
-------| -------|--------
![dark1](https://cloud.githubusercontent.com/assets/4543956/10470756/d8ec4334-720f-11e5-8c3e-034fc7f7efb6.png) | ![dark2](https://cloud.githubusercontent.com/assets/4543956/10470760/d8ed871c-720f-11e5-913e-46211ce2137b.png) | ![dark3](https://cloud.githubusercontent.com/assets/4543956/10470758/d8ecfb3a-720f-11e5-8436-325abbfe68ce.png) 

Light1 | Light2 | Light3
-------| -------|--------
![light1](https://cloud.githubusercontent.com/assets/4543956/10470759/d8ed4266-720f-11e5-897f-2a5114ccf6dc.png) | ![light2](https://cloud.githubusercontent.com/assets/4543956/10470755/d8e9b70e-720f-11e5-89ed-beb7704c7674.png) | ![light3](https://cloud.githubusercontent.com/assets/4543956/10470757/d8ece140-720f-11e5-91f9-f33f0f36bb3a.png) |

**Comment by d0ugal** [comment]
There are neat. I like the direction of them more, they would be easier to use as a regular logo. Great to see more ideas!

**Comment by tomchristie** [comment]
Agree. The binder style ones look nice and modern - fan of those.

**Comment by robodude666** [comment]
I personally like the clean and modern look of Dark2/Light2/Light3, however they remind me of binder dividers that I have in a 1,500 page reference manual in a 3-inch ring binder I have at my work desk.

The thing that attracted me to MkDocs when I first discovered it was how easy it is to use, and there being almost no learning curve. I feel that the logo should envelop that easy-of-use. Possibly three sheets of loose leaf paper splayed in a fan to symbol that "you can just write your docs as if you were writing them on paper" ?

**Comment by georgesuba** [comment]
Hi Guys. I personally like dark 3 and light 1 and dark 1. @salazarp great job!

**Comment by d0ugal** [comment]
> however they remind me of binder dividers that I have in a 1,500 page reference manual in a 3-inch ring binder I have at my work desk.

Is that a bad thing? MkDocs could be a good solution to reference manuals.

Since we are all throwing in our favourites. I would probably go for Light 2 or 3.

I guess the real question is how we go about designing the MkDocs website and then making sure the logo fits in that overall picture. These different logos would match very different website designs at the moment.

**Comment by georgesuba** [comment]
@d0ugal I think it is matter of people - once the logo is selected then I don't really see the problem to change anything anywhere.. as you said these different logos would match very different website designs at the moment, which means I had few different builds, but without final logo - it can always wait I guess.

**Comment by salazarp** [comment]
Hey, thanks everyone for the feedback. This time I was more concerned with how the logo would scale up and down --from, say, a header or a hero unit, to a favicon, a slide or even a tshirt. I think those logos featuring the book will be worse off in this sense than the ones with the binder sheets.

I like Dark2/Light2. It's the same icon, and it just goes to show how having 2 "official" contrasting versions of the same logo can be very helpful, depending on the background. I also like the fact that they could work without the "Mkdocs" legend below, which can come in handy for some use cases.
Also Light3 without the bounding square I think could work.

Anyway, I am happy if a superdesigner comes in to save the day, but if not, at least there are a few options.

**Comment by salazarp** [comment]
Btw, is the colour scheme for the mkdocs.org site fixed? (#2fa4e7 light blue for the main colour). 
If that colours is already part of the mkdocs "brand", maybe we could incorporate it in the logo (or at least make sure the logo colours work well with it). Knowing it would also help anyone trying to do the website makeover, I suppose.

**Comment by georgesuba** [comment]
Hi guys, its been few weeks - and it seems to me that this was abandoned already for few months or years.. well another open sourced project. I am on my profile email if anyone need site or suggestions.. I am leaving this web development opening as creators of this project keeping failing to come to me forward with any ideas / issues. It is very sad to see the project with a glue and future to go cold turkey as this one. Perhaps it is not all gone cold turkey but regards mentioned posts here - its frozen turkey.

@d0ugal I think I gave you more then open space for coming forward with your ideas to me - however there is only one idea logged in.. nothing else. So - I am leaving this wonderful open but also I have to do other opensource projects come forward with the ideas and many did, and many was already published. Well contact me in future if you will need me... Please don't take this in wrong way but - there is no movement forward or at least I feel its not.. 

Thank you for mkdocs.

**Comment by tomchristie** [comment]
Light2/Dark2 seem like a great option yup.

Aside: would be a good plan to discuss usage & rights if we do accept these. Eg if MkDocs used the logo in a branded t-shirt a few years down the road, we'd want to be sure that we'd all agreed on its availability  for use (or otherwise)

**Comment by jberkel** [comment]
I evaluated a few generators recently and most of them have these screaming / bragging marketing sites. I ended up picking mkdocs because it just worked and looked solidly engineered but also because of its modesty. So maybe clean / spruce up the copy a bit but don't use existing site generators as an example, as @robodude666 pointed out, dog fooding is a good sign :) The generator space is getting quite crowded, so maybe it's worth pointing just a few strengths / main differences to other projects.

**Comment by tomchristie** [comment]
@jberkel good feedback there :+1:

**Comment by salazarp** [comment]
@tomchristie so what would be the most suitable license for the logo? I was thinking CC-attribution, but anything else would do (gfdl, wtfpl...) Should you guys want to use any contribution of mine, I'm happy to put it under whatever is easier for the project.

**Comment by tomchristie** [comment]
I assume that'd be fine.

**Comment by JayHoltslander** [comment]
I have artistic ability and would be interested in contributing in this area. Is there any new info since this thread left off? (Wouldn't want to step on someone's toes.)

**Comment by tomchristie** [comment]
@JayHoltslander Nothing new, no. We're lacking maintainer time on the project a bit ATM.

**Comment by JayHoltslander** [comment]
Feedback: I like @georgesuba 's landing page. But I like the flatness and simplicity of https://middlemanapp.com

So it sounds like you want to go the direction of some kind of book or binder while incorporating the "mk" of the MkDocs name?

**Comment by d0ugal** [comment]
> So it sounds like you want to go the direction of some kind of book or binder while incorporating the "mk" of the MkDocs name?

Something like that does seem reasonable, but nobody should feel limited to that either. No decisions have been made other than a desire to improve things. However, as Tom said, unfortunately we are lacking the time of a maintainer to review any suggestions so I wouldn't want you to invest lots of time into anything at this point.

We are struggling to make the next release of MkDocs, so deciding on changing all the aesthetics might be a step too far :)

**Comment by d0ugal** [comment]
A quick update to keep people in the loop. I've had some outside discussions and help with a new design and logo - I should hopefully have something to share towards the end of the month.

**Comment by jodumont** [comment]
Hi @georgesuba 

about your demo (http://demo.topfreelancer.co.uk/mkdocs/)
it is a mkdoc theme ?
do you project to make it as a mkdoc theme ?
:)

**Comment by georgesuba** [comment]
@jodumont hi, nope that is not mkdocs theme, its just plain good old html site. It could be converted to mkdocs theme as I am guessing its just adding correct tags and place it somewhere. 

Currently I use something else for my documentation: pandoc for self contained documentation generating just one html file from md (when I ship my themes or apps) and one php script where I just drop .md files and it automatically list them and parse them as html. I also developed bash script which will generate static site based on pandoc and any html files - something like blog but currently using it as alternative to gists on my own private server. I just found it very convenient, very easy to theming and adjusting towards my needs like keywords and other things . To be honest I did not use mkdocs for quiet  while now. Sorry :)

**Comment by ajcollett** [comment]
Hey, so not sure if this is the best place to report this. 

There is a link (https://mkdocs.org) floating around in all the demos and so on. This link gets flagged as Insecure. 

http://mkdocs.org works and get redirected. 

Not sure why, but there is no cert offered up for https://mkdocs.org. 

Also, great work! I am planning on using this at my University for Admin docs and so on.

**Comment by tomchristie** [comment]
It should be "https://www.mkdocs.org" everywhere.

If we've got any "https://mkdocs.org" they should be changed to include the "www" subdomain. Pull requests welcome! https://github.com/mkdocs/mkdocs/search?p=1&q=mkdocs.org&unscoped_q=mkdocs.org

**Comment by noraj** [comment]
![logo](https://user-images.githubusercontent.com/16578570/61556938-3c337400-aa63-11e9-9ec1-a3ba5643a1a6.png)

![logo](https://user-images.githubusercontent.com/16578570/61556951-42c1eb80-aa63-11e9-8562-29922295b39c.png)

Requires somewhere on the website a link to www.designevo.com

**Comment by SDR0512** [comment]
![f2b045c3-c735-476c-ac97-5e4de2d2ca3d_200x200](https://user-images.githubusercontent.com/58349712/86569446-0c3ef280-bf8c-11ea-98ec-62432dd18e17.png)

**Comment by MichaIng** [comment]
I was just looking for a logo, great to see so many contributions here, I like the second one from @noraj; modern, simple, clean 👍.

**Comment by tomchristie** [comment]
Closing as stale.
