### ISSUE TITLE
Code inside admonition's boxes looks ugly

### ISSUE THREAD

**Issue by tterrag1098** [mkdocs/mkdocs#656]
An example of code inside a warning box is here http://mcforge.readthedocs.org/en/latest/networking/simpleimpl/#making-packets

As you can see the code has an ugly white box around it, maybe the box should just be an outline? In which case the red text wouldn't be great, so we need to think of a good solution for this, it may not be so simple.

**Comment by d0ugal** [comment]
I found an example of a Sphinx project here that has them. Seems it looks almost the same but with black text. http://phpmyadmin.readthedocs.org/en/latest/setup.html#installation

**Comment by ci5er** [comment]
@tterrag1098  -- As a quick fix, you can change the `code` element definition on line 12 of your theme.css file from #e74c3c to #000.

**Comment by d0ugal** [comment]
Or use `extra_css` which means that the theme doesn't need to be forked :)

https://github.com/tterrag1098/Documentation/commit/f5a15da09170a34ba6eef60eea07e9c73122ab36#commitcomment-11887148

**Comment by tterrag1098** [comment]
@ci5er Yeah we are already working on some css adjustments, I was just putting this here for documentation's sake. Thanks though.

**Comment by tterrag1098** [comment]
Here is the CSS we are using to make code boxes look way better https://github.com/tterrag1098/Documentation/blob/testing/css/code_fixer.css

It fixes the line wrapping, and instead of a solid white box it uses a translucent white box so that it takes on a lighter color of whatever the background is.
