### ISSUE TITLE
Validate links to anchors on Markdown documents

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#658]
We do a reasonable job of checking that links to local markdown files are valid. However, the standard pattern for linking to sections is to use anchors in headers. This doesn't work well if the title is moved or renamed.

With the TOC code, we should be able to keep a set of valid anchors for each page and verify it with that.

**Comment by robodude666** [comment]
:+1: Was going to submit an issue for this.

Should take into account if a user is using a custom slugify function. Don't think this should be an issue if you continue to parse the `toc` output from markdown.

**Comment by d0ugal** [comment]
True, that is one advantage of parsing the HTML output, which is otherwise pretty hacky :)

**Comment by waylan** [comment]
Its not clear how this feature could be implemented. We validate links when rendering the Markdown to HTML. Of course, we do so for one page at a time. If a later page links to an earlier page, sure, it would be possible to validate the anchor. But if an earlier page links to a later page, no validation could happen without first processing the Markdown of the later page.

I see two possible solutions:
1. Run some sort of validator across all pages after all pages have been rendered to HTML. And that would require every page be run through an HTML parser and checked against all other pages.
2. As we parse each Markdown document, build a collection of all anchors and a collection of all links to an anchor. Then after all pages are processed, loop through the collection of links and check that any linked anchors exist in the collection of anchors.

Either way, seems like a lot of work for not much gain. I'm inclined to leave this as something for a plugin to handle and remove it from the 1.0 milestone. We can always come back to it later.

**Comment by samuelcolvin** [comment]
Would be wonderful if this could be implemented.

Especially since the links to local md files is so good, it's too easy to blithely assume the same will hold for anchor/hash links.

**Comment by joaoe** [comment]
> Its not clear how this feature could be implemented. 

This kind of validation could happen after all HTML is generated.
For each document keep a list of internal links and anchors.
Validate everything in the end.

**Comment by waylan** [comment]
@joaoe that sounds like a great candidate for a third-party plugin. Use an [on_page_content][1] event to collect all links and anchors and an [on_post_build][2] event to compare them all.

[1]: https://www.mkdocs.org/user-guide/plugins/#on_page_content
[2]: https://www.mkdocs.org/user-guide/plugins/#on_post_build

**Comment by joaoe** [comment]
Thanks for the tip :)

**Comment by johnthagen** [comment]
Did a third-party plugin ever get created for this? This seems like a really important feature.

Having moved from Sphinx, not being able to validate that the `#title` portion of links is valid adds a lot of uncertainty to keeping docs correct.

**Comment by pawamoy** [comment]
@johnthagen see https://github.com/manuzhang/mkdocs-htmlproofer-plugin 🙂

**Comment by johnthagen** [comment]
@pawamoy Thanks for the link. When I tried it though, the `htmlproofer` plugin didn't catch an invalid anchor link: https://github.com/manuzhang/mkdocs-htmlproofer-plugin/issues/13

I think this is because it is checking the return code from the browser and invalid anchor still return a 200 okay, they just do not position the browser on the page correctly.

**Comment by oprypin** [comment]
https://github.com/mkdocstrings/autorefs has a link syntax that ends up being turned into anchors, and linking to non-existent anchors *that* way happens to fail validation. So,

1. If you're OK with the different linking syntax, you can just use that.
2. This proves that a plugin doing just anchor validation is possible.
I'm not sure if such a plugin exists, but I had it on my radar to make a plugin to validate anchors and absolute links.

**Comment by johnthagen** [comment]
Anchor validation has been released into [`mkdocs-htmlproofer-plugin` version 0.5.0](https://github.com/manuzhang/mkdocs-htmlproofer-plugin/releases/tag/v0.5.0).
