### ISSUE TITLE
Use xml.etree.ElementTree to parse toc instead of HTMLParser?

### ISSUE THREAD

**Issue by robodude666** [mkdocs/mkdocs#659]
Might be able to cleanup the toc code by using an [ElementTree](https://docs.python.org/2/library/xml.etree.elementtree.html) instead of passing line-by-line into an `HTMLParser`. `ElementTree` allows you to either iterate over specific tags or return a list.

Not sure about any performance implications though, but it seems to be serving Python-Markdown well.

**Comment by waylan** [comment]
Actually, I would strongly suggest avoiding the ElementTree lib for parsing HTML. The ElementTree Parser is an XML parser and it does not handle HTML's more permissive syntax very well (it will crash and burn on invalid XML, which valid HTML5 can be). Note that while Python-Markdown does use ElementTree's document object, it does not use the XML Parser. If you want a decent HTML parser I suggest (usually in this order):

1. [lxml] (third party dependency and requires a third-party C lib)
2. [html5lib] (third party dependency, but pure Python lib)
3. [HTMLParser] (in Python 3 standard lib -- the Python 2 lib does not do proper error handling)

Interestingly, lxml and html5lib use an ElementTree document object to hold the parsed HTML, so they  give you the benefits of using ElementTree, but they are much better HTML Parsers than ElementTree's Parser. However, given the dependency issues, they are not always right for every project, and I completely understand why MkDocs is using HTMLParser.

Regarding performance implications, see [Ian Bicking's tests][1]. While old, they are still good (although, I see the graphs have gone missing somewhere along the line).

[lxml]: http://lxml.de/
[html5lib]: https://github.com/html5lib/html5lib-python
[HTMLParser]: https://docs.python.org/3/library/html.parser.html
[1]: http://www.ianbicking.org/blog/2008/03/python-html-parser-performance.html

**Comment by d0ugal** [comment]
I'm not convinced this is worth it. We only parse HTML from python-markdown which does a good job of giving us valid HTML without errors. Adding a dependency is a huge overhead we don't need. The performance difference is probably negligible.

So, simply put, I don't much like the HTMLParser code, but it works well enough and none of the other options appeal more.

I'll think about this a bit more.

**Comment by d0ugal** [comment]
Yeah, so after thinking this through I can't really think of a compelling reason to move at the moment.
