### ISSUE TITLE
Remove `include_nav` and `include_next_prev`

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#663]
Seems these two config options were never documented. I can't imagine ever wanting them either TBH :)

**Comment by tomchristie** [comment]
Perhaps we could drop em? (And eg set the nav context and next/prev context to `None` on single page sites?)

**Comment by d0ugal** [comment]
Even better.

**Comment by standage** [comment]
I didn't know about this feature, but I am very grateful to have found out about it here. Very useful when building a site/docs that don't have a strict linear progression. I would vote that the feature be documented rather than deprecated.

**Comment by waylan** [comment]
Seems to me that this customization could be offered through theme customization as described in #607. Obviously, for it to work that way a few edits to the built-in themes would be needed first.

**Comment by waylan** [comment]
This was addressed some time ago in 4a532be. I guess we missed closing this (there were a few duplicates) so I'm closing it now.
