### ISSUE TITLE
Find a way to automatically link GitHub issues from the release notes.

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#664]
In the release notes, we have gotten into quite a good habit of including the GitHub issue, this is nice for people that want extra context. It would be more useful if they actually linked back to the GitHub issue. We could link them all manually, but it would be a pain.

I suspect we would want a Markdown extension for this, one may already exist? We wouldn't want to include it in MkDocs itself, hence this having a Documentation label.

We could always wait for the plugin API if that is easier, there is no rush, but it has bugged me for a while so I thought that I would track the idea.

**Comment by waylan** [comment]
Yeah, this is definitely something to accomplish with a Markdown extension. As it is only a "nice-to-have" I'm adding it to the Post 1.0 milestone. If someone cares enough, they can create (and distribute) the extension separately.

**Comment by waylan** [comment]
This was added in #1343. Guess we missed linking that to this issue.
