### ISSUE TITLE
Add Markdown linting for MkDocs documentation

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#666]
Comment from @waylan in #624.

> it might be interesting to add that lint tool to your flake8 tests to check the Markdown source in the docs dir (as well as the README, etc.) to enforce good form in the docs. Some of them are pretty awful to read/edit right now. It is a Ruby project, but is does have a CLI so it should not be impossible to use from Tox/Travis (the Node.js clone does not have a CLI and I'm not aware of a Python clone outside of this, which is a little too special-purpose for general use).

I would like to see this happen only on Travis, simply because I don't want to require developers to install a ruby tool to run the tests. This means it could either be added to the Travis config only, or added to Tox but not included in the default run list.

This will also obviously also need to tidy up the current issues, and maybe disable some of the current failures if the fix creates too much noise.

**Comment by DavidAnson** [comment]
Unsolicited testimonial: https://github.com/mivok/markdownlint is quite nice for this kind of thing and I recommend it. On the off chance that a Node.js implementation would be easier, my https://github.com/DavidAnson/markdownlint is a port of it. I'd be happy to help if you have issues using the latter.

**Comment by d0ugal** [comment]
@DavidAnson Thanks, I plan on going with the Ruby implementation as it seems to be the canonical one. Neither is easier than the other, we'd want a Python version for that :) I started adding it in #685

**Comment by waylan** [comment]
FYI, a PR with updates to the docs can be found in #698. There are a few issues raised there. Any feedback is welcome. @DavidAnson  as you are more familiar with Markdown linting, do you have any feedback on the [bug][1] in the linter we encountered?

[1]: https://github.com/mivok/markdownlint/issues/100

**Comment by DavidAnson** [comment]
I've left some thoughts in mivok/markdownlint#100 just now.

**Comment by d0ugal** [comment]
I am going to leave this open until we can properly enforce it by removing the [allow_failure](https://github.com/mkdocs/mkdocs/blob/master/.travis.yml#L32-L33) from the Travis config.
