### ISSUE TITLE
Can't acces Markdown on VM-IP-:8000

### ISSUE THREAD

**Issue by notaduck** [mkdocs/mkdocs#671]
I have a Ubuntu running inside a VM, the issue is that i can't connect to the VM-IP:8000  
when i start the ```mkdocs serve``` then i am getting this output 
 

```
INFO    -  Building documentation... 
<notaduck> [I 150628 11:56:27 server:271] Serving on http://127.0.0.1:8000
<notaduck> [I 150628 11:56:27 handlers:58] Start watching changes
<notaduck> [I 150628 11:56:27 handlers:60] Start detecting changes
```

**Comment by d0ugal** [comment]
I think the default behaviour should never work - we don't want to listen on all IPs automatically. So, the version that should work for your usecase is:

    mkdocs serve --dev-addr 0.0.0.0:8000

However, I tried to verify this functionality with two machines in the same local network, rather than a VM and failed to get it working.

**Comment by notaduck** [comment]
I can't tell you why it won't work for you? but i did a fresh setup of Mkdocs and it seems to work just fine with 
>mkdocs serve --dev-addr 0.0.0.0:8000
