### ISSUE TITLE
mkDocs in npm?

### ISSUE THREAD

**Issue by mzaini30** [mkdocs/mkdocs#675]
Are there mkDocs in npm? Thanks :smiley:

**Comment by d0ugal** [comment]
No. MkDocs is a Python project...

**Comment by d0ugal** [comment]
So, to further add to that. I am not sure how that would work or make sense :) If you can elaborate, that would be good.

**Comment by waylan** [comment]
@mzaini30, MkDocs is on [PyPI][1] ([here][3]), which is the **Py**thon **P**ackage **I**ndex. PyPI is to Python what npm is to Node.js (in fact, "npm" stands for **N**ode **P**ackage **M**anager). If you have [pip][2], you can install packages from PyPI using the `pip` command just like the `npm` command installs packages from npm. See MkDocs' [documentation][4] for more info.

[1]: https://pypi.python.org/pypi
[2]: https://pip.pypa.io/en/latest/installing.html
[3]: https://pypi.python.org/pypi/mkdocs
[4]: http://www.mkdocs.org/#installation

**Comment by mzaini30** [comment]
@d0ugal Hahaha... Sorry, I am not an expert in javascript yet :D

**Comment by d0ugal** [comment]
@mzaini30 No problem :) It is confusing!

**Comment by mzaini30** [comment]
:v

**Comment by mohanramphp** [comment]
Love to see mkdocs in npm.

**Comment by froschdesign** [comment]
@mohanramphp 
The question was already answered. See the [comment from @waylan](https://github.com/mkdocs/mkdocs/issues/675#issuecomment-117177082) above:

> MkDocs is on PyPI (here), which is the Python Package Index. PyPI is to Python what npm is to Node.js (in fact, "npm" stands for Node Package Manager). If you have pip, you can install packages from PyPI using the pip command just like the npm command installs packages from npm.
