### ISSUE TITLE
Drop `include_nav`, `include_next_prev` from config and context.

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#679]
We should consider dropping the `include_nav` and `include_next_prev` config.
The only theme that currently references them is the builtin `mkdocs` theme, and this could presumbly instead use...

    {% if nav|length > 1 %}

...and...

    {% if next_page or prev_page %}

For contextual switching, instead of using the current context variables.

**Comment by d0ugal** [comment]
Sounds good. That'll resolve #479

**Comment by standage** [comment]
I have found disabling the next/prev buttons sitewide with a single config option is very helpful.

**Comment by waylan** [comment]
This appears to be a duplicate of #663, or at least very much related.
