### ISSUE TITLE
Ensure trailing slash present in internal links

### ISSUE THREAD

**Issue by bennuttall** [mkdocs/mkdocs#680]
Internal links are sometimes generated without the trailing slash, which breaks on some servers, including pythonhosted.org.

Example: http://pythonhosted.org/rpi-greenhouse/installing/ (click the RTC setup link in the nav bar)

Code from: https://github.com/bennuttall/rpi-greenhouse/

**Comment by waylan** [comment]
@bennuttall, which version of MkdDocs are you using?

Assuming you are using the latest version (Version 0.14.0), it appears that you are using the old, deprecated pages config. You should update your config to the [new format](http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation). I suspect that will fix your problem. In fact, if you look at the output of the build (or serve) command, there should be warnings to that effect.

Therefore, I an assuming that this is a bug in the stub which converts the old format to the new. Not sure when it will be removed though. @d0ugal, what is the deprecation schedule on this. It it worth fixing, or will it be removed in the next release?

**Comment by d0ugal** [comment]
I can't see how updating the pages config will fix this issue, but maybe it will.

If a fix is simple I'd be happy to include it. I wouldn't want to invest much time in it tho' - I had planned to keep support until we hit 1.0.

FWIW, I made a script to convert configs. https://gist.github.com/d0ugal/53a1af8ec63c906cc203 - remove the superfluous { and } from the output

**Comment by bennuttall** [comment]
Ok I had updated mkdocs to v0.14.0 prior to this, but I think the script in `/usr/local/bin` was still referring to v0.11.0 somehow? I uninstalled and reinstalled and got the new version.

I also updated to the new pages config and dropped the unsupported united theme for the readthedocs theme. I'm not seeing the issue any more - thanks for the help.

**Comment by d0ugal** [comment]
Great! We will still support the theme to, it will just be developed in its own repo. Looking for help doing that.

https://github.com/mkdocs/mkdocs-bootswatch
