### ISSUE TITLE
Deprecate or remove `use_directory_urls`

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#682]
The `use_directory_urls` setting was created before we had the `serve` command.

I think there's a strong argument for us to make now in favor of removing it, and only supporting the nice directory linking style. There's no obvious reason we should need to support file system browsing of pages - reasonable for us to assume that builds need to be behind a webserver in order to be fully functional.

**Comment by d0ugal** [comment]
I hear about people using this surprisingly often which makes me hesitant.

**Comment by d0ugal** [comment]
https://github.com/search?utf8=%E2%9C%93&q=use_directory_urls%3A+true&type=Code&ref=searchresults

Some of these are bad search results, but that is still quite a few users.

**Comment by tomchristie** [comment]
Let's close this for now as a non-issue.

**Comment by tomchristie** [comment]
On reflection I think that it's more about presentation of *what* this option is, and *when* you'd want to use it.
My hunch would be that nobody seriously wants '/index.html' links on their deployed sites, but that folks are using the setting because it helps when their looking at the local builds.
An alternative (which I've added to the document https://github.com/mkdocs/mkdocs/issues/683) would be to have a `local` config setting, which is also included as a command line argument to build. This would be *inverse* to `use_directory_urls`, when set to `True` it would generate `index.html` links.

From the command line:

    `mkdocs build --local`

In the config:

    build:
        local: True

**Comment by d0ugal** [comment]
I don't think I could guess what `local` would do. How about `offline`?

**Comment by tomchristie** [comment]
> How about offline?

Dunno - sounds like it'd build an HTML5 offline capable site.
`local_urls`, `file_urls` options?
Anyways, bikeshedding. Keeping this parked but in mind wrt https://github.com/mkdocs/mkdocs/issues/683

**Comment by waylan** [comment]
> My hunch would be that nobody seriously wants '/index.html' links on their deployed sites,

Actually, that is my preference. And in fact one of the reasons why I took a serious look at MkDocs (because you offer this feature). My only regret is that there is currently no option to also copy over the source Markdown files to the site dir. I want `somepage.html` and `somepage.md` right next to it. It is a static site. Why hide it?

If you are going to remove this feature, please want until the plugin API is available so that those of us who want it can add it back in.

**Comment by tomchristie** [comment]
Surprised, but noted. :)

**Comment by d0ugal** [comment]
I don't suppose anyone really wants doc.md -> doc/index.html but they probably ideally want doc.md -> doc.html. I sometimes wish that is what we had rather than the magic we have now.
