### ISSUE TITLE
Make readthedocs theme not depending on Google server

### ISSUE THREAD

**Issue by marienfressinaud** [mkdocs/mkdocs#690]
Readthedocs theme uses Google servers to provide the fonts. I know lot of my users don't want Google knows about where they go. It would be very nice to provide fonts directly (at least as an option).

Thanks!

**Comment by huglester** [comment]
Really good idea. Because later, sudden google will start crawling docs, which is also now always desired!

**Comment by d0ugal** [comment]
I don't really have a strong preference here but it might come under #607

**Comment by marienfressinaud** [comment]
It would be OK for me indeed

**Comment by d0ugal** [comment]
Going to close this for now. I think the theme either needs to be edited, [like this](https://github.com/FreshRSS/documentation/issues/8) or we need to handle it with #607.
