### ISSUE TITLE
import code into page from file or url

### ISSUE THREAD

**Issue by samuelcolvin** [mkdocs/mkdocs#692]
(I'm kind of amazed no one has asked about/proposed this before, if I've missed the issue, sorry. The closest I could find was #300 but that seems different)

I have some code I want to include in our help site, specifically it's examples of how to call our API. Obviously I want those examples to have tests so it makes sense to have them in the main project repo (in this case separate from the help site repo for lots of boring reasons).

Now what's the best way of including this code in a page in the mkdocs helps site? 

The current solution seem to be to copy and paste the code as a code block into the markdown file every time it changes, this seems horrible.

It would be great if we could reference a file in markdown thus:
```
Here's the example:
    
    {{ include_source_code('/path/to/file.py') }}
```

It would be relatively easy to extend this function to allow urls of files:
```
{{ include_source_code('http://www.wherever.com/file.py', language='python') }}
```

Now obviously ultimately what we need is a way to access a file in a private repo perhaps using github's [content api](https://developer.github.com/v3/repos/contents/) which would be possible, but is perhaps a bit niche.

I think the `include_source_code` function would be very useful but it might also be helpful to allow custom jinja2 functions to be defined for a project (eg. some kind of "mkdocs extensions") so special case like the above could be handled?

**Comment by samuelcolvin** [comment]
I guess custom extensions might be possible by building a custom markdown extension then using that, but that seems like a bit of a hack.

**Comment by d0ugal** [comment]
> I guess custom extensions might be possible by building a custom markdown extension then using that, but that seems like a bit of a hack.

I don't really think that is a hack, using markdown extensions with MkDocs is very common.

I think this feature is a bit specific for us to include in MkDocs core, so I'd be tempted to say it should wait for an MkDocs extension API, but that probably wont give you much more than than writing one for python-markdown directly and will be some time away.

Since we don't even have variables that can be used in Markdown yet, I would expect that we want to do that before we start to consider allowing functions too. #304 would allow that and is thus probably a prerequisite for this.

**Comment by samuelcolvin** [comment]
I was just coming to the same conclusion on markdown extensions. I think that's what I'll use.

WRT `include_source_code` I'm still kind of amazed it doesn't exist already and no one has asked for it. I was under the impression mkdocs's primary function was for "making docs" for technical projects where including source code from files would seem a very obvious demand.

I guess the fact I am the first to ask for it proves I'm wrong.

Still both the sites I've built with mkdocs could use this and a third site I built with some custom python and jinja2 specifically because this wasn't available. Indeed the django-restful-framework help site itself could also have used this I imagine.

**Comment by tomchristie** [comment]
> Indeed the django-restful-framework help site itself could also have used this I imagine.

We prefer a prose style rather than including source code verbatim. We link to the source code for each module, but otherwise not.

**Comment by d0ugal** [comment]
@tomchristie I don't think the idea is to include DRF code, but rather something like the large chunk of code in the [example section](http://www.django-rest-framework.org/#example). It could live in a file like `doc_exampes/example.py` and then in theory be included in test runs to verify it works.

It is however quite tricky to make a complete test case that also looks good in documentation without some magic.

**Comment by samuelcolvin** [comment]
yes exactly, to prove this is not just a theoretical case, [here's](https://gist.github.com/samuelcolvin/685cbee913bf5f389a8f) a summary of our case. The examples are clear enough to be published but are also tested. Coincidently they also refer to DRF but that's not the point.

As well as testing the example works, they also serve to test the system itself is working properly.

**Comment by d0ugal** [comment]
So, I think the ideal situation for this is that #304 is completed and we have an extension API. Then you could in theory have a plugin that simply grabs files and adds them to the context that is available in Markdown. It might be that it looks more like `{{ config.extra.code_samples['path/to/file'] }}` or something like that rather than a function.

So going to close that with the above being the target path but there are other options at the moment like a Markdown plugin.

**Comment by samuelcolvin** [comment]
great thanks.

**Comment by shapiromatron** [comment]
FYI, I needed this and found a solution.

I used the [mkdocs_macros_plugin](https://github.com/fralau/mkdocs_macros_plugin) and wrote a custom macro, this is the `main.py`:

```python
import os

def declare_variables(variables, macro):

    @macro
    def code_from_file(fn: str, flavor:str =""):
        """
        Load code from a file and save as a preformatted code block. If a 
        flavor is specified, it's passed in as a hint for syntax highlighters.

        Example usage in markdown:

            {{code_from_file("code/myfile.py", "python")}}

        """
        docs_dir = variables.get('docs_dir', 'docs')
        fn = os.path.abspath(os.path.join('docs', fn))
        if not os.path.exists(fn):
            return f"""<b>File not found: {fn}</b>"""
        with open(fn, 'r') as f:
            return f"""<pre><code class="{flavor}">{f.read()}</code></pre>"""

```

**Comment by parthi2929** [comment]
> FYI, I needed this and found a solution.
> 
> I used the [mkdocs_macros_plugin](/fralau/mkdocs_macros_plugin) and wrote a custom macro, this is the main.py:
> 
> ```python
> import html
> import os
> 
> 
> def declare_variables(variables, macro):
>     @macro
>     def code_from_file(fn: str, flavor: str = ""):
>         """
>         Load code from a file and save as a preformatted code block.
>         If a flavor is specified, it's passed in as a hint for syntax highlighters.
> 
>         Example usage in markdown:
> 
>             {{code_from_file("code/myfile.py", "python")}}
> 
>         """
>         docs_dir = variables.get("docs_dir", "docs")
>         fn = os.path.abspath(os.path.join(docs_dir, fn))
>         if not os.path.exists(fn):
>             return f"""<b>File not found: {fn}</b>"""
>         with open(fn, "r") as f:
>             return (
>                 f"""<pre><code class="{flavor}">{html.escape(f.read())}</code></pre>"""
>             )
> 
>     @macro
>     def external_markdown(fn: str):
>         """
>         Load markdown from files external to the mkdocs root path.
>         Example usage in markdown:
> 
>             {{external_markdown("../../README.md")}}
> 
>         """
>         docs_dir = variables.get("docs_dir", "docs")
>         fn = os.path.abspath(os.path.join(docs_dir, fn))
>         if not os.path.exists(fn):
>             return f"""<b>File not found: {fn}</b>"""
>         with open(fn, "r") as f:
>             return f.read()
> ```

Hi 

In this case, the referred md also gets built separately right if its in docs_dir?? Can we make mkdocs ignore the source file or at least specify another root location outside docs_dir, where mkdocs will not get confused or corrupt?

**Comment by waylan** [comment]
> In this case, the referred md also gets built separately right if its in docs_dir?? Can we make mkdocs ignore the source file or at least specify another root location outside docs_dir, where mkdocs will not get confused or corrupt?

This should be possible through the plugin [on_files][1] event. Of course, the "macros" plugin itself doesn't do that, but perhaps a clone of it which only provided this feature could add the option to exclude certain files.

[1]: https://www.mkdocs.org/user-guide/plugins/#on_files

**Comment by jsoucheiron** [comment]
I wanted something similar and ended up using mkdocs_macros_plugin with this:
```import importlib
import inspect

from cfripper import rules


def define_env(env):
    @env.macro
    def cfripper_rules():
        rules_inspection = inspect.getmembers(rules, inspect.isclass)
        results = []
        for _, klass in rules_inspection:
            doc = inspect.getdoc(klass)
            # Remove ABCMeta default docstring
            if not doc.startswith("Helper class that"):
                results.append((klass.__name__, doc))
            else:
                results.append((klass.__name__, None))
        return sorted(results)

    @env.macro
    def inline_source(reference):
        obj = get_object_from_reference(reference)
        source = "".join(inspect.getsourcelines(obj)[0])
        return f"```python3\n{source}```"


def get_object_from_reference(reference):
    split = reference.split(".")
    right = []
    module = None
    while split:
        try:
            module = importlib.import_module(".".join(split))
            break
        except ModuleNotFoundError:
            right.append(split.pop())
    if module:
        for entry in reversed(right):
            module = getattr(module, entry)
    return module
```

Then, you just need to add: `{{ inline_source('cfripper.model.rule.Rule.invoke') }}`

**Comment by fralau** [comment]
@parthi2929  and  @jsoucheiron glad that https://github.com/fralau/mkdocs_macros_plugin could be of help.

Indeed, the `@env.macro` decorator is new usage (replacing earlier `@macro`, which is deprecated).

**Comment by fralau** [comment]
I was looking for the _recommended_ method for including external files into mkdocs, and it turns out, that someone mentioned mkdocs, the plugin that I wrote for this.

Note that mkdocs-macros does not require macros for that, because it is nothing but a Jinja2 environment,  which offers includes as a standard feature!

```
## Paragraph
{% include 'snippet.md' %}
```
See more on: 

- Mkdocs-macro: [including snippets in pages](https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#including-snippets-in-pages)
- Jinj2: [include directive](https://jinja.palletsprojects.com/en/2.11.x/templates/#include)

**Comment by timskovjacobsen** [comment]
When using the Material theme, this can be done by the *snippets* feature via the python-markdown extension. See more here:

* https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#snippets
* https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets

You could easily have separate code files in the same project and refer them in this way.

**Comment by fralau** [comment]
> When using the Material theme, this can be done by the _snippets_ feature via the python-markdown extension. 

@timskovjacobsen thanks a lot for the reference! 

For the record, here is the link to the *snippet notation*: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation

```
--8<-- "filename.ext"
```

or 

```
--8<--
filename.md
filename.log
--8<--
```

I also learnt a new word in the process: **transclusion**. I imagine it's a portmanteau between _transfer_ and _inclusion_ ? Apparently this word had been around for a long time?... 🤔
