### ISSUE TITLE
Anchor links stradle nav bar in edge case.

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#7]
Edge case: Anchor links that happen to just straddle the nav bar when the page is fully scrolled down will trigger the 'click to bottom' javascript code and will not be scrolled to the correct position.  (See 1.0.0 anchor in screenshot)

![screen shot 2014-01-13 at 13 42 21](https://f.cloud.github.com/assets/647359/1900770/ae3523e4-7c58-11e3-962f-37a8ebd180dc.png)

**Comment by d0ugal** [comment]
Fixed by #407!
