### ISSUE TITLE
mkdocs gh-deploy

### ISSUE THREAD

**Issue by jabbalaci** [mkdocs/mkdocs#70]
`mkdocs gh-deploy` is not documented anywhere.

(1) `mkdocs help` says nothing about it

(2) I didn't find it on the homepage of the project.

It's a very useful feature, people should know about it.

**Comment by harshavardhana** [comment]
```
> mkdocs help gh-deploy
mkdocs [help|new|build|serve|gh-deploy|json] {options}
```

Nothing comes up on latest pip install

**Comment by d0ugal** [comment]
@harshavardhana That is the expected behavior. The help command only lists the commands available. This is the same as the output of just running `mkdocs` with no arguments.

This isn't ideal - we need to make the CLI interface much nicer at some point. See #259
