### ISSUE TITLE
Disabling the ToC on a specific page

### ISSUE THREAD

**Issue by pmackay** [mkdocs/mkdocs#700]
Is there any way to disable or hide the ToC on a given page? I cannot see a way to define a custom theme layout for that could be used for just one or a few pages, rather than all pages, which would be another way to do it. Is that possible at all?

**Comment by robodude666** [comment]
You should be able to define a `hide_toc` attribute in the metadata of the markdown file you don't want the ToC generated for. Then, modify the template to not render the ToC if `meta.hide_toc` is true.

**Comment by d0ugal** [comment]
Yup, good idea. That would do it. Otherwise there isn't a way to do this in mkdocs - theme customisation is required.
