### ISSUE TITLE
Link to documentations in GitHub repo is broken 

### ISSUE THREAD

**Issue by Collizo4sky** [mkdocs/mkdocs#702]
Hi @d0ugal, Here is my documentation http://docs.profilepress.net/en/latest/installation/
Clicking on the view or edit link lead to a 404 error.

Reason because the first letter of the filename is capitalized eg

`https://github.com/ProfilePress/documentation/blob/master/docs/Installation.md`

instead of `https://github.com/ProfilePress/documentation/blob/master/docs/installation.md`

**Comment by waylan** [comment]
I don't see any view or edit links on the page you link to which point to either the capitalized or lowercase location. I'm assuming you are suggesting that MkDocs is generating a bad URL. But it is not clear what URL this is or where MkDocs could be generating it from.

**Comment by d0ugal** [comment]
This is a bug with the ReadTheDocs integration. The issue should be reported with them, it looks like recent changes have broken things.
