### ISSUE TITLE
Internal md file linking triggers 404: Not Found

### ISSUE THREAD

**Issue by BentCoder** [mkdocs/mkdocs#710]
Hi,

I cannot create internal links as defined in [documentation](http://www.mkdocs.org/user-guide/writing-your-docs/#linking-documents). If I click `hello page` link below, I get **404: Not Found**. Even `mkdocs build` command doesn't export `hello.md` file at all so "site" folder has only `index.md`. Note: `hello.md` is not part of menu/navigation.

How do I solve this issue?

Regards

**resources/index.md**
```
# Resources
This is resources page. Now go to [hello page](hello.md).
```

**mkdocs.yml**

```
pages:
- Home: index.md
- Resources: resources/index.md
```

**Project Structure**

```
project
   - docs
      - resources
         index.md
         hello.md
```

**Comment by d0ugal** [comment]
Note: hello.md is not part of menu/navigation.

That's the problem. All pages need to be included in the navigation for now. See #699 for a discussion, #689 for a possible fix

**Comment by BentCoder** [comment]
That's really bad. If I have 100 document they all should appear in navigation/menu which makes MkDocs "not fit for purpose" or "fit for small purpose" !

**Comment by d0ugal** [comment]
That reply isn't helpful. As I replied, this is a known limitation and work is already going towards improving this. If this is something you need you could [consider helping.](http://www.mkdocs.org/about/contributing/)

Also, for what it is worth, I am aware of users with around 200 documents.

**Comment by BentCoder** [comment]
> That's the problem. All pages need to be included in the navigation for now.

It doesn't really say "... work is already going towards improving ..." unless we ready whole discussion and some other referencing so on. Anyway, let's drop it for now. What is the exact workaround for it, I cannot find it? I'm lost in it.

**Comment by d0ugal** [comment]
There isn't a workaround at the moment, it is dependant on the work and discussion in #699 and #689 and it is part of a larger discussion that is happening.

**Comment by BentCoder** [comment]
Last question - Have you got a rough idea when it could be implemented cos I'm happy to postpone using MkDocs until it is ready?

**Comment by tomchristie** [comment]
> What is the exact workaround for it

Put the documents in your `pages` configuration, rather than leaving them out.
