### ISSUE TITLE
Support other extensions than `yml` for `mkdocs.yml`

### ISSUE THREAD

**Issue by brutus** [mkdocs/mkdocs#711]
This is just a minor cosmetic enhancement, but it would be neat, if other extensions where recognized for the settings file (`mkdocs.yml`). Since I usually use `.yaml` for all my YAML files, it would makes organizing stuff in projects slightly easier and more organized.

**Comment by tomchristie** [comment]
I take it by "other extensions" you *just* mean *.yaml* and *.yml* right?

**Comment by waylan** [comment]
You can name your config file whatever you want. Just pass the filename with the appropriate flag:

```sh
mkdocs build --config-file whatever_name_you_want.anything
```

My point is, I'm not sure there is any benefit to expanding the default to two possible options. What happens when a third option is requested, and a fourth ...

**Comment by brutus** [comment]
@tomchristie: never came across any other. Just thought i keep it general.

@waylan: Yes this works. The annoying part is, that the `--config-file` option comes after the `build` and `serve` arguments… makes it harder to write shell aliases. But as I said, minor cosmetic thing.

**Comment by waylan** [comment]
It is a nitpick, but `build` and `serve` are not arguments, but sub-commands. Although, I suppose to the OS, they are seen as arguments (which is why git sub-commands are actually `git-commandname` under the hood).

Unfortunately, Click does not give us the flexibility to allow options defined on a sub-command to be passed by the user to the parent command and then passed through to the sub-command (annoyingly, Click would require the options to be defined twice, once on the parent command and again on the sub-command--which is not very dry and creates weird output for the `--help` flag).

**Comment by brutus** [comment]
If you would support multiple possibilities for the default filename, it could look something like this:

https://github.com/mkdocs/mkdocs/compare/master...brutus:patch-1

I thought `.yaml` is a really common ending. But I agree, it might be too much hassle, since it is just cosmetics.

**Comment by brutus** [comment]
My original thought was kinda like this: 

Since the _official file extension_ for YAML files (as stated by the maintainers of the spec) is `.yaml`, it should be supported (also see [here](http://stackoverflow.com/questions/21059124/is-it-yaml-or-yml)).

I thick the three letter form `yml` comes from old MS Windows restrictions, but I think that even there you can use extensions like `json` and `yaml` nowadays, so it is no longer needed.

If you dislike the small overhead to check for two different extensions, you could just support `yaml`. Might be not that big of a thing since mkdocs is not at version 1 yet?

**Comment by tomchristie** [comment]
The official file extension is at odds with the measured usage of the two styles (.yml is actually more common), so {shrug}

Can't see any sufficient justification for us to make a change here, and there's advantages in having a single style.

**Comment by d0ugal** [comment]
Changing the default would drive me bananas :)
