### ISSUE TITLE
resource search-results-template.mustache is not present in master.tar.gz

### ISSUE THREAD

**Issue by rickpeters** [mkdocs/mkdocs#715]
After trying out the current master branch build the search function stopped working. Reason is that the resource search-results-template.mustache is not available in the master.tar.gz.
I don't know how this happens, when I check your github repo for master branch the resource is available?

**Comment by d0ugal** [comment]
This sounds like it is a problem with our setup.py/manifest.

**Comment by waylan** [comment]
This was fixed in e3da231 some time ago.

**Comment by rickpeters** [comment]
Yes! Agreed, tested this successfully yesterday :-)
