### ISSUE TITLE
Add option to create zip of built docs

### ISSUE THREAD

**Issue by bennuttall** [mkdocs/mkdocs#719]
I'm using mkdocs and deploying to pythonhosted.org via PyPI. Here's the process:

```bash
mkdocs build
cd pythonhosted
zip -r pythonhosted.zip .
```

then browse to PyPI and use the web upload tool.

I wonder if it would be worth adding a *build zip* option, so that I could just use `mkdocs build --zip` and do the same thing. Note: pythonhosted requires an uploaded zip to directly contain the top level `index.html` rather than contain a directory with the web files in, so you need to enter the directory and build the zip from there.

Looking at the code, it looks like an parameter on the `build` and `build_pages` functions and an `if zip` option after [L259](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/commands/build.py#L259) and at the entry point in `__main__.py` might do the trick.

I might be able to implement this. Any thoughts?

**Comment by d0ugal** [comment]
You can upload to PyPI without using the website, would that cover your needs? See the docs: http://www.mkdocs.org/user-guide/deploying-your-docs/#pypi

**Comment by bennuttall** [comment]
Did not know! Awesome, thanks :)

**Comment by d0ugal** [comment]
We also have #431 which should make it even easier eventually.

**Comment by bennuttall** [comment]
Looks good!

**Comment by bennuttall** [comment]
Update: PyPI no longer supports uploading docs using setuptools. You can only use the web upload.

```
Upload failed (410): Uploading documentation is no longer supported, we recommend using https://readthedocs.org/.
```

**Comment by waylan** [comment]
@bennuttall did you try to upload to `pypi.io` or `pypi.python.org`? As I understand it, the former is the new, "pre-production" system which has a new way of uploading, whereas the later is the old system which still works fine. Personally, until the new system comes out of its "pre-production" status, I'm ignoring it.

**Comment by bennuttall** [comment]
I tried to upload to the old one:

```bash
ben@gunter:~/python-sense-hat (master) $ python setup.py upload_docs --upload-dir=pythonhosted
running upload_docs
Submitting documentation to https://upload.pypi.org/legacy/
Upload failed (410): Uploading documentation is no longer supported, we recommend using https://readthedocs.org/.
```
