### ISSUE TITLE
"help" is not a valid command

### ISSUE THREAD

**Issue by cassidoo** [mkdocs/mkdocs#720]
The documentation lists:
> Install the mkdocs package using pip:
> ```$ pip install mkdocs```
> You should now have the mkdocs command installed on your system. Run `mkdocs help` to check that everything worked okay.

But `mkdocs help` returns `Error: No such command "help".`

When you just type in `mkdocs`, it works just fine.  Not sure if I installed it incorrectly, or if the documentation should be updated.

**Comment by d0ugal** [comment]
Good spot. The docs need to be updated.

**Comment by waylan** [comment]
This was fixed in 0aa6e56 some time ago.
