### ISSUE TITLE
Menu for subpages

### ISSUE THREAD

**Issue by alasdairdc** [mkdocs/mkdocs#723]
I know the issue of subpage support has been asked before and it does this is not about that more about the menu.  Currently trying out readthedocs and not sure if this is an issue (or misunderstanding on my part) in RTD or mkdocs.  I have also read the docs I could find and know I do not need a `mkdocs.yml`.

I have the following structure
```
docs/
    index.md
    item1.md
    item2.md
    item2/
        subitem1.md
```

expected:

```
HOME [collapsable with internal headings]
item1 [collapsable with internal headings]
item2 [collapsable with internal headings including subitem1 and respective internal headings]
```

actual:

```
HOME [collapsable with internal headings]
item1 [collapsable with internal headings]
item2 [collapsable with internal headings]
item2
  subitem1 [collapsable with internal headings]
```

Is it possible to get my `expected` without manually specifying every page in a `mkdocs.yml`?  If I am just missing something would suggest an enhancement to the documentation expanding this point.

**Comment by d0ugal** [comment]
Unfortunately this is a current limitation in MkDocs. The closest you can have is this, but I think it still isn't quite what you want?

    index.md
    item1.md
    item2/
        index.md
        subitem1.md

**Comment by d0ugal** [comment]
I think what you want is #73 - which is a feature that has been requested for some time but I don't think anyone is working on it.

**Comment by alasdairdc** [comment]
No probs, thanks for the update

**Comment by d0ugal** [comment]
I think that answers everything for this issue, we can use #73 to track the further feature addition.

**Comment by AbhaysinghBhosale** [comment]
anyone can please let me know that this feature is added or not ?

**Comment by waylan** [comment]
@AbhaysinghBhosale the current behavior is fully documented [here](https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation).
