### ISSUE TITLE
Provide source filename to templates by default?

### ISSUE THREAD

**Issue by louh** [mkdocs/mkdocs#724]
The [documentation](http://www.mkdocs.org/user-guide/styling-your-docs/#meta) contains instructions for including a filename via the `meta` property, but it looks like I have to include that myself at the top of each source Markdown file?

Would it be possible to make this a "default" behavior of MkDocs? Automatically make the source filename available to the template. This way I can create links to its GitHub source, as the documentation suggests, but I wouldn't have to require that every Markdown file contain metadata referring to itself.

Thanks!

**Comment by d0ugal** [comment]
It is already available with `{{ current_page.input_path }}`

**Comment by louh** [comment]
Perfect, that's exactly what I needed.
Would you mind if I made a PR to update the documentation on the site? It's not there right now which is why I didn't find it earlier.

Thanks!

**Comment by d0ugal** [comment]
The problem with this stuff is that it starts to dive into private API's or at least, API's we hadn't designed for public consumption so it isn't that well defined. A note in [the documentation here](https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/custom-themes.md#current_page) would probably make sense.

We need to have a longer discussion about backwards comparability and what API's we are going to support for 1.0 and beyond.

**Comment by louh** [comment]
Sure, I understand. Thanks for the reply and for being really helpful.

I'm starting to pay more attention to ongoing development process and would be interested to know where 1.0 is going, and of course pitching in if it helps. We're using this to roll out a lot of documentation for Mapzen projects in the very near future.
