### ISSUE TITLE
Remove site_favicon

### ISSUE THREAD

**Issue by carlwgeorge** [mkdocs/mkdocs#725]
The documentation states that the default for `site_favicon` is ["null"](https://github.com/mkdocs/mkdocs/blame/74031a084d776f45ad43568e334da2b89133986b/docs/user-guide/configuration.md#L66-L75).

```md
**default**: `null`
```

However, if `site_favicon` is not specified, the favicon is [set](https://github.com/mkdocs/mkdocs/blob/74031a084d776f45ad43568e334da2b89133986b/mkdocs/themes/mkdocs/base.html#L10-L11) to a [book icon](https://github.com/mkdocs/mkdocs/blob/74031a084d776f45ad43568e334da2b89133986b/mkdocs/themes/mkdocs/img/favicon.ico).

```html
{% if favicon %}<link rel="shortcut icon" href="{{ base_url }}/{{ favicon }}">
{% else %}<link rel="shortcut icon" href="{{ base_url }}/img/favicon.ico">{% endif %}
```
![book](https://raw.githubusercontent.com/mkdocs/mkdocs/74031a084d776f45ad43568e334da2b89133986b/mkdocs/themes/mkdocs/img/favicon.ico)

What is the intention?  Should the book icon be used if `site_favicon` is not set?  Or should it be completely disabled if `site_favicon` is not set?  I think either the behavior should be modified to match the documentation, or the documentation should be updated to match the behavior.

**Comment by d0ugal** [comment]
Good question! I think we should update the theme to match the documentation.

Ultimately it is up to the theme how it wants to handle this, but we should do this for the mkdocs themes at least.

**Comment by d0ugal** [comment]
Good question! I think we should update the theme to match the documentation.

Ultimately it is up to the theme how it wants to handle this, but we should do this for the mkdocs themes at least.

**Comment by d0ugal** [comment]
(Sorry, accidental close)

**Comment by waylan** [comment]
I find it curious that this setting exists at all. While it certainly makes sense for users to be able to use their own custom favicon, it seems like that should be part of theme customization, not as a config setting. 

In fact, if the template was reduced to: 

    <link rel="shortcut icon" href="{{ base_url }}/img/favicon.ico">

Then, as a theme customization, a user could simply include there own favicon at `docs/img/favicon.ico` and their custom favicon will be used rather than the theme provided favicon (at least I'm assuming that it works that way based on how it works for other things). If course, if using a custom theme, the favicon could be included in the theme dir.

Not sure what value there is in also having a setting for it.

**Comment by waylan** [comment]
I'll also add that if the user has a need to use a different path/filename for their favicon (or no favicon at all), then that could also be addressed as a theme customization using the methods described in #607 (includes and/or blocks). Again, this removes the need for a favicon setting.

**Comment by carlgeorge** [comment]
Would the project be open to a pull request that removes the `site_favicon` setting completely?  Or is there a deprecation process that needs to be followed first?

**Comment by d0ugal** [comment]
@carlgeorge we can probably remove it for version 1.0.

**Comment by waylan** [comment]
As we are deprecating a bunch of template vars in 0.16 (see #921 and #1026), I just changed the milestone for this to 0.16. In fact, the template var is already being deprecated in #1026. The setting just needs to be deprecated as well.

**Comment by dragos** [comment]
It would be good to reconsider. I think most projects will want a different favicon than the stock one, and the favicon need not be an `.ico` file. It seems overkill to require theme customization for something so simple.

BTW, The `readthedocs` theme is still using the setting, [it seems](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/base.html#L11).
