### ISSUE TITLE
Question: Gollum wiki to MkDocs via "static" markdown files?

### ISSUE THREAD

**Issue by twardoch** [mkdocs/mkdocs#726]
I have the following plan: 
* I'd like to use the Github built-in wiki (which is based on [Gollum](https://github.com/gollum/gollum/), I believe) to collaboratively edit the user documentation in a private Github repo. 
* I want to use Markdown, but I'd like to use some Gollum-style wiki `[[tags]]`, possibly including some custom tags like `[[_TOC_]]` or `[[include:filename]]` — even if they’re not really supported by the Github wiki engine itself. 
* Then, I'd like to use MkDocs (or ReadTheDocs) to create the "real" user-facing documentation from that wiki. 

MkDocs supports "pure" Markdown but of course does not support the Gollum `[[tags]]`. My [example page](https://github.com/twardoch/dos-font-utils/wiki/index) page on the Github wiki has three links. First two are made using the Markdown syntax `[title](url)`, the third using the Gollum syntax `[[page name]]`. When I build my docs into ReadTheDocs directly, I get [this result](http://dos-font-utils-wiki.readthedocs.org/en/latest/), as expected. The first two links convert well, the third does not. 

So I wonder — is there any package that would allow to take a Gollum wiki and convert it to a set of static Markdown files ("inlining" all the Gollum tags like `[[include:filename]]` or `[[TOC]]` and converting the Gollum links into Markdown links)? 

Then, MkDocs or ReadTheDocs could parse the static site and build the final documentation.

**Comment by d0ugal** [comment]
I am not aware of any way to do this, it should be possible to create a python-markdown plugin to do this if somebody hasn't created one already. I am not sure what the syntax is called to google for it.

I'd say this is out of scope for MkDocs itself.

**Comment by waylan** [comment]
@twardoch to be clear, I suspect what you are requesting is possible in MkDocs via a Markdown extension. However, this is a question for [that project][0], not MkDocs (thus the closure of this issue). MkDocs has full support for using Markdown extensions, so once you get a working extension which does what you want, you can just [include it in the config][1] and it will work with MkDocs. You might want to check the list of [third party extensions][2] for anything which will work for you.  If you need to build your own extension, I would suggest you see the [documentation][3] and [tutorial][4] for instructions on building extensions. Please feel free to ask questions on the [mailing list][5]. You might  also find the [WikiLinks Extension][6] to be a good example to work from as a starting point.

[0]: https://pythonhosted.org/Markdown/
[1]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
[2]: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions
[3]: https://pythonhosted.org/Markdown/extensions/api.html
[4]: https://github.com/waylan/Python-Markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown
[5]: http://lists.sourceforge.net/lists/listinfo/python-markdown-discuss
[6]: https://pythonhosted.org/Markdown/extensions/wikilinks.html
