### ISSUE TITLE
create gitter.im chatroom instead of irc?

### ISSUE THREAD

**Issue by mlzummo** [mkdocs/mkdocs#727]

**Comment by d0ugal** [comment]
I don't have the bandwidth to monitor another chatroom. I am already heavily invested in IRC for work etc. and that wont change anytime soon.

However, I would be happy for others to go ahead and try and use it and see if it works well for them. Is there anything we need to do to enable that?

**Comment by mlzummo** [comment]
just signup and link this repo to http://gitter.im ... i can use IRC at work but its much easier to load up this and provides notifications and all as well, integrates with GH very well.

**Comment by mlzummo** [comment]
@d0ugal 
and you can them place a gitter icon where you have your other icons (for build status etc)

**Comment by d0ugal** [comment]
Created but it doesn't seem to be public.

**Comment by d0ugal** [comment]
I can't figure out how to change that. Odd.

**Comment by mlzummo** [comment]
@d0ugal 
hmm when i did it on my repo it created the gitter bandge for me and everything and made a Pull Request ... did you create the room from the repository thats what you prolly wanna do?

**Comment by d0ugal** [comment]
hmm, not sure. I don't have time to look into it at the moment, I'll try tomorrow.

**Comment by tomchristie** [comment]
I'd be happy to see an online client to the IRC room (haven't looked at IRCCloud but might be an option?) but adding a second channel wouldn't be productive (just splits the audience)

**Comment by d0ugal** [comment]
While I agree, a huge chunk of our target audience is never going to use IRC which is a shame.

**Comment by tomchristie** [comment]
@d0ugal I'd be happy to make a change, but I think we should have one thing or the other, rather than both. Assessing IRCCloud first as well would also be a prerequisite.

**Comment by d0ugal** [comment]
IRC Cloud is a fairly heavyweight thing - it is a general purpose IRC client. Maybe https://webchat.freenode.net/ is more what you had in mind.

**Comment by d0ugal** [comment]
or https://kiwiirc.com/client

**Comment by d0ugal** [comment]
but really, the problem with IRC tends to be that people come and ask questions, they are not seen for an hour or so and people unfamiliar with IRC usually just leave rather than leave it open for a while.

**Comment by ProfYaffle** [comment]
The kiwi client can be very easily embedded into a web page as well (inc. the documentation)l, and also posted into the readme.md. Doesn't stop people from posting and leaving, of course, but...

```html
[![Visit our IRC channel](https://kiwiirc.com/buttons/irc.freenode.com/mkdocs.png)](https://kiwiirc.com/client/irc.freenode.com/?nick=mkdocs|?#mkdocs)
```

... gives:

[![Visit our IRC channel](https://kiwiirc.com/buttons/irc.freenode.com/mkdocs.png)](https://kiwiirc.com/client/irc.freenode.com/?nick=mkdocs|?#mkdocs)

Or you can embed a full IRC widget somewhere with this:

```html
<iframe src="https://kiwiirc.com/client/irc.freenode.com/?nick=mkdocs|?#mkdocs" style="border:0; width:100%; height:450px;"></iframe>
```

or just link like this:

https://kiwiirc.com/client/irc.freenode.com/?nick=mkdocs|?#mkdocs

(examples generated from the Kiwiirc site).

**Comment by tomchristie** [comment]
None of those IRC options look feasible to me. Lack of polish telling.
Here's what'd convince me, personally:

Point to other major projects - what are they doing?

**Comment by ProfYaffle** [comment]
I suspect most folks either just link or use an irc:// handler to launch an external client.

Certainly, for our project I did look seriously at the embedded widgets but eventually reverted to the 'we're over *http://there* if you need us' approach.

**Comment by tomchristie** [comment]
> I suspect most folks either just link or use an irc:// handler to launch an external client.

IRC is an opaque awkward medium that excludes a huge chunk of people, so I'm sympathetic to any *widely used, serious alternative* web client that we could present. But I'd expect to see it demonstrated as being widely adopted first.
