### ISSUE TITLE
Using a period in a directory name causes the rendered title to include only the left hand side of the directory

### ISSUE THREAD

**Issue by justinkinney** [mkdocs/mkdocs#728]
I noticed that using a period in a directory name causes the rendered title to lose everything to the right of the period.

![cursor_and_seespn_docs](https://cloud.githubusercontent.com/assets/466759/10026426/95e8c814-6116-11e5-8226-01e90346c682.png)

To replicate (assuming default docs directory path):
```
mkdir -p docs/Project\ with\ a.dot
echo "#testing" > docs/Project\ with\ a.dot/test\ page\ with\ a.dot.md
mkdocs build
```

I'm guessing the problem comes from [filename_to_title()](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/utils/__init__.py#L387), but I don't have a suggestion for how to fix it at this point.

**Comment by d0ugal** [comment]
Hmm, interesting. So Python see's this as all being part of the extension. That is annoying. I am not sure what a good fix would be.

**Comment by waylan** [comment]
`filename_to_title()` calls `os.path.splitext(filename)[0]` on every name given to it. However, that should only be called on filenames, but not on directory names. Given `filename_to_title()` is only passed the base name (not the path) there is no way internally for the function to check whether it has a dir or file name (can't call `os.path.isdir()`). Therefore, that `isdir` test needs to happen in the calling code. Perhaps a second function `dirname_to_title()` could be created. Or require the ext to be removed prior to passing to `filename_to_title()`.

**Comment by justinkinney** [comment]
A naive solution I played with was essentially adding the following to `filename_to_title()`:
```
    for (dirpath, dirnames, filenames) in os.walk('docs'):
        for dirname in dirnames:
            if os.path.isdir('%s/%s' % (dirpath, dirname)):
                title = filename
            else:
                title = os.path.splitext(filename)[0]
```
it "works" but it's obviously pretty frail.
