### ISSUE TITLE
How to create link in menu to another folder.

### ISSUE THREAD

**Issue by Serhioromano** [mkdocs/mkdocs#739]
Led's say I have also documentation generated by PHPDoc and it is in `api` folder of my `/site` folder. How can I create in menu link to folder?

**Comment by waylan** [comment]
I believe that this is not possible at this time. All menu items must be existing pages within MkDocs. Perhaps such a feature would be possible if/when a Plugin API is implemented (see #206).

**Comment by louh** [comment]
If you're comfortable with editing the theme you could hard-code other things into the menu templates. For instance if you were using the bootstrap theme you could hard-code a link to `/api` in either `[nav.html](https://github.com/mkdocs/mkdocs-bootstrap/blob/master/mkdocs_bootstrap/nav.html)` or `[toc.html](https://github.com/mkdocs/mkdocs-bootstrap/blob/master/mkdocs_bootstrap/toc.html)`, overriding the default files used by the theme.

**Comment by Serhioromano** [comment]
@louh In what folder themes are installed on my mac with `pip`? I cannot find them.

**Comment by louh** [comment]
So basically here's how I have it set up.

In my config `mkdocs.yml` I set:

```yaml
theme: mkdocs
theme_dir: theme
```

The theme files are actually located in this repository: https://github.com/mkdocs/mkdocs-basic-theme

The `theme_dir` allows me to set a different folder in which theme files can be located. In my case I just named the folder `theme` but you can call it whatever you want.

Inside of the this folder, you can have whatever additional theme files you want. If it's a filename that matches some thing in the `basic_theme` folder of the `mkdocs-basic-theme` repository, it will overwrite the original file. Whatever file name that you don't have, it will use the original.

This way, I can create a file at `theme/nav.html` and it will overwrite the `basic_theme/nav.html` file, which allows me to create whatever menu navigation I want.

**Comment by Serhioromano** [comment]
Perfect @louh. Thank you very much!

**Comment by waylan** [comment]
So, if this is an issue of customizing a theme, then this is related to (and possibly a duplicate of) #607, or at the very least, documentation related to #607.

**Comment by Serhioromano** [comment]
Anyway I do not consider this an issue anymore.
