### ISSUE TITLE
Pipe Character | doesn't work inside a code block inside a table cell

### ISSUE THREAD

**Issue by MustafaHaddara** [mkdocs/mkdocs#743]
Source

```markdown
Column 1 | Column 2 | Column 3
---------|----------|---------
Pipe     | `|`      | word
```

This should produce the pipe character in a cell. Instead, it detects the `|` as the column separator and pushes the `` ` `` characters into the two cells. 
![pipe demo](https://cloud.githubusercontent.com/assets/11722214/10646220/0be0c8b4-7800-11e5-9e4a-9fbd7b92b730.png)

**Comment by MustafaHaddara** [comment]
This looks like an issue with the code python markdown parser. 

In the meantime, a workaround: use the html `<code>` tags with the html pipe literal: `&#124;`

```
Column 1 | Column 2 | Column 3
---------|----------|---------
Pipe     | <code>&#124;</code> | word
```

**Comment by waylan** [comment]
> This looks like an issue with the code python markdown parser.

You are correct. Could you raise the issue [there](/waylan/Python-Markdown) so I don't forget about it?

**Comment by MustafaHaddara** [comment]
@waylan I'm actually not sure any more -- trying to parse the markdown in a python shell works as expected. I'm assuming it's in one of the extensions that gets passed in to the `Markdown.convert()` inside of `convert_markdown` in `utils/__init__.py`.
