### ISSUE TITLE
Anchor Linking with Heading Sections

### ISSUE THREAD

**Issue by brianjking** [mkdocs/mkdocs#744]
Hello,

I'm trying to setup MkDocs so that headers will automatically (or manually) receive anchor based link support for navigation purposes using the ReadTheDocs theme.

I see it working on the MkDocs website at http://www.mkdocs.org/#preview-your-site-as-you-work, however, I'm having trouble making this work on my site.

Am I missing something?

**Comment by waylan** [comment]
That feature is enabled by the [permalink][1] option of the [TOC][2] extension to Markdown. You can see it enabled in the [config file][3]:

```yaml
markdown_extensions:
    - toc:
        permalink: 
```

[1]: https://pythonhosted.org/Markdown/extensions/toc.html#usage
[2]: https://pythonhosted.org/Markdown/extensions/toc.html
[3]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml#L23

**Comment by brianjking** [comment]
@waylan -- Thanks. How about when I'm trying to link from say a single word of a file down to a section of the same file? Alternatively, when I'm attempting to link from a word of a file to a section of another file?

**Comment by waylan** [comment]
@brianjking if you have the `permalink` option of the `toc` extension enabled, then every header will be assigned an `id`. Simply use that `id` to link to it. This is basic HTML linking techniques. Nothing unique to MkDocs or Markdown.

For example, the following header:

    # A Header

Will produce the following HTML:

    <h1 id="a-header">A Header</h1>

Note that the `id` is assigned the slug: `a-header`.

1. From the same page, use the id (slug) only as the anchor: `[link](#a-header)`.
2. From a different page, use the path and anchor: `[link](/path/to/page.html#a-header)`
3. From a different domain, use the full URL and achor: `[link](http://example.com/path/to/page.html#a-header)`

**Comment by brianjking** [comment]
Thanks!

**Comment by noel-yap** [comment]
I'd like to be able to do this from `mkdocs.yml` but `mkdocs` adds a `/` to the end of the link so that something like `    - Item: 'ANOTHER_PAGE#anchor'` creates a link for `ANOTHER_PAGE#anchor/` and the anchor doesn't work. Any advice?

**Comment by waylan** [comment]
@noel-yap are you listing `- Item: 'ANOTHER_PAGE#anchor'` as an item in your `pages` config in the `mkdocs.yml` file? If so, that won't work. You can only point nav items at pages, not subsections of a page.

**Comment by noel-yap** [comment]
Can/should `mkdocs` be changed so this would work? All that really needs to
happen is for it not to append `/` to the nav link.

**Comment by sesong11** [comment]
Is it possible to change auto generated link?
e.g `## My Header` generated `#my-header`
how can I change this auto generated to `#my-customer-link-to-header`.

**Comment by waylan** [comment]
@sesong11 if you enable the [attr-list] extension, that will allow you to define custom ids for your headers. Those ids will then be used rather than the auto-generated ones.

[attr-list]: https://python-markdown.github.io/extensions/attr_list/

**Comment by jvleminc** [comment]
> Can/should `mkdocs` be changed so this would work? All that really needs to
> happen is for it not to append `/` to the nav link.

By any chance are there any updates on this?

**Comment by petre-renware** [comment]
another solution  that works is to link directly to html. The "background" is: when `mkdocs` parse yaml file to get html pages where to go, first is looking if specified link finish with a markdown known extension (ie, like `.md`). If NOT take string as is and put it in a `href` attribute. So if you specify in nav something like `entry name = 'your_page.html#desired_section'` will happen what you want... Please take a look at generated URL. Have a wonderful day.

**Comment by pereorga** [comment]
@petre-renware this workaround is problematic on relative paths appearing in multiple places, or on anything that requires MkDocs altering the URL (such as when using the use_directory_urls setting).

**Comment by petre-renware** [comment]
> @petre-renware this workaround is problematic on relative paths appearing in multiple places, or on anything that requires MkDocs altering the URL (such as when using the use_directory_urls setting).

yes, you have right, but it solves the problem for the moment and gives you time to find a better solution... Another workaround that is possible is to make directories (with html extension ! - take a look at pdf maker but that with js included to render `mermaid` diagrams) that have simple `index.html` inside that redirects to what you want. But this workaround will be also hard to maintain for large data and link volumes... I'm supposind that what are doing exceed the level of a static portal... and should be a dynamic one with an active application server running some code... What I did in such cases was to use `mkdocs` for UI (for simplicity of using instead of HTML and with more Jinja variables) and Flask to render at run time the `mkdocs` static pages. In this case `mkdocs` is run only when change tge interface and "fixed, static, top" navigation and all dynamic part is solved at run time from `wsgi` server.
