### ISSUE TITLE
ReadTheDocs theme is not uptodate.

### ISSUE THREAD

**Issue by henrikbjorn** [mkdocs/mkdocs#746]
Comparing a Sphinx build and a MkDocs build on readthedocs using the same theme, the mkdocs one has very small text etc.

**Comment by waylan** [comment]
Is it the goal to keep the RTD theme in MkDocs up-to-date with the RTD theme for Sphinx? I haven't seen it stated that that is the goal. Of course, I haven't seen it stated that that is not the goal either.

**Comment by waylan** [comment]
This may be a duplicate of #588.

**Comment by henrikbjorn** [comment]
It is.
