### ISSUE TITLE
Markdown List not rendered.

### ISSUE THREAD

**Issue by JBelCOOL** [mkdocs/mkdocs#754]
The markdown list structure:
    * list item
    * another one
does not appear to be rendering.

mkdocs 0.14.0, python 3.4.3.

**Comment by waylan** [comment]
I just guessing here, I assume this is your sample document (is would have helped to put it in a code block):

```md
The markdown list structure:
* list item
* another one
does not appear to be rendering.
```

You need blank lines before and after the list:

```md
The markdown list structure:

* list item
* another one

does not appear to be rendering.
```

Otherwise Markdown does not know when the paragraph ends and when the list starts or when the list ends and the next paragraph starts.

**Comment by d0ugal** [comment]
This sounds like standard python-markdown behaviour and there isn't an issue. If there is, it will be with python-markdown and not MkDocs. So, I'll close this for now. Thanks @waylan!
