### ISSUE TITLE
unicode_literals is not suggested to use.

### ISSUE THREAD

**Issue by kxxoling** [mkdocs/mkdocs#758]
As click warns when I use mkdocs command:

> This is heavily discouraged because it can introduce subtle bugs in your code. 
> You should instead use explicit u"" literals for your unicode strings. 
> For more information see http://click.pocoo.org/python3/

Suggesting not to use ``from __future__ import unicode_literals`` in your code.

**Comment by facelessuser** [comment]
Read #703.  This is not a problem for mkdocs.

**Comment by kxxoling** [comment]
@facelessuser I didn't see the issue, sorry for that. But as mentioned here: https://twitter.com/mitsuhiko/status/628553189663580160 I think it would be a better choice to remove the support of Python 3.0-3.2.

Other way, can I remove the unicode_literals warning in some way?

**Comment by facelessuser** [comment]
@kxxoling Sorry if I was too terse with my answer. The way in which mkdocs is used, there isn't really an issue, so the warnings will just be turned off in the next version.  The only advice I can give is to ignore the warnings until the next mkdocs version drops.

**Comment by d0ugal** [comment]
> I think it would be a better choice to remove the support of Python 3.0-3.2.

Technically, we already only support 3.3 and 3.4.

https://github.com/mkdocs/mkdocs/blob/master/setup.py#L87-L92

**Comment by kxxoling** [comment]
@d0ugal So, it is accessible to remove this import? BTW, when will it be the next release?

**Comment by waylan** [comment]
> So, it is accessible to remove this import?

It's possible, but only if every single string literal in the source code has a `u` prepended to it (to maintain Python 2 support). Uhg. Given that the potential problems with unicode_literal do not effect MkDocs (we don't use it in a way that can cause those problems), I see no benefit to doing so.

**Comment by d0ugal** [comment]
> BTW, when will it be the next release?

@kxxoling For now there is no ETA for the next release. I tried to promise one before but utterly failed to meet it. Also, currently there are not enough resources working on the project to make a release.
