### ISSUE TITLE
Linebreak

### ISSUE THREAD

**Issue by huglester** [mkdocs/mkdocs#760]
Hello, is it this possible to make a linebreak? Simply writing the:

```
this
is
second
line
```
make them into one line for me. where could be the issue?

**Comment by louh** [comment]
This is normal Markdown behavior. You can use the [nl2br](https://pythonhosted.org/Markdown/extensions/nl2br.html) (newline-to-break) extension to enable what you describe.

Add it to the `mkdocs.yml` [configuration file](http://www.mkdocs.org/user-guide/configuration/#markdown_extensions):

```yaml
markdown_extensions:
    - nl2br
```

**Comment by waylan** [comment]
You can also create line breaks with plain old markdown if you use Markdown's syntax as described in the [docs][1]:

> When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.

[1]: http://daringfireball.net/projects/markdown/syntax#p

**Comment by d0ugal** [comment]
I think that covers everything, thanks @louh and @waylan!
