### ISSUE TITLE
Search feature doesn't work off mkdocs master

### ISSUE THREAD

**Issue by dmehra** [mkdocs/mkdocs#764]
Reposting from https://groups.google.com/forum/#!msg/mkdocs/AmwN77dwcsE/oqxJ9YlyCSUJ

I forked mkdocs from git master (in order to make some modifications, PR https://github.com/mkdocs/mkdocs/pull/752 pending), and search stopped working for me. It worked when using the released version of mkdocs; in both cases using Python 2.7.10 on OS X Yosemite.

The error I get is
```
[W 151117 14:26:20 web:1946] 404 GET /mkdocs/js/search-results-template.mustache (127.0.0.1) 5.50ms
```

There is no additional info when running with debug on (mkdocs serve -v). On my docs site, there is no error message, only "Sorry, page not found" when trying to search for anything. The console shows:
```
Failed to load resource: the server responded with a status of 404 (Not Found)  http://127.0.0.1:8000/mkdocs/js/search-results-template.mustache
require.js:8 Uncaught Error: ./mkdocs/js/search-results-template.mustache HTTP status: 404
```

Let me know if I can help debug this any better, thanks. Advice on a workaround would be great too, as I have to keep running mkdocs off master, and would like to have search.

**Comment by samuilovaa** [comment]
I have the same bug. I use mkdocs 0.14.0 and Python 3.4.0 under Windows 10 to build html doc.

**Comment by d0ugal** [comment]
Hmm, this is a strange one. I thought from reading the email thread that it would be an obvious break - however, it seems to work fine for me.

I am running Python 2.7.10, Chrome 46 on Fedora 22. I tested on the mkdocs and readthedocs themes also.

**Comment by d0ugal** [comment]
Which theme are you both using?

**Comment by samuilovaa** [comment]
I use readthedocs theme.

**Comment by samuilovaa** [comment]
I've tested in default mkdocs theme and have the same bug.

**Comment by dmehra** [comment]
Readthedocs theme, modified per https://github.com/mkdocs/mkdocs/pull/752 (mods unrelated to search)

**Comment by d0ugal** [comment]
If you do `mkdocs build` and `ls -la site/mkdocs/js` (assuming you have not changed the [site_dir](http://www.mkdocs.org/user-guide/configuration/#site_dir) setting), what do you see? There should be a file called `search-results-template.mustache`. This is the file that is missing for some reason when you run `mkdocs server` - I want to try and establish if the problem is wish building or serving (or both).

I get:
```
$ ls -la site/mkdocs/js 
total 76
drwxr-xr-x. 2 dougal dougal  4096 Nov 24 16:33 .
drwxr-xr-x. 3 dougal dougal  4096 Nov 24 16:33 ..
-rw-r--r--. 1 dougal dougal 14502 Nov 24 16:33 lunr-0.5.7.min.js
-rw-r--r--. 1 dougal dougal  8835 Nov 24 16:33 mustache.min.js
-rw-r--r--. 1 dougal dougal 15292 Nov 24 16:33 require.js
-rw-r--r--. 1 dougal dougal  2593 Nov 24 16:33 search.js
-rw-r--r--. 1 dougal dougal    90 Nov 24 16:33 search-results-template.mustache
-rw-r--r--. 1 dougal dougal 15611 Nov 24 16:33 text.js
```

**Comment by dmehra** [comment]
Right, I get those files with exception of search-results-template.mustache:
```
$ mkdocs build --clean
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /Users/dmehra/git/juttle/site 
$ ls -la site/mkdocs/js 
total 128
drwxr-xr-x  7 dmehra  staff    238 Nov 26 16:08 .
drwxr-xr-x  4 dmehra  staff    136 Nov 26 16:08 ..
-rw-r--r--  1 dmehra  staff  14502 Nov 26 16:08 lunr-0.5.7.min.js
-rw-r--r--  1 dmehra  staff   8835 Nov 26 16:08 mustache.min.js
-rw-r--r--  1 dmehra  staff  15292 Nov 26 16:08 require.js
-rw-r--r--  1 dmehra  staff   2593 Nov 26 16:08 search.js
-rw-r--r--  1 dmehra  staff  15611 Nov 26 16:08 text.js
```

**Comment by dmehra** [comment]
Ok so simply placing the .mustache file into site/mkdocs/js didn't do anything, but this worked (with sudo because my virtualenv was messed up, so i installed mkdocs globally):
```
mkdocs-fork $ sudo cp ./mkdocs/assets/search/mkdocs/js/search-results-template.mustache build/lib/mkdocs/assets/search/mkdocs/js/
mkdocs-fork $ sudo python setup.py install

docs $ mkdocs build --clean 
docs $ mkdocs serve
```
After this, `search-results-template.mustache` is in the expected site/mkdocs/js location, and search works.

I hope this helps figure out which build step isn't working.

**Comment by samuilovaa** [comment]
It seems that I have another problem, because I see ```search-results-template.mustache``` in site folder when I build a website.

**Comment by coderstephen** [comment]
I don't know if this info helps anyone at all, but I only experience this problem when using `mkdocs serve`. With the development server, there seems to be no `search-results-template.mustache` file. But when I run `mkdocs build`, it does generate the correct `search-results-template.mustache` file in the correct location.

**Comment by d0ugal** [comment]
That is useful. If it is there when the documentation is built it lowers the severity of this bug.

**Comment by d0ugal** [comment]
.... but we still need to get it fixed before doing a 0.15 release, otherwise we will just get a million questions from confused users :)

**Comment by coderstephen** [comment]
Hmm, never mind. I already had the search template from another build :stuck_out_tongue:.

I think I've figured some things out though. I tried uninstalling and reinstalling several times, and noticed that the search template file isn't even included in the latest install. So I proceeded to use a process like this:

```sh
$ sudo pip install mkdocs # install 0.14
$ ls /usr/local/lib/python2.7/dist-packages/mkdocs/assets/search/mkdocs/js
total 64K
-rw-r--r-- 1 stephen stephen  15K Jan 16 20:30 lunr-0.5.7.min.js
-rw-r--r-- 1 stephen stephen 8.7K Jan 16 20:30 mustache.min.js
-rw-r--r-- 1 stephen stephen  15K Jan 16 20:30 require.js
-rw-r--r-- 1 stephen stephen 2.6K Jan 16 20:30 search.js
-rw-r--r-- 1 stephen stephen   90 Jan 16 20:31 search-results-template.mustache
-rw-r--r-- 1 stephen stephen  16K Jan 16 20:30 text.js
# OK, looking good. Now let's try master.
$ sudo pip uninstall mkdocs
$ sudo pip install https://github.com/mkdocs/mkdocs/archive/master.zip
$ ls /usr/local/lib/python2.7/dist-packages/mkdocs/assets/search/mkdocs/js
total 64K
-rw-r--r-- 1 stephen stephen  15K Jan 16 20:30 lunr-0.5.7.min.js
-rw-r--r-- 1 stephen stephen 8.7K Jan 16 20:30 mustache.min.js
-rw-r--r-- 1 stephen stephen  15K Jan 16 20:30 require.js
-rw-r--r-- 1 stephen stephen 2.6K Jan 16 20:30 search.js
-rw-r--r-- 1 stephen stephen  16K Jan 16 20:30 text.js
# No template in master.
```

I installed each commit starting after version 0.14 and identified the commit that stopped installing the search template file. Said commit is aa7c34e3a799ff9377a381d4e35c52c91e28cea9.

You can verify this yourself as follows:
```sh
# Install commit right before offending one.
$ sudo pip install https://github.com/mkdocs/mkdocs/archive/00f96640c4cdd1dd0c31355c67521c7f42161c6f.zip
$ ls /usr/local/lib/python2.7/dist-packages/mkdocs/assets/search/mkdocs/js
total 64K
-rw-r--r-- 1 stephen stephen  15K Jan 16 20:30 lunr-0.5.7.min.js
-rw-r--r-- 1 stephen stephen 8.7K Jan 16 20:30 mustache.min.js
-rw-r--r-- 1 stephen stephen  15K Jan 16 20:30 require.js
-rw-r--r-- 1 stephen stephen 2.6K Jan 16 20:30 search.js
-rw-r--r-- 1 stephen stephen   90 Jan 16 20:31 search-results-template.mustache
-rw-r--r-- 1 stephen stephen  16K Jan 16 20:30 text.js
# Install offending commit.
$ sudo pip install https://github.com/mkdocs/mkdocs/archive/aa7c34e3a799ff9377a381d4e35c52c91e28cea9.zip
$ ls /usr/local/lib/python2.7/dist-packages/mkdocs/assets/search/mkdocs/js
total 64K
-rw-r--r-- 1 stephen stephen  15K Jan 16 20:30 lunr-0.5.7.min.js
-rw-r--r-- 1 stephen stephen 8.7K Jan 16 20:30 mustache.min.js
-rw-r--r-- 1 stephen stephen  15K Jan 16 20:30 require.js
-rw-r--r-- 1 stephen stephen 2.6K Jan 16 20:30 search.js
-rw-r--r-- 1 stephen stephen  16K Jan 16 20:30 text.js
```

I know very little Python, or Python packaging, so I can't give any insight as to what is wrong with aa7c34e3a799ff9377a381d4e35c52c91e28cea9, but hopefully narrowing down the changes that broke something will help.

**Comment by d0ugal** [comment]
@coderstephen Great work. So it looks like when I tried to remove the custom packaging code from MkDocs I broke something. I am wondering if adding the file extension to the [manifest](https://github.com/mkdocs/mkdocs/blob/master/MANIFEST.in#L3) will solve the issue. Otherwise I can just revert aa7c34e.

**Comment by d0ugal** [comment]
I've added it to the manifest in e3da231798de0080a876fba7a1c3881928ab3e1b and a quick test locally shows that the file is added to the package. If others could try master again now and let me know if it is resolved that would be great. Thanks!

**Comment by coderstephen** [comment]
@d0ugal Yep, that fixed it. Nice work! :+1:

**Comment by d0ugal** [comment]
Great!

**Comment by samuilovaa** [comment]
I use 0.15.0 and I still have this error. search-results-template.mustache exist but it contains the following:
<article>
  <h3><a href="{{location}}">{{title}}</a></h3>
  <p>{{summary}}</p>
</article>

**Comment by d0ugal** [comment]
That is all it should contain. https://github.com/mkdocs/mkdocs/blob/master/mkdocs/assets/search/mkdocs/js/search-results-template.mustache

Search is working on http://www.mkdocs.org/ and it uses 0.15.

**Comment by shiraze** [comment]
I'm using mkdocs 0.15.3 on Windows and see exactly the same issue mentioned above.
`mkdocs serve` allows document searching and doesn't throw any errors, but `mkdocs build` results in a site that doesn't allow searching, throws errrors about the missing file, and the js folder only contains the following:
```
highlight.pack.js
jquery-2.1.1.min.js
modernizr-2.8.3.min.js
theme.js
```

**Comment by waylan** [comment]
@shiraze that list of files are the files in the `/js` directory. Search files are is in the `/mkdocs/js` directory. Sorry, I don't know why they're in a separate dir.

Also, different behavior for `serve` and `build` does not make sense as all `serve` does is call `build` then start a server on the build dir. There is no reason I can think of for files to be missing from one and not the other.

The problem that was fixed in this issue was that the files were not being included in the package. However, if you are getting the files when calling `serve` the files are included in the package. Therefore, you would appear to be having a separate issue. I would recommend opening a new issue.

**Comment by d0ugal** [comment]
> @shiraze that list of files are the files in the /js directory. Search files are is in the /mkdocs/js directory. Sorry, I don't know why they're in a separate dir.

One is added by the theme, the other (under `/mkdocs/`) is general assets available to all themes. It's a bit confusing but it was the only way I could think of easily avoiding collisions.

It's interesting to see in @shiraze's edit that IIS doesn't like `.mustache` files. Maybe we should rename it, I just used that as I thought it was the normal practice.

**Comment by waylan** [comment]
Content types on Windows is being tracked in #897, which I'm working on as we speak -- at least in regard to the dev server. Of course, other, third party servers will have their own issues. But, I suppose it makes sense to avoid non-standard file extensions to keep the number of issues down. I have no idea how standard `.mustache` is.

In any event, on Windows I get:

```
>>> mimetypes.guess_all_extensions('text/template')
[]
```

So it would appear there are no standard extensions for `text/template`.

**Comment by shiraze** [comment]
Thanks for your comments, and for looking into this. The issue appears to be IIS issue, and is easily resolved by adding a suitable web.config or setting IIS global mime type settings.

**Comment by steveshortt** [comment]
> @shiraze  FIXED!
> 
> The issue related to IIS, and how it failed to server json/mustache files.
> Fixed by adding mime-types in IIS:
> json: application/json
> mustache: text/template


This worked for me, too.  I added the mime types on a test server, and Search came right to life (using the 'readthedocs' theme).  I'll likely use a web.config update in prod.

**Comment by helenhillrunck** [comment]
I added the mime types (json was already there) but with no luck. I am running mkdocs 0.15.3 and have tried both the mkdocs and readthedocs theme. The search works in both themes after running mkdocs server and opening http://127.0.0.1:8000/. However when I run mkdocs build and open site/index in either Chrome or IE the search does not work.

**Comment by waylan** [comment]
@helenhillrunck search does not work if you are not running a server. The way it is implemented requires a server. That has always been the case. You may be able to get it working if you disable variable browser security policies, but that is not recommended. As everything works fine behind the server, just use the server.

**Comment by helenhillrunck** [comment]
Thank you so much for the quick response!

**Comment by flxkid** [comment]
@waylan So is it not advised to use mkdocs with a project for offline documentation since search doesn't work without a server? Maybe search should be disabled if accessed from file:// so that it isn't "broken".

**Comment by waylan** [comment]
> So is it not advised to use mkdocs with a project for offline documentation

Yes, that is correct. We don't test for that use case and don't guarantee things will work. In fact, the default settings will not work out-of-the-box (see [use_directory_urls][1]) regardless of search.

On top of that,  many modern browsers have made it impossible with their default security settings (XMLHttpRequests are not permitted on pages loaded from `file://` locations and search needs to use an XMLHttpRequest to retrieve the search index). While those settings can be overridden, it creates a security vulnerability for the user and is not recommended. 

[1]: http://www.mkdocs.org/user-guide/configuration/#use_directory_urls

> Maybe search should be disabled if accessed from file:// so that it isn't "broken".

As this wouldn't give us much benefit (default MkDocs settings still need to be overridden) and could potentially encourage poor security practices (people would be disabling browser security settings), I'm inclined to disagree.

Can someone explain to me the use case for serving the files from `file://`. I keep seeing people stumble over this and I'm not following. The intended use case for MkDocs (as I understand it) is that locally (while authoring/customizing your site) you use the included dev server, and then you upload and host the built site on a public server somewhere. Where does local file access come in? I've always assumed its from people who are new to web development and/or people who don't have a good development stack/tools... in order words, people who should be using the dev server but aren't due to lack of knowledge/tools/both. What is a valid use case for not using a server?

**Comment by flxkid** [comment]
@waylan The use case is related to products/projects that ship as an installer where they want to include the documentation as part of the product. I'd imagine this would happen more often on Windows, but wanting to ship a "static" version of the documentation I think is a fairly common practice. In this case, file:// access is really needed as the alternative (with mkdocs) is to ship a ton of stuff that isn't really part of the product that you're using mkdocs to document.

After all, the very first sentence of the description for mkdocs is:

>  MkDocs is a fast, simple and downright gorgeous static site generator that's geared towards building project documentation. 

When people see "static site generator" I think the expectation is that no server components should be needed...just static resources that should be able to load from file://

**Comment by helenhillrunck** [comment]
Oops guess I asked the wrong question re searching. I AM new to MkDocs. I installed it two days ago and love how easy it is to use. I am a technical writer and was asked to look at using MkDocs to replace the PDF and chm files currently distributed with our product documentation.  I easily converted a 30 pg guide from Word using mkdocs and love the new format. 

However, unless a decision is made to host the information on a server rather than ship it with the product we will have to try something else.

**Comment by waylan** [comment]
> using MkDocs to replace the PDF and chm files currently distributed with our product documentation. 

I've given some thought to this over the last couple days; specifically asking myself the question: "Is this something MkDocs might want to support?" And I don't think it is. The primary concern is search. With a PDF, or a chm file (or its alternatives on other platforms such as Apple Help Viewer), search is available across multiple pages. However, there is no practical way to implement search across multiple HTML pages without a server running unless you require your users to disable the security features of their browsers. In the end, a PDF or a chm file (or Apple help file) will give the user a much better experience.

I suppose someone could use one of those libraries which wraps a one-off browser and implements its own search feature. But that would basically be re-implementing the chm file browser. A few such efforts already exist. A quick search turned up [QT Assistant][1] and [HelpBlocks][2] (for example, I have used neither and can make no recommendations--I'm not even sure they use HTML under the hood). Of course, such a platform would need to be downloaded and installed by each user, so the cross-platform benefit is offset by that. And while a tool like MkDocs with a custom template might be able to generate HTML which such a platform could use, I would expect these platforms already have their existing communities and tools.

My point is that using MkDocs on its own would be a sub-par experience and shoehorning MkDocs into some more elaborate system would be a lot of work and outside the scope of the core project.

@helenhillrunck if you are looking to use Markdown to generate content in a different file format (certainly would be my preference), you might want to look at [Pandoc][3]. It can convert between many different formats. The default is pretty boring, unstyled output, but with the proper options, you may be able to get something which looks nice too.

[1]: http://doc.qt.io/qt-4.8/assistant-manual.html
[2]: http://www.helpblocks.com/
[3]: http://pandoc.org/

**Comment by flxkid** [comment]
@waylan sphinx-doc seems to have a means of doing search from a file:// based html static system. It looks like they create an index at compile time. Maybe MkDocs could do something similar.

I'm not trying to force the issue. But I think there are ways of doing this without hitting browser security constraints.

**Comment by waylan** [comment]
>  sphinx-doc seems to have a means of doing search from a file:// based html static system.

Are you sure that search works across multiple pages? Or can you only search within the current page?

> It looks like they create an index at compile time.

I have a working fork of MkDocs which does this (still in testing). However, how do you access the pre-built index without using an `XMLHttpRequest`?  If Sphinx has solved that, then I would like to know how.

**Comment by waylan** [comment]
I got curious about how Sphinx does it and their solution is an interesting hack. Not sure if it will work with the tools we use though. In any event, they load their search lib along with the other JS libs for the page as per normal. Then they define an empty script tag in the HTML with a specific id attribute. Once the page is loaded they update that empty script tag (referencing it by id) and populate the `src` attribute with the url of their search index. The search index is actually a JavaScript file (rather than JSON) and looks more-or-less like this:

    Search.load_index({ /*...the search index JSON object goes here ... */ })

Once the `src` attribute is updated, the browser will download and process its contents. No XMLHttpRequests necessary.

**Comment by waylan** [comment]
Whether that hack is used depends on whether we can do something similar from within a webworker (see #859). If not, when the Plugin API (see #206) is finished, someone could implement it as an alternate search plugin.

**Comment by motikagan** [comment]
I'm another technical writer here to say that search in static local files would be important to me. Implementing help in the form of locally stored files that come bundled with an app seems like the natural way to go in many cases. By the way, mkdocs is wonderful, thank you for it.

**Comment by rmzelle** [comment]
I was able to fix it following the advise given above about editing my `web.config` file (https://github.com/mkdocs/mkdocs/issues/764#issuecomment-219607169). Just to help others along, this is what worked for me:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <staticContent>
            <mimeMap fileExtension=".json" mimeType="application/json" />
            <mimeMap fileExtension=".mustache" mimeType="text/template" />
        </staticContent>
    </system.webServer>
</configuration>
```

(see also http://blogs.iis.net/bills/how-to-add-mime-types-with-iis7-web-config)
