### ISSUE TITLE
optimize how `mkdocs serve` reacts to multiple files updated quickly

### ISSUE THREAD

**Issue by vlcinsky** [mkdocs/mkdocs#766]
I use mkdocs with my own pre-processing, which regenerates couple of `*.md` files in docs directory.

The pre-processing uses jinja2 templating and often changes multiple files very quickly

When using `mkdoc serve`, and multiple files change at once, it triggers multiple builds of the whole site.

```
$ mkdocs serve
INFO    -  Building documentation... 
[I 151128 12:58:16 server:271] Serving on http://127.0.0.1:8000
[I 151128 12:58:16 handlers:58] Start watching changes
INFO    -  Building documentation... 
INFO    -  Building documentation... 
INFO    -  Building documentation... 
INFO    -  Building documentation... 
INFO    -  Building documentation... 
INFO    -  Building documentation... 
INFO    -  Building documentation... 
INFO    -  Building documentation... 
INFO    -  Building documentation... 
```

When I use it for larger projects and there change 20 or more pages, the rebuild task takes in total
too much time (and I had to stop using `server` and turn to using `python -m SimpleHTTPServer`
combined with background job rebuilding the site only once.
# Proposed optimization

Before triggering autorebuild, wait fraction of a second and check, if there are more updates
comming. If so, wait another fraction of second untill the changes stop, start the build task after
that.

I am not sure, how to implement it (after quick research of `livereload` I have found that `server.watch(..., delay=?)` did not work for me.

One (crazy?) idea would be to (re)schedule the build command into near future. Burst of rebuild requests would keep rescheduling the task into near future until the burst completes and the build task itself gets really executed.

**Comment by waylan** [comment]
It seems to me that this should be handled by livereload. Although I'm not that familiar with livereload's feature set. If they don't already support such a feature, then it should be added upstream.

**Comment by waylan** [comment]
You can now use the `--dirty` flag to only build pages which have been edited (#997). I think that should sufficiently address this issue.
