### ISSUE TITLE
python executable

### ISSUE THREAD

**Issue by MiPnamic** [mkdocs/mkdocs#769]
As a Mac OS User I use homebrew, I upgraded MkDocs to the last versions and it says:

> import click
> ImportError: No module named click

I found that the main problem is in the mkdocs executable

> #!/usr/bin/python

but, in my case, it should be

> #!/usr/local/bin/python

as homebrew install everything and configure my custom tools under **/usr/local/**

AFAIK it should be:

> #!/usr/bin/env python

so it will use the default "python" enviroment selected by the user

**Comment by d0ugal** [comment]
We use `#!/usr/bin/env python` everywhere ([for example](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/__init__.py#L1)). So, I don't know what is causing that path, but I don't think it is mkdocs.

**Comment by waylan** [comment]
As I understand it, when a package is built in certain situations the shebang lines can be changed to match the local system (I don't recall/it is not clear to me what triggers this). It is possible that when Homebrew built their package, something of the sort is happening. In order words, I would suggest reporting the problem to Homebrew. 

Personally, I **never** use system specific systems for installing Python packages. I always use a Python specific tool (like pip). But then, I also always install in virtual envs, so I don't have a choice. At least I never run into these types of problems.

**Comment by MiPnamic** [comment]
I also installed mkdocs via pip

**Comment by waylan** [comment]
Did you use pip or Homebrew? Or did you use both? You need to pick one system and stick with it. Perhaps you have multiple copies installed and that is part of the problem.

**Comment by MiPnamic** [comment]
Sorry @waylan, I use Homebrew for get linux software under mac os, so I installed almost everything (the latest versions) with it, also python.

So I installed MkDocs using pip but I got that pip through easy_install, through Python installed via Homebrew

**Comment by waylan** [comment]
Okay, then you did install MkDocs via pip (I don't care how Python or pip got installed, although the version may matter). Is pip the latest version? Have you tried uninstalling and reinstalling MkDocs?  Can you point us to a pip log of the MkDocs install? If you increase verbosity, it should tell you if pip is changing the shebang lines.

**Comment by MiPnamic** [comment]
Ok, I tried removing mkdocs and after the full clean install it works without troubles (and the shebang point to the correct brew version of Python)

I sincerely did not known that pip could change the shebang of a package.

**Comment by d0ugal** [comment]
I didn't know that either, good to know :)

**Comment by waylan** [comment]
It sounds like maybe you have multiple Python versions installed on your system. Of course, when a package in installed for a specific version, it needs to know which Python version to use. Therefore, the shebang line is changed to point to the proper Python (the same thing happens with virtual envs). It sounds like maybe you installed with with a different Python that the one you actually wanted to use. In any event, glad the problem has been resolved.
