### ISSUE TITLE
Add support for excluding pages from search indexing

### ISSUE THREAD

**Issue by btiernay** [mkdocs/mkdocs#773]
It would be really nice if there was a meta variable that could indicate search indexing in a markdown file:

```md
index: false

# My Content
```

Which would then exclude this content from being indexed. I think a simple approach would to be to check this variable before indexing at:

https://github.com/mkdocs/mkdocs/blob/3c6a66b38825dc409f1f8e000bd041f57ee225be/mkdocs/commands/build.py#L251

**Comment by d0ugal** [comment]
I can see this could be useful in some cases. However, I think it is quite a specific feature. I'd rather see something like this be added via a a plugin API when one is available. See #206.

**Comment by chrieke** [comment]
Developed a plugin for this: [mkdocs-exclude-search](https://github.com/chrieke/mkdocs-exclude-search)
