### ISSUE TITLE
navigation runs off the page

### ISSUE THREAD

**Issue by wtholliday** [mkdocs/mkdocs#776]
If you have enough headings, the left-hand navigation will go off the page. It seems that robust themes should not allow this.

<img width="1066" alt="nav" src="https://cloud.githubusercontent.com/assets/841144/11914643/caec5a6c-a63a-11e5-9f3d-bb50cbb7053c.png">

**Comment by d0ugal** [comment]
Agree'd, but this is a duplicate of https://github.com/mkdocs/mkdocs-bootswatch/issues/2 which as it happens originates from an issue that you opened https://github.com/mkdocs/mkdocs/issues/204.
