### ISSUE TITLE
Question about ReadTheDocs MkDocs Theme/Template

### ISSUE THREAD

**Issue by brianjking** [mkdocs/mkdocs#780]
<img width="781" alt="screenshot12-26-1510 54" src="https://cloud.githubusercontent.com/assets/6786817/12007201/a64c38d2-abbf-11e5-8a93-c72325a6ff37.png">

I've seen notification boxes used in the official ReadTheDocs Sphinx theme, however, is this supported in MkDocs port of this? If so, what is the syntax to make these?

Thanks, keep up the great work. It's highly appreciated!

**Comment by brianjking** [comment]
Based on looking at the docs/getting_started.rst file from https://github.com/rtfd/readthedocs.org/blob/master/docs/getting_started.rst the syntax they use is 

```.. note:: Markdown doesn't support a lot of the features of Sphinx,
          like inline markup and directives.
          However, it works for basic prose content.```

However, when I deploy this to MkDocs it doesn't get this style for it. Any help would be greatly appreciated.

**Comment by trel** [comment]
You're looking for the admonition extension.

You use it like this in your `mkdocs.yml` file:

```yaml
markdown_extensions:
 - admonition
```

This is also discussed in https://github.com/mkdocs/mkdocs/issues/426

**Comment by brianjking** [comment]
@trel ooh, nice. thanks.

What about strikethrough text support? I've always used ```~~text~~``` when using Daux.io, however, it doesn't seem to work on MkDocs.

**Comment by facelessuser** [comment]
Check out python markdown 3rd party extensions:  https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions.  They have some there that can do it; I know I have one listed they that can, but I think there are others as well.

**Comment by brianjking** [comment]
@facelessuser I checked out the wiki provided, didn't see any that support strikethrough text. :(

**Comment by facelessuser** [comment]
I believe one was del_ins.  The other is mine in the pymdown extensions: it's called tilde.

**Comment by brianjking** [comment]
@facelessuser Thanks. I ran ```pip install pymdown-extensions``` and in my mkdocs.yml file I added 

```
markdown_extensions:
    - toc:
        permalink: 
    - admonition:
    - tilde:
```

However, I'm getting this error when I try to deploy the docs.

```ImportError: Failed loading extension 'tilde' from 'tilde', 'markdown.extensions.tilde' or 'mdx_tilde'```

**Comment by facelessuser** [comment]
pymdownx.tilde I believe.

**Comment by facelessuser** [comment]
This page lists the inclusion names http://facelessuser.github.io/pymdown-extensions/.

**Comment by brianjking** [comment]
@facelessuser thanks, it works!
