### ISSUE TITLE
Doxygen

### ISSUE THREAD

**Issue by chraibi** [mkdocs/mkdocs#784]
I'm using `Doxygen` to document the internals and `mkdocs` to document the big picture. 
Actually, I'm just linking to the doxygen-index-file. Here an [example](http://jupedsim.github.io/jpscore/doxygen/).

Is there a way to have the [doxygen-index-file](http://jupedsim.github.io/jpscore/html/index.html) directly linked in the navigation bar, like *Home* or *Publications*?

**Comment by d0ugal** [comment]
No, at the moment we don't offer any integration with Doxygen. It might be that one day a plugin would make sense for this, but it isn't easily possible at the moment. See #206
