### ISSUE TITLE
Req: Update old Font Awesome in MkDocs' themes.

### ISSUE THREAD

**Issue by JayHoltslander** [mkdocs/mkdocs#789]
Font awesome 4.0.3 is included with mkdocs-bootstrap & the mkdocs-bootswatch themes.

It'd be nice to see it updated to the minified version of 4.5.0

**Comment by d0ugal** [comment]
Seems like a good idea.

**Comment by jkrenge** [comment]
As this is not yet available in version `0.14.0`, but if you need it right now (as I did), e.g. on Mac: `cd /Library/Python/2.7/site-packages/themes/`. There you can place the new files in `css` and `fonts`. You probably also need to modify `base.html`. Although I would say this is generally not recommended. :-)

**Comment by d0ugal** [comment]
> Although I would say this is generally not recommended. 

hah, absolutely not. I'd rather people installed the development version of MkDocs. http://www.mkdocs.org/about/contributing/#testing-the-development-version

Closing this as it should be released soon-ish. See #796
