### ISSUE TITLE
gh-pages branch issue

### ISSUE THREAD

**Issue by JayHoltslander** [mkdocs/mkdocs#790]
From [the documentation](http://www.mkdocs.org/user-guide/deploying-your-docs/) I read

>Warning. You should never edit files in your gh-pages branch by hand if you're using the gh-deploy command because you will lose your work.

But I needed to add a CNAME file to the branch in order to [use a custom domain name](https://help.github.com/articles/adding-a-cname-file-to-your-repository/). So I ignored this advice and added the CNAME file to the repo through GitHub's web interface.

Since manually adding that CNAME file though, the command ``mkdocs gh-deploy --clean`` seems to no longer be updating the gh-pages branch.

How can I fix this?

**Comment by d0ugal** [comment]
By including the CNAME in your docs directory :) See for example how MkDocs does it.

https://github.com/mkdocs/mkdocs/blob/master/docs/CNAME

**Comment by JayHoltslander** [comment]
Thank you. Wasn't clear on that. All fixed now.

**Comment by dvirsky** [comment]
@d0ugal this should be better documented. I couldn't find it in the docs, and found this simple solution only by searching the issues on the repos
