### ISSUE TITLE
Bootstrap tabs break when tab content contains blank line

### ISSUE THREAD

**Issue by mikemherron** [mkdocs/mkdocs#791]
When using bootstrap tabs with mkdocs, a blank line in a tab panel will cause the the markup of subsequent tabs (including the containing div) to be incorrectly placed in a &lt;pre&gt; block, preventing the tab from rendering correctly.

The attached mkdocs project provides an example of this, but to summarise here, the below "markdown":

```
<ul class="nav nav-tabs">
    <li class="active">
        <a href="#tab-bad-one" data-toggle="tab">Tab One</a>
    </li>
    <li>
        <a href="#tab-bad-two" data-toggle="tab">Tab Two</a>
    </li>
</ul>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="tab-bad-one">
        Tab One With a blank line
        
        in the middle. See how the content of "tab-bad-two" has been placed in a &lt;pre&gt; block below
    </div>
    <div role="tabpanel" class="tab-pane" id="tab-bad-two">
        <pre>Tab Two</pre>
    </div>
</div>
```

Generates the following HTML when passed through mkdocs:

```
<ul class="nav nav-tabs">
    <li class="active">
        <a href="#tab-bad-one" data-toggle="tab">Tab One</a>
    </li>
    <li>
        <a href="#tab-bad-two" data-toggle="tab">Tab Two</a>
    </li>
</ul>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="tab-bad-one">
        Tab One With a blank line

        in the middle. See how the content of "tab-bad-two" has been placed in a &lt;pre&gt; block below
    </div>

<pre><code>&lt;div role="tabpanel" class="tab-pane" id="tab-bad-two"&gt;
    &lt;pre&gt;Tab Two&lt;/pre&gt;
&lt;/div&gt;
</code></pre>
</div></div>
```

The attached file contains a runnable mkdocs project demonstrating the issue:

[tab-bug.zip](https://github.com/mkdocs/mkdocs/files/87110/tab-bug.zip)

**Comment by d0ugal** [comment]
Yikes, I guess this HTML is clashing with some of the processing we do. I don't have a good solution for this, but supporting advanced HTML in the Markdown like this is going to be tricky.

**Comment by d0ugal** [comment]
I can't even think which part of the code base would be doing this.

**Comment by waylan** [comment]
@mikemherron you just found a bug in the Markdown parser. I've created an [issue](/waylan/Python-Markdown/issues/452) for it there.

@d0ugal you can close this as it is not a MkDocs bug, but a Markdown bug.

As a side note, [many implementations][1] get this wrong. The rules specifically state that raw HTML must not be indented to be recognized as such. Although the reference implementation does the right thing with nested HTML, the rules are not clear on this. Therefore, for best results, it is always better to not indent raw HTML within Markdown documents. That said, this should still work and we will fix it. I'm just saying that, as a long-time Markdown user, this is an edge case I'm not surprised about.

Therefore, as a temporary fix, remove any indent in your raw HTML and you won't see this problem.

[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Cdiv%3E%0A++++%3Cdiv%3E%0A++++++++Div+with+a+blank+line%0A%0A++++++++in+the+middle.%0A++++%3C%2Fdiv%3E%0A++++%3Cdiv%3E%0A++++++++This+gets+treated+as+a+code+block%0A++++%3C%2Fdiv%3E%0A%3C%2Fdiv%3E

**Comment by mikemherron** [comment]
Thanks for the reply - my assumption was that it would not be an easy fix! But thought better raise the issue just in case.
