### ISSUE TITLE
Deploying

### ISSUE THREAD

**Issue by mjanv** [mkdocs/mkdocs#793]
I use _mkdocs_ to write rapidly user documentation for script tools in various languages. All the project is **perfectly** appropriate for what i do!

All the deploying options are great but I'm not using one of those, as I'm only building local versions of the documentation that I put in some `doc` or `docs` folder of my library/program/script/whatever. When I'm writing, I use `mkdocs serve` to see live changes and when I'm done `mkdocs build` and voilà.

But if the "server" is not up, and you just navigate through the static site when you click on a link in the sidebar (not one of the current anchors) like one of those:
``` html
<li class="toctree-l1 ">
        <a class="" href="foobar/">Some text!</a>
</li>
```
you just end up in the `foobar` folder which contains the `ìndex.html`, and the browser do not automatically open the index (like below)
![capture](https://cloud.githubusercontent.com/assets/5563461/12269599/8a17fb38-b952-11e5-871f-09cf46cf6064.PNG)

I'd like to be able to distribute a local version of the generated documentation (even without a search options) without any broken links. Will it be technically possible and in accordance with the roadmap ? 

I've read all the issues list and the group discussion and it didn't seem that this topic arose (My mistake if it actually did!). What do you think about this issue ? If it trigger any interest, I will be happy to work on it and try to provide a pull request.

Thanks.

**Comment by d0ugal** [comment]
You just need to add `use_directory_urls: false` to your mkdocs.yml.

http://www.mkdocs.org/user-guide/configuration/#use_directory_urls
