### ISSUE TITLE
Release 0.15.0

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#796]
I don't currently have time to work on the project (I am not even using MkDocs at the moment), however, I don't want to hold people back from getting a number of fixes in master. I would therefore like to try and see that the current master version works well. So I am looking for a few volunteers to help test and verify master and then I'll roll a release.

These are the outstanding tasks - I would need help with the first, and hopefully the second point if people have time.

- [x] Verify master
- [x] Resolve #764 and #693 
- [x] Update release notes
- [x] push release
- [x] update documentation on mkdocs.org

**Comment by MadsRC** [comment]
I'm currently using MkDocs for my new project, so I'll try to squeeze in some time for helping you out.

**Comment by d0ugal** [comment]
Thanks! If anyone else is interested but not sure how to do it, it's in the docs. http://www.mkdocs.org/about/contributing/#testing-the-development-version

**Comment by d0ugal** [comment]
There are also a few bugs that might be blocking a release. https://github.com/mkdocs/mkdocs/milestones/0.15.0

**Comment by laythun** [comment]
I am just about to start using mkdocs, once i get it working, i'll be available to contribute

**Comment by waylan** [comment]
> There are also a few bugs that might be blocking a release. https://github.com/mkdocs/mkdocs/milestones/0.15.0

Well, #653 can't be a release blocker as it is *not* a bug as I explain in its duplicate (#192).

And for #610, a much simpler fix would be to raise an error when people put their site_dir in their docs_dir. I don't care if it breaks peoples stuff. It makes no sense, they've been told not to do it and it should never have been allowed.

That would remove two of the five potential blockers.

**Comment by d0ugal** [comment]
> And for #610, a much simpler fix would be to raise an error when people put their site_dir in their docs_dir. I don't care if it breaks peoples stuff. It makes no sense, they've been told not to do it and it should never have been allowed.

Hah, I only care because tons of people pinged me about the error! However, given that we display a warning, maybe that is enough. If people are going to ignore warnings and complain at errors I can't please them :) I'll leave the issue for now, but it shouldn't block a release.

**Comment by d0ugal** [comment]
Okay, I've removed the unimportant issues. That leaves us with #764 and #693. I think these are both bugs that were introduced since `0.14.0`. So these need to be verified as issues and fixed.

I might have time this weekend to try and fix #764 (I presume I broke this with the theme changes in master). Then I'll try and remember what was happening in #693.

**Comment by d0ugal** [comment]
I believe #764 is now resolved.

**Comment by d0ugal** [comment]
Okay, I think we are now ready to roll a release. I have done some brief testing on the MkDocs and Drango REST Framework docs. I am going to see if I can setup Travis pushing to PyPI to make this easier in future. Otherwise I'll do it manually tomorrow morning.

**Comment by marcelstoer** [comment]
Was #752 / #269 dropped from this release? That'd be a sad for something that's been carrying the label 'Easy' for over a year now :disappointed:. I don't really understand based on the PR comments what's missing.

**Comment by waylan** [comment]
I think was is missing is @d0ugal's time to review the PR. I'm willing to take a look at at, but I won't have time for another 8 hours or so.

**Comment by d0ugal** [comment]
Yeah, essentially I've not looked at the most recent version - I forgot about it. I'll also try and take a look and wait a bit longer before doing the release - it would be a good addition.

**Comment by d0ugal** [comment]
Boom.

- http://www.mkdocs.org/about/release-notes/#major-additions-to-version-0150
- https://pypi.python.org/pypi/mkdocs/0.15.0

**Comment by d0ugal** [comment]
Thanks all for the help. I did leave #269 out for now, it has been around for a while but it was only recently active. I would happily consider releasing it in a 0.15.1 release if we can get it looking nice, I know that shouldn't really be for new features but I'm happy to make an exception here if people think it is okay. (Otherwise we could release a 0.16 really soon and small).
