### ISSUE TITLE
Linking external markdown files

### ISSUE THREAD

**Issue by seesharper** [mkdocs/mkdocs#797]
First of all, congrats on a really great project. Love it!!

I have this site that curls in markdown files from different locations.
Now I have to do this as a pre build step, but it would have been really nice if I could just do something like this:

```
site_name:SomeName

pages:
- Home: http://wherever.org/index.md
```  

Given that Mkdocs sees an external url it could curl in the file as a pre build step.
What do you think?

**Comment by d0ugal** [comment]
I think this would be a good idea for a MkDocs plugin once we have a #206 (but that wont be soon). I don't think it is something that belong in MkDocs core.
