### ISSUE TITLE
Req: Theme's source (Readthedocs)

### ISSUE THREAD

**Issue by JayHoltslander** [mkdocs/mkdocs#798]
Wondering if there are some source Sass files for the MkDocs version of the readthedocs theme somewhere?

I looked at <https://github.com/snide/sphinx_rtd_theme> but it seems to include and reference a lot of RTD specific files.

eg:
````
@import wyrm_core/wy_variables
@import wyrm_core/grid_settings
````

**Comment by waylan** [comment]
The [documentation][1] makes the following note:

> To benefit from all of the features offered by Read the Docs, you will need to use the Read the Docs theme which ships with MkDocs. The various themes which may be referenced in Read the Docs' documentation are Sphinx specific themes and will not work with MkDocs.

In fact, the RTD theme in MkDocs is a MkDocs specific theme which happens to (mostly--see #588) **look like** RTD' Sphinx theme. The entire theme is contained in the files at [`mkdocs/themes/readthedocs`][2]. There is nothing else (no Sass files, etc.) and I'm not aware of any plans to change that.

If you are looking for ways to override parts of a theme, that is a work-in-progress (see #607). Although, I don't believe CSS customization of the built-in themes has been discussed much, if at all. The expectation is that you would simply take advantage of the "cascading" feature of CSS and add your own CSS file (see the [`extra_css`][3] option) which would be loaded after the theme's CSS and override the theme as necessary. In fact, some might argue that tools like Sass are redundant as CSS already gives you everything you need (I'm not saying that is my argument; just pointing out that you can already override any part of the CSS without tools like Sass)

[1]: http://www.mkdocs.org/user-guide/deploying-your-docs/#read-the-docs
[2]: https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/readthedocs
[3]: http://www.mkdocs.org/user-guide/configuration/#extra_css

**Comment by JayHoltslander** [comment]
>The expectation is that you would simply take advantage of the "cascading" feature of CSS and add your own CSS file (see the extra_css option) which would be loaded after the theme's CSS and override the theme as necessary.

Was hoping to avoid that so as to:

1. to reduce the number of stylesheets requested.
2. make it easier to customize in seconds with variables for font-family and colors.

**Comment by d0ugal** [comment]
Yeah, so the problem with the readthedocs theme is that is was reverse engineered to make it work with MkDocs. To try and avoid problems we change it as little as possible, adding just a few fixes to make it work with our slightly different HTML.

I don't have a good suggestion for what you want to achieve, but it might be better to create a new theme which offers more customisation.

There is another issue that wants to tackle this general issue. So closing this in favour of #607
