### ISSUE TITLE
Not sure where to find this answer about TOC

### ISSUE THREAD

**Issue by Parth-Mehrotra** [mkdocs/mkdocs#805]
I don't want "sub-headings" to show up in my TOC

# This should show up
(some content)
## This should not show up
(some content
# This should also show up

I know an issue isn't  the right way to go about this, but where should I look? What are my options?

**Comment by d0ugal** [comment]
The only want to do this is to manually add the HTML for the headings you don't want to show up. So just put this in the markdown file:
<h3>this won't be in the TOF</h3>






On Sat, Jan 23, 2016 at 6:11 PM -0800, "Parth Mehrotra" <notifications@github.com> wrote:












I don't want "sub-headings" to show up in my TOC

This should show up



(some content)

This should not show up



(some content

This should also show up



I know an issue isn't  the right way to go about this, but where should I look? What are my options?

**Comment by Parth-Mehrotra** [comment]
I'm not sure I understand the syntax. you're saying I should put html in the md file?

**Comment by d0ugal** [comment]
Yup! That is the only current work around for what you want.
