### ISSUE TITLE
codehilite monokai highlight background color not changing

### ISSUE THREAD

**Issue by Dowwie** [mkdocs/mkdocs#809]
I'm trying to use a monokai themed codehilite using the setting below.
The monokai code block background color setting is generated in the index.html file yet the color doesn't apply in the browser.  It seems there is an overriding setting that conflicts?

markdown_extensions:
  - admonition
  - fenced_code
  - codehilite:
      noclasses: True
      pygments_style: monokai

**Comment by d0ugal** [comment]
This isn't really supported in any of the supplied themes, you would need to build a custom one I think or adapt and existing theme.
