### ISSUE TITLE
Authentication?

### ISSUE THREAD

**Issue by MartinAyla** [mkdocs/mkdocs#81]
Is it possible to protect (username/password) the hosted mkdocs site?

Or has it been considered as a future addition?

**Comment by artemv** [comment]
Just in case, I recently made an opensource Rails app wrapping a MkDocs site and providing users authentication. You can easily deploy e.g. to Heroku. https://www.npmjs.com/package/authenticated-docs

**Comment by farnetani** [comment]
Using django and material theme:

[https://github.com/farnetani/django_material_mkdocs](https://github.com/farnetani/django_material_mkdocs)

**Comment by sunweihunu** [comment]
Please add the login or authentication function if possible.

**Comment by pawamoy** [comment]
Hi @sunweihunu, please don't comment on old, closed issues, and instead open new Q&A discussions or issues if you have questions or requests :slightly_smiling_face:
