### ISSUE TITLE
Mkdocs Subpages

### ISSUE THREAD

**Issue by eric-mathu** [mkdocs/mkdocs#810]
Hi, my subpages are displaying the "404 not found" , what could be the problem?
what should be their directory?? (other pages are good).

**Comment by d0ugal** [comment]
You are going to have to give us more information. Can we see the project? Or your mkdocs.yml? What structure do you have your pages in now?

Have you compared with the MkDocs documentation, it is a good example.

**Comment by eric-mathu** [comment]
site_name: JAMBO PAY
pages:
- Home: index.md
- Nairobi City County(NCC) Payment Streams: Nairobi City County(NCC) Payment Streams.md
- NAIROBI WATER: NAIROBI WATER.md
- STARTIMES: STARTIMES.md
- NHIF: 
  - Eric: NHIF/Eric.md
  - Eliud: NHIF/Eliud.md

theme: readthedocs
That's the structure, i am just testing but the sub pages i.e eric & eliud are giving back the 404 error.

**Comment by d0ugal** [comment]
Hmm, I am not sure. Normally you would only have problems if you get a path incorrect. I would try deleting the pages config from your mkdocs.yml and let MkDocs discover the files on it's own.

**Comment by eric-mathu** [comment]
Are all the md files (including the sub pages md files) supposed to be together in the docs folder?

**Comment by d0ugal** [comment]
They can be nested within other folders in the docs folder. For example: https://github.com/mkdocs/mkdocs/tree/master/docs

**Comment by eric-mathu** [comment]
Its working, Thank you.

**Comment by eric-mathu** [comment]
Hi, how do i get to arrange my pages in the order i want other than the default (alphabetical) in mkdocs?

**Comment by d0ugal** [comment]
https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml

**Comment by eric-mathu** [comment]
Good progress so far, how about adding tables?
