### ISSUE TITLE
How to support markdown pages outside of mkdocs.yml

### ISSUE THREAD

**Issue by slackmoehrle** [mkdocs/mkdocs#813]
I have markdown files that I would like included in on the build process (i.e made to html) but that I don't want as part of mkdocs.yml. (so they don't show up in any menus)

Say I have this:
```
  - 'Editors & Tools':
      - 'Studio': 'editors_and_tools/studio.md'
```

but in `studio.md` I might have other files I need:
```

### [Workspace Overview](Workspace_Overview/en.md)
```

I get a warning:
``` 
WARNING -  The page "editors_and_tools/studio.md" contained a hyperlink to "editors_and_tools/Workspace_Overview/en.md" which is not listed in the "pages" configuration.
```

but I really would like this page built as part of the process.

**Comment by slackmoehrle** [comment]
oops, I see there is a discussion group. I missed that. Closing issue and moving to the group.

**Comment by waylan** [comment]
@slackmoehrle this is not officially supported at this time. See #699 for details and a possible workaround.

**Comment by slackmoehrle** [comment]
@waylan perfect. Thank you.
