### ISSUE TITLE
Collecting a list of MkDocs themes

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#818]
With 0.15 out the door, I am starting to hear about new themes - much faster than I expected. I know of three already.

- [Cinder](https://github.com/chrissimpkins/cinder)
- [Alabaster](https://github.com/iamale/mkdocs-alabaster)
- [Materializr](https://github.com/squidfunk/materializr) (not on PyPI yet)

To aid discovery and help promote the great work done by the community I would like to create a gallery for themes. Where should we do it?

- In the MkDocs documentation? We would have the issue of keeping this relevant and up to date
- In the MkDocs wiki? https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes - this is already stale since I first started it and I bet it is usually missed.

**Comment by waylan** [comment]
The model that works for Python-Markdown extensions is to use the community editable (GitHub) wiki (that way I don't need to do anything). The trick is to link to that wiki page from the documentation (both in the instructions for theme developers and users). That way, everyone just follows the link to the "list of third party themes." Make is clear both in the documentation and on the wiki page that it is editable by anyone with a github account and encourage theme devs to add their own to the list.

**Comment by d0ugal** [comment]
Good idea. Let's do that.

**Comment by d0ugal** [comment]
Okay, cool - I think this is now handled! It would be good to make the wiki a bit nicer and include a screenshot for each theme. It should be possible for anyone to do that, but I'll leave this open to remind me to get to it at some point if nothing else.

**Comment by d0ugal** [comment]
The major downside of the wiki is that we can't upload images directly to it. They need to be hosted somewhere and then referenced. I can't think of a nice way to do this - it's making me slightly favour having a dedicated third party themes page in the docs.

**Comment by waylan** [comment]
The wiki is just a git repo. Are you sure its not possible to include images? I agree that committing them locally and pushing it less than ideal, but if it works...

Or why can't the images be hosted in the theme's repo and/or documentation and just linked from the wiki?

**Comment by d0ugal** [comment]
Okay, I managed to add images. That was hard work. It looks a bit better now, but I am not a huge fan still.

Having themes host their images would work - it's just another barrier to entry.

**Comment by d0ugal** [comment]
I do quite like all the screenshots showing the same documentation - it makes the difference in the themes more obvious.

**Comment by d0ugal** [comment]
I'll close this issue, the wiki page is good enough for now. We can see how it evolves over time.
