### ISSUE TITLE
Markdown problem

### ISSUE THREAD

**Issue by coffeetalkh** [mkdocs/mkdocs#825]
MKDocs doesn't build markup very well, It lacks on - and can't convert them to ul. It doesn't support == for highlighting and some more, is it possible to use other open source markup parser for this part?

**Comment by d0ugal** [comment]
Can you provide us with a specific problem? An example that doesn't work? All the features you mention are used on mkdocs.org (The MkDocs documentation, build with MkDocs).

MkDocs uses python-markdown for Markdown parsing, a very competent Markdown parser.

**Comment by coffeetalkh** [comment]
Thank you dear dougal, I listed some issues here:
 
- Emoji support 
- Table, These type of tables doesn't [supported](https://github.com/mozilla/kuma/blob/master/README.rst) 
- [Tasklist](https://guides.github.com/features/mastering-markdown/)
- Strikethrough ~~doesn't supported~~
- Nested lists doesn't works

**Comment by facelessuser** [comment]
> Thank you dear @d0ugal , I listed some issues here:

> - Emoji support
> - Table, These type of tables doesn't supported
> - Tasklist
> - Strikethrough doesn't supported
> - Nested lists doesn't works

MkDocs itself does not provide Markdown parsing; this is done via the 3rd party Python module Python Markdown.

None of your listed features are part of the Markdown spec as documented by its creator: https://daringfireball.net/projects/markdown/syntax.  Even amongst various Markdown parsers, all of your desired features are not supported as people reimagine an ideal Markdown in their various flavors in various ways.

As stated earlier, MkDocs uses Python Markdown which has an extension framework where you can add all the non-standard/reimagined Markdown features you want.  There are also numerous extensions that already exist that may provide some, if not all, of your desired features: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions.  I would take a look there.

**Comment by d0ugal** [comment]
Thanks @facelessuser. I think that answers everything, but let us know if there is a follow up question.

**Comment by waylan** [comment]
> * Nested lists doesn't works

Actually they work fine, if you use four spaces (or one tab) of indentation for each level of nesting as required by the [rules][1]. This is documented in Python-Markdown's [docs][2].

Thanks @facelessuser for covering all of the other points quite well.

[1]: http://daringfireball.net/projects/markdown/syntax#list
[2]: https://pythonhosted.org/Markdown/index.html#differences

**Comment by coffeetalkh** [comment]
thanks @d0ugal and @facelessuser for your Great advises.
