### ISSUE TITLE
`mkdocs --version` not working

### ISSUE THREAD

**Issue by SimonDanisch** [mkdocs/mkdocs#828]
I seem to have a weird version of mkdocs on Ubuntu 15.10:
```
>mkdocs --version
mkdocs [help|new|build|serve|gh-deploy|json] {options}
```

```
>sudo pip install mkdocs
Downloading/unpacking mkdocs
  Downloading mkdocs-0.15.2-py2.py3-none-any.whl (966kB): 966kB downloaded
Requirement already satisfied (use --upgrade to upgrade): Markdown>=2.3.1 in /home/s/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): livereload>=2.3.2 in /home/s/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /home/s/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.1 in /home/s/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.7.1 in /home/s/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): click>=3.3 in /home/s/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): mkdocs-bootswatch>=0.1.0 in /home/s/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): mkdocs-bootstrap>=0.1.1 in /home/s/.local/lib/python2.7/site-packages (from mkdocs)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /home/s/.local/lib/python2.7/site-packages (from tornado>=4.1->mkdocs)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /home/s/.local/lib/python2.7/site-packages (from tornado>=4.1->mkdocs)
Requirement already satisfied (use --upgrade to upgrade): certifi in /home/s/.local/lib/python2.7/site-packages (from tornado>=4.1->mkdocs)
Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in /home/s/.local/lib/python2.7/site-packages (from tornado>=4.1->mkdocs)
Installing collected packages: mkdocs
Successfully installed mkdocs
Cleaning up...
```

```
>mkdocs --version
mkdocs [help|new|build|serve|gh-deploy|json] {options}

>python --version
Python 2.7.10

>pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)

>pip freeze | grep mkdocs
mkdocs==0.15.2
mkdocs-bootstrap==0.1.1
mkdocs-bootswatch==0.2.0

>which mkdocs
/usr/local/bin/mkdocs
>which pip
/usr/bin/pip

>/usr/local/bin/pip freeze | grep mkdocs
bash: /usr/local/bin/pip: No such file or directory
```

`mkdocs serve` works fine, but the generated website looks a bit different then the one from my windows computer (where `mkdocs` just works fine). E.g. the search is missing and the same configuration file doesn't work (it doesn't seem to handle pages in the same way as on windows).

**Comment by d0ugal** [comment]
I spoke briefly with @SimonDanisch on IRC about this. I think for some reason two versions of MkDocs are installed (probably with multiple python and pip installs). The message shown with `mkdocs --version` dates one install as [version 0.11.](https://github.com/mkdocs/mkdocs/blob/0.11.1/mkdocs/main.py#L47) (0.12 was similar, but included [the version](https://github.com/mkdocs/mkdocs/blob/0.12.0/mkdocs/main.py#L63).) Then pip shows the other to be 0.15.2, the current release.

I am fairly sure this is an environment issue and not a MkDocs issue. However, I said to open this issue as I wasn't sure how best to resolve it and I didn't have more time to investigate.

**Comment by d0ugal** [comment]
Looking again at the output above, it seems that the new MkDocs is installed in `/home/s/.local/lib/python2.7/site-packages` - that looks like a virtualenv? You can probably run that with `~/.local/bin/mkdocs`

@SimonDanisch Did you install MkDocs via apt-get previously?

**Comment by SimonDanisch** [comment]
Hah! I just realized this as well... The pip build was broken because of missing dependencies so I installed it via apt-get at some point... But then I got the pip install running so I thought it would take over... Sorry for the noise, I debugged this over multiple days, so I forgot to mention the important details :(

**Comment by d0ugal** [comment]
No problem :smile:! It is a shame the deb doesn't seem to be maintained (I'd rather it didn't exist than be old) - the rpm is updated quite frequently.

**Comment by ventolinmono** [comment]
I installed and uninstalled Mkdocs via apt-get. Because of issues with themes I tried to do it with pip but get bash: /usr/bin/mkdocs: No such file or directory. How can i fix this?

**Comment by ventolinmono** [comment]
Fixed this adding Python site-packages to the bash profile.
