### ISSUE TITLE
clang error during install on Mac OSX Mavericks using '-mno-fused-madd' argument

### ISSUE THREAD

**Issue by newoga** [mkdocs/mkdocs#83]
I tried installing mkdocs on mavericks and got the following error:
```
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -DWATCHDOG_VERSION_STRING="0.7.0" -DWATCHDOG_VERSION_MAJOR=0 -DWATCHDOG_VERSION_MINOR=7 -DWATCHDOG_VERSION_BUILD=0 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/watchdog_fsevents.c -o build/temp.macosx-10.9-intel-2.7/src/watchdog_fsevents.o -std=c99 -pedantic -Wall -Wextra -fPIC

clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]

clang: note: this will be a hard error (cannot be downgraded to a warning) in the future

error: command 'cc' failed with exit status 1
```

I found this [blog post](https://langui.sh/2014/03/10/wunused-command-line-argument-hard-error-in-future-is-a-harsh-mistress/) that said that unknown compiler flags now hard fail instead of warn in newer versions of clang. In this case, the `-mno-fused-madd` flag is causing the issue. I'm running this on Mavericks with version `Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)` of clang.

I was able to get around this by running the following command to install instead: 
`sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install mkdocs`, but wanted to create an issue and let you know.

Thanks!

**Comment by d0ugal** [comment]
Closing in favour of #445 which summarises this and has an actionable result. The specific error here is something to do with upstream dependencies.
