### ISSUE TITLE
Markdown tables expand beyond window with no scrollbar

### ISSUE THREAD

**Issue by sahilTakiar** [mkdocs/mkdocs#834]
I created the following test table in a `.md` file:

```
|Test1|Test2|
|-------------|-------------|
|Hello|`really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really long code`|
```

And when loaded via a ReadTheDocs theme the resulting table looks like this:

<img width="1082" alt="screen shot 2016-02-21 at 6 39 10 pm" src="https://cloud.githubusercontent.com/assets/1282583/13208095/82115622-d8ca-11e5-9d48-71e284a7fbd6.png">

The contents of a row that expand beyond the current window are not viewable. There is also no way to scroll horizontally on the table to view the contents at the end of the row. I am assuming this is happening because the text with the `<code>` tag is not splittable.

* My `mkdocs.yml` file contains:

```
theme: readthedocs

pages:
    - Home: index.md

markdown_extensions:
  - toc:
      permalink: True
  - tables
```

* Viewing the docs using Chrome. 

Any ideas how to get around this?

**Comment by d0ugal** [comment]
You could add some custom CSS, I'm not sure what off the top of my head, but otherwise I am no aware of a workaround.

**Comment by waylan** [comment]
This is a common problem with any code block on any web site. Unless you account for it in your CSS, code blocks with long lines will run off the right of the screen. The typical solution is to define a rule that a scroll bar is used if the width of the block exceeds some value, but not if it is less. Just like GitHub has in the first comment here. 

However, the weird thing here is that this is inline code, which would normally wrap like this: `really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really long code`.  I expect the difference is that it is in a table cell. Not sure what needs to happen.

**Comment by sahilTakiar** [comment]
Thanks for the comments. I'll try to see if some custom CSS will fix this. Ideally, an horizontal scroll bar would be automatically created so that the code is viewable. Basically, replicating what GitHub does for rendering long code in a table (see https://github.com/linkedin/gobblin/wiki/Gobblin-on-Yarn#configuration)

**Comment by waylan** [comment]
@sahilTakiar  do the changes in #1027 resolve this for you?
