### ISSUE TITLE
Document the CLI and it's options

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#837]
I'm not sure this is totally required, since the CLI has good help - but it would be good to have something to reference from other areas of the documentation and when helping people.

**Comment by waylan** [comment]
Can Click generate the help as HTML?

In my experience, over time, the autogenerated `--help` and the manually edited documentation drift apart. So any replication in the documentation should be autogenerated as well.

**Comment by d0ugal** [comment]
If Click can do this, it is a feature I can't find. I agree that this would be ideally automated.

**Comment by waylan** [comment]
Based on my research (as outlined in #687) it is not supported out-of-the-box, but it should be possible. Probably the same solution I recommended in the second half of [this comment](https://github.com/mkdocs/mkdocs/pull/687#issuecomment-125688585).

**Comment by d0ugal** [comment]
That looks like a good start. I don't think this is a particularly high priority issue, but it would be nice to do at some point. We should generate the manpage at the same time I think, covering the goals from #686  too.

**Comment by waylan** [comment]
Thinking about his a little more, it is not clear to me how the autogeneration here would be triggered. In the case of the manpage (#687) that would only need to happen on each release (as it would only be distributed with the release) so it could be triggered via the `setup.py` script.  However, in this case, the autogenerated document would be a page in the MkDocs site. There is currently no mechanism to do that from within MkDocs. Sure, an external command could build a page in the `docs` dir, but how do we ensure that script gets called every time `mkdocs build` is called? This may need to wait for a Plugin API (#206).

**Comment by waylan** [comment]
I just found [sphinx-click], which "is a Sphinx plugin that allows you to automatically extract documentation from a click-based application and include it in your docs." We could probably get some inspiration for MkDocs from this.

[sphinx-click]: https://github.com/click-contrib/sphinx-click
