### ISSUE TITLE
Help with using Travis-CI/Codeship for deploying MkDocs

### ISSUE THREAD

**Issue by brianjking** [mkdocs/mkdocs#840]
Hi,

I currently have some MkDocs instances associated with Github repos and two others with Bitbucket repositories. I'm looking for some guidance as to how I can properly setup Travis-CI (for Github) and Codeship for the Bitbucket repos.

Currently my workflow looks like this:

- Edit docs
- Commit
- Push
- Travis-CI or Codeship informs me of any issues executing `mkdocs build`
- If no issues are found I execute `mkdocs build` locally and commit those changes and push them to their respective remotes
- I use `Deploybot` [http://deploybot.com](http://deploybot.com) to upload these files to their respective domains.

I know it's very primitive, however, I just was getting started with using CI services and want to take this to a more logical and properly setup approach. Any tips or example configurations would be greatly appreciated.

I'd like to have it work something like this:

- Edit docs
- Commit
- Push
- Travis-CI/Codeship tests for `mkdocs build` and if it works it deploys to the respective FTP sites. If there are errors it doesn't deploy the updates and informs me of the errors.

Thanks again!

**Comment by d0ugal** [comment]
You are in luck. I have been recently investigating this. See #814 (and #632) for some related issues, but they don't have many details yet.

There is a [blog post](https://mwop.net/blog/2016-01-29-automating-gh-pages.html) that goes into lots of detail, but also contains some very specific things so it might not all be useful.

I recently added [automatic building](
https://github.com/mkdocs/mkdocs-bootswatch/blob/master/.travis.yml#L29-L35) (with Travis) to one of the themes we have. To add the secret you need to run `travis encrypt --add GH_TOKEN=TOKEN_FROM_GITHUB_SETTINGS"`. It works well, but it only updates the docs when we do a release to PyPI if you change the `after_deploy` to `after_success` it will do the update on each commit.

I can't help you with Codeship, or any other CI really. I am only familiar with Travis. However, they should all be fairly similar I guess.

Originally in #632 I thought we could make it a bit easier in MkDocs to do this. However, after doing it in the `mkdocs-bootswatch` project I am not sure we can easily make it better. The tricky bit is just setting up the git repo and doing things specific to different CI systems - that feels a bit out of scope for MkDocs.

**Comment by brianjking** [comment]
@d0ugal 

All my docs deploy onto private servers with FTP. It looks like using `after_success` may be the solution, thoughts?

https://docs.travis-ci.com/user/deployment/custom/

**Comment by d0ugal** [comment]
Yup, looks like that would work well.

**Comment by brianjking** [comment]
@d0ugal https://github.com/conda/conda-docs/blob/master/update-gh-pages.sh

This is built with Sphinx, but this is looking promising.

**Comment by d0ugal** [comment]
Ugh, that looks horrifically more complicated. What's wrong with the approach I used?

**Comment by waylan** [comment]
Actually, if MkDocs wasn't using the `ghp_import.py` script, we would need that complicated of a solution as well. Most of the complexity is left to that third-party lib though. I've gotten the impression that perhaps @brianjking is trying to come up with a solution that does not use the provided `gh-deploy` command (which wraps `ghp_import.py`) and that is why he's having difficulty coming up with  simple solution.

@brianjking if you explained why the `gh-deploy` command doesn't work for you, perhaps we could be of more assistance.

**Comment by brianjking** [comment]
@waylan Two reasons why the `gh-deploy` isn't feasible for me (in most cases thus far):

1. One of the repos is a private repository hosted on Bitbucket. The `MkDocs` site is behind password authentication, which is why it's uploaded to a private FTP server instead of a publicly accessible service like `gh-pages`.

2. For the repositories not stored on Github and instead on Bitbucket, I don't have Github pages as an option.

There are a bunch of other Sphinx repositories I've found that use the output of Travis-CI to upload the html files to either Github pages or an FTP site, however, I haven't found anything specific to MkDocs.

**Comment by waylan** [comment]
@brianjking thanks for clearing that up. It is clear that `gh-deploy` won't work for you. However, I would expect that many of the Sphinx related scripts would work. Just replace the one line that builds Sphinx with the command to build MkDocs, make a couple adjustments for different naming conventions (name of build/site dir, etc.) and you should be good to go. Not sure what else we can do to help.

**Comment by brianjking** [comment]
@waylan @d0ugal -- I just started working on a set of docs that can be hosted on Github pages and tried out the Travis-CI Approach you referenced here: https://mwop.net/blog/2016-01-29-automating-gh-pages.html

However, whenever Travis-CI pushes to the `gh-pages` branch it deletes the `CNAME` file from this branch. Any tips, I'm feeling a bit lost... :confused: 

Thanks!

https://github.com/zendframework/zf-mkdoc-theme/issues/5

https://github.com/brianjking/hudsonvalleyhelp/blob/master/.travis.yml#L15 --> I removed the --clean argument.

**Comment by waylan** [comment]
You need to have the `CNAME` file in your `docs` dir so that MkDocs includes it in the `site` dir. As the [docs][1] warn, when you run `gh-deploy` it completely nukes what you already have in the `gh-pages` branch. So if you manually added the `CNAME` file, it will be lost every time. All edits must be on the MkDocs side only. Note that removing the `--clean` argument does not change this behavior. The `--clean` flag only affects what happens in the `site` dir. After the site is built in the `site` dir, then gh-deploy takes over and copies that to the `gh-pages` branch. Whatever is in the `site` dir becomes the new content of the gh-pages` branch. Therefore, I would recommend always using `--clean` when running `gh-deploy` to avoid any unclean builds.

[1]: http://www.mkdocs.org/user-guide/deploying-your-docs/

**Comment by d0ugal** [comment]
> However, whenever Travis-CI pushes to the gh-pages branch it deletes the CNAME file from this branch.

For MkDocs we include the CNAME file in the docs directory. Then it is copied over with all the other static assets. https://github.com/mkdocs/mkdocs/blob/master/docs/CNAME

**Comment by waylan** [comment]
Thinking about my latest response a little and it occurs to me that perhaps we should change something here. Why do we have a `--clean` flag on the `gh-deploy` command? Should that perhaps be the default as the underlying `ghp-import` script [nukes][1] the entire contents of the `gh-pages` branch. It hadn't occurred to me before, but reading @brianjking's last comment, I realized that users could assume that not using the `--clean` flag would alter that behavior. Of course, as the underlying `ghp-import` script has no such option, it does not. 

Or at the very least, perhaps the help message associated with the `--clean` flag should be more specific.

[1]: https://github.com/davisp/ghp-import#big-fat-warning

**Comment by brianjking** [comment]
@waylan @d0ugal Thanks, placing the CNAME in the docs folder in my master branch works! :+1:

**Comment by brianjking** [comment]
Actually, I was wrong... :-1: I guess placing CNAME in the docs folder didn't work. Any other tips?

**Comment by waylan** [comment]
It works for MkDocs own documentation. Not sure why it wouldn't for anyone else. Can you provide us with more info to help you debug it?
