### ISSUE TITLE
Hover state for headers' permalinks is weird

### ISSUE THREAD

**Issue by jimporter** [mkdocs/mkdocs#843]
Try going to http://www.mkdocs.org/ and put your mouse to the right of "Host anywhere". You'd expect to see the permalink for that heading, but instead, the permalink for "Great themes available" shows up. This can be pretty annoying, since it makes it harder to click on the permalink; if you go a pixel too far to the right, you have to move your mouse back over the text itself, and then back again to the permalink.

As far as I can tell, this is because of the following code: <https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/css/base.css#L43-L49>. I gather that it's there to work around the existence of the header so that anchor links go to the right spot. I'd argue that the old Javascript way was better, unless someone can figure out a way to trick CSS into handling the hover state better.

**Comment by waylan** [comment]
I'm not seeing this behavior in Chrome on Linux. Everything looks fine to me. What browser are you using?

**Comment by jimporter** [comment]
I tried Firefox (nightly and release), Chromium, and IE. You might need to maximize the browser window to ensure that the text under "Host anywhere" is all on one line. Here's a screenshot from Chromium:

![untitled](https://cloud.githubusercontent.com/assets/826865/13341512/11db9a9c-dbff-11e5-92fd-6c220312f50c.png)

**Comment by waylan** [comment]
I see the incorrect behavior you are describing in your screenshot, but am not able to reproduce it locally.

**Comment by d0ugal** [comment]
Yeah, confirmed on Chrome 48 (on Fedora). I can see this bug. Just move your mouse around a bit and it'll sometimes show the header link when you are not over any header at all (and usually it then shows the header below where you are).

**Comment by jimporter** [comment]
Right. If you inspect the element, you can see why:

![untitled-1](https://cloud.githubusercontent.com/assets/826865/13346824/c4345c18-dc2e-11e5-9636-20bbec5aca00.png)

It's actually much larger than just the line of text, since the `::before` pseudo-element adds to the size in order to make the element's top be closer to the beginning of the page. That helps ensure that navigating to the anchor for that element doesn't hide the heading behind the navbar at the top. I'm not sure there's a CSS-only way to do this without causing this issue. You'd either need to use Javascript or modify the HTML.

**Comment by d0ugal** [comment]
Cool, yeah, I spotted that too. I think I've fixed it in #844.

**Comment by d0ugal** [comment]
Meanwhile, if you use [extra_css](http://www.mkdocs.org/user-guide/configuration/#extra_css) and add the following, it should fix it for you (and let you confirm my fix which would be super helpful! :star2:).

```css
h1[id]:before, h2[id]:before, h3[id]:before, h4[id]:before, h5[id]:before, h6[id]:before {
    content: "";
    display: block;
    pointer-events: none;
}
```

**Comment by jimporter** [comment]
Unfortunately, I think that patch will cause the header itself to be hidden by the navbar at the top (which is why that padding/negative-margin trick was there in the first place). I delved into the history, and it used to have a JS implementation: <https://github.com/mkdocs/mkdocs/pull/407>.

**Comment by d0ugal** [comment]
aha, that's what that height hack was for! We should really use comments.

**Comment by jimporter** [comment]
Yeah, any time there's a negative margin in CSS, there should probably be a comment. :)

**Comment by d0ugal** [comment]
Well, that's a shame I was feeling clever for a moment. I'll finish my coffee and think about it for a bit.

**Comment by jimporter** [comment]
A partial fix would be to change the CSS to:

```css
:target::before {
    content: "";
    display: block;
    margin-top: -75px;
    height: 75px;
    pointer-events: none;
}
```

The above will ensure that all the headers, *except the one referred to in the URL's hash,* will work fine. You could probably be really tricky and turn the selector into something like `body:not(.scrolled) :target::before`, and then have JS set `.scrolled` on the body in an onscroll event handler. That's kind of weird, but arguably less weird than the original JS code.

The *real* solution is for CSS to have some sort of `anchor-offset` attribute. :)

**Comment by d0ugal** [comment]
Oh, that is neat. I didn't know you could do `:target::before` - that is an improvement at least until somebody has time to figure out a better fix.

**Comment by jimporter** [comment]
Ok, I think I have a patch for this. It's fairly bizarre, so I need to clean it up and add some comments. Then I'll file a PR.

**Comment by jimporter** [comment]
@d0ugal Ok, the PR is up. I added a comment that hopefully explains all the weird magic I performed. I can also add vendor-specific CSS prefixes as appropriate if you think they're necessary. Here's a compatibility chart: https://developer.mozilla.org/en-US/docs/Web/CSS/animation#Browser_compatibility

**Comment by ppKrauss** [comment]
Navbar is not a custom feature?  How to maintain a custom CSS-code (ex. change navbar backgroundcolor) in a ugly and mixed-bootstrap CSS code?
