### ISSUE TITLE
MkDocs on ReadTheDocs Search Broken Links

### ISSUE THREAD

**Issue by sahilTakiar** [mkdocs/mkdocs#848]
When performing a trivial search on: https://mkdocs.readthedocs.org/en/stable/

I get re-directed to here: https://readthedocs.org//search/?q=mkdocs&check_keywords=yes&area=default&project=mkdocs&version=stable&type=file

It lists out a few search results but most are broken: http://mikasa-demo.readthedocs.org/en/stable/user-guide/styling-your-docs/?highlight=mkdocs

Based on https://github.com/mkdocs/mkdocs/pull/222 it should look something more like [this](https://camo.githubusercontent.com/c6cb60082d1407d22171c928f9380cd9e26acac2/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f31343235353231372f53637265656e73686f74732f53637265656e73686f74253230323031342d31312d32312d31382e34392e35302e4e6176696761746f722e706e67).

Any idea what is going on? Is this a problem with ReadTheDocs? Should I open an issue there instead?

**Comment by d0ugal** [comment]
Yup, this is a problem with ReadTheDocs. They do some custom search stuff and already have a number of related issues. https://github.com/rtfd/readthedocs.org/issues/1487 and https://github.com/rtfd/readthedocs.org/issues/1633 look like good places to start.
