### ISSUE TITLE
Remove Download from ReadTheDocs Footer

### ISSUE THREAD

**Issue by sahilTakiar** [mkdocs/mkdocs#849]
On the MkDocs ReadTheDocs page: https://mkdocs.readthedocs.org/en/stable/

The footer generated by ReadTheDocs does not contain a "Downloads" section. I believe this is because there is no MkDocs support for PDF, HTML, ePub generation.

How can I get the "Downloads" section removed from my own project? http://gobblin.readthedocs.org/en/readthedocs/

Ideally it would be removed from all ReadTheDocs themed sites since it doesn't work and can confuse users.

Related Issue on the ReadTheDocs GitHub: https://github.com/rtfd/readthedocs.org/issues/2024

**Comment by d0ugal** [comment]
That whole popup section on the bottom left is injected by ReadTheDocs. There is no way with MkDocs to remove that (other than adding custom CSS or JS to remove it again... but that would be somewhat hacky!)

**Comment by waylan** [comment]
A quick search turned up an [option][1] which enables you to list which formats you want ReadTheDocs to provide. However, it is unclear to me if it will even work as the entire YAML config file for RTD appears to be in beta.

[1]: http://read-the-docs.readthedocs.org/en/latest/yaml-config.html?highlight=pdf#formats

**Comment by d0ugal** [comment]
This is where the contents for that popup section comes from: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/restapi/templates/restapi/footer.html

**Comment by sahilTakiar** [comment]
Thanks for the pointers.The `readthedocs.yml` file didn't seem to work. The Admin page on the ReadTheDocs page allows disabling ePub and PDF generation, but not HTML generation. I noticed that the MkDocs ReadTheDocs link doesn't have the "Download" section at all, is there anything specific that was done to get rid of it?
