### ISSUE TITLE
Search index missing on mkdocs serve

### ISSUE THREAD

**Issue by kylegregory** [mkdocs/mkdocs#865]
When using the built in server for testing, the `search_index.json` file is not included in the site files, therefore the search functionality cannot be tested/used. This may be intentional.

**Comment by waylan** [comment]
Which version of MkDocs are you using? Try running `mkdocs --version` to find out.

**Comment by kylegregory** [comment]
Hey @waylan,

``mkdocs, version 0.15.3``

**Comment by waylan** [comment]
Hmm, that is the lasted version so it is not an old bug. There is nothing special about the build process when using `mkdocs serve` so the file should be there. Is the project publicly available to we can test it? Or at least could you provide your `config.yml` file?

**Comment by kylegregory** [comment]
Here's the contents of my `mkdocs.yml` file. Changed the product names to Foo.

```
site_name: Foo Documentation
pages:
- 'Get Started': index.md
- Pages: content/pages.md
- Content: content/content.md   
theme: readthedocs
markdown_extensions:
    - admonition
site_url: http://docs.foo.com
repo_url: https://github.com/foo/docs/
site_author: Foo Bar Software
site_description: 'Documentation for the Foo Content Management System (CMS)'
copyright: '&copy; Foo Bar Software. All Rights Reserved.'
site_favicon: favicon.ico
```

**Comment by waylan** [comment]
Hmm, I don't see anything that jumps out at me. We'll have to take a closer look.

**Comment by kylegregory** [comment]
I think I figured it out. There must have been some sort of build error which wasn't preventing the site from loading and being served, but was stopping at a point where the `search_index.json` file was not included in the output. I've run a few more tests, and it's clearly working now.
