### ISSUE TITLE
word separators in searching

### ISSUE THREAD

**Issue by randy3k** [mkdocs/mkdocs#867]
Suppose in the markdown file, I have a "word": "Foo.bar", the current search function is not able to pick "Foo.bar" if I search for "bar". May be some settings in lunr.js will do the job?

**Comment by waylan** [comment]
It appears that you would need to override [`lunr.tokenizer.seperator`][1]. As the code currently stands this change would be made in [search.js][2] which you could override using [`theme_dir`][4] (place a modified copy of `search.js` in the appropriate subdir). However, if [this proposed fix][3] to #869 is accepted, then index creation will be hardcoded into the Python source and no longer overridable by theme customization.

As I've been playing with search the last few days, I'm thinking we may need to add some search related config settings. One for this issue (word separators) and one for language support (see #826). Possibly even one to disable search support altogether?

[1]: https://github.com/olivernn/lunr.js/blob/fa28620689e2050b92923d420413203db6c5a03f/lib/tokenizer.js#L23
[2]: https://github.com/mkdocs/mkdocs/blob/9a0451ae3e688d615e68a00e013b86947a8c4188/mkdocs/assets/search/mkdocs/js/search.js
[3]: https://github.com/mkdocs/mkdocs/compare/master...waylan:search
[4]: http://www.mkdocs.org/user-guide/configuration/#theme_dir

**Comment by waylan** [comment]
I'm switching the milestone for this issue to 1.0 as this would be part of the search refactor which I'm working on for 1.0 (see my previous comment).
