### ISSUE TITLE
Strikethrough

### ISSUE THREAD

**Issue by versedi** [mkdocs/mkdocs#868]
What do you think about adding a support for ~~striked text~~ by the same markdown as here?

<pre>
~~strike~~
</pre>

**Comment by Ralphilius** [comment]
It's possible with this 3rd party extension:
https://github.com/aleray/mdx_del_ins

**Comment by d0ugal** [comment]
Yup, we wont add this directly to MkDocs. To use that extension, do this:

    pip install mdx_del_int

**Note:** If you installed MkDocs via another method and not pip (like yum, homebrew or apt-get), you will likely need to install this extension in another way.

Then in your ``mkdocs.yaml`` add this.

    markdown_extensions:
        - del_ins

**Comment by versedi** [comment]
Didn't knew about that.
Everything's clear now, thank you!

**Comment by d0ugal** [comment]
Great, we probably need to do a better job at telling people about markdown extensions.

**Comment by pivaldi** [comment]
```txt
$ pip install mdx_del_int
Collecting mdx_del_int
  Could not find a version that satisfies the requirement mdx_del_int (from versions: )
No matching distribution found for mdx_del_int
```

but

```txt
$ pip install git+git://github.com/aleray/mdx_del_ins.git
Collecting git+git://github.com/aleray/mdx_del_ins.git
  Cloning git://github.com/aleray/mdx_del_ins.git to /tmp/pip-YVWmpj-build
Collecting Markdown>=2.0 (from mdx-del-ins===1.0)
Installing collected packages: Markdown, mdx-del-ins
  Running setup.py install for mdx-del-ins ... done
Successfully installed Markdown-2.6.7 mdx-del-ins-1.0
```

**Comment by facelessuser** [comment]
@pivaldi you can also try https://github.com/facelessuser/pymdown-extensions and specifically enable the [tilde extension](http://facelessuser.github.io/pymdown-extensions/extensions/tilde/).  You can configure it to do what you want and what you don't.   Just another option.  If you prefer `mdx_del_ins`, you may have to talk with that author about why his extension doesn't install proper.

**Comment by XtremeOwnageDotCom** [comment]
For.... anyone else who stumbles across this.... Here is the solution:

``` yaml
markdown_extensions:
  - pymdownx.tilde
```

[Documentation](https://facelessuser.github.io/pymdown-extensions/extensions/tilde/)

**Comment by NicoloCavalli95horses** [comment]
If you are like me and don't want to add any extension or install things, just use CSS:
`<span style="text-decoration: line-through;">wrong text </span>`
