### ISSUE TITLE
Tutorial screenshot appears to be out of date.

### ISSUE THREAD

**Issue by lanceleonard** [mkdocs/mkdocs#870]
When working [through the tutorial](http://www.mkdocs.org/#installation), ("Getting Started" section) the screen shot displaying the default index page is incorrect (presumably out of date).   (See on mkdocs, version 0.15.3, OS X and Windows.)

To reproduce:
1.  Create a new project as instructed in the first step of the tutorial.
2.  Change to the directory created for the new project.
3.  Run the serve command.
4.  Open your browser to http://127.0.0.1:8000 and note that the default index page is different than what's presented in [the screenshot](http://www.mkdocs.org/img/screenshot.png).

(Also, the sentence "Once you hit reload in the browser you'll see your new site name take effect." contains a typo.  It should be "Once you hit reload in the browser, you'll see your new site name take effect."  Rewriting the sentence to something along the lines of "Reload the page in your browser to see the new site name." may be even better.)

**Comment by waylan** [comment]
Interesting observation. The screenshots show example pages filled with [Lorem ipsum][1] filler text (well, actually "lorem markdownum"; presumably someones attempt at being cute :-1: ). However, the actual text displayed at that point in the tutorial is not that text. but a single line header: "Welcome to MkDocs" (see [mkdocs/commands/new.py#L9][2]).

The real question is: what should we change, the screenshots or the default text? The screenshots are definitely more attractive as they are today (they better demonstrate what pages could look like), but the the actual pages leave less for the user to replace/delete when they add some real content.



[1]: https://en.wikipedia.org/wiki/Lorem_ipsum
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/commands/new.py#L9

**Comment by waylan** [comment]
I also notice that a second page is already present in the first screenshot, but adding a second page isn't covered until later in the tutorial (with no screenshot provided at that point). Seems to me like the tutorial needs a little work in general.

**Comment by d0ugal** [comment]
> Seems to me like the tutorial needs a little work in general

+1
