### ISSUE TITLE
Allow pages to be configured in the docs\ folder

### ISSUE THREAD

**Issue by JakeGinnivan** [mkdocs/mkdocs#876]
Hey all,

I would like to have a `mkdocs.yml` _inside_ my /docs folder so I can just open the docs folder and edit from there rather than opening the root of the repo just so I can edit the mkdocs.yml file at the same time. This could either be with `'pages-config': 'docs/pages.yml'` or if there is a mkdocs file in the docs folder it gets merged with the parent or something.

I couldn't see anything which allowed that but it would be a really nice improvement.

**Comment by waylan** [comment]
As we've moved in the opposite direction in #996, I'm closing this.
