### ISSUE TITLE
Before build script

### ISSUE THREAD

**Issue by gsouf** [mkdocs/mkdocs#877]
Hi,

I use to work with ``mkdocs gh-deploy`` to publish documentation. It would be nice to have the ability to run custom scripts to add stuff to the generated content (as an example this npm package does it: https://github.com/meandavejustice/gh-pages-deploy)

In my case I want to add the auto-generated api doc to the gh-pages.

Is it something you want to see in mkdocs ?

**Comment by waylan** [comment]
This would be addressed by the Plugin API (see #206) if/when it becomes available. I'm closing this as a duplicate.

However, as a workaround, the `mkdocs gh-deploy` command is simply a wrapper around [ghp-import](/davisp/ghp-import), so you could write your own script which calls `mkdocs build` followed by your custom code and finishes with `ghp-import`.

**Comment by gsouf** [comment]
Good to know, thanks :+1:
