### ISSUE TITLE
Potential conflict with site from the standard lib

### ISSUE THREAD

**Issue by davidbgk** [mkdocs/mkdocs#878]
It took me quite some time to figure out why after a `mkdocs build` my virtualenv and even my whole python install were broken. It appears that the generated documentation is by default within the `site` directory and it conflicts with the [site module](https://docs.python.org/2/library/site.html) from the standard lib that is quite important to run python (to say the least :) ).

I'm not sure how to fix that except building in another default directory, a new clean install of my venv + new build resolve the issue. If you encounter the same issue, the command `python2.7 -c "import site; print site.__file__"` may help you understand what's going on.

**Comment by waylan** [comment]
As the Python [docs][1] state:

> The `__init__.py` files are required to make Python treat the directories as containing packages; this is done to prevent directories with a common name, such as `string`, from unintentionally hiding valid modules that occur later on the module search path.

In fact, I just tried it and, with a `site` directory built by MkDocs, I can `import site` just fine as my `site` directory does not contain an `__init__.py` file. Does yours?

If this is unavoidable on your system (either you have a legitimate need for a `__init__.py` file in your `site` dir or you have a weird system config), you can always change the name of the [`site_dir`][2] in your `mkdocs.yml` config file:

```yaml
site_dir: somethingthatisnotsite
```

[1]: https://docs.python.org/2/tutorial/modules.html#packages
[2]: http://www.mkdocs.org/user-guide/configuration/#site_dir

**Comment by davidbgk** [comment]
> Does yours?

Yes, the `mkdocs build` step generates a `__init__.py` file in my `site` directory.

**Comment by waylan** [comment]
Oh, I just remembered #807. This is a duplicate so I'm closing it..

**Comment by davidbgk** [comment]
I missed that one, thanks and sorry for the noise!
