### ISSUE TITLE
Better way to perform pre-processing on source md files / Support a custom directive "including" a path-specified file

### ISSUE THREAD

**Issue by ronjouch** [mkdocs/mkdocs#884]
Hi.

I'm working to improve the accessibility of a projects high-level doc (as opposed to docstrings-based per-class/method doc). It's already markdown-based, and I picked mkdocs because it does the job well. So as expected, I'm ending up with a `docs` folder at the root of the project, with a dozen `.md` files.

However, as part of *"improving the accessibility of high-level doc"*, we had a goal of bringing the doc as close as possible to the code. So in cases where it makes sense, we want high-level doc to be included directly in the code (c++ in our case) as comments, to minimize eventual doc/code de-synchronization: when the documentation is in your face *in the code*, it's easier to remember updating it when changing code.

To my knowledge this is not possible with mkdocs, so I ended up with a simple hackish pre-processing Python script that reads `mkdocs.yml` and, for each `.md` referenced in the `pages` section, looks for something like

```
!md_include path/to/some.cpp
```

... opens `path/to/some.cpp`, then finds

```
/** md
Awesome markdown-based doc on `some.cpp`.
*/
```

... and replaces the `!md_include` with the contents delimited by the special `/** md` ... `*/` multi-line comment. Pre-processed files are dumped to a temporary folder, from where the script then calls `mkdocs build` and calls it a day. This works well for us, except it's hackish and breaks `mkdocs serve`.

→ Do you see a better way of reaching the same result with the current mkdocs?  
→ If not, is there interest to add support for such custom pre-processing?

**Comment by waylan** [comment]
May I suggest taking a look at #777.

If that doesn't meet your needs, then I suspect this would need to wait for the Plugin API (see #206).

Either way, this would be a duplicate.

**Comment by ronjouch** [comment]
#777 doesn't cover my use case as I need to "extract" markdown content from files, not just include the whole files. Cool to see a plugin API is being thought of. Thanks for the fast answer @waylan :)

**Comment by facelessuser** [comment]
@ronjouch You could adapt the markdown-include extension listed in #777 by modifying it to suite your need.  You could have it include your source file(s) and then have the extension filter out the non relevant text leaving you only with your markdown source comments before inserting it into the body of the markdown file.  If that is still not doable, as @waylan said, you would need to wait for the Plugin API listed in #206.

**Comment by waylan** [comment]
Note that anything that would change the behavior of the Markdown parser would be implemented through an extension to the Markdown parser, which is already possible. For some guidance on building your own extensions, I would suggest starting with the [tutorial][1]. You can follow links from there for more documentation.

[1]: https://github.com/waylan/Python-Markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown

**Comment by ronjouch** [comment]
Good; thanks for the pointers @facelessuser @waylan.

**Comment by AndreasAZiegler** [comment]
@ronjouch I'm looking for exactly the functionality you mentioned. As since this issue was closed, quite some time passed, I wondering if you made any progress or if you can share your setup.
