### ISSUE TITLE
Meta variables are always arrays

### ISSUE THREAD

**Issue by gsouf** [mkdocs/mkdocs#885]
Hi, it seems that page meta variable is always an array of array. e.g:

```
foo: bar
baz: bar
```

This will export as follows:

```
{
  foo: [bar],
 baz: [bar]
}
```

This is what I was expecting:

```
{
  foo:  "bar",
 baz:  "bar"
}
```

The doc about meta is very short. I'm not sure if it's a bug or if it is the expected behavior.

**Comment by waylan** [comment]
The TOC is implemented simply by using the [TOC][1] extension which ships with Python-Markdown. That is the intended behavior of that extension (each line of the data is a new list item so a single line results in a list of 1 item). That extension was inspired by the [MetatData] feature of MuliMarkdown, which behaves the same way (at least it used to). So yes, this is the intended behavior.

I realize this is not always ideal. In fact, I have done some work on a potential solution [here][3]. However, that is not implemented as a Markdown extension, but as a preprocessor which would need or be called before Markdown. And then there is the need to define a type for each key. The keys which MkDocs uses are easy enough, but when users create their own keys, how should they define types? 

You can find some previous discussions about this in #300, #316 and #627. Personally, I would like to see MetaData switched to use YAML format, which gives us types for free. But that would be backward incompatible and potentially breaks hundreds/thousands of users sites. Therefore, I don't expect any change in the foreseeable future.

[1]: https://pythonhosted.org/Markdown/extensions/toc.html
[2]: http://fletcher.github.io/MultiMarkdown-5/metadata.html
[3]: https://github.com/waylan/docdata#multimarkdown-meta-data

**Comment by gsouf** [comment]
Yes, I though it was yaml. I understand the issue.
There is an other fact: true`` (bool) translates to ``"true"`` (string).

By the way I agree on the fact that it is not ideal, but the BC break is too important. Well, while we know it, it's ok, I'll take this in consideration!

Thanks
