### ISSUE TITLE
Incorrect syntax to center table column in user guide

### ISSUE THREAD

**Issue by filaton** [mkdocs/mkdocs#889]
**Description:**
In the section about [writing Markdown tables](http://www.mkdocs.org/user-guide/writing-your-docs/#tables), the described example produces an incorrect output (see the attached screenshot).

![screen shot 2016-04-11 at 20 24 59](https://cloud.githubusercontent.com/assets/6297260/14437977/1aea3b9a-0024-11e6-8723-30a7c8e49c22.png)

**Expected result:**
The second column of the table is centered.

**Current result:**
The second column of the table is left-aligned.

**Solution:**
Removing the whitespaces around the separator between table header and first row solves the problem.

**Attached file:**
- [index.txt](https://github.com/mkdocs/mkdocs/files/213638/index.txt): content to reproduce the problem

Mac OS 10.11.4
mkdocs v0.15.3
Python 2.7.11

**Comment by filaton** [comment]
I opened a PR fixing the behaviour in the documentation, but it's up to you to decide whether it's a Markdown processor bug or not. Using Discount/GFM locally produced correct results in both cases though…

**Comment by waylan** [comment]
If is was a Markdown bug, then it would need to be reported upstream to that [library][1]. However, as it stands, the Python-Markdown table extension is intended to be a clone of the behavior of [PHP Markdown Extra][1], which it is as-is. so not a bug.

In any event, thanks for the correction in the docs. Once the CI checks have finished running, I'll merge that.

[1]: https://github.com/waylan/Python-Markdown
[2]: https://michelf.ca/projects/php-markdown/extra/#table

**Comment by filaton** [comment]
Awesome, thanks!
