### ISSUE TITLE
CLI only mode; removing need for mkdocs.yml

### ISSUE THREAD

**Issue by anantshri** [mkdocs/mkdocs#893]
First of all awesome work. Where is donate button or buy me a beer button. This project deserves some.

Now to the issue, right now we need mkdocs.yml created however a basic file with 2 entries a site_name and a docs_dir Why not allow people to priovide the values via commandline and remove need of a file at all.

**Comment by waylan** [comment]
I can't speak to the original decision (it was made long before I came along), but personally I find the idea rather disagreeable. With a config file, I can set it and forget it. I don't need to remember what the `site_name` and the `docs_dir` is every time I need to build. Sure, you could hard-code that into a bash script (or makefile, etc), but then why not just have a config file?

If anything, removing the need for the config file could be dangerous. Suppose a user inadvertently deleted/moved their config file. An automated build would not raise an error and they might not notice their carefully crafted configuration hasn't been applied to the latest build which was then automatically uploaded to their live site. I'm sure a solution could be devised (perhaps the lack of a `site_name` would still raise an error in that scenario), but uhg.

In any event, the decision is not mine to make.

**Comment by d0ugal** [comment]
I have considered removing the requirement for a config for some time as I agree, it feels weird when it only contains a site_name. I think I mentioned it in my EuroPython talk last year. However, I can think of three points that mean I don't want to remove it.

- Much of the code is based around the fact that a config file exists. While this is just a lame legacy reason, it means the effort to change is higher and thus the benefit needs to be higher than the cost.
- You almost always want a config file, only really trivial documentation projects tend to get away without one. Most people want to add a markdown plugin, sort the pages or enable one of the other features (like google analytics.)
- In OpenStack we are actually in the process of moving to a config file, we went down the route of an overloaded command (granted, quite a different command line tool - but lessons when designing a CLI interface apply). In some ways it is nice, but generally it just led to gross long CLI commands with many flags that look much better in a config.
- @waylan's comment is also very convincing.

So, yeah, we will keep it for now.
