### ISSUE TITLE
Webfont served as Content-Type:text/html

### ISSUE THREAD

**Issue by waylan** [mkdocs/mkdocs#897]
On my windows box, I'm getting the following response for http://127.0.0.1:8000/fonts/fontawesome-webfont.woff2?v=4.5.0:

```
HTTP/1.1 200 OK
Date: Thu, 14 Apr 2016 13:53:51 GMT
Content-Length: 54
Etag: "b6dacbdf4965e9ad9022d26da2bcccea6759244a"
Content-Type: text/html
Server: TornadoServer/4.1
```

Notice that the `Content-Type` is `text/html` while it [should be](https://dev.w3.org/webfonts/WOFF2/spec/#IMT) `font/woff2`.

This may be something that should be addressed upstream, but I wanted to record it here.

**Comment by d0ugal** [comment]
Yup, this sounds like an upstream python-livereload (or maybe even Tornado?) issue.

**Comment by waylan** [comment]
Digging into this, it looks like we will need to address this locally. Tornado's position is that they use the `mimeypes` module in the standard lib, and so they won't override that (see tornadoweb/tornado#1690 and tornadoweb/tornado#1077).

The question is: how should we address this? There are a few possibilities:

1. We could use `mimetypes.add_type()` to globally (per Python process) add/override the the mime type for the relevant file types.

2. We could subclass the `StaticFileHandler` subclass provided by livereload to special case this type.

3. We could require Windows users to edit their registry to ensure the proper types are assigned on their systems.

I'm not crazy about any of the above but am leaning towards 1. That said, 3 would be acceptable for the simple reason that that requires us to do nothing. Like Tornado, we could take the position that we are not responsible for improperly configured systems.

**Comment by waylan** [comment]
Weird, when I serve the build dir using `SimpleHTTPServer` (from the Python standard lib with default settings), I get the following response:

    Content-Length:66624
    Content-type:application/octet-stream
    Date:Thu, 28 Apr 2016 14:57:49 GMT
    Last-Modified:Thu, 28 Apr 2016 14:23:47 GMT
    Server:SimpleHTTP/0.6 Python/2.7.1


Notably, the content type is `application/octet-stream`, which the browser (Chrome) displays correctly. And this is on the same Windows system. So I got curious:

```python
>>> mimetypes.guess_type('font.woff2')
(None, None)
>>> mimetypes.guess_type('font.woff2', strict=False)
(None, None)
```

Apparently Tornado's fallback when a type is unknown is the problem. In fact, `SimpleHTTPServer` is [defining][1] its own default: `application/octet-stream`.

[1]: https://hg.python.org/cpython/file/2.7/Lib/SimpleHTTPServer.py#l222

**Comment by waylan** [comment]
Even stranger, Tornado also [defaults][1] to `application/octet-stream` for unknown types. And I don't see any indication that [lepture/python-livereload][2] modifies/overrides that part of Tornado's static file server.

[1]: https://github.com/tornadoweb/tornado/blob/master/tornado/web.py#L2589
[2]: /lepture/python-livereload

**Comment by waylan** [comment]
All of the following files are being returned as `Content-Type:text/html` on Windows by the included dev server:

```
fonts/fontawesome-webfont.woff2
fonts/fontawesome-webfont.woff
fonts/fontawesome-webfont.ttf
mkdocs/js/search-results-template.mustache
mkdocs/search_index.json
```

But with `SimpleHTTPServer` they all return `Content-Type:application/octet-stream`. While different types might be preferred, in Chrome (at least), everything works with `application/octet-stream`. Not so much with `text/html`. At the very least the fonts don't work -- the json (should be `application/json`?) and mustache (should be `text/template`?) files seem to still work fine.

**Comment by waylan** [comment]
For future reference, here are instructions on how to manually set Content Types on Windows system-wide: <http://stackoverflow.com/a/3452261/866026>.

**Comment by waylan** [comment]
Turns out this is LiveReload's fault. If I run the dev server with `--no-livereload` everything works properly. I've filed a ticket at lepture/python-livereload#135

**Comment by d0ugal** [comment]
Thanks for investigating this, great detective work. I think given the dependancy issue we are unlikely to resolve this in 0.16 unless we can work around it somehow. I'll leave it on the milestone for now, but wont consider it a blocker.

**Comment by emceebigk** [comment]
I've run into a similar issue running mkdocs on an ubuntu server, accessing from os x. Using the --no-live-reload option does not help in this case. The mime time for woff2 is text/html, while regular woff is coming back fine as application/x-font-woff

```
General
Request URL:http://docs.skyward.io/fonts/fontawesome-webfont.woff2?v=4.5.0
Request Method:GET
Status Code:404 Not Found
Remote Address:52.35.233.179:80

Response Headers
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Date: Wed, 22 Jun 2016 16:17:05 GMT
Server: TornadoServer/4.2.1
Content-Length: 69
Connection: keep-alive

Request Headers
GET /fonts/fontawesome-webfont.woff2?v=4.5.0 HTTP/1.1
Host: docs.skyward.io
Connection: keep-alive
Cache-Control: max-age=0
Origin: http://docs.skyward.io
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Accept: */*
Referer: http://docs.skyward.io/css/font-awesome-4.5.0.css
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

**Comment by waylan** [comment]
@emceebigk that appears to be an unrelated issue. Note that the response is returning `HTTP/1.1 404 Not Found` and a "not found" response should be `text/html`. Your issue seems to be that the server is not finding the `fontawesome-webfont.woff` file and therefore is not returning it at all. In this issue, we are addressing files which are found and returned, but with the wrong content type. You have an unrelated issue. I would suggest addressing it separately,

**Comment by emceebigk** [comment]
Ah ok thank you for the clarification.

**Comment by waylan** [comment]
The PR at lepture/python-livereload#136 was merged, but no idea when that will be released. When it is, we should set that version as a new minimum dependency (at [setup.py#L63][1] and [requirements/project.txt#L3][2]). I'm leaving this open to remind us.

[1]: https://github.com/mkdocs/mkdocs/blob/master/setup.py#L63
[2]: https://github.com/mkdocs/mkdocs/blob/master/requirements/project.txt#L3
