### ISSUE TITLE
Parent pages

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#9]
Pass a list of `parent_pages` into the context.
Use this in the `readthedocs` theme to populate breadcrumbs.

Should be an object with `.title` and `.url`

**Comment by Mopster** [comment]
This will fix the breadcrumbs for level 2 pages in the 'readthedocs' template ?

**Comment by d0ugal** [comment]
Yup, that's the plan - I'll be looking at this tomorrow.
