### ISSUE TITLE
per page customization

### ISSUE THREAD

**Issue by anantshri** [mkdocs/mkdocs#900]
Example there is a specific page where i want the ToC to either be not present or collapsible. i am not a ui specialist and hence a simpler solution i was looking at was some sort of options in per md page where i can say something like toc=no and toc doesn't gets added to it.

So is it possible or i will need to spend time in getting a new theme worked out for it.

**Comment by waylan** [comment]
Page meta-data is passed to the template under the `meta` variable. You would just need to provide a template which made use of it. While overriding templates is currently possible, more work needs to be done both to make it easier and to document what is possible. See #607 for the details.

I suspect anything outside of that would need to wait for the as-yet unimplemented Plugin API (see #206).

**Comment by anantshri** [comment]
Thanks for the pointer will check them out.
Also is there a way to remove one of the default plugin's in mkdocs (meta, toc, tables, and fenced_code).

I am most probably trying to find a way with minimal tweaks in core mkdocs stuff or files coz with auto builds that basically means more tweaking and testing of build environment and more chances of failure.

**Comment by d0ugal** [comment]
> Also is there a way to remove one of the default plugin's in mkdocs (meta, toc, tables, and fenced_code).

No, not at the moment. Some of these are required for MkDocs to work, I have not experimented with disabling any. Are they causing a problem?

**Comment by anantshri** [comment]
@d0ugal toc is something i wanted to remove for a specific project of mine. but i think i will end up creating a custom theme for it.

**Comment by d0ugal** [comment]
Yup, makes sense. I think the toc extension is the one we rely on the most :smile:

**Comment by anantshri** [comment]
i think this simple pull request should add this feature in default set and yet doesn't impact much https://github.com/mkdocs/mkdocs/pull/917
