### ISSUE TITLE
documenting "feature"-files (gherkin)

### ISSUE THREAD

**Issue by VinzentE** [mkdocs/mkdocs#905]
Hi there,

I was wondering if anyone knows an easy way to document a bunch of feature files - ideally with mkdocs & markdown.
What I found so far is "pickles" - but that seems to be only for windows.

Thanks for your help

**Comment by d0ugal** [comment]
What do you mean by documenting a "bunch of feature files"?

**Comment by VinzentE** [comment]
For each "feature" in gherkin we create one file with the ending .feature - let's say we have 50 of them. How could I have them all somehow integrated in mkdocs for integrating them in the rest of the documentation but still maintaing them as .feature files?

**Comment by d0ugal** [comment]
Oh, I see. I have no idea what format that file is but I guess you could write a custom Python-markdown plugin and enable that in the MkDocs settings.
