### ISSUE TITLE
Prepare 0.16 release

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#907]
I have created a [milestone](https://github.com/mkdocs/mkdocs/milestones/0.16), we just need to add outstanding issues to it that we want to fix soon. (@waylan I'd be interested in knowing what you think should be added to this, as you have been more in touch with things lately.) So far I have just added a few documentation tasks that I would like to tackle.

Ideally I would like to make this the last release before working towards a 1.0 and fixing some of our larger and longer standing issues that will require breaking compatibility. However, I am not sure I will have the time to dedicate to that yet - but wishful thinking etc.

**Comment by waylan** [comment]
I think anything labeled [bug] which is not related to search could be a candidate. I'm excluding search related bugs because I think the entire search functionality needs a refactor (see #859 & #826) which should solve all of those bugs and more.

[bug]: https://github.com/mkdocs/mkdocs/issues?q=is%3Aissue+is%3Aopen+label%3ABug

**Comment by d0ugal** [comment]
Okay, cool - I have added all of the bugs to the milestone (except for #859 and #826). They may not all be fixed for that release, but I'll at least assess each of them individually over the next week or so.

**Comment by waylan** [comment]
By my estimation, the 0.16 release should be about ready. A couple PRs on the milestone need review (#1026 and #1027). With those resolved, we have two remaining issues: #897 is an upstream problem and already determined to be non-blocking (see [comment][1]) and #842 is a path related issue on Windows/cygwin. Cygwin adds another whole level of complexity to paths (behavior is different on Windows python vs cygwin Python on the same system) and I'm inclined to consider this a non-blocking issue as well.

So if we could get another set of eyes on #1026 and #1027 I'll feel comfortable merging them and we should be ready to release 0.16.

[1]: https://github.com/mkdocs/mkdocs/issues/897#issuecomment-216979704

**Comment by waylan** [comment]
@d0ugal I believe 0.16 is ready for a release. The remaining open issues on the milestone are non-blocking. You can do a release anytime.

Note, that I would do it, but I can't deploy an update to the docs myself.

**Comment by d0ugal** [comment]
Okay, amazing. Thank you so much for all the work you have done.

I'll dedicate some time tomorrow to try a few things out, catch up and then do the release.

You should be able to do the docs update - can't you push to the gh-pages branch? We should resolve that at the same time.

**Comment by waylan** [comment]
Oh right, I suppose I can push to the gh-pages branch. I don't use gh-pages for my own projects, so I forget I don't need any extra permissions for that. The issue would be with PyPI, bit that is automated by Travis, so no problem there.

**Comment by d0ugal** [comment]
Yup, so 'mkdocs gh-deploy' should do it. However, the process hasn't been tested that often - so it might be best to trigger it when I'm at a computer should any manual steps be required.

If you want to try, go for it or I will tomorrow.

**Comment by styfle** [comment]
Woohoo! 🎉 
Lookin' forward to this release 💯

**Comment by d0ugal** [comment]
It is live! Thanks everyone and particularly @waylan for making this release happen!

**Comment by d0ugal** [comment]
If you would like to help spread the word, retweets would be appreciated: https://twitter.com/MkDocsProject/status/794543620036657152
