### ISSUE TITLE
MkDocs working in a sub-uri

### ISSUE THREAD

**Issue by PeGa** [mkdocs/mkdocs#908]
I'm unable to find a way to make MkDocs work in a sub-uri with nginx as a reverse proxy.

This is what I've done so far:

## Nginx side
> Nginx v1.8.1 on Gentoo GNU/Linux
```
        location /kb {
                proxy_pass http://127.0.0.1:8000/;
}
```

## MkDocs side
> MkDocs 0.15.3 installed via package repository without containerization nor virtualization

### mkdocs.yml
```
site_name: My KB
theme: slate
site_url: https://example.org/kb
docs_dir: customers/
```

### Running mkdocs
``` 
$ mkdocs build --clean                                                                                                                                
WARNING -  Config value: 'theme'. Warning: The theme 'slate' will be removed in an upcoming MkDocs release. See http://www.mkdocs.org/about/release-notes/ for more details 
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /var/lib/mkdocs/customers/docs/site 
$ mkdocs serve                                                                                                                                        
INFO    -  Building documentation... 
WARNING -  Config value: 'theme'. Warning: The theme 'slate' will be removed in an upcoming MkDocs release. See http://www.mkdocs.org/about/release-notes/ for more details 
INFO    -  Cleaning site directory 
Serving on http://127.0.0.1:8000
```

## What else I tried

I've been playing with the site_url, docs_dir and site_dir without visible success.

## What works
I can access mkdocs in /kb sub-uri and I see some controls and the welcome text.

## What does not
Apparently all formatting assets (css, js, images, etc) are loaded from /, so when I open the browser network console I see a lot of 404 occurrences e.g. pointing to /css and to /js.

How can I make MkDocs serve the whole site in a sub-uri?

**Comment by d0ugal** [comment]
`mkdocs serve` is intended for development purposes only and should **not** be used in combination with nginx or in production in any way.

Instead you should take the output from `mkdocs build` and have nginx serve that static content.
