### ISSUE TITLE
How to use fontawesome-markdown 

### ISSUE THREAD

**Issue by bwmarrin** [mkdocs/mkdocs#909]
Is it possible to configure MkDocs to include this plugin?  I tried adding the name to the markdown_extensions setting but that didn't seem to work.

It would be nice, because the bootstrap themes already include font-awesome and having an easy way to use the icons would be wonderful.

https://pypi.python.org/pypi/fontawesome-markdown

**Comment by waylan** [comment]
Did you install the package? Simply including it in your config will not install it (and will likely raise an error if it is not installed).

Regardless, the font file included with MkDocs is a small subset of the characters in FontAwesome; specifically the subset of characters used by the theme. That said, you could potentially download your own more complete font files to include in the `custom_theme` directory to override the default files.

**Comment by bwmarrin** [comment]
Yes, I did install it using pip. :)

Hmn, I didn't consider that it wouldn't have all the fonts but it did have the few I tried using the normal `<i class="..."></i>` markup.

**Comment by waylan** [comment]
When you say it didn't work, what do you mean? How did it not work? Can you provide some sample input and the HTML output? What is being displayed in your browser? Is the browser raising any errors?

**Comment by bwmarrin** [comment]
Sure thing, sorry I should have started with that.  I'll send the output when I'm at a computer again.

When I run mkdocs build or serve it gives an error saying it can't find the package to import.  That's why I though maybe I just didn't know the right syntax for the config file.

**Comment by waylan** [comment]
Hmm, I'm not sure as the most recent version wasn't tagged, but it appears that the latest version ([0.2.5]) was released five days before the [commit] which made it possible to include the extension by string name.  In other words, if you installed version 0.2.5, you have to import and initiate the Python class. Whereas the HEAD of the master branch (and presumably the next release) would support using the string name: `fontawesome_markdown`.

You have a few options:

1. Wait for the next release of fontawesome_markdown. At that time you can install/upgrade via the following command:

        pip install -U fontawesome_markdown

    Then, in your config file do:

         - python_extensions:
            - fontawesome_markdown

2. Install the development version of the extension directly from GitHub. Of course, this is not an officially supported release and may not be appropriate for a production environment.  Regardless, the following command should get things installed for you:

        pip install https://github.com/bmcorser/fontawesome-markdown/archive/master.zip

    Then in your config file do:

        - python_extensions:
            - fontawesome_markdown

3. Continue to use the current release of the extension, which would be installed via normal:

        pip install fontawesome-markdown

    And then you would use a dirty little trick in the config file to load the extension:

        - python_extensions:
            - !!python/object:fontawesome_markdown.FontAwesomeExtension

    Although, I'm not sure that would even work. You need to pass in an instance of the class, and all that does is give you the class itself, not an instance.

Personally, I would recommend option 1, with option 2 as an alternate if you are desperate.


[0.2.5]: https://github.com/bmcorser/fontawesome-markdown/commit/28b410659ad6aef54183bbbe1e476c3c309888a3
[commit]: https://github.com/bmcorser/fontawesome-markdown/commit/90db7ae2652aded2bb2c26a162288b080c0610f6

**Comment by bwmarrin** [comment]
Wow, thanks @waylan that's super helpful info.  I'll give 2 a try for now then switch to 1 when it comes out.   Thanks for all the info and I'll report back once I get a chance to test it out, probably tomorrow.

**Comment by brianjking** [comment]
@bwmarrin I tried out Option #2 from @waylan's excellent response above and receive errors when running `mkdocs build` or `mkdocs serve` locally or if attempting to run these commands via `Travis-CI`.

Any luck?

**Comment by bwmarrin** [comment]
Well, I did get lucky I suppose :)

Here's an example:
http://bwmarrin.github.io/MkDocsPlus/fontawesome/

The code can be found here:
https://github.com/bwmarrin/MkDocsPlus

**Comment by waylan** [comment]
I'm closing this as there does not appear to be any actionable item here. The support question appears to be resolved.
