### ISSUE TITLE
YAML 'pages' key returning 404

### ISSUE THREAD

**Issue by stingclaw** [mkdocs/mkdocs#916]
I'm trying to name my pages in YAML, with the exact same structure as on the website (see below), but it keeps returning a 404 for the key, instead of the value.

```
pages:
- Page Title: 'page-title.md'
```
or,
```
pages:
- 'Page Title': 'page-title.md'
```

When I switch them around, it doesn't register the right page name, nor does it read the Jekyll title, all of which the documentation claims it can do. Thanks!

Jekyll title:
```
---
title: Page Title
---
```

**Comment by d0ugal** [comment]
You need an `index.md` for the home page, you can view that one by going to `/page-title/`. We need to make this clearer in the documentation.

Where does the documentation claim we support reading Jekyll titles? That has never been a feature.

**Comment by waylan** [comment]
> You need an `index.md` for the home page, you can view that one by going to `/page-title/`. We need to make this clearer in the documentation.

I'd say that is made clear enough [here][1].

[1]: http://www.mkdocs.org/user-guide/writing-your-docs/#file-layout

**Comment by d0ugal** [comment]
Good point. Closing this but feel free to ask more questions or continue discussion!
