### ISSUE TITLE
build docs from setup.py 

### ISSUE THREAD

**Issue by williamjmorenor** [mkdocs/mkdocs#918]
Hi 

I was looking at the setup.py file of https://github.com/mfenniak/pg8000 and it uses a setup_command to expose a  python setup.py build_sphinx options to setup.

Looking at sphinx source code for setup_command (0) look like mkdocs can implement a similar oproach to let users builds the documentation with a setup.py options (something like python setup.py mkdocs).

I am not sure if this feature interests to mkdocs core team, but maybe I can take a time to work in a setup_command implementation for mkdocs, even try to get it for the 0.16.0 release.

Regards

(0): https://github.com/sphinx-doc/sphinx/blob/master/sphinx/setup_command.py

**Comment by waylan** [comment]
Whether we add it to MkDocs proper or not, I'm sure it would be helpful to others. I see that Sphinx [registers][1] their `build_sphinx` command with the `distutils.commands` entry point. That makes it easy for people to use it. I would be interested in a similar `build_mkdocs` command if was not already written. 

[1]: https://github.com/sphinx-doc/sphinx/blob/master/setup.py#L209

**Comment by waylan** [comment]
As a reminder, review the comments in #919 when working on this.

Although, I am questioning the value of this. Initially I noted that this could be useful. Presumably, a developer could document their Python project with MkDocs and add a line to their `setup.py` script to add a `build_mkdocs` command for their users to build the documentation to their project. While that sounds like a nice feature (using standard Python tools, etc), the command would fail if the user didn't have the dependencies installed (namely MkDocs). Sure, a nice error message could be issued telling the user to install the dependencies, but that still seems less than ideal to me. Note that the same problem exists with the cited example for building documentation with Sphinx. It only works if the user has the dependencies installed. Sure, a properly configured `setup.py` script will auto-install dependencies for the package, but that would mean the developer would need to list MkDocs as a dependency and the dependencies would need to be installed before the build script is run (I don't recall off-hand which order things are done s that may or may not work).

What I'm sure about is that getting the user to install the dependencies manually is a larger hurdle than getting them to run the `mkdocs build` command directly.

**Comment by oprypin** [comment]
`setup.py` is dead :slightly_smiling_face:  :tada: 
* #2988
