### ISSUE TITLE
navbar links to /folder instead of linking to folder/index.html

### ISSUE THREAD

**Issue by kostnermo** [mkdocs/mkdocs#926]
At the moment the navbar links to folders which represent the markdown files. This is sufficient if you host your docs on a websever which searches for a */index.html within that folder. 

If you open the docs locally (i.e. Windows), the browser isn't able to retrieve the /index.html which makes the doc difficult to use. 
It could be easily solve by adding a /index.html after every link in the navbar (it actually already the case in the sidebar).
If, for any reason, this intentionally the case, it could be triggered by a command in the mkdocs.yml 

This is not a bug but rather a suggestion for an enhancement for local usage.

**Comment by waylan** [comment]
Does setting [`use_directory_urls`][1] to `false` in your config file resolve this for you?

[1]: http://www.mkdocs.org/user-guide/configuration/#use_directory_urls

**Comment by d0ugal** [comment]
Yes it will 🙂

**Comment by kostnermo** [comment]
It did. My bad, I even did some googling on how to trigger this but couldn't find it.

**Comment by JonasGroeger** [comment]
@kostnermo Shit Kostner, geht ganz schön ab, was :P

**Comment by ltworf** [comment]
Well I googled and this is the 1st result

**Comment by feldentm** [comment]
is there a good reason for not having this as the default?
