### ISSUE TITLE
Document different installation methods

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#932]
Currently we tell everyone to do a sudo pip install which isn't ideal for all users. This could be documented with yum, dnf, apt-get, using a virtualenv or some combination of these.

**Comment by waylan** [comment]
So then you would like to add something like the following:

> Or install MkDocs using the package management system of your choice (apt-get, yum, dnf, etc). Please see the documentation for your specific system for details.

Not sure what else we should add. Providing an example command for each tool means we know what the package is called in that system's repository. Unless you are creating and submitting the files to those repositories yourself, you don't have control over that. And then some offer support for multiple different Python versions and have naming conventions to designate which version works with which. It can get complicated fast.

And finally, regarding virutalenv. If someone is using virtualenv, then it seems to me that virtualenv should be providing documentation for how to install in an environment (activate and don't use sudo, etc). Generally, I expect virtualenv users to already know this as they are more likely to be advanced users.

**Comment by d0ugal** [comment]
Yup, that's a fair summary of the situation. Just referencing/linking out to the alternative sources would be fine with me.

I raised this issue after I was asked about it on IRC.

**Comment by d0ugal** [comment]
The problems when installing in Windows came up recently in #957. It would be good to take that into account when revamping the install guide.

**Comment by waylan** [comment]
The windows issues have been addressed in #1028. 

I'll leave this open to remind us to add something for system specific package managers.
