### ISSUE TITLE
403 is not in root static directory [Windows10]

### ISSUE THREAD

**Issue by Nightbr** [mkdocs/mkdocs#936]
Hi,

I have an issue with Mkdocs v0.15.3 (python 2.7, pip 8.1.2) on Windows 10 (I haven't the problem on my Linux Mint).
When I use `mkdocs serve`, I can view properly the index.md but all others pages are broken.

I get a 403 error on JS and CSS assets.

Console debug:

![cmder](https://cloud.githubusercontent.com/assets/4228646/15206386/0e34969e-181f-11e6-8298-d2ead8f246f5.PNG)

Browser debug:

![browser](https://cloud.githubusercontent.com/assets/4228646/15206414/44d18306-181f-11e6-86ef-93b82fa75cea.PNG)

I have made some research and I found two interesting things:

- [StackOverflow Link](http://stackoverflow.com/questions/17662878/hosting-static-file-for-download-python-tornado)
- [Tornado StaticFileHandler](https://gist.github.com/didip/902931)

It seems that the tornado server doesn't authorize to get static content if you don't explicitly wrote it.

`To map a path to this handler for a static data directory /var/www,
    you would add a line to your application like:
        application = web.Application([
            (r"/static/(.*)", web.StaticFileHandler, {"path": "/var/www"}),
        ])
    The local root directory of the content should be passed as the "path"
    argument to the handler.`

If anyone has a solution or a workaround, it is quite annoying when you wrote your doc ^^"

If you want more information, don't hesitate to ask me.

Thanks

**Comment by d0ugal** [comment]
Interesting. I believe we do have a number of users having success on Windows, so I'm not sure what is different with your setup.

**Comment by d0ugal** [comment]
Although, it sounds like this could be related to #897.

**Comment by Nightbr** [comment]
I tried with `mkdocs serve --no-livereload` and same issue.
Also I verified my mimetype and I have proper mimetype for .js, .css ...

![mime](https://cloud.githubusercontent.com/assets/4228646/15207229/f2afa570-1824-11e6-89f5-799517c857ac.PNG)

Add to that, the error correspond to this [error](https://gist.github.com/didip/902931#file-tornado-static-file-py-L33).

I have tested on a PC on Windows 7 and it works fine... Really weird

**Comment by d0ugal** [comment]
Interesting, perhaps it is Windows 10 specific. I'm not sure how many users we have there.

**Comment by Nightbr** [comment]
Wait & see if others have the same issue... I will inspect deeper if I can find something else.

**Comment by d0ugal** [comment]
Labelled this as "Needs information" - not necessarily from the reporter, we just need more information in general as we don't have a way forward with this.

**Comment by Nightbr** [comment]
Hey,
I update Python to the version 2.7.12 and everything works... Seems to be a bug with Python.
Thanks for your time guys ;)
Closed

**Comment by Akanksha0919** [comment]
I am facing 403 forbidden issue with mkdocs
the individual htmls for different modules are working fine but the sandwich icon showing all "pages" gives 403 forbidden error
image

![image](https://github.com/mkdocs/mkdocs/assets/65400521/f82ae222-677d-4199-a238-b93c3390837d)


all the links have their own index.html which works fine but the page links on sandwich icon don't work. what do you think , is this the issue of permissions? because in mkdocs.yml file i have the following code :
site_name: dynamic pricing documentation

theme:
name: "material"

nav:

Intro Docs: index.md
evaluation documentation: evaluation.md
metrics documentation: metrics.md
plugins:

mkdocstrings
I think the only thing that is crucial to connecting to these md pages is the nav and plugin: mkdocstrings

how can i resolve this 403 forbidden error

**Comment by pawamoy** [comment]
Hmmm, you seem to be serving your site from Jupyter? I don't think that is supported. I'd suggest you open a new discussion with all your setup (especially how your build/serve your site), to see if there's actually an issue first.

**Comment by Akanksha0919** [comment]
> Hmmm, you seem to be serving your site from Jupyter? I don't think that is supported. I'd suggest you open a new discussion with all your setup (especially how your build/serve your site), to see if there's actually an issue first.

It worked from my local jupyterlab. this version that's not working is from GCP hosted Jupyterlab. so can this be a jupyter server permission issue on GCP side? mkdocs works fine from my local system jupyterlab

**Comment by Akanksha0919** [comment]
Also my mkdocs build doesn't have any warnings or errors, it is build successfully. but still the links are broken on the sandwich icon for the "pages"

**Comment by pawamoy** [comment]
> so can this be a jupyter server permission issue on GCP side?

Yes, it definitely looks like an issue with how your site is served.
