### ISSUE TITLE
Option of using different lunr stemmers.

### ISSUE THREAD

**Issue by qwemaze** [mkdocs/mkdocs#937]
So the problem is search in non-English language.

I've managed to enable it by editing `docs/mkdocs/js/search.js` file and adding extra `docs/mkdocs/js/lunr.stemmer.support.js` and `docs/mkdocs/js/lunr.ru.js`  for Russian language support, but on any next build I'll have to do it again by some 'post-build' script which is sucks.

If get things right the assets for this is in `mkdocs/mkdocs/assets/search/mkdocs/js/search.js`. We could include there *like* all available `lunr` stemmers and in `search.js` require and use only ones that are mentioned in `mkdocs.yml` by some special option.

**Comment by d0ugal** [comment]
Yup, this is a known limitation. See primarily #826 but also #625 #617 and #211 for related discussions.
