### ISSUE TITLE
Feature request: Unique ID for tables

### ISSUE THREAD

**Issue by viewty** [mkdocs/mkdocs#941]
Hi all,

Just an idea from this morning while doing a few bits with some extra css and extra js - could you add a way to put a unique ID on a table? Would allow different tables to be styled individually.

At the moment it's quite messy but can be done by using js to find the table by looking for a unique combination of `<th>My</th><th>First</th>Table</th>` and traversing up to add an ID to the `<table>`.

Maybe something like:
```
| [first] My | First | Table |
|----        |----   |----   |
...
```
Results in `<table id="first">...`

Appreciate this would be a fairly unique extension to markdown but who knows, it could get more widely adopted :)

Edit: Not unique it seems, kramdown has it: http://stackoverflow.com/questions/14732028/add-id-or-class-to-markdown-element

Although their implementation is more general - you can add a class or an id to almost anything using `{.some_class}` or `{#some_id}`

**Comment by d0ugal** [comment]
This is something that can be created as a python-markdown extension outside of MkDocs, I don't believe this idea belongs in MkDocs itself.

For what it is worth, I think you can achieve part of what you want with this CSS.

    table tr:first-child td {
        // This would be the first colum in the 
    }

There is also the [attr_list](https://pythonhosted.org/Markdown/extensions/attr_list.html) extension that does a similar thing to Kramdown.

**Comment by viewty** [comment]
Ah yes that makes more sense. I'll look there. Thanks

**Comment by viewty** [comment]
Just for records, if any one else is trying to achieve this, solved by using a bit of javascript with a css selector.

```
<div id="marker"></div>
| Some | Table | Here
|----   |---- |----
| A | row | here
```
Put an empty div immediately before the table in the markdown. Then some javascript on DOMContentLoaded:
```
document.querySelector('#marker ~ div table').setAttribute("id", "test");
```
Could also be done by referencing the `<div class="data">` before the table but if more than one on the page that might get messy. Using the marker and traversing the data div would let you ID each table one by one.

**Comment by abubelinha** [comment]
@viewty I tried this but I don't understand your syntax.
`document.querySelector('#marker ~ div table').setAttribute("id", "test");` 
What does ` ~ div table` do? Is that supposed to work in all browsers?

This is what worked for me:
`document.querySelector('#marker').nextElementSibling.setAttribute("id", "test");`

Example taken from here:
https://stackoverflow.com/questions/11475232/find-the-element-before-and-after-a-specific-element-with-pure-javascript/11475290#11475290
@abubelinha
