### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by huegelc** [mkdocs/mkdocs#945]
Hi, 

is there a way to have the "Search,Previous,Next" strings translated without hacking the theme code?
Like a extra option in mkdocs.yml

Thank you

**Comment by d0ugal** [comment]
No, not at the moment. This would require a custom theme. See #617 and #211 for more discussion.

**Comment by huegelc** [comment]
Yes, I´ ve seen that here: http://squidfunk.github.io/mkdocs-material/getting-started/

**Comment by d0ugal** [comment]
That might be something specific to that theme.
