### ISSUE TITLE
Question about TOC

### ISSUE THREAD

**Issue by huegelc** [mkdocs/mkdocs#951]
Hi,

is there a way to have a TOC including all pages build by `MkDocs` ? For instance I have following page setup:
+ Home: 'index.md'
+Projects:
      + 'Project 1': 'projects/project1.md'
      + 'Project 2': 'projects/project2.md'

and on the index page i would like to have the summary of all pages.

Thank you.

**Comment by d0ugal** [comment]
No, I don't think this is possible without making a custom theme.

**Comment by waylan** [comment]
What do you mean by TOC? If you are referring to the "nav", then yes, there is a list of all pages with their titles and URLs which is available in the [nav][1] global variable. However, if you are referring to the page specific "TOC", the list of headings and subheadings in a page, then no, that is a [page context variable][2] and only available for the given page, not all pages. See the [documentation][3] for more info. All of the available variables are listed along with the global vs. page context status.

[1]: http://www.mkdocs.org/user-guide/custom-themes/#nav
[2]: http://www.mkdocs.org/user-guide/custom-themes/#toc
[3]: http://www.mkdocs.org/user-guide/custom-themes/#global-context

**Comment by huegelc** [comment]
Yes I meant the page specific TOC. Ok, I understand. I thought it would be the same as with restructuredtext where I could define a TOC tree spanning multiple pages http://www.sphinx-doc.org/en/stable/markup/toctree.html

**Comment by huegelc** [comment]
Speaking of which: how can the TOC be disabled on specific pages? Would be nice if it could be done from mkdocs.yml instead of CSS

**Comment by waylan** [comment]
> I thought it would be the same as with restructuredtext where I could define a TOC tree spanning multiple pages http://www.sphinx-doc.org/en/stable/markup/toctree.html

There was some work on that in the past (#627) which was abandoned for reasons I don't recall.

> Speaking of which: how can the TOC be disabled on specific pages? Would be nice if it could be done from mkdocs.yml instead of CSS

Actually this can be done via theme customization--no additional config settings necessary. See 947, which is a work in progress (especially the documentation should be helpful). For historical reasons the TOC and the main body content are under the same block, but the `content` block doesn't contain too much so it shouldn't be too much of a problem to override the entire thing. For that matter, at least in the `mkdocs` theme, the content is also broken out into a separate file so it is overridable prior to 947 being merged (see 4bb0c1cb for some documentation on that).

**Comment by huegelc** [comment]
Thank you

**Comment by waylan** [comment]
I'm closing this as this appears to be a support question and no actionable item exists.
