### ISSUE TITLE
Load jquery at the top of themes.

### ISSUE THREAD

**Issue by bwmarrin** [mkdocs/mkdocs#956]
Hi! I'd like to propose that MkDocs themes and the bootstrap themes switch to loading jquery at the top of the page (or before user content is added) instead of at the bottom.  This matches the behavior of the readthedocs theme.  

This change would allow users to use jquery within their documents to spice things up, like many of the examples shown here http://bwmarrin.github.io/MkDocsPlus/

Please also see this related issue here : https://github.com/bwmarrin/MkDocsPlus/issues/2
I waited a bit to see if the OP for the above issue wanted to push this issue up over here but it looks like he's vanished.  I still think this is a good change if it doesn't somehow cause other problems.

**Comment by d0ugal** [comment]
I would be happy for this change to happen. We can only add this to the mkdocs theme here. The others need to be handled in their repos

https://github.com/mkdocs/mkdocs-bootswatch
https://github.com/mkdocs/mkdocs-bootstrap

**Comment by bwmarrin** [comment]
I created tickets in those repos as well :)

**Comment by waylan** [comment]
Just a warning/reminder when someone implements this. Be ware of the recent changes where blocks were added to the template (#947). All JavaScript should be wrapped in the `scripts` block in the template. This is accomplished in the readthedocs theme, so its possible. Just didn't want it to be overlooked.

Although, it may be better to have two blocks. Maybe we should add a `libs` block which loads JavaScript libraries at the top and only use the `scripts` block at the bottom for scripts which take action on the page after page load. But this would require a way to distinguish between libraries and scripts. If we do this, is should be now before the template changes get released.
