### ISSUE TITLE
minor correction to tutorial

### ISSUE THREAD

**Issue by makruger** [mkdocs/mkdocs#958]
Was following: http://www.mkdocs.org/#adding-pages and noticed the url used by curl didn't work. Looks like the URL may have begun using https since this tutorial was written.

Didn't work:

curl 'jaspervdj.be/lorem-markdownum/markdown.txt' > docs/about.md

works: 

curl 'https://jaspervdj.be/lorem-markdownum/markdown.txt' > docs/about.md

**Comment by waylan** [comment]
This was fixed in fe40c9d and will be available with the next release.
