### ISSUE TITLE
mkdocs not reading level 3 header?

### ISSUE THREAD

**Issue by imtehrookie** [mkdocs/mkdocs#961]
Hey,
 So I can get the right output when I do
`## header 2`
and it will come out as a second level header
but when I do 
`### header 3`
it comes out as "###header 3" still with the hashes attached. I thought mkdocs supported up to level 6 headers?

Thanks in advance!

**Comment by d0ugal** [comment]
Sure, we do. You can see a third and fourth level here: http://www.mkdocs.org/about/release-notes/#major-additions-to-version-0150

The source is here: https://github.com/mkdocs/mkdocs/blob/master/docs/about/release-notes.md

You'll need to show us a full example or something. What version of MkDocs do you have?

**Comment by imtehrookie** [comment]
Here is a screenshot for an example. I am running mkdocs 0.15.3. It is also not doing it for fourth level as well. 
<img width="548" alt="screen shot 2016-06-13 at 11 52 40 am" src="https://cloud.githubusercontent.com/assets/8965095/16013997/6d6238b8-315d-11e6-9934-dfb38fdb282d.png">

**Comment by imtehrookie** [comment]
Hey just found the problem. I had a space before the #s. Forgive me, new to markdown.

**Comment by waylan** [comment]
@imtehrookie, the screenshot is not helpful.  We need to see the Markdown source text and possibly the HTML code which is generated (you can use "view source" from a right-click in your browser to get the HTML).
