### ISSUE TITLE
No theme working other than mkdocs and readthedocs

### ISSUE THREAD

**Issue by thexavier666** [mkdocs/mkdocs#962]
My yml file
```
site_name: My Site
theme_dir: custom
pages:
- Home: index.md
theme: material
```

Contents of my directory
`custom  docs  mkdocs.yml  moveToApace.sh  site`

`custom` consists of the theme material

**Comment by waylan** [comment]
Some more thorough documentation will be added in the next release alone with some feature additions (see #911 and #947). 

In short, the value assigned to `theme` must be a known registered theme or `null`. If you are building your own custom theme in the directory assigned to `theme_dir` that is not extending an existing theme, then you should set `theme` to `null`.

**Comment by thexavier666** [comment]
Thanks. I changed `theme` to `null` and it's working now.

In case someone has got stuck like me
* put the contents of the theme folder into `custom`
* set `theme_dir` as `custom`
* set `theme` as `null`

See the OP for reference
