### ISSUE TITLE
mkdocs command does not appear in path

### ISSUE THREAD

**Issue by ThomasMentzel** [mkdocs/mkdocs#965]
After installing mkdocs with pip, the command is not part of the path. I use a boxstarter (powershell) script to install python, update pip and install mkdocs. The script is executed as administator.

    cinst python
    python -m pip install --upgrade pip
    pip install mkdocs

Afterwards mkdocs.exe is not part of the path environment variable.

Workaround so far: Add the path manually to the path environment variable. Boxstarter:

    $env:PATH = $env:PATH + ";c:\ProgramData\chocolatey\lib\python3\tools\Scripts"
    [Environment]::SetEnvironmentVariable("PATH", $env:PATH, "Machine")

Unfortunately this might be a python issue.

---

_Environment:_

Windows 8.1 (Version 6.3 Build 9600)
Python 3.5.1
pip 8.1.2 from c:\programdata\chocolatey\lib\python3\tools\lib\site-packages (python 3.5)
mkdocs, version 0.15.3

**Comment by d0ugal** [comment]
Yeah, I think this is a Python oddity when using Windows. Unfortunately (or fortunately!) I don't use windows, so I don't know how best to document this. We have an open issue (about documenting the install in general) https://github.com/mkdocs/mkdocs/issues/932#issuecomment-224344467 which would cover this.

We don't know what the best practice is when installing on Windows, but we do want to document that if we can find somebody with the expertise. It might be that including the workaround you mentioned is all we need, bit I'm not sure.

**Comment by d0ugal** [comment]
I'm going to close this. I think this is only something we can improve with Documentation. Unless we write a native installer, which I would like to do some day.

For now, we should work on the docs. https://github.com/mkdocs/mkdocs/issues/932

**Comment by favorstar892738** [comment]
hope this helpfull to you.
python -m mkdocs new .

**Comment by mamadoudiop-code** [comment]
mkdocs is installed in this path, you have to add it on the path in environmental variable C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts

**Comment by fdtaljaard** [comment]
My issue was adminstrative rights

**Comment by Atlas-Night-Out** [comment]
> mkdocs is installed in this path, you have to add it on the path in environmental variable C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts

whic directory is mkdocs installed too as pythom seem to have  different paths for each version

**Comment by pawamoy** [comment]
@Atlas-Night-Out you could try to type this in a Python interpreter to find out:

```python
import mkdocs
print(mkdocs.__file__)
```

**Comment by pawamoy** [comment]
Congrats on fixing your issue!! :tada:
