### ISSUE TITLE
../ Reference is not taking

### ISSUE THREAD

**Issue by rameshthoomu** [mkdocs/mkdocs#968]
My folder structure like below:

```
xyz.md
mkdocs.yml
docs/
      index.md
      xyz.md
``` 

-- Inside `xyz.md` I have given `../xyz.md`

On Readthedocs -- Instead of displaying what I have in xyz.md (root folder) I could see ../xyz.md. Could you please let me know how to fix this issue.

**Comment by d0ugal** [comment]
At the moment there is no way to reference a file outside of the docs folder that I know of.

**Comment by waylan** [comment]
I suspect this is an issue with ReadtheDocs as they use their own build process. You might want to file a report with them.
