### ISSUE TITLE
External theme does not appear in ReadtheDocs

### ISSUE THREAD

**Issue by aiboyles** [mkdocs/mkdocs#969]
I switched from the included ReadtheDocs theme to the United theme for my project. I did a `pip install mkdocs-bootswatch` for this theme, and changed `theme: readthedocs` to `theme: united` in my mkdocs.yml file.

However, although the project builds successfully in Read the Docs, the documentation retains the standard readthedocs theme. When I run it locally (using `mkdocs serve`), it appears correctly with the United theme.

Is there another line of code I should be tweaking somewhere? A requirements file I should add? How can I get the external theme to properly appear in the ReadtheDocs? And, can this be better documented to avoid confusion in future?

**Comment by waylan** [comment]
I believe this is a limitation of ReadtheDocs. They use their own build process separate from ours, which only supports the readthedocs theme. If you want to use a theme other than readthedocs, then you cannot host your documentation on ReadtheDocs. In any event, this is outside our control. You should take this issue up with ReadtheDocs.
