### ISSUE TITLE
"Removed in upcoming release" theme breaks strict mode

### ISSUE THREAD

**Issue by stjohnjohnson** [mkdocs/mkdocs#974]
I'm trying to use strict mode and the new external theme, but I'm getting blocked on the warning about it being removed in a future version.

What can I do to get around this?
```
$ pip list | grep mkdocs
mkdocs (0.15.3)
mkdocs-bootstrap (0.1.1)
mkdocs-bootswatch (0.4.0)
$ cat mkdocs.yml
site_name: test
strict: true
theme: yeti
$ mkdocs gh-deploy
WARNING -  Config value: 'theme'. Warning: The theme 'yeti' will be removed in an upcoming MkDocs release. See http://www.mkdocs.org/about/release-notes/ for more details

Aborted with 1 Configuration Warnings in 'strict' mode!

**Comment by waylan** [comment]
I don't think this is a use-case we considered. The bootstrap and bootswatch themes have already been broken out into separate packages. The warning is to inform users about that. The only change to be made in a future release is that those themes will not be updated/installed by default. The user will need to install them separately.

Of course, if you already know this, then the warning is no longer of use to you. However, there is no way to turn warnings off, so any warnings in strict mode will cause a failure. Unfortunately, at this time you will need to not use "strict mode." I'm not sure of how to address this going forward. We could make a change to the strict mode/warning, but the more sensible change would simply be to stop the themes from being installed by default, in which case the warning will be unnecessary and can be removed.

**Comment by stjohnjohnson** [comment]
Thanks for the quick reply, @waylan.  Yeah, I figured as such and have already removed strict mode in my own projects.

When do you think you will stop including the themes by default?  I know it was mentioned that the hope was in the 1.0 release.

**Comment by waylan** [comment]
As I understand it, the plan is for version 1.0 to be the next version after 0.16, which is in development now. However, there is no specific time-table for our releases except for "when its ready", so I can't say when that will happen.

**Comment by stjohnjohnson** [comment]
Awesome!  Thanks.

_you can close this if you'd like_

**Comment by d0ugal** [comment]
Closing this as I think there is nothing actionable. Thanks for the report.
