### ISSUE TITLE
Mkdocs-compatible wiki?

### ISSUE THREAD

**Issue by chris-hailstorm** [mkdocs/mkdocs#976]
We use Mkdocs heavily.  It's a wonderful tool.  Although the non-WYSIWIG approach isn't for everyone, I like to treat documentation as a versionable asset like code that we manage via source code control, and Mkdocs works well in that approach.

However there are also situations where it would make sense to have more of a type-and-go wiki approach, either because the user creating the content is less technical, or the content is more general and doesn't need to be versioned.

Is there a wiki that's especially well suited for use with Mkdocs, i.e. uses the same dialect of Markdown or otherwise easier to integrate and move content between the two systems?

**Comment by waylan** [comment]
MkDocs is a "static site generator" (no rendering of Markdown to HTML happens on the server), whereas, a Wiki, by its nature, is not (all Markdown is rendered to HTML by the server). A wiki is out-of-scope for MkDocs. I'm sure there are Wiki engines which use Python-Markdown, but I've never used any of them and can't make any specific recommendations. Sorry I can't be more helpful.

**Comment by d0ugal** [comment]
If you want a static site generator with a graphical interface, you may want to try [Lektor](https://www.getlektor.com/). I don't have much experience with it, but I hear good things.

**Comment by zhaoqingqing** [comment]
so that .
