### ISSUE TITLE
Build status badge is not functioning correctly

### ISSUE THREAD

**Issue by rameshthoomu** [mkdocs/mkdocs#977]
My mkdocs build is passing every time but on Readme, build status badge is showing in Red color. Also I observed in ReadTheDocs page, I could see latest build status badge in Green color. Could you please let me know why it is showing as failed.

**Comment by waylan** [comment]
It may just be a cache problem. Try refreshing the page and/or deleting your browser's cache/history.

If that doesn't help, your going to need to provide more info for us to help you. MkDocs doesn't have any specific build status badge support built in. Which services are you using to do your build, provide the badge, and host your docs? Can you point us to the actual project (if its publicly available)?

**Comment by d0ugal** [comment]
Yeah, so I suspect that you are looking at a ReadTheDocs build badge in your README which is being viewed on GitHub. If that is correct, GitHub caches it aggressively and it wont update very often.

This isn't something we can fix in MkDocs. I'll close this, but if I guessed badly, please add more info and we can reopen.
