### ISSUE TITLE
Can I include a HTML page in the output?

### ISSUE THREAD

**Issue by sztomi** [mkdocs/mkdocs#987]
I hope this is the right place to ask a question.

I would like to integrate my doxygen-generated documentation with the hand-written mkdocs. Doxygen doesn't have a markdown output and pandoc converts all doxygen-outputs in a very bad quality to markdown, so I can't do that. I was thinking I might be able to pull in the HTML output? I'd like to keep the mkdocs header and whatnot and just place the doxygen index.html as a page. Is this possible somehow?

**Comment by d0ugal** [comment]
This is sort-of possible. However, I am not sure how well it will turn out. Markdown allows you to put HTML in it, so you can just have a markdown file that is made up on HTML. That should work, but it is probably a bit of a hack.

If doxygen adds the full html document (i.e. html, head and body tags) it might not work well at all.

**Comment by waylan** [comment]
Note that we are working on a Plugin API which might allow something like this to do doable through a Plugin. See #206.

**Comment by calebwin** [comment]
Is there a way to do this now?

**Comment by waylan** [comment]
@calebwin, you can find a list of plugins on the [wiki][1].

However, you may not need a plugin. We recently added support for including links to non-pages in the [nav][2]. If you simply have some HTML pages in your `docs_dir` and want to include links to them in the nav, then just include the links in the `nav` config setting. However, if you want to do anything more complex, you will need a plugin.

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins
[2]: https://www.mkdocs.org/user-guide/configuration/#nav

**Comment by ggaabe** [comment]
is there a way to add it to the generated sitemap as well?
