### ISSUE TITLE
Edit on Github support

### ISSUE THREAD

**Issue by leastprivilege** [mkdocs/mkdocs#995]
When I add the `repo_url` to mkdocs.yml, I get the "Edit on Github" link - 

but this link always points to the static url I configured - how can I make this link point to the current document in my github repo for editing?

thanks!

**Comment by leastprivilege** [comment]
OK - sorry - I found the old threads about this.

So what I did is - added the two settings:

```
repo_url: https://github.com/identityserver/identityserver4/
edit_uri: blob/dev/docs/
```

Still the "Edit on Github" link points to my repo_url.

Does the readthedocs template support that - or do I need to change the template manually?

thanks

**Comment by leastprivilege** [comment]
OK - I also get this when building on RTD

`WARNING -  Config value: 'edit_uri'. Warning: Unrecognised configuration name: edit_uri`

Could someone point me to docs that describe how to implement that feature correctly?

**Comment by d0ugal** [comment]
It is in MkDocs master but not yet released. I think you are otherwise using it correctly.

**Comment by leastprivilege** [comment]
Thanks! Do you have an ETA?

**Comment by d0ugal** [comment]
No, sorry - no ETA at the moment. We got close to a release but I have found it hard to find time to dedicate to the project lately (work, travel, life, etc.)

**Comment by leastprivilege** [comment]
ok - understood.

Can I manually implement that feature?

**Comment by waylan** [comment]
You could install directly from master. Of course, as we are in-between releases, we can't guarantee stability. In other words, things may break between now and the next release. If you chose to go that root, you can download from here: https://github.com/mkdocs/mkdocs/archive/master.zip

**Comment by leastprivilege** [comment]
thanks - but RTD is building my docs - so they would need to upgrade.
