### ISSUE TITLE
Feature Request for Includes / Partials support

### ISSUE THREAD

**Issue by SusanthCom** [mkdocs/mkdocs#998]
Hi,

***Feature Request for Includes / Partials support***

I was looking for a way to include one markdown file within other markdown file :  ( Include / Partials support )

Found that :  [Markdown-Include](https://github.com/cmacmackin/markdown-include) for [Python-Markdown](https://pythonhosted.org/Markdown/) is having a simple syntax  `{!filename!}` for achieving this.

Along with this, there must be some mechanism to skip the included file getting rendered as a stand alone. Some file naming convention will help to identify them : say skip all files begin with `__` will do.

Hi friends, please let me know your thoughts...

Thank you.

**Comment by waylan** [comment]
All modifications to the Markdown parser should be handled as Markdown extensions outside of MkDocs. I would suggest you address this with the developer of the Markdown-Include extension. this is out-of-scope for MkDocs to address directly.

**Comment by SusanthCom** [comment]
@waylan Thanks for clarification. 

Include is already implemented as a [third party extension](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions) 
> [Markdown-Include (PyPI)](https://github.com/cmacmackin/markdown-include) Provides syntax which will include the contents of other files in the document, similarly to the \include{} command in LaTeX.

Am looking to enable it to get result via MkDocs. Installed it via `pip install markdown-include`
A searching for : ***which section of  of MkDocs  should i change to make it working.***

Thanks for your time.

**Comment by waylan** [comment]
See the [documentation][1] for configuring Python-Markdown extensions for use with MkDocs. Add the appropriate settings to your `mkdocs.yml` config file. The config file is in YAML, so no need to use Python.

[1]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by SusanthCom** [comment]
Executed Install steps from [this link](https://github.com/cmacmackin/markdown-include)

At Shell : 
`pip install markdown-include` 

successfully installed 👍 

file 📄  : `mkdocs.yml`  

```yml
site_name: MyMd
theme: mkdocs

markdown_extensions:
    - markdown_include.include:
        base_path: '/path/from/root/mymd/docs/'
    - smarty
    - toc:
        permalink: True
    - sane_lists
```

successfully started MkDocs server, (no errors listed) 👍 

file 📄 : `foo.md` 
```markdown
## Am Foo.md

Sample Contents from `foo.md`

* foo 1
* foo 2
* foo 3
```

file 📄 : `bar.md` 
```markdown
## Am Bar.md

Sample Contents from `bar.md`

* bar 1
* bar 2
* bar 3
```

file 📄 : `test.md` 
```markdown
## Am Test.md

{!foo.md!}

{!bar.md!}

Sample Contents from `test.md`

* test 1
* test 2
* test 3
```

Success 👍 
All three files get rendered via browser > http://192.168.0.12:8000/
> without `base_path: '/path/from/root/mymd/docs/'`  it ignores `{!foo.md!}` and  `{!bar.md!}`

---

Now need to hide `foo.md` and `bar.md` from rendering directly
Renamed files to : `foo.md.include` and `bar.md.include`

Inside file 📄 : `test.md`
>   `{!foo.md.include!}` and  `{!bar.md.include!}`

Success 👍 
> `foo.md.include` and `bar.md.include` is hidden from direct rendering !
> `test.md` now contains foo + bar + test contents !!!

Thanks to all members of **Markdown-Include** and **MkDocs**

Special thanks to  @waylan and @cmacmackin 

[MarkDown Include Doc](https://github.com/cmacmackin/markdown-include)
[MkDocs  Doc](http://www.mkdocs.org/user-guide/configuration/#markdown_extensions)
